Allow pods to send metrics to datadog
helm/charts pull request #1006
Opened 2017-05-05 00:13 UTC by apenney

[Not sure this is a great idea, but I wanted to see what people think about the idea.  I don't want to have to run lots and lots of dogstatsd containers!]

By using host networking and a nodeport, clusters running CNI can
use the downward API to send metrics to a single dogstatsd rather
than one per pod.

An example:

 - name: DATADOG_HOST
   valueFrom:
     fieldRef:
       fieldPath: spec.nodeName

Then just send metrics to $DATADOG_HOST:8125.

2017-05-05 12:37 UTC, sameersbn commented
@k8s-bot ok to test

2017-05-10 04:53 UTC, irabinovitch commented
Looks reasonable to me. @hkaj thoughts?

2017-05-10 08:40 UTC, xvello requested changes

2017-05-10 08:40 UTC, xvello commented on stable/datadog/templates/daemonset.yaml
> +          hostPort: 8125
I agree this is useful, but most deployments don't need it and enabling it by default might cause port conflicts on some setups.
I'd prefer to have it linked to a configuration option and disabled by default.

2017-05-10 08:40 UTC, xvello commented on stable/datadog/templates/daemonset.yaml
> +      hostNetwork: true
To be confirmed by someone more seasoned than me, but I think hostPort (having a port redirection to the container) is enough for this use case and hostNetwork (sharing the host's IP) is not necessary.

2017-05-10 09:21 UTC, hkaj commented
I think both changes are useful, but should be configurable and disabled by default.
Exposing the host port by default is a bit invasive, using host networking is also not necessary for most people. And I think here we can need one or the other options but not both at the same time.
If we use hostNetwork, exposing the port is redundant, if we project the port on the host, not sure sharing the host network is necessary.

2017-05-25 17:46 UTC, pierreozoux commented on stable/datadog/templates/daemonset.yaml
> +      hostNetwork: true
This is not needed, look at: https://github.com/kubernetes/heapster/issues/1586

2017-06-14 17:36 UTC, unguiculus commented
What's the status of this? Pleas update within the next week.

2017-07-05 22:10 UTC, viglesiasce commented
Closing as stale. Please re-open when you have time to address the comments.

2017-07-05 22:10 UTC, closed without merging