[stable/chartmuseum] fix permission denied for persistent volume with app version 0.8.0
helm/charts pull request #10082
Opened 2018-12-17 18:22 UTC by jdolitsky

#### What this PR does / why we need it:
New chartmuseum 0.8.0 runs as "chartmuseum" user, which breaks persistent volume. Adding updated default security context

#### Which issue this PR fixes
  - fixes https://github.com/helm/chartmuseum/issues/193

#### Special notes for your reviewer:
n/a

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-12-17 18:30 UTC, jdolitsky commented
@goruha can I get a review?

2018-12-17 19:22 UTC, paulczar requested changes
You may need to have this on a switch so it can be disabled.  Some clusters have DenySecurityContext enabled which would cause this to fail.

2018-12-17 20:48 UTC, goruha commented
@paulczar I guess it would be just ignored.
It enabled by default 
https://github.com/helm/charts/blob/master/stable/chartmuseum/templates/deployment.yaml

2018-12-17 20:48 UTC, goruha approved these changes

2018-12-17 20:49 UTC, goruha commented
\lgtm

2018-12-18 16:11 UTC, paulczar commented
for more context -

if the kubernetes cluster has this admission controller - https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#securitycontextdeny

then this chart with default values will not work.  I guess you could document that it can be turned off by overriding the values to be nil and that would be sufficient.

2018-12-19 21:07 UTC, paulczar approved these changes

2018-12-19 21:07 UTC, paulczar commented
/lgtm

2018-12-19 21:10 UTC, merged