Adding chart for cluster-autoscaler overprovisioning
helm/charts pull request #10100
Opened 2018-12-18 10:20 UTC by mmingorance-dh

#### What this PR does / why we need it:
This chart creates an easy way to overprovision a cluster.

#### Special notes for your reviewer:
This approach is the [current recommended method to achieve overprovisioning](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler).

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-12-18 10:32 UTC, mmingorance-dh commented
/assign @foxish

2019-01-10 10:59 UTC, max-rocket-internet commented
Or @prydonius or @sameersbn or @seanknox ? Thanks!

2019-01-17 16:45 UTC, unguiculus requested changes

2019-01-17 16:45 UTC, unguiculus commented on stable/cluster-overprovisioner/templates/priorityclass-default.yaml
> +  name: {{ .Values.priorityClassDefault.name }}
Could you apply the same naming logic for PriorityClasses as we suggest for service accounts using helper templates?

See https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md#using-rbac-resources

2019-01-17 16:56 UTC, unguiculus commented on stable/cluster-overprovisioner/templates/priorityclass-default.yaml
> +  name: {{ .Values.priorityClassDefault.name }}
Nevermind. I guess this doesn't make sense here.

2019-01-17 16:57 UTC, unguiculus approved these changes

2019-01-17 16:57 UTC, unguiculus commented
/ok-to-test

2019-01-17 17:53 UTC, mmingorance-dh commented
> @mmingorance-dh: The following test **failed**, say `/retest` to rerun them all:
> 
> Test name	Commit	Details	Rerun command
> pull-charts-e2e	[cf68cf5](https://github.com/helm/charts/commit/cf68cf5216ffc8eb5715f3dfbb06921a14dd792b)	[link](https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/helm_charts/10100/pull-charts-e2e/19156/)	`/test pull-charts-e2e`
> [Full PR test history](https://gubernator.k8s.io/pr/helm_charts/10100). [Your PR dashboard](https://gubernator.k8s.io/pr/mmingorance-dh). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/helm/charts/issues?q=is:issue+is:open) when you hit one in your PR.

Could this issue be related with `apiVersion` defined in the Chart?
I saw that PodPriority is now v1

2019-01-17 17:56 UTC, unguiculus commented
Might be due to our K8s version, which is still at 1.10. I'll try and get the test cluster updated soon.

2019-01-17 17:59 UTC, mmingorance-dh commented
We are currently running 1.10.6 with PodPriority feature enabled (as it's still on beta)

2019-01-18 15:03 UTC, max-rocket-internet commented
As per the README: `Kubernetes 1.11+ with Beta APIs enabled or 1.8-1.10 with alpha APIs enabled`

2019-01-22 10:10 UTC, unguiculus commented
/lgtm

2019-01-22 10:18 UTC, merged