adding SSL version option
helm/charts pull request #10176
Opened 2018-12-20 16:21 UTC by asloan7

#### What this PR does / why we need it:
to use AWS elasticsearch host, which uses SSL

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-12-20 16:31 UTC, asloan7 reviewed
adding version bump

2018-12-20 16:41 UTC, asloan7 commented
/assign @monotek

2018-12-20 17:44 UTC, monotek requested changes
Please put the TLS settings in "if scheme = https" statement so the TLS setting don't needs to be commented out in the values file.

2018-12-20 23:31 UTC, monotek requested changes
also fix your dco please

2018-12-20 23:31 UTC, monotek commented on stable/fluentd-elasticsearch/values.yaml
> +  scheme: http
please remove. its already there...

2018-12-20 23:31 UTC, monotek commented on stable/fluentd-elasticsearch/templates/daemonset.yaml
> +        {{- if eq .Values.elasticsearch.scheme "https" }}
sorry, lets remove the if statement again please.
otherwise we have an empty tls setting with http scheme

2018-12-20 23:31 UTC, monotek commented on stable/fluentd-elasticsearch/values.yaml
> +#  ssl_version: TLSv1_2
please comment that in

2018-12-21 19:42 UTC, monotek approved these changes

2018-12-21 19:43 UTC, monotek commented
/lgtm

2018-12-21 19:51 UTC, merged