[incubator/jaeger] fix hotrod demo application
helm/charts pull request #10175
Opened 2018-12-20 16:19 UTC by sebastien-prudhomme

Signed-off-by: Sébastien Prud'homme <sebastien.prudhomme@gmail.com>

#### What this PR does / why we need it:

Hotrod demo application not working with this chart

#### Which issue this PR fixes

  - fixes #10137, fixes #10138

fix also the name of the jaeger agent service

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

2019-01-07 09:12 UTC, sebastien-prudhomme commented
/assign @foxish

2019-01-08 00:25 UTC, pavelnikolov requested changes
LGTM. Just fix the version, please.

2019-01-08 00:25 UTC, pavelnikolov commented on incubator/jaeger/Chart.yaml
> +version: 0.8.1
Version `0.8.1` has already been [used](https://github.com/helm/charts/blob/master/incubator/jaeger/Chart.yaml#L5). 
Please, bump the version

2019-01-08 06:18 UTC, sebastien-prudhomme commented on incubator/jaeger/Chart.yaml
> +version: 0.8.1
Done

2019-01-09 05:40 UTC, merged