[stable/efs-provisioner] Add nodeselector, affinity, podAnnotations
helm/charts pull request #10205
Opened 2018-12-21 12:35 UTC by SweetOps

#### What this PR does / why we need it:

Adds `nodeSelector`, `affinity` to schedule pods in specific nodes and  `podAnnotations` to be able to annotate deployment. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-12-21 12:37 UTC, SweetOps commented
/assign @unguiculus

2018-12-21 21:08 UTC, whereisaaron commented
ref #9127 patch which is needed for newer k8s RBAC rules.

2018-12-21 21:19 UTC, whereisaaron commented
This of one of four PR's to add the same selector and/or pod annotations functionality to this chart (#10205, #10088, #10013, #9253), stuck in the backlog of unloved PRs 😢

2018-12-26 09:43 UTC, SweetOps commented
@whereisaaron , may be more PRs will help to speed up merging :) . You can close this PR, it nvm for me which PR will be merged - me just need that functionality

2018-12-26 19:11 UTC, whereisaaron commented
Maybe @SweetOps! 😀 I wasn’t making any suggestion as to which PRs should close or merge, just noting the slow review of PR’s leads to wasteful duplication of effort. You had to do the same work to improve chart as others before you, instead of being able to share your work in an easy, timely manner.

A more distributed system would be better I think. I made this original chart, yet I have no ability to maintain it. Now I watch it fall into neglect and disrepair while useful PRs like yours and important bug fixes like #9127 gather dust 😕

2019-01-04 13:37 UTC, unguiculus requested changes

2019-01-04 13:37 UTC, unguiculus commented on stable/efs-provisioner/values.yaml
> +# affinity: {}
```suggestion
affinity: {}
```

2019-01-04 13:37 UTC, unguiculus commented on stable/efs-provisioner/README.md
> +# affinity: {}
```suggestion
affinity: {}
```

2019-01-08 10:14 UTC, SweetOps commented on stable/efs-provisioner/values.yaml
> +# affinity: {}
has been uncommented as you requested

2019-01-08 10:15 UTC, SweetOps commented on stable/efs-provisioner/README.md
> +# affinity: {}
has been uncommented as you requested

2019-01-08 10:18 UTC, SweetOps commented
@unguiculus , please update your review

2019-02-04 19:35 UTC, unguiculus commented
/ok-to-test

2019-02-04 19:40 UTC, unguiculus approved these changes

2019-02-04 19:40 UTC, unguiculus commented
/lgtm

2019-02-04 19:42 UTC, merged

2019-05-05 09:07 UTC, whereisaaron commented
This merge appears to introduce two `annotations` sections to the Pod template,  where `.Value.annotations` will override `.Values.podAnnotations`, see #13494.