Add Eventrouter Chart
helm/charts pull request #1023
Opened 2017-05-08 15:28 UTC by rosskukulinski

This Pull Request adds an incubator chart for [Eventrouter](https://github.com/heptio/eventrouter).

The Eventrouter serves as an active watcher of _event_ resource in the kubernetes system, which takes those events and _pushes_ them to a user specified _sink_.  This is useful for a number of different purposes, but most notably long term behavioral analysis of your workloads running on your kubernetes cluster.

2017-05-08 15:31 UTC, rosskukulinski commented
I have signed the CLA

2017-05-08 17:00 UTC, rimusz commented
@rosskukulinski can you add `NOTES.txt` which explains waht to expect after the install, how to use/access it? e.g. https://github.com/kubernetes/charts/blob/master/stable/coredns/templates/NOTES.txt

2017-05-08 17:01 UTC, rimusz commented
@rosskukulinski please use `helmignore` which gets generated via `helm create ...` e.g. https://github.com/kubernetes/charts/blob/master/stable/coredns/.helmignore

2017-05-09 14:36 UTC, rosskukulinski commented
@rimusz updated based on your feedback

2017-05-09 15:01 UTC, rimusz commented
@rosskukulinski can you explain in more details in the `readme` how it leverages/uses existing EFK stacks? it is really unclear, thanks

2017-05-22 16:34 UTC, rosskukulinski commented
@rimusz sorry - this got lost while I was prepping for a conference talk.  Are you referring to the README for this chart or the upstream project README?

2017-05-22 16:45 UTC, rimusz commented
@rosskukulinski referring the chart one README, but also upstream project one should be have more info too.

2017-05-24 19:16 UTC, unguiculus requested changes
Thanks for adding this.

2017-05-24 19:16 UTC, unguiculus commented on incubator/eventrouter/Chart.yaml
> +home: "https://github.com/heptio/eventrouter"
Do you have an icon you could add here?

2017-05-24 19:16 UTC, unguiculus commented on incubator/eventrouter/templates/configmap.yaml
> +    heritage: {{.Release.Service | quote }}
`chart` label missing here. Please use `{{template "name" .}}` for the `app` label.

See https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md

Apply label changes everywhere.

2017-05-24 19:16 UTC, unguiculus commented on incubator/eventrouter/templates/configmap.yaml
> +  name: {{template "fullname" .}}
Please use consistent formatting everywhere:

Space after `{{` and before `}}`.

2017-05-24 19:16 UTC, unguiculus commented on incubator/eventrouter/templates/deployment.yaml
> +          - name: config-volume
Use consistent style for list indentation.

2017-05-24 19:16 UTC, unguiculus commented on incubator/eventrouter/values.yaml
> +namespace: "kube-system"
Any reason you code the namespace into the chart? This is rather uncommon.

2017-05-24 19:16 UTC, unguiculus commented on incubator/eventrouter/templates/deployment.yaml
> +          image: "{{default "gcr.io/heptio-images/eventrouter" .Values.image}}:{{default "latest" .Values.imageTag}}"
No need to specify defaults. They come from `values.yaml` anyways.

2017-05-24 19:16 UTC, unguiculus commented on incubator/eventrouter/templates/_helpers.tpl
> +{{/* vim: set filetype=mustache: */}}
Any reason why you changed the default implementation for `name` and `fullname`?

2017-06-08 05:51 UTC, lachie83 commented
@rosskukulinski do you have time to work getting this into shape?

2017-06-09 22:20 UTC, rosskukulinski commented on incubator/eventrouter/Chart.yaml
> +home: "https://github.com/heptio/eventrouter"
We do not have an icon at this time

2017-06-09 22:23 UTC, rosskukulinski commented on incubator/eventrouter/templates/_helpers.tpl
> +{{/* vim: set filetype=mustache: */}}
This file was taken directly from one of the example Charts in the docs (I forget which one).  If this isn't necessary, I'm happy to remove

2017-06-09 22:29 UTC, rosskukulinski commented
@lachie83 I do - Tweaked PR a bit today, need to polish improved Readme for this AND upstream.

2017-06-20 10:29 UTC, prydonius requested changes

2017-06-20 10:29 UTC, prydonius commented on incubator/eventrouter/templates/_helpers.tpl
> +{{/* vim: set filetype=mustache: */}}
@unguiculus updated the examples in the Helm docs, could you maybe update this file to use one from one of the existing charts in this repo?

2017-06-20 10:29 UTC, prydonius commented on incubator/eventrouter/values.yaml
> +namespace: "kube-system"
This isn't actually used, and Helm only allows you to specify the namespace using `helm install --namespace`, so I think this needs to be removed. If this needs to be installed into kube-system, you could add a note in the README or NOTES.txt

2017-06-20 10:29 UTC, prydonius commented on incubator/eventrouter/Chart.yaml
> +version: 0.1.0
add `appVersion: 0.1`

2017-07-20 17:57 UTC, unguiculus commented
Marking as stale. Please update within the next week.

2017-07-28 05:40 UTC, unguiculus commented
Closing as stale. Feel free to re-open if/when you decide to work on this again.

2017-07-28 05:40 UTC, closed without merging