add support for prometheus_rabbitmq_exporter plugin
helm/charts pull request #10280
Opened 2018-12-28 11:36 UTC by DXist

#### What this PR does / why we need it:
Allows to use Rabbitmq  [image](https://hub.docker.com/r/deadtrickster/rabbitmq_prometheus) with [prometheus_exporter](https://github.com/deadtrickster/prometheus_rabbitmq_exporter) plugin as alternative to [external exporter](https://github.com/kbudde/rabbitmq_exporter)

#### Special notes for your reviewer:

Chart user still needs to override rabbitmq image at the moment.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [Alpine image](https://github.com/deadtrickster/prometheus_rabbitmq_exporter/pull/66) of `rabbitmq_prometheus` is built and published
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-12-28 20:40 UTC, steven-sheehy requested changes
- Sign your commits
- Bump the version in Chart.yaml. Should be minor increase
- Add a section in README.md on how to configure the chart to use the exporter plugin. For example what image to set and custom servicemonitor.
- New variables not documented in README

2018-12-28 20:40 UTC, steven-sheehy commented on stable/rabbitmq-ha/values.yaml
> +    rabbitmq_plugin: false
I don't think this variable is needed and it's confusing since prometheus.exporter section is reserved for the sidecar container. Instead, you can just use the custom rabbitmq image that you need and create your own servicemonitor resource outside the chart.

2018-12-28 20:42 UTC, steven-sheehy commented
/assign @steven-sheehy

2018-12-29 08:49 UTC, DXist commented on stable/rabbitmq-ha/values.yaml
> +    rabbitmq_plugin: false
Ok, sounds reasonable.

2018-12-29 08:50 UTC, closed without merging