[stable/fluentd-elasticsearch] Add support for priorityClasses
helm/charts pull request #10285
Opened 2018-12-28 12:53 UTC by Art3mK

Signed-off-by: Art3mK <artem@kayalaynen.ru>

#### What this PR does / why we need it:

According to [this](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/) `scheduler.alpha.kubernetes.io/critical-pod` annotation is deprecated in 1.13 and will be removed in 1.14. This PR allows user to specify priority class for pods

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

ping @monotek

2018-12-28 12:55 UTC, Art3mK commented
/assing axdotl

2018-12-28 12:57 UTC, Art3mK commented
/assing @axdotl

2018-12-28 12:57 UTC, Art3mK commented
/assign @axdotl

2018-12-28 13:01 UTC, Art3mK commented
/assign @paulczar

2018-12-28 13:27 UTC, monotek requested changes

2018-12-28 13:27 UTC, monotek commented on stable/fluentd-elasticsearch/templates/daemonset.yaml
>          scheduler.alpha.kubernetes.io/critical-pod: ''
Imho we should put this in an if statement (enable if k8s version is below 1.13 via "Capabilities.KubeVersion") to be backwards compatible.

2018-12-28 13:27 UTC, monotek commented on stable/fluentd-elasticsearch/Chart.yaml
> +version: 2.0.4
please raise to 2.0.5. 
2.0.4 will be merged soon...

2018-12-28 13:55 UTC, Art3mK commented on stable/fluentd-elasticsearch/templates/daemonset.yaml
>          scheduler.alpha.kubernetes.io/critical-pod: ''
fixed!

2018-12-28 13:55 UTC, Art3mK commented on stable/fluentd-elasticsearch/Chart.yaml
> +version: 2.0.4
if you will merge some changes before that, then even if I bump my version to 2.0.5 it will still result in merge conflict?

2018-12-28 14:01 UTC, Art3mK commented on stable/fluentd-elasticsearch/Chart.yaml
> +version: 2.0.4
fixed

2019-01-07 07:01 UTC, Art3mK commented
I've rebased my branch and bumped chart version, @monotek, can you review, please?

2019-01-07 09:00 UTC, monotek commented
Hey @Art3mK

i'm sorry, but in the meantime we deprecated the chart here and moved it to the following repo:
https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch

This is also the repo you'll find if you search for it on https://hub.helm.sh .

Could you please add you pr there?

Thanks!

Regards
André

2019-01-07 12:17 UTC, Art3mK commented
new PR opened there -> https://github.com/kiwigrid/helm-charts/pull/11

2019-01-07 12:17 UTC, closed without merging