[stable/traefik] feat: add priorityClassName for pods
helm/charts pull request #10315
Opened 2018-12-31 10:14 UTC by Art3mK

Signed-off-by: Art3mK <artem@kayalaynen.ru>

#### What this PR does / why we need it:

This PR allows user to specify [PriorityClass](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) for traefik pods

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-12-31 10:16 UTC, Art3mK commented
/assign @dtomcej

2019-01-03 18:03 UTC, dtomcej requested changes

2019-01-03 18:03 UTC, dtomcej commented on stable/traefik/values.yaml
> +priorityClassName: ""
Can this be commented out by default?

2019-01-03 18:03 UTC, dtomcej commented on stable/traefik/templates/deployment.yaml
> +      priorityClassName: "{{ .Values.priorityClassName }}"
```suggestion
       priorityClassName: {{ .Values.priorityClassName | quote }}
```

2019-01-05 13:27 UTC, Art3mK commented on stable/traefik/values.yaml
> +priorityClassName: ""
all right, although it's not required, as `if` evaluates to false with empty strings

2019-01-05 13:27 UTC, Art3mK commented on stable/traefik/templates/deployment.yaml
> +      priorityClassName: "{{ .Values.priorityClassName }}"
done

2019-01-07 11:42 UTC, Art3mK commented
ping @dtomcej, or @mmatur maybe?

2019-01-07 14:05 UTC, dtomcej commented
/lgtm

2019-01-07 14:05 UTC, dtomcej commented
/approved

2019-01-07 14:12 UTC, merged