Allow pre-created secrets for external database credentials
helm/charts pull request #10340
Opened 2019-01-02 15:43 UTC by robbie-demuth

#### What this PR does / why we need it:

Previously, the chart required that users set the password for an external database via a value. This change allows users to instead provide the name of a pre-created secret containing the password

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2019-01-02 15:50 UTC, robbie-demuth commented
/assign @rjkernick

2019-01-03 14:33 UTC, robbie-demuth commented
/assign @sameersbn

2019-01-03 14:33 UTC, rjkernick commented
/ok-to-test

2019-01-03 14:37 UTC, rjkernick requested changes

2019-01-03 14:37 UTC, rjkernick commented on stable/sonarqube/Chart.yaml
> +version: 0.11.1
Please bump the minor version as this adds a feature

2019-01-03 14:37 UTC, rjkernick commented on stable/sonarqube/values.yaml
> +  # To use an external secret for the password for an external mySQL instance,
Please specify that enabled must be set to false for this to work

2019-01-03 14:37 UTC, rjkernick commented on stable/sonarqube/values.yaml
> +  # To use an external secret for the password for an external PostgreSQL
Please specify that enabled needs to be set to false

2019-01-07 13:52 UTC, rjkernick commented
Please merge the latest master branch and increment the version in Chart.yaml

2019-01-07 14:18 UTC, robbie-demuth commented
Done, @rjkernick

2019-01-07 14:55 UTC, rjkernick commented
One got merged ahead of you. Please merge the latest master and increment the version again.

2019-01-07 15:02 UTC, robbie-demuth commented
Done, @rjkernick

2019-01-07 19:38 UTC, merged