Update Kured chart to create Service for prometheus metrics
helm/charts pull request #10368
Opened 2019-01-03 11:44 UTC by razaj92

Signed-off-by: Raza Jhaveri <razajhaveri@googlemail.com>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2019-01-03 11:47 UTC, razaj92 commented
/assign @lachie83

2019-01-04 21:32 UTC, lachie83 commented
/ok-to-test

2019-01-04 21:35 UTC, lachie83 requested changes

2019-01-04 21:35 UTC, lachie83 commented on stable/kured/templates/daemonset.yaml
> +              containerPort: {{ .Values.service.port }}
Should the service.port and the containerPort always be the same thing? Is there a way to tell kured to run on a different port?

2019-01-15 18:50 UTC, davidkarlsen requested changes

2019-01-15 18:50 UTC, davidkarlsen commented on stable/kured/templates/service.yaml
> +    port: {{ default "8080" .Values.service.port }}
```suggestion
    port: {{ .Values.service.port }}
```
which is according to best practices

2019-02-28 20:15 UTC, closed without merging