[stable/memcached] Add pod annotations
helm/charts pull request #10371
Opened 2019-01-03 12:06 UTC by dkarnutsch

Signed-off-by: Daniel Karnutsch <d.karnutsch@gmail.com>

#### What this PR does / why we need it:
Add support for pod annotations.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-01-03 12:10 UTC, dkarnutsch commented
/assign @gtaylor

2019-01-03 15:21 UTC, olemarkus requested changes
Thanks for the PR. Just fix the version and it is good to go

2019-01-03 15:21 UTC, olemarkus commented on stable/memcached/Chart.yaml
> +version: 2.4.1
This is a new feature. Could you bump minor version?

2019-01-03 15:21 UTC, olemarkus commented
/assign

2019-01-03 15:21 UTC, olemarkus commented
/ok-to-test

2019-01-07 07:32 UTC, dkarnutsch commented
@olemarkus Thanks for your quick review! I've made the changes accordingly.

2019-01-07 07:35 UTC, olemarkus commented
Thanks!
/lgtm

2019-01-07 07:37 UTC, merged