[stable/lamp] updated documentation due to #8425, bumped various container versions to current stable
helm/charts pull request #10395
Opened 2019-01-04 11:48 UTC by lead4good

updated documentation due to #8425, bumped various container versions to current stable

2019-01-04 13:00 UTC, lead4good commented
/assign @paulczar

2019-01-09 15:47 UTC, paulczar requested changes
this looks pretty good, just a few nitpicks about pulling repo/tags from values rather than being hard coded.  I know that was pre-existing, but since we're updating them I think we should fix it up.

2019-01-09 15:47 UTC, paulczar commented on stable/lamp/templates/deployment.yaml
> +        image: "httpd:2.4-alpine"
we should probably pull this image repo and version from a value so it can be pulled from a non public repo.

2019-01-09 15:47 UTC, paulczar commented on stable/lamp/templates/deployment.yaml
> +        image: "php:{{ .Values.php.version }}-fpm-alpine"
we should probably pull this image repo from a value so it can be pulled from a non public repo.

2019-01-09 15:47 UTC, paulczar commented on stable/lamp/templates/deployment.yaml
> +        image: atmoz/sftp:alpine
we should probably pull this image repo and version from a value so it can be pulled from a non public repo.

2019-01-10 20:05 UTC, paulczar approved these changes

2019-01-10 20:12 UTC, paulczar requested changes
I appreciate that you took all the static images from the templates and turned them into values, however you've also merged the separate "image" (or repository) and "tag" values for each value in favor of just a single value.  most charts follow the convention of having the image name and the image vesion (or repo and tag) separate.

I think it makes sense to retain that, plus you've introduced breaking changes ( which in theory is okay because this is not a version 1, but in reality its in the stable repo so we should assume some amount of stability). 

I would recommend splitting the image name and version back out and then we can bump the version to `1.0.0` and get this released as a real genuine stable chart.

2019-01-10 20:12 UTC, paulczar commented on stable/lamp/README.md
> +| `init.manually.image` | Containers image | lead4good/init-wp:latest |
this would be a breaking change and would require semver bumped a full version (or at least a minor since this is a not even version 1 ).

2019-01-10 20:12 UTC, paulczar commented on stable/lamp/examples/drupal.yaml
> +  image: "drupal:fpm-alpine"
this would be a breaking change and would require semver bumped a full version (or at least a minor since this is a not even version 1 ).

2019-01-26 11:39 UTC, lead4good commented
Sorry for taking so long, please also merge #10365 asap since its a security fix

2019-01-26 15:18 UTC, paulczar commented
/lgtm

2019-01-26 15:25 UTC, merged