[stable/wordpress] Add service annotations
helm/charts pull request #10498
Opened 2019-01-09 13:54 UTC by clalbus

Signed-off-by: Andrejs Volkovs <clalbus@gmail.com>

#### What this PR does / why we need it:
Allows users to set service annotations.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-01-09 15:37 UTC, cpanato commented on stable/wordpress/Chart.yaml
> +version: 5.0.6
please bump to 5.1.0 since this is not a bug fix

2019-01-09 15:43 UTC, cpanato commented
/ok-to-test

2019-01-09 15:44 UTC, cpanato commented
/assign

2019-01-10 06:29 UTC, clalbus commented on stable/wordpress/Chart.yaml
> +version: 5.0.6
Done

2019-01-10 08:27 UTC, juan131 requested changes
Thanks so much for your contribution! Please take a look to my comments.

2019-01-10 08:27 UTC, juan131 commented on stable/wordpress/values.yaml
> +  annotations: {}
Could you please add the same parameter to `values-production.yaml`?

2019-01-10 08:43 UTC, clalbus commented on stable/wordpress/values.yaml
> +  annotations: {}
Added

2019-01-10 09:32 UTC, juan131 approved these changes
Thanks so much!

2019-01-10 09:32 UTC, juan131 commented
/lgtm
/ok-to-test

2019-01-10 09:39 UTC, merged