[stable/nats] metrics image registry takes value from global
helm/charts pull request #10555
Opened 2019-01-11 12:02 UTC by offzale

#### What this PR does / why we need it:
This chart uses two different images from docker.io registry. It is possible to override the value of each registry separately but in case you want to assign the sale value to both registries there is no way to do it by setting just a single value.

There is a `global.imageRegistry` parameter on the values file, but it just overrides the registry of the main container. Metrics container is not setting the registry depending on this global value. Which makes the global value quite useless.

This simple change in the helpers file will allow metrics container to set the registry of its image from the global parameter as well.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-01-11 15:26 UTC, sameersbn requested changes

2019-01-11 15:26 UTC, sameersbn commented on stable/nats/templates/_helpers.tpl
> +{{- end -}}
I believe you can simplify this with:

```
{{- if and .Values.global .Values.global.imageRegistry }}
    {{- printf "%s/%s:%s" .Values.global.imageRegistry $repositoryName $tag -}}
{{- else -}}
    {{- printf "%s/%s:%s" $registryName $repositoryName $tag -}}
{{- end -}}
```

2019-01-12 10:24 UTC, gzenrique commented on stable/nats/templates/_helpers.tpl
> +{{- end -}}
Thanks for the suggestion :) That works fine as long as you got `global` defined (and not empty) in the `values.yaml`file. If you don't, you get this error: 
```
Error: render error in "nats/templates/statefulset.yaml": template: nats/templates/_helpers.tpl:35:33: executing "nats.image" at <.Values.global.image...>: can't evaluate field imageRegistry in type interface {}
```
So, since `global` is an optional parameter in this chart, I believe we should keep the if-else syntax that makes possible you don't use any global values.

2019-01-14 06:25 UTC, sameersbn commented on stable/nats/templates/_helpers.tpl
> +{{- end -}}
yea, you're right

2019-01-14 06:25 UTC, sameersbn approved these changes
/ok-to-test
/lgtm

2019-01-14 06:32 UTC, merged