[stable/cert-manager] Add securityContext to cert-manager deployment pods
helm/charts pull request #10602
Opened 2019-01-14 07:53 UTC by tjakobsson

#### What this PR does / why we need it:

Adds the ability to run cert-manager deployment pods with a non-root user which enables cert manager to work with PodSecurityPolicy defaults.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-01-14 07:59 UTC, tjakobsson commented
/assign munnerz

2019-01-14 21:04 UTC, davidkarlsen requested changes

2019-01-14 21:04 UTC, davidkarlsen commented on stable/cert-manager/Chart.yaml
> +version: v0.5.3
```suggestion
version: v0.6.0
```
since it adds a feature

2019-01-15 18:29 UTC, davidkarlsen approved these changes

2019-01-16 06:50 UTC, tjakobsson commented
cc @mattfarina seems like other PRs suffered from the same failures on the e2e tests that Certificate, Issuer and ClusterIssuer CRDs are still hanging around since earlier tests. Also seen in PR #9329

2019-01-16 11:11 UTC, munnerz commented
Sorry to be a pain, could you please open this PR in the upstream jetstack/cert-manager repo?

We accept PRs over there and publish them here according to our own release schedule, which allows for more extensive e2e testing. There is a brief note about this in the chart's README, but perhaps we need to make this more prominent.

Re the chart test failures - yes this is an issue with Helm & the current testing environment - it happens pretty much all the time and there's nothing I can do about it 😢 whenever the CM chart is `helm install` and then `helm delete`'d during tests, it does not delete the CRD resources and so the tests will fail on second installation 😬 

/hold

2019-01-18 06:47 UTC, tjakobsson commented
@munnerz I've added a PR to jetstack/cert-manager instead, thank you.

2019-01-18 06:47 UTC, closed without merging