Harden elasticsearch chart for Kube 1.5
helm/charts pull request #1062
Opened 2017-05-11 23:29 UTC by icereval

Further extends upon PR https://github.com/kubernetes/charts/pull/890

* Added configmap to explicitly provide cluster configurations and scripts

* Replace depreciating `ES_HEAP_SIZE` with `ES_JAVA_OPTS` to position for ES v5 support

* Removed alpha storage class operators

* Removed catastrophic liveness probe checking entire clusters health

* Readiness probe now inspects local node health

* Added termination grace period (defaults to 15m) to allow pre-stop-script.sh time to gracefully migrate shards

* Added init container on data nodes to configure `vm.max_map_count`

* Updated elasticsearch.yaml:
  * Added `PROCESSOR` configuration to prevent large cluster garbage collection issues leading to node eviction
  * Added configurable gateway defaults to help avoid a split brain, requiring two masters online and in consensus before recovery can continue

* Updated pre-stop-script.sh:
  * Check `v1beta1` `statefulset` endpoint
  * Evalute `.spec.replicas` for statefulset desired size
  * Clear `_cluster/settings` ip exclusion prior to shutdown to avoid a possible (random) ip match scenario on expansion of the clsuter

* Data nodes now use default storage class if once is not specified

2017-05-12 06:45 UTC, unguiculus requested changes

2017-05-12 06:45 UTC, unguiculus commented on stable/elasticsearch/values.yaml
> +DataTerminationGracePeriodSeconds: 900
I would prefer to not move the chart to `stable` as long as config values start with an uppercase letter. In this case, I would also switch to nesting first. I think this make sense here, e. g.:

```yaml
client:
  replicas: 2
  port: 2379
  heapSize: "128m"
master:
  replicas: 2
  heapSize: "128m"
data:
  replicas: 3
  storage: "30Gi"
```

See https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/values.md

Generally, I think a move to stable should be a separate PR so it is explicit.

Regarding resources, it's becoming increasingly popular to specify resources like so (without specifying defaults): https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L93

2017-05-14 19:34 UTC, icereval commented on stable/elasticsearch/values.yaml
> +DataTerminationGracePeriodSeconds: 900
I completely agree and all are very good points. Would you mind informing the base PR https://github.com/kubernetes/charts/pull/890, if we can get this merged, even if still in incubator status one of us can follow up with a new PR with the final changes needed to make this `stable`.

2017-06-18 09:42 UTC, viglesiasce commented
@simonswine @unguiculus any update on this review? Were the latest changes enough to merge?

2017-06-18 12:30 UTC, unguiculus commented
As suggested in #890, a move to stable should only happen after applying best practices, e. g. regarding values. See https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/values.md.

2017-06-19 13:49 UTC, icereval commented
@unguiculus & @prydonius, rebase complete and a first pass at helm best practices applied to the incubator chart.

2017-06-20 15:39 UTC, unguiculus commented
Excellent. This goes in the right direction. Now, please have a look at `app` labels, which should be `{{ template "name" . }}`. Note that you will then have to add the `release` label to the selector in services. `nginx-ingress` an excellent example:

https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml#L6
https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml#L56-L58

2017-07-02 18:08 UTC, unguiculus commented
@icereval Are you working on an update?

2017-07-03 02:11 UTC, icereval commented
@unguiculus, yep, I'll have my updates ready soon

2017-07-03 03:37 UTC, icereval commented
@unguiculus, best practices changes pushed up

2017-07-04 19:15 UTC, unguiculus commented
Would you mind adding a NOTES.txt? Otherwise it looks nice but I have yet to review more thoroughly. I installed it on GKE and everything came up nicely.

2017-07-04 19:15 UTC, unguiculus commented
@k8s-bot ok to test

2017-07-04 20:44 UTC, icereval commented
Added NOTES.txt and `client.serviceType` based on review of the concourse stable chart.

2017-07-05 15:41 UTC, unguiculus approved these changes

2017-07-05 15:43 UTC, merged