Update rookout chart environment variables
helm/charts pull request #10634
Opened 2019-01-15 11:07 UTC by Zohar2506

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2019-01-15 11:08 UTC, Zohar2506 commented
/assign @prydonius

2019-01-15 20:36 UTC, davidkarlsen requested changes

2019-01-15 20:36 UTC, davidkarlsen commented on stable/rookout/Chart.yaml
> +appVersion: "0.2.3"
```suggestion
appVersion: "0.3.9"
```
which is the image tag?

2019-01-21 10:10 UTC, Zohar2506 commented
/davidkarlsen what else needs to be done to merge it?

2019-02-10 13:55 UTC, Zohar2506 commented
https://github.com/helm/charts/pull/11306

2019-02-10 13:55 UTC, closed without merging