Add scalyr
helm/charts pull request #1066
Opened 2017-05-12 16:28 UTC by pierreozoux

2017-05-22 18:35 UTC, unguiculus requested changes

2017-05-22 18:35 UTC, unguiculus commented on stable/scalyr/values.yaml
> +  tag: latest
Use a fixed version.

2017-05-22 18:35 UTC, unguiculus commented on stable/scalyr/templates/daemonset.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
Add missing labels. See https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md.

2017-05-23 11:15 UTC, pierreozoux commented
Thanks @unguiculus I addressed your comments.

2017-05-23 15:58 UTC, unguiculus requested changes
Thanks for the quick changes. I've found a few more things.

2017-05-23 15:58 UTC, unguiculus commented on stable/scalyr/templates/cm-agent.yaml
> +  name: {{ template "configuration.fullname" . }}
Is there a reason why you name the config map differently? I'd suggest to use `{{ template "fullname" . }}` as well.

2017-05-23 15:58 UTC, unguiculus commented on stable/scalyr/templates/secrets.yaml
> +  api-key: {{ default "MISSING" .Values.scalyr.apiKey | b64enc | quote }}
I don't know what makes more sense to you, but are you aware of the new `required` function? See https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#know-your-template-functions.

2017-05-23 15:58 UTC, unguiculus commented on stable/scalyr/values.yaml
> +resources:
Make resources configurable but do not specify defaults. This should be a conscious choice of the user.

2017-05-23 15:58 UTC, unguiculus commented on stable/scalyr/templates/daemonset.yaml
> +    app: {{ template "fullname" . }}
`{{ template "name" . }}` would be a better choice for the `app` label. I'd suggest you change it everywhere.

2017-05-23 16:02 UTC, unguiculus commented
I just tried to deploy the chart and got the following error:
```
$ helm install --name foo stable/scalyr
Error: render error in "scalyr/templates/NOTES.txt": template: scalyr/templates/NOTES.txt:1:14: executing "scalyr/templates/NOTES.txt" at <.Values.scalyr.apiKe...>: can't evaluate field apiKey in type interface {}
```
The same happens with `helm template stable/scalyr`.

2017-06-01 14:16 UTC, prydonius commented
@pierreozoux ping, can you update to address @unguiculus's comments?

2017-06-02 11:24 UTC, pierreozoux commented
@prydonius can we keep it on hold, I'm currently working for a client, and I want them to sign the CLA before continuing this task.

2017-06-21 17:28 UTC, pierreozoux commented
Addressed the comments thanks.
(And my current employer signed the CLA)

2017-06-24 15:45 UTC, unguiculus requested changes
Just found one more thing.

2017-06-24 15:45 UTC, unguiculus commented on stable/scalyr/templates/daemonset.yaml
> +        app: {{ template "fullname" . }}
Add release label: `release: "{{ .Release.Name }}"`

2017-06-30 15:47 UTC, pierreozoux commented on stable/scalyr/templates/daemonset.yaml
> +        app: {{ template "fullname" . }}
Ok, done

2017-07-20 19:31 UTC, unguiculus approved these changes

2017-07-20 19:32 UTC, unguiculus commented
@k8s-bot ok to test

2017-08-13 13:50 UTC, unguiculus commented
Sorry for the delay. It should be possible to run install the chart with defaults.

2017-09-28 19:11 UTC, unguiculus commented
Closing as stale. Feel free to reopen if/when you decide to work on this again.

2017-09-28 19:11 UTC, closed without merging

2019-05-07 16:05 UTC, scottrigby commented
@pierreozoux I drew from some of your earlier work for a new Scalyr Helm chart. Check out https://github.com/scalyr/scalyr-agent-2/issues/118#issuecomment-490135304 if you're still interested in this - always up for collaboration 😄