[stable/openvpn] add kubevpn simple CLI
helm/charts pull request #1068
Opened 2017-05-12 19:44 UTC by pfeodrippe

The pod now generates the kubevpn CLI so you don't overflow your terminal stack with so many lines. 
Copy once from the pod, use anywhere (if you want... with the correct kubectl context, of course)

2017-05-26 06:34 UTC, unguiculus commented
/cc @jfelten

2017-06-02 00:04 UTC, jfelten commented
nice! - Works like a charm
A couple things:
1.) Increment minor version in Chart.yaml
2.) Can you add a section in README.md that shows the kubevpn script in detail and how to use it. 

Otherwise looks good.

2017-06-02 02:57 UTC, pfeodrippe commented
@jfelten Version bumped.
What do you mean with a more detailed explanation? There is some script usage at the Readme already.

Thanks for the time to review it, man :)

2017-06-02 04:18 UTC, jfelten requested changes
I want a couple sentences that explain client cert generation a bit better.  Ex:

replace: "Be sure to change KEY_NAME if generatingto your client name to generate additional keys. Import the .ovpn file into your favorite openvpn tool like tunnelblick and verify connectivity."

with:
### Client Cert Generation

The above instructions copy a script locally that is used to generate client certificates.  It takes a single key name argument, $KEY_NAME, and outputs a .ovpn file that can be imported into any openvpn compatible client like tunnelblick.  Client key names ($KEY_NAME) MUST be unique.

2017-06-13 19:48 UTC, unguiculus commented
@pfeodrippe Are you going to come up with the suggested improvement?

2017-06-14 09:43 UTC, pfeodrippe commented
@unguiculus I'll catch on it until the next week... sorry for the delay

2017-07-18 00:25 UTC, viglesiasce commented
Closing as stale. Please re-open if/when you have a chance to work on this.

2017-07-18 00:25 UTC, closed without merging