Add prometheus-snmp-exporter chart
helm/charts pull request #10734
Opened 2019-01-17 15:05 UTC by Miouge1

#### What this PR does / why we need it:
Add prometheus-snmp-exporter chart

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-01-17 15:07 UTC, Miouge1 commented
@gianrubio and @mgoodness can you have a look at this?

2019-01-17 23:57 UTC, davidkarlsen requested changes
Please also follow https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md
See https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md for labels

Maybe some lines should be added to tell how to be able to scrape a given SNMP device? How to I make prometheus use this chart to scrape a given device's SNMP values?

2019-01-17 23:57 UTC, davidkarlsen commented on stable/prometheus-snmp-exporter/templates/deployment.yaml
> +apiVersion: apps/v1beta2
use v1

2019-01-18 09:48 UTC, Miouge1 commented on stable/prometheus-snmp-exporter/templates/deployment.yaml
> +apiVersion: apps/v1beta2
OK, fixed in latest commit.

2019-01-18 11:12 UTC, Miouge1 commented
@davidkarlsen thanks for the feedback, I didn't know about the new labels.

Have a look at the latest commit, i've added:
- RBAC and ServiceAccount
- new label format
- Documentation of Prometheus server configuration

2019-01-20 23:50 UTC, davidkarlsen approved these changes

2019-01-20 23:50 UTC, davidkarlsen commented
/lgtm

2019-01-20 23:58 UTC, merged