Add CoScale Helm Chart
helm/charts pull request #1076
Opened 2017-05-15 09:30 UTC by fryckbos

2017-06-01 11:03 UTC, prydonius commented
@fryckbos waiting on CLA, were you able to get this signed?

2017-06-02 07:05 UTC, fryckbos commented
@prydonius I forgot to link my CNCF user with my github account, I did this just now. Should the CLA check become green by itself or do I need to take additional actions ?

2017-06-02 07:31 UTC, prydonius commented
woot thanks @fryckbos

2017-06-02 07:36 UTC, prydonius requested changes
Thanks @fryckbos, just have a couple of comments

2017-06-02 07:36 UTC, prydonius commented on stable/coscale/values.yaml
> +    pullPolicy: "IfNotPresent"
It would be better to set the tag to a version (e.g. 3.7.0). If you need to use latest, the `pullPolicy` should be Always.

2017-06-02 07:36 UTC, prydonius commented on stable/coscale/Chart.yaml
> +version: 3.9.1
The version of CoScale should be in the `appVersion` field, `version` is the chart version and should be `0.1.0`.

2017-06-02 16:48 UTC, prydonius commented
@k8s-bot ok to test

2017-06-02 16:48 UTC, prydonius approved these changes

2017-06-02 16:51 UTC, prydonius commented
@fryckbos can you fix the lint error?

2017-06-03 06:32 UTC, fryckbos commented
@prydonius The linter passes now.

2017-06-14 20:29 UTC, unguiculus requested changes

2017-06-14 20:29 UTC, unguiculus commented on stable/coscale/templates/daemonset.yaml
> +    app: {{ template "fullname" . }}
The `app` labels should be `{{ template "name" . }}`. Apply everywhere.

2017-06-14 20:29 UTC, unguiculus commented on stable/coscale/values.yaml
> +resources:
We've started to recommend not specifying default resources. This should be a conscious choice of the user.

2017-06-14 20:29 UTC, unguiculus commented on stable/coscale/values.yaml
> +    tag: "latest"
I'd prefer a release version here.

2017-06-14 20:29 UTC, unguiculus commented on stable/coscale/values.yaml
> +    pullPolicy: "Always"
Use `IfNotPresent` as default when `tag` is a release.

2017-06-14 20:29 UTC, unguiculus commented on stable/coscale/values.yaml
> +    AppId: ""
Variables should start with a lowercase letter. See https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/values.md#naming-conventions

2017-06-14 20:29 UTC, unguiculus commented on stable/coscale/README.md
> +- Kubernetes 1.2+ with Beta APIs enabled
`1.2`. Really?

2017-06-15 07:07 UTC, fryckbos commented on stable/coscale/templates/daemonset.yaml
> +    app: {{ template "fullname" . }}
Fixed.

2017-06-15 07:07 UTC, fryckbos commented on stable/coscale/values.yaml
> +    tag: "latest"
Fixed.

2017-06-15 07:07 UTC, fryckbos commented on stable/coscale/values.yaml
> +    pullPolicy: "Always"
Fixed.

2017-06-15 07:07 UTC, fryckbos commented on stable/coscale/values.yaml
> +    AppId: ""
Fixed.

2017-06-15 07:07 UTC, fryckbos commented on stable/coscale/README.md
> +- Kubernetes 1.2+ with Beta APIs enabled
The installation requires daemonsets, which were introduced as a beta feature in Kubernetes 1.2: http://blog.kubernetes.io/2016/03/Kubernetes-1.2-even-more-performance-upgrades-plus-easier-application-deployment-and-management-.html

2017-06-15 07:07 UTC, fryckbos commented on stable/coscale/values.yaml
> +resources:
In this case, for a monitoring agent, I think it makes sense to provide resource constraints, as a vendor I like to give sensible defaults to my users.

2017-06-15 15:08 UTC, unguiculus commented on stable/coscale/README.md
> +- Kubernetes 1.2+ with Beta APIs enabled
I mean 1.2 is ancient, but ok.

2017-06-15 15:10 UTC, unguiculus approved these changes

2017-06-15 15:49 UTC, prydonius commented
@unguiculus lgtm if you want to merge

2017-06-15 17:06 UTC, merged