[stable/concourse] Add warning about test user; Update README
helm/charts pull request #10766
Opened 2019-01-18 15:40 UTC by cirocosta

#### What this PR does / why we need it:

This PR improves:

- notes regarding the use of the default `test:test` default user; and
- README instructions
  - so that we don't use the future tense too much; and
  - so that the instructions regarding credential management match the actual `values.yml` structure.

It also incorporates the corrections made by #9949. 

#### Special notes for your reviewer:

The `notes` generation can be tested by running `helm template`:

```sh
# Running with the default values, outputs the warning
helm template ./ --notes -x templates/NOTES.txt | grep "WARNING" | wc -l
2

# With something that is not the default user, outputs just one warning (the one about naive):
helm template --set secrets.localUsers=this:that . --notes -x templates/NOTES.txt  | grep "WARNING" | wc -l
1
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

cc @william-tran

2019-01-19 14:20 UTC, cpanato commented
@cirocosta please rebase

2019-01-19 15:09 UTC, cpanato commented
/ok-to-test

2019-01-21 19:29 UTC, william-tran requested changes
Thanks for all the readme fixes! There's one more update that I wanted to see though:
https://github.com/helm/charts/pull/10766/files#diff-969838d261afed87173f82e43073caefR196
```
printf "%s" "concourse" > basic-auth-username
printf "%s" "$(openssl rand -base64 24)" > basic-auth-password
```
That needs to be updated to something like
```
printf "%s:%s" "concourse" "$(openssl rand -base64 24)" > local-users
```

2019-01-21 21:13 UTC, cirocosta commented
Oh, nice catch! Going to update here.

2019-01-22 00:12 UTC, cirocosta commented
/retest

2019-01-22 00:20 UTC, cirocosta commented
I'm very confused around why GitHub shows `3.6.2` under https://github.com/helm/charts/blob/master/stable/concourse/Chart.yaml but the diff correctly diffs against `3.6.1` (which, in my first bump, I bumped to 3.6.2, which then k8s ci fail as it tells me to bump to 3.6.3 then).

2019-01-22 21:44 UTC, cirocosta commented
ping @william-tran

2019-01-24 18:49 UTC, william-tran commented
/lgtm

2019-01-24 18:50 UTC, william-tran commented
/hold cancel

2019-01-24 19:00 UTC, merged