[stable/traefik] Add config option for hostNetwork
helm/charts pull request #10764
Opened 2019-01-18 15:25 UTC by RobBollons

Signed-off-by: Robert Bollons <rob@robbollons.com>

#### What this PR does / why we need it:
This will allow the hostNetwork value to be configured for the deployment. It defaults to false but when set to true it will allow external ingress on non-load balanced k8s instances such as a VPSs.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-01-18 15:34 UTC, RobBollons commented
/assign @jbdoumenjou

2019-01-18 19:31 UTC, RobBollons commented
/assign @dtomcej

2019-01-23 17:20 UTC, dtomcej requested changes

2019-01-23 17:20 UTC, dtomcej commented on stable/traefik/values.yaml
> +  hostNetwork: false
This should be commented out by default

2019-01-23 17:20 UTC, dtomcej commented on stable/traefik/templates/deployment.yaml
> +        hostNetwork: {{ .Values.deployment.hostNetwork }}
This entire setting should be optional. You need to test if `.Values.deployment.hostNetwork` exists, then use the setting if it does. Keeps the yaml cleaner.

2019-01-23 19:26 UTC, mrbalihai commented on stable/traefik/values.yaml
> +  hostNetwork: false
Fixed.

2019-03-06 08:36 UTC, closed without merging

2020-03-26 14:26 UTC, Hessu1337 commented
Would be great to have this parameter released

2020-07-19 15:36 UTC, alexpovel commented
> Would be great to have this parameter released

Second this.