[stable/janusgraph] Replace deployment with statefulset
helm/charts pull request #10770
Opened 2019-01-18 21:03 UTC by idcrosby

#### What this PR does / why we need it:

As per https://github.com/helm/charts/issues/1863. Replaces the Deployment with a StatefulSet. This chart uses PersistentVolumeClaims, scaling the number of replicas currently results in an error.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes https://github.com/helm/charts/issues/9663

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-01-18 23:17 UTC, idcrosby commented
/assign @unguiculus

2019-02-04 19:57 UTC, unguiculus requested changes
Can you elaborate why this change makes sense? I agree that scaling up a deployment with a PVC won't work. The question is how/whether Janusgraph itself can be scaled. If you simply switch to a StatefulSet, you'll get independent replicas with their own database. I would expect that you will somehow have to form a cluster which is not handled by your PR.

2019-02-04 19:57 UTC, unguiculus commented on stable/janusgraph/templates/statefulset.yaml
> +apiVersion: apps/v1beta1
You should go for `apps/v1`.

2019-02-04 19:57 UTC, unguiculus commented on stable/janusgraph/Chart.yaml
> +version: 0.2.1
You should bump to `1.0.0`.

2019-03-07 19:19 UTC, viglesiasce commented
cc @samizuh

2019-03-08 04:57 UTC, samizuh commented
The chart was created so that the default experience was written as a standalone getting started JanusGraph experience that uses Lucene for indexing. The PVC is there so that if you want to preserve your db you can, but the default is for it to be ephemeral. For a scalable solution that can span more than one pod, you need change the indexing backend to use Solr or Elasticsearch as documented [here](https://docs.janusgraph.org/0.2.0/index-backends.html).

2019-03-08 21:15 UTC, idcrosby commented
Yes, that makes sense. I had misunderstood how Janus should be configured. We did not need the local persistence (using Elasticsearch). 

The comment on this line threw me off initially: https://github.com/helm/charts/blob/8d8f98816290c64ccda3bac64be95d8b48613d11/stable/janusgraph/values.yaml#L71 

I'll close the PR. Thanks for the responses.

2019-03-08 21:15 UTC, closed without merging

2019-03-08 23:54 UTC, samizuh commented
Sounds good. And thank you for catching the typo! (will fix)