[stable/metabase] release 0.31.2
helm/charts pull request #10780
Opened 2019-01-19 20:05 UTC by ahmadalli

Signed-off-by: ahmadali shafiee <mail@ahmadalli.net>

2019-01-19 20:08 UTC, ahmadalli commented
/assign @unguiculus

2019-01-20 23:52 UTC, davidkarlsen requested changes

2019-01-20 23:52 UTC, davidkarlsen commented on stable/metabase/values.yaml
> +  tag: v0.31.2
update the readme too for consistency

2019-01-22 13:12 UTC, ahmadalli commented on stable/metabase/values.yaml
> +  tag: v0.31.2
done

2019-02-04 19:58 UTC, unguiculus commented
/ok-to-test

2019-02-04 20:18 UTC, unguiculus commented
/lgtm

2019-02-04 20:26 UTC, merged