[Datadog] Update default value of datadog.livenessProbe in README
helm/charts pull request #10876
Opened 2019-01-24 14:41 UTC by rbmrclo

#### What this PR does / why we need it:

- The default value for `datadog.livenessProbe` has been updated by this PR: https://github.com/helm/charts/pull/10827
- This keeps the documentation updated and could save other people's time when debugging the problem which the new default value might cause. (In my case, we are still respecting the former default `probe.sh`)

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-01-24 15:03 UTC, rbmrclo commented
/assign @charlyf

2019-01-26 17:52 UTC, rbmrclo commented
/assign @charlyf @hkaj

2019-01-29 08:20 UTC, CharlyF requested changes
Hey @rbmrclo - Thank you for this PR!
I double checked and the http liveness probe was only implemented in the version 6.8.0 of the agent:
https://github.com/DataDog/datadog-agent/pull/2359/files

Any chance you can bump the version of the agent (`appVersion`) in the Chart.yaml and the `tag` in the [values.yaml](https://github.com/helm/charts/pull/10827/files#diff-b0757b75566f9f21c4596c73bba4292aR6) to the newest `6.9.0` ? 

I will take another pass at this PR after.
.C

2019-01-29 15:20 UTC, rbmrclo commented
Hi @CharlyF,

I've noticed that the aforementioned requests were already updated in the latest `stable` so I just rebased my branch off the upstream branch. 

- [x] [`appVersion` in `Chart.yml`](https://github.com/helm/charts/pull/10959/files#diff-87e06a738b277ff385305ebe4d37b47eR3)
- [x] [`tag` in `values.yml`](https://github.com/helm/charts/pull/10959/files#diff-b0757b75566f9f21c4596c73bba4292aR6)

Thanks for taking time to review 🙏

2019-01-29 15:35 UTC, merged