Configure environment variables for Traefik
helm/charts pull request #10928
Opened 2019-01-28 05:53 UTC by lawliet89

Signed-off-by: Yong Wen Chua <lawliet89@users.noreply.github.com>

#### What this PR does / why we need it:

Add environment variables configuration for Traefik containers.

Use case might include adding an `status.hostIP` environment variable to use the local Consul agent (which is run as `DaemonSet`) when installed with the official HashiCorp helm chart, for example.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md

Do I need to bump the Chart version in this PR?

2019-01-28 09:36 UTC, cpanato commented on stable/traefik/README.md
> +| `deploymentStrategy`                   | Environment variables for the container                                                                                      | `{}`
this is duplicate, maybe this is `env`

2019-01-28 09:36 UTC, cpanato requested changes
see comment above.

2019-01-28 09:36 UTC, cpanato commented
/assign

2019-01-28 11:24 UTC, lawliet89 commented on stable/traefik/README.md
> +| `deploymentStrategy`                   | Environment variables for the container                                                                                      | `{}`
Oops, I've fixed the typo.

2019-02-04 01:03 UTC, lawliet89 commented
@dtomcej Please review this.

My implementation is different from #10812 in that it allows more flexibility in how you define your environment variables, including the use of the downward API.

I am using Consul and I would like my Traefik pods to use the Consul agent running on each node (as `DaemonSet`) instead of talking directly to the Consul server.

2019-02-12 18:00 UTC, rockwe11 commented
Hey @lawliet89, could you please fix the conflicts in this PR so it could be merged?
I also interested in your implementation since it is more flexible and allows to use downward API (need to send metrics and traces to Datadog agents deployed as DaemonSet).

2019-02-13 01:57 UTC, lawliet89 commented
@rockwe11 I've fixed the conflicts.

2019-02-15 15:00 UTC, cpanato commented
@lawliet89 there are still conflicts, are you able to update the branch?

2019-02-17 23:46 UTC, lawliet89 commented
@cpanato That's done.

2019-02-22 03:37 UTC, rockwe11 commented
Hey @cpanato,
Looks like @lawliet89 made the changes you requested. Could you please review and merge if everything looks good to you?

2019-03-04 19:58 UTC, dtomcej commented
@lawliet89 This looks great. Can you rebase, and bump the minor version? (this isn't a patch 😛)

Thanks!

2019-03-05 02:15 UTC, lawliet89 commented
Done

2019-03-05 02:18 UTC, dtomcej commented
Awesome!

2019-03-05 02:18 UTC, dtomcej commented
/approved

2019-03-05 02:19 UTC, dtomcej commented
/lgtm

2019-03-05 02:31 UTC, merged