[stable/kube-state-metrics] Provide else statement or other wise helm lint and template wont work.
helm/charts pull request #11031
Opened 2019-01-31 12:55 UTC by trevex

#### What this PR does / why we need it:
Recently the kube-state-metrics chart was patched to support PSPs. This introduced the usage of `.Capabilities` to the chart. Unfortunately without an `else`-statement the chart can not be used with `helm lint` or `helm template` (see https://github.com/helm/helm/issues/3377). To fix this a sensible default in an `else`-statement is provided.

#### Which issue this PR fixes
Fixed usage with `helm template` and `helm lint`

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

2019-01-31 14:48 UTC, trevex commented
/assign @cpanato

2019-01-31 19:53 UTC, davidkarlsen requested changes

2019-01-31 19:53 UTC, davidkarlsen commented on stable/kube-state-metrics/templates/psp-clusterrole.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
maybe v1 is a more sane default?

2019-01-31 19:53 UTC, davidkarlsen commented on stable/kube-state-metrics/templates/psp-clusterrolebinding.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
maybe v1 is a more sane default?

2019-02-01 12:16 UTC, trevex commented on stable/kube-state-metrics/templates/psp-clusterrole.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
Good call, changed.

2019-02-01 12:16 UTC, trevex commented on stable/kube-state-metrics/templates/psp-clusterrolebinding.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
Good call, changed.

2019-02-04 09:41 UTC, closed without merging