[prometheus-rabbitmq-export] Add skip_verify to rabbitmq-exporter
helm/charts pull request #11107
Opened 2019-02-04 08:41 UTC by eloo

This PR adds the skip_verify env variable to prometheus-rabbitmq-exporter.

2019-02-04 15:58 UTC, steven-sheehy requested changes

2019-02-04 15:58 UTC, steven-sheehy commented on stable/prometheus-rabbitmq-exporter/Chart.yaml
> -version: 0.3.0
New feature -> 0.4.0

2019-02-08 01:08 UTC, steven-sheehy requested changes

2019-02-08 01:08 UTC, steven-sheehy commented on stable/prometheus-rabbitmq-exporter/values.yaml
> -  capabilities: bert,no_sort
This shouldn't be removed.

2019-02-08 08:50 UTC, eloo commented on stable/prometheus-rabbitmq-exporter/values.yaml
> -  capabilities: bert,no_sort
oh yes, my mistake

2019-02-08 15:58 UTC, steven-sheehy commented
/ok-to-test
/retest

2019-02-08 16:04 UTC, steven-sheehy commented
Trying to figure out how to re-run that failed lint
/lint
/test all

2019-02-08 16:24 UTC, unguiculus commented
/lgtm

2019-02-08 16:39 UTC, merged