[stable/traefik] Add acme dns resolvers configuration
helm/charts pull request #11112
Opened 2019-02-04 10:30 UTC by emmanuelCarre

#### What this PR does / why we need it:

In some case, we need to define DNS servers for Letsencrypt DNS challange with option `acme.dnsChallenge.resolvers` (see [acme configuration](https://docs.traefik.io/configuration/acme/)) but is not available into Helm deployment.

#### Which issue this PR fixes
None

#### Special notes for your reviewer:
* I was not sure if I have to squash my commit...
* Naming variables is never easy; Don't hesitate to suggest better names.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-02-04 11:04 UTC, ldez commented
/assign @dtomcej

2019-02-04 15:35 UTC, dtomcej requested changes

2019-02-04 15:35 UTC, dtomcej commented on stable/traefik/README.md
> +| `acme.resolvers.enable`                | Whether to enable specific DNS servers for DNS challenge                                                                     | `false`
Does this actually do anything?

2019-02-04 15:35 UTC, dtomcej commented on stable/traefik/templates/configmap.yaml
> +      {{- if .Values.acme.resolvers.enable }}
Can you just do `if .Values.acme.resolvers` and skip the whole enable value?

2019-02-04 15:35 UTC, dtomcej commented on stable/traefik/values.yaml
> +  resolvers:
That would make this:

```yaml
resolvers: []
# - 1.1.1.1:53
# - 8.8.8.8:53
```

2019-02-05 10:24 UTC, emmanuelCarre commented on stable/traefik/templates/configmap.yaml
> +      {{- if .Values.acme.resolvers.enable }}
Done. I was afraid about empty array is always `true` but it is work fine.  Thx for this tips :)

2019-02-05 10:26 UTC, emmanuelCarre commented on stable/traefik/README.md
> +| `acme.resolvers.enable`                | Whether to enable specific DNS servers for DNS challenge                                                                     | `false`
It is not needed with with `acme.resolvers: []` in `values.yaml`. I removed this change.

2019-02-05 10:27 UTC, emmanuelCarre commented on stable/traefik/values.yaml
> +  resolvers:
Done.

2019-02-05 10:32 UTC, emmanuelCarre commented
Newbee contributor question: Is it fine if I solve directly conversation after take care of feedback?

2019-03-07 23:32 UTC, ldez commented
@emmanuelCarre could you rebase ?

2019-03-11 09:57 UTC, emmanuelCarre commented
Hi,
I rebase, it should be OK now.

2019-03-12 01:04 UTC, ldez commented
@emmanuelCarre could you rebase once again ?

2019-03-12 12:30 UTC, emmanuelCarre commented
Done :)

2019-03-12 17:22 UTC, ldez commented
/ok-to-test

2019-03-12 17:40 UTC, ldez commented
/lgtm

2019-03-13 11:40 UTC, ldez commented
/lgtm

2019-03-14 00:36 UTC, merged