[stable/elasticsearch] Add ability to disable sysctl init container.
helm/charts pull request #11122
Opened 2019-02-04 15:20 UTC by trevex

Signed-off-by: Niklas Voss <niklas.voss@gmail.com>

#### What this PR does / why we need it:
In out cluster we have the correct sysctl settings for elasticsearch on all nodes. We would like the ability to disable the init container to avoid unnecessary privileges.

Therefore this PR introduces a new value `sysctlInitContainer.enabled`, which is `true` by default.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-02-04 15:22 UTC, trevex commented
/assign @simonswine

2019-02-05 09:10 UTC, desaintmartin requested changes

2019-02-05 09:10 UTC, desaintmartin commented on stable/elasticsearch/Chart.yaml
> +version: 1.18.2
Since it is a new feature, please bump a  minor version instead of patch.

2019-02-05 09:10 UTC, desaintmartin commented on stable/elasticsearch/README.md
> +| `sysctlInitContainer.enabled`        | If true, the sysctl init container is enabledtpl                    | `true`                                              |
Typo! :)
Also, make sure to state that even if it is false, it does not prevent extraInitContainers to run.

2019-02-05 09:11 UTC, desaintmartin commented
Thanks!
/assign

2019-02-05 10:27 UTC, trevex commented on stable/elasticsearch/Chart.yaml
> +version: 1.18.2
Fixed via https://github.com/helm/charts/pull/11122/commits/176826ba55ca94a5a78c8a4fc798c54521f3f6f8

2019-02-05 10:27 UTC, trevex commented on stable/elasticsearch/README.md
> +| `sysctlInitContainer.enabled`        | If true, the sysctl init container is enabledtpl                    | `true`                                              |
Fixed via https://github.com/helm/charts/pull/11122/commits/cca767c395ff1b8542f97347e497c14524a82273

2019-02-05 10:35 UTC, desaintmartin commented
Nice.
/ok-to-test

2019-02-05 11:46 UTC, desaintmartin commented
/lgtm

2019-02-05 11:48 UTC, merged