Add a Chart for Risk Advisor
helm/charts pull request #1135
Opened 2017-05-22 17:10 UTC by pposkrobko

Hi,

We are a group of Computer Science students from University of Warsaw and we made Risk Advisor module for Kubernetes as our Bachelor's thesis in cooperation with @crassirostris from Google Warsaw.

The source code can be found here: https://github.com/Prytu/risk-advisor

Cheers,
Pawel

2017-05-24 18:45 UTC, unguiculus requested changes

2017-05-24 18:45 UTC, unguiculus commented on stable/risk-advisor/values.yaml
> +  limits:
Don't provide defaults for resources

2017-05-24 18:45 UTC, unguiculus commented on stable/risk-advisor/templates/deployment.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
See best practices for standard labels and apply them everywhere:
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md

Use `{{ template "name" . }}` for the `app` label.

2017-05-24 18:45 UTC, unguiculus commented on stable/risk-advisor/README.md
> +# risk-advisor
Please follow the standard readme style. See e. g. https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/README.md

2017-06-09 17:01 UTC, unguiculus commented
Closing this due to inactivity. Feel free to re-open if you decide to continue working on it.

2017-06-18 12:04 UTC, pposkrobko commented
I'd like to continue working on it and I add suggested fixes to my fork, however can't see a way to reopen this PR by myself, could you please reopen it? Or do you want me to create new PR?

2017-06-18 12:33 UTC, pposkrobko commented
thanks, I see new commits have been added automatically, I hope PR is ok now, please verify

2017-06-20 15:54 UTC, unguiculus requested changes
A few more things.

2017-06-20 15:54 UTC, unguiculus commented on stable/risk-advisor/Chart.yaml
> +icon: https://raw.githubusercontent.com/Prytu/risk-advisor/master/logo.svg
Maintainer is missing. User Github username.

2017-06-20 15:54 UTC, unguiculus commented on stable/risk-advisor/README.md
> +
Add a configuration section.

2017-06-20 15:54 UTC, unguiculus commented on stable/risk-advisor/templates/NOTES.txt
> +	curl -XPOST SERVICE_URL:11111/advise -H "Content-type: application/json" -d @PATH_TO_JSON_WITH_PODS
This is very little information. URL/port should not be hard-coded.

Here's a good example: https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/templates/NOTES.txt

2017-06-20 15:54 UTC, unguiculus commented on stable/risk-advisor/templates/service.yaml
> +    app: {{ template "fullname" . }}
Selector should be this:

```yaml
app: "{{ template "name" . }}"
release: "{{ .Release.Name }}"
```

2017-06-23 12:04 UTC, pposkrobko commented
@unguiculus thanks for pointing these things out, I have done all the changes you've requested

2017-06-24 09:19 UTC, unguiculus requested changes

2017-06-24 09:19 UTC, unguiculus commented on stable/risk-advisor/templates/deployment.yaml
> +      labels:
Only keep `app` and `release` label here.

2017-06-24 09:30 UTC, pposkrobko commented on stable/risk-advisor/templates/deployment.yaml
> +      labels:
done

2017-06-24 15:41 UTC, unguiculus approved these changes

2017-06-24 15:42 UTC, unguiculus commented
@k8s-bot ok to test

2017-07-02 18:17 UTC, merged