Added values to chose init container, additional label for Ingress and deleteDefaultPlugins option.
helm/charts pull request #11361
Opened 2019-02-12 18:16 UTC by andreyshamray

#### What this PR does / why we need it:
I have added several values which will improve the flexibility, security and upgrade plugins procedure of this chart.
1. ingress.labels - will give you an opportunity to route traffic to particular Ingress controller. 
2. plugins.initContainerImage - it is needed for security reason, for example, access to docker hub is not permitted.
3. plugins.deleteDefaultPlugins - this option will remove default plugins and deploy plugins from plugins.install list. It will give an opportunity to upgrade plugins.

2019-02-12 18:31 UTC, andreyshamray commented
/assign @rjkernick

2019-02-12 18:33 UTC, andreyshamray commented
Hi, guys will be good if you can merge it, so I will no need to store this chart in local helm repo.
Thanks in advance.

2019-02-13 15:11 UTC, rjkernick commented
/ok-to-test

2019-02-13 15:19 UTC, rjkernick requested changes

2019-02-13 15:19 UTC, rjkernick commented on stable/sonarqube/values.yaml
> +  #labels:
Please add a space between the # and the comment

2019-02-13 15:19 UTC, rjkernick commented on stable/sonarqube/values.yaml
> +  #deleteDefaultPlugins: true
Same here, please add a space after the #

2019-02-13 15:19 UTC, rjkernick commented on stable/sonarqube/Chart.yaml
> +version: 0.13.5
Please bump the minor version as this adds new features

2019-02-14 11:54 UTC, andreyshamray commented
I have applied all the recommendations.
Thanks!

2019-02-14 12:21 UTC, andreyshamray commented
/retest

2019-02-14 12:27 UTC, andreyshamray commented
/retest

2019-02-14 12:42 UTC, andreyshamray commented
@rjkernick could you pls help to understand what is wrong again?)
Thanks a lot.

2019-02-14 12:45 UTC, andreyshamray commented
/retest

2019-02-14 14:32 UTC, rjkernick commented
/lgtm

2019-02-14 14:46 UTC, rjkernick commented
Please merge the latest master and update the chart.yaml. Please be sure to include "--signoff" when merging. Another pull request got merged ahead of yours

2019-02-14 20:06 UTC, andreyshamray commented
> Please merge the latest master and update the chart.yaml. Please be sure to include "--signoff" when merging. Another pull request got merged ahead of yours

Done!)

2019-02-15 13:43 UTC, rjkernick commented
/lgtm

2019-02-15 14:12 UTC, merged

2019-02-15 15:39 UTC, andreyshamray commented
Thanks a lot!