[prometheus-operator] Fix namespace lookup of grafana pv dashboard
helm/charts pull request #11407
Opened 2019-02-14 09:22 UTC by RmMsr

#### What this PR does / why we need it:

Fix the namespace selection within the Grafana dashboard "Persistent Volumes" that comes with the prometheus-operator. Previously the namespace was exported via the label `exported_namespace`. Now it is called plainly `namespace`.

#### Which issue this PR fixes

* none

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

2019-02-18 22:06 UTC, vsliouniaev commented
/ok-to-test

2019-02-19 11:13 UTC, paskal requested changes
It couldn't be done like that - changes will be removed on next sync, please read [hacks folder's](https://github.com/helm/charts/tree/master/stable/prometheus-operator/hack) Readme for details.
In order to make changes there you need first to introduce them [to original location](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml), and then sync everything by running scripts in hack folder.

2019-02-19 12:09 UTC, vsliouniaev commented
@paskal 
I think it would be useful to add this as a comment to the top of the file to make it more obvious.

2019-02-21 09:11 UTC, paskal commented
No problem, I'll prepare PR for that.
@RmMsr, in order to introduce changes here they need to be added [to this file](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/persistentvolumesusage.libsonnet) first and then imported to coreos/prometheus-operator according to their rules, [here is an instruction](https://github.com/coreos/prometheus-operator/pull/2096#issuecomment-436561961).

2019-04-06 09:30 UTC, closed without merging