[stable/kube-state-metrics] Add imagePullSecrets in serviceAccount
helm/charts pull request #11405
Opened 2019-02-14 07:26 UTC by tbuchier

Signed-off-by: Tanguy Buchier <tanguy.buchier@gmail.com>

#### What this PR does / why we need it:

Add the ability to specify the imagePullSecrets field in the serviceAccount
Allow you to specify the serviceAccount name even if rbac is enabled

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-02-14 07:27 UTC, tbuchier commented
/assign @lachie83

2019-02-28 06:08 UTC, tbuchier commented
need to bump version, because another change was added.

2019-02-28 06:26 UTC, tbuchier commented
/assign @davidkarlsen

2019-03-07 21:13 UTC, cpanato requested changes

2019-03-07 21:13 UTC, cpanato commented on stable/kube-state-metrics/templates/serviceaccount.yaml
> +{{- end -}}
new line 😄

2019-03-07 21:13 UTC, cpanato commented on stable/kube-state-metrics/templates/_helpers.tpl
> +{{- end -}}
new line

2019-03-07 21:13 UTC, cpanato commented on stable/kube-state-metrics/Chart.yaml
> +version: 0.14.2
```suggestion
version: 0.15.0
```

2019-03-08 02:32 UTC, tbuchier commented on stable/kube-state-metrics/templates/serviceaccount.yaml
> +{{- end -}}
Done :slightly_smiling_face:

2019-03-08 02:32 UTC, tbuchier commented on stable/kube-state-metrics/Chart.yaml
> +version: 0.14.2
Done

2019-03-13 13:00 UTC, cpanato commented
/ok-to-test

2019-03-13 13:05 UTC, cpanato approved these changes

2019-03-13 13:05 UTC, cpanato commented
/lgtm

2019-03-14 00:36 UTC, merged