Add Logary Rutta to incubator/
helm/charts pull request #11499
Opened 2019-02-18 18:02 UTC by haf

#### What this PR does / why we need it:

Doing cloud-native logging, metrics and monitoring across languages and platforms is hard. Rutta solves a lot of the hardships that software architects face, trying to unify a logging/metrics pipeline.

#### Special notes for your reviewer:
This is my first PR and my first chart! 😅

#### Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-02-18 18:25 UTC, haf commented
Hey c'mon! That's not fair!

<img width="727" alt="image" src="https://user-images.githubusercontent.com/193115/52970098-f0e14080-33b2-11e9-9f3c-1b72dc58f748.png">

2019-02-22 15:27 UTC, haf commented
What do I need to do to progress this?

2019-03-24 17:32 UTC, haf commented
xxxxxxxx

2019-04-23 18:16 UTC, haf commented
xxxxxxxx

2019-05-16 09:16 UTC, maorfr commented
hey @haf 

Have you considered hosting this chart and adding it to helm hub?
https://github.com/helm/hub/blob/master/Repositories.md

2019-06-15 10:38 UTC, haf commented
Not stale

2019-06-15 10:39 UTC, haf commented
@maorfr No I don’t want that. Thanks for the suggestion though.

2019-06-26 12:04 UTC, haf commented
xxxxxxxxxx

2019-07-28 06:07 UTC, haf commented
Not

> On Friday, Jul 26, 2019 at 2:41 PM, stale[bot] <notifications@github.com (mailto:notifications@github.com)> wrote:
>
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Any further update will cause the issue/pull request to no longer be considered stale. Thank you for your contributions.
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (https://github.com/helm/charts/pull/11499?email_source=notifications&email_token=AABPEW3Z533VRHUYVVN2YCDQBLWFRA5CNFSM4GYFQJF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD24OUGA#issuecomment-515435032), or mute the thread (https://github.com/notifications/unsubscribe-auth/AABPEW4UEUFULU3NR4VIYZLQBLWFRANCNFSM4GYFQJFQ).
>
>
>

2019-07-29 09:03 UTC, cpanato requested changes
after you make the changes please move this to the stable folder. thanks!

2019-07-29 09:03 UTC, cpanato commented on incubator/rutta/Chart.yaml
> +- name: Henrik Feldt
should be your github handler and good practice is to add the email as well

2019-07-29 09:03 UTC, cpanato commented on incubator/rutta/templates/deployment.yaml
> +        image: {{ .Values.image | default "haaf/rutta:5.0.0-rc.1.597e31a3" | quote }}
you dont need to set the default image

2019-07-29 09:03 UTC, cpanato commented on incubator/rutta/templates/service.yaml
> +{{- end }}
new line

2019-07-29 09:03 UTC, cpanato commented on incubator/rutta/templates/tests/test-connection.yaml
> +  restartPolicy: Never
new line

2019-08-13 06:43 UTC, maorfr commented
please take a look at https://github.com/helm/helm/pull/6095#issue-301608768

we strongly encourage people to self host chart repos:
https://github.com/helm/hub/blob/master/Repositories.md

you can even do that using GitHub pages:
https://github.com/helm/hub/blob/master/docs/github.md#github-pages-as-a-repository

2019-09-26 07:35 UTC, closed without merging