update to 1.6.0, add psp support
helm/charts pull request #11534
Opened 2019-02-19 14:36 UTC by verwilst

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2019-02-19 14:37 UTC, verwilst commented
/assign davidkarlsen

2019-02-22 17:36 UTC, davidkarlsen requested changes

2019-02-22 17:36 UTC, davidkarlsen commented on stable/newrelic-infrastructure/templates/clusterrolebinding.yaml
>  apiVersion: rbac.authorization.k8s.io/v1beta1
this can be v1

2019-03-20 16:16 UTC, verwilst commented
@davidkarlsen Should be ok now :-)

2019-04-02 08:31 UTC, verwilst commented
bump

2019-04-05 14:10 UTC, verwilst commented
/assign  paulczar 
/assign  scottrigby

2019-04-06 09:53 UTC, davidkarlsen commented
/ok-to-test

2019-04-06 09:53 UTC, davidkarlsen approved these changes

2019-04-06 11:34 UTC, davidkarlsen commented
/lgtm

2019-04-06 11:34 UTC, merged