Allow datadog to run on masters with a taint of NoSchedule
helm/charts pull request #1157
Opened 2017-05-26 01:23 UTC by chobomuffin

Basically datadog is one daemonset that I want to run on all of my nodes, regardless of the taints really. At the moment we use `kube-aws` and by default it sets up the masters with a NoSchedule taint. I have added this as a default tolerant but it can be modified by the values file.

2017-05-26 03:27 UTC, irabinovitch commented
/CC @hkaj

2017-06-08 11:27 UTC, hkaj commented
That makes sense, but maybe not as the new default. Mostly because it will incur extra cost. But you could leave the value commented out as an example?

2017-06-20 12:39 UTC, prydonius commented
Agree with @hkaj, I would keep the value commented as an example and leave K8S to set the default.

2017-06-20 12:39 UTC, prydonius requested changes
- commented tolerations (null by default)
- bump chart version
- rebase

2017-06-20 15:54 UTC, pierreozoux commented on stable/datadog/README.md
> +  autoconf:
I'd make a separate commit for codestyle fix.

2017-07-11 03:30 UTC, irabinovitch commented
@chobomuffin Any thoughts on the feedback from @hkaj and @prydonius ? We may also need a quick rebase of this as theres now some conflicts with master due to changes from other PRs. Thanks again for digging into this.

2017-08-31 14:58 UTC, pierreozoux commented
I think it is a duplicate of https://github.com/kubernetes/charts/pull/1252 and as a result, we could close this one.

2017-09-01 03:29 UTC, irabinovitch commented
@lachie83 mind helping us close this one?

2017-09-01 07:15 UTC, lachie83 commented
@pierreozoux you are correct. This can be closed.

2017-09-01 07:15 UTC, closed without merging