[stable/kubernetes-replicator] Initial commit.
helm/charts pull request #11818
Opened 2019-02-27 17:07 UTC by desaintmartin

#### What this PR does / why we need it:

Add kubernetes-replicator.
https://github.com/mittwald/kubernetes-replicator/

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-02-27 17:07 UTC, desaintmartin commented
/hold

2019-02-27 17:08 UTC, desaintmartin commented
cc @botzill @martin-helmich for review

2019-02-27 17:09 UTC, desaintmartin commented
We would also need a liveness probe, i.e a way to check that the Pod is still alive and working. Do you know how to do it?

2019-02-27 17:12 UTC, martin-helmich commented
>We would also need a liveness probe, i.e a way to check that the Pod is still alive and working. Do you know how to do it?

I don't know if the application already supports a status route off the top of my head. I'll check and get back to you ASAP.

2019-02-27 17:25 UTC, martin-helmich requested changes

2019-02-27 17:25 UTC, martin-helmich commented on stable/kubernetes-replicator/Chart.yaml
> +  email: TBD
This seems to kill one of the test jobs.

```suggestion
  email: m.helmich@mittwald.de
```

2019-02-27 17:25 UTC, martin-helmich commented on stable/kubernetes-replicator/README.md
> +The following table lists the configurable parameters of the cerebro chart and their default values.
`cerebro`? Forgotten copy&paste?

2019-02-27 17:25 UTC, martin-helmich commented on stable/kubernetes-replicator/README.md
> +The following table lists the configurable parameters of the cerebro chart and their default values.
```suggestion
The following table lists the configurable parameters of the replicator chart and their default values.
```

2019-02-27 17:25 UTC, martin-helmich commented on stable/kubernetes-replicator/OWNERS
> +- tbd
Do approvers/reviewers need to be project collaborators/org members? Otherwise, you're welcome to add me to the list.

2019-02-27 17:25 UTC, martin-helmich commented on stable/kubernetes-replicator/README.md
> +kubernetes-replicator is an open source (Apache 2.0 License) custom Kubernetes controller that can be used to make secrets and config maps available in multiple namespaces.
Maybe add a link to the original project homepage in the README?

```suggestion
[kubernetes-replicator](https://github.com/mittwald/kubernetes-replicator) is an open source (Apache 2.0 License) custom Kubernetes controller that can be used to make secrets and config maps available in multiple namespaces.
```

2019-03-01 15:14 UTC, desaintmartin commented on stable/kubernetes-replicator/README.md
> +The following table lists the configurable parameters of the cerebro chart and their default values.
Indeed...

2019-03-05 16:23 UTC, mattfarina commented
/retest

2019-03-07 16:21 UTC, mattfarina commented
/retest

2019-03-07 16:24 UTC, desaintmartin commented
This one is not finished yet, I should spend a few minutes in the coming days to finish it and remove the /hold.

2019-04-20 18:30 UTC, closed without merging

2019-04-21 14:12 UTC, desaintmartin commented
Can't find time to finish this, probably later.