update - istio add standard labels
helm/charts pull request #1181
Opened 2017-05-28 07:31 UTC by lachie83

* add standard labels
* Fix conditional on ca deployment
* Bump chart version
* Update istio labels
* use serviceName across all manifests

2017-05-28 07:31 UTC, lachie83 commented
cc @unguiculus

2017-05-28 15:43 UTC, unguiculus requested changes
I think it's great to use a template function for standard labels. Can we include this in the default `_helpers.tpl`, so everyone gets it with `helm create`? Currently, `helm create` doesn't even add standard labels at all.

/cc @technosophos

2017-05-28 15:43 UTC, unguiculus commented on incubator/istio/templates/_helpers.tpl
> +app: {{template "fullname" .}}
Let's use `{{ template "name" . }}` for the `app` label. See recent discussion on Slack about this. Note that you will have to update label selectors in services. See e. g. here: https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml#L55

And please use consistent formatting everywhere, i. e. space after '{{' and space before `}}`.

Apply everywhere in this chart.

2017-05-28 15:43 UTC, unguiculus commented on incubator/istio/templates/addons-prometheus-svc.yaml
> +  # Grafana datasource config is hardcoded to prometheus:9090
Does it have to be?

2017-05-30 18:44 UTC, lachie83 commented on incubator/istio/templates/addons-prometheus-svc.yaml
> +  # Grafana datasource config is hardcoded to prometheus:9090
Currently yes.

2017-05-30 18:44 UTC, lachie83 commented on incubator/istio/templates/_helpers.tpl
> +app: {{template "fullname" .}}
Agreed

2017-05-30 22:23 UTC, lachie83 commented
@unguiculus Updated with your changes. Please review

2017-05-30 22:41 UTC, lachie83 commented
@k8s-bot pull-charts-e2e test this

2017-05-31 08:38 UTC, unguiculus requested changes
Thanks for the update. We're not quite there yet. I would add `component` annotations for the individual components. Look at how @mgoodness did it. I think that's the way to go.

https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml#L8-L14

You will also have to change label selectors in the services:

https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml#L55-L58

2017-05-31 08:38 UTC, unguiculus commented on incubator/istio/templates/_helpers.tpl
> +chart: {{template "chartref" . }}
Still some missing spaces here.

2017-05-31 16:36 UTC, lachie83 commented
Updated based on @unguiculus feedback

2017-05-31 18:50 UTC, unguiculus submitted a review, later dismissed
One more little thing...

2017-05-31 18:50 UTC, unguiculus commented on incubator/istio/values.yaml
> +      name: grafan
grafana?

2017-05-31 18:53 UTC, lachie83 commented
fixed thanks! 👍 @unguiculus

2017-05-31 19:24 UTC, unguiculus commented
lgtm

2017-05-31 19:36 UTC, merged