Add prometheus support to gitlab-ce
helm/charts pull request #1186
Opened 2017-05-29 07:39 UTC by simt2

The integrated prometheus in Gitlab does currently not work with an RBAC enabled cluster and is also not considered in the charts service template.

2017-05-29 07:40 UTC, simt2 commented
Note: I actually signed the CLA and am still not sure why it shows up as not signed.

2017-06-01 15:18 UTC, kfox1111 commented
Can gitlab-ce use an external prometheus? There already is a prometheus chart and it might be easier to maintain then if it was reused?

2017-07-05 22:12 UTC, viglesiasce commented
Yes I agree with @kfox1111 that this should make a conditional dependency on the Prometheus chart and be able to point to an existing chart. 

Please update with those changes.

2017-07-05 22:13 UTC, viglesiasce requested changes
Should allow a configurable Prometheus URL and also allow deploying the prometheus chart rather than deploying its own Prometheus.

2017-07-15 15:09 UTC, mgoodness commented
Linking this to the discussion underway in #1138

2017-08-02 00:52 UTC, mgoodness commented
Closing this because it increasingly looks like we're going to deprecate our GitLab charts and point users to the "official" ones. I encourage you to submit this work [there](https://gitlab.com/charts/charts.gitlab.io/tree/master/charts/gitlab).

2017-08-02 00:52 UTC, closed without merging