Istio  - Support type loadbalancer in notes
helm/charts pull request #1202
Opened 2017-05-30 19:25 UTC by lachie83

2017-05-30 19:34 UTC, unguiculus commented
Needs a rebase.

2017-05-30 20:08 UTC, lachie83 commented
@unguiculus rebased

2017-05-31 19:11 UTC, unguiculus requested changes

2017-05-31 19:11 UTC, unguiculus commented on incubator/istio/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ $serviceName }}-serviegraph" -o jsonpath="{.items[0].metadata.name}")
Typo: serviegraph -> servicegraph

2017-05-31 19:13 UTC, lachie83 commented on incubator/istio/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ $serviceName }}-serviegraph" -o jsonpath="{.items[0].metadata.name}")
Will fix

2017-05-31 20:19 UTC, unguiculus approved these changes

2017-05-31 20:46 UTC, merged