[stable/kibana] Added alternative method to import saved objects
helm/charts pull request #12277
Opened 2019-03-15 14:12 UTC by hprotzek

Added alternative method to import saved objects like: visualization, dashboard, search, index-pattern, config, and timelion-sheet.

Right now the Bulk Create Object API is used to create the objects on startup (analog to the dashboards).

@compleatang
I'm not sure if we need both functions or if we just should merge them to one using saved_objects api.

Pro: Single objects could be imported
Con: More configuration to import a dashboard together with all saved objects.

Whats your opinion?

2019-03-18 11:24 UTC, compleatang requested changes

2019-03-18 11:24 UTC, compleatang commented on stable/kibana/values.yaml
> +    username: myuser
Let's comment theses in the values.yaml since they're only utilized if `enabled: true`

2019-03-18 11:24 UTC, compleatang commented on stable/kibana/README.md
> +| `objectsImport.enabled`                    | Enable objects   import                                                | `false`                               |
extra space between objects and import here.

2019-03-18 11:24 UTC, compleatang commented on stable/kibana/README.md
>  | `plugins.values`                           | List of plugins to install. Format                                     | None:                                 |
At the bottom of the readme, it would be good to add some documentation as to how to use this feature beneath the Dashboard Imports section.

2019-03-18 11:24 UTC, compleatang commented on stable/kibana/templates/deployment.yaml
> +        {{- range $configFile := (keys .Values.files) }}
outdent here and the `end`

2019-03-18 11:24 UTC, compleatang commented on stable/kibana/templates/deployment.yaml
> +        {{- range $key, $value := .Values.env }}
outdent here and the `end`

2019-03-18 11:31 UTC, compleatang commented
@montek am continuing the discussion from [here](https://github.com/helm/charts/pull/12178#pullrequestreview-215000792). 

I'm not exactly sure if we need both either. I can see in the instance where an operator **only** wants to import dashboards the utility of having the objects be separate, and I can also see the utility where an operator wants to import saved objects and also dashboards from a URL (e.g., always give me the updated version of the dashboard). 

My main worry here is how do we actually test this feature? It's unclear to me how we can actually do that without having an es instance running somewhere that has saved objects we can import. This will be especially important when we get the typical version bump PRs where importing may not be on top of mind for the contributor and perhaps where the API structure has changed in, say, v7.0 or the like (I have no idea if this is on ES's radar, just mentioning the fragility of a lack of testing here). 

@hprotzek can you outline any reasons to keep both the import objects feature **and** the import dashboards feature? 

@monotek what is your inclination regarding the possibility of a merger of these features?

2019-03-18 12:59 UTC, hprotzek commented
@compleatang Thank's for your feedback. My intention to keep the existing dashboard import, was not to break existing usage of this feature. For the long run, I think the Import Objects API (https://www.elastic.co/guide/en/kibana/master/saved-objects-api-import.html, available maybe in 7.x ?) could be used as a general purpose import. Then it's very easy to create your config once, export the saved objects over the ui and put that in your chart.

2019-03-18 15:10 UTC, compleatang commented
Given that the API is still in experimental mode, my personal inclination is to wait a bit to add this feature to the chart. However I'd like to wait for @monotek who also maintains the chart to weigh in.

2019-03-19 10:40 UTC, monotek requested changes
@compleatang 
I think currently its a good idea to implement both options.
If there is any way to merge both functions (via a new api for example) in the future, i would go fo it.

@hprotzek 
What i would like to see is a merge of the configmaps as it contains a lot of redundant code at the moment.

The different parts, which are likely only the curl requests, could make use of an if statement.

2019-03-19 13:58 UTC, compleatang commented
OK. I definitely can see the utility in being able to import (in our case at least) saved searches (and I suspect other objects will be of interest for others). Agree fully on reducing the redundancy where possible in the bash scripts. That would also open the pathway for eventually completely merging the functions over time. So, I'm on board with this direction. 

I still have a concern as to how we can test this. Perhaps it would be possible to export a sample index to a json in the CI directory here and then reference that via the URL import option?

2019-03-19 16:19 UTC, hprotzek commented
I am struggling to merge dashboard and objects import. Right now its duplicated code, but if the plan is to ditch the dashboard only import function at some point in time, then I would keep them separate for the time being, so when this happens, only the dashboard files must be deleted without modifying the additional if statements.

2019-03-20 16:05 UTC, compleatang commented
@hprotzek OK. I'm OK with that if we can find a way to test this feature (which is my larger concern) for going forward stability.

2019-03-20 17:06 UTC, monotek commented
I'll do the merge later...

2019-03-21 09:43 UTC, hprotzek commented
> @hprotzek OK. I'm OK with that if we can find a way to test this feature (which is my larger concern) for going forward stability.

How do you test the chart in general and where are the files from the ci folder used?

2019-03-21 09:47 UTC, compleatang commented
The jenkins CI system will run a test against *each* of the yaml files in the ci directory. So to build a test you would add an additional yaml file to the ci directory. You'd likely need to change the image since the default image for the chart does not have the API this PR would seek to leverage. Then you'd likely need to store an exported JSON file in the CI directory and use that within the values file for the test. At least that's the best I can think to do here.

2019-03-21 10:15 UTC, hprotzek commented
Where can I find more infos about this Jenkins CI system?

2019-03-21 14:47 UTC, compleatang commented
@hprotzek [here](https://github.com/helm/charts/tree/master/test) basically just follow the other examples in the ci directory of this chart and it should all be clear.

2019-03-21 15:40 UTC, hprotzek commented
Thanks, that was the missing piece :-) I will look into it and try to add a test.

2019-03-22 09:39 UTC, hprotzek commented
Oh my, I should read the documentation more carefully :-) The existing dashboard API says:
```
The dashboard import API allows people to import dashboards along with all of their corresponding saved objects such as visualizations, saved searches, and index patterns.
```
Which is almost exactly the same as the object import. So, no need for this PR, as the existing dashboard import is sufficient. 

Anyway the testing is still not clear. If the chart is installed in ci, it won't find the default `http://elasticsearch:9200/`, so it also won't run the dashboard import and with health-checks disabled by default the helm install will be successful anyway. What do I miss here?

2019-03-28 10:16 UTC, compleatang commented
@hprotzek so, assuming the dashboard import API is sufficient for your purposes, should we close this PR?

2019-03-28 10:16 UTC, compleatang commented
/hold

2019-03-28 10:34 UTC, closed without merging

2019-03-28 11:55 UTC, monotek commented
@compleatang 

About the test issue...
We could add an Elasticsearch dependency which is disabled by default and enable it only via the ci directory.
What do you think?

2019-03-28 13:41 UTC, compleatang commented
@monotek was worried such a discussion would get buried in this PR so moved to #12628