[stable/postgresql] Allow a template for persistence.existingClaim
helm/charts pull request #12313
Opened 2019-03-17 15:14 UTC by michaelbeaumont

#### What this PR does / why we need it:

Allows `.Values.persistence.existingClaim` to depend on things like `.Release.Name`.

#### Which issue this PR fixes

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-03-18 12:39 UTC, jonninen50 approved these changes

2019-03-19 14:16 UTC, juan131 requested changes
Thanks for the contribution @michaelbeaumont 

I'm okay with the changes but please extend the changes to `values-production.yaml` too.

2019-03-19 14:16 UTC, juan131 commented on stable/postgresql/values.yaml
> +  ## The value is evaluated as a template, so, for example, the name can depend on .Release or .Chart
Please update `values-production.yaml` too.

2019-03-19 15:15 UTC, michaelbeaumont commented on stable/postgresql/values.yaml
> +  ## The value is evaluated as a template, so, for example, the name can depend on .Release or .Chart
done, nice catch

2019-03-19 15:35 UTC, juan131 commented
/ok-to-test
/lgtm

2019-03-19 15:40 UTC, merged