[stable/drupal] Allow non-bitnami Drupal data and Apache configuration volume paths
helm/charts pull request #1232
Opened 2017-06-03 02:57 UTC by scottrigby

Follow up to #1231.

@prydonius As an aside, I'm unclear why we mount the Apache config directory? I'm sure I'm missing something obvious about this.

2017-06-06 07:54 UTC, prydonius commented
@scottrigby it's not required, but it persists the apache configuration in a volume in case you need to back it up, or modify it

2017-06-06 07:58 UTC, prydonius requested changes

2017-06-06 07:58 UTC, prydonius commented on stable/drupal/README.md
> +## Image
This section seems redundant to me, as it's in the configuration table and there isn't really anything further to explain about this value?

2017-06-06 07:58 UTC, prydonius commented
@k8s-bot ok to test

2017-06-08 17:34 UTC, scottrigby commented on stable/drupal/README.md
> +## Image
You're right. I was trying to make a header that would encompass subheaders for both the existing Persistence header and this new volume mounts header - and thought Image might make sense. But maybe you're right. Let me remove that extra image header hierarchy, and see if it seems less redundant?

2017-06-08 17:41 UTC, scottrigby commented on stable/drupal/README.md
> +## Image
@prydonius OK, how does that read now?

2017-06-23 19:18 UTC, scottrigby commented
@prydonius rebased, and correctly bumped version (note the bump is the same as #1340 because I'm not sure which will be merged first. Once one is, I can bump the other PR PATCH version again. Or you can if you prefer)

2017-06-26 05:17 UTC, scottrigby commented
@prydonius OK rebased again, after #1340 was merged. This time I bumped the MINOR version (I should have bumped this PR MINOR version in the first place).

2017-06-26 06:59 UTC, scottrigby commented
@prydonius I also added an additional conditional in f131108f4cd7c9ba6d0febb57de5b8b1088d14ed. This was important for an image I tested that doesn't store anything in the apache conf directory, and so didn't need to be mounted. Also, it didn't build apache configs at runtime, so the dir was always overwritten by an empty object. This wasn't an issue with the bitnami-docker-drupal image because it has matching logic, but for other images this was difficult. I'm open to other ways of doing this though if you have suggestions?

2017-06-28 23:45 UTC, scottrigby commented
@prydonius The last commit f6cc19 fixes an issue with this patch on Tectonic/AWS. GCP was fine.

2017-06-29 10:42 UTC, prydonius commented
/ok-to-test

2017-06-29 10:42 UTC, prydonius approved these changes

2017-06-29 11:41 UTC, merged