[prometheus-cloudwatch-exporter] Added securityContext configuration
helm/charts pull request #12405
Opened 2019-03-20 17:14 UTC by mvisonneau

#### What this PR does / why we need it:

Allow user to specify securityContext configuration onto the pods

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-04-01 20:26 UTC, gianrubio commented on stable/prometheus-cloudwatch-exporter/values.yaml
> +securityContext: {}
Could you specify your recommenced security context here?

2019-04-01 20:27 UTC, gianrubio approved these changes
/ok-to-test

2019-04-02 08:14 UTC, mvisonneau commented on stable/prometheus-cloudwatch-exporter/values.yaml
> +securityContext: {}
done 👍

2019-04-03 09:39 UTC, mvisonneau commented
@gianrubio, I just rebased, should be good to go 👍

2019-05-05 20:18 UTC, davidkarlsen requested changes

2019-05-05 20:18 UTC, davidkarlsen commented on stable/prometheus-cloudwatch-exporter/README.md
> +<<<<<<< HEAD
mergeerror

2019-06-05 10:49 UTC, mvisonneau commented on stable/prometheus-cloudwatch-exporter/README.md
> +<<<<<<< HEAD
indeed, sorry about that 🙇

2019-07-10 11:06 UTC, mvisonneau commented
/assign @nestorsalceda @torstenwalter

2019-07-19 09:35 UTC, torstenwalter commented
/lgtm

2019-07-19 09:47 UTC, merged