Hydra
helm/charts pull request #1241
Opened 2017-06-05 15:22 UTC by 20zinnm

Building off of the work by @kminehart, I produced a more idiomatic and production-ready version of the Hydra chart. We agreed that the changes warranted a new PR.

Supersedes #1022

2017-06-05 16:07 UTC, kminehart commented
Perfect, thank you for doing this.

2017-06-05 16:27 UTC, 20zinnm commented
My pleasure. Thanks for getting the ball rolling on this @kminehart

2017-06-05 17:16 UTC, 20zinnm commented
@Grillz if you'd like to review this one that would be amazing.

2017-06-12 16:41 UTC, unguiculus commented
@k8s-bot ok to test

2017-06-12 17:05 UTC, 20zinnm commented
Fixing.

2017-06-12 17:21 UTC, 20zinnm commented
/cc [@unguiculus]

2017-06-12 20:22 UTC, unguiculus requested changes
Thanks, this looks really good.

2017-06-12 20:22 UTC, unguiculus commented on incubator/hydra/Chart.yaml
> +maintainers:
Use Github usernames. See e. g. https://github.com/kubernetes/charts/blob/master/stable/jenkins/Chart.yaml#L10-L13

2017-06-12 20:22 UTC, unguiculus commented on incubator/hydra/templates/NOTES.txt
> +{{- if and (not .Values.postgresql.enabled) (not .Values.config.hydra.databaseURL ) }}
Nit: Remove the space before the parenthesis (`.databaseURL )`).

2017-06-12 20:22 UTC, unguiculus commented on incubator/hydra/values.yaml
> +imagePullPolicy: "Always"
Why `Always` as default?

2017-06-12 20:22 UTC, unguiculus commented on incubator/hydra/templates/_helpers.tpl
> +{{- default "" .Values.config.hydra.database_url | b64enc | quote -}}
`database_url` -> `databaseURL`

You can remove the `default "" ` if you specify a default value in `values.yaml`.

2017-06-12 23:25 UTC, 20zinnm commented on incubator/hydra/values.yaml
> +imagePullPolicy: "Always"
@unguiculus Hydra is currently pre-release (pre-v1, though generally stable) and pushes out frequent security or other patches. Thus, the intention here was to allow image tags to stabilize (i.e. a v1 tag that is v1.0-v1.X) while still pulling the Docker images, but it's not strictly required.

In the end, there's a reason this is configurable 😛.

2017-06-12 23:26 UTC, 20zinnm commented on incubator/hydra/templates/_helpers.tpl
> +{{- default "" .Values.config.hydra.database_url | b64enc | quote -}}
@unguiculus It needs to be camel case to work as a source for environmental variables.

2017-06-12 23:27 UTC, 20zinnm commented on incubator/hydra/templates/_helpers.tpl
> +{{- default "" .Values.config.hydra.database_url | b64enc | quote -}}
Oh, I mistook the instance you were referring to. I'll change it.

2017-06-13 00:04 UTC, Grillz commented on incubator/hydra/Chart.yaml
> +- hdyra
s/hdyra/hydra

2017-06-13 00:04 UTC, Grillz commented on incubator/hydra/Chart.yaml
> +- jwt
may as well add OIDC while were at it

2017-06-13 00:07 UTC, Grillz commented
Aside from the semantic tag stuff, this looks really solid. Awesome work @20zinnm and @kminehart ! 👍

2017-06-13 00:53 UTC, 20zinnm commented
@Grillz Added the tags. I believe that's a wrap 👍

2017-06-13 01:48 UTC, 20zinnm commented on incubator/hydra/Chart.yaml
> +- jwt
Added with 9dfbaa8.

2017-06-13 01:48 UTC, 20zinnm commented on incubator/hydra/Chart.yaml
> +maintainers:
Fixed with 82c507c.

2017-06-13 01:50 UTC, 20zinnm commented
@unguiculus I made the requested changes. Please let me know when you have a chance to look over it for final review.

2017-06-13 16:43 UTC, unguiculus requested changes
I deployed it with defaults on a GKE cluster. Calling the load balancer URL on port 4444 returns this:

`{"error":{"code":500,"message":"Can not serve request over insecure http"}}`

Here's the log.

```
$ kubectl logs --namespace default $(kubectl get pods -l "app=hydra" -o jsonpath="{.items[0].metadata.name}") -c hydra                                                               ± ★ 〜 ⫘ (9dfbaa8)
Applying `ladon` SQL migrations...
Applied 0 `ladon` SQL migrations.
Applying `group` SQL migrations...
Applied 0 `group` SQL migrations.
Applying `client` SQL migrations...
Applied 0 `client` SQL migrations.
Applying `oauth2` SQL migrations...
Applied 0 `oauth2` SQL migrations.
Applying `jwk` SQL migrations...
Applied 0 `jwk` SQL migrations.
Migration successful! Applied a total of 0 SQL migrations.
Migration successful!
time="2017-06-13T16:40:40Z" level=info msg="Connecting with postgres://*:*@ironic-stoat-postgresql/hydra?sslmode=disable"
time="2017-06-13T16:40:40Z" level=info msg="Connected to SQL!"
time="2017-06-13T16:40:40Z" level=info msg="Setting up telemetry - for more information please visit https://ory.gitbooks.io/hydra/content/telemetry.html"
time="2017-06-13T16:40:40Z" level=info msg="Setting up http server on :4444"
time="2017-06-13T16:40:40Z" level=info msg="TLS termination enabled, disabling https."
time="2017-06-13T16:40:44Z" level=info msg="started handling request" method=GET remote="10.28.2.1:37524" request="/health"
time="2017-06-13T16:40:44Z" level=warning msg="Could not serve http connection" error="X-Forwarded-Proto header is missing"
time="2017-06-13T16:40:44Z" level=error msg="An error occurred while handling a request" code=502 details=[] error="Can not serve request over insecure http" reason= request-id= status= trace="Stack trace:
github.com/ory/hydra/cmd/server.(*Handler).rejectInsecureRequests
	/go/src/github.com/ory/hydra/cmd/server/handler.go:165
github.com/ory/hydra/cmd/server.(*Handler).(github.com/ory/hydra/cmd/server.rejectInsecureRequests)-fm
	/go/src/github.com/ory/hydra/cmd/server/handler.go:69
github.com/ory/hydra/vendor/github.com/urfave/negroni.HandlerFunc.ServeHTTP
	/go/src/github.com/ory/hydra/vendor/github.com/urfave/negroni/negroni.go:24
github.com/ory/hydra/vendor/github.com/urfave/negroni.middleware.ServeHTTP
	/go/src/github.com/ory/hydra/vendor/github.com/urfave/negroni/negroni.go:33
github.com/ory/hydra/vendor/github.com/urfave/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/ory/hydra/vendor/github.com/urfave/negroni/negroni.go:33
github.com/ory/hydra/vendor/github.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP
	/go/src/github.com/ory/hydra/vendor/github.com/meatballhat/negroni-logrus/middleware.go:135
github.com/ory/hydra/vendor/github.com/urfave/negroni.middleware.ServeHTTP
	/go/src/github.com/ory/hydra/vendor/github.com/urfave/negroni/negroni.go:33
github.com/ory/hydra/vendor/github.com/urfave/negroni.(middleware).ServeHTTP-fm
	/go/src/github.com/ory/hydra/vendor/github.com/urfave/negroni/negroni.go:33
github.com/ory/hydra/metrics.(*MetricsManager).ServeHTTP
	/go/src/github.com/ory/hydra/metrics/middleware.go:133
github.com/ory/hydra/vendor/github.com/urfave/negroni.middleware.ServeHTTP
	/go/src/github.com/ory/hydra/vendor/github.com/urfave/negroni/negroni.go:33
github.com/ory/hydra/vendor/github.com/urfave/negroni.(*Negroni).ServeHTTP
	/go/src/github.com/ory/hydra/vendor/github.com/urfave/negroni/negroni.go:73
github.com/ory/hydra/vendor/github.com/gorilla/context.ClearHandler.func1
	/go/src/github.com/ory/hydra/vendor/github.com/gorilla/context/context.go:141
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1942
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2568
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1825
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197" writer=JSON
time="2017-06-13T16:40:44Z" level=info msg="completed handling request" measure#hydra.example.com.latency=393805 method=GET remote="10.28.2.1:37524" request="/health" status=502 text_status="Bad Gateway" took=393.805µs
```

2017-06-13 16:43 UTC, unguiculus commented on incubator/hydra/values.yaml
> +imagePullPolicy: "Always"
If I specify a version like `v0.9.1` I would not expect it to change. If this is actually the case, then `Always` should be a conscious choice. I'd suggest you change the default to `IfNotPresent`.

2017-06-13 16:43 UTC, unguiculus commented on incubator/hydra/templates/NOTES.txt
> +  echo http://$SERVICE_IP/
Port is missing

2017-06-13 20:21 UTC, 20zinnm commented on incubator/hydra/templates/NOTES.txt
> +  echo http://$SERVICE_IP/
I think the idea here is that it's proxied to :80, since it's a load balancer, no?

2017-06-13 20:24 UTC, 20zinnm commented
@unguiculus When behind a load balancer, it needs a correct HTTPS_ALLOW_TERMINATION_FROM environmental variable. However, I've found that for some reason GCE load balancers don't send the correct headers downstream, so you can manually disable HTTPS behind a load balancer by adding `--dangerous-force-http`.

I wasn't able to identify the issue but I think it has more to do with GCE than Hydra.

2017-06-13 20:28 UTC, 20zinnm commented
Oh, @unguiculus Hydra cannot work with ingress out of the box because it requires SSL or SSL termination. Try setting `config.http.allowTerminationFrom` to whatever range GCE uses (I believe it's `10.0.0.0/8`.

I'll look into it more, but generally speaking Hydra shouldn't be publically accessible without SSL.

2017-06-14 16:36 UTC, 20zinnm commented
So what I've found out is that GCE load balancer for whatever reason are not adding the correct proxy headers. Thus, try NodePort and disable SSL termination.

2017-06-14 16:37 UTC, 20zinnm commented
Or use an ingress and properly configure it.

2017-06-14 17:29 UTC, unguiculus commented on incubator/hydra/templates/NOTES.txt
> +  echo http://$SERVICE_IP/
`service.port`is `4444`. That's what is used. This port must be added here.

2017-06-14 17:31 UTC, unguiculus commented
We have the general assumption that a chart should come up successfully with defaults. Is this somehow feasible? You cannot expect us to do more extensive tests.

2017-06-14 20:11 UTC, 20zinnm commented
@unguiculus I don't think that's feasible for a secure-by-default Hydra installation. Due to the nature of Hydra (which necessitates SSL/TLS for basic functionality) I don't think this chart should work with defaults. Of course, it could be configured to dump SSL/TLS (with the `--dangerous-force-http` flag), but that makes it more difficult to use it securely.

I could add in the notes that Hydra can only be exposed publicly (via the Ingress) with SSL, and that for internal use NodePort with `--dangerous-force-http` could work. Or should I add a boolean value?

2017-06-15 16:40 UTC, meyerzinn commented
I'm going on a trip for about 12 days and won't be in internet range. Let's pick this up when I get back, unless someone else wants to make the changes.

2017-07-19 19:28 UTC, unguiculus commented
Marking as stale. Please update within the next week.

2017-07-20 18:46 UTC, 20zinnm commented
Sorry, been really busy. Will see if I find some time soon.

2017-07-23 21:40 UTC, 20zinnm commented
@unguiculus Not sure what the conclusion was as to whether Hydra should be secure-by-default. It's not possible to set up Hydra publicly to be secure because of the transport security requirement, but the ingress is not the default exposure so it should come up fine by default.

2017-07-28 05:37 UTC, unguiculus requested changes
OK, I'd suggest you add some more documentation to the README and also some prominent message to the NOTES. Here's an example for NOTES from Datadog to illustrate what I mean.

https://github.com/kubernetes/charts/blob/master/stable/datadog/templates/NOTES.txt

We should just make sure we fail gracefully and the user gets directions how they can make things work.

2017-07-28 05:37 UTC, unguiculus commented on incubator/hydra/README.md
> +[Hydra](https://github/ory/hdya) offers OAuth 2.0 and OpenID Connect Core 1.0 capabilities as a service. Hydra is different, because it works with any existing authentication infrastructure, not just
The Github link is incorrect.

2017-08-13 12:26 UTC, unguiculus commented
Marking this as stale. Please update within one week.

2017-08-21 17:12 UTC, unguiculus commented
Closing this as stale. Feel free to reopen if/when you decide to work on this again.

2017-08-21 17:12 UTC, closed without merging

2017-10-28 01:59 UTC, alonl commented
@20zinnm I'll be very happy to see this on air :)

2019-01-26 18:55 UTC, haf commented
@unguiculus How about merging this and letting the community work on it? The author is right that Google's L7 LB has issues with SNI and requires manual intervention to bootstrap TLS certificates; and at the same time, a security-critical piece of infrastructure like Ory Hydra has a functional requirement not to be accessible unless the channel is encrypted. I would deploy this with certmanager and let's encrypt via nginx-ingress, traefik or envoy ingresses; and that's out of scope for this chart.

2019-07-18 09:22 UTC, aeneasr commented
In case this was missed, we have now official helm charts: https://k8s.ory.sh/helm/