Add ingress to gitlab-ce chart
helm/charts pull request #1251
Opened 2017-06-06 12:14 UTC by RyanHartje

Added an ingress template based on what I see for Jenkins.

Please let me know if further documentation is needed or if there are any style suggestions or other possible improvements.

2017-06-14 20:37 UTC, unguiculus requested changes

2017-06-14 20:37 UTC, unguiculus commented on stable/gitlab-ce/templates/ingress.yaml
> +  name: {{ template "fullname" . }}
Add standard labels.

2017-06-25 20:31 UTC, RyanHartje commented on stable/gitlab-ce/templates/ingress.yaml
> +  name: {{ template "fullname" . }}
I've added labels below this, thanks for the feedback

2017-07-06 18:34 UTC, RyanHartje commented on stable/gitlab-ce/templates/ingress.yaml
> +  name: {{ template "fullname" . }}
@unguiculus does this cover standard labels appropriately?

2017-07-20 17:54 UTC, unguiculus commented
@k8s-bot ok to test

2017-07-20 17:54 UTC, unguiculus approved these changes

2017-07-28 06:28 UTC, unguiculus commented on stable/gitlab-ce/templates/ingress.yaml
> +  name: {{ template "fullname" . }}
Sorry for the late feedback. With respect to the existing chart, it does. For new charts, the recommendation is to use `{{ template "name" . }}` for the `app` label.

2017-07-28 07:11 UTC, merged