[stable/parse] deploys a parse server and optionally the parse dashboard
helm/charts pull request #1256
Opened 2017-06-07 10:26 UTC by sameersbn

2017-06-24 09:32 UTC, unguiculus requested changes
Please apply best practices for standard labels, especially the `app` label. 

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md

2017-07-20 17:57 UTC, unguiculus commented
Marking as stale. Please update within the next week.

2017-07-28 05:40 UTC, unguiculus commented
Closing as stale. Feel free to re-open if/when you decide to work on this again.

2017-07-28 06:20 UTC, sameersbn commented
Sorry, I missed your earlier comment.
I've applied the standard labels to the Deployment templates as and updated the image versions, etc.

2017-07-29 15:26 UTC, unguiculus requested changes
The `app` label should be `{{ template "name" . }}`.

2017-07-29 15:26 UTC, unguiculus commented on stable/parse/templates/_helpers.tpl
> +We truncate at 24 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
24 -> 63

2017-07-29 16:47 UTC, sameersbn commented on stable/parse/templates/_helpers.tpl
> +We truncate at 24 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
fixed!

2017-07-29 16:47 UTC, sameersbn commented
applied the required changes. thanks for the review.

2017-07-29 18:51 UTC, unguiculus requested changes

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "fullname" . }},component={{ .Chart.Name }}" -o jsonpath="{.items[0].metadata.name}")
`"app={{ template "fullname" . }},component={{ .Chart.Name }}"` -> `"app={{ template "name" . }},component={{ .Chart.Name }},release={{ .Release.Name }}"`

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "fullname" . }},component={{ .Chart.Name }}-dashboard" -o jsonpath="{.items[0].metadata.name}")
`"app={{ template "fullname" . }},component={{ .Chart.Name }}"` -> `"app={{ template "name" . }},component={{ .Chart.Name }},release={{ .Release.Name }}"`

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/dashboard-deployment.yaml
> +      labels:
Only `app`, `release`, and `component` labels should be added here.

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/server-deployment.yaml
> +      labels:
Only `app`, `release`, and `component` labels should be added here.

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/dashboard-deployment.yaml
> +  labels:
Add `component: "{{ .Chart.Name }}-dashboard"` label.

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/server-deployment.yaml
> +  labels:
Add `component: "{{ .Chart.Name }}"` label.

For consistency, how about using `name: {{ template "fullname" . }}-server` and `component: "{{ .Chart.Name }}-server"`. Actually, I would not even add the chart name to the components at all.

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/svc.yaml
> +  loadBalancerIP: {{ default "" .Values.loadBalancerIP | quote }}
Remove `default ""` and just add an empty default to `values.yaml`.

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/secrets.yaml
> +  master-key: {{ default "" .Values.parse.masterKey | b64enc | quote }}
No need to add `default "" `.

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/dashboard-deployment.yaml
> +        imagePullPolicy: {{ default "" .Values.parseDashboard.imagePullPolicy | quote }}
No need to add `default "" `.

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/server-deployment.yaml
> +        imagePullPolicy: {{ default "" .Values.parse.imagePullPolicy | quote }}
No need to add `default "" `.

2017-07-29 18:51 UTC, unguiculus commented on stable/parse/templates/secrets.yaml
> +  parse-dashboard-password: {{ default "" .Values.parseDashboard.password | b64enc | quote }}
No need to add `default "" `.

2017-07-30 08:49 UTC, sameersbn commented
updated! thanks for the review.

2017-07-30 11:43 UTC, unguiculus requested changes
Thanks for updating.

2017-07-30 11:43 UTC, unguiculus commented on stable/parse/values.yaml
> +  resources:
We've started recommending not to specify default resources. It's usually better to leave this a conscious choice of the user. If defaults are too high, charts may not come up successfully, especially on Minikube.

2017-07-30 11:43 UTC, unguiculus commented on stable/parse/values.yaml
> +parse:
Values are grouped under `parse` and `parseDashboard`. I think it would make sense to use `server` and `dashboard` which reflect the component names.

2017-07-31 05:15 UTC, sameersbn commented
updated!

2017-07-31 14:18 UTC, unguiculus approved these changes

2017-07-31 14:20 UTC, unguiculus commented
/re-test

2017-07-31 14:45 UTC, merged