[stable/sugarcrm] adds chart to deploy SugarCRM
helm/charts pull request #1257
Opened 2017-06-07 10:42 UTC by sameersbn

2017-06-24 09:33 UTC, unguiculus requested changes
Please apply best practices for standard labels, especially the `app` label. 

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md

2017-07-03 07:32 UTC, spesnova commented
@sameersbn 

It looks this chart doesn't work with AWS ELB.

I tried to install this chart to a Kubernetes cluster (1.6+) on AWS. All resources were created correctly. I could see pods were ready status, an ELB was created. But ELB healthcheck result did not change to healthy.  I guess sugarcrm container's redirecting is the cause.

> If the load balancer receives any response other than "200 OK" within the response timeout period, the instance is considered unhealthy.

http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html

So sugarcrm(apache) should not redirect traffic from ELB.

2017-07-20 17:56 UTC, unguiculus commented
Marking as stale. Please update within the next week.

2017-07-28 05:40 UTC, unguiculus commented
Closing as stale. Feel free to re-open if/when you decide to work on this again.

2017-07-28 11:38 UTC, sameersbn commented
updated chart with suggested changes.

2017-07-29 15:23 UTC, unguiculus requested changes
The `app` label should be `{{ template "name" . }}`.

2017-07-29 15:23 UTC, unguiculus commented on stable/sugarcrm/templates/_helpers.tpl
> +We truncate at 24 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
24 -> 63

2017-07-29 15:23 UTC, unguiculus commented on stable/sugarcrm/templates/_helpers.tpl
> +We truncate at 24 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
24 -> 63

2017-07-29 17:13 UTC, sameersbn commented
updated the pull-request with the required changes.

2017-07-29 17:15 UTC, sameersbn commented
updated with the required changes.

2017-07-29 18:51 UTC, unguiculus requested changes

2017-07-29 18:51 UTC, unguiculus commented on stable/sugarcrm/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "fullname" . }}" -o jsonpath="{.items[0].metadata.name}")
`"app={{ template "fullname" . }}"` -> `"app={{ template "name" . }},release={{ .Release.Name }}"`

2017-07-29 18:51 UTC, unguiculus commented on stable/sugarcrm/templates/deployment.yaml
> +      labels:
Only `app` and `release` label should be added here.

2017-07-29 18:51 UTC, unguiculus commented on stable/sugarcrm/templates/svc.yaml
> +    app: {{ template "name" . }}
Add `release` label to selector.

2017-07-29 18:51 UTC, unguiculus commented on stable/sugarcrm/templates/deployment.yaml
> +        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
No need to add `default "" `.

2017-07-29 18:51 UTC, unguiculus commented on stable/sugarcrm/templates/deployment.yaml
> +          value: {{ default "" .Values.sugarcrmUsername | quote }}
No need to add `default "" ` if you add an empty default to `values.yml`. Apply where applicable in the whole chart.

2017-07-30 13:09 UTC, sameersbn commented
updated! thanks for the review,

2017-07-30 14:37 UTC, unguiculus requested changes

2017-07-30 14:37 UTC, unguiculus commented on stable/sugarcrm/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "name" . }}" -o jsonpath="{.items[0].metadata.name}")
`"app={{ template "name" . }}"` -> `"app={{ template "name" . }}",release="{{ .Release.Name }}"`

2017-07-31 04:22 UTC, sameersbn commented on stable/sugarcrm/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "name" . }}" -o jsonpath="{.items[0].metadata.name}")
good catch!

2017-07-31 04:33 UTC, sameersbn commented
updated! thanks for the in-depth review. great work!

2017-07-31 14:29 UTC, unguiculus approved these changes

2017-07-31 14:47 UTC, merged