cluster-autoscaler: support managed identity extension in Azure
helm/charts pull request #12606
Opened 2019-03-27 23:38 UTC by steved

#### What this PR does / why we need it:

cluster-autoscaler supports the `ARM_USE_MANAGED_IDENTITY_EXTENSION` flag in Azure. The only other [requirements are the subscription ID and resource group](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/examples/cluster-autoscaler-vmss-msi.yaml).

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-03-28 09:42 UTC, cpanato requested changes
missing a {{- end }} in the end of the templates/deployment.yaml and also need to add a space in `{{-end }}` line 164 in the same file

2019-03-28 17:12 UTC, steved commented
Fixed, thanks!

2019-04-22 14:15 UTC, cpanato approved these changes

2019-04-22 14:15 UTC, cpanato commented
/ok-to-test

2019-04-22 14:21 UTC, cpanato commented
/test pull-charts-e2e

2019-04-22 16:33 UTC, davidkarlsen commented
/retest

2019-04-29 19:05 UTC, mattfarina approved these changes

2019-04-29 19:05 UTC, mattfarina commented
/lgtm

2019-04-29 21:26 UTC, davidkarlsen requested changes

2019-04-29 21:26 UTC, davidkarlsen commented on stable/cluster-autoscaler/Chart.yaml
> +version: 0.12.3
```suggestion
version: 0.12.4
```

2019-04-29 21:53 UTC, steved commented on stable/cluster-autoscaler/Chart.yaml
> +version: 0.12.3
Thanks, hazards of a long-lived PR :)

2019-05-06 17:15 UTC, mattfarina commented
/lgtm

2019-05-06 17:29 UTC, merged