Fix typo of orgWhitelist value
helm/charts pull request #12620
Opened 2019-03-28 10:30 UTC by jbuettnerbild

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2019-04-25 12:53 UTC, lkysow commented
Sorry I'm just seeing this now. For some reason I didn't get auto-assigned. Thanks for the PR! You'll need to rebase off of master and then you also have to bump the Chart version for the PR to be mergeable.

2019-04-25 12:53 UTC, lkysow commented
/assign me

2019-04-26 07:05 UTC, jbuettnerbild commented
maybe i did't merge correctly.

2019-04-26 10:58 UTC, davidkarlsen requested changes

2019-04-26 10:58 UTC, davidkarlsen commented on stable/atlantis/Chart.yaml
> -version: 3.0.0
This should not be removed but rather bumped

2019-04-26 12:16 UTC, lkysow commented on stable/atlantis/Chart.yaml
> +version: 3.0.1
```suggestion
version: 3.1.1
```

Another PR was merged today, sorry for the pain.

2019-04-26 18:35 UTC, lkysow requested changes

2019-04-26 18:35 UTC, lkysow commented on stable/atlantis/README.md
> +| `allowRepoConfig`                           | Whether to allow the use of [atlantis.yaml files](https://www.runatlantis.io/docs/atlantis-yaml-reference.html).
So you're adding all of these back now which were removed by https://github.com/helm/charts/pull/13253. Please rebase and ensure this changeset only has your changes.

2019-06-09 19:02 UTC, closed without merging