[redis-ha] Added sysctl init container same as in stable/redis
helm/charts pull request #12633
Opened 2019-03-28 15:00 UTC by killmeplz

#### What this PR does / why we need it:

Includes options to make host kernel modifications. Especially somaxconn and THP disable

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2019-03-28 15:09 UTC, killmeplz commented
/assign @ssalaues

2019-04-09 09:26 UTC, killmeplz commented
@ssalaues

2019-04-09 20:43 UTC, ssalaues requested changes
Seems like your changes don't install properly. I tested it as you outlined in the README and resulted in no pods being deployed with an error on the StatefulSet:
```
  Warning  FailedCreate  3s (x15 over 44s)  statefulset-controller  create Pod redis-ha-server-0 in StatefulSet redis-ha-server failed error: Pod "redis-ha-server-0" is invalid: spec.initContainers[0].volumeMounts[0].name: Not found: "host-sys"
```

2019-04-09 20:43 UTC, ssalaues commented on stable/redis-ha/templates/redis-ha-statefulset.yaml
> +        - name: host-sys
This volume mount seems like it should reference a `volume` like these https://github.com/helm/charts/blob/master/stable/redis-ha/templates/redis-ha-statefulset.yaml#L213

Otherwise the StatefulSet doesn't know what to actually mount.

2019-04-10 11:14 UTC, killmeplz commented
Indeed, I probably forgot this last piece

2019-04-11 23:43 UTC, ssalaues commented
/ok-to-test

2019-04-11 23:46 UTC, ssalaues commented
@killmeplz looks good and worked exactly as described. Just fix up the conflict and I'll approve (another PR was merged so the versions are likely conflicting)

2019-04-15 10:29 UTC, killmeplz commented
@ssalaues That should be all

2019-04-15 11:52 UTC, paulczar commented
/lgtm

2019-04-15 12:22 UTC, merged