var for scoping to namespace
helm/charts pull request #12670
Opened 2019-03-29 14:05 UTC by ryandawsonuk

fixes https://github.com/helm/charts/issues/12669 by effectively re-applying https://github.com/datawire/ambassador/pull/657

Using the term 'scope' as I think that makes it clearer that it sets what ambassador will watch. More like https://github.com/helm/charts/blob/d2a6482b3e374a52d8dbb904a6004dfe99231b86/incubator/aws-alb-ingress-controller/values.yaml#L28 and https://github.com/helm/charts/blob/cbd5e811a44c7bac6226b019f1d1810ef5ee45fa/incubator/istio/templates/custom-resources/mixer.yaml#L16

2019-04-01 17:39 UTC, kflynn commented
@Flydiverny thoughts? I'm generally OK with making the Ambassador chart more Helm-like, but we've shifted some other stuff deliberately to the environment recently, and this is shifting single-namespace away from the environment...

2019-04-06 13:23 UTC, Flydiverny commented
/assign

2019-04-08 11:35 UTC, Flydiverny requested changes

2019-04-08 11:35 UTC, Flydiverny commented on stable/ambassador/Chart.yaml
> +version: 2.0.2
Can we set this as `2.1.0` instead

2019-04-08 11:35 UTC, Flydiverny commented
/ok-to-test

2019-04-08 11:38 UTC, Flydiverny commented
Rebase and bump version as suggested and test should prob be ok :)

2019-04-08 13:32 UTC, Flydiverny commented
/lgtm

2019-04-08 13:34 UTC, merged