Add Chart to deploy Couchbase Operator
helm/charts pull request #12682
Opened 2019-03-29 22:01 UTC by tahmmee

Signed-off-by: Tommie McAfee <tommie@couchbase.com>

#### What this PR does / why we need it:
The Chart helps Kubernetes administrators to deploy the Couchbase Operator for deploying and managing Couchbase Clusters.  
Manual deployment of the operator requires the creation of the following resources which are automatically (and optionally) installed by this chart:

```
RESOURCES:
==> v1/ServiceAccount
NAME                                               AGE
unrealized-tarsier-couchbase-admission-controller  1h
unrealized-tarsier-couchbase-operator              1h

==> v1beta1/ClusterRole
unrealized-tarsier-couchbase-admission-controller  1h
unrealized-tarsier-couchbase-operator              1h

==> v1/ClusterRoleBinding
unrealized-tarsier-couchbase-admission-controller  1h

==> v1beta1/ClusterRoleBinding
unrealized-tarsier-couchbase-operator  1h

==> v1beta1/MutatingWebhookConfiguration
unrealized-tarsier-couchbase-admission-controller  1h

==> v1beta1/ValidatingWebhookConfiguration
unrealized-tarsier-couchbase-admission-controller  1h

==> v1/Secret
unrealized-tarsier-couchbase-admission-controller  1h

==> v1/Service
unrealized-tarsier-couchbase-admission-controller  1h

==> v1/Deployment
unrealized-tarsier-couchbase-admission-controller  1h
unrealized-tarsier-couchbase-operator              1h
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

2019-04-03 09:21 UTC, cpanato commented on incubator/couchbase-operator/.helmignore
> +*.tmproj
add OWNERS here as well

2019-04-16 20:17 UTC, tahmmee commented
Hey @cpanto and @prydonius,
Let me know if any additional changes are needed here.

2019-05-09 12:55 UTC, cpanato commented on incubator/couchbase-operator/templates/admission-cluster-role-binding.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
can you update the labels to use the new ones? if you use the latest helm when you create the project it already add the new lables, but here is for reference https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#metadata

2019-06-26 17:16 UTC, tahmmee commented
Hey @cpanto, added the requested change, let me know if anything else needed.
Thanks!

2019-07-01 19:39 UTC, tahmmee commented
Hi @prydonius Looks like you were requested for a review here, can you have a look?

2019-07-17 11:54 UTC, cpanato commented on incubator/couchbase-operator/templates/admission-deployment.yaml
> +      app: {{ template "admission-controller.name" . }}
wrong label here please update to match

2019-07-17 11:54 UTC, cpanato commented on incubator/couchbase-operator/templates/admission-deployment.yaml
> +        app: {{ template "admission-controller.name" . }}
here as well

2019-07-17 11:55 UTC, cpanato commented on incubator/couchbase-operator/templates/admission-service.yaml
> +    app: {{ template "admission-controller.name" . }}
wrong label

2019-07-17 11:55 UTC, cpanato commented on incubator/couchbase-operator/templates/couchbase-deployment.yaml
> +      app: {{ template "couchbase-operator.name" . }}
same here

2019-07-17 11:55 UTC, cpanato commented on incubator/couchbase-operator/templates/couchbase-deployment.yaml
> +        app: {{ template "couchbase-operator.name" . }}
here

2019-07-17 11:56 UTC, cpanato requested changes
also when you fix the small issues you can move this chart to the stable folder

2019-07-18 20:34 UTC, tahmmee commented
@cpanato all set - thanks!

2019-08-13 06:51 UTC, maorfr commented
/ok-to-test

cc @cpanato

2019-08-15 08:12 UTC, cpanato approved these changes
/lgtm

thanks for the work on this chart!

2019-08-15 08:26 UTC, merged