Add lifecycle hooks option for keycloak container
helm/charts pull request #12783
Opened 2019-04-03 09:10 UTC by radumazi

Signed-off-by: radu mazilu <radumazi2@gmail.com>

#### What this PR does / why we need it:
Adds container lifecycle hooks for the keycloak chart

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
This is my first pull request on github. I went through the documentation but if I missed anything please point it out. Thank you
I'm not sure where I should @-mention the maintainers so I'm doing it here: @unguiculus @thomasdarimont

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-04-03 09:18 UTC, radumazi commented
/assign @thomasdarimont

2019-04-03 15:49 UTC, unguiculus requested changes
Thanks @radumazi. Would you mind sharing what your use case is for this?

2019-04-03 15:49 UTC, unguiculus commented on stable/keycloak/templates/statefulset.yaml
> +          {{- end }}
Please change the formatting to match the existing style:

```yaml
        {{- if .Values.keycloak.lifecycleHooks }}
          lifecycle:
{{ tpl .Values.keycloak.lifecycleHooks . | indent 12 }}
        {{- end }}
```

2019-04-03 15:49 UTC, unguiculus commented on stable/keycloak/values.yaml
> +    #postStart:
Add space after `#`

2019-04-03 15:49 UTC, unguiculus commented on stable/keycloak/Chart.yaml
> +version: 4.8.1
Bump minor version for new feature.

2019-04-03 15:49 UTC, unguiculus commented on stable/keycloak/README.md
> +`keycloak.lifecycleHooks` | Container lifecycle hooks. Passed through the `tpl` function and thus to be configured a string | `""
```suggestion
`keycloak.lifecycleHooks` | Container lifecycle hooks. Passed through the `tpl` function and thus to be configured a string | ``
```

2019-04-04 08:03 UTC, radumazi commented
@unguiculus I made the required modifications. My use case is that I want to export metrics from keycloak in order for prometheus to be able to query them. For that I used this service provider https://github.com/aerogear/keycloak-metrics-spi that can be enabled either from the interface or from the cli, and as I'm building an automated pipeline for deploying keycloak I needed to do it from the cli.

To do so I use these commands found in the service provider docs:
`/opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user $KEYCLOAK_USER --password $KEYCLOAK_PASSWORD
/opt/jboss/keycloak/bin/kcadm.sh update events/config -s "eventsEnabled=true" -s "adminEventsEnabled=true" -s "eventsListeners+=metrics-listener"
/usr/bin/rm -f /opt/jboss/.keycloak/kcadm.config`

Keycloak must be up and running before I use these commands, so my solution was to write a script that runs at the postStart container lifecycle hook and waits for the connection to :8080 to become available, then runs the commands.

If you know of a better way to do this, feel free to correct me

Thank you

2019-04-04 09:32 UTC, unguiculus commented
/ok-to-test

2019-04-08 10:10 UTC, radumazi commented
@unguiculus As I told you, I'm unfamiliar with the process, so I hope it's not a stupid question. Is there anything I more I can do for this pull request? I understand that the lgtm and approved labels needs to be added. Thank you

2019-04-08 18:41 UTC, unguiculus commented
@radumazi Please bare with us. I wanted to have @thomasdarimont to have a look as well.

2019-04-08 19:51 UTC, thomasdarimont commented
/lgtm

2019-04-08 20:07 UTC, merged

2019-04-09 06:05 UTC, radumazi commented
@unguiculus I just wasn't sure if there was anything else I should have done, cause it still displayed "changes required". Anyhow, thank you, and have a nice day!