[stable/concourse] Added HPA autoscaling for web component.
helm/charts pull request #12792
Opened 2019-04-03 15:17 UTC by jpds

#### What this PR does / why we need it:

Added HPA values to concourse web component.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-04-03 15:30 UTC, jpds commented
@cirocosta @william-tran This one should be good to go. :)

2019-04-05 12:47 UTC, YoussB commented
/assign

2019-04-09 20:14 UTC, cirocosta commented
/ok-to-test

2019-04-09 20:16 UTC, cirocosta commented
Hi @jpds, thanks for submitting the PR! 

Just adding some more context to the discussion, @YoussB is part of the Concourse team 😁  wdyt about those remarks?

Thanks!

2019-04-09 20:16 UTC, cirocosta commented
/retest

2019-04-10 10:01 UTC, jpds commented
@YoussB I'm not too fussed about autoscaling the workers for my use-case at the moment, which is too run the minimum number of web pods and then autoscale them as developers use the CI system. As for which metrics to use, I do prefer to let the users decide what works for them.

@cirocosta Fixed the version.

2019-04-10 13:07 UTC, YoussB commented
Nice, this can be the first step to autoscaling concourse 😁.
- I would also recommend if we make autoscaling available for workers too and let the operators decide their scaling strategy (maybe in a separate PR).
- Can we also follow the same convention we're using with other resources like the [`ingress`](https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L1282). this is also the recommended approach in the [review guide](https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#autoscaling--horizontalpodautoscaler)
I am thinking of something like:
```yaml
## Create HorizontalPodAutoscaler object.
## Ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
##
autoscaling:
  ## enable autoscaling for web nodes
  ##
  enabled: flase
  
  ## minimum number of available replicas
  ##
  minReplicas: 1
  
  ## maximum number of available replicas
  ##
  maxReplicas: 10
  
  ## The metrics upon which the pods will be scaled up/down
  ## exmaple:
  ##   - type: Resource
  ##     resource:
  ##       name: cpu
  ##       targetAverageUtilization: 60
  ##   - type: Resource
  ##     resource:
  ##       name: memory
  ##       targetAverageUtilization: 60
  metrics:
```

let me know your thoughts.

2019-04-10 13:16 UTC, jpds commented
@YoussB Sorry, but that's exactly what I have in this branch, except that this doesn't have a `enabled` option for the autoscaler? I copied over the YAML pieces from the `traefik` chart

2019-04-11 12:47 UTC, YoussB commented
@jpds sorry for the misunderstanding 🤦‍♂️.
I was just suggesting some documentation around the values and the `enabled` for consistency with other parts of the chart.

2019-04-24 08:50 UTC, jpds commented
@cirocosta I think this one's good to go.

2019-04-25 20:23 UTC, cirocosta requested changes
There are some little details to be more consistent with the Chart - having those minor details fixed, it's indeed good to go!

2019-04-25 20:23 UTC, cirocosta commented on stable/concourse/Chart.yaml
> +version: 5.2.4
Hey, because this is adding new functionality, this should be a minor bump.

2019-04-25 20:23 UTC, cirocosta commented on stable/concourse/values.yaml
> +  ##
We've been putting references for these resources - for consistency, it'd be good to provide one regarding HPA that people can point to 👍

2019-04-25 20:23 UTC, cirocosta commented on stable/concourse/values.yaml
> +  # autoscaling:
We're keeping these options not using comments in order to parse those, and going with an `enabled` basis would be more consistent with the [reviewing guidelines](https://github.com/helm/charts/blob/ef91306195f2a2cb89349c2729bb8c30065a368b/REVIEW_GUIDELINES.md#autoscaling--horizontalpodautoscaler).

2019-06-08 20:51 UTC, closed without merging