[incubator/acs-engine-autoscaler] Add acs-engine-autoscaler charge
helm/charts pull request #1279
Opened 2017-06-12 00:53 UTC by ritazh

This chart deploys [acs-engine-autoscaler](https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler), a node-level autoscaler for Kubernetes for clusters created with acs-engine.

Tested with commit [f2526da](https://github.com/ritazh/Kubernetes-acs-autoscaler/commit/f2526dad4edf4f1491fa828c9373cfd97c8e2043) on a v1.6.0 k8s.

2017-06-13 03:41 UTC, ritazh commented
@seanknox Would love to get your feedback on this one. Thanks!!! :bowing_woman:

2017-06-13 05:03 UTC, seanknox requested changes
Impressive first chart! Thanks for taking this on.

2017-06-13 05:03 UTC, seanknox commented on incubator/acs-engine-autoscaler/README.md
> +
Hooray! This will be a great chart addition.

2017-06-13 05:03 UTC, seanknox commented on incubator/acs-engine-autoscaler/templates/NOTES.txt
> +
As this chart requires credentials to run, you should output an error if they're missing. Check out https://github.com/kubernetes/charts/blob/master/stable/sumokube/templates/NOTES.txt for one pattern. No point in a user checking pods if core config is missing.

2017-06-13 05:03 UTC, seanknox commented on incubator/acs-engine-autoscaler/templates/_helpers.tpl
> +{{- end -}}
Replace this _helpers.tpl with this one: https://github.com/kubernetes/charts/blob/master/incubator/istio/templates/_helpers.tpl

It enables additional patterns we're trying to establish, such as DRY'ing up the label boilerplate with the helper function.

2017-06-13 05:03 UTC, seanknox commented on incubator/acs-engine-autoscaler/Chart.yaml
> +description: Scales worker nodes within autoscaling groups.
This chart can be in `stable/`. incubator is required only if you're using experimental Kubernetes functionality: alpha APIs, for example.

2017-06-13 05:03 UTC, seanknox commented on incubator/acs-engine-autoscaler/README.md
> +`acsdeployment`| [OPTIONAL] The name of the deployment used to deploy the kubernetes cluster initially. If not provided, it is defaulted to `azuredeploy` | None.
Is there any benefit to configuring the Azure deployment name? Wondering if there's any harm to always using a default name.

2017-06-13 05:03 UTC, seanknox commented on incubator/acs-engine-autoscaler/templates/deployment.yaml
> +    spec:
is the openai label still present in the autoscaler? Just curious.

2017-06-13 05:03 UTC, seanknox commented on incubator/acs-engine-autoscaler/values.yaml
> +  pullPolicy: IfNotPresent
Don't forget to pin image to a specific version tag.

2017-06-13 13:31 UTC, wbuchwalter commented on incubator/acs-engine-autoscaler/README.md
> +`acsdeployment`| [OPTIONAL] The name of the deployment used to deploy the kubernetes cluster initially. If not provided, it is defaulted to `azuredeploy` | None.
This is actually the name that was used to deploy the cluster generated with acs-engine via `az group deployment create ...` .

2017-06-13 13:32 UTC, wbuchwalter commented on incubator/acs-engine-autoscaler/templates/deployment.yaml
> +    spec:
Yep!

2017-06-13 14:36 UTC, wbuchwalter commented on incubator/acs-engine-autoscaler/Chart.yaml
> +description: Scales worker nodes within autoscaling groups.
Should this be changed for "Scales worker nodes within availability sets" ?

2017-06-13 16:41 UTC, ritazh commented on incubator/acs-engine-autoscaler/README.md
> +`acsdeployment`| [OPTIONAL] The name of the deployment used to deploy the kubernetes cluster initially. If not provided, it is defaulted to `azuredeploy` | None.
@seanknox This argument is optional. It is here to support users who have provided a custom Azure deployment name, not using the default `azuredeploy` name at the time of running `az group deployment create `

From the `deployment.yaml`:
```
{{- if .Values.acsenginecluster.acsdeployment}}
            - --acs-deployment 
            - {{ .Values.acsenginecluster.acsdeployment }}
```

2017-06-13 16:58 UTC, seanknox commented on incubator/acs-engine-autoscaler/Chart.yaml
> +description: Scales worker nodes within autoscaling groups.
👍

2017-06-13 19:23 UTC, ritazh commented on incubator/acs-engine-autoscaler/Chart.yaml
> +description: Scales worker nodes within autoscaling groups.
done.

2017-06-13 19:24 UTC, ritazh commented
@seanknox I have made the suggested updates. Once approved, I will squash my commits.

2017-06-13 22:49 UTC, seanknox commented
Looking great. Two minor comments and I'll merge—no need to squash unless you want to, as I can do it at merge time.

2017-06-13 22:49 UTC, seanknox requested changes

2017-06-13 22:49 UTC, seanknox commented on stable/acs-engine-autoscaler/templates/deployment.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
You can replace the manually defined labels with your fancy new `labels.standard` helper function. Example here: https://github.com/kubernetes/charts/blob/master/incubator/istio/templates/addons-grafana-deployment.yaml#L8

2017-06-13 22:49 UTC, seanknox commented on stable/acs-engine-autoscaler/templates/secrets.yaml
> +type: Opaque
Minor nit: for consistency's sake you should add the labels to all K8s resources managed by Helm (again, using `labels.standard`).

2017-06-14 23:39 UTC, seanknox approved these changes
You rock. Thank you Rita!

2017-06-14 23:39 UTC, merged