add kube-lego RBAC support
helm/charts pull request #1287
Opened 2017-06-13 08:48 UTC by SamClinckspoor

Adds support in kube-lego for RBAC.
Permissions sourced https://github.com/jetstack/kube-lego/issues/99 and adjusted slightly.

setting `rbac.enabled` to true will create a role, rolebinding and service account.

2017-06-13 16:47 UTC, unguiculus commented
/cc @jackzampolin

2017-06-27 19:05 UTC, SamClinckspoor commented
pinging for a review

2017-06-28 20:26 UTC, jackzampolin commented
@SamClinckspoor Thanks for the ping. Pulled this down and it looks good. Thanks for adding this! LGTM! 👍

2017-07-12 01:16 UTC, dmccaffery commented
@mgoodness what do we need to do to get this merged? I'd love to have RBAC "official"

2017-08-02 02:15 UTC, mgoodness commented
@dmccaffery give me just a couple more days. I'm on a roll with RBAC-related merges, so we should get this merged pretty quickly.

2017-08-14 22:15 UTC, mgoodness requested changes
Just a few requested changes to conform with the repo-wide RBAC pattern we've adopted. Should be a quick merge after that.

2017-08-14 22:15 UTC, mgoodness commented on stable/kube-lego/templates/deployment.yaml
> +{{- end }}
Use `serviceAccountName: {{ if .Values.rbac.create }}{{ template "fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}`

2017-08-14 22:15 UTC, mgoodness commented on stable/kube-lego/templates/role.yaml
> +  - "extensions"
Nit: don't need quotes around `extensions`

2017-08-14 22:15 UTC, mgoodness commented on stable/kube-lego/templates/role.yaml
> +  - "extensions"
Nit: no quotes required

2017-08-14 22:15 UTC, mgoodness commented on stable/kube-lego/templates/role.yaml
> +  - "*"
We should be explicit, no?

2017-08-14 22:15 UTC, mgoodness commented on stable/kube-lego/values.yaml
> +  enabled: false
Let's make this `create`. Add `rbac.serviceAccountName` and set to `default`.

2017-08-14 22:15 UTC, mgoodness commented on stable/kube-lego/README.md
> +`rbac.enabled` | Enable role and serviceaccount creation | `false`
Update with changes made to `values.yaml`

2017-08-15 09:10 UTC, SamClinckspoor commented
@mgoodness Changed to the new RBAC pattern and also trimmed the role permissions as per https://github.com/jetstack/kube-lego/issues/99#issuecomment-316978562

2017-08-15 13:34 UTC, mgoodness approved these changes

2017-08-15 13:34 UTC, mgoodness commented
/ok-to-test

2017-08-15 13:35 UTC, mgoodness commented
/lgtm

2017-08-15 13:40 UTC, mgoodness commented
CI failure is expected due to the required `LEGO_EMAIL` value (which still needs to be addressed).

2017-08-15 13:40 UTC, merged