[stable/wordpress] Allow more flexible TLS configuration.
helm/charts pull request #12875
Opened 2019-04-06 20:38 UTC by adtennant

#### What this PR does / why we need it:
Allows more flexible TLS configuration. Currently you can't do certain things, e.g. generate certificates that cover multiple hosts. Instead of having a custom structure for TLS this PR reverts to using the standard Ingress structure.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-04-08 08:00 UTC, juan131 requested changes
Hi @adtennant 

Please take a look to my comments! Please also notice that you need to sign every commit or the DCO tests will fail.

2019-04-08 08:00 UTC, juan131 commented on stable/wordpress/values.yaml
> +  tls:
I'd add another boolean parameter "tls.enabled" that allows you specify whether to enable/disable TLS in the Ingress definition.

2019-04-08 08:00 UTC, juan131 commented on stable/wordpress/README.md
>  | `ingress.hosts[0].tls`           | Utilize TLS backend in ingress             | `false`                                                 |
Shouldn't you remove this parameter?

2019-04-11 21:43 UTC, adtennant commented on stable/wordpress/values.yaml
> +  tls:
I feel that's redundant as a blank or missing `tls` section in the ingress indicates that intent and matches up with what other charts do, e.g. `stable/artifactory` (there are many more a quick search for `{{ toYaml .Values.ingress.tls | indent 4 }}` in the repo will find them)

2019-04-12 06:27 UTC, juan131 approved these changes

2019-04-12 06:27 UTC, juan131 commented on stable/wordpress/values.yaml
> +  tls:
Okay, let's keep it your way. I'm okay with this approach.

2019-04-12 06:28 UTC, juan131 commented
/ok-to-test

2019-04-12 06:28 UTC, juan131 commented
/retest

2019-04-12 06:31 UTC, juan131 commented
Could you please rebase from master and bump the version of the chart?

2019-04-12 14:46 UTC, juan131 commented
Hi @adtennant 

I just merged your other PR to unset the nodePort and, as a consequence, the CI complains again about conflicts in the Chart.yml. could you rebase agin?

2019-04-15 07:46 UTC, juan131 commented
/ok-to-test
/lgtm

2019-04-15 07:54 UTC, merged