Add nodeSelector to stable/redis
helm/charts pull request #1290
Opened 2017-06-13 17:57 UTC by cburmeister

This commit adds support for `nodeSelector` and `tolerations` to the
`stable/redis` chart.

2017-06-30 06:30 UTC, unguiculus requested changes

2017-06-30 06:30 UTC, unguiculus commented on stable/redis/README.md
> +| `tolerations`              | Toleration labels for pod assignment  | {}                                                        |
`{}` -> `[]`.

2017-06-30 06:30 UTC, unguiculus commented on stable/redis/values.yaml
> +tolerations: {}
`tolerations: []`

Should be a list.

2017-06-30 16:45 UTC, cburmeister commented
thanks @unguiculus !

2017-07-01 11:47 UTC, unguiculus commented
@k8s-bot ok to test

2017-07-01 11:49 UTC, unguiculus approved these changes

2017-07-01 11:50 UTC, merged