stable/concourse: separate worker, web deployments
helm/charts pull request #12920
Opened 2019-04-08 19:38 UTC by YoussB

#### What this PR does / why we need it:

- Added `.Values.Web.enabled` and `.Values.worker.enabled` (with default to
true).
- if only `.Values.web.enabled` is enabled: only web resources are going to
be created, as well as secrets namespace.
- if only `.Values.worker.enabled` is enabled: only worker resources are going to
be created.
- moved the worker-specific and web-specific secrets each to a separate
file and secrets object.
- added `.Values.concourse.worker.tsa.port` and utilised
`.Values.concourse.worker.host` in order to allow the user to set the
`CONCOURSE_TSA_HOST` easily.
- removed the template `concourse.concourse.fullname` as it is not used
anymore.
- bumped the chart version to 6.0.0, as this adds new ways to use the
chart.
- added the new variables to the README doc.

#### Which issue this PR fixes
  - fixes #11280

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

cc: @taylorsilva

2019-04-08 23:42 UTC, cirocosta commented
/ok-to-test

2019-04-08 23:43 UTC, cirocosta commented
/assign cirocosta

2019-04-09 12:34 UTC, taylorsilva commented
Looks like we forgot to push up the chart version bump. Just need to do that and then this will be good to test.

2019-04-09 16:24 UTC, cirocosta commented
Hey,

Some thoughts that @YoussB and I were talking about when pairing on reviewing the PR:


- we could make required that either one or both of `{web|worker}.enabled` is set to `true`,
- given that the chart now internally creates and uses two secrets (one for the workers, another for the web components), there is a breaking change for consumers of the chart who are bringing their own secrets (which is what we recommend)
- add a `required` to `concourse.worker.tsa.host` to ensure that when `web` is not enabled, we fail there
- PostgreSQL dependency could have a check for `web.enabled`

Also, as follow-ups:

- we can also go ahead with https://github.com/helm/charts/issues/11512 and provide the first documentation of breaking changes (in a separate PR).
- we can leave `worker-key-pub` out of `worker-secrets` and `worker-statefulset` as that's not needed (this can be done in a separate PR)
- we could have the labels updated to ensure that they all match the new ones (https://github.com/helm/charts/blob/2e42062101349b82aa9995bfc8e2db88870bc1c8/REVIEW_GUIDELINES.md#metadata) - also in a separate PR
- perhaps on the Concourse team side, we might want to have some coverage regarding RBAC (separate PR, in the `concourse/concourse` repository)
- `concourse.worker.tsa.hosts` could be an array that takes multiple TSA hosts (separate PR)

Thanks!

2019-04-12 14:10 UTC, YoussB commented
Some thoughts that @YoussB and I were talking about when pairing on reviewing the PR:

- [x] we could make required that either one or both of {web|worker}.enabled is set to true. **added a hacky way to check if either of the worker or web are enabled.**
- given that the chart now internally creates and uses two secrets (one for the workers, another for the web components), there is a breaking change for consumers of the chart who are bringing their own secrets (which is what we recommend)
- add a required to concourse.worker.tsa.host to ensure that when web is not enabled, we fail there
- PostgreSQL dependency could have a check for web.enabled

Also, as follow-ups:

- we can also go ahead with #11512 and provide the first documentation of breaking changes (in a separate PR).
- we can leave worker-key-pub out of worker-secrets and worker-statefulset as that's not needed (this can be done in a separate PR)
- we could have the labels updated to ensure that they all match the new ones (https://github.com/helm/charts/blob/2e42062101349b82aa9995bfc8e2db88870bc1c8/REVIEW_GUIDELINES.md#metadata) - also in a separate PR
- perhaps on the Concourse team side, we might want to have some coverage regarding RBAC (separate PR, in the concourse/concourse repository)
- concourse.worker.tsa.hosts could be an array that takes multiple TSA hosts (separate PR)

2019-04-12 22:16 UTC, YoussB commented
@cirocosta ready for testing 😁

2019-04-15 01:45 UTC, cirocosta commented
/retest

2019-04-17 21:30 UTC, cirocosta requested changes
Hey,

I've made quite a few suggestions in terms of phrasing, feel free to not accept them right away 😁  I tried making them a bit more coherent to the rest of the comments & docs, let me know what you think!

The overall functionality seems good to me 👍  Thanks for adding the `breaking changes` too!

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/CHANGELOG.md
> +- added the ability to create worker only and web only deployments using web.enabled and worker.enabled
A little bit of "formatting":

```suggestion
- added the ability to create worker only and web-only deployments using `web.enabled` and `worker.enabled`
```

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/CHANGELOG.md
> +- **[breaking]** worker and web secrets are now separated into 2 different templates, `worker-secrets.yaml` and `web-secrets.yaml`. users bringing their own secrets will have to split them into 2 dif
Whops, forgot capitalizing `users` there.

```suggestion
- **[breaking]** worker and web secrets are now separated into 2 different templates, `worker-secrets.yaml` and `web-secrets.yaml`. Users bringing their own secrets will have to split them into 2 different k8s objects.
```

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/README.md
> +| `web.enabled` | enable or disable the web component | `true` |
```suggestion
| `web.enabled` | Enable or disable the web component | `true` |
```

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/README.md
> +| `worker.enabled` | enable or disable the worker component. you should set postgres.enabled=false in order not to get an unnecessary postgres chart deployed | `true` |
```suggestion
| `worker.enabled` | Enable or disable the worker component. You should set postgres.enabled=false in order not to get an unnecessary Postgres chart deployed | `true` |
```

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/README.md
> +all the worker-specific secrets, namely, `workerKey`, `workerKeyPub`, `hostKeyPub` are to be added to a separate Kubernetes secrets object with the name [release name]-worker.
```suggestion
All the worker-specific secrets, namely, `workerKey`, `workerKeyPub`, `hostKeyPub` are to be added to a separate Kubernetes secrets object with the name [release name]-worker.
```

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/README.md
> +all other secrets are to be added to a secrets object with the name [release name]-web.
```suggestion
All other secrets are to be added to a secrets object with the name `[release name]-web`.
```

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/README.md
> +for the time being, the secret `workerKeyPub` is to be added to both the worker and the web secret objects, until investigated within issue #13019
```suggestion
For the time being, the secret `workerKeyPub` is to be added to both the worker and the web secret objects, until investigated within issue #13019.
```

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/values.yaml
> +  ## enable/disable web component
```suggestion
  ## Enable or disable the web component.
```

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/values.yaml
> +  ## This can allow users to create worker only releases by setting this to false
```suggestion
  ## This allows the creation of worker-only releases by setting this to false.
```

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/values.yaml
> +  ## enable/disable worker component
```suggestion
  ## Enable or disable the worker component.
```

2019-04-17 21:30 UTC, cirocosta commented on stable/concourse/values.yaml
> +  ## This can allow users to create web only releases by setting this to false
```suggestion
  ## This allows the creation of web-only releases by setting this to false.
```

2019-04-22 12:41 UTC, YoussB commented
@cirocosta updated!

2019-04-22 12:52 UTC, jonninen50 approved these changes

2019-04-25 20:29 UTC, cirocosta approved these changes
SGTM

2019-04-25 20:29 UTC, cirocosta commented
/lgtm

2019-04-25 20:30 UTC, merged