[stable/prometheus] Fix RBAC permissions (required by kubeadm 1.6)
helm/charts pull request #1295
Opened 2017-06-14 03:36 UTC by zilman

I believe this fixes https://github.com/kubernetes/charts/issues/1075.

I might be over eager here, not sure if alertmanager and node exporter need the service account but Prometheus definitely does.

Tested on a pristine Kubeadm v1.6.4.

2017-06-16 12:13 UTC, tobilarscheid commented
Definitely voting for this, my team faces the same issue!

2017-06-21 16:27 UTC, tobilarscheid requested changes

2017-06-21 16:27 UTC, tobilarscheid commented on stable/prometheus/templates/rbac-setup.yml
> +  name: prometheus
shouldn't this be `name: {{ .Values.kubeStateMetrics.serviceAccountName }}` ?

2017-06-21 16:28 UTC, tobilarscheid requested changes

2017-06-21 16:28 UTC, tobilarscheid commented on stable/prometheus/values.yaml
> +  serviceAccountName: prometheus
same here, this should most definitely be `serviceAccountName: {{ .Values.kubeStateMetrics.serviceAccountName }}`

2017-07-02 09:39 UTC, zilman commented
@tobilarscheid You're 100% correct, I forgot to push with the serviceAccountName not hard coded. Fixed now.

Should be fine to merge now I hope.

2017-07-17 08:32 UTC, tobilarscheid commented
Our team is eagerly waiting for this to get merge, any progress??

2017-07-26 15:01 UTC, tobilarscheid commented
Hi @zilman ,

I am still using what you build here ;-)

Our `kube-state-metrics` kept complaining that access to `deployments`, `resourcequotas` and something else was not allowed. The rule from the official [kube-state-metrics repo](https://github.com/kubernetes/kube-state-metrics/blob/master/kubernetes/kube-state-metrics-cluster-role.yaml) indeed looks a little different than yours - I think yours at least misses
```yaml
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs: ["list", "watch"]
```

and

```yaml
  - resourcequotas
  - replicationcontrollers
  - limitranges
```

under the `""` `apiGroups`.

You might wanna add these :-)

2017-08-02 00:35 UTC, mgoodness commented
Sorry about the delay. I've opted to work with #1443, as it's just a little more complete. I'll get it merged ASAP.

2017-08-02 00:35 UTC, closed without merging