Upgrade Fluent bit 0.11.9
helm/charts pull request #1296
Opened 2017-06-14 18:33 UTC by edsiper

This patch do the following changes:
    
- Use the new Fluent Bit v0.11.9
- Bump chart version to AppVersion 0.1.1
- Update description keywords
    
For more details about Fluent Bit v0.11.9 changes, please visit the following release notes:
    
http://fluentbit.io/announcements/v0.11.9/

2017-06-20 18:26 UTC, kfox1111 commented
This looks good to me.

2017-06-23 21:33 UTC, kfox1111 commented
LGTM

2017-06-24 10:35 UTC, prydonius requested changes

2017-06-24 10:35 UTC, prydonius commented on stable/fluent-bit/Chart.yaml
> +  - name: Eduardo Silva
Any reason you added yourself as a maintainer twice? Also can you use `edsiper` for the name.

2017-06-24 10:35 UTC, prydonius commented on stable/fluent-bit/Chart.yaml
> +version: 0.1.2
should this be 0.1.1?

2017-06-26 16:12 UTC, edsiper commented on stable/fluent-bit/Chart.yaml
> +version: 0.1.2
fixed.

2017-06-26 16:12 UTC, edsiper commented on stable/fluent-bit/Chart.yaml
> +  - name: Eduardo Silva
thanks, using github name now.

2017-06-26 16:13 UTC, edsiper commented
@prydonius thanks for the review, I've updated the commits with the changes suggested

2017-06-26 16:59 UTC, prydonius commented
thanks @edsiper!

@k8s-bot ok to test

2017-06-26 17:05 UTC, prydonius approved these changes

2017-06-26 17:05 UTC, merged