Adds ingress.path documentation
helm/charts pull request #13022
Opened 2019-04-12 21:31 UTC by bantonj

#### What this PR does / why we need it:
When using gce-ingress in Google Cloud the ingress path needs to be set to /*. This note may help others in the future.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed

2019-04-15 13:09 UTC, lkysow requested changes

2019-04-15 13:09 UTC, lkysow commented on stable/atlantis/README.md
> +| `ingress.path`                             | Path to use in the `Ingress`. Should be set to `/*` if using gce-ingress in Google Cloud.
if we're going to document `ingress` we should document all the parameters:
* ingress.enabled
* ingress.annotations
* ingress.path
* ingress.host
* ingress.tls

2019-04-16 01:58 UTC, bantonj commented on stable/atlantis/README.md
> +| `ingress.path`                             | Path to use in the `Ingress`. Should be set to `/*` if using gce-ingress in Google Cloud.
I've added the additional ingress parameters.

2019-04-16 14:59 UTC, lkysow reviewed
You need to bump the version in Chart.yaml so the linting passes.

2019-04-16 15:21 UTC, lkysow approved these changes

2019-04-16 15:22 UTC, lkysow commented
/approve

2019-04-16 15:22 UTC, lkysow commented
/lgtm

2019-04-16 15:29 UTC, merged