add centrifugo chart
helm/charts pull request #1308
Opened 2017-06-15 22:02 UTC by oleh-ozimok

2017-06-15 22:09 UTC, oleh-ozimok commented
CLA signed

2017-07-20 19:15 UTC, unguiculus requested changes
Thanks for your PR.

Please apply best practices for labels. The `app` label should be `{{ template "name" . }}`. Note that this will also require changes to label selectors.

https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

See examples for reference.
https://github.com/kubernetes/helm/tree/master/docs/examples

2017-07-20 19:15 UTC, unguiculus commented on stable/centrifugo/Chart.yaml
> +  - name: Oleh Ozimok
Please use Github username.

Could you add an `icon`?

2017-07-20 19:15 UTC, unguiculus commented on stable/centrifugo/values.yaml
> +  enabled: true
I would not enable ingress by default. The configuration assume there is an Nginx ingress controller. I would not require this by default.

2017-07-20 19:15 UTC, unguiculus commented on stable/centrifugo/values.yaml
> +resources:
We started recommending not to specify defaults for resources. This should always be a conscious choice of the user.

2017-07-29 18:19 UTC, unguiculus requested changes

2017-07-29 18:19 UTC, unguiculus commented on stable/centrifugo/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "fullname" . }}" -o jsonpath="{.items[0].metadata.name}")
`"app={{ template "fullname" . }}"`-> `"app={{ template "name" . }},release={{ .Release.Name }}"`

2017-07-29 18:20 UTC, unguiculus commented
@k8s-bot ok to test

2017-07-30 11:51 UTC, unguiculus requested changes

2017-07-30 11:51 UTC, unguiculus commented on stable/centrifugo/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "name" . }}" -o jsonpath="{.items[0].metadata.name}")
`"app={{ template "name" . }}"` -> `"app={{ template "name" . }},release={{ .Release.Name }}"`

2017-07-30 11:51 UTC, unguiculus commented on stable/centrifugo/README.md
> +
Table incomplete not not correct.

2017-07-30 11:51 UTC, unguiculus commented on stable/centrifugo/values.yaml
> +  admin_password: password
Can you provide the option to use a secret for the password?

2017-07-31 14:44 UTC, unguiculus approved these changes

2017-07-31 14:44 UTC, unguiculus commented
@k8s-bot ok to test

2017-08-08 20:02 UTC, merged