Update svc.yaml
helm/charts pull request #13103
Opened 2019-04-17 07:15 UTC by jbussdieker

Add load balancer source ranges to service

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2019-04-21 21:07 UTC, davidkarlsen requested changes

2019-04-21 21:07 UTC, davidkarlsen commented on stable/kubernetes-dashboard/templates/svc.yaml
> +{{ toYaml .Values.service.LoadBalancerSourceRanges | indent 4 }}
```suggestion
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
```

2019-04-21 21:07 UTC, davidkarlsen commented on stable/kubernetes-dashboard/templates/svc.yaml
> +  loadBalancerSourceRanges:
Also add docs in README

2019-04-23 19:46 UTC, jbussdieker commented on stable/kubernetes-dashboard/templates/svc.yaml
> +{{ toYaml .Values.service.LoadBalancerSourceRanges | indent 4 }}
Updated

2019-04-23 19:46 UTC, jbussdieker commented on stable/kubernetes-dashboard/templates/svc.yaml
> +  loadBalancerSourceRanges:
Added

2019-04-23 20:17 UTC, davidkarlsen commented
/ok-to-test

2019-04-23 20:27 UTC, davidkarlsen commented
/retest

2019-04-23 20:59 UTC, davidkarlsen commented
/retest

2019-04-27 05:34 UTC, jbussdieker commented
Were there any other changes needed?

2019-04-27 09:02 UTC, davidkarlsen approved these changes

2019-04-27 09:02 UTC, davidkarlsen commented
/lgtm

2019-04-27 09:18 UTC, merged