[stable/datadog] Remove default resources requests and limits
helm/charts pull request #13138
Opened 2019-04-18 10:24 UTC by KIVagant

#### What this PR does / why we need it:

Resources should not be limited by default because nobody knows where
the chart will be installed to. Especially worth not to set CPU limits
by default as per https://github.com/kubernetes/kubernetes/issues/67577

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-04-19 16:20 UTC, hkaj requested changes
Thanks for the PR @KIVagant ! 👍 for the CPU limits, that makes total sense. Could we keep the memory limits though? Unbounded memory usage makes me nervous. We don't have any memory leak but it happened in the past and I don't want the agent to cause trouble because of that.
Thanks again

2019-04-19 16:21 UTC, hkaj commented
oh and you'll also need to signoff your commit to satisfy the PR lifecycle hooks :)

2019-04-20 18:47 UTC, KIVagant commented
> Could we keep the memory limits though? Unbounded memory usage makes me nervous. 

Everyone should have the limits in any clusters but they shouldn't be predefined because someone can play with the chart even using local micro K8s. 

You can see how other charts follow the principle:

https://github.com/helm/charts/blob/master/stable/elasticsearch-curator/values.yaml#L79

> oh and you'll also need to signoff your commit to satisfy the PR lifecycle hooks :)

Hmm, I was sure I have done this but maybe not. I'll do on Monday.

2019-04-22 10:16 UTC, KIVagant commented
DCO check finally passed

2019-04-23 08:41 UTC, cpanato commented
@KIVagant can you please update your branch with the latest master and bump the chart version? thanks!

2019-04-23 08:41 UTC, cpanato commented
/assign

2019-04-23 11:49 UTC, hkaj commented
Interesting, I didn't know about this recommendation.

We've seen users being surprised by high memory usage in some cases though (heavy tracing usage for example), and preventing the agent mem usage from growing unbounded is more important to us than making the deployment in minikube simpler.

Besides, it's still possible to override the limits at deployment time right? And IMHO the impact of forgetting to set limits in prod clusters is much worse than the impact of forgetting to unset limits in a minikube deployment.

Does that make sense to you?

2019-04-24 08:14 UTC, KIVagant commented
> Does that make sense to you?

I can suggest the change, but it's always your choice as a maintainer. As for me, I prefer not to have the default limits at all anywhere. But at least, CPU limits should be removed until the related problem is fixed.

2019-04-24 08:19 UTC, KIVagant commented
Rebased from master, bumped the chart version. Feel free to close the PR and if necessary create another one with partial changes.

2019-05-23 16:40 UTC, cpanato commented
/ok-to-test

2019-05-23 16:55 UTC, cpanato approved these changes

2019-05-23 16:55 UTC, cpanato commented
/lgtm

2019-05-23 17:20 UTC, merged