Normalize resource names
helm/charts pull request #1317
Opened 2017-06-19 16:56 UTC by h0tbird

If your helm release name is `kafka` you get:

**Stateful Sets**
*kafka-zookeeper*

**Pods**
*kafka-zookeeper-0*
*kafka-zookeeper-1*
*kafka-zookeeper-2*

**Services**
*kafka-zookeeper* (clients)
*kafka-zookeeper-headless*

2017-07-05 18:41 UTC, unguiculus requested changes
Thanks for this. Much appreciated.

2017-07-05 18:41 UTC, unguiculus commented on incubator/zookeeper/templates/PodDisruptionBudget.yaml
> +    component: {{ template "name" . }}
Rename `component` label to `app`.

2017-07-05 18:41 UTC, unguiculus commented on incubator/zookeeper/templates/PodDisruptionBudget.yaml
> +      component: {{ template "name" . }}
Selector should have `app` and `release` labels.

2017-07-05 18:41 UTC, unguiculus commented on incubator/zookeeper/templates/Service-headless.yaml
> +    component: {{ template "name" . }}
Selector should have `app` and `release` labels.

2017-07-05 18:41 UTC, unguiculus commented on incubator/zookeeper/templates/StatefulSet.yaml
> +        component: {{ template "name" . }}
Add `app` and `release` labels.

2017-07-05 18:41 UTC, unguiculus commented on incubator/zookeeper/templates/StatefulSet.yaml
> +                    - {{ template "name" . }}
Selector should have `app` and `release` labels.

2017-07-05 18:41 UTC, unguiculus commented on incubator/zookeeper/templates/StatefulSet.yaml
> +                         - {{ template "name" . }}
Selector should have `app` and `release` labels.

2017-07-06 10:22 UTC, h0tbird commented
Thank you @unguiculus I have added your requested changes.

2017-07-06 12:35 UTC, h0tbird commented
Notify https://github.com/kubernetes/charts/issues/233 whenever this is merged.

2017-07-06 14:50 UTC, unguiculus requested changes

2017-07-06 14:50 UTC, unguiculus commented on incubator/zookeeper/templates/PodDisruptionBudget.yaml
> +    release: {{.Release.Name | quote }}
Please use consistent formatting. Add space after `{{` and before `}}`. Please fix this everywhere in the chart.

2017-07-06 15:32 UTC, h0tbird commented
@unguiculus now formatting is consistent.

2017-07-11 19:54 UTC, unguiculus commented
Any reason why you are now using `include` vs. `template` for the `app` label? That's uncommon.

While you are at it, would you mind removing the `helm.sh/created` annotation. It does more harm than good, especially on statefulsets.

Moreover, I'd suggest to have file names all lowercase. That's how it is commonly done.

2017-07-12 08:01 UTC, h0tbird commented
I use `include` because it works in combination with `| quote` whereas `template` doesn't.
I tend to use the `quote` function over literal `""` because I don't like nesting quotes.
Nonetheless I am ok reverting this change if you don't like it.

2017-07-13 17:03 UTC, unguiculus approved these changes

2017-07-13 17:03 UTC, unguiculus commented
@k8s-bot ok to test

2017-07-13 17:24 UTC, unguiculus commented
LGTM

/cc @kow3ns @lachie83

2017-07-13 17:41 UTC, unguiculus commented
Just tested it on GKE. Only one pod comes up. The results from the test are actually wrong.
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/charts/1317/pull-charts-e2e/2148/?log#log

2017-07-14 08:50 UTC, h0tbird commented
I can't reproduce the error on my test GKE cluster:
```
[0] ~ >> kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

```
[0] ~ >> helm version            
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

Maybe it is related to https://github.com/kubernetes/helm/issues/2223? Is IPv6 disabled in your GKE cluster? I will downgrade helm to `2.4.2` and test again.

2017-07-14 09:04 UTC, h0tbird commented
Still running helm `2.5.0` I can partially reproduce the issue like this:
```
[0] ~ >> sudo sysctl net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.all.disable_ipv6 = 1
```
```
[0] ~/git/charts/incubator/zookeeper (rename_files|✚1)>> helm install --timeout 600 --name zookeeper --namespace zookeeper --set Cpu=0.1 --set Memory=1Gi --set Heap=1G --set Storage=5Gi .
E0714 11:00:25.190395    5117 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:40249: bind: cannot assign requested address
NAME:   zookeeper
LAST DEPLOYED: Fri Jul 14 11:00:25 2017
NAMESPACE: zookeeper
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/StatefulSet
NAME                 DESIRED  CURRENT  AGE
zookeeper-zookeeper  3        0        1s

==> v1beta1/PodDisruptionBudget
NAME                 MIN-AVAILABLE  ALLOWED-DISRUPTIONS  AGE
zookeeper-zookeeper  2              0                    1s

==> v1/Service
NAME                          CLUSTER-IP    EXTERNAL-IP  PORT(S)            AGE
zookeeper-zookeeper-headless  None          <none>       2888/TCP,3888/TCP  1s
zookeeper-zookeeper           10.3.252.216  <none>       2181/TCP           1s


NOTES:
Thank you for installing ZooKeeper on your Kubernetes cluster. More information
about ZooKeeper can be found at https://zookeeper.apache.org/doc/current/

1. ZooKeeper is not accessible outside of the Kubernetes cluster. Its purpose is
to provide coordination for distributed systems running inside the cluster. As
ZooKeeper uses a TCP based protocol with an internal wire format, you will
probably want to use an existing client library for communication with the
ensemble.

2. The officially maintained clients are written in C and Java, and these can be
obtained with ZooKeeper release from
http://www-us.apache.org/dist/zookeeper/zookeeper-3.4.9/.
A list of language specific bindings and higher level libraries is available
here https://cwiki.apache.org/confluence/display/ZOOKEEPER/ZKClientBindings.

3. Most ZooKeeper clients require a connection string when instantiating an
instance of the client library, or when first connecting the client to the
ensemble. The connection string takes the form
<server>:<port>,<server>:<port>,... . If your ensemble has greater than 1
server, you should provide multiple servers in the connection string to allow
for the client to continue to function in the presence of individual server
failures. It is important that you do not use IP addresses and instead use the
DNS entries for the domain established by the StatefulSet's HeadlessService.
Your connection string should look like zookeeper-zookeeper-headless-0:2181,zookeeper-zookeeper-headless-1:2181,...
You can also use the client Service zookeeper-zookeeper:2181 to connect to an
available ZooKeeper server.
```

But I still can successfully deploy zookeeper anyway.

2017-07-14 14:17 UTC, unguiculus commented
@h0tbird I'm aware of the IPv6 issue. We have that too. From my experience that doesn't do any harm.

I managed to run it successfully now. My cluster did not meet the resource requirements. The defaults the Zookeeper chart specifies are kind of high. We nowadays recommend not to specify any default resources at all if possible.

2017-07-15 12:42 UTC, h0tbird commented
I will remove defaults on Monday, I also think those are too high.

2017-07-18 13:54 UTC, merged