Added log format support to prometheus spec
helm/charts pull request #13192
Opened 2019-04-23 05:39 UTC by stijndehaes

#### What this PR does / why we need it:

It adds support for setting the log format of prometheus so prometheus can log in json format.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-04-23 07:54 UTC, davidkarlsen requested changes

2019-04-23 07:54 UTC, davidkarlsen commented on stable/prometheus-operator/Chart.yaml
> +version: 5.2.1
```suggestion
version: 5.3.0
```

2019-04-23 14:02 UTC, stijndehaes commented on stable/prometheus-operator/Chart.yaml
> +version: 5.2.1
Done

2019-04-29 14:12 UTC, vsliouniaev commented
/ok-to-test

2019-04-29 14:20 UTC, vsliouniaev commented
/lgtm

2019-04-29 14:22 UTC, merged