Add SA to Grafana Test deployment
helm/charts pull request #13205
Opened 2019-04-23 14:23 UTC by dansible

#### What this PR does / why we need it:

#### Which issue this PR fixes
I wasn't able to find an issue for this but the tests fail to run on a cluster with a PSP admission controller. Adding the SA to the deployment resolves this issue.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-04-23 14:39 UTC, dansible commented
/assign @zanhsieh
/assign @rtluckie
/assign @maorfr

2019-04-23 15:27 UTC, zanhsieh approved these changes

2019-04-23 18:05 UTC, maorfr commented
/ok-to-test

2019-04-23 20:19 UTC, dansible commented
/test pull-charts-e2e

2019-04-23 20:37 UTC, dansible commented
hmm... the two tests fail at different points, for reasons that don't seem to be related to the PR. 

Test 1: seems to fail due to not being able to pull the `test-image`:
```
docker: error pulling image configuration: Get https://gcr.io/v2/kubernetes-charts-ci/test-image/blobs/sha256:ae3e206fc03dcb31c3a59f48b8e577deba901bbb41b77170e127d94249930ec1: dial tcp 172.217.212.82:443: i/o timeout.
W0423 18:06:45.876] See 'docker run --help'.
W0423 18:06:45.879] Traceback (most recent call last):
W0423 18:06:45.880] File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0423 18:06:45.880] main(ARGS.env, ARGS.cmd + ARGS.args)
W0423 18:06:45.880] File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0423 18:06:45.880] check(*cmd)
W0423 18:06:45.880] File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0423 18:06:45.880] subprocess.check_call(cmd)
W0423 18:06:45.880] File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0423 18:06:45.880] raise CalledProcessError(retcode, cmd)
W0423 18:06:45.881] subprocess.CalledProcessError: Command '('./test/e2e.sh',)' returned non-zero exit status 125
E0423 18:06:45.886] Command failed
I0423 18:06:45.886] process 642 exited with code 1 after 0.5m
E0423 18:06:45.887] FAIL: pull-charts-e2e
```

Test2 seems to fail because of incompatible helm client/tiller versions and some issue with the Namespace deletion (?):
```
I0423 20:22:29.149] 1 chart(s) linted, no failures
I0423 20:22:29.152] Installing chart 'grafana => (version: "3.3.2", path: "stable/grafana")'...
I0423 20:22:29.865] Error: incompatible versions client[v2.13.1] server[v2.12.2]
I0423 20:22:30.446] ========================================================================================================================
I0423 20:22:30.446] ========================================================================================================================
I0423 20:22:30.446] Deleting release 'grafana-mb8rsb404u'...
I0423 20:22:31.052] Error: incompatible versions client[v2.13.1] server[v2.12.2]
I0423 20:22:31.052] Error deleting Helm release: Error waiting for process: exit status 1
I0423 20:22:31.052] Deleting namespace 'grafana-presubmit-13205-1120784490851995648-mb8rsb404u'...
I0423 20:22:31.572] Error from server (NotFound): namespaces "grafana-presubmit-13205-1120784490851995648-mb8rsb404u" not found
I0423 20:22:31.572] Namespace 'grafana-presubmit-13205-1120784490851995648-mb8rsb404u' did not terminate after 120s.
I0423 20:22:32.142] Namespace 'grafana-presubmit-13205-1120784490851995648-mb8rsb404u' terminated.
I0423 20:22:32.143] Error linting and installing charts: Error processing charts
I0423 20:22:32.143] ------------------------------------------------------------------------------------------------------------------------
I0423 20:22:32.143] ✖︎ grafana => (version: "3.3.2", path: "stable/grafana") > Error waiting for process: exit status 1
I0423 20:22:32.144] ------------------------------------------------------------------------------------------------------------------------
I0423 20:22:32.769] 0be59676ad201dc88b4eea89dfb8899939d3e937e51be42f3d48b808c1e0e4c7
W0423 20:22:32.783] Traceback (most recent call last):
W0423 20:22:32.783] File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0423 20:22:32.784] main(ARGS.env, ARGS.cmd + ARGS.args)
W0423 20:22:32.784] File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0423 20:22:32.784] check(*cmd)
W0423 20:22:32.785] File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0423 20:22:32.785] subprocess.check_call(cmd)
W0423 20:22:32.785] File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0423 20:22:32.785] raise CalledProcessError(retcode, cmd)
W0423 20:22:32.785] subprocess.CalledProcessError: Command '('./test/e2e.sh',)' returned non-zero exit status 1
E0423 20:22:32.785] Command failed
I0423 20:22:32.785] process 643 exited with code 1 after 1.3m
```

Are these tests flaky or is there something I'm missing? Should I just spam more tests? 😅

2019-04-23 20:40 UTC, maorfr commented
there is some work behind the scenes. lets wait with this for a bit :)

2019-04-25 16:04 UTC, dansible commented
I used the same format for the other resources with the exception of the PSP as the `bats` container would not run successfully without `allowPrivilegeEscalation: true` 

The other difference from the chart resources is that the role and rolebinding are only deployed if PSPs have been enabled (not RBAC). The SA gets deployed regardless.

Feel free to request any changes 👍

2019-04-30 18:37 UTC, davidkarlsen requested changes

2019-04-30 18:37 UTC, davidkarlsen commented on stable/grafana/templates/tests/test-role.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
```suggestion
apiVersion: rbac.authorization.k8s.io/v1
```

2019-04-30 18:37 UTC, davidkarlsen commented on stable/grafana/templates/tests/test-rolebinding.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
```suggestion
apiVersion: rbac.authorization.k8s.io/v1
```

2019-04-30 18:48 UTC, dansible commented on stable/grafana/templates/tests/test-role.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
updated 👍

2019-04-30 18:48 UTC, dansible commented on stable/grafana/templates/tests/test-rolebinding.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
updated 👍

2019-04-30 18:51 UTC, dansible commented
@davidkarlsen thank you for the feedback - i've updated the versions on the Role and Rolebinding objects as requested. I wanted to flag that the main Role/RB resources are still using the v1beta1 version:
https://github.com/helm/charts/blob/master/stable/grafana/templates/role.yaml
https://github.com/helm/charts/blob/master/stable/grafana/templates/rolebinding.yaml

It's outside of the scope of this PR but should I update those as well?

2019-04-30 19:00 UTC, dansible commented
/test pull-charts-e2e

2019-05-02 12:36 UTC, dansible commented
@maorfr @zanhsieh is there anything I can do to move this PR along?

2019-05-02 13:11 UTC, maorfr commented
/lgtm

thanks for contributing and congrats on your first contribution!

2019-05-02 13:18 UTC, merged