Add cloudflare-datadog chart
helm/charts pull request #1324
Opened 2017-06-20 14:10 UTC by metadave

see also: https://github.com/kubernetes/charts/pull/780

@so0k since you did most of the work on this, do you want me to add your name and email to the maintainers?

cc @jgmize @glogiotatidis

2017-06-21 15:27 UTC, so0k commented
@metadave - it's fine, sorry I didn't have time to work on my previous PR - Thanks for taking this over

2017-06-21 15:57 UTC, metadave commented
@so0k excellent, added!

2017-07-05 22:44 UTC, viglesiasce commented
@k8s-bot ok to test

2017-07-20 19:47 UTC, unguiculus requested changes

2017-07-20 19:47 UTC, unguiculus commented on incubator/cloudflare-datadog/values.yaml
> +  tag: latest
How about not using `latest` and using `IfNotPresent`?

2017-07-20 19:47 UTC, unguiculus commented on incubator/cloudflare-datadog/Chart.yaml
> +apiVersion: v1
Can you add an `icon` and `appVersion`?

Also, please use Github usernames instead of real names.

2017-07-20 19:47 UTC, unguiculus commented on incubator/cloudflare-datadog/templates/deployment.yaml
> +    app: {{ template "fullname" . }}
Please apply best practices for lablels.
https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices
The `app` label should be `{{ template "name" . }}`.

2017-07-20 19:47 UTC, unguiculus commented on incubator/cloudflare-datadog/templates/deployment.yaml
> +        heritage: {{ .Release.Service | quote }}
The `heritage` label can be removed here.

2017-07-20 19:47 UTC, unguiculus commented on incubator/cloudflare-datadog/templates/deployment.yaml
> +  replicas: {{default 1 .Values.replicaCount}}
It's better to add defaults to `values.yaml` only. Don't specify them here if not necessary.

Use consistent formatting: Space after `{{` and before `}}`.

2017-07-20 19:47 UTC, unguiculus commented on incubator/cloudflare-datadog/values.yaml
> +resources:
We started recommending not to specify defaults for resources. This should be a conscious choice of the user.

2017-07-20 19:47 UTC, unguiculus commented on incubator/cloudflare-datadog/templates/_helpers.tpl
> +We truncate at 24 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
24 -> 63

2017-07-20 19:47 UTC, unguiculus commented on incubator/cloudflare-datadog/README.md
> +* Requires (and tested with) helm `v2.1.2` or above.
v2.1.2 is kind of dated.

2017-07-28 06:21 UTC, unguiculus commented
Marking this as stale. Please up date within the next week.

2017-07-28 13:44 UTC, closed without merging