[stable/sonatype-nexus] Add openshift routes
helm/charts pull request #13248
Opened 2019-04-24 13:15 UTC by hamza3202

**Problem:**
No resource to create openshift routes.

**Solution**
Add routes for both services.

**What this PR does?**
Adds new routes for both docker and nexus(proxy) service.

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-04-24 13:49 UTC, hamza3202 commented
/assign @rjkernick

2019-04-25 09:26 UTC, hamza3202 commented
@rjkernick any updates on this?

2019-04-25 12:37 UTC, rjkernick requested changes

2019-04-25 12:37 UTC, rjkernick commented on stable/sonatype-nexus/Chart.yaml
> +version: 1.17.1
Please bump the minor version as this add features

2019-04-25 12:37 UTC, rjkernick commented on stable/sonatype-nexus/README.md
Maybe add a section on what an example set of overrides for openshift look like.

2019-04-25 12:37 UTC, rjkernick commented
/ok-to-test

2019-04-29 14:03 UTC, hamza3202 commented
@rjkernick any updates on this?

2019-04-29 15:45 UTC, rjkernick commented
/lgtm

2019-04-29 15:56 UTC, merged