Add NetworkPolicy for Prometheus
helm/charts pull request #1327
Opened 2017-06-20 17:28 UTC by ozdanborne

2017-07-15 17:18 UTC, mgoodness requested changes
Looks pretty good, but I think we can eliminate the need to specify `apiVersion`. Don't forget to rebase!

2017-07-15 17:18 UTC, mgoodness commented on stable/prometheus/templates/alertmanager-networkpolicy.yaml
> +apiVersion: {{ .Values.networkPolicy.apiVersion }}
Let's take this off users' shoulders and use Helm's `.Capabilities` object to set the API version accordingly.

2017-07-15 17:18 UTC, mgoodness commented on stable/prometheus/templates/alertmanager-networkpolicy.yaml
> +  name: {{ template "prometheus.alertmanager.fullname" . }}
Add standard labels (`app`, `component`, `chart`, `release`, `heritage`).

2017-07-15 17:18 UTC, mgoodness commented on stable/prometheus/templates/alertmanager-networkpolicy.yaml
> +            component: {{ .Values.server.name }}
Needs quotes around the value.

2017-07-15 17:18 UTC, mgoodness commented on stable/prometheus/Chart.yaml
> +version: 3.0.3
We're adding functionality, so let's make this a minor (not patch) version bump.

2017-07-15 17:18 UTC, mgoodness commented on stable/prometheus/templates/kube-state-metrics-networkpolicy.yaml
> +{{- end }}
Comments from `alertmanager-networkpolicy.yaml` apply here.

2017-07-15 17:18 UTC, mgoodness commented on stable/prometheus/templates/server-networkpolicy.yaml
> +{{- end }}
Comments from `alertmanager-networkpolicy.yaml` apply here as well.

2017-07-15 17:19 UTC, mgoodness commented
@k8s-bot ok to test

2017-07-28 21:02 UTC, ozdanborne commented
@mgoodness I've been trying to implement `.Capabilities` to automatically provide the correct networkPolicy apiVersion, but have been running into a lot of issues.

For starters, comparator functions (`ge`, `le`) do not accept strings. Only `int`. Which is quite confusing as [there's](https://github.com/kubernetes/charts/blob/3e43eb735c2da44565aea81bd65bb155fbaa2272/stable/traefik/templates/deployment.yaml#L17) [a](https://github.com/kubernetes/charts/blob/74dda6cdc563d27935daccb2d97336bc5625ae66/stable/kube2iam/templates/daemonset.yaml#L56) [few](https://github.com/kubernetes/charts/blob/f2e6b169cbfb1c5f131042f14fec9f0f8794bb8e/stable/spotify-docker-gc/templates/daemonset.yaml#L6) places where charts are comparing strings.

I can get past that syntax error by casting them to integers. But then when I try to deploy my chart, `.Capabilities.KubeVersion.Minor` is always nil. 

Any pointers on what's going on? I've tried using helm v2.4.2 and v2.5.1

2017-08-01 20:33 UTC, ozdanborne commented
/retest

2017-08-01 20:38 UTC, ozdanborne commented
Thanks for helping me to realize I wasn't passing the current context to my template functions @mgoodness .

I think I've addressed all feedback at this point. Look good? feedback is in 2nd commit. I can squash when ready to merge

2017-08-01 22:47 UTC, mgoodness approved these changes

2017-08-01 22:47 UTC, mgoodness commented
/lgtm

2017-08-01 22:48 UTC, merged