[stable/docker-registry] Add affinity for pod assignment
helm/charts pull request #13324
Opened 2019-04-26 23:57 UTC by mouradmourafiq

#### What this PR does / why we need it:

This PR adds affinity for for pod assignment for [stable/docker-registry]

#### Special notes for your reviewer:

No breaking changes, this is PR just exposes std kubernetes pod/node scheduling mechanism. The chart already has toleration and node selectors, and this PR extends the pod assignment with affinity.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2019-04-27 00:00 UTC, mouradmourafiq commented
/assign @jpds

2019-04-27 16:10 UTC, davidkarlsen requested changes

2019-04-27 16:10 UTC, davidkarlsen commented on stable/docker-registry/Chart.yaml
> +version: 1.7.2
```suggestion
version: 1.8.0
```

2019-04-27 16:17 UTC, davidkarlsen commented
/ok-to-test

2019-04-29 10:06 UTC, mouradmourafiq commented
/assign @rendhalver

2019-05-09 22:17 UTC, mouradmourafiq commented
@redbaron  @jpds any comments on this?

2019-06-22 23:36 UTC, closed without merging