[stable/helm-exporter] toggle honorLabels in servicemonitor
helm/charts pull request #13526
Opened 2019-05-05 07:30 UTC by alexsn

prometheus-operator renames 'namespace' label to 'exported-namespace'
which breaks https://grafana.com/dashboards/9367

Signed-off-by: Alex Snast <alexsn@fb.com>

#### Which issue this PR fixes
Default label renaming which prometheus-operator preforms breaks https://grafana.com/dashboards/9367

Checklist
[x ] DCO signed
[x ] Chart Version bumped
[ x] title of the PR contains starts with chart name e.g. [stable/chart]

2019-05-05 07:31 UTC, alexsn commented
/assign @sstarcher

2019-05-05 18:28 UTC, sstarcher commented
/ok-to-test

2019-05-05 18:29 UTC, sstarcher commented
/lgtm

2019-05-05 18:29 UTC, sstarcher requested changes

2019-05-05 18:29 UTC, sstarcher commented on stable/helm-exporter/Chart.yaml
> +version: 0.3.1
change it to 0.2.2 as this  is a bug fix.

2019-05-05 18:30 UTC, sstarcher commented
/lgtm cancel

2019-05-06 03:14 UTC, alexsn commented
done

2019-05-06 14:54 UTC, sstarcher commented
/lgtm

2019-05-06 15:01 UTC, merged