[stable/signalfx-agent] Adding deprication notice
helm/charts pull request #13586
Opened 2019-05-07 21:11 UTC by EricLemieux

Adding depreciation notice to the signalfx-agent readme

Signed-off-by: Eric Lemieux <eric@lemieuxdev.com>

#### What this PR does / why we need it:
This copy of the chart is out of date, and closed prs reference it as being deprecated.
This change just makes it clearer to new users where they can find the more up to date version.
I used the Istio deprecation notice, in the incubator/istio readme, as a model.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] title of the PR contains starts with chart name e.g. `[stable/chart]`

2019-05-08 15:03 UTC, EricLemieux commented
/assign @lachie83

2019-05-08 22:05 UTC, davidkarlsen requested changes

2019-05-08 22:05 UTC, davidkarlsen commented on stable/signalfx-agent/Chart.yaml
> +version: 0.3.1
please add `deprecated: true` as well

2019-05-08 22:06 UTC, davidkarlsen commented
/assign

2019-05-08 23:52 UTC, EricLemieux commented on stable/signalfx-agent/Chart.yaml
> +version: 0.3.1
Added `deprecated: true`.

2019-05-09 09:43 UTC, cpanato requested changes
please remove the maintainers
`Deprecated chart must not have maintainers`

2019-05-09 12:39 UTC, EricLemieux commented
@cpanato I have removed the maintainer section, I didn't see that it needed to be removed in the docs.

2019-05-09 12:47 UTC, cpanato commented
/ok-to-test

2019-05-09 12:47 UTC, cpanato commented
@EricLemieux i wil update the docs thanks for the catch

2019-05-09 12:57 UTC, cpanato commented
@EricLemieux actually the item to remove the maintainers are describe here: https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart
item 4

2019-05-09 12:58 UTC, cpanato commented on stable/signalfx-agent/Chart.yaml
>  description: The SignalFx Kubernetes agent
also need to add: DEPRECATED in the beginning
```suggestion
description: DEPRECATED The SignalFx Kubernetes agent
```

2019-05-09 13:42 UTC, EricLemieux commented
@cparedes Apologies, I was following this doc https://github.com/helm/helm/blob/master/docs/charts.md#deprecating-charts

I have made the changes required in the doc you linked.

2019-05-09 20:29 UTC, davidkarlsen approved these changes

2019-05-09 20:30 UTC, davidkarlsen commented
/lgtm

2019-05-09 20:44 UTC, merged