Allow static IP address
helm/charts pull request #1361
Opened 2017-06-22 23:50 UTC by dhcdata

If cloud provider supports, will assign the static IP address to the raefik service https://kubernetes.io/docs/api-reference/v1.6/#servicespec-v1-core

Confirmed on GCP.

2017-06-22 23:59 UTC, dhcdata commented
CLA sent

2017-06-23 00:02 UTC, dhcdata commented
CLA sent

2017-06-23 00:04 UTC, dhcdata commented
New Comment

2017-06-23 09:28 UTC, unguiculus requested changes
One small thing. Otherwise LGTM.

2017-06-23 09:28 UTC, unguiculus commented on stable/traefik/templates/service.yaml
> +  {{- if .Values.loadBalancerIP}}
Nit: Add space before `}}`.

2017-06-23 09:29 UTC, unguiculus commented
Check you CLA again. Did you commit with the correct e-mail?

2017-06-23 15:59 UTC, dhcdata commented
Done

2017-06-24 09:00 UTC, unguiculus requested changes

2017-06-24 09:00 UTC, unguiculus commented on stable/traefik/values.yaml
> +# Static IP Address pass --set loadBalancerIP=false from command line if running mulitiple
`loadBalancerIP=false` doesn't seem to make sense. Either set it or leave it empty. Also, there's a typo in `mulitiple`. I'd just remove the comment.

2017-06-24 10:05 UTC, dhcdata commented
Because helm supports multiple release objects, if you set `loadBalancerIP` in the ``values.yaml` file and run `helm install .` followed by `helm install --name my-project`, the second release object will never obtain an external IP address.  If it is set to false, it will obtain a dynamic IP address.

Perhaps the better approach is to:
1) remove the comment from `values.yaml`
2) add documentation to README.md
3) uncomment `loadBalancerIP` and set the default value to false

@unguiculus thoughts?

2017-06-24 15:35 UTC, unguiculus commented
A value of `false` doesn't make sense. Just set the default value to empty in `values.yaml`. If you install the chart twice, it is, of course, your responsibility to configure each installation properly.

2017-06-24 21:32 UTC, dhcdata commented
The problem is that the vast majority that would utilize the `loadBalancerIP`  would set their static IP address in `values.yaml`. The command line flag `--set` doesn't allow `empty` to override `values.yaml`.  

I've updated to have the default be `loadBalacerIP: dynamic`.  The template will now check that the values do not equal `nil` or `dynamic` before attempting the static IP.

2017-06-25 11:04 UTC, unguiculus commented
The problem you are making up just does not exist. Please set the default to empty in `values.yaml`. If someone installs the chart multiple times, they will have to provide different values for each installation, either using `--set` or different `values.yaml` files. Look e. g. at this example to see how it should be done:

https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/templates/controller-service.yaml#L21-L23
https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/values.yaml#L101

Example for installing the chart twice with different IPs:
```
helm install stable/traefik --name rel1 --set loadBalancerIP=10.20.30.40
helm install stable/traefik --name rel2 --set loadBalancerIP=10.20.30.41
```

2017-06-25 20:59 UTC, dhcdata commented
done

2017-06-26 06:45 UTC, unguiculus commented
Please update the service as well.

2017-06-26 14:59 UTC, closed without merging