stable/nginx-ingress Set hostPort on TCP and UDP listeners
helm/charts pull request #13627
Opened 2019-05-08 23:46 UTC by steakfest

When .Values.controller.daemonset.useHostPort is true, we should set the hostPort on those tcp and udp listeners as well.

Signed-off-by: John McGowan <john@steakfest.com>

#### What this PR does / why we need it:

@jackzampolin @mgoodness

When .Values.controller.daemonset.useHostPort is true, we should set the hostPort on those tcp and udp listeners as well.  I ran into this issue when exposing new TCP ports in an environment where I was expecting all Ingress to be exposed via hostPort

#### Which issue this PR fixes

I am not aware of a documented issue for this.

#### Special notes for your reviewer:

Looking at the history there seems to be precedent for adding this without total backwards compatibility in mind.  (See previous commit where it was added for the stats endpoint)

That being said, there could be a slightly different way of doing this that would allow existing TCP and UDP listerners to not use hostPorts if that value is set to true.  Instead we could either.  have the user set a different boolean that turns on hostPort for all TCP or UDP listeners, OR we could make it something that we set on a port by port basis.  (that seems like it might be overkill)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] title of the PR contains starts with chart name e.g. `[stable/chart]`

2019-05-08 23:49 UTC, steakfest commented
My fist time contributing to this repo.... I thought I read everything and added sign offs to my commits, but I must have screwed something up?

2019-05-16 21:59 UTC, ChiefAlexander requested changes
Awesome thanks for the PR. Just one change and also bump the version of the chart to whichever bugfix version is next.

2019-05-16 21:59 UTC, ChiefAlexander commented on stable/nginx-ingress/templates/controller-daemonset.yaml
> +              {{- if $useHostPort }}
Lets match the if statements above instead of putting the value into a temporary var.
```
{{- if .Values.controller.daemonset.useHostPort }}
```

2019-05-16 21:59 UTC, ChiefAlexander commented
/assign

2019-05-28 20:01 UTC, ChiefAlexander commented
/close
This is a dup of https://github.com/helm/charts/pull/14171 which has been merged

2019-05-28 20:29 UTC, steakfest commented
@ChiefAlexander I looked at the other PR.  For my own education, was this one not accepted, because I didn't respond soon enough?  (Sorry I missed the email from github, ended up in the wrong filtered folder)

2019-05-28 20:37 UTC, ChiefAlexander commented
Correct, that and the tests where failing at this point since the versions needed to be bumped.

2019-07-11 21:42 UTC, closed without merging