add option to include tolerations to daemonset
helm/charts pull request #1364
Opened 2017-06-23 15:36 UTC by ag237

Occasionally pods need to run on the master nodes, and with Kubernetes 1.6.x there are taints on these nodes that prevent sumokube from running there and grabbing logs. This adds the option to add those tolerations to the daemonset.

I'm not sure on protocol for updating version number, so I left it alone.

2017-06-23 20:54 UTC, vreon commented on stable/sumokube/README.md
> +| `daemonsets.tolerations     | List of node taints to tolerate (requires Kubernetes >= 1.6)            | `Nil` You must provide your own tolerations        |
Looks like this should be `daemonset` rather than `daemonsets`

2017-06-24 16:00 UTC, unguiculus requested changes
Thanks. Just a small correction.

2017-06-24 16:00 UTC, unguiculus commented on stable/sumokube/templates/daemonset.yaml
> +      {{- if .Values.daemonset.tolerations }}
Remove `if` statement.

2017-06-24 16:00 UTC, unguiculus commented on stable/sumokube/values.yaml
> +
Comment these lines in after removing the `if`statement.

```yaml
daemonset:
  tolerations: []
```

2017-06-24 16:01 UTC, unguiculus commented on stable/sumokube/README.md
> +| `daemonsets.tolerations     | List of node taints to tolerate (requires Kubernetes >= 1.6)            | `Nil` You must provide your own tolerations        |
`[]` instead of '`Nil` You must provide your own tolerations'

2017-06-24 16:02 UTC, unguiculus commented
/ok-to-test

2017-06-26 13:40 UTC, ag237 commented
Made requested changes.

2017-06-28 10:16 UTC, unguiculus commented
/cc @seanknox @jdumars

2017-06-28 10:16 UTC, unguiculus approved these changes

2017-06-29 23:37 UTC, DStorck commented on stable/sumokube/README.md
> +| `daemonset.tolerations      | List of node taints to tolerate (requires Kubernetes >= 1.6)            | []    |
missing the closing `

2017-07-06 12:47 UTC, ag237 commented on stable/sumokube/README.md
> +| `daemonset.tolerations      | List of node taints to tolerate (requires Kubernetes >= 1.6)            | []    |
Thanks, fixed.

2017-07-06 15:12 UTC, merged