Bump memcached version, add Kubernetes Service type configuration.
helm/charts pull request #13668
Opened 2019-05-10 00:11 UTC by janghwan

Added Kubernetes Service type configuration for the memcached chart.
Signed-off-by: Janghwan <cheesespy@gmail.com>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] title of the PR contains starts with chart name e.g. `[stable/chart]`

2019-05-11 13:24 UTC, olemarkus commented
/assign

Why would you want to change the service type? If you put multiple memcached behind a load balancer, you'll get inconsistent hit/miss/cache updates depending on what server you hit.

2019-05-19 02:06 UTC, janghwan commented
> /assign
> 
> Why would you want to change the service type? If you put multiple memcached behind a load balancer, you'll get inconsistent hit/miss/cache updates depending on what server you hit.

I need to access Memcached from outside of the kubernetes cluster. I had to set up only one replica due to the issue you mentioned.
The idea of exposing service with the service type is from the bitnami helm chart.

2019-05-27 13:50 UTC, olemarkus requested changes

2019-05-27 13:50 UTC, olemarkus commented on stable/memcached/templates/svc.yaml
> +  type: {{ .Values.serviceType }}
You cannot remove this line. That would make the service non-headless.

2019-05-27 13:50 UTC, olemarkus commented on stable/memcached/Chart.yaml
> +version: 2.8.3
You need to bump the minor version here, as a new feature is being added.

2019-07-03 03:20 UTC, closed without merging