Initial commit of Mattermost chart.
helm/charts pull request #1373
Opened 2017-06-25 12:25 UTC by jpds

2017-06-26 13:36 UTC, unguiculus requested changes
Thanks for the PR. Looks pretty good.

2017-06-26 13:36 UTC, unguiculus commented on incubator/mattermost/templates/pvc.yaml
> +    app: {{ template "fullname" . }}
`app` label should be  `{{ template "name" . }}`.

2017-06-26 13:36 UTC, unguiculus commented on incubator/mattermost/templates/secrets.yaml
> +    app: {{ template "fullname" . }}
`app` label should be  `{{ template "name" . }}`.

2017-06-26 13:36 UTC, unguiculus commented on incubator/mattermost/Chart.yaml
> +version: 0.1.0
`Chart.yaml` incomplete. Please add `appVersion`, `icon`, `home`, `sources`, `maintainers`, etc.

2017-06-28 23:15 UTC, jpds commented
Fixes pushed, thanks.

2017-07-01 11:52 UTC, unguiculus requested changes

2017-07-01 11:52 UTC, unguiculus commented on incubator/mattermost/Chart.yaml
> +  - name: Jonathan Davies
Please use your Github handle as name.

2017-07-04 19:09 UTC, unguiculus requested changes
A few more things I noticed.

2017-07-04 19:09 UTC, unguiculus commented on incubator/mattermost/README.md
> +| `resources.limits.cpu`  | Container requested CPU             | `nil`                                               |
You should just specify `resources` with default `{}`.

2017-07-04 19:09 UTC, unguiculus commented on incubator/mattermost/values.yaml
> +mattermost:
Why is just the DB under `mattermost`? You could probably put everything under that so I'd just remove it.

2017-07-20 17:55 UTC, unguiculus commented
Marking as stale. Please update within the next week.

2017-07-26 22:36 UTC, mccricardo commented
Any progress on this?

2017-07-28 05:25 UTC, unguiculus commented
Closing as stale. Feel free to reopen if/when you can work on this again.

2017-07-28 05:25 UTC, closed without merging