[stable/prometheus] Add extraHostPathMounts config to alert manager
helm/charts pull request #1377
Opened 2017-06-26 13:52 UTC by nlamirault

Like this PR #862

Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

2017-07-15 17:00 UTC, mgoodness requested changes
Just a couple nits. Also needs a rebase & minor version bump for adding functionality.

Kudos for using existing patterns!

2017-07-15 17:00 UTC, mgoodness commented on stable/prometheus/templates/alertmanager-deployment.yaml
> +            {{-end}}
Nit: let's move the conditionals in one level (that is, one less indent)

2017-07-15 17:00 UTC, mgoodness commented on stable/prometheus/templates/alertmanager-deployment.yaml
> +        {{-end}}
Nit: let's move the conditionals in one level (that is, one less indent)

2017-07-15 17:01 UTC, mgoodness commented
@k8s-bot ok to test

2017-08-02 01:55 UTC, mgoodness commented
/retest

2017-08-02 01:59 UTC, mgoodness commented
@nlamirault looks like you committed a new `stable/snmp-exporter` chart. Pull that out into its own PR, then we can get this one merged.

2017-08-13 18:30 UTC, unguiculus commented
Marking this as stale. Please update within one week.

2017-08-23 14:52 UTC, mgoodness commented
Closing as stale. Feel free to re-open if/when you have the opportunity.

2017-08-23 14:52 UTC, closed without merging