Add kubernetes-vault chart
helm/charts pull request #1396
Opened 2017-06-28 22:19 UTC by bbriggs

This packages the deployment found in [boostport/kubernetes-vault](https://github.com/Boostport/kubernetes-vault) into a helm chart.

Also, this is my first attempt at submitting any charts or changes here (or in the Kubernetes community at large), so any feedback, help, or advice is greatly appreciated.

I did my best to follow the requirements laid out in the style guides and used the Consul chart as a model for most of this. One thing I was unable to do or figure out the best approach for was with requiring users to supply the Vault URL and AppRole token, breaking the simple "this runs with defaults" guideline. I'd particularly welcome any guidance there.

2017-06-28 22:20 UTC, bbriggs commented
Also, I submitted my CLA a couple of hours ago. Hopefully it went through (or will go through).

2017-06-28 22:49 UTC, jpds commented
[Interestingly, I've just pushed a vault to https://github.com/kubernetes/charts/pull/1397 ]

2017-06-28 23:40 UTC, bbriggs commented
Synergy!
![synergy](https://user-images.githubusercontent.com/2350379/27665132-6dfffef6-5c39-11e7-88a4-e44551763469.gif)

Kubernetes-vault was the missing piece for us to programmatically issue Vault tokens to our applications in k8s pods. Boostport also had a Vault deployment that you might find as a useful reference for your Vault chart.

2017-07-05 14:14 UTC, bbriggs commented
Bumping for visibility

2017-07-06 16:47 UTC, lachie83 commented
I'll take a look at this!

2017-07-12 15:36 UTC, bbriggs commented
Any progress on this @lachie83?

2017-07-12 16:01 UTC, lachie83 commented
@bbriggs None as of yet because I'm trying to review the whole stack.... consul, vault, kubernetes-vault

2017-07-12 18:35 UTC, bbriggs commented
No worries, thanks for taking a look. Ready to make adjustments whenever you get the review going.

2017-07-13 14:24 UTC, dmccaffery commented
I would love to see this... make all of my dreams come true :) Thanks @bbriggs for doing this!

2017-07-13 14:44 UTC, bbriggs commented
@dmccaffery We're currently running this chart in prod. If you'd like to try it out and provide any feedback, use my branch and deploy this from your local Helm. So far it's working great for us.

2017-07-31 22:54 UTC, F21 commented
@bbriggs Thank you so much for this chart! 😄 

A small nit, could you update the default image version to `0.4.8`? There was some internal refactoring, but the external API is still the same.

Also, I think the default `imageTag` here https://github.com/kubernetes/charts/pull/1396/files#diff-7748195ee40bbae462cac7b2e9fdc7cdR29 should be `0.4.8` as there is no `0.7.5` yet.

Other than that, I think this looks really great!

2017-08-02 14:18 UTC, bbriggs commented
I can do that, thanks!

2017-08-03 20:20 UTC, bbriggs commented
Fixed. Bumping for review.

2017-08-04 03:04 UTC, F21 commented
Friendly ping @lachie83

2017-08-04 05:55 UTC, unguiculus requested changes
I'm jumping in for a review. Let's try and get this through. Please have a look at our best practices.  Especially, I'd like you to add standard labels everywhere.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md

You may also look at the chart examples for reference:

https://github.com/kubernetes/helm/tree/master/docs/examples/nginx

BTW, if you create a new chart with `helm create` and Helm 2.5+ you'll get an initial experience with correct labels.

2017-08-04 12:46 UTC, bbriggs commented
Thanks, I'll get to work on this today!

2017-08-08 20:12 UTC, unguiculus requested changes

2017-08-08 20:12 UTC, unguiculus commented on incubator/kubernetes-vault/templates/configMap.yaml
> +  name: {{ template "name" . }}
`{{ template "name" . }}` -> `{{ template "fullname" . }}`

2017-08-08 20:12 UTC, unguiculus commented on incubator/kubernetes-vault/templates/configMap.yaml
> +metadata:
Add standard labels.

2017-08-08 20:12 UTC, unguiculus commented on incubator/kubernetes-vault/templates/deployment.yaml
> +  name: kubernetes-vault
`{{ template "fullname" . }}`

2017-08-08 20:12 UTC, unguiculus commented on incubator/kubernetes-vault/templates/deployment.yaml
> +metadata:
Add standard labels.

2017-08-08 20:12 UTC, unguiculus commented on incubator/kubernetes-vault/templates/deployment.yaml
> +      labels:
Only `app` and `release` labels should go here.

2017-08-08 20:12 UTC, unguiculus commented on incubator/kubernetes-vault/templates/service.yaml
> +    component: "{{ template "fullname" . }}"
Remove `component` label. Add `app`, `heritage`, and `release` labels.

2017-08-08 20:12 UTC, unguiculus commented on incubator/kubernetes-vault/templates/service.yaml
> +  selector:
Selector should contain `app` and `release` label.

2017-08-15 23:45 UTC, bbriggs commented
I'm trying to figure out here what constitutes "standard" labels. I used the links you gave me as a guide initially, and then you requested changes from that. When I looked in stable, few (if any) of the charts had labeling that matched what you requested.

Is there a gold standard somewhere I can reference for what constitutes what labels go where?

2017-08-16 05:58 UTC, unguiculus commented
Best practices evolve over time. The links I posted reflect our current best practices. Of course, there are older charts that e. g. have different labels. Don't take those as reference.

2017-08-31 17:31 UTC, alejandroEsc commented
any progress here?

2017-08-31 18:41 UTC, bbriggs commented
Hey, I got pulled away the last two weeks but I'll have the updated labels in within the next few hours. New helm installed, I'll regenerate the skeleton and transfer everything over.

2017-09-09 21:07 UTC, unguiculus commented
Looks good except for the `Chart.yaml`. Please add back all the information that got lost.

2017-09-09 21:07 UTC, unguiculus commented
/ok-to-test

2017-09-09 21:14 UTC, unguiculus commented
OK, you need to fix the `values.yaml` and the config table in the readme.

2017-09-09 22:55 UTC, bbriggs commented
Not sure what to do with this one: `W0909 22:40:34.774] E0909 22:40:34.773861     105 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:42661: bind: cannot assign requested address`

2017-09-10 19:37 UTC, unguiculus commented on incubator/kubernetes-vault/Chart.yaml
> +appVersion: 0.4.7
0.4.8

2017-09-10 19:37 UTC, unguiculus commented on incubator/kubernetes-vault/values.yaml
> +  tag: 0.4.8
v0.4.8

2017-09-10 19:38 UTC, unguiculus commented
Don't worry about this message. It's normal. The problem is that the image could not be pulled due to an incorrect tag.

2017-09-11 15:17 UTC, unguiculus commented
/retest

2017-09-11 19:51 UTC, unguiculus approved these changes

2017-09-11 19:53 UTC, merged

2017-09-11 21:46 UTC, F21 commented
Thanks for getting this one through @bbriggs and @unguiculus !

2017-09-13 13:38 UTC, bbriggs commented
Phew! We made it!