Fix multiple TCP NotePort support
helm/charts pull request #14008
Opened 2019-05-20 23:00 UTC by gschanuel

- fixes #14007
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-05-21 04:07 UTC, KongZ commented
@gschanuel please sign-off your commit

2019-05-24 16:57 UTC, gschanuel commented
Hi.. i'm really new to PRs, what should I do now?

2019-05-27 03:50 UTC, KongZ requested changes

2019-05-27 03:50 UTC, KongZ commented on stable/graylog/templates/tcp-service.yaml
> +    {{- if .nodePort }}
The `service.type` for `NodePort` is still need to check. You can add nodeport to other service type.

For signing off
https://github.com/helm/charts/pull/14008/checks?check_run_id=134192087

2019-07-10 04:55 UTC, closed without merging