[incubator/vault-ui] Initial chart
helm/charts pull request #1406
Opened 2017-06-29 15:37 UTC by jpds

2017-06-29 16:41 UTC, kachkaev commented
Great to see this, thanks for crafting this chart! Just wondering if it's reasonable to mention `ingress` stuff in `README.md` so that it was clear that it's implemented.

I also suspect that mentioning k8s 1.5 only may make someone think that the chart is not compatible with k8s 1.6 and up. Maybe worth adding `+` or some other note here and in https://github.com/kubernetes/charts/pull/1397?

2017-06-30 06:23 UTC, unguiculus commented
/ok-to-test

2017-07-31 10:53 UTC, andrewhowdencom commented
Yo @jpds is this good to review or?

2017-09-15 12:41 UTC, unguiculus requested changes

2017-09-15 12:41 UTC, unguiculus commented on incubator/vault-ui/README.md
> +* Kubernetes 1.5
We support the current and the previous version, thus: 1.6+

2017-09-15 12:41 UTC, unguiculus commented on incubator/vault-ui/README.md
> +
Align table properly.

2017-09-15 12:41 UTC, unguiculus commented on incubator/vault-ui/templates/_helpers.tpl
> +{{- define "name" -}}
We've started namespacing templates. See this issue and apply the same to your PR: #1785
Eventually, Helm create will do this for you in a future release. See kubernetes/helm#2845

`vault-ui.name`, `vault-ui.fullname`

2017-09-18 12:27 UTC, andrewhowdencom commented
@jpds  I can carry this for you if you like? I'll set a reminder to follow this up in a couple days.

2017-09-28 17:17 UTC, unguiculus commented
Marking this as stale. Please update PR within one week.

2017-10-09 19:32 UTC, unguiculus commented
Closing this as stale. Feel free to reopen if/when you decide to work on it again.

2017-10-09 19:32 UTC, closed without merging