Prometheus: add ingress paths value
helm/charts pull request #1407
Opened 2017-06-29 15:45 UTC by markvdw4

To enable prometheus federation the 'federate' endpoint needs to be reachable on port 9090, to do this you need to add a new path to the server ingress template. In this PR I add a new value for server ingress paths and if it is set then we inject the desired paths into the server ingress template.

In order to parse properly paths must be defined in JSON:

```
server:
  ingress:
    paths: [{"backend": {"serviceName": "promfed","servicePort": 9090},"path": '/federate'}]
```

2017-06-29 15:47 UTC, markvdw4 commented
my github should be properly linked to my linuxfoundation/cncf account where I signed the CLA

2017-08-13 18:27 UTC, unguiculus requested changes

2017-08-13 18:27 UTC, unguiculus commented on stable/prometheus/README.md
> +```
I'd prefer this style:

```yaml
server:
  ingress:
    ## Prometheus server Ingress paths
    ## Must be used for Prometheus federation
    ##
    paths: 
      - path: /federate
        backend: 
          serviceName: prometheusfederation
          servicePort: 9090  
```

2017-08-13 18:27 UTC, unguiculus commented on stable/prometheus/values.yaml
> +    paths: []
I don't like the name. It is really something like `additionalPaths`.

2017-08-14 22:41 UTC, mgoodness commented
The `/federate` endpoint is already exposed by the server Ingress. By default it's exposed on port 80, but that can be changed by setting `server.service.servicePort=9090`. Unless you absolutely *must* have different endpoints exposed on different ports, I think we should avoid the extra complexity this introduces.

2017-08-14 22:41 UTC, mgoodness requested changes
The /federate endpoint is already exposed by the server Ingress. By default it's exposed on port 80, but that can be changed by setting `server.service.servicePort=9090` (for example). Unless you absolutely *must* have different endpoints exposed on different ports, I think we should avoid the extra complexity this introduces.

2017-08-17 14:26 UTC, mgoodness commented
Closing this. Feel free to re-open if you really do need separate endpoints/ports.

2017-08-17 14:26 UTC, closed without merging