[stable/kubernetes-dashboard] Add RBAC support
helm/charts pull request #1415
Opened 2017-07-03 07:23 UTC by yuanying

Adds support in kubernetes-dashboard for RBAC.
Permissions sourced from https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml and adjusted slightly.

setting rbac.enabled to true will create a rolebinding and service account.

2017-07-20 19:33 UTC, unguiculus commented
/cc @mgoodness re. RBAC

2017-07-20 19:34 UTC, unguiculus commented
/cc @kfox1111

2017-07-23 17:06 UTC, unguiculus submitted a review, later dismissed
Here's a good example for RBAC support. How about doing it the same way?
https://github.com/coreos/alb-ingress-controller/pull/146

2017-07-23 23:58 UTC, yuanying commented
@unguiculus Hi, thanks for your review!

One question, the parameter `rbac.serviceAccountName` seems very confusable, I expect this parameter will set serviceAccount name if `rbac==true`.
Is this standard way to configure rbac?

Thanks.

2017-08-13 14:02 UTC, unguiculus commented
You may not want to configure RBAC with the chart and only specify an existing `rbac.serviceAccountName`. You would then set `rbac.create=false`.

2017-08-14 16:55 UTC, kfox1111 commented
Yeah, you may want to specify service account name separately from creating so that you can use preexisting service accounts.

2017-08-14 21:49 UTC, yuanying commented
Ahh, I see!! This rbac.serviceAccountName setting is for user who want to configure rbac service account by himself. right?
I'll update this patch soon.

2017-08-14 22:00 UTC, mgoodness requested changes
Same changes @unguiculus requested, just made explicit.

2017-08-14 22:00 UTC, mgoodness commented on stable/kubernetes-dashboard/templates/deployment.yaml
> +      serviceAccountName: {{ template "fullname" . }}
As @unguiculus stated, use `serviceAccountName: {{ if .Values.rbac.create }}{{ template "fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}`

2017-08-14 22:00 UTC, mgoodness commented on stable/kubernetes-dashboard/templates/serviceaccount.yaml
> +---
Delete the YAML separator and wrap the entire manifest in a `{{- if .Values.rbac.create }}...{{- end }}`

2017-08-14 22:00 UTC, mgoodness commented on stable/kubernetes-dashboard/values.yaml
> +  enabled: false
Change `enabled` to `create` and add `serviceAccountName`

2017-08-14 22:00 UTC, mgoodness commented on stable/kubernetes-dashboard/templates/rolebinding.yaml
> +{{- if .Values.rbac.enabled -}}
Change `enabled` to `create`

2017-08-14 22:00 UTC, mgoodness commented on stable/kubernetes-dashboard/README.md
> +| `rbac.enabled`        | Enable rbac resource               | `false`                                                                  |
Change `enabled` to `create` and add `rbac.serviceAccountName`

2017-08-14 22:32 UTC, yuanying commented
@mgoodness Thanks! I think, all needed changes are fixed.

2017-08-14 22:59 UTC, mgoodness approved these changes

2017-08-14 22:59 UTC, mgoodness commented
/ok-to-test

2017-08-14 22:59 UTC, mgoodness commented
/lgtm

2017-08-14 23:08 UTC, merged