Version bump linkerd:1.1.0 and kubectl:v1.6.2
helm/charts pull request #1416
Opened 2017-07-03 14:33 UTC by VDuda

Bump versions to latest,
**linkerd**: 1.1.0
**kubectl**: v1.6.2

2017-07-05 22:50 UTC, viglesiasce requested changes
This change is causing linkerd to continually crash in my setup on v1.6.6 of k8s.

Also needs a version bump in the Chart.yaml to 0.3.0

2017-07-13 19:35 UTC, VDuda commented
I ran a test of each kubernetes environment offered on GKE and ran through the scenario of: helm package version 0.3.0 of the chart, helm install that package, verify pods are running, verify that I'm able to hit the admin page after port-forwarding the pod.

| Kubernetes Version | Linkerd Version | Works? |
|--------------------|-----------------|--------|
| 1.6.4              | 1.1.2           | 🆗  |
| 1.6.7              | 1.1.2           | 🆗 |
| 1.7                | 1.1.2           | 🆗 |

2017-08-10 04:51 UTC, viglesiasce commented
/ok-to-test

2017-08-10 04:54 UTC, viglesiasce approved these changes

2017-08-10 04:54 UTC, merged