Adding JFrog Artifactory
helm/charts pull request #142
Opened 2016-10-21 21:02 UTC by jainishshah17

2016-10-21 21:09 UTC, viglesiasce commented
Hey @jainishshah17!!

Thanks for the submission!

A few things to fix up:

1. The nginx chart was errantly checked in
2. You need to sign the Linux Foundation CLA as noted above
3. The .gitignore change has already been checked in
4. Use a ClusterIP service by default, we prefer not to optimize for Minikube
5. Does this chart work out of the box without having a pro license?
6. You have a note about volumes and config maps in the deployment but I dont see that configuration included.

2016-10-24 21:07 UTC, ultimateboy commented on incubator/artifactory/README.md
> +The following tables lists the configurable parameters of the elasticsearch chart and their default values.
s/elasticsearch/JFrog Artifactory

2016-10-24 23:48 UTC, jainishshah17 commented on incubator/artifactory/README.md
> +The following tables lists the configurable parameters of the elasticsearch chart and their default values.
Fixed

2016-10-26 02:09 UTC, chrislovecnm commented
Can u squash your commits amigo?

2016-10-26 02:12 UTC, chrislovecnm commented
@jainishshah17 your rebase is a tad wonky. Please remove the .ignore changes out of the commit ;)

2016-10-26 02:21 UTC, chrislovecnm requested changes
Thanks for the PR!! Have a couple tweaks

2016-10-26 02:21 UTC, chrislovecnm commented on incubator/artifactory/README.md
> +* Artifactory Pro trial license
@viglesiasce how are we handling paid for software? Do we need some notice in the README, hey you need to pay for this ;)

2016-10-26 02:21 UTC, chrislovecnm commented on incubator/artifactory/README.md
> +$ kubectl delete pvcs -l release=my-release,type=data
Can you include the timed wait that is in the PetSet docs?

2016-10-26 02:21 UTC, chrislovecnm commented on incubator/artifactory/templates/deployment.yaml
> +        # This (and the volumes section below) mount the config map as a volume.
Where is this at? We need resource limit and health probes as well please

2016-10-28 22:59 UTC, jainishshah17 commented on incubator/artifactory/README.md
> +$ kubectl delete pvcs -l release=my-release,type=data
@chrislovecnm  I have updated my chart

2016-11-04 18:39 UTC, prydonius commented
@jainishshah17 any luck on the Linux Foundation CLA?

2016-11-04 19:00 UTC, jainishshah17 commented
@prydonius Done signing it.

2016-11-04 20:21 UTC, prydonius commented
Can you rebase to fix the conflicts?

2016-11-05 05:39 UTC, gtaylor commented on incubator/artifactory/README.md
> +| `ImagePullPolicy`         | Container pull policy             | `Always`                                                 |
Sorry to come in late, but can this be left blank to fall through to the Kubernetes default of IfNotExists, like here? https://github.com/kubernetes/charts/blob/master/stable/redis/templates/deployment.yaml#L19

2016-11-06 00:19 UTC, chrislovecnm requested changes
Thanks for the chart.  Some more notes.

2016-11-06 00:19 UTC, chrislovecnm commented on .gitignore
> -# General files for the project
You need to remove this file from your commit.  You are removing it from the repo.  Add it back in your branch please.

2016-11-06 00:19 UTC, chrislovecnm commented on incubator/artifactory/README.md
> +$ kubectl delete pvcs -l release=my-release,type=data
No here is an example
```console
$ grace=$(kubectl get po web-0 --template '{{.spec.terminationGracePeriodSeconds}}')
$ kubectl delete petset,po -l app=nginx
$ sleep $grace
$ kubectl delete pvc -l app=nginx
```

2016-11-06 00:19 UTC, chrislovecnm commented on incubator/artifactory/templates/deployment.yaml
> +        image: "{{default "docker.bintray.io/jfrog/artifactory-pro" .Values.image}}:{{default "4.13.2" .Values.imageTag}}"
I would prefer to have these hard coded values in values.yaml.  @viglesiasce thoughts?

2016-11-06 00:19 UTC, chrislovecnm commented on incubator/artifactory/templates/deployment.yaml
> +        resources:
This is a much cleaner way to do the resources https://github.com/kubernetes/charts/blob/master/stable/mysql/templates/deployment.yaml#L34

You will need the https://github.com/kubernetes/charts/blob/master/stable/mysql/templates/_helpers.tpl file as well in your chart.

2016-11-06 00:19 UTC, chrislovecnm commented on incubator/artifactory/templates/deployment.yaml
> +          name: {{ template "fullname" . }}
You list PVC in your instructions, but you do not define any PVC components in your chat?

2016-11-10 07:32 UTC, alon-argus commented on incubator/artifactory/values.yaml
> +# Default values for etcd.
etcd?

2016-11-10 07:39 UTC, alon-argus commented on incubator/artifactory/templates/deployment.yaml
> +        image: "{{default "docker.bintray.io/jfrog/artifactory-pro" .Values.image}}:{{default "4.13.2" .Values.imageTag}}"
I agree. Also, fix to `.Values.Image` (capital i) and `.Values.ImageTag`, as in `values.yaml`.

2016-11-10 07:45 UTC, alon-argus commented on incubator/artifactory/templates/deployment.yaml
> +        imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
`.Values.pullPolicy` -> `.Values.ImagePullPolicy`

2016-11-10 07:49 UTC, alon-argus commented on incubator/artifactory/templates/svc.yaml
> +  - port: {{default 8081 .Values.httpPort}}
`.Values.httpPort` is not defined

2016-11-14 16:46 UTC, viglesiasce commented
Can you add a [NOTES.txt](https://github.com/kubernetes/helm/blob/master/docs/charts.md#chart-license-readme-and-notes) file that explains what users need to do in order to use the Chart?

2016-11-30 17:29 UTC, jainishshah17 commented
@prydonius I have updated my changes. Please check

2016-12-02 06:51 UTC, viglesiasce commented
@k8s-bot ok to test

2016-12-02 06:54 UTC, viglesiasce requested changes

2016-12-02 06:54 UTC, viglesiasce commented on stable/mysql/values.yaml
> +  accessMode: ReadWrite
This should not be changed in this PR.

2016-12-02 06:54 UTC, viglesiasce commented on incubator/artifactory/values.yaml
> +  accessMode: ReadWrite
Invalid access mode, see test results.

2016-12-02 06:54 UTC, viglesiasce commented on incubator/artifactory/values.yaml
> +image: "docker.bintray.io/jfrog/artifactory-pro"
can we default this to the oss image and have a note about how to switch it?

2016-12-04 07:45 UTC, jainishshah17 commented on stable/mysql/values.yaml
> +  accessMode: ReadWrite
Changed default image to Artifactory-oss

2016-12-04 13:23 UTC, jainishshah17 commented
@k8s-bot e2e test this

2016-12-05 18:33 UTC, viglesiasce commented
@k8s-bot ok to test

2016-12-05 18:39 UTC, viglesiasce requested changes

2016-12-05 18:39 UTC, viglesiasce commented on incubator/artifactory/templates/NOTES.txt
> +
Add examples of how to connect to this from outside the cluster. Check out the jenkins chart for an example of how to differentiate between the various service modes.

2016-12-05 18:39 UTC, viglesiasce commented on incubator/artifactory/values.yaml
> +ServiceType: LoadBalancer
Lets make this ClusterIP by default since the password isnt randomly generated by default.

2016-12-05 18:39 UTC, viglesiasce commented
Looking good @jainishshah17! Was able to install it this time around. 2 more things to fix:

1. Add NOTES about how to connect from outside the cluster
2. Make the service ClusterIP by default

2016-12-11 07:38 UTC, jainishshah17 commented
@viglesiasce Made changes please check

2016-12-19 23:18 UTC, viglesiasce approved these changes

2016-12-19 23:18 UTC, viglesiasce commented
This worked for me. Thanks @jainishshah17!

2016-12-19 23:31 UTC, merged