Add Stash chart
helm/charts pull request #1420
Opened 2017-07-04 00:16 UTC by tamalsaha

Stash is a Kubernetes operator for [restic](https://github.com/restic/restic). Using Stash, you can backup Kubernetes volumes mounted in following types of workloads:
- Deployment
- DaemonSet
- ReplicaSet
- ReplicationController
- StatefulSet

2017-07-04 19:29 UTC, unguiculus requested changes

2017-07-04 19:29 UTC, unguiculus commented on stable/stash/templates/deployment.yaml
> +      labels:
`chart` and `heritage` labels should be removed here.

2017-07-04 19:29 UTC, unguiculus commented on stable/stash/templates/rbac.yaml
> +---
Please create separate file.

2017-07-04 19:32 UTC, unguiculus commented on stable/stash/templates/deployment.yaml
> +  replicas: {{.Values.replicaCount}}
Add space after `{{` and before `}}` and make sure it's consistent throughout the chart.

2017-07-04 20:15 UTC, tamalsaha commented
I have addressed your comments.

2017-07-05 15:46 UTC, unguiculus commented
Actually, I wanted you to fix the whitespace issue around braces in all files. Sorry, if this was not clear.

2017-07-05 18:48 UTC, tamalsaha commented
Should be fixed now.  It seems that the vscode extensions linting doed not identify this issue. PTAL.

2017-07-06 15:01 UTC, unguiculus requested changes

2017-07-06 15:01 UTC, unguiculus commented on stable/stash/templates/_helpers.tpl
> +{{/* vim: set filetype=mustache: */}}
This is an outdated version of the file with wrong truncation. Update it from this example: https://github.com/kubernetes/helm/blob/master/docs/examples/nginx/templates/_helpers.tpl

2017-07-06 15:13 UTC, tamalsaha commented
Updated. PTAL.

2017-07-06 15:18 UTC, unguiculus commented
/ok-to-test

2017-07-06 15:19 UTC, unguiculus approved these changes

2017-07-06 15:20 UTC, merged