Add Gearman G2 chart
helm/charts pull request #1421
Opened 2017-07-04 00:29 UTC by tamalsaha

[G2](https://github.com/appscode/g2) is a modern implementation of Gearman server in GO.

2017-07-04 19:31 UTC, unguiculus requested changes

2017-07-04 19:31 UTC, unguiculus commented on stable/g2/templates/deployment.yaml
> +      labels:
`chart` and `heritage` labels should be removed here.

2017-07-04 19:31 UTC, unguiculus commented on stable/g2/templates/deployment.yaml
> +  replicas: {{.Values.replicaCount}}
Add space after `{{` and before `}}` and make sure it's consistent throughout the chart.

2017-07-04 19:31 UTC, unguiculus commented on stable/g2/templates/rbac.yaml
> +---
Please create separate file.

2017-07-04 20:25 UTC, tamalsaha commented
I have addressed your comments.

2017-07-05 15:46 UTC, unguiculus commented
Actually, I wanted you to fix the whitespace issue around braces in all files. Sorry, if this was not clear.

2017-07-05 18:48 UTC, tamalsaha commented
Should be fixed now.  It seems that the vscode extensions linting doed not identify this issue. PTAL.

2017-07-06 15:00 UTC, unguiculus requested changes

2017-07-06 15:00 UTC, unguiculus commented on stable/g2/README.md
> +If the output contains "beta" or both "alpha" and "beta" you can may install with enabling the creating of rbac resources (see below).
Incorrect grammar. Try to improve the wording.

2017-07-06 15:00 UTC, unguiculus commented on stable/g2/templates/_helpers.tpl
> +{{/* vim: set filetype=mustache: */}}
This is an outdated version of the file with wrong truncation. Update it from this example: https://github.com/kubernetes/helm/blob/master/docs/examples/nginx/templates/_helpers.tpl

2017-07-06 15:13 UTC, tamalsaha commented
Updated. PTAL.

2017-07-06 15:14 UTC, unguiculus commented
/ok-to-test

2017-07-06 15:19 UTC, unguiculus approved these changes

2017-07-06 15:19 UTC, merged