[stable/atlantis] Atlantis v0.8.0
helm/charts pull request #14242
Opened 2019-05-29 10:28 UTC by adharmawan

#### What this PR does / why we need it:

Allow to pass `--disable-apply-all` server flag via `ATLANTIS_DISABLE_APPLY_ALL` env var

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-06-16 09:46 UTC, adharmawan commented on stable/atlantis/Chart.yaml
> +version: 3.6.1
```suggestion
version: 3.6.0
```

2019-06-16 09:57 UTC, adharmawan commented
@anubhavmishra @callmeradical Please kindly review :)

2019-06-16 12:56 UTC, adharmawan commented
/assign @callmeradical

2019-06-24 03:34 UTC, adharmawan commented
Hello @callmeradical and @anubhavmishra, could you look at this PR? 😄

2019-06-24 20:40 UTC, anubhavmishra commented
@lkysow can you take a look at this?

2019-06-24 20:40 UTC, anubhavmishra commented
/assign @lkysow

2019-06-24 20:41 UTC, anubhavmishra commented
/unassign @lkysow

2019-06-24 20:42 UTC, anubhavmishra commented
/auto-cc @lkysow

2019-06-24 20:43 UTC, anubhavmishra commented
/cc @lkysow

2019-06-25 12:53 UTC, lkysow requested changes

2019-06-25 12:53 UTC, lkysow commented on stable/atlantis/README.md
> +| `disableApplyAll`                           | disables running `atlantis apply` without any flags
```suggestion
| `disableApplyAll`                           | Disables running `atlantis apply` without any flags                                                                                                                                                                                                                                                       | `false` |
```

2019-06-25 13:00 UTC, lkysow commented
Thanks Andy, can you squash your commits so there's only 1? Then we're good to go.

2019-06-25 14:34 UTC, adharmawan commented
Hi @lkysow, so I followed [this guide](https://github.com/wprig/wprig/wiki/How-to-squash-commits) on how to squash all the commits. Managed to do that (I only have one commit now)

```sh
❯ gst
On branch atlantisv0.8.0
Your branch and 'origin/atlantisv0.8.0' have diverged,
and have 1 and 479 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

but when I do a git log, it includes the commit messages from other charts.

```sh
commit eca4608f66c719b7b337b4ba412397275faa3d37 (HEAD -> atlantisv0.8.0)
Author: Andy Aldo Dharmawan <andyaldodharmawan@gmail.com>
Date:   Wed May 29 18:23:51 2019 +0800

    [stable/atlantis] Add options to pass --disable-apply-all

    Signed-off-by: Andy Aldo Dharmawan <andyaldodharmawan@gmail.com>

    [stable/atlantis] Update docker image tag

    Signed-off-by: Andy Aldo Dharmawan <andyaldodharmawan@gmail.com>

    [stable/atlantis] Bump version

    Signed-off-by: Andy Aldo Dharmawan <andyaldodharmawan@gmail.com>

    [stable/velero] Render `extraEnvVars` even when not using credentials (#14184)

    * [stable/velero] Render `extraEnvVars` even when not using credentials

    Fixes #14130

    Signed-off-by: Elisiano Petrini <elisiano@gmail.com>

    * [stable/velero] Chart version bump
...
```

I am pretty sure I'm doing it wrongly, would appreciate if you can advise on this

2019-06-25 14:53 UTC, lkysow commented
The easiest thing for you to do is probably:
1. rename your branch locally to a backup: `git branch -m atlantisv0.8.0-backup`
1. get the latest helm/charts `master` and check out a new branch from that called `atlantisv0.8.0`
1. manually apply the same changes you made in this pull request
1. commit the changes in a single commit
1. force push your branch up

2019-06-25 15:16 UTC, adharmawan commented
Done, thanks @lkysow

2019-06-25 16:20 UTC, lkysow commented
/lgtm

2019-06-25 16:28 UTC, merged