[stable/postgresql] Add namespace variable to metadata to honor spinnaker helm deployments
helm/charts pull request #14247
Opened 2019-05-29 11:34 UTC by mruepp

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #3988

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-05-29 11:56 UTC, mruepp commented
/assign @tompizmor

2019-05-30 07:31 UTC, tompizmor approved these changes
/ok-to-test
/lgtm

2019-05-30 07:42 UTC, tompizmor requested changes

2019-05-30 07:42 UTC, tompizmor commented on stable/postgresql/Chart.yaml
> +version: 5.1.2
```suggestion
version: 5.1.3
```

The version 5.1.2 is already merged in master. Can you bump the version again?

2019-06-18 15:14 UTC, paulczar commented
@mruepp can you try this using the namespaceOverride here ? spinnaker/clouddriver#3678

2019-08-01 15:46 UTC, closed without merging