Allow explicit NodePort value for prometheus
helm/charts pull request #1427
Opened 2017-07-04 13:50 UTC by kelveden

Currently, if one wants prometheus running as a NodePort service one is stuck with whatever port is dynamically assigned when the service starts. This PR allows the explicit specification of the NodePort port with the `server.service.nodePort` value.

2017-07-04 14:45 UTC, kelveden commented
Signed.

2017-08-02 02:08 UTC, mgoodness requested changes
Looks pretty good. Just a couple of nits, and be sure to add the new value to `values.yaml`, with a default of 0.

2017-08-02 02:08 UTC, mgoodness commented on stable/prometheus/README.md
> +`server.service.nodePort` | Port to be used as the service NodePort (ignored if `service.service.type` is not `NodePort`) | `None`
ignored if `**server**.service.type`...

And let's set the default value to `0`

2017-08-02 02:08 UTC, mgoodness commented on stable/prometheus/templates/server-service.yaml
> +{{- end }}
Nit: indent the if...end statements 4 spaces so the dashes align with the 'n'  in `nodePort`

2017-08-02 02:08 UTC, mgoodness commented
/ok-to-test

2017-08-05 22:11 UTC, kelveden commented
@mgoodness Thanks for the review. The requested changes are ready to roll.

2017-08-05 22:22 UTC, kelveden commented
I'm not sure how to read that e2e test failure. The container for the prometheus-server pod failed to get created in time (it got stuck in `ContainerCreating` state) but there's also the `Unable to create listener: Error listen tcp6 [::1]:34935: bind: cannot assign requested address` which I'm not sure is a symptom or the cause.

2017-08-11 00:15 UTC, prat0318 commented
+1 for the change. Is there a way to rerun the failed e2e test?

2017-08-11 05:21 UTC, unguiculus commented
/retest

2017-08-14 19:47 UTC, mgoodness approved these changes

2017-08-14 19:47 UTC, mgoodness commented
/lgtm

2017-08-14 19:56 UTC, merged