[stable/mariadb] add metrics servicemonitor
helm/charts pull request #14279
Opened 2019-05-29 12:47 UTC by zh168654

#### What this PR does / why we need it:

Add support for prometheus operator ServiceMonitor.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-05-29 12:51 UTC, zh168654 commented
/assign @tompizmor

2019-05-30 09:15 UTC, juan131 requested changes
Thanks so much for your contribution, please take a look to my suggestions.

- Document all the new parameters in the **README.md**
- I'd rename the file from `servicemonitors.yaml` to `servicemonitor.yaml`

2019-05-30 09:15 UTC, juan131 commented on stable/mariadb/Chart.yaml
> +version: 6.2.2
Increase minor version:
```suggestion
version: 6.3.0
```

2019-05-30 09:15 UTC, juan131 commented on stable/mariadb/templates/servicemonitors.yaml
> +{{ if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
```suggestion
{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
```

2019-05-30 09:15 UTC, juan131 commented on stable/mariadb/templates/servicemonitors.yaml
> +      release: {{ .Release.Name }}
Be consistent with the way you declared the labels before:
```suggestion
      release: {{ .Release.Name | quote }}
```

2019-05-30 09:15 UTC, juan131 commented on stable/mariadb/templates/servicemonitors.yaml
> +{{ end }}
```suggestion
{{- end }}
```

2019-05-30 14:19 UTC, zh168654 commented
> Thanks so much for your contribution, please take a look to my suggestions.
> 
> * Document all the new parameters in the **README.md**
> * I'd rename the file from `servicemonitors.yaml` to `servicemonitor.yaml`

@juan131 Thanks for your feedback and suggestions. 
I have followed your recommendation and modified the commits

2019-05-31 07:52 UTC, juan131 commented on stable/mariadb/README.md
> +| `metrics.serviceMonitor.enabled`          | if `true`, creates a Prometheus Operator ServiceMonitor (also requires `metrics.enabled` to be `true`)                    | `nil`
You set the default value to `nil` but it is actually `false`

2019-05-31 07:52 UTC, juan131 requested changes
A minor change

2019-05-31 11:58 UTC, zh168654 commented
@juan131 Thanks, and sorry for the mistake and some previous wrong behaviour

2019-05-31 14:27 UTC, juan131 commented
/ok-to-test
/lgtm

2019-05-31 14:38 UTC, merged