[stable/postgresql] Add extraVolumeMount and Volume to Postgresql Master and Slave
helm/charts pull request #14280
Opened 2019-05-29 13:50 UTC by baluchicken

Signed-off-by: Balint Molnar <balintmolnar91@gmail.com>

#### What this PR does / why we need it:
This PR allows to add extraVolumeMounts and Volumes to Postgresql Master and Slave StatefulSet.
E.g.:
```
  extraVolumeMounts:
    - name: bar
      mountPath: /bar/
    - name: foo
      mountPath: /foosecret/
  extraVolumes:
    - name: foo
      secret:
        secretName: foosecret
    - name: bar
      emptyDir: {}
```
#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-05-29 15:03 UTC, baluchicken commented
/assign @carrodher

2019-05-30 10:45 UTC, javsalgar commented on stable/postgresql/templates/statefulset-slaves.yaml
> +      {{ toYaml .Values.slave.extraVolumes | indent 6}}
```suggestion
      {{- toYaml .Values.slave.extraVolumes | nindent 6}}
```

2019-05-30 10:45 UTC, javsalgar commented on stable/postgresql/templates/statefulset-slaves.yaml
> +        {{ toYaml .Values.slave.extraVolumeMounts | nindent 8 }}
```suggestion
        {{- toYaml .Values.slave.extraVolumeMounts | nindent 8 }}
```

2019-05-30 10:46 UTC, javsalgar requested changes

2019-05-30 10:46 UTC, javsalgar commented on stable/postgresql/templates/statefulset-slaves.yaml
> +      {{ toYaml .Values.slave.extraVolumes | indent 6}}
I see that in one it is indent 6 and in the other indent 8. Make sure which the right indentation is

2019-05-30 11:43 UTC, baluchicken commented
@javsalgar thanks for your review in case of extraVolume it is 6 but for extraVolumeMount it is 8

2019-05-31 08:41 UTC, javsalgar commented
LGTM. Could you please fix the conflicts?

2019-05-31 09:39 UTC, baluchicken commented
@javsalgar rebased to master

2019-05-31 10:16 UTC, carrodher commented
/ok-to-test
/lgtm

2019-05-31 10:24 UTC, merged