Use consistent whitespace in template placeholders
helm/charts pull request #1437
Opened 2017-07-05 12:06 UTC by fhemberger

2017-07-05 18:31 UTC, unguiculus commented
Thanks a lot. This is very much appreciated. But I'm afraid most of this, if not all, has already been done in #1062 which has just been merged today.

2017-07-05 18:42 UTC, fhemberger commented
@unguiculus Hmm, the issue you mentioned is about Ealsticsearch. 🤔

2017-07-05 18:45 UTC, unguiculus commented
Ouch, sorry. I guess I got confused by the merge conflicts. Here's an open PR for Artifactory which should get merged soon: #1314.

2017-07-05 18:50 UTC, fhemberger commented
@unguiculus I updated the PR to resolve the merge conflicts. My PR doesn't just cover Artifactory, it fixes the template placeholder whitespace in *all* charts.

2017-07-05 18:57 UTC, unguiculus commented
Wow, I guess I did not look far enough. Did you use some script for this? 

Usually we want separate PRs per chart. Do you think you can split this up?

@kubernetes/charts-maintainers How should we go about this? I think this is great.

2017-07-05 19:06 UTC, fhemberger commented
Just a simple Regex search & replace in Sublime Text:

`{{([^ -])` -> `{{ $1`
`([^ -])}}` -> `$1 }}`

Splitting it up would have ended up in 38 separate PRs just adding whitespace, so I left it in one single PR instead. 😉

https://github.com/kubernetes/charts/pull/1437/files?w=1 shows that it's really only whitespace that has changed.

2017-07-05 19:23 UTC, unguiculus commented
Maybe we can take this as a whole. Discussing it on Slack.

2017-07-05 19:30 UTC, unguiculus requested changes
I just found one place where the replace should not happen.

2017-07-05 19:30 UTC, unguiculus commented on incubator/etcd/templates/etcd-statefulset.yaml
> +            SET_ID=${HOSTNAME:5:${#HOSTNAME }}
This is shell not Go templating. We probably don't want to change that.

2017-07-05 19:40 UTC, fhemberger commented on incubator/etcd/templates/etcd-statefulset.yaml
> +            SET_ID=${HOSTNAME:5:${#HOSTNAME }}
Fixed.

2017-07-05 19:49 UTC, unguiculus approved these changes

2017-07-05 21:04 UTC, mgoodness commented
/test pull-charts-e2e

2017-07-06 04:05 UTC, fhemberger commented
Rebased master, fixed tensorflow helper.

/retest

2017-07-06 09:07 UTC, unguiculus commented
/retest

2017-07-06 09:59 UTC, fhemberger commented
@unguiculus Sorry, not sure what's wrong with the Jenkins built, I don't think it's actually related to my changes.

2017-07-07 05:37 UTC, unguiculus commented
Yeah, there seems to be some test flakiness. We are going to merge this as a whole. Anything else does not make sense.

2017-07-07 06:01 UTC, unguiculus commented
Would you mind covering `NOTES.txt` files as well? I understand that those will not be as easy because they often contain shell magic. But we can just try and get this in soon and follow up with that in a separate PR.

2017-07-07 09:08 UTC, fhemberger commented
Sure, I can do that as well, but I'd prefer a separate PR to minimize impact.

2017-07-08 14:47 UTC, fhemberger commented
@unguiculus Fixing NOTES.txt wasn't so bad, so I added it here. Also fixed parameter order on three occasions, so the command is always identical. Should I also adjust `APP_HOST` vs. `SERVICE_IP`? (I'd prefer the latter, it is more precise.)

2017-07-09 19:10 UTC, unguiculus commented
I'm going to merge this as is. You may create a separate PR as follow-up. I'd prefer SERVICE_IP as well.

2017-07-09 19:11 UTC, merged

2017-07-09 19:34 UTC, fhemberger commented
Awesome, thanks!

2017-07-10 10:11 UTC, rk295 commented
Hi, this commit breaks (at least) the grafana chart. It fails a lint with the default values. 

```==> Linting grafana/
[ERROR] templates/: parse error in "grafana/templates/job.yaml": template: grafana/templates/job.yaml:41: unexpected "}" in operand

Error: 1 chart(s) linted, 1 chart(s) failed
```

2017-07-10 10:11 UTC, rk295 commented
As a follow up, would it be worth having CI lint each of the charts in branches before merging?

2017-07-10 10:57 UTC, fhemberger commented
@rk295 Sorry, didn't notice the change in the Job.
Fixed in #1458.