RBAC, namespaces, and node-exporter default update
helm/charts pull request #1443
Opened 2017-07-06 15:33 UTC by alejandroEsc

- rbac is off by default, but can be turned on
- added clusterroles, bindings and service accounts
- added namespaces where needed.
- updated default node-exporter because previous version had a fairly serious bug disallowing it to start up properly.

2017-07-17 14:26 UTC, alejandroEsc commented
@mgoodness could you please review or assign?

2017-07-28 18:14 UTC, alejandroEsc commented
@mgoodness could I get an eta on this review? if you are too busy any suggestions to possible maintainers that may be able to take over?

2017-07-28 23:39 UTC, cortesi commented
@mgoodness I'd like to add my voice to @alejandroEsc here. The Prometheus chart is critical, and it is often broken for months on end with all PRs self-assigned to you and no activity.

2017-08-02 00:32 UTC, mgoodness requested changes
The changes I'm requesting generally follow the RBAC pattern we established in #1504. I only commented on the first part of `rbac-clusterrolebindings`, but the changes should be applied throughout that file, `rbac-clusterroles`, and `rbac-serviceaccounts`.

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/alertmanager-deployment.yaml
> +      {{- end }}
Use `serviceAccountName: {{ if .Values.createRbac }}{{ template "prometheus.alertmanager.fullname" . }}{{ else }}"{{ .Values.alertmanager.serviceAccountName }}"{{ end }}`

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/kube-state-metrics-deployment.yaml
> +      {{- end }}
Use `serviceAccountName: {{ if .Values.createRbac }}{{ template "prometheus.kubeStateMetrics.fullname" . }}{{ else }}"{{ .Values.kubeStateMetrics.serviceAccountName }}"{{ end }}`

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/node-exporter-daemonset.yaml
> +      {{- end }}
Use `serviceAccountName: {{ if .Values.createRbac }}{{ template "prometheus.nodeExporter.fullname" . }}{{ else }}"{{ .Values.nodeExporter.serviceAccountName }}"{{ end }}`

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/server-deployment.yaml
> +      {{- end }}
Use `serviceAccountName: {{ if .Values.createRbac }}{{ template "prometheus.fullname" . }}{{ else }}"{{ .Values.server.serviceAccountName }}"{{ end }}`

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/rbac-clusterrolebindings.yaml
> +---
Delete all YAML separators, and break the file up (one per CRB). Grouping resources like this can cause problems when upgrading.

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/rbac-clusterrolebindings.yaml
> +{{- if .Values.rbac.install }}
Use `{{- if .Values.createRbac -}}`

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/rbac-clusterrolebindings.yaml
> +apiVersion: rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}
We only support the last two versions of Kubernetes (currently 1.6 & 1.7), so it's safe to statically set the API version to `v1beta1`.

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/rbac-clusterrolebindings.yaml
> +  name: prometheus-server-binding
Use `name: {{ template "prometheus.fullname" . }}`

Also add standard labels (app, chart, release, component, heritage).

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/rbac-clusterrolebindings.yaml
> +  name: prometheus-server-account
Use `name: {{ template "prometheus.fullname" . }}`

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/rbac-clusterrolebindings.yaml
> +  name: prometheus-server
Use `name: {{ template "prometheus.fullname" . }}`

2017-08-02 00:32 UTC, mgoodness commented on stable/prometheus/templates/rbac-clusterrolebindings.yaml
> +  #name: cluster-admin
Delete

2017-08-02 02:17 UTC, mgoodness commented
Fixes #1075

2017-08-04 04:25 UTC, alejandroEsc commented
@mgoodness thanks for the review, will start ASAP.

2017-08-07 14:12 UTC, alejandroEsc commented
@mgoodness I believe I addressed all your points. The only thing I did not address was the apiVersion rbac option. You suggest I leave it as v1beta1 and remove this value. But I think until we are at v1 it still a good idea.

2017-08-10 15:41 UTC, naveensrinivasan commented
@mgoodness Any update on this?

2017-08-10 18:08 UTC, chainlink commented
Also waiting on this one to test prometheus on GCE

2017-08-10 18:44 UTC, maartenvanvliet commented
I have enabled Legacy authorization on GCE to test prometheus. Works great. Waiting for this to be accepted though, and disable Legacy authorization again.

2017-08-10 18:47 UTC, chainlink commented
Good to know @maartenvanvliet !

2017-08-14 20:05 UTC, mgoodness commented
Reviewing right now. Sit tight.

2017-08-14 21:42 UTC, mgoodness approved these changes

2017-08-14 21:53 UTC, mgoodness commented
serviceAccountNames now defaults to `default` if `rbac.create=false`, as is our pattern.

I also set the RBAC apiVersion to v1beta1. When it hits v1, we'll handle compatibility with a conditional based on the `.Capabilities` object.

Please test one more time to make sure I didn't bork anything.

2017-08-14 21:54 UTC, mgoodness commented
/lgtm

2017-08-17 05:33 UTC, jurgenweber commented
eta on merge? This would be really handy.

2017-08-17 10:43 UTC, dhilipkumars commented
/retest

2017-08-17 12:48 UTC, seh commented on stable/prometheus/templates/alertmanager-clusterrolebinding.yaml
> +  name: cluster-admin
- [ ] Given that Alertmanager only _reads_ objects, giving it the "cluster-admin" _ClusterRole_ is rather generous.  
  Better would be to define a _ClusterRole_ that allows it to read only what it needs to read.

2017-08-17 12:48 UTC, seh commented on stable/prometheus/templates/node-exporter-clusterrolebinding.yaml
> +  name: cluster-admin
- [ ] Given that Node Exporter only reads things, giving it the "cluster-admin" _ClusterRole_ is rather generous.  
  Better would be to define a _ClusterRole_ that allows it to read only what it needs to read. What does it need to read from the API server?

2017-08-17 12:48 UTC, seh commented on stable/prometheus/values.yaml
> +  serviceAccountName: default
- [ ] You risk granting the "cluster-admin" _ClusterRole_ to the "default" service account here.

2017-08-17 13:38 UTC, mgoodness commented on stable/prometheus/values.yaml
> +  serviceAccountName: default
Pods only run as `.Values.serviceAccountName` if `rbac.create=false`. In that case, none of the RBAC resources are created and it's up to the user to configure permissions externally.

2017-08-17 13:40 UTC, seh commented on stable/prometheus/values.yaml
> +  serviceAccountName: default
That comment above is confusing, then. It says, "when [RBAC] is enabled," which I took to mean "when this chart plays along with RBAC."

2017-08-17 13:45 UTC, mgoodness commented
@jurgenweber I'd been [waiting](https://github.com/kubernetes/charts/pull/1443#issuecomment-322320396) for someone to deploy & test this before I merged. Also, like @seh, I'm somewhat uncomfortable running alertmanager & node exporter as `cluster-admin`. However, if the consensus is to improve RBAC in another PR, I'll get this merged today.

2017-08-17 13:47 UTC, mgoodness commented on stable/prometheus/values.yaml
> +  serviceAccountName: default
Fair enough. I'll be explicit about `rbac.enabled=true`.

2017-08-17 14:53 UTC, chainlink commented
Tested this on gce with 1.6 and it works great out of the box!

2017-08-18 02:44 UTC, jurgenweber commented
@mgoodness ok, I started giving it a go and then go distracted but as far as I could see all of the resources were green. Not a great test I know, but it is a fresh install for me.

2017-08-18 15:29 UTC, merged

2017-08-18 15:36 UTC, seh commented on stable/prometheus/templates/alertmanager-clusterrolebinding.yaml
> +  name: cluster-admin
This still strikes me as dangerous. If an administrator installs this chart into a namespace in which other non-administrators can run pods, those other users can run a pod using this service account, and escalate their privileges up to "cluster-admin." I think you should at least document this hazard if you're not willing to come up with a safer, narrower _ClusterRole_ for Alertmanager here.

2017-08-18 15:37 UTC, seh commented on stable/prometheus/templates/node-exporter-clusterrolebinding.yaml
> +  name: cluster-admin
[Likewise](https://github.com/kubernetes/charts/pull/1443/files#r133989161), but here with Node Exporter.

2017-08-18 15:41 UTC, mgoodness commented on stable/prometheus/templates/alertmanager-clusterrolebinding.yaml
> +  name: cluster-admin
Any refinement of the the RBAC permissions can & should be submitted through PRs.

2017-08-21 03:54 UTC, jurgenweber commented
thanks for the merge, for the record I upgraded to kube 1.7.4 and it works great. :) Thanks again.