Add securityContext to MongoDB metrics sidecar container
helm/charts pull request #14443
Opened 2019-06-04 10:19 UTC by miguelaeh

This pull request add the security context to the metrics sidecar container, to use the same security context as MongoDB.

2019-06-04 10:35 UTC, carrodher commented
cc @carrodher

2019-06-04 10:38 UTC, carrodher commented
/cc @carrodher

2019-06-05 11:14 UTC, juan131 requested changes
I'm okay with the changes but I'd like to hear form other maintainers: @carrodher

2019-06-05 11:14 UTC, juan131 commented on stable/mongodb/Chart.yaml
> +version: 5.18.1
Bump minor Version:
```diff
version: 5.18.1
version: 5.19.0
```

2019-06-05 12:40 UTC, carrodher commented
Did you test if the metrics image is configured to run as not root properly? I mean, it's not a Bitnami image so I don't know what practices it follows

2019-06-05 12:44 UTC, miguelaeh commented
> Did you test if the metrics image is configured to run as not root properly? I mean, it's not a Bitnami image so I don't know what practices it follows

Yes, I tested it and looking to the log output it works as if it was root.

2019-06-05 13:49 UTC, carrodher commented
Can you rebase the changes and resolve conflicts? After that, I can add the proper tags

2019-06-05 15:45 UTC, miguelaeh commented
Sure. I performed the rebase and resolve the conflict on that last push.

2019-06-06 07:52 UTC, carrodher commented
/ok-to-test
/lgtm

2019-06-06 08:00 UTC, merged