[stable/cerebro] Enables use of Cerebro provided auth
helm/charts pull request #14506
Opened 2019-06-04 21:24 UTC by wvidana

#### What this PR does / why we need it:
 * Enables use of Cerebro provided auth by using the app's `auth` section in the config file https://github.com/lmenezes/cerebro/blob/f2ed031fd89258c6ad85d40d846f5ff1f610fe73/conf/application.conf#L25-L62
 * Also provides the ability to reference a `Secret` object to get the env vars from.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-06-04 21:25 UTC, wvidana commented
/assign @davidkarlsen

2019-06-04 23:36 UTC, davidkarlsen requested changes

2019-06-04 23:36 UTC, davidkarlsen commented on stable/cerebro/Chart.yaml
> +version: 1.1.2
```suggestion
version: 1.1.0
```

2019-06-04 23:36 UTC, davidkarlsen commented
/ok-to-test

2019-06-06 21:42 UTC, wvidana commented
@davidkarlsen changes pushed per suggestions https://github.com/helm/charts/pull/14506#pullrequestreview-245752033

2019-06-12 20:04 UTC, wvidana commented
@davidkarlsen ping

2019-06-17 13:09 UTC, davidkarlsen commented
/lgtm

2019-06-17 13:09 UTC, davidkarlsen approved these changes

2019-06-17 13:22 UTC, merged