[stable/aws-alb-ingress-controller] Adding priority class support 🔺
helm/charts pull request #14512
Opened 2019-06-05 03:16 UTC by johndaviesco

Summoning @bigkraig and/or @M00nF1sh  per the PR template. Thanks for taking the time to review this, it's much appreciated!

####Special notes for your reviewer:
I installed this change on an EKS cluster and the  priority class appeared as expected.

#### What this PR does / why we need it:
Adding `priorityClassName` support for aws-alb-ingress-controller.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-06-05 17:00 UTC, M00nF1sh commented
/ok-to-test

2019-06-06 03:40 UTC, johndaviesco commented
Hey @komljen could you run the `ok-to-test` on this please. @M00nF1sh tried but didn't have permissions

2019-06-06 07:17 UTC, komljen commented
I can try, but it will not work as I'm not in the owners list of this chart. @M00nF1sh Should be able to do it, not sure why it didn't work.

2019-06-06 07:17 UTC, komljen commented
/ok-to-test

2019-06-06 07:18 UTC, komljen commented
Ah, actually it worked :)

2019-06-06 22:06 UTC, johndaviesco commented
@komljen could you also give it a `/lgtm`

2019-06-07 05:24 UTC, komljen commented
/lgtm

2019-06-08 03:55 UTC, johndaviesco commented
Hey @M00nF1sh your in the owners file do you want to try `/lgtm` if you approve ?

2019-06-10 22:21 UTC, johndaviesco commented
Hey @bigkraig your in the owners file do you want to try /lgtm if you approve ?

2019-06-10 22:40 UTC, bigkraig requested changes

2019-06-10 22:40 UTC, bigkraig commented on incubator/aws-alb-ingress-controller/README.md
> +| `priorityClassName`       | priorityClassName                                                                                              | `""`
can you add a description here of what the setting is?

2019-06-10 22:40 UTC, bigkraig commented on incubator/aws-alb-ingress-controller/README.md
> +| `podLabels`               | labels to be added to controller pod                                                                           | `{}`
it looks like this line was corrupted

2019-06-11 02:54 UTC, johndaviesco commented
Hey @bigkraig I think I have addressed your concerns can you please review ?

2019-06-17 22:01 UTC, bigkraig commented
/lgtm
/approve

2019-06-17 22:18 UTC, merged