Add chart for Traefik-based ingress controller
helm/charts pull request #146
Opened 2016-10-24 21:19 UTC by krancour

2016-10-24 21:44 UTC, prydonius commented
Thanks @krancour!

2016-10-24 21:45 UTC, prydonius commented on incubator/traefik/README.md
> +Let's Encrypt. By default, Traefik will be installed into the `kube-system` namespace.
Is this a requirement? I think we generally prefer that Helm manages the namespace Charts get installed into with the `--namespace` flag.

2016-10-24 23:08 UTC, krancour commented on incubator/traefik/README.md
> +Let's Encrypt. By default, Traefik will be installed into the `kube-system` namespace.
It's not a hard and fast requirement, however, since ingress controllers are frequently used to watch `Ingress` objects _cluster-wide_ (i.e. in all namespaces), they often require the elevated permissions of the `kube-system` namespace's default service account.

When writing this chart, I assumed that for the less-frequent (or so I imagine) use case where someone _does_ want to install this into some other namespace that `--namespace` would _override_ the hard-coded default of `kube-system`. I've put that to the test now, however, and found it doesn't work that way!

cc @technosophos @michelleN isn't `--namespace` supposed to override whatever default is hard-coded in the chart's manifests? Or was it just wishful thinking on my part that it works that way?

At any rate, it does seem that what is best for now is that I omit this hard-coded default and instead _document_ that this component would most often be installed into `kube-system`.

2016-10-24 23:28 UTC, krancour commented on incubator/traefik/README.md
> +Let's Encrypt. By default, Traefik will be installed into the `kube-system` namespace.
@prydonius I've amended the PR as discussed above.

2016-10-25 00:30 UTC, chrislovecnm requested changes
Thanks for the PR, looks awesome. Have some recommended tweaks

2016-10-25 00:30 UTC, chrislovecnm commented on incubator/traefik/LICENSE
> +Copyright (c) 2016 Deis
Do we need this? This project is Apache 2 licensed and now we have MIT?

2016-10-25 00:30 UTC, chrislovecnm commented on incubator/traefik/templates/deployment.yaml
> +    spec:
ready and lively probes please, as well as resource limits ;)

2016-10-25 00:30 UTC, chrislovecnm commented on incubator/traefik/templates/deployment.yaml
> +        persistentVolumeClaim:
It there value to have storage classes?

2016-10-25 00:30 UTC, chrislovecnm commented on incubator/traefik/templates/deployment.yaml
> +        persistentVolumeClaim:
It == Is

2016-10-25 01:52 UTC, krancour commented on incubator/traefik/LICENSE
> +Copyright (c) 2016 Deis
Well, that's a tricky question. It seems individual charts are subject to their own license, no? What I opted to do here was use the same license that Traefik itself uses. If that's the wrong move, lmk.

2016-10-25 01:52 UTC, krancour commented on incubator/traefik/templates/deployment.yaml
> +    spec:
Yep. Good call.

2016-10-25 01:57 UTC, krancour commented on incubator/traefik/templates/deployment.yaml
> +        persistentVolumeClaim:
I'm not sure what you're asking here. Can you clarify please?

This currently follows the exact pattern used by the stable MySQL chart for persistent storage.

2016-10-25 02:08 UTC, viglesiasce commented on incubator/traefik/LICENSE
> +Copyright (c) 2016 Deis
I think this code/repo can have a separate license from the source of traefik itself.

2016-10-25 02:10 UTC, viglesiasce commented on incubator/traefik/values.yaml
> +  defaultCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVtekNDQTRPZ0F3SUJBZ0lKQUpBR1FsTW1DMGt5TUEwR0NTcUdTSWIzRFFFQkJRVUFNSUdQTVFzd0NRWUQKVlFRR0V3SlZVekVSTUE4R0ExVUVDQk1JUTI5c2IzSmhaRzh4RURBT0JnTlZC
Can this be a secret name instead? Then the docs could outline how to create that secret (keys/values) such that it can be used here?

2016-10-25 02:10 UTC, viglesiasce commented on incubator/traefik/templates/deployment.yaml
> +        persistentVolumeClaim:
The storage class is defined in the PVC not the deployment. Nothing to see here.

2016-10-25 02:11 UTC, viglesiasce commented
Awesome stuff @krancour!

2016-10-25 02:12 UTC, viglesiasce commented
@k8s-bot ok to test

2016-10-25 02:14 UTC, krancour commented on incubator/traefik/LICENSE
> +Copyright (c) 2016 Deis
Ok. I'll change it.

2016-10-25 02:24 UTC, krancour commented on incubator/traefik/values.yaml
> +  defaultCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVtekNDQTRPZ0F3SUJBZ0lKQUpBR1FsTW1DMGt5TUEwR0NTcUdTSWIzRFFFQkJRVUFNSUdQTVFzd0NRWUQKVlFRR0V3SlZVekVSTUE4R0ExVUVDQk1JUTI5c2IzSmhaRzh4RURBT0JnTlZC
If I can make an argument for keeping it as it is...

The base64 encoded cert and key you put here _becomes_ a secret. This means that you provide customizations to this either through `--set` on the command line or in your own `values.yaml`. i.e. You can customize these through the usual Helm workflow for customizing a chart.

Compare that to some other approach that requires a careful reading of the documentation and an "out of band" effort to create the secrets... I don't believe that compares favorably to what's in place now.

2016-10-25 02:27 UTC, viglesiasce commented on incubator/traefik/values.yaml
> +  defaultCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVtekNDQTRPZ0F3SUJBZ0lKQUpBR1FsTW1DMGt5TUEwR0NTcUdTSWIzRFFFQkJRVUFNSUdQTVFzd0NRWUQKVlFRR0V3SlZVekVSTUE4R0ExVUVDQk1JUTI5c2IzSmhaRzh4RURBT0JnTlZC
Fair. I'm fine as is. If users want something different, I'm sure they will chime in down the road.

Could I ask you to add instructions on getting those values? Also what do the default certs point to?

2016-10-25 02:37 UTC, krancour commented on incubator/traefik/values.yaml
> +  defaultCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVtekNDQTRPZ0F3SUJBZ0lKQUpBR1FsTW1DMGt5TUEwR0NTcUdTSWIzRFFFQkJRVUFNSUdQTVFzd0NRWUQKVlFRR0V3SlZVekVSTUE4R0ExVUVDQk1JUTI5c2IzSmhaRzh4RURBT0JnTlZC
The readme has a table describing the configuration options. It's clear that the cert and key should be base64 encoded. I can add more specific instructions if you like. lmk

The cert that's included is a self-signed cert for *.example.com-- so it's basically garbage. The benefit, however, is that it's enough to get people going.

I will update the table to reflect the details of this cert.

2016-10-25 09:25 UTC, ekozan commented
@krancour  Can you integrate HostPort option or I'll make a PR after merge

2016-10-25 12:53 UTC, krancour commented
@ekozan, did you mean `NodePort`? You want that as an alternative to `type: LoadBalancer`?

That seems a reasonable option (but not a default). It would certainly be a benefit to anyone who wants to run this anywhere where the "cloud provider" no-ops provisioning of an external load balancer-- e.g. minikube or bare metal.

I'd be happy to add that.

2016-10-25 15:28 UTC, vdice commented on incubator/traefik/README.md
> +traffic the load balancer. You can you the command below to find the load balancer's DNS name:
a couple minor typos here; perhaps the following were intended: `... direct inbound traffic to the load balancer` and `You can use the command ...`

2016-10-25 15:44 UTC, krancour commented on incubator/traefik/README.md
> +traffic the load balancer. You can you the command below to find the load balancer's DNS name:
Nice eye, @vdice. Will fix.

2016-10-25 16:20 UTC, viglesiasce commented
Tested manually and all things seem to check out. Thanks again @krancour! Let me know when you've patched the README fixes. Also if you'd like to get this into stable, adding a NOTES.txt pointing people in the right direction for how to configure and use traefik would do the trick.

2016-10-25 16:27 UTC, krancour commented
@viglesiasce great. I will try and amend with all suggested fixes as soon as time permits-- a few hours off, for sure.

2016-10-25 17:37 UTC, ekozan commented on incubator/traefik/README.md
> +$ helm install --name my-release --namespace kube-system --set dashboard.enabled=true,dashboard.domain=traefik.example.com stable/traefik
Actually it's incubator/traefik not stable/traefik

2016-10-25 17:40 UTC, ekozan commented
Yeap it's an alternative for barebone cluster ;)

We need 
Add option like Expose: LoadBalancer / HostPort / NodePort  
Add option for switch to Deamonset is needed too :p i'll handle this if you dont want to add this one

2016-10-25 18:35 UTC, ultimateboy commented
Just thought I'd report my successful testing of this chart, and Traefik's ability to issue certs from Let's Encrypt.

```
helm install incubator/traefik --name my-traefik --namespace kube-system --set dashboard.enabled=true,dashboard.domain=traefik.domain.you.own.com,ssl.enabled=true,acme.enabled=true,acme.email=admin@domain.you.own.com
```

```
kubectl run nginx --image=nginx
kubecl expose deploy nginx --port=80 --target-port=80
```

```
echo "apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: default
spec:
  rules:
  - host: some.domain.you.own.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80" > ingress.yaml

kubectl create -f ingress.yaml```


```echo | openssl s_client -servername some.domain.you.own.com -connect some.domain.you.own.com:443 2>/dev/null | openssl x509 -noout -issuer
issuer= /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3```

2016-10-25 22:01 UTC, krancour commented
It'll be tomorrow before I get to this.

2016-10-26 03:31 UTC, chrislovecnm commented on incubator/traefik/README.md
> +$ helm install --name my-release --namespace kube-system --set dashboard.enabled=true,dashboard.domain=traefik.example.com stable/traefik
If he adds a NOTES.txt it can be merged into stable directly

2016-10-27 04:08 UTC, krancour commented on incubator/traefik/LICENSE
> +Copyright (c) 2016 Deis
I'm actually just going to remove the license from this chart altogether. It seems license is optional for charts and no other chart in this repo includes one. I'm going to follow that precedent.

2016-10-27 06:11 UTC, krancour commented
@viglesiasce I've addressed comments apart from one. You indicated I should add a `NOTES.txt` "pointing people in the right direction for how to configure and use traefik."

I'm unclear on what that should contain or what its purpose would be.

`charts.yaml` already points users in the direction of the Traefik documentation. That aside, detailed knowledge of configuring Traefik isn't required to use this chart, since all customizations are carried out not by editing Traefik's config directly, but by supplying a `value.yaml` instead.

2016-10-27 06:12 UTC, krancour commented
@ultimateboy offline you asked me to support LE staging to avoid rate limits when testing / experimenting. I've added that now and made it the default as well (when ACME is enabled). Check it out and lmk what you think.

2016-10-27 15:13 UTC, ultimateboy commented
@krancour Awesome! It's probably worth explicitly calling that configuration out in the README as people might be confused why they aren't getting real valid certs. But this looks great!

2016-10-28 18:32 UTC, krancour commented
@viglesiasce nevermind re: my previous question about notes.txt... I realize now that this is an optional, but conventional component of charts. I've looked at some existing charts to get a sense of what sort of info is usually included. Pending the addition of those notes, I think this PR is into a reviewable state.

2016-10-30 00:14 UTC, chrislovecnm commented
Before we merge you mind squashing your commits into units of work? Thanks

2016-10-30 14:52 UTC, krancour commented
@chrislovecnm I was going to squash everything into one commit when done. Is that acceptable?

2016-10-30 16:18 UTC, chrislovecnm commented
@krancour your call mate!

2016-10-31 16:28 UTC, viglesiasce commented
No need to squash on your end as Github now allows Squash and merge when accepting the pull request.

2016-11-01 01:50 UTC, krancour commented
Ya... knew that, but not all projects necessarily have that enabled. If it's enabled here, awesome.

2016-11-01 22:25 UTC, lachie83 commented
I've reached out to @krancour and have agreed to work on getting a NOTES.txt into this chart.

2016-11-02 05:04 UTC, lachie83 commented
Seeing the following in the log file
```
time="2016-11-02T05:00:14Z" level=error msg="Kubernetes connection error failed to decode watch event: GET \"https://10.3.0.1:443/apis/extensions/v1beta1/ingresses\" : unexpected EOF, retrying in 682.444463ms" 
```

Looks like it's an issue with traefik -- https://github.com/containous/traefik/issues/732

2016-11-02 05:14 UTC, lachie83 commented
Tried putting an ingress in-front of Jenkins and it doesn't look like it handles more complex backends. Found this open issue -- https://github.com/containous/traefik/issues/30

2016-11-02 06:23 UTC, lachie83 commented
Added NOTES.txt. I believe this is the only outstanding item on this PR. Please review

2016-11-02 16:49 UTC, lachie83 commented
@krancour Thanks for updating NOTES.txt. Looks good!

2016-11-02 16:53 UTC, lachie83 commented
@viglesiasce @prydonius @krancour I would like to propose that we reopen the discussion on moving this to the incubator. Based on my testing last night I found several things that didn't work and associated open issues on the Traefik repo. By putting this chart into stable may give the impression that it's ready for primetime. 

To sum up my thoughts here. The chart is stable, the application is still maturing.

2016-11-02 17:00 UTC, lachie83 requested changes
Can we add a disclaimer on the current state of Traefik and it's prod readiness?

2016-11-02 17:00 UTC, lachie83 commented on stable/traefik/README.md
>  Let's Encrypt.
Can you a disclaimer about the state of Traefik?

2016-11-02 17:00 UTC, lachie83 commented on stable/traefik/README.md
>  This chart bootstraps Traefik as a Kubernetes ingress controller with optional support for SSL and
Looks great! Thanks for the updates!

2016-11-02 17:00 UTC, lachie83 reviewed
NOTES.txt looks much better! Thanks

2016-11-02 17:00 UTC, krancour commented on stable/traefik/README.md
>  Let's Encrypt.
Yep. Meant to, as we'd discussed. Forgot. Coming atcha.

2016-11-02 17:02 UTC, prydonius commented
@lachie83 @viglesiasce @krancour 
> By putting this chart into stable may give the impression that it's ready for primetime.

Agreed, if the project itself is not production-ready then the package should be in incubator.

2016-11-02 17:05 UTC, lachie83 commented on stable/traefik/README.md
> +__DISCLAIMER:__ While this chart has been well-tested, testers have encountered occasional issues
Thanks @krancour

2016-11-02 17:06 UTC, lachie83 approved these changes

2016-11-02 17:08 UTC, krancour commented
To clarify, I believe Traefik regards itself as production ready and people certainly _do_ use Traefik in production. Any assertion about production readiness here is purely based on @lachie83's and my own hesitation to endorse this as such.

2016-11-02 17:09 UTC, krancour commented
So I'm going to move this to incubator. Standby.

2016-11-02 17:11 UTC, krancour commented
Moved

2016-11-02 17:11 UTC, lachie83 commented
> To clarify, I believe Traefik regards itself as production ready and people certainly do use Traefik in production. Any assertion about production readiness here is purely based on @lachie83's and my own hesitation to endorse this as such.

Agreed 👍

2016-11-02 17:11 UTC, viglesiasce commented
I dont know about that folks. Where is this production ready requirement coming from for stable? Its not listed anywhere and the other requirements are quite explicit. I don't want us to cross this line.

2016-11-02 17:13 UTC, krancour commented
So if the chart's own author(s) would hesitate to use it in production (depending on the use case), this can still qualify as "stable?"

2016-11-02 17:15 UTC, krancour commented
Maybe some clarification on what, precisely, is meant by "stable" is in order. I will acknowledge I made a pretty big (and perhaps incorrect) assumption that stability was equated with production readiness.

2016-11-02 17:18 UTC, lachie83 commented
> I dont know about that folks. Where is this production ready requirement coming from for stable? Its not listed anywhere and the other requirements are quite explicit. I don't want us to cross this line.

Understood and I agree that it's not our position to decide whether something is production ready. I don't want to cross that line. Stable does not mean Prod Ready

How about we approach this from a difference angle - putting this in the incubator is a great way for it to gather some miles

2016-11-02 17:18 UTC, viglesiasce commented
Stable chart meet [these requirements](https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#how-to-contribute-a-chart).

If we cross the line of requiring things to be production ready then we need to define production ready in a way that is obvious otherwise we are going to end up with a lot of bikeshedding. For most packages (rpm and deb) the defaults are sane but not production ready.

2016-11-02 17:22 UTC, krancour commented
> How about we approach this from a difference angle - putting this in the incubator is a great way for it to gather some miles

@viglesiasce is there any validity to that notion? That things are "promoted" so stable after proving themselves in the incubator?

2016-11-02 17:27 UTC, viglesiasce commented
The only thing we say in the [README.md](https://github.com/kubernetes/charts#repository-structure) is that stable charts meet the criteria in the [technical requirements](https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#how-to-contribute-a-chart). If we want to change that policy then we need to update the documentation via a PR where we can hash out the why and how.

2016-11-02 17:28 UTC, krancour commented
Ok. I'm going to strike the last commit (the move to incubator) from this PR.

2016-11-02 17:29 UTC, lachie83 commented
Thanks for the great discussion and clarification. 

Given that this chart meets the requirements. My vote is on putting this in stable.

2016-11-02 17:29 UTC, krancour commented
All set. Back in stable.

2016-11-02 17:30 UTC, prydonius commented
@viglesiasce you're right, for some reason I thought some level of 'production-readiness' was a requirement. I would argue for promoting the stable repo as a source of 'production-ready' charts, but it's a separate discussion to define what we could mean by that and whether it makes sense to enforce it.

2016-11-02 17:35 UTC, lachie83 commented
LGTM

2016-11-02 17:39 UTC, viglesiasce commented
LGTM

2016-11-02 18:05 UTC, prydonius commented
@krancour lgtm, all good to merge?

2016-11-02 18:28 UTC, krancour commented
Yes

2016-11-02 18:32 UTC, merged

2016-11-02 18:32 UTC, lachie83 commented
Thanks all! Excited to have this chart!