Add PostgreSQL chart.
helm/charts pull request #147
Opened 2016-10-24 21:29 UTC by swordbeta

2016-10-24 21:41 UTC, prydonius commented
@k8s-bot ok to test

2016-10-24 22:53 UTC, prydonius commented on stable/postgresql/templates/NOTES.txt
> +   kubectl run {{ template "fullname" . }}-client --rm --tty -i --image postgres --command -- psql -h {{ template "fullname" . }} {{- if .Values.postgresUser }} -U{{ .Values.postgresUser }}{{ else }}
I can't seem to enter the password using this command. Perhaps you can provide it using an ENV var like the patroni chart does: https://github.com/kubernetes/charts/blob/master/incubator/patroni/templates/NOTES.txt#L17

2016-10-24 22:56 UTC, prydonius commented
@swordbeta thanks! I'm getting a CrashLoopBackOff error with the following logs:
```
initdb: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
It contains a lost+found directory, perhaps due to it being a mount point.
Using a mount point directly as the data directory is not recommended.
Create a subdirectory under the mount point.
```

2016-10-25 00:25 UTC, chrislovecnm requested changes
Looks great, just a couple of comments. You an emacs user?

2016-10-25 00:25 UTC, chrislovecnm commented on stable/postgresql/templates/deployment.yaml
> +        livenessProbe:
Readyprove?

2016-10-25 00:25 UTC, chrislovecnm commented on stable/postgresql/README.md
> +- PV provisioner support in the underlying infrastructure
If you do an empty doe do you need a PV provisioner? Maybe change the language for that. Local dev I could run on minikube with emptydir

2016-10-25 00:26 UTC, chrislovecnm commented on stable/postgresql/templates/deployment.yaml
> +        livenessProbe:
readyprobe ... Frigin autocomplete on mobile

2016-10-25 02:03 UTC, viglesiasce commented
@swordbeta This is what I did in the mysql chart for the lost+found issue:
https://github.com/kubernetes/charts/blob/master/stable/mysql/templates/deployment.yaml#L16

2016-10-25 08:32 UTC, swordbeta commented on stable/postgresql/templates/NOTES.txt
> +   kubectl run {{ template "fullname" . }}-client --rm --tty -i --image postgres --command -- psql -h {{ template "fullname" . }} {{- if .Values.postgresUser }} -U{{ .Values.postgresUser }}{{ else }}
@prydonius You can it's just really unclear: (I pressed enter and entered no password)

```
Waiting for pod default/ok-postgresql-client-2287579111-zo7qi to be running, status is Pending, pod ready: false
If you don't see a command prompt, try pressing enter.

psql: fe_sendauth: no password supplied
```

Changed it to patroni's style.

2016-10-25 08:33 UTC, swordbeta commented on stable/postgresql/templates/deployment.yaml
> +        livenessProbe:
@chrislovecnm The `readinessProbe` is a few lines below this one!

And I don't use emacs, what makes you think that haha?

2016-10-25 08:35 UTC, swordbeta commented on stable/postgresql/README.md
> +- PV provisioner support in the underlying infrastructure
@chrislovecnm I copied this from one of the stable READMEs (actually all of them say this). Changed it nevertheless.

2016-10-25 08:51 UTC, swordbeta commented
@prydonius I haven't been able to reproduce the `lost+found` issue, but I have added an init container like @viglesiasce suggested which deletes it. Can you let me know if it works?

@viglesiasce The `mysql` annotation uses `pod.alpha.kubernetes.io/init-containers`, shouldn't alpha features be omitted from the stable graphs?

2016-10-26 04:04 UTC, chrislovecnm approved these changes
LGTM

2016-10-26 04:04 UTC, chrislovecnm commented on stable/postgresql/templates/deployment.yaml
> +        livenessProbe:
Missed a EOF on one of the file

2016-10-26 04:04 UTC, chrislovecnm commented on stable/postgresql/templates/deployment.yaml
> +        livenessProbe:
Thanks ... Missed thay

2016-10-26 04:04 UTC, chrislovecnm commented on stable/postgresql/templates/deployment.yaml
> +        livenessProbe:
So they have changed edit on these. My engrish is sucking tonight. So there was an EOF marker that was missed on on of the files. One of my co-workers gets that with emacs all the time.


Missed your probes, you rock!

2016-10-26 04:06 UTC, chrislovecnm commented
@swordbeta it depends on the version of k8s you are running. Those should be vars to allow for easy upgrade. Another topic that we need to talk about.

2016-10-26 05:01 UTC, viglesiasce commented
@swordbeta @chrislovecnm the feature is now in beta and the annotation as listed continues to work. We should look to update these across the board soon but it is not currently necessary.

2016-10-26 05:29 UTC, chrislovecnm commented
I have an issue open Vic

2016-10-31 16:29 UTC, merged