[WORDPRESS] Add option to use HTTPS for readiness and liveliness
helm/charts pull request #1475
Opened 2017-07-12 09:17 UTC by bcorijn

The healthchecks are hardcoded to use the http port, which prevents users from setting up Wordpress to serve over https. If you change your wp_config to serve over https, the readiness and liveliness check fail and the container gets into a crashloop backoff.
This PR adds a simple flag to move these checks to https + removes a secret value that was unused.

2017-07-21 21:55 UTC, viglesiasce requested changes

2017-07-21 21:55 UTC, viglesiasce commented on stable/wordpress/templates/secrets.yaml
> -  {{ if .Values.databasePassword }}
Was this removed by mistake?

2017-07-26 08:47 UTC, sameersbn approved these changes
IMO health checks should be performed over plain HTTP. The option does make sense when wordpress is configured to enforce https though :+1:

2017-07-26 08:47 UTC, sameersbn commented on stable/wordpress/templates/secrets.yaml
> -  {{ if .Values.databasePassword }}
@viglesiasce it appears the `databasePassword` field is not used. Looks like it may have been added by mistake. Makes sense to have it removed.

2017-07-26 08:47 UTC, sameersbn commented
/ok-to-test

2017-07-26 08:48 UTC, bcorijn commented on stable/wordpress/templates/secrets.yaml
> -  {{ if .Values.databasePassword }}
Indeed. This secret is not used anywhere, the password is pulled from the MariaDB subchart. Having a password secret around that is not used is just confusing to the user imo.

2017-08-10 05:23 UTC, viglesiasce approved these changes

2017-08-10 05:26 UTC, viglesiasce commented
/ok-to-test

2017-08-10 05:31 UTC, merged