Initial version of NATS
helm/charts pull request #1483
Opened 2017-07-13 15:48 UTC by gabrtv

This PR adds a NATS chart that uses StatefulSet to provide clustering support.  Besides general testing, I see at least two things that must to be improved before this chart can graduate to stable:

1. **Use a blessed NATS Docker image** - Due to the `StatefulSet` patterns for registering nodes in quorum-based systems, we need shell interpolation support in the Docker image.  Unfortunately, the current NATS Docker image is built `FROM scratch` without a shell.  I will discuss adding shell interpolation support with the NATS folks, so I can remove my personal image as the default.
2. **Add Authorization support** - NATS supports [authorization](http://nats.io/documentation/server/gnatsd-authorization/) for the client and cluster ports. Writing a configuration file via a template appears to be the best approach.  This should be added ASAP.

That said, this chart works well for me as-is, so PR'ing it now.

2017-07-13 16:01 UTC, gabrtv commented
Bump for CLA

2017-07-13 16:04 UTC, gabrtv commented
Bump to verify CLA.

2017-07-13 16:59 UTC, unguiculus requested changes
Thanks for the PR. Please make sure you apply best practices, especially standard labels.

See https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md

If you create a new chart with `helm create` and at least Helm 2.5.0 you'll get an initial experience with correct labels and selectors.

2017-07-21 21:27 UTC, unguiculus commented
Any chance you get your CLA cleared and continue with this?

2017-07-28 05:38 UTC, unguiculus commented
Ping @gabrtv

2017-07-28 15:14 UTC, gabrtv commented
I filed a ticket with the LF to work through the CLA issue.  I'll keep this issue updated.

2017-07-29 15:19 UTC, unguiculus requested changes
Please apply best practices, especially standard labels. 

https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

If you create a new chart with `helm create` and Helm 2.5+, you'll get correct labels. You may also look at this example: 

https://github.com/kubernetes/helm/tree/master/docs/examples/nginxPlease apply best practices, especially standard labels.

2017-08-13 12:27 UTC, unguiculus commented
Marking this as stale. Please update within one week.

2017-08-21 17:12 UTC, unguiculus commented
Closing this as stale. Feel free to reopen if/when you decide to work on this again.

2017-08-21 17:12 UTC, closed without merging