Added check-mk chart to incubator
helm/charts pull request #1486
Opened 2017-07-14 09:01 UTC by junaid18183

Added a check-mk ( monitoring tool on top of Nagios ) chart to incubator

2017-07-21 21:30 UTC, unguiculus requested changes
Thanks for the PR.

2017-07-21 21:30 UTC, unguiculus commented on incubator/check-mk/Chart.yaml
> +  name: Juned Memon
Use Github username.

2017-07-21 21:30 UTC, unguiculus commented
/ok-to-test

2017-07-24 06:51 UTC, junaid18183 commented on incubator/check-mk/Chart.yaml
> +  name: Juned Memon
Thanks , updated the name with git username

2017-07-24 07:02 UTC, junaid18183 commented
have updated the name with git username

2017-07-29 15:46 UTC, unguiculus approved these changes

2017-08-13 17:00 UTC, merged