[stable/concourse] properly cleanup btrfs subvolume and children
helm/charts pull request #14941
Opened 2019-06-20 14:58 UTC by cirocosta

#### What this PR does / why we need it:

This PR is a follow up to https://github.com/helm/charts/pull/12398, having the `git rebase` already done.

More information about why it's needed can be found in the PR I mentioned above, but  the `tl;dr` is that a straight `rm -rf` doesn't work when what's there to be deleted is BTRFS subvolumes (rather than a plain sparse file - used when we don't have a "real" btrfs partition to use).

#### Which issue this PR fixes

  - fixes #13284

#### Special notes for your reviewer:

Please do not merge yet - I'll re-run the end-to-end tests that Concourse has first to ensure that we'll not be caught up with surprises 👍  

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-06-20 15:01 UTC, cirocosta commented
/retest

2019-06-20 15:23 UTC, cirocosta commented
/hold

2019-06-20 15:37 UTC, cirocosta commented
/hold cancel

2019-06-20 15:38 UTC, cirocosta commented
cc @william-tran @YoussB 

Tests are working good (including the one that uses a real BTRFS partition: <>)

<details>
<summary>Test Results (click to expand)</summary>
<pre>
Running in parallel across 6 nodes

• [SLOW TEST:67.214 seconds]
Kubernetes credential management
/Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:14
  /api/v1/info/creds
  /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:42
    Contains kubernetes config
    /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:55
------------------------------
• [SLOW TEST:72.638 seconds]
Container Limits
/Users/cirocosta/workspace/concourse/topgun/k8s/container_limits_test.go:14
  using Ubuntu as NodeImage
  /Users/cirocosta/workspace/concourse/topgun/k8s/container_limits_test.go:76
    fails to set the memory limit
    /Users/cirocosta/workspace/concourse/topgun/k8s/container_limits_test.go:81
------------------------------
• [SLOW TEST:92.704 seconds]
Container Limits
/Users/cirocosta/workspace/concourse/topgun/k8s/container_limits_test.go:14
  using cos as NodeImage
  /Users/cirocosta/workspace/concourse/topgun/k8s/container_limits_test.go:53
    returns the configure default container limit
    /Users/cirocosta/workspace/concourse/topgun/k8s/container_limits_test.go:58
------------------------------
• [SLOW TEST:107.001 seconds]
Kubernetes credential management
/Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:14
  Consuming k8s credentials
  /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:71
    using per-team credentials
    /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:90
      using a user-provided namespace
      /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:112
        succeeds
        /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:115
------------------------------
• [SLOW TEST:107.224 seconds]
Kubernetes credential management
/Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:14
  Consuming k8s credentials
  /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:71
    using per-team credentials
    /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:90
      using the default namespace created by the chart
      /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:94
        succeeds
        /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:99
------------------------------
• [SLOW TEST:123.685 seconds]
Kubernetes credential management
/Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:14
  Consuming k8s credentials
  /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:71
    using per-team credentials
    /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:90
      with caching enabled
      /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:104
        gets cached credentials
        /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:107
------------------------------
• [SLOW TEST:68.536 seconds]
Kubernetes credential management
/Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:14
  one-off build
  /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:162
    one-off build fails
    /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:176
------------------------------
• [SLOW TEST:112.959 seconds]
Kubernetes credential management
/Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:14
  Consuming k8s credentials
  /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:71
    using per-pipeline credentials
    /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:126
      using the default namespace created by the chart
      /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:130
        succeeds
        /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:135
------------------------------
• [SLOW TEST:107.184 seconds]
Kubernetes credential management
/Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:14
  Consuming k8s credentials
  /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:71
    using per-pipeline credentials
    /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:126
      using a user-provided namespace
      /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:148
        succeeds
        /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:151
------------------------------
• [SLOW TEST:141.290 seconds]
Kubernetes credential management
/Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:14
  Consuming k8s credentials
  /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:71
    using per-pipeline credentials
    /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:126
      with caching enabled
      /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:140
        gets cached credentials
        /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:143
------------------------------
• [SLOW TEST:108.201 seconds]
Kubernetes credential management
/Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:14
  one-off build
  /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:162
    runs the one-off build successfully
    /Users/cirocosta/workspace/concourse/topgun/k8s/kubernetes_creds_mgmt_test.go:167
------------------------------
••
------------------------------
• [SLOW TEST:95.477 seconds]
Worker Rebalancing
/Users/cirocosta/workspace/concourse/topgun/k8s/rebalance_test.go:14
  eventually has worker connecting to each web nodes over a period of time
  /Users/cirocosta/workspace/concourse/topgun/k8s/rebalance_test.go:49
------------------------------
• [SLOW TEST:67.335 seconds]
Web HTTP or HTTPS(TLS) termination at web node
/Users/cirocosta/workspace/concourse/topgun/k8s/https_web_tls_termination_test.go:17
  When configured correctly
  /Users/cirocosta/workspace/concourse/topgun/k8s/https_web_tls_termination_test.go:46
    configure helm chart for tls termination at web
    /Users/cirocosta/workspace/concourse/topgun/k8s/https_web_tls_termination_test.go:70
      fly login fails when NOT using the correct CA
      /Users/cirocosta/workspace/concourse/topgun/k8s/https_web_tls_termination_test.go:90
------------------------------
• [SLOW TEST:72.523 seconds]
Web HTTP or HTTPS(TLS) termination at web node
/Users/cirocosta/workspace/concourse/topgun/k8s/https_web_tls_termination_test.go:17
  When configured correctly
  /Users/cirocosta/workspace/concourse/topgun/k8s/https_web_tls_termination_test.go:46
    configure helm chart for tls termination at web
    /Users/cirocosta/workspace/concourse/topgun/k8s/https_web_tls_termination_test.go:70
      fly login succeeds when using the correct CA and host
      /Users/cirocosta/workspace/concourse/topgun/k8s/https_web_tls_termination_test.go:83
------------------------------
• [SLOW TEST:38.771 seconds]
External PostgreSQL
/Users/cirocosta/workspace/concourse/topgun/k8s/external_postgres_test.go:11
  can have pipelines set
  /Users/cirocosta/workspace/concourse/topgun/k8s/external_postgres_test.go:56
------------------------------
• [SLOW TEST:40.841 seconds]
Baggageclaim Drivers
/Users/cirocosta/workspace/concourse/topgun/k8s/baggageclaim_drivers_test.go:14
  across different node images
  /Users/cirocosta/go/pkg/mod/github.com/onsi/g [...]

2019-06-21 14:05 UTC, YoussB commented
@cirocosta Will you please rebase the `Chart.yml`?

2019-06-21 14:06 UTC, YoussB requested changes
@cirocosta Will you please rebase the `Chart.yml`?

2019-06-21 14:21 UTC, cirocosta commented
done @YoussB  😁

2019-06-21 19:29 UTC, smoke approved these changes

2019-06-21 19:37 UTC, YoussB commented
Hey, 
although this didn't affect the running of the deployment, the `initContainer` fails when using a filesystem other than `btrfs`. that is because the directory is not of `btrfs` filesystem type.
```
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 21 Jun 2019 15:20:15 -0400
      Finished:     Fri, 21 Jun 2019 15:20:15 -0400
```
when running `kubectl logs` for the `initContainer` I got the following:\
```
ERROR: not a btrfs filesystem: /concourse-work-dir
ERROR: can't access '/concourse-work-dir'
```

- while this can be ignored, since the deployment doesn't fail, I think wrapping the loop with a condition of using `btrfs` will be useful.

wdyt @cirocosta ?

2019-06-21 19:43 UTC, cirocosta commented
Oh, that's quite surprising, I wonder if I ran the tests against the wrong branch 🤔  

As we have the suite that goes over all of the supported drivers (https://github.com/concourse/concourse/blob/fedde4ee68fb03faeb5360ca78a64c2d12a7451b/topgun/k8s/baggageclaim_drivers_test.go#L66-L94), I thought it'd be good 🤔 

let me double check this one 👍

2019-06-21 19:52 UTC, cirocosta commented
>   while this can be ignored, since the deployment doesn't fail, I think wrapping the loop with a condition of using btrfs will be useful.

I think the hard part of this is the `detect` driver 😬  (which I'm even proposing to be the default: https://github.com/helm/charts/issues/14033)

In that case, matching for `btrfs` wouldn't work well hmmmm

Wdyt?

2019-06-21 20:10 UTC, YoussB commented
hmmm 🤔 , makes sense, not sure if this could still cause problems on other IAASes though 🤔

2019-06-22 06:21 UTC, smoke commented
There is nothing stopping people to switch from btrfs to other driver, so the workdir should well be cleaned in these cases as well.
This is why I suggest to somehow ignore the message / error and let it run regardless of the driver.

2019-06-22 06:45 UTC, smoke requested changes
I would suggest the following changes to gracefully continue in case the volume is not btrfs, still showing as error the fact of it.
Here is how it will workout
```
rkirilov-work-pc /home/smoke # (btrfs subvolume list /boot || true) | awk '{print $9}'
ERROR: not a btrfs filesystem: /boot
ERROR: can't access '/boot'
rkirilov-work-pc /home/smoke # echo $?
0
```

2019-06-22 06:45 UTC, smoke commented on stable/concourse/templates/worker-statefulset.yaml
> +              for v in $(btrfs subvolume list --sort=-ogen {{ .Values.concourse.worker.workDir }} | awk '{print $9}'); do
```suggestion
              for v in $((btrfs subvolume list --sort=-ogen "{{ .Values.concourse.worker.workDir }}" || true) | awk '{print $9}'); do
```

2019-06-22 06:45 UTC, smoke commented on stable/concourse/templates/worker-statefulset.yaml
> +                btrfs subvolume delete {{ .Values.concourse.worker.workDir }}/$v
```suggestion
                btrfs subvolume delete "{{ .Values.concourse.worker.workDir }}/$v"
```

2019-06-24 12:50 UTC, YoussB commented
@smoke, looks good 👍 
@cirocosta ?

2019-06-24 14:56 UTC, cirocosta commented
SGTM!

I think it's good even without the `||` just because we're not using `set -o pipefail`, so a failure there in `btrfs` will not make it stop with an error anyway (the reason why all of our tests pass regardless 😁 )

Thanks!

2019-06-24 15:04 UTC, smoke commented
by the way because it uses `/bin/sh` the `|| true` does not work - I am working about it in this very moment

2019-06-24 15:08 UTC, smoke commented
Alright ... I am not sure how to do this the best way - so I have filled a PR against your branch :) 
https://github.com/concourse/charts/pull/2

2019-06-24 15:10 UTC, smoke requested changes
Here is a working set of suggestions - same as https://github.com/concourse/charts/pull/2

2019-06-24 15:10 UTC, smoke commented on stable/concourse/templates/worker-statefulset.yaml
>              - /bin/sh
```suggestion
            - /bin/bash
```

2019-06-24 15:10 UTC, smoke commented on stable/concourse/templates/worker-statefulset.yaml
>                rm -rf {{ .Values.concourse.worker.workDir }}/*
```suggestion
               rm -rf "{{ .Values.concourse.worker.workDir }}/*"
```

2019-06-28 05:57 UTC, smoke commented
@cirocosta @YoussB I can confirm with the latest patch https://github.com/concourse/charts/pull/2 all is working flawlessly on my side.
Please let me know if I can help with something more.

2019-07-04 21:09 UTC, cirocosta commented
tests just passed @YoussB 😁

2019-07-05 02:17 UTC, YoussB approved these changes

2019-07-05 02:17 UTC, YoussB commented
/lgtm

2019-07-05 02:19 UTC, YoussB commented
thanks @smoke @cirocosta and @taylorsilva

2019-07-05 02:26 UTC, merged