[stable/atlantis] Added support for existing GCP Service Account Secret
helm/charts pull request #14962
Opened 2019-06-21 12:21 UTC by jonnydford

#### What this PR does / why we need it:
Adds support for existing GPC Service Account to use with Atlantis, set `GOOGLE_APPLICATION_CREDENTIALS` to file path of this account. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-06-24 20:44 UTC, anubhavmishra commented
/cc @lkysow.

2019-06-24 20:45 UTC, anubhavmishra commented
/cc @lkysow

2019-06-25 12:57 UTC, lkysow requested changes

2019-06-25 12:57 UTC, lkysow commented on stable/atlantis/Chart.yaml
> +version: 3.5.4
```suggestion
version: 3.6.0
```
Since it's new functionality it should be a minor release

2019-06-25 19:51 UTC, lkysow commented
/lgtm

2019-06-25 20:00 UTC, jonnydford commented
/retest

2019-06-25 22:28 UTC, lkysow commented
/ok-to-test

2019-06-25 22:28 UTC, lkysow commented
/retest

2019-07-26 11:57 UTC, lkysow commented
@jonnydford I think you need to update the chart.yaml because another PR bumped the version

2019-08-13 07:17 UTC, maorfr commented
need to signoff that commit

2019-09-26 08:35 UTC, closed without merging