[stable/external-dns] fix issue 15002
helm/charts pull request #15013
Opened 2019-06-24 12:31 UTC by SantoDE

#### What this PR does / why we need it:

#### Which issue this PR fixes
  - fixes 15002

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-06-24 12:32 UTC, SantoDE commented
/assign @cpanato

2019-06-24 12:48 UTC, chrisz100 commented
Issue is fixed with this patch, thanks!

2019-06-24 18:01 UTC, juan131 requested changes
Thanks so much for your PR, could you please take a look to my suggestions?

2019-06-24 18:01 UTC, juan131 commented on stable/external-dns/Chart.yaml
> +version: 1.8.1
Could you please rebase from master and bump the patch version again?

2019-06-24 18:01 UTC, juan131 commented on stable/external-dns/README.md
> +| `crd.create`                       | If true, create CRD ressource
The default value is `false`

2019-06-25 06:30 UTC, SantoDE commented
Hey @juan131,

all done. Thanks for the feedback! :)

2019-06-25 14:23 UTC, juan131 approved these changes
Thanks for addressing the changes! Approving them

2019-06-25 14:23 UTC, juan131 commented
/ok-to-test
/lgtm

2019-06-25 14:30 UTC, merged