stable/concourse: Improve documentation awsSecretsManager template
helm/charts pull request #15038
Opened 2019-06-25 10:03 UTC by shyamz-22

Provide `correct` default template for pipeline and team for awsSecretsManager

Signed-off-by: Syamala Umamaheswaran <shykart2203@gmail.com>

#### What this PR does / why we need it:
### What
This PR updates `correct` default template for pipeline and team for awsSecretsManager. 
### Why
When we use the example template [`/concourse/{team}/{pipeline}/{secret}`], the concourse task fails with the following error:

`Invalid name. Must be a valid name containing alphanumeric characters, or any of the following: -/_+=.@!`

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-06-25 10:11 UTC, shyamz-22 commented
/assign @cirocosta. This is my first PR with charts. Can you help me with the linting error?

2019-06-25 12:26 UTC, YoussB commented
@shyamz-22, you need to bump the chart version here: 
https://github.com/helm/charts/blob/6ee98b392c12e31fe319265ab54dce484007f21d/stable/concourse/Chart.yaml#L3


Also, we are using the way we wrote these in a way to show that it uses the team name and not the word `{team}` or pipeline and so on, Do you think that this way is going to make things more clear for whoever reads the values file?

If so, can you also change the ones here: 
https://github.com/helm/charts/blob/6ee98b392c12e31fe319265ab54dce484007f21d/stable/concourse/values.yaml#L355-L361

2019-06-25 13:14 UTC, shyamz-22 commented
@YoussB Thank you for the reply. 

My motivation behind this change was wanted to have a different template value like `/concourse/a-unique-id/{team}/{pipeline}/{secret}`. We used exactly this value because of  the word choice `defaults to:` in the comment thinking that the default template value had this format.

Do you think it is a good idea to reword from `defaults to:`  to ` default template value:` to be more clear?

```    awsSecretsManager:

      ## pipeline-specific template for Secrets Manager parameters, default template value: /concourse/{{.Team}}/{{.Pipeline}}/{{.Secret}}
      ##
      pipelineSecretTemplate: 
```

2019-06-25 17:15 UTC, YoussB commented
oh, I see. this makes sense!

2019-06-25 17:16 UTC, YoussB commented
/ok-to-test

2019-06-28 11:04 UTC, shyamz-22 commented
@YoussB I have couple more improvements to the documentation, do you think it makes sense to do it in the same PR or create a new one? Thanks :)

2019-06-28 13:17 UTC, YoussB commented
@shyamz-22 Let's create a new one, so it won't get stuck on review, I will merge this one in 🥇

2019-06-28 13:20 UTC, cirocosta commented
/retest

2019-06-28 13:24 UTC, YoussB commented
/lgtm

2019-06-28 13:29 UTC, YoussB commented
/retest

2019-06-28 16:31 UTC, YoussB requested changes

2019-06-28 16:31 UTC, YoussB commented on stable/concourse/Chart.yaml
> -version: 7.0.0
@shyamz-22 you'll need to bump the version again.

2019-06-28 18:41 UTC, YoussB commented
@shyamz-22 there is something weird `pull-charts-e2e` probably because your branch wasn't rebased, do you mind rebasing your branch on top of master.

2019-06-28 18:58 UTC, shyamz-22 commented
@YoussB Thanks for the hint. Should be fine now.

2019-06-28 20:02 UTC, YoussB commented
/lgtm

2019-06-28 20:33 UTC, YoussB commented
/retest

2019-06-28 20:56 UTC, shyamz-22 commented
synced with upstream again, cannot understand why tests keep failing

2019-06-28 21:07 UTC, YoussB commented
for some reason, it is not able to deploy the chart, idk why 🤷‍♂

2019-06-28 21:08 UTC, YoussB commented
although it did work before!!

2019-06-28 21:13 UTC, YoussB commented
looks like the test environment used by prow is having problems:
```
I0628 20:46:18.534]   Warning  FailedScheduling   54s (x14 over 10m)      default-scheduler   pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
```

2019-07-02 18:34 UTC, YoussB commented
/retest

2019-07-02 19:06 UTC, YoussB commented
/lgtm

2019-07-02 19:16 UTC, merged