[stable/nats] Adapt chart to NATS version 2
helm/charts pull request #15037
Opened 2019-06-25 10:00 UTC by tompizmor

#### What this PR does / why we need it:
In NATS v2 the main server binary has been renamed from `gnastd` to `nats-server`. This PR makes the necessary changes.

#### Special notes for your reviewer:
Don't merge yet.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-06-25 10:00 UTC, tompizmor commented
/hold

2019-06-25 14:04 UTC, tompizmor commented
/hold cancel

2019-06-25 19:06 UTC, javsalgar commented
I see that the changes to make it work with the new version or nats are mininal. Could we parametrize the config file name and the command so it is compatible with the previous version of nats?

2019-06-26 10:59 UTC, tompizmor commented
@javsalgar I implemented the requested change. Please take a look when you have a chance

2019-06-26 16:15 UTC, javsalgar requested changes

2019-06-26 16:15 UTC, javsalgar commented on stable/nats/templates/deployment.yaml
> +            mountPath: /opt/bitnami/nats/nats-server.conf
We need to change this as well, right?

2019-06-27 08:14 UTC, tompizmor commented on stable/nats/templates/deployment.yaml
> +            mountPath: /opt/bitnami/nats/nats-server.conf
ups...done

2019-06-28 09:16 UTC, carrodher commented
I would add the comment related to the new version:
```
## Nats filenames:
##  - For Nats 1.x.x version, some filenames (binary, configuration file, pid file) uses `gnatsd` as part of the name.
##  - For Nats 2.x.x version, those filenames now uses `nats-server`
## In order to make the chart compatible with NATS versions 1.0.0 and 2.0.0 we have parametrized the following value
## to specify the proper filename according to the image version.
##
```
in the README, the rest LGTM

2019-06-28 09:16 UTC, carrodher commented
/ok-to-test

2019-06-28 09:55 UTC, carrodher commented
/lgtm

2019-06-28 09:55 UTC, merged