[stable/redis] - Fix probes when network policy is enabled
helm/charts pull request #15062
Opened 2019-06-26 07:59 UTC by bbenzikry

#### What this PR does / why we need it:
When network policy is enabled, liveness and readiness probes fail with the password warning discussed in bitnami/bitnami-docker-redis#141 and antirez/redis#5073

```bash
helm install --namespace test --set networkPolicy.enabled=true --name test-redis stable/redis
```

```
Normal    Created                  Pod                     Created container
Normal    Started                  Pod                     Started container
Warning   Unhealthy                Pod                     Readiness probe failed:
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Killed
```
Additions: 
* ``--no-auth-warning`` flag at every usePassword block
```yaml
{{- if .Values.usePassword }}
        -a $REDIS_PASSWORD --no-auth-warning \
{{- end }}
```
* Slaves are labeled as clients as well
```diff
   template:
     metadata:
       labels:
+        {{- if not .Values.networkPolicy.allowExternal }}
+        {{ template "redis.fullname" . }}-client: "true"
+        {{- end }}
         release: "{{ .Release.Name }}"
         chart: {{ template "redis.chart" . }}
         role: slave
```

* Changes README to specify that allowExternal is not true by default

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-06-26 08:01 UTC, bbenzikry commented
/assign @juan131

2019-06-27 16:57 UTC, juan131 requested changes
Thanks for your contribution @bbenzikry !!
Could you please take a look to my comments?

2019-06-27 16:57 UTC, juan131 commented on stable/redis/README.md
> +| `networkPolicy.allowExternal`                 | Don't require client label for connections                                                                                                          |
The actual current values is `nil` since it's commented in the **values.yaml**

2019-06-27 16:57 UTC, juan131 commented on stable/redis/templates/redis-slave-statefulset.yaml
> +        {{- if not .Values.networkPolicy.allowExternal }}
I'd use:
```diff
- {{- if not .Values.networkPolicy.allowExternal }}
+ {{- if and .Values.networkPolicy.enabled (not .Values.networkPolicy.allowExternal) }}
```

2019-06-27 17:03 UTC, bbenzikry commented
Conflicts with #15082

2019-06-27 17:12 UTC, juan131 commented
You're right @bbenzikry, both solutions fix the same issue.

We can continue with the approach suggested at #15082 and add the auth flag as a seperate PR

2019-06-27 17:14 UTC, bbenzikry commented
Great, I'll open one soon

2019-06-27 17:14 UTC, closed without merging