[stable/airflow] Add readinessProbe
helm/charts pull request #15138
Opened 2019-06-29 08:51 UTC by khwj

Signed-off-by: Khwunchai Jaengsawang <khwunchai.j@ku.th>

#### What this PR does / why we need it:
This PR adds readinessProb to Airflow web deployment, this readiness prob is needed for some Ingress engine for health checking (e.g. with GCE ingress will not consider a backend is healthy since it’s keep querying `/` rather than `/health `).

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-06-29 09:02 UTC, khwj commented
/assign @gsemet

2019-06-29 15:38 UTC, gsemet approved these changes
Oh great, I didn’t noticed they added the /health endpoint

/lgtm

2019-06-29 16:06 UTC, khwj commented
/retest

2019-07-08 02:18 UTC, TomNeyland commented
@gsemet @khwj
Looks like this just needs a trusted user to kick off the retest?

2019-07-13 05:51 UTC, khwj commented
> @gsemet @khwj
> Looks like this just needs a trusted user to kick off the retest?

Think so, unfortunately I’m not a trusted user.

2019-07-13 09:39 UTC, gsemet commented on stable/airflow/requirements.lock
> +dependencies:
I don’t think you should add this file

2019-08-13 07:22 UTC, maorfr commented
/lgtm

2019-08-13 07:45 UTC, gsemet requested changes
/approve cancel

2019-08-13 07:45 UTC, gsemet commented on stable/airflow/requirements.lock
> +  repository: https://kubernetes-charts.storage.googleapis.com/
Please remove this file

2019-08-13 08:12 UTC, merged

2019-08-13 08:17 UTC, gsemet commented
Damned, I am pretty sure this should not have been merged