[incubator/couchdb] use seedlist to join cluster
helm/charts pull request #15167
Opened 2019-07-01 14:31 UTC by willholley

#### What this PR does / why we need it:

Uses the [seedlist] feature in CouchDB 2.3.1 to join the nodes in the cluster. This removes the requirement for the statefulset-assembler sidecar. The first node in the statefulset is always used as the seed.

One slight niggle is that CouchDB will assume the seedlist contains fully qualified domain names, which can't be determined by Helm at install time. 

To address this, a new config value, `dns.clusterDomainSuffix` is added, which defaults to `cluster.local`. For now, users will need to modify this when using a non-default
domain suffix.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-01 21:21 UTC, kocolosk requested changes
It will be great to get rid of the sidecar image. The seedlist implementation also has the nice property that it makes the readiness probe smarter; now a node won't be marked as ready until it actually has the full shard map replicated.

Do you think it's sufficient to only include the first cluster node in the seedlist? I'm worried about the case where someone might be running a cluster on local storage and the server hosting the first member of the StatefulSet dies. In that case the first member will be re-created elsewhere but will believe itself to be a standalone cluster and we'll have a permanent partition until an operator notices.

I don't know how to express this in the templating language but I would be happier with something like `max(clusterSize, 3)` as the number of entries in the seedlist.

2019-07-01 21:21 UTC, kocolosk commented on incubator/couchdb/templates/headless.yaml
> +{{ include "couchdb.ss.selector" . | indent 4 }}
Nice cleanup on the use of a template for the StatefulSet selector here and elsewhere.

2019-07-01 21:21 UTC, kocolosk commented on incubator/couchdb/templates/statefulset.yaml
>  {{- if not .Values.allowAdminParty }}
This is the proposed change from #15162, so that'll need to be cleaned up into separate commits once that other PR is finalized.

2019-07-02 08:34 UTC, willholley commented
@kocolosk I've updated the PR so that the seedlist is generated based on the number of replicas. I've also remove the duplicate of #15162 though this PR will either need rebasing on that or we just ignore it and as the bug it addresses goes away when we lose the statefulset assembler anyway.

2019-08-13 17:28 UTC, kocolosk approved these changes
This is a nice enhancement, I left one small comment about capping the size of the seedlist when deploying large clusters, otherwise I'm 👍

2019-08-13 17:28 UTC, kocolosk commented on incubator/couchdb/templates/_helpers.tpl
> +{{- $nodeCount := .Values.clusterSize | int }}
I'd suggest putting a cap on the size of the seedlist here, e.g. 

> {{- $nodeCount := min 5 .Values.clusterSize | int }}

2019-08-16 15:21 UTC, kocolosk commented
All my review comments have been addressed, the latest version looks great. Can we get an `/ok-to-test`?

2019-08-25 05:04 UTC, maorfr commented
/ok-to-test
/lgtm

2019-08-25 05:12 UTC, merged