[stable/fluent-bit] added config option to specific path on elastic output
helm/charts pull request #15201
Opened 2019-07-02 07:19 UTC by 27ascii

#### What this PR does / why we need it:
added config option to specific path on elastic output as defined in https://github.com/fluent/fluent-bit-docs/blob/master/output/elasticsearch.md

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-03 05:14 UTC, 27ascii commented
/assign @hectorj2f

2019-07-05 15:56 UTC, asherf commented
@27ascii the new param should be documented in the [readme](https://github.com/helm/charts/blob/master/stable/fluent-bit/README.md)

2019-08-05 17:49 UTC, hectorj2f reviewed
/ok-to-test

2019-08-05 17:49 UTC, hectorj2f requested changes

2019-08-05 17:49 UTC, hectorj2f commented on stable/fluent-bit/values.yaml
> +    # Optional: Path prefix for ElasticSearch
Yeah, let's document this new property

2019-09-05 06:00 UTC, closed without merging