[stable/prometheus-mongodb-exporter] Add Service object for ServiceMonitor to work properly
helm/charts pull request #15218
Opened 2019-07-02 18:31 UTC by decayofmind

#### What this PR does / why we need it:

This PR creates a Service object if serviceMonitor is enabled.
It's needed to provide exporter's Endpoints for ServiceMonitor, so prometheus-operator will get targets to scrap metrics from.

> For Prometheus to monitor any application within Kubernetes an Endpoints object needs to exist. Endpoints objects are essentially lists of IP addresses. Typically an Endpoints object is populated by a Service object. A Service object discovers Pods by a label selector and adds those to the Endpoints object.

(from https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md#servicemonitor)

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-02 18:32 UTC, decayofmind commented
/assign @steven-sheehy

2019-07-11 05:01 UTC, steven-sheehy requested changes
Ah, didn't realize ServiceMonitor requires a service. I think it's better to just undo the changes in https://github.com/helm/charts/pull/12796/files related to removing the service. That is copy the previous `service.yaml`, `tests/test-connection.yaml` and add back the service options to the `values.yaml` and README.

2019-07-15 17:19 UTC, marcosArruda commented
+1

2019-07-24 11:37 UTC, decayofmind commented
@steven-sheehy since `service.yaml` is pretty identical, I suggest to add back just `templates/tests/test-connection.yaml` and some parts of related documentation. Right to this PR.

Will it be OK?

2019-07-24 15:27 UTC, steven-sheehy commented
@decayofmind Sure, that will suffice. Thanks for taking this on.

2019-07-30 18:17 UTC, steven-sheehy commented
/ok-to-test

2019-07-30 18:32 UTC, steven-sheehy commented
/lgtm
Thanks @decayofmind !

2019-07-30 18:34 UTC, merged