[stable/zetcd] zetcd chart
helm/charts pull request #1529
Opened 2017-07-21 09:46 UTC by hunter

A chart that bootstraps zetcd with an optional etcd-operator cluster.

2017-07-21 16:32 UTC, unguiculus commented
/ok-to-test

2017-07-21 20:32 UTC, unguiculus requested changes
Thanks for the PR. Just a few things.

2017-07-21 20:32 UTC, unguiculus commented on stable/zetcd/Chart.yaml
> +  - https://github.com/coreos/zetcd
Please add maintainer. Use Github username.

2017-07-21 20:32 UTC, unguiculus commented on stable/zetcd/values.yaml
> +  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
I'd rather not add defaults here.

2017-07-22 03:20 UTC, hunter commented on stable/zetcd/values.yaml
> +  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
Agreed. I'd forgotten to comment them back out after development. Now fixed.

2017-07-22 03:22 UTC, hunter commented on stable/zetcd/Chart.yaml
> +  - https://github.com/coreos/zetcd
Added in maintainers

2017-07-22 07:05 UTC, unguiculus commented on stable/zetcd/values.yaml
> +resources:
Add `{} ` again.

2017-07-24 02:30 UTC, hunter commented on stable/zetcd/values.yaml
> +resources:
Apologies. Overlooked it :|

2017-07-25 19:26 UTC, unguiculus requested changes
Almost there ;)

2017-07-25 19:26 UTC, unguiculus commented on stable/zetcd/README.md
> +| `resources.limits.memory`                         | Memory limit per zetcd pod                                   | `128Mi`                                        |
Remove the defaults for resources.

2017-07-25 19:26 UTC, unguiculus commented on stable/zetcd/templates/_helpers.tpl
> +{{- define "etcd-operator.fullname" -}}
This is not used. Why is it there?

2017-07-26 05:19 UTC, hunter commented on stable/zetcd/README.md
> +| `resources.limits.memory`                         | Memory limit per zetcd pod                                   | `128Mi`                                        |
Done :)

2017-07-26 05:19 UTC, hunter commented on stable/zetcd/templates/_helpers.tpl
> +{{- define "etcd-operator.fullname" -}}
Removed as its no longer being used

2017-07-28 05:43 UTC, unguiculus commented
/ok-to-test

2017-07-28 06:07 UTC, unguiculus approved these changes

2017-07-28 06:08 UTC, merged