Add factorio chart to incubator.
helm/charts pull request #153
Opened 2016-10-25 04:03 UTC by gtaylor

This PR adds a chart for the increasingly popular [Factorio](https://www.factorio.com/), an indie game that has been doing well on Steam. 

This is my first chart, so feedback is especially sought!

2016-10-25 04:08 UTC, gtaylor commented
CNCF CLA signed!

2016-10-25 20:22 UTC, viglesiasce commented
@k8s-bot ok to test

2016-10-26 08:14 UTC, chrislovecnm requested changes
So the other tweaks you did on minecraft, yah want to do here?

2016-10-26 08:43 UTC, gtaylor commented
@chrislovecnm Done!

2016-10-26 08:49 UTC, chrislovecnm approved these changes
LGTM

2016-10-26 08:49 UTC, chrislovecnm commented
@k8s-bot ok to test

2016-10-26 08:51 UTC, gtaylor commented
I can squash + force this all desired prior to merge.

2016-10-26 08:53 UTC, chrislovecnm commented
Squash and @viglesiasce can give yah a thumbs up and merge

2016-10-26 08:54 UTC, gtaylor commented
Squashed

2016-10-27 07:26 UTC, chrislovecnm commented
@gtaylor your call!!

2016-10-27 21:30 UTC, prydonius commented on incubator/factorio/templates/NOTES.txt
> +Getting Started:
Can you remove this, it's made redundant since Helm will output `NOTES:` as the header before this.

2016-10-27 21:31 UTC, prydonius commented on incubator/factorio/README.md
> +Amazon's Elastic Loadbalancer lacks support for UDP. You'll need to set `factorioServer.ServiceType` to `NodePort` and expose the port that gets selected (see `kubectl describe svc <servicename>`) vi
Can we add a quick line about this in NOTES.txt, and point to this for more info?

2016-10-27 21:33 UTC, prydonius commented on incubator/factorio/templates/deployment.yaml
> +          {{ include "toYaml" .Values.resources | indent 10 }}
this should be

```
        resources:
{{ toYaml .Values.resources | indent 10 }}
```

With the built-in toYaml function, the first line gets indented so it needs to be un-indented in the template.

See https://github.com/kubernetes/charts/blob/master/stable/redis/templates/deployment.yaml#L44

2016-10-31 08:43 UTC, gtaylor commented
@prydonius Done, done, and done

2016-11-03 06:01 UTC, gtaylor commented
Rebased, too.

2016-11-03 19:04 UTC, viglesiasce commented
LGTM. Installed and was able to hit the open UDP port.

2016-11-03 20:25 UTC, prydonius commented on stable/factorio/README.md
> +Refer to `values.yaml` for the full run-down on defaults. These are a mixture of Kubernetes and Factorio-related directives that map to environment variables in [docker-factorio](https://github.com/g
Like in Minecraft, it would be good to link to the values.yaml file here.

2016-11-03 20:26 UTC, prydonius commented
One minor nitpick in the README, sorry I didn't catch it earlier. Otherwise LGTM! Thanks @gtaylor :)

2016-11-03 23:10 UTC, prydonius commented
I'm going to go ahead and merge this, and update the README in a separate PR!

2016-11-03 23:10 UTC, merged