[stable/cerebro] cerebro: iterate over .Values.env to set specific auth settings
helm/charts pull request #15351
Opened 2019-07-09 14:03 UTC by sebdoido

Currently, some auth settings from application.conf should be overwritter through env variables.
We can only set specific values from secret right now.

This PR allows to set some settings through env variables, and not only from secrets.

2019-07-09 14:11 UTC, sebdoido commented
/assign @davidkarlsen

2019-07-20 17:33 UTC, davidkarlsen requested changes

2019-07-20 17:33 UTC, davidkarlsen commented on stable/cerebro/README.md
> +| `env`                               | List with env vars (key/value   )   |                                           |
```suggestion
| `env`                               | Map of env vars (key/value   )   | `{}`                                          |
```

2019-07-21 12:21 UTC, sebdoido commented on stable/cerebro/README.md
> +| `env`                               | List with env vars (key/value   )   |                                           |
thanks for your review. I update the PR

2019-07-26 09:17 UTC, davidkarlsen approved these changes

2019-07-26 09:18 UTC, davidkarlsen commented
/ok-to-test

2019-07-26 09:54 UTC, davidkarlsen commented
/lgtm

2019-07-26 10:07 UTC, merged