[stable/drone] Add support for custom volumes in drone agent
helm/charts pull request #15380
Opened 2019-07-10 10:12 UTC by georgekaz

#### What this PR does / why we need it:
Adds support for custom volumes to drone agent, which allows for global docker login for pulls, and shared cache volumes when using dind or agents on multiple nodes.

#### Special notes for your reviewer:
see: Option 2 ref: https://discourse.drone.io/t/how-to-pull-private-images-with-1-0/3155
Also useful for other purposes.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-10 10:13 UTC, georgekaz commented
/assign @zakkg3

2019-07-15 10:21 UTC, zakkg3 requested changes

2019-07-15 10:21 UTC, zakkg3 commented on stable/drone/values.yaml
> +  ## Option 2 ref: https://discourse.drone.io/t/how-to-pull-private-images-with-1-0/3155
It may be good to add a more clear warning here that 'This will make the credentials available globally to all builds and all repositories.'

2019-07-15 10:21 UTC, zakkg3 commented on stable/drone/Chart.yaml
> +version: 2.0.5
You may need to bump the chart version one more time, as we want to merge https://github.com/helm/charts/pull/14965 asap, probabbly before,  as its a fixing bug thing. I will let you know.

/edit 
please bump chart version to 2.0.6

2019-07-23 15:21 UTC, zakkg3 commented on stable/drone/Chart.yaml
> +version: 2.0.5
now it needs to be -> 2.0.7
Are you mantining this PR ?

2019-07-23 19:55 UTC, georgekaz commented on stable/drone/Chart.yaml
> +version: 2.0.5
I will but currently am on holiday and with very little internet. I'm happy for someone to make the edits, or I'll do them when I return on 31st. Thanks

2019-07-31 12:58 UTC, georgekaz commented on stable/drone/values.yaml
> +  ## Option 2 ref: https://discourse.drone.io/t/how-to-pull-private-images-with-1-0/3155
I added this note, although this is a specific warning for a specific use case example that really should be understood before it's used, so i'm not sure it should be in the chart.

2019-07-31 12:59 UTC, georgekaz commented on stable/drone/Chart.yaml
> +version: 2.0.5
@zakkg3 that's changed now

2019-07-31 13:05 UTC, zakkg3 commented on stable/drone/Chart.yaml
> +version: 2.0.5
Welcome back @Georgekaz

2019-07-31 13:06 UTC, zakkg3 commented
/approved
/lgtm

2019-07-31 13:14 UTC, merged