[stable/datadog]
helm/charts pull request #15384
Opened 2019-07-10 12:35 UTC by denniswebb

Signed-off-by: Dennis Webb <dennis@bluesentryit.com>

#### What this PR does / why we need it:
Need the ability to add annotations to the cluster-agent pods, specifically for disabling Istio sidecar injection.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-10 15:37 UTC, denniswebb commented
/assign @clamoriniere

2019-07-10 20:19 UTC, clamoriniere commented
/ok-to-test

2019-07-10 21:53 UTC, davidkarlsen requested changes

2019-07-10 21:53 UTC, davidkarlsen commented on stable/datadog/values.yaml
> +  #   <POD_ANNOTATION>: '[{"key": "<KEY>", "value": "<VALUE>"}]'
```suggestion
  #   key: "value"
```

2019-07-15 08:58 UTC, clamoriniere approved these changes
/lgtm

2019-07-15 09:05 UTC, merged