[stable/grafana] Allow default TLS certs for ingress
helm/charts pull request #15499
Opened 2019-07-12 20:45 UTC by voor

#### What this PR does / why we need it:

Ingress format for tls allows providing no secret name, and ingress controllers will use a default certificate.  If a cluster has a wildcard cert as the default certificate, this allows grafana to consume that rather than having a specific secret that might not exist in the same namespace.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-12 20:46 UTC, voor commented
@zanhsieh @rtluckie @maorfr

2019-07-13 17:49 UTC, zanhsieh approved these changes

2019-07-13 17:49 UTC, zanhsieh commented
/assign
/ok-to-test

2019-07-13 18:04 UTC, zanhsieh requested changes
@voor 
Please change:

https://github.com/helm/charts/blob/master/stable/grafana/values.yaml#L103

to reflect the modification you made.

2019-07-13 18:22 UTC, voor commented
Hi @zanhsieh the format of the ingress definition has not changed, this structure just allows `secretName` to be an optional field.

So while:
```
   - secretName: chart-example-tls
     hosts:
       - chart-example.local
```
is still completely valid, you can now also do this:
```
   - hosts:
       - chart-example.local
```
Which will allow resolution by the SNI hostname alone (for example if you have a wildcard cert).

2019-07-13 23:28 UTC, zanhsieh commented
/retest

2019-07-13 23:30 UTC, zanhsieh commented
/lgtm

2019-07-13 23:31 UTC, merged