[stable/keel] keel chart
helm/charts pull request #1552
Opened 2017-07-25 18:41 UTC by rimusz

A chart that bootstraps Keel - stateless, robust and lightweight Continues Deployment system

2017-07-25 19:51 UTC, unguiculus requested changes
Thanks for the PR.

2017-07-25 19:51 UTC, unguiculus commented on stable/keel/templates/deployment.yaml
> +  name: {{ template "name" . }}
`name: {{ template "fullname" . }}`

2017-07-25 19:51 UTC, unguiculus commented on stable/keel/templates/deployment.yaml
> +        app: {{ template "name" . }}
Add `release` label.

2017-07-25 19:51 UTC, unguiculus commented on stable/keel/templates/secrets-webhookrelay.yaml
> +  name: {{ template "name" . }}-webhookrelay
Should use `{{ template "fullname" . }}`. Actually, the additional suffix is not necessary. Update references accordingly.

2017-07-25 19:51 UTC, unguiculus commented on stable/keel/templates/service-account.yaml
> +  name: {{ template "name" . }}
`name: {{ template "fullname" . }}`

2017-07-25 19:51 UTC, unguiculus commented on stable/keel/templates/service.yaml
> +  name: {{ template "name" . }}
`name: {{ template "fullname" . }}`

2017-07-25 19:51 UTC, unguiculus commented on stable/keel/templates/service.yaml
> +    app: {{ template "name" . }}
Add `release` label.

2017-07-25 19:51 UTC, unguiculus commented on stable/keel/values.yaml
> +resources:
Don't specify defaults for resources.

2017-07-25 19:51 UTC, unguiculus commented on stable/keel/Chart.yaml
> +- name: Rimas Mocevicius
Please use Github usernames.

2017-07-25 19:51 UTC, unguiculus commented on stable/keel/Chart.yaml
> +engine: gotpl
Do you have an `icon` you could add?

2017-07-25 20:43 UTC, rimusz commented on stable/keel/Chart.yaml
> +engine: gotpl
we do not the have the icon yet

2017-07-26 13:48 UTC, prydonius approved these changes
lgtm!

2017-07-26 13:48 UTC, prydonius commented on stable/keel/Chart.yaml
> +appversion: 0.4.1
Should be `appVersion`

2017-07-26 13:52 UTC, prydonius commented
@unguiculus lgtm, PTAL

2017-07-27 18:07 UTC, rimusz commented
ping @unguiculus let's do not make this chart stale, please

2017-07-28 05:23 UTC, unguiculus requested changes
Almost there. Secret references need to be fixed.

2017-07-28 05:23 UTC, unguiculus commented on stable/keel/templates/deployment.yaml
> +                  name: {{ template "name" . }}-webhookrelay
`{{ template "fullname" . }}-webhookrelay`

2017-07-28 05:23 UTC, unguiculus commented on stable/keel/templates/deployment.yaml
> +                  name: {{ template "name" . }}-webhookrelay
`{{ template "fullname" . }}-webhookrelay`

2017-07-28 05:55 UTC, rimusz commented
@unguiculus fixed the last ones `template "fullname"`

2017-07-28 16:26 UTC, unguiculus commented
/ok-to-test

2017-07-29 15:14 UTC, unguiculus requested changes

2017-07-29 15:14 UTC, unguiculus commented on stable/keel/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace kube-system  -l "app={{ template "fullname" . }}" -o jsonpath="{.items[0].metadata.name}")
`app={{ template "fullname" . }}` -> `app={{ template "name" . }},release={{ .Release.Name }}`

2017-07-29 15:14 UTC, unguiculus commented on stable/keel/templates/NOTES.txt
> +  kubectl --namespace=kube-system get pods -l "app={{ template "fullname" . }}"
`app={{ template "fullname" . }}` -> `app={{ template "name" . }},release={{ .Release.Name }}`

2017-07-29 18:54 UTC, unguiculus requested changes

2017-07-29 18:54 UTC, unguiculus commented on stable/keel/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace kube-system  -l "app=app={{ template "name" . }},release={{ .Release.Name }}" -o jsonpath="{.items[0].metadata.name}")
One `app` too many: `app=app=`

2017-07-31 15:43 UTC, unguiculus approved these changes

2017-07-31 15:44 UTC, merged