[stable/nginx-ldap-proxy] Add protocol configuration for nginx-ldap-proxy
helm/charts pull request #15532
Opened 2019-07-15 13:14 UTC by JGodin-C2C

## What this PR does / why we need it:
This PR allows the use of LDAPs instead of the hard-coded ldap protocol.
Retro-compatiblity is assured by the value file. 

J
 
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x] Chart Version bumped
- [ x] Variables are documented in the README.md
- [ x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-07 12:34 UTC, Aisuko commented
/retest

2019-08-07 12:49 UTC, Aisuko requested changes
Thanks for your PR. Please see below.

2019-08-07 12:49 UTC, Aisuko commented on stable/nginx-ldapauth-proxy/Chart.yaml
>  sources:
Please add `home: https://github.com/nginxinc/nginx-ldap-auth` filed here, that could allow your PR test to succeed.

2019-08-19 15:56 UTC, Aisuko commented
/test all

2019-09-10 12:15 UTC, Aisuko approved these changes
/ok-to-test

2019-09-10 12:19 UTC, Aisuko commented
/lgtm

2019-09-11 07:29 UTC, JGodin-C2C commented
/assign @mattfarina

2019-10-09 11:30 UTC, JGodin-C2C commented
Ping on this ? :)

2019-10-09 18:18 UTC, zanhsieh commented
/ok-to-test

2019-10-12 13:44 UTC, Aisuko commented
cc @maorfr Hello sir, Please help us with this. Thanks

2019-10-21 14:31 UTC, maorfr commented
/lgtm

thanks!

2019-10-22 01:35 UTC, Aisuko commented
/test pull-charts-e2e

2019-10-22 01:47 UTC, merged