[stable/concourse] add missing credhub mtls auth
helm/charts pull request #15541
Opened 2019-07-15 19:26 UTC by cirocosta

## What this PR does / why we need it:

Previously (https://github.com/helm/charts/pull/14545), configuration
was added to allow folks to leverage CredHub as a credential management
for Concourse.

While that allowed people to have that functionality, it was only
partially implemented - mutual TLS was still missing.

This commit aims at addressing that by introducing a
`authenticationMode` key that allows one to either specify a secret & id
pair for the authentication, or client certificates.

#### Which issue this PR fixes

  - fixes #15459

#### Special notes for your reviewer:

Here's a break down of some possible cases:

```yaml
# mTLS with nothing set - fails
#
concourse:
  web:
    credhub:
      enabled: true
      authenticationMode: "mtls"
```

```yaml
# mTLS with certificates set - succeeds
#
concourse:
  web:
    credhub:
      enabled: true
      authenticationMode: "mtls"
secrets:
  credhubClientKey: dhisuah
  credhubClientCert: iusahdi
```

```yaml
# secrets with nothing set - fails
#
concourse:
  web:
    credhub:
      enabled: true
      authenticationMode: "secrets"
```

```yaml
# secrets with the keys set - suceeds
#
concourse:
  web:
    credhub:
      enabled: true
      authenticationMode: "secrets"
secrets:
  credhubClientId: dhisuah
  credhubClientSecret: iusahdi
```

```yaml
# values for both set - succeeds
# - selects "mtls" variables (as that's the auth mode configured)
#
concourse:
  web:
    credhub:
      enabled: true
      authenticationMode: "mtls"
secrets:
  credhubClientKey: dhisuah
  credhubClientCert: iusahdi
  credhubClientId: dhisuah
  credhubClientSecret: iusahdi
```

```yaml
# empty - works without credhub 😁 
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-15 19:27 UTC, cirocosta commented
Hey @aegershman, would you mind reviewing this one?

We're not entirely sure whether that the right usage of CredHub, but we guess that's the case - you either use TLS certificates or client secrets 🤔 

Thank you!

2019-07-16 01:45 UTC, aegershman requested changes
👍 left a comment regarding `credhubClientCert`

I'll be honest in saying that I haven't leveraged mTLS for credhub auth. The [concourse documentation on configuring credhub](https://concourse-ci.org/credhub-credential-manager.html#configuration) only demos using client credentials. This could be a good opportunity to update the credhub provider docs; I'd contribute it, but to be honest I don't 100% know what it should be.

With that said, I believe this PR implementation is correct.

---

more background:

Notice the [vault credentials manager doc](https://concourse-ci.org/vault-credential-manager.html) has a section on the `cert` backend which mentions using the certificate _path_. Further, the existing impl of `vault` using `cert` backend [uses the _path_ of the key/cert rather than the "raw" values](https://github.com/helm/charts/blob/e94c100265a32382be50f7aa1258947817d5c3a1/stable/concourse/templates/web-deployment.yaml#L429-L434), which might lead you to think Credhub does the same (e.g., instead of a `secretKeyRef`, the `clientCert` would be evaluated as the path, `credhubSecretsPath/client.{cert,key}`). **But**, considering the [bosh-deployment for concourse](https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/operations/credhub-colocated.yml#L117) appears to want the full certificate, as does the [bosh doc for 4.2.1](https://bosh.io/jobs/atc?source=github.com/concourse/concourse&version=4.2.1#p%3dcredhub.tls.client_cert), I believe the provided PR implementation is correct.

I don't know anything beyond that, though. Not sure if having other params like the `CREDHUB_CA_CERT` are required if using `mTLS`. It's also possible I'm _completely misunderstanding everything_ and `mTLS` and `secrets` aren't mutually exclusive && are actually supposed to be used together. I doubt it, but it's possible.

Apologies for not giving a resounding vote of confidence on usage, but this is part of the reason it wasn't implemented in the first PR  😉

what do you think?

2019-07-16 01:45 UTC, aegershman commented on stable/concourse/templates/web-deployment.yaml
> +                  key: credhub-client-key
`credhubClientCert`?

2019-07-18 15:38 UTC, cirocosta commented on stable/concourse/templates/web-deployment.yaml
> +                  key: credhub-client-key
oooh nice catch! thank you!

2019-07-18 15:42 UTC, cirocosta commented
> Not sure if having other params like the CREDHUB_CA_CERT are required if using mTLS

Yeah, I was quite unsure about that too! Looking at https://github.com/concourse/concourse/blob/360d64f152c165a53bc219f3ac8cb7057b11aa3b/atc/creds/credhub/manager.go#L55-L89, it seems like it's not 🤷‍♂  

> Apologies for not giving a resounding vote of confidence on usage, but this is part of the reason it wasn't implemented in the first PR 😉

np! Totally understand 😁  thanks for giving the start on it!

>  This could be a good opportunity to update the credhub provider docs; I'd contribute it, but to be honest I don't 100% know what it should be.

ooh nice to know! If you'd like to get started with an issue, I guess we could have some more eyes on it and people helping us out - wdyt?

Thank you!

---

Just updated the field you pointed out 👍  

Thanks again!

2019-07-22 13:30 UTC, cirocosta commented
cc @YoussB just rebased 😁

2019-07-26 14:15 UTC, YoussB commented
/LGTM

2019-07-26 14:15 UTC, YoussB commented
@cirocosta looks like it needs another rebase,

2019-07-26 14:50 UTC, cirocosta commented
@YoussB thx! I just rebased it here

2019-07-26 15:22 UTC, YoussB commented
/lgtm

2019-07-26 15:23 UTC, YoussB approved these changes

2019-07-26 15:24 UTC, merged