[stable/jenkins] Change the value name for docker image tags - standartise to what is accepted standard in all charts - tag; this also allows auto-deployments using weaveworks flux
helm/charts pull request #15565
Opened 2019-07-16 14:50 UTC by isindir

* Change the value name for docker image tags - standartise to what is accepted standard in all charts - tag
* This also allows auto-deployments using weaveworks flux

@torstenwalter
@maorfr
@viglesiasce
@lachie83

Signed-off-by: Eriks Zelenka <isindir@users.sf.net>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-16 14:55 UTC, isindir commented
/assign @viglesiasce

2019-07-17 15:40 UTC, torstenwalter commented
> standartise to what is accepted standard in all charts - tag

Can you tell me where this standard is documented?

I did a quick search through this repository. These charts use "imageTag" (total of 39):

```
incubator/artifactory/values.yaml
incubator/istio/values.yaml
incubator/kafka/values.yaml
incubator/mysqlha/values.yaml
incubator/schema-registry/values.yaml
stable/atlantis/values.yaml
stable/chaoskube/values.yaml
stable/cockroachdb/values.yaml
stable/concourse/values.yaml
stable/consul/values.yaml
stable/dask-distributed/values.yaml
stable/dex/values.yaml
stable/factorio/values.yaml
stable/gcloud-sqlproxy/values.yaml
stable/gitlab-ce/values.yaml
stable/gitlab-ee/values.yaml
stable/hackmd/values.yaml
stable/hlf-ca/values.yaml
stable/jenkins/values.yaml
stable/kubedb/values.yaml
stable/memcached/values.yaml
stable/minecraft/values.yaml
stable/minio/values.yaml
stable/mysql/values.yaml
stable/neo4j/values.yaml
stable/opa/values.yaml
stable/openebs/values.yaml
stable/percona/values.yaml
stable/prisma/values.yaml
stable/sensu/values.yaml
stable/sentry/values.yaml
stable/signalfx-agent/values.yaml
stable/sonatype-nexus/values.yaml
stable/spark/values.yaml
stable/spinnaker/values.yaml
stable/superset/values.yaml
stable/traefik/values.yaml
stable/uchiwa/values.yaml
stable/voyager/values.yaml
```

 Is it not possible to use `imageTag` for flux?

Changing the property would be a breaking change. So a major version number increase would be required. Not sure if the effect to users is in relation to the gained benefit.

2019-07-17 15:56 UTC, isindir commented
@torstenwalter I realise that is breaking change. But at the same time jenkins chart is not consistent as well - in 2 cases `imageTag` is used but in one `tag`. Not sure if the standard is written anywhere, but when brand new chart is created with `helm` it has `tag`, for example:

```
helm create abc
```

generated following `values.yaml`:

```
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
```

just assume that is best practice.

Flux does not support imageTag:
https://github.com/fluxcd/flux/blob/8292179855e15370fb3d3b03135a61b54f00ae42/site/helm-integration.md#upgrading-images-in-a-helmrelease-using-flux

2019-07-17 20:53 UTC, isindir commented
There are actually best practices defined in helm documentation:
https://github.com/helm/helm/blob/master/docs/chart_best_practices/values.md#flat-or-nested-values

I can redo this PR to follow helm best practices and satisfy flux requirements at the same time.
Thanks

2019-07-17 21:18 UTC, torstenwalter commented
I am aware of those, but there is little information regarding image tags:
https://github.com/helm/helm/blob/master/docs/chart_best_practices/pods.md#images

> An image and a tag may be defined in values.yaml as two separate fields:

> `image: "{{ .Values.redisImage }}:{{ .Values.redisTag }}"`

Do you see an option to implement the change as a non-breaking change?

2019-07-18 07:41 UTC, isindir commented
@torstenwalter I'll think about it, but likely to involve both tagging schemas to be in place and one would be prefered option. If that sounds good, I can have a go ?

2019-07-18 14:40 UTC, ezelenka commented
/assign @torstenwalter

2019-07-18 14:41 UTC, isindir commented
/assign @torstenwalter

2019-07-18 14:47 UTC, isindir commented
@torstenwalter please review refined code

2019-07-18 19:43 UTC, torstenwalter requested changes

2019-07-18 19:43 UTC, torstenwalter commented on stable/jenkins/templates/deprecation.yaml
> +           {{ fail "`master.imageTag` will be obsoleted soon. It has been renamed to `master.tag`" }}
fail results in an error. So the chart can not be deployed before fixing it.

I suggest to move the if statement to the NOTES.txt and print a warning instead.

2019-07-18 19:43 UTC, torstenwalter commented on stable/jenkins/templates/deprecation.yaml
> +           {{ fail "`Master.ImageTag` does no longer exist. It has been renamed to `master.tag`" }}
Same as above.

2019-07-19 05:24 UTC, ezelenka commented
@torstenwalter my bad, should have done better code reading... Changed as you suggested.

2019-07-19 05:25 UTC, torstenwalter commented
Deprecation warning looks good. Could you add the same for `agent.imageTag`?

2019-07-19 05:28 UTC, ezelenka commented
Morning, yep - noticed that as well :)

2019-07-19 06:07 UTC, isindir commented
Should be fixed now

2019-07-19 08:44 UTC, torstenwalter commented
/lgtm

2019-07-19 08:45 UTC, torstenwalter commented
@isindir Thank you for the PR. Great job.

2019-07-19 09:01 UTC, merged