[stable/airflow]: Added extraInitContainers option
helm/charts pull request #15690
Opened 2019-07-18 15:32 UTC by MahaGamal

#### What this PR does / why we need it:
Additional init containers to run before the Scheduler pods.
usr/local/airflow/logs storage. This directory needs to be writable by the airflow user, which runs as UID 1000.
There is no way to set the UID of user using the definition of Pod, but Kubernetes saves the UID of sourced volume.
So, i can set the UID by InitContainer, which launches before the main container

#### Which issue this PR fixes
#15671

2019-08-16 07:36 UTC, Aisuko requested changes
Thanks for your PR, so cleanly. Let's solute the conflict.

2019-08-28 08:03 UTC, gsemet commented
Hi. Thanks for your PR. Can you rebase so that I can merge it

2019-08-28 08:03 UTC, gsemet commented
/assign gsemet

2019-09-16 21:06 UTC, gsemet commented
Hi @MahaGamal are you still interested in this pull request? Can you rebase it? thanks

2019-09-22 08:55 UTC, MahaGamal commented
@gsemet

2019-09-22 08:57 UTC, gsemet approved these changes
/lgtm

2019-09-22 09:11 UTC, merged