[stable/nginx-ingress] Allow to configure source IP preservation through on Kubernetes 1.7
helm/charts pull request #1570
Opened 2017-07-28 09:54 UTC by mstrzele

Unfortunately, after upgrading Kubernetes to 1.7, I'm no longer able to set `service.beta.kubernetes.io/external-traffic`.

According to [documentation](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#feature-availability), the annotation is deprecated and the field under `service.spec` should be used.

This pull request adds two values to controller's service: `externalTrafficPolicy` and `healthCheckNodePort`

2017-07-28 12:04 UTC, mstrzele commented
Probably duplicate of #1542. The only difference is the `healthCheckNodePort` value.

2017-08-14 19:55 UTC, mgoodness requested changes
Just a couple minor changes. Be sure to rebase & re-bump chart version.

2017-08-14 19:55 UTC, mgoodness commented on stable/nginx-ingress/values.yaml
> +    # externalTrafficPolicy: Local
Un-comment this and set to `""`

2017-08-14 19:55 UTC, mgoodness commented on stable/nginx-ingress/values.yaml
> +    # healthCheckNodePort: 32080
Un-comment and set to `0` (zero)

2017-08-14 20:01 UTC, mgoodness submitted a review, later dismissed
Couple more changes. Sorry.

2017-08-14 20:01 UTC, mgoodness commented on stable/nginx-ingress/templates/controller-service.yaml
> +{{- if .Values.controller.service.externalTrafficPolicy }}
Make this `{{- if and (ge .Capabilities.KubeVersion.Minor "7") (.Values.controller.service.externalTrafficPolicy) }}` so v1.6 (and lower) is still supported.

2017-08-14 20:01 UTC, mgoodness commented on stable/nginx-ingress/templates/controller-service.yaml
> +{{- if .Values.controller.service.healthCheckNodePort }}
Make this `{{- if and (ge .Capabilities.KubeVersion.Minor "7") (.Values.controller.service. healthCheckNodePort) }}` so v1.6 (and lower) is still supported.

2017-09-02 14:47 UTC, mgoodness commented
/ok-to-test

2017-09-02 14:47 UTC, mgoodness commented
/lgtm

2017-09-02 14:52 UTC, merged