[stable/logstash] add servicemonitor
helm/charts pull request #15829
Opened 2019-07-24 12:36 UTC by angelfs

Signed-off-by: Julian Marié <ang3lfs@gmail.com>

#### What this PR does / why we need it:

When use exporter, allow to create a servicemonitor for prometheus metrics.
Add a comment in values.yaml (service.exporter) to create the service which expose metrics.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
I change exporter.logstash by metrics, in some of charts, this convention is used.
If you prefere, I can change exporter.logstash in another PR.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-28 11:56 UTC, davidkarlsen requested changes

2019-07-28 11:56 UTC, davidkarlsen commented on stable/logstash/Chart.yaml
> +version: 2.1.1
```suggestion
version: 2.2.0
```

2019-07-28 11:56 UTC, davidkarlsen commented
/ok-to-test

2019-07-31 08:19 UTC, angelfs commented on stable/logstash/Chart.yaml
> +version: 2.1.1
Modification done

2019-09-29 13:57 UTC, zanhsieh commented
/retest

2019-09-29 13:58 UTC, zanhsieh commented
@angelfs 
Please sign off DCO. Thank you.

2019-11-09 05:35 UTC, zanhsieh commented
@christian-roggia
@rendhalver

Would you guys LGTM this PR please? Thank you.

2019-12-23 07:19 UTC, closed without merging