stable/velero: Add azure support based on velero CLI
helm/charts pull request #15834
Opened 2019-07-24 14:18 UTC by clebs

#### What this PR does / why we need it:
- Fixes the velero chart deployment for Azure, producing the same output as the velero CLI in version 1.0.0.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #15701

#### Special notes for your reviewer:

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-24 14:24 UTC, clebs commented
/assign @hectorj2f

2019-07-25 02:51 UTC, nrb approved these changes
I thought I had already added this, but apparently not!

2019-07-26 15:24 UTC, nrb commented
/ok-to-test

2019-08-09 09:36 UTC, clebs commented
Thanks for the review @nrb!
It seems though that Tide still requires an approval/lgtm label to allow merging.
Could you add it if all is fine please? Thanks! :)

2019-08-27 07:15 UTC, clebs commented
Hello @nrb, @hectorj2f,
is it possible that this PR got lost in the inbox? It would be great if you could add the missing label for it to get merged, or, if there is still something to change, please let me know!

2019-08-27 07:39 UTC, hectorj2f requested changes
I will keep the conditions for the provider's name adding one for azure. I won't like to have an AWS env var while using azure.

2019-08-27 09:46 UTC, clebs commented
I did base my change on what [Velero CLI](https://github.com/heptio/velero/tree/master/pkg/cmd/cli) generates. It does keep all credentials files for all providers.

Of course it would be possible to just have a condition for it and create only the relevant entry.

Is this what you are aiming for?

2019-09-26 10:43 UTC, hectorj2f commented
@clebs Yeah, it got lost somehow. Can you fix the conflicts ?

2019-10-26 11:45 UTC, zanhsieh commented
/remove-lifecycle stale

2019-11-12 21:31 UTC, nrb commented
@clebs Sorry about the delay in getting this approved. Would you be able to fix the conflicts? Once that's done, I'm :+1:

2019-11-13 15:43 UTC, clebs commented
Hi @nrb, I have solved the conflicts and it should now be ready to be merged.

2019-11-13 19:06 UTC, nrb commented
/approve

2019-11-14 12:33 UTC, clebs commented
Hi @nrb, thanks for the approval. It seems Tide still needs the `lgtm` label to merge the PR.

2019-11-14 14:51 UTC, ZeroVEVO approved these changes

2019-11-14 17:29 UTC, hectorj2f reviewed
/lgtm

2019-11-14 17:33 UTC, merged