[stable/opencart] Fix opencart template errors when using ingress
helm/charts pull request #15891
Opened 2019-07-25 09:31 UTC by miguelaeh

#### What this PR does / why we need it:
Fix the template when using ingress for Opencart Helm Chart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-25 09:38 UTC, miguelaeh commented on stable/opencart/Chart.yaml
> -version: 4.5.3
This was not the previous version, I forgot to update my fork so I needed to update the version until the latest one.

2019-07-26 07:34 UTC, tompizmor requested changes

2019-07-26 07:34 UTC, tompizmor commented on stable/opencart/Chart.yaml
> +version: 5.1.2
I think now you should update it to `6.0.1`

2019-07-26 08:05 UTC, tompizmor approved these changes
/ok-to-test
/lgtm

2019-07-26 08:36 UTC, merged