stable/sonatype-nexus
helm/charts pull request #15909
Opened 2019-07-26 09:43 UTC by cmoroianu1

Signed-off-by: Catalin Moroianu <c.moroianu@travelaudience.com>

#### What this PR does / why we need it:
Update Sonatype Nexus to the latest version.

Changes:
- updated Nexus to latest version
- updated Alpine to latest version
- updated OpenJDK to latest version

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-26 14:14 UTC, davidkarlsen commented
/ok-to-test

2019-07-26 14:15 UTC, davidkarlsen requested changes

2019-07-26 14:15 UTC, davidkarlsen commented on stable/sonatype-nexus/values.yaml
> +  imageTag: 3.17.0
please update the readme too

2019-07-26 14:27 UTC, cmoroianu1 commented on stable/sonatype-nexus/values.yaml
> +  imageTag: 3.17.0
updated. thanks!

2019-07-28 12:26 UTC, davidkarlsen commented
@cmoroianu1 In the mean time 3.18.0 has been released. Update?

2019-07-28 12:26 UTC, davidkarlsen approved these changes

2019-07-28 12:26 UTC, davidkarlsen commented
/assign

2019-07-28 18:36 UTC, davidkarlsen commented
Why not use the standard image https://hub.docker.com/r/sonatype/nexus3/ ?

2019-07-29 08:18 UTC, davidkarlsen commented
/lgtm

2019-07-29 08:25 UTC, merged