[stable/nginx-ingress] Add helpful comment regarding affinity
helm/charts pull request #15904
Opened 2019-07-25 21:13 UTC by naseemkullah

I presume this is how people keep the pods when run as a deployment running on separate nodes? If so it's nice to have it in the values file to easily uncomment.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-25 22:14 UTC, ChiefAlexander requested changes
Hey thanks for the PR! Just need to bump the version and I will be fine with this.

2019-07-25 22:14 UTC, ChiefAlexander commented on stable/nginx-ingress/Chart.yaml
> +version: 1.11.2
This should be 1.11.3

2019-07-25 22:28 UTC, naseemkullah commented on stable/nginx-ingress/Chart.yaml
> +version: 1.11.2
Oops, done! Thanks.

2019-07-25 23:24 UTC, ChiefAlexander commented
/lgtm

2019-07-26 03:37 UTC, naseemkullah commented
/retest

2019-07-26 05:01 UTC, merged