[stable/metrics-server] Update 'metrics-server' to v0.3.3.
helm/charts pull request #15919
Opened 2019-07-26 15:36 UTC by bmcstdio

### What this PR does / why we need it:

This PR updates `metrics-server` to v0.3.3.

#### Which issue this PR fixes

N/A

#### Special notes for your reviewer:

N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-26 16:16 UTC, olemarkus requested changes

2019-07-26 16:16 UTC, olemarkus commented on stable/metrics-server/Chart.yaml
> +version: 2.8.3
Bump minor version here

2019-07-26 16:16 UTC, olemarkus commented on stable/metrics-server/Chart.yaml
>  appVersion: 0.3.2
Bump version here too

2019-08-20 15:57 UTC, olemarkus commented
/ok-to-test

2019-08-27 11:35 UTC, PierluigiLenociAkelius commented
This PR is uncomplete and now is useless. Ref: #16618
@bmcstdio could you please close it?

2019-08-27 11:43 UTC, PierluigiLenociAkelius commented
/assign @olemarkus

2019-08-28 14:05 UTC, PierluigiLenociAkelius commented
https://github.com/helm/charts/pull/16656

2019-08-28 14:05 UTC, PierluigiLenociAkelius commented
@bmcstdio could you please close this?

2019-09-02 07:53 UTC, closed without merging