[incubator/jaeger] allow specifying priorityClassName
helm/charts pull request #15954
Opened 2019-07-29 20:01 UTC by r0fls

#### What this PR does / why we need it:
Adds configurable `priorityClassName` to jaeger agent daemonset. This is needed for environments that support `priorityClassName` to ensure scheduling of the jaeger agent on all nodes.

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-07-29 20:08 UTC, naseemkullah commented
/ok-to-test

2019-07-31 00:40 UTC, granular-ryanbonham commented on incubator/jaeger/templates/agent-ds.yaml
> +        priorityClassName: {{ .Values.agent.priorityClassName }}
priorityClassName goes under the the .spec.template.spec not .spec.template.spec.containers[]

2019-08-12 14:19 UTC, naseemkullah requested changes

2019-08-12 14:19 UTC, naseemkullah commented on incubator/jaeger/values.yaml
> +  priorityClassName: null
So sorry for the delay @r0fls!

Thanks for the PR! Don't mean to be nit picky but could the `agent.priorityClassName` be put somewhere below `agent.enabled` ? Cheers

2019-09-25 14:50 UTC, closed without merging