Added loadBalancerIP too the traefik service template
helm/charts pull request #1607
Opened 2017-08-03 13:54 UTC by vongohren

This can be set through a value called googleStaticIP, which is None by default. This was needed to make it possible to set up your loadbalancer with helm and assigning an already reserverd static ip in GCP. Im not sure if this works on other clouds, therefor have I called it googleStaticIP. Updated README with proper values

2017-08-03 15:40 UTC, krancour commented
I think if we start introducing cloud-specific functionality to this chart, those features should maybe be cordoned off in their own section of `values.yaml`. i.e. Perhaps add a `gcp` section and move this option under there. Additionally, it might be worthwhile to introduce another option that is undefined by default, but can be set to indicate what cloud the chart is being deployed to. This way, if (as?) cloud-specific options continue to grow, it will be easy to write templates that quickly determine which swath of cloud-specific options are applicable.

Also, you'd need to bump the chart's minor version number in `chart.yam`.

2017-08-03 16:54 UTC, vongohren commented
@krancour I did a commit now which made it more cloud specific. But would you like to elborate on the last part? Not sure if I get how it can be done?

My thought would be to have a value saying `cloud`

If set to f.ex "gcp", how would that be used?
You thinking of then having templates with if statements based on the value of cloud? Then those options would be available, and if no cloud specified, those would not be available?

2017-08-04 04:48 UTC, krancour commented on stable/traefik/Chart.yaml
> +version: 1.7.3
This PR adds a feature; not a bug fix. So, this should be 1.8; not 1.7.3.

2017-08-04 04:53 UTC, krancour commented
> You thinking of then having templates with if statements based on the value of cloud? Then those options would be available, and if no cloud specified, those would not be available?

Yes. Exactly. So the following:

```
{{- if .Values.gcp.staticIP }}
loadBalancerIP: {{ .Values.gcp.staticIP }}
{{- end }}
```

Should change to something like:

```
{{- if and (eq .Values.cloud "gcp") (.Values.gcp.staticIP) }}
loadBalancerIP: {{ .Values.gcp.staticIP }}
{{- end }}
```

These sort of guards can be used to ensure that logic that's only applicable to a given cloud isn't applied to deployments to some other cloud.

2017-08-04 07:05 UTC, unguiculus requested changes

2017-08-04 07:05 UTC, unguiculus commented on stable/traefik/README.md
> +| `gcp.staticIP`            | An available IP you have reserved on Google Cloud Platform           | None                                      |
Don't call it `gcp.staticIP`. This is not GCP-specific. Just call it `loadBalancerIP`.

2017-08-04 07:05 UTC, unguiculus commented on stable/traefik/Chart.yaml
> +version: 1.7.3
I agree.

2017-08-04 07:38 UTC, vongohren commented on stable/traefik/README.md
> +| `gcp.staticIP`            | An available IP you have reserved on Google Cloud Platform           | None                                      |
What do you think of @krancour's suggestion? As I mentioned in my comment im not sure how this works with other clouds. But you know that this works with more than gcp?

2017-08-04 07:39 UTC, vongohren commented
I think that its a good idea @krancour, but now @unguiculus came with a change request meaning that it probably works with multiple clouds. So the cloud specifics have to come with another PR i think

2017-08-04 13:25 UTC, unguiculus commented
/ok-to-test

2017-08-04 20:01 UTC, krancour commented
@vongohren you mentioned not knowing if/how this works in clouds other than GCP, and I have to admit, I let that fool me into thinking there was _probably_ something cloud-specific happening here. Especially in light of @unguiculus comment, I've reconsidered that. I think that setting the `loadBalancerIP` in the service is always going to be ok and if a cloud provider support it, it supports it. Or it may not. It will all sort itself out. So I agree with @unguiculus.

Having said that, this setting probably isn't equally applicable to all _types_ of services. e.g. It makes sense when the service is one of `type: LoadBalancer`, but if it's one of `type: NodePort` (for instance), it may not make as much sense.

So, should the service type be considered when deciding to set or not set this attribute?

2017-08-05 11:29 UTC, vongohren commented
Yeah @krancour, something like this? Im quite new to this, but it sounds logical. But either you or @unguiculus have to answer if this is the case, and that you want this change

```
{{- if and (eq .Values.serviceType "LoadBalancer") (.Values.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
{{- end }}
```

2017-08-07 17:27 UTC, unguiculus commented
You can check the chart examples for reference: https://github.com/kubernetes/helm/blob/master/docs/examples/nginx/templates/service.yaml

2017-08-07 20:44 UTC, vongohren commented
Looks like what im doing here, so I would say its good to go?

2017-08-08 13:39 UTC, unguiculus approved these changes

2017-08-08 13:40 UTC, unguiculus commented
Bump the chart version as suggested and this is good to go.

2017-08-08 13:58 UTC, vongohren commented
@unguiculus done!

Guess i missed that one since he commented something else earlier

2017-08-08 16:28 UTC, krancour commented
@vongohren the version still doesn't appear changed.

2017-08-08 17:36 UTC, vongohren commented
@krancour ah no sorry, I assumed 1.8 was latest, but someone captured that version, so I now do 1.9. Now its done.

2017-08-08 17:41 UTC, krancour commented
LGTM

2017-08-08 19:18 UTC, merged