[stable/etcd-operator] chore: updates etcd-operator to v0.9.4
helm/charts pull request #16085
Opened 2019-08-05 10:15 UTC by marcostvz

#### What this PR does / why we need it:
* updates etcd-operator to v0.9.4
* adds securityContext to operators
* adds imagePullSecrets to serviceAccounts

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-05 10:22 UTC, marcostvz commented
/retest

2019-08-06 07:22 UTC, marcostvz commented
/assign @alejandroEsc  :)

2019-08-06 10:37 UTC, marcostvz commented
/assign @lachie83

2019-08-06 15:52 UTC, alejandroEsc commented
/assign alejandroEsc
/ok-to-test

2019-08-06 15:55 UTC, alejandroEsc commented
/ok-to-test

2019-08-06 16:03 UTC, alejandroEsc requested changes
LGTM overall, nice job. Will be testing myself soon.

2019-08-06 16:03 UTC, alejandroEsc commented on stable/etcd-operator/templates/backup-etcd-crd.yaml
> ----
Can you leave the initial `---` for now.

2019-08-06 16:03 UTC, alejandroEsc commented on stable/etcd-operator/templates/backup-operator-deployment.yaml
> -      serviceAccountName: {{ template "etcd-backup-operator.serviceAccountName" . }}
nice I like this.

2019-08-06 16:03 UTC, alejandroEsc commented on stable/etcd-operator/templates/etcd-cluster-crd.yaml
> ----
please leave initial `---` marks for now.

2019-08-08 00:06 UTC, marcostvz commented
Hey @alejandroEsc , check my last commits with the changes you requested (and I also modified a couple of things I noticed later). Thanks a lot! :)

2019-08-08 18:40 UTC, davidkarlsen commented
/ok-to-test

2019-08-21 11:10 UTC, marcostvz commented
Hello @alejandroEsc , does this PR need anything else? Thanks!

2019-08-21 15:57 UTC, alejandroEsc commented
@marcostvz Sorry! been busy here and will look today (promise) @davidkarlsen why wasn't i able to set ok-to-test before?

2019-08-21 17:09 UTC, alejandroEsc commented
/lgtm

2019-08-21 17:48 UTC, merged