[stable/dask] Mount only jupyter_notebook_config.py file instead of whole jupyter directory.
helm/charts pull request #16106
Opened 2019-08-06 08:33 UTC by kayibal

#### What this PR does / why we need it:
Instead of mounting the whole `~/.jupyter` directory with a config map, it only mounts the file specified in the config map now: `jupyter_notebook_config.py`. 

This way I can build images with custom configurations which are not overwritten by the mount, edit configurations in JuypterLab (e.g. keyboard shortcuts, etc.). Last but not least, I can actually use the dask labextension with kubectl port-forward without getting `{"message": "[Errno 30] Read-only file system: '/home/jovyan/.jupyter/lab'", "reason": null}`. 

I guess issue #13124 is somehow related..

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-06 08:43 UTC, kayibal commented
/assign @prydonius

2019-08-22 09:14 UTC, Aisuko requested changes
Thanks for your PR, please have a look on https://github.com/kubernetes/kubernetes/issues/61076 . So, If we add `subPath ` to this chart. Shall we need to bump the `Major version`? And there should add the upgrade notice in README.md, the chart only support `Kubernetes version > 1.7.0` right?

2019-09-01 14:46 UTC, kayibal commented
@Aisuko Thanks for pointing out the potential issues with changing this to sub path. I'm not exactly sure what Kubernetes version this chart supports and if we should bump the major version. Maybe one of the owners could have a short look over this @danielfrg @mrocklin

2019-10-03 03:53 UTC, zanhsieh commented
/ok-to-test

2019-10-03 03:54 UTC, zanhsieh commented
@kayibal 
Could you resolve stable/dask/Chart.yaml conflict please? Thank you.

2019-11-16 05:48 UTC, closed without merging