[stable/nginx-ingress] add terminationGracePeriodSeconds option
helm/charts pull request #16115
Opened 2019-08-06 15:09 UTC by henryoswald

#### What this PR does / why we need it:
Adds terminationGracePeriodSeconds as a configurable option to nginx-ingress. Useful for allowing very long running requests to finish processing (websockets) before killing the pod. 

#### Which issue this PR fixes

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x ] Chart Version bumped
- [ x ] Variables are documented in the README.md
- [ x ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-06 15:15 UTC, ChiefAlexander requested changes
Thanks for the PR! Just a few things to fixup

2019-08-06 15:15 UTC, ChiefAlexander commented on stable/nginx-ingress/Chart.yaml
> +version: 1.13.1
`1.13.0`

2019-08-06 15:15 UTC, ChiefAlexander commented on stable/nginx-ingress/README.md
> +`controller.terminationGracePeriodSeconds` | how many seconds to wait before terminating a pod | `{}`
default is 60 not `{}`

2019-08-06 15:15 UTC, ChiefAlexander commented
/ok-to-test

2019-08-06 15:15 UTC, ChiefAlexander commented
/assign

2019-08-06 15:23 UTC, henryoswald commented on stable/nginx-ingress/Chart.yaml
> +version: 1.13.1
Thanks, updated.

2019-08-06 15:23 UTC, henryoswald commented on stable/nginx-ingress/README.md
> +`controller.terminationGracePeriodSeconds` | how many seconds to wait before terminating a pod | `{}`
Thanks, updated.

2019-08-06 15:26 UTC, ChiefAlexander commented
Thanks again!
/lgtm

2019-08-06 16:00 UTC, henryoswald commented
Thanks @ChiefAlexander

2019-08-06 16:07 UTC, henryoswald commented
/retest

looks similar to https://github.com/helm/charts/issues/16070

2019-08-06 16:26 UTC, ChiefAlexander commented
We also have a bunch of tests that we run. I went a little crazy adding test cases b/c we caused things to break one to many times without them.

2019-08-06 18:00 UTC, ChiefAlexander commented
/test pull-charts-e2e

2019-08-06 18:50 UTC, henryoswald commented
/test pull-charts-e2e

2019-08-06 19:40 UTC, ChiefAlexander commented
The test is failing on https://github.com/helm/charts/blob/master/stable/nginx-ingress/ci/deamonset-hostport-values.yaml
```
I0806 18:40:38.883]   Warning  FailedScheduling   52s (x18 over 10m)     default-scheduler   0/3 nodes are available: 2 node(s) didn't match node selector, 3 node(s) didn't have free ports for the requested pod ports.
```

Lets set the hostports to a random port instead of trying to bind to the defaults (80,443)
```
controller:
  kind: DaemonSet
  daemonset:
    useHostPort: true
    hostPorts:
      http: 58462
      https: 58463
```

2019-08-07 08:22 UTC, henryoswald commented
/test pull-charts-e2e

2019-08-07 11:15 UTC, henryoswald commented
looks like the change fixed the tests, thanks @ChiefAlexander 

Would you like the port change inside this pr or removed/moved?

2019-08-07 14:19 UTC, ChiefAlexander commented
Here is fine
/lgtm

2019-08-07 17:38 UTC, merged