[stable/metabase] Add tolerations and affinity
helm/charts pull request #16129
Opened 2019-08-07 08:52 UTC by amit-o

Signed-off-by: Amit Oren <amitoren224@gmail.com>

#### What this PR does / why we need it:
Add tolerations and affinity in addition to the node selector already present

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-07 08:53 UTC, amit-o commented
/assign @paulczar

2019-08-08 13:17 UTC, amit-o commented
davidkarlsen

2019-08-08 13:17 UTC, amit-o commented
/assign @davidkarlsen

2019-08-08 17:22 UTC, davidkarlsen requested changes

2019-08-08 17:22 UTC, davidkarlsen commented on stable/metabase/Chart.yaml
> +version: 0.7.1
```suggestion
version: 0.8.0
```

2019-08-08 17:22 UTC, davidkarlsen commented
/ok-to-test

2019-08-13 08:14 UTC, amit-o commented
@davidkarlsen ping

2019-08-15 08:10 UTC, cpanato approved these changes
/lgtm

2019-08-15 08:26 UTC, merged