[stable/jenkins] Update and standardize Jenkins chart
helm/charts pull request #1615
Opened 2017-08-04 05:00 UTC by binoculars

## Changes
* Standardize template filenames
* Use current helm best practices with values file (lowercase names, etc)
* Update default image repositories to their current locations
* Use current LTS master and latest agent image tags
* Compatible with Kubernetes 1.6+, if rbac is enabled (alpha API is deprecated)

2017-08-04 07:00 UTC, unguiculus requested changes
Excellent. This is very much appreciated. I made a few comments.

2017-08-04 07:00 UTC, unguiculus commented on stable/jenkins/templates/deployment.yaml
> +{{- $component := printf "%s-master" .Release.Name }}
In `NOTES.txt` you do this: `"component={{ template "fullname" . }}-master"`. Please make it consistent. Actually, I would not even add the fullname to the component name. I'd just go like this:

```yaml
name: {{ template "fullname" . }}-master
labels:
  ...
  component: master
```

2017-08-04 07:00 UTC, unguiculus commented on stable/jenkins/templates/deployment.yaml
> +    matchLabels:
Add `app` and `release` labels to selector.

2017-08-04 07:00 UTC, unguiculus commented on stable/jenkins/templates/networkpolicy.yaml
> +  name: {{ .Release.Name }}-master
Add standard labels.

2017-08-04 07:00 UTC, unguiculus commented on stable/jenkins/templates/networkpolicy.yaml
> +      component: {{ .Release.Name }}-master
Add `app` and `release` labels to selector.

2017-08-04 07:00 UTC, unguiculus commented on stable/jenkins/templates/networkpolicy.yaml
> +---
One file per resource, please.

2017-08-04 07:00 UTC, unguiculus commented on stable/jenkins/templates/service.yaml
> +---
One file per resource, please.

2017-08-04 07:00 UTC, unguiculus commented on stable/jenkins/templates/networkpolicy.yaml
> +metadata:
Add standard labels.

2017-08-04 07:00 UTC, unguiculus commented on stable/jenkins/templates/pvc.yaml
> +    volume.alpha.kubernetes.io/storage-class: default
There's no use in supporting the alpha version any more. Here's an interesting approach for supporting storage classes. I'd suggest you follow it:
https://github.com/kubernetes/charts/pull/1332

2017-08-04 07:00 UTC, unguiculus commented on stable/jenkins/templates/serviceaccount.yaml
> +{{- if .Values.rbac.install }}
@mgoodness has come up with a nice approach for RBAC. We've started suggesting following his example. I'd be great if you did too. See:

https://github.com/kubernetes/charts/pull/1504/files
https://github.com/mgoodness/charts/tree/master/stable/kube2iam

2017-08-04 07:00 UTC, unguiculus commented on stable/jenkins/templates/test.yaml
> +  name: "{{ .Release.Name }}-ui-test-{{ randAlphaNum 5 | lower }}"
Add standard labels.

2017-08-04 07:00 UTC, unguiculus commented
/cc @lachie83 @viglesiasce

2017-08-04 18:07 UTC, binoculars commented
@unguiculus I made the requested changes. I'm still unsure if the ClusterRole is correct. I would appreciate any help there and a good look at the NetworkPolicies.

2017-08-08 19:16 UTC, unguiculus commented
@mgoodness Could you review the RBAC stuff?

2017-08-15 21:58 UTC, binoculars commented
Let me know when you'll be ready to review and I'll rebase it, but feel free to make any changes otherwise.

2017-08-16 03:53 UTC, unguiculus commented
Waiting for the rebase actually. Tests won't run as long as there are conflicts.

2017-08-22 15:24 UTC, evansj commented on stable/jenkins/README.md
>  The suported volume types are: `ConfigMap`, `EmptyDir`, `HostPath`, `Nfs`, `Pod`, `Secret`. Each type supports a different set of configurable attributes, defined by [the corresponding Java class](ht
*supported

2017-08-23 09:53 UTC, unguiculus commented
@binoculars Please fix conflicts.

2017-08-23 15:07 UTC, binoculars commented
@unguiculus Conflicts resolved. I'll be around to make changes if necessary.

2017-08-24 19:28 UTC, unguiculus requested changes

2017-08-24 19:28 UTC, unguiculus commented on stable/jenkins/templates/service.yaml
> +    release: {{ .Release.Name }}
Remove `heritage` and `chart` from selector.

2017-08-24 19:28 UTC, unguiculus commented on stable/jenkins/templates/deployment.yaml
> +        heritage: {{ .Release.Service }}
Remove `chart` and `heritage` from selector.

2017-08-24 19:28 UTC, unguiculus commented on stable/jenkins/templates/service.yaml
> +    heritage: {{ .Release.Service }}
Remove `chart` and `heritage` from selector.

2017-08-24 19:28 UTC, unguiculus commented on stable/jenkins/templates/test.yaml
> +  name: "{{ .Release.Name }}-ui-test-{{ randAlphaNum 5 | lower }}"
Standard labels still missing.

2017-08-24 19:28 UTC, unguiculus commented on stable/jenkins/templates/test-configmap.yaml
> +      curl --retry 12 --retry-delay 10 {{ .Release.Name }}-jenkins:8080{{ default "" .Values.master.uriPrefix }}/login
Add an empty default in `values.yaml`, then you don't need to specify a default here:

`{{ .Values.master.uriPrefix }}`

2017-08-24 19:28 UTC, unguiculus commented on stable/jenkins/templates/test-configmap.yaml
> +      curl --retry 12 --retry-delay 10 {{ .Release.Name }}-jenkins:8080{{ default "" .Values.master.uriPrefix }}/login
Needs standard labels.

2017-08-24 19:28 UTC, unguiculus commented on stable/jenkins/values.yaml
> +  tolerations: {}
`tolerations: []`

2017-08-24 19:28 UTC, unguiculus commented on stable/jenkins/templates/NOTES.txt
> +{{- else if contains "ClusterIP"  .Values.service.type }}
Label selector wrong. Needs `app`, `release`, and `component` labels.

2017-08-24 19:28 UTC, unguiculus commented on stable/jenkins/values.yaml
> +  name: master
You are still keeping the name of the master component configurable. Doesn't make sense to me. Why would you ever change this?

2017-08-28 12:57 UTC, binoculars commented
@unguiculus requested changes made

2017-08-30 20:31 UTC, unguiculus commented
/ok-to-test

2017-08-30 20:42 UTC, lachie83 commented
I'm happy with this change. We should just bump the major version as this will be backwards incompatible. How do we want to handle that? Also can you please take a look at why CI is failing

2017-09-15 12:06 UTC, unguiculus commented
Please fix conflicts and apply suggested changes.

2017-09-28 17:14 UTC, unguiculus commented
@binoculars Any change you can continue with this? I'd really like to get it in.

2017-09-28 18:38 UTC, binoculars commented
@unguiculus yes, it'll take me a bit to resolve the conflicts, but I'll do it soon.

2017-10-09 19:30 UTC, unguiculus commented
@binoculars I have to make this as stale now. Please update it within one week.

2017-10-18 20:02 UTC, unguiculus commented
Closing this as stale now. Feel free to reopen when you decide to work on it again.

2017-10-18 20:02 UTC, closed without merging