Add metabase chart
helm/charts pull request #1617
Opened 2017-08-04 16:16 UTC by pmint93

The helm chart for Metabase

2017-08-07 17:14 UTC, unguiculus requested changes
Thanks for the PR. 

The `app` labels is  inconsistent across resources. Please have a look at our best practices, especially regarding standard labels.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md

2017-08-07 17:14 UTC, unguiculus commented on stable/metabase/templates/secrets.yaml
> +---
One file per resource, please.

2017-08-07 17:48 UTC, pmint93 commented
@unguiculus I've just made a few changes as your request, sorry for my mistake 😄

2017-08-13 17:34 UTC, unguiculus approved these changes

2017-08-13 17:34 UTC, unguiculus commented
/ok-to-test

2017-08-13 17:52 UTC, unguiculus commented
Good work, thanks. Don' be sorry. :wink:

2017-08-13 17:52 UTC, merged