[stable/rocketchat] update to 1.3.1, upgrade mongo to latest helm chart
helm/charts pull request #16321
Opened 2019-08-14 13:10 UTC by verwilst

Signed-off-by: Bart Verwilst <bart@verwilst.be>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-14 13:56 UTC, srueg requested changes

2019-08-14 13:56 UTC, srueg commented on stable/rocketchat/Chart.yaml
>  appVersion: 1.2.3
Please update the `appVersion` accordingly

2019-08-14 14:22 UTC, geekgonecrazy commented
What actual versions of mongo is this moving between?

2019-08-14 14:36 UTC, verwilst commented
Both are 4.0.9, so no changes there.

2019-08-15 06:37 UTC, srueg commented
/lgtm

2019-08-15 06:46 UTC, merged