[sparkoperator]Support configure `batchSchedulerName`
helm/charts pull request #16345
Opened 2019-08-15 08:13 UTC by TommyLike

#### What this PR does / why we need it:

To support configure `batchSchedulerName` in spark operator, this patch depends on [main change](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/567)

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

Depends on: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/567

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-15 08:16 UTC, TommyLike commented
@liyinan926  please take a look

2019-09-03 03:07 UTC, Aisuko requested changes
Thanks for your PR, there may some a piece of advice, please have a look, and don't forget solve the conflict first.

2019-09-03 03:07 UTC, Aisuko commented on incubator/sparkoperator/Chart.yaml
> +version: 0.2.6
Please bump the minor version, like `0.3.0`

2019-09-03 03:07 UTC, Aisuko commented on incubator/sparkoperator/values.yaml
> +batchSchedulerName: ""
Please add the code annotation for `batchSchedulerName `  here can make more sense.

2019-09-05 02:26 UTC, liyinan926 commented
/ok-to-test

2019-09-05 02:31 UTC, TommyLike commented
@liyinan926  please take a look

2019-09-05 04:07 UTC, liyinan926 commented
/retest

2019-09-05 04:08 UTC, liyinan926 commented
/lgtm

2019-09-05 04:18 UTC, merged