incubator/pgadmin
helm/charts pull request #16357
Opened 2019-08-15 16:16 UTC by rowanruseler

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

Created a simple pgadmin helm chart, colleague suggested perhaps get it added to incubator. Apologies if something is incorrect.

2019-08-19 09:05 UTC, cpanato commented
/ok-to-test

2019-08-19 09:13 UTC, cpanato requested changes
please move to `stable` folder

2019-08-19 10:11 UTC, rowanruseler commented
/retest

2019-08-19 10:12 UTC, rowanruseler commented
> please move to `stable` folder

Done, and updated the appVersion cause it was the default one rather then the version of pgadmin.

2019-10-16 07:08 UTC, rowanruseler commented
@cpanato Is there perhaps something missing, or should something be different?

2019-10-16 09:48 UTC, cpanato requested changes

2019-10-16 09:48 UTC, cpanato commented on stable/pgadmin/Chart.yaml
> +version: 0.1.1
should be 
```suggestion
version: 1.0.0
```
since it is in the stable folder and will be the first release

2019-10-16 10:00 UTC, rowanruseler commented
@cpanato sorry about those commits, need to get used to the signoff.

2019-10-16 10:02 UTC, cpanato commented
@rowanruseler no problem you can rebase if you want

2019-10-16 10:07 UTC, cpanato approved these changes
/approve
/lgtm

2019-10-16 10:07 UTC, merged