Add Microsoft OMS linux agent helm chart
helm/charts pull request #1636
Opened 2017-08-07 18:39 UTC by samisms

2017-08-07 19:25 UTC, unguiculus requested changes
Thanks for the PR. Please check our best practices, especially regarding naming resources and labels.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md

Also, see chart examples for reference: https://github.com/kubernetes/helm/tree/master/docs/examples

BTW, `helm create` with Helm 2.5+ creates an initial experience with best practices applied.

2017-08-07 22:46 UTC, samisms commented
@unguiculus Modified chart and template to follow best practices . Please review and let me know if any further changes are required. Thanks.

2017-08-08 19:40 UTC, unguiculus requested changes
* Please check best practices again
* Add missing `_helpers.tpl` and use it

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/Chart.yaml
> +version: 0.1.0
Add `appVersion`. Is there an `icon` you could add?

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/Chart.yaml
> +  - name: OMS Containers
Can you add a github username?

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/README.md
> +- Kubernetes 1.4+ with Beta APIs enabled
Let's make it 1.6+

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/templates/omsagent-daemonset.yaml
> + name: {{ .Values.agentname }}
Should be `{{ template "fullname" . }} `

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/templates/omsagent-daemonset.yaml
> +metadata:
Labels are missing.

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/templates/omsagent-daemonset.yaml
> +   labels:
Only `app` and `release` label should go here.

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/values.yaml
> +    pull_policy: Always
Camel case, please. No underscores.

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/values.yaml
> +# Declare variables to be passed into your templates.
The whole file is incorrectly indented.

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/values.yaml
> +    registry:
Please drop `registry` and use a more common way of specifying image.

```yaml
image:
  repository:
  tag:
  pullPolicy:
```

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/values.yaml
> +    tag: latest
Can you specify a concrete version?

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/templates/omsagent-daemonset.yaml
> +apiVersion: extensions/v1beta1
The file is incorrectly indented.

2017-08-08 19:40 UTC, unguiculus commented on stable/msoms/templates/omsagent-secret.yaml
> +  name: {{ .Values.secretname }}
Don't make it configurable, just use `{{ template "fullname" . }}`

2017-08-08 21:44 UTC, weinong commented on stable/msoms/values.yaml
> +    tag: latest
I'd suggest not to use latest tag especially with pull policy being Always.

2017-08-30 21:14 UTC, unguiculus commented
Marking this as stale. Please update within one week.

2017-09-09 16:24 UTC, unguiculus commented
Closing as stale. Feel free to reopen when/if you decide to work on it again.

2017-09-09 16:24 UTC, closed without merging