Feature/grafana node tolerations
helm/charts pull request #1637
Opened 2017-08-07 18:47 UTC by yagonobre

2017-08-08 17:05 UTC, unguiculus requested changes

2017-08-08 17:05 UTC, unguiculus commented on stable/grafana/templates/deployment.yaml
> +{{ toYaml .Values.server.tolerations | ident 12 }}
Hm, `indent 12` doesn't seem correct. The same goes for `nodeSelector`.

2017-08-08 17:05 UTC, unguiculus commented
/cc @zanhsieh

2017-08-08 17:24 UTC, yagonobre commented on stable/grafana/templates/deployment.yaml
> +{{ toYaml .Values.server.tolerations | ident 12 }}
you are right, changed to 8

2017-08-08 19:19 UTC, unguiculus commented
/ok-to-test

2017-08-09 13:53 UTC, zanhsieh commented
LGTM.

2017-08-09 15:07 UTC, unguiculus commented
Please bump the chart version.

2017-08-09 15:15 UTC, yagonobre commented
Done!

2017-08-13 12:45 UTC, unguiculus commented
/retest

2017-08-13 12:51 UTC, unguiculus approved these changes

2017-08-13 12:51 UTC, merged