[stable/prometheus-adapter] Added pod annotations to chart.
helm/charts pull request #16446
Opened 2019-08-19 22:58 UTC by aaronmell

Upgraded chart to latest version of image

Signed-off-by: Aaron Mell <aaronamell@gmail.com>

#### What this PR does / why we need it:
I needed to add some pod annotations, which the chart doesn't support. Also, the version was outdated.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-20 07:23 UTC, winromulus commented
/ok-to-test

2019-08-20 18:59 UTC, steven-sheehy requested changes

2019-08-20 18:59 UTC, steven-sheehy commented on stable/prometheus-adapter/Chart.yaml
> +version: v1.2.1
`1.3.0` for new features. And drop the `v` for consistency with past releases.

2019-08-20 18:59 UTC, steven-sheehy commented on stable/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml
> +{{ toYaml . | indent 8 }}
Use nindent like the rest of the file and align to be under `checksum/config`

2019-08-22 14:01 UTC, aaronmell commented
@steven-sheehy Code review changes made

2019-08-22 15:09 UTC, steven-sheehy commented
/lgtm
Thanks!

2019-08-22 15:26 UTC, merged