[stable/traefik] Updated acme storage location to be configurable
helm/charts pull request #16464
Opened 2019-08-20 19:56 UTC by ryaneorth

Signed-off-by: Ryan Orth <ryanorth@workfront.com>

#### What this PR does / why we need it:
This change allows users for the traefik chart to specify a custom storage location for acme data in the KV store of their choosing. This is necessary in the situation where you are using the same kv store instance for multiple instances of traefik.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-20 20:02 UTC, ryaneorth commented
/assign @jbdoumenjou

2019-08-20 20:04 UTC, ryaneorth commented
/assign @dtomcej

2019-08-21 15:09 UTC, ryaneorth commented
hey @dtomcej - could you take a look at this PR when you get the chance? Thank you!

2019-08-22 20:35 UTC, ryaneorth commented
@emilevauge - could you look at this pull request? thanks!

2019-08-26 01:48 UTC, ryaneorth commented
poke @emilevauge or @dtomcej . could one of you take a look at these proposed changes when you get the chance? Thanks!

2019-08-30 09:07 UTC, dtomcej requested changes

2019-08-30 09:07 UTC, dtomcej commented on stable/traefik/templates/configmap.yaml
> +    storage = "{{ .Values.kvprovider.acmeStorageLocation }}"
How does this interact with `kvprovider.$name.prefix`?

2019-09-06 14:00 UTC, ryaneorth reviewed
@dtomcej what are your thoughts on my response to your question?

2019-09-06 14:00 UTC, ryaneorth commented on stable/traefik/templates/configmap.yaml
> +    storage = "{{ .Values.kvprovider.acmeStorageLocation }}"
I'm not 100% sure what you mean by "interact", but in my personal case I do not have them set to the same value. For example, if I set `kvprovider.acmeStorageLocation` to traefik "foo" and the `kvprovider.consul.prefix` to "bar" I seem to achieve the expected results. Specifically the certs are stored in "bar" and all the configuration information for the traefik controller is stored with the prefix "foo".

If you set them to the same value it will likely cause problems, however.

2019-09-09 19:03 UTC, dtomcej commented on stable/traefik/templates/configmap.yaml
> +    storage = "{{ .Values.kvprovider.acmeStorageLocation }}"
Gotcha. Seems legit to me.

2019-09-09 19:03 UTC, dtomcej commented
/ok-to-test

2019-09-11 20:04 UTC, ryaneorth commented
@dtomcej - you good with approving this change?

2019-09-11 20:55 UTC, dtomcej commented
Hey @ryaneorth,

Just needs a rebase + chart version bump to 🚢 

Thanks!

2019-09-11 21:28 UTC, ryaneorth commented
@dtomcej done!

2019-09-11 21:46 UTC, dtomcej commented
/lgtm

2019-09-11 21:48 UTC, merged