Add tensorflow inception model to incubator
helm/charts pull request #165
Opened 2016-10-28 17:19 UTC by lachie83

2016-10-30 00:22 UTC, chrislovecnm requested changes
Looks great, couple of requests

2016-10-30 00:22 UTC, chrislovecnm commented on incubator/tensorflow-inception/templates/tensorflow-inception.yaml
> +              memory: "{{.Values.Memory}}"
Can we get limits as well, there are examples of using a dict with toyaml

2016-10-30 00:22 UTC, chrislovecnm commented on incubator/tensorflow-inception/values.yaml
> +ImageTag: "latest"
Personally not a fan of latest ;) will defer to who merges the PR. I have had production failures because latest was not tested on k8s.

2016-10-30 00:26 UTC, chrislovecnm commented
Can we get ready and liveliness probes as well please

2016-10-30 03:52 UTC, lachie83 commented on incubator/tensorflow-inception/templates/tensorflow-inception.yaml
> +              memory: "{{.Values.Memory}}"
Sure. Shall I just have the request and the limits equal the same thing? I've dug around on the tensorflow documentation and haven't found any recommendations to use as a guide.

2016-10-30 03:54 UTC, lachie83 commented on incubator/tensorflow-inception/values.yaml
> +ImageTag: "latest"
I totally agree. I initially wanted to use the published containers in the original documentation but they don't work currently. Let me work with @viglesiasce to see if we can 't find a better home for this. I will most probably tag it v3 as that's the inception model it's serving.

2016-10-30 03:55 UTC, lachie83 commented
Thanks for reviewing @chrislovecnm. Great feedback!

2016-10-30 16:02 UTC, chrislovecnm commented on incubator/tensorflow-inception/templates/tensorflow-inception.yaml
> +              memory: "{{.Values.Memory}}"
Not surprised.  Start small :)

2016-10-31 05:46 UTC, lachie83 commented on incubator/tensorflow-inception/templates/tensorflow-inception.yaml
> +              memory: "{{.Values.Memory}}"
Complete

2016-10-31 05:48 UTC, lachie83 commented
Added readiness as tcpSocket check. I suggest we just use the process running as "liveliness" unless there is a better suggestion

2017-01-13 05:48 UTC, viglesiasce commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.kubernetes.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/charts/165)
<!-- Reviewable:end -->

2017-01-25 23:28 UTC, bgrant0607 commented
@jlewi

2017-02-03 19:23 UTC, merged