[stable/atlantis] Allow google service accounts to be passed as kubernetes secrets
helm/charts pull request #16515
Opened 2019-08-21 16:32 UTC by kpurdon

#### What this PR does / why we need it:

This is intended to replace the functionality of
`serviceAccountSecrets` providing a slightly more secure and standard
way of authenticating to google with service accounts. This pattern
mostly follows
https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform
and provides significantly more documentation than the previous solution.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-21 17:18 UTC, kpurdon commented
/assign @lkysow

2019-08-21 17:36 UTC, kpurdon commented
I was able to test and validate this on my own deployment. Please let me know if there is any other useful validation I can do or if you'd like me to provide any information about my validation.

2019-08-22 10:20 UTC, lkysow requested changes

2019-08-22 10:20 UTC, lkysow commented on stable/atlantis/values.yaml
> +#
Can you remove these newlines.

2019-08-22 10:20 UTC, lkysow commented on stable/atlantis/values.yaml
> +# Once included here you must update your terraform google provider configuration to include:
I don't think this should be in the docs for the helm chart. Not everyone will be using Terraform and this will confuse them.

2019-08-22 10:20 UTC, lkysow commented on stable/atlantis/values.yaml
> +# If you are using the GCS backend you may additionally want to update that to include the credentials:
Same for this

2019-08-26 17:17 UTC, lkysow commented
/lgtm

2019-08-26 17:26 UTC, merged