[stable/sonatype-nexus] adding ACM cert support when using LoadBalancer service type
helm/charts pull request #16577
Opened 2019-08-22 17:04 UTC by danielwhatmuff

#### What this PR does / why we need it:

Adds ability to specify an AWS ACM certificate to provide SSL for the Nexus server.

#### Special notes for your reviewer:

Let me know if anything else is required/missing for this @rjkernick @tsiddique

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-29 15:26 UTC, rjkernick requested changes

2019-08-29 15:26 UTC, rjkernick commented on stable/sonatype-nexus/Chart.yaml
> +version: 1.19.1
Please bump the minor version as this adds features

2019-08-29 15:26 UTC, rjkernick commented on stable/sonatype-nexus/values.yaml
> +  annotations:
Don't we want the "{}" to remain the default?

2019-08-29 15:26 UTC, rjkernick commented
/ok-to-test

2019-09-04 15:22 UTC, danielwhatmuff commented on stable/sonatype-nexus/values.yaml
> +  annotations:
Yes, done

2019-09-04 15:22 UTC, danielwhatmuff commented on stable/sonatype-nexus/Chart.yaml
> +version: 1.19.1
Done

2019-09-10 12:25 UTC, rjkernick commented
Please fix the DCO: https://github.com/helm/charts/pull/16577/checks?check_run_id=212032508

2019-09-10 12:25 UTC, rjkernick commented
/assign

2019-10-10 19:11 UTC, zanhsieh commented
@rjkernick 
Could you approve this please? Thank you.

2019-10-14 17:24 UTC, rjkernick commented
It doesn't look like either change was made from the review. Only the patch version is changed, and the {} are no longer the default value.

2019-10-14 17:48 UTC, danielwhatmuff commented
Apologies. I will get on this soon.

2019-10-21 09:05 UTC, danielwhatmuff commented
> It doesn't look like either change was made from the review. Only the patch version is changed, and the {} are no longer the default value.

Both done.

2019-10-22 13:58 UTC, rjkernick commented
/lgtm

2019-10-22 14:23 UTC, merged