[stable/redis] Adapt redis exporter initialization as it doesn't support REDIS_PASSW…
helm/charts pull request #16613
Opened 2019-08-26 13:04 UTC by miguelaeh

…ORD_FILE anymore

#### What this PR does / why we need it:
The Redis exporter does not support anymore the REDIS_PASSWORD_FILE en var so this PR patches the redis_exporter initialization to support it.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #16049

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-08-26 13:07 UTC, miguelaeh commented
/assign javsalgar

2019-08-26 13:07 UTC, miguelaeh commented
/assign juan131

2019-08-26 13:08 UTC, miguelaeh commented
/assign @carrodher

2019-08-27 08:39 UTC, carrodher commented on stable/redis/README.md
> +## Using password file
IMHO we should include this section inside the `## Configuration` section, adding another level (`###`) and moving it to the below section

2019-08-27 08:40 UTC, alemorcuq requested changes

2019-08-27 08:40 UTC, alemorcuq commented on stable/redis/templates/redis-master-statefulset.yaml
> +           password_aux-`cat /secret/redis-password`
You don't need an aux variable here. Also, using `$()` is preferred instead of using backticks.

2019-08-27 08:40 UTC, alemorcuq commented on stable/redis/templates/redis-slave-statefulset.yaml
> +           password_aux-`cat /secrets/redis-password`
Same as before.

2019-08-27 09:14 UTC, alemorcuq requested changes

2019-08-27 09:14 UTC, alemorcuq commented on stable/redis/templates/redis-master-statefulset.yaml
> +           export REDIS_PASSWORD=$(cat /secret/redis-password)
Wrong path the file. Should be `/secrets/...`

2019-08-27 11:39 UTC, carrodher commented
/ok-to-test
/lgtm

2019-08-27 12:14 UTC, merged