Spartakus - static container name
helm/charts pull request #168
Opened 2016-10-28 20:34 UTC by mgoodness

My company aggregates container logs by container name, with each stream named after the pod itself. Naming both the pod & the container dynamically based on the release name breaks that pattern between different deployments.

2016-10-30 00:17 UTC, chrislovecnm commented
@k8s-bot ok to test

2016-10-30 00:17 UTC, chrislovecnm approved these changes
LGTM

2016-10-30 00:18 UTC, chrislovecnm commented
Let me take that back ;) can we make that the default, or when defined is the name??

2016-10-30 16:04 UTC, chrislovecnm requested changes
Can we get spartakus, or the template name?

2016-10-31 02:01 UTC, mgoodness commented
I've created a `containerName` variable that, if set, will be used as the container's name in the pod. Otherwise, the existing `{{ template fullname . }}` behavior will be used. @chrislovecnm, I _think_ that's what you requested.

However, I don't really like this default. As I explained in the PR, there is value in having consistent container names between deployments, and I think that should be the out-of-the box behavior. I'm going to propose it as a best practice. Does templating the container name yield any particular benefit?

2016-10-31 16:36 UTC, viglesiasce commented
I prefer consistent container names. It helps in live as well as after-the-fact debugging.

2016-11-01 16:42 UTC, prydonius commented
> I'm going to propose it as a best practice.

+1, I thinks this makes sense

2016-11-02 06:48 UTC, sameersbn commented on stable/spartakus/templates/deployment.yaml
> +        - name: {{ if .Values.containerName }}"{{ .Values.containerName }}"{{ else }}{{ template "fullname" . }}{{ end }}
sugeestion: add a helper function in `templates/_helpers.tpl`

2016-11-02 11:31 UTC, mgoodness commented
Based on feedback, I've reverted to a static container name (default `spartakus`) that can be overridden by `.Values.containerName`. I believe this is the best approach.

2016-11-02 17:14 UTC, prydonius commented on stable/spartakus/templates/deployment.yaml
> +        - name: {{ default "spartakus" .Values.containerName | quote }}
You could use `.Chart.Name`? or `{{ template "name" . }}` which already uses `.Values.nameOverride` for overriding.

2016-11-02 17:14 UTC, prydonius commented
@mgoodness this is really great feedback. Given that all charts are currently using the current `app=goofy-gus-<name>` pattern, can you bring it up for discussion in the [best practices](https://github.com/kubernetes/charts/issues/44) or a separate issue?

2016-11-02 18:27 UTC, prydonius commented
@k8s-bot e2e test this

2016-11-02 18:33 UTC, prydonius commented
thanks @mgoodness, all looks good to me. Ok to merge?

2016-11-02 18:53 UTC, mgoodness commented
@prydonius please do! I'll take my bigger ideas over to the best-practices issue

2016-11-02 19:00 UTC, prydonius commented
Thanks a lot @mgoodness!

2016-11-02 19:00 UTC, merged