[stable/postgresql] Allow setting the mount path of initdb scripts
helm/charts pull request #16914
Opened 2019-09-06 07:24 UTC by mwalser

#### What this PR does / why we need it:
Some PostgreSQL images such as TimescaleDB are shipping with initdb scripts in /docker-entrypoint-initdb.d/. Using the same directory as mountPath results in these scripts being shadowed.

This change makes it possible to specify a different mount path (for example /docker-entrypoint-initdb.d/helm/) so that these scripts can coexist.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-09-06 12:52 UTC, juan131 reviewed
Hi @mwalser 

Thanks so much for the PR! 

What are the reasons to allow modifying this **mountPath** for initdb scripts? Are you using the Bitnami image? Please note this image expects the initdb scripts at that specific path.

2019-09-06 13:31 UTC, mwalser commented
Hi @juan131 

Thank you for the fast reply.

The reason adding this is that currently the path of the ConfigMap mount is fixed to /docker-entrypoint-initdb.d/.
This wouldn't be a problem, but the TimescaleDB docker image (based on bitnami/postgresql) already contains some initialization scripts: https://github.com/timescale/timescaledb-docker/tree/master/docker-entrypoint-initdb.d

When we now use the initdb feature of the helm chart only the initdb scripts are visible in /docker-entrypoint-initdb.d/. The preexisting files (000_install_timescaledb.sh, 001_reenable_auth.sh and 002_timescaledb_tune.sh) are inaccessible.

This pull request adds the ability to specify a custom mount path, e.g. /docker-entrypoint-initdb.d/helm/. This enables a coexistence of the already existing files and those from the helm chart.

2019-09-09 07:39 UTC, juan131 commented
Thanks for the detailed explanation. It makes total sense.

> This pull request adds the ability to specify a custom mount path, e.g. /docker-entrypoint-initdb.d/helm/. This enables a coexistence of the already existing files and those from the helm chart.

Just a question. How are you supposed to run these new scripts during the initialization? I mean, the current logic (the one at Bitnami PostgreSQL image) won't detect your custom scripts (it'll only detect the ones included in the TimescaleDB docker image) and therefore, you need to find a way to execute them

2019-09-09 11:44 UTC, mwalser commented
Hi @juan131 

I'm not sure I understand your question.

When the initdb scripts are mounted in `/docker-entrypoint-initdb.d/some-custom-directory/` they are going to be found by this script https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/centos-7/rootfs/libpostgresql.sh#L580

There is no maxdepth option specified in the find command so it will decend into the custom subdirectory.

The directory layout would look like this:
```
/docker-entrypoint-initdb.d/000_install_timescaledb.sh
/docker-entrypoint-initdb.d/001_reenable_auth.sh
/docker-entrypoint-initdb.d/002_timescaledb_tune.sh
/docker-entrypoint-initdb.d/some-custom-directory/some-initdb-script.sql
/docker-entrypoint-initdb.d/some-custom-directory/other-initdb-script.sql
```

2019-10-01 08:06 UTC, juan131 requested changes

2019-10-01 08:06 UTC, juan131 commented on stable/postgresql/values.yaml
> +
Could you do the same change in the **values-production.yaml**?

2019-10-01 08:07 UTC, juan131 commented
> There is no maxdepth option specified in the find command so it will decend into the custom subdirectory.

You're right! Thanks so much again for the explanation.

Please rebase your branch from master to avoid the conflicting issues.

2019-11-01 13:50 UTC, zanhsieh commented
@mwalser 
Would you mind to resolve conflicting files please?
stable/postgresql/Chart.yaml
stable/postgresql/README.md
stable/postgresql/templates/statefulset.yaml

2019-12-02 13:01 UTC, carrodher commented
Sorry, I just saw the stale bot notification.
Yes, you should fix the existing conflicts in the following files:
```
stable/postgresql/Chart.yaml
stable/postgresql/README.md
stable/postgresql/templates/statefulset.yaml
```
In the same way, as @juan131 suggested, can you add the same change in the _values-production.yaml_?

2019-12-08 19:05 UTC, mwalser commented
Sorry, for the late answer. It was a bit of a stressful time. I'm not sure anymore the solution I proposed is the right way to go. While it might solve my specific problem it feels very hacky.

I thought about changing this merge request to always put the initdb scripts into a subfolder. But while this might work with the bitnami based images it will not on the official postgres docker image. So this is no way forward.

The next thought I had was to abandon the idea of letting the user specify the initdb script path via `initdbScriptsMountPath` and to just introduce a boolean `initdbScriptsUseSubfolder` (which would default to false). IMHO this feels slightly less hacky.

Do you have any opinions on this?

2020-01-21 20:23 UTC, closed without merging