[stable/sentry] Bump dependencies and allow dependency naming
helm/charts pull request #16996
Opened 2019-09-09 16:15 UTC by paroxp

#### Is this a new chart
No

#### What this PR does / why we need it:

These charts have been updated a lot, since we've introduced
these dependencies.

It mainly introduces new version of Postgres and doesn't seem to break
the general functionality. It does introduce some template changes and
fixes a single problem, where policy has an empty value and causes
kubernetes to fall out in persistant volume claim.

```yaml
  annotations:
    "helm.sh/resource-policy":
```

We can also benefit from not having Persistent Volumes.

Whilst being here, it would be nice to bump redis too.

On separate note:

It may be a case, when a user would like to install two different
instances of postgres or redis in the same namespace with a single
release. This would cause one of the instances being overwritten by the
other and lead to unwanted behaviour.

Adding this support and prefixing sentry's dependencies, may solve that
problem, and doesn't really strike as a bad practice.

#### Special notes for your reviewer:

Only briefly tested.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-09-09 18:56 UTC, okgolove commented
Hi @paroxp!
I'd bump the chart version to 3.0.0 because the changes brake compatibility.

Have you the chart tested with new requirements?

2019-09-09 20:52 UTC, paroxp commented
Hey @okgolove,

I've bumped the version.

I have tested the chart. But not to the fullest. (Issues with my cluster not related to the chart). 

It would appear, it's all scheduling up correctly, independently running. I didn't however see the full Sentry running as I got into the rabbit hole of doom not related :D 

I'll try to run it somewhere, but it may be quicker for you to run it 🤔 

I fully expect it to carry on working, as per https://github.com/getsentry/sentry/issues/12673

2019-09-20 05:23 UTC, admorphit requested changes
Picked up some `postgresql` typos.

2019-09-20 05:23 UTC, admorphit commented on stable/sentry/values.yaml
> +  # postgressqlPort: 5432
```suggestion
  # postgresqlPort: 5432
```

2019-09-20 05:23 UTC, admorphit commented on stable/sentry/values.yaml
> +  # postgressqlPassword: postgres
```suggestion
  # postgresqlPassword: postgres
```

2019-09-20 05:23 UTC, admorphit commented on stable/sentry/values.yaml
> +  # postgressqlHost: postgres
```suggestion
  # postgresqlHost: postgres
```

2019-09-20 09:08 UTC, paroxp commented
Nice catch! 😱 

Also resolved some conflicts.

2019-10-19 19:45 UTC, zanhsieh commented
@paroxp 
Would you bump the chart version to latest please?

2019-10-20 10:37 UTC, paroxp commented
hey @zanhsieh, bumped it now.

2019-10-20 10:41 UTC, okgolove commented
/ok-to-test

2019-10-20 11:13 UTC, okgolove commented
As you can see something is going wrong.

2019-10-20 11:27 UTC, paroxp commented
Sure. I've had a brief look into this, and to be honest I'm not sure what's wrong or if it's even related...

It seems like it fails to run the migrations. It starts with:

> FATAL ERROR - The following SQL query failed: CREATE EXTENSION IF NOT EXISTS citext

If I run that docker image locally and `psql` into it, the above command works just fine...

I know that THIS CHANGE introduced it, but I'm lost as to where to look for clues :O

2019-10-20 11:44 UTC, paroxp commented
/test pull-charts-e2e

2019-10-20 12:01 UTC, okgolove commented
/retest

2019-10-20 12:03 UTC, paroxp commented
The last run succeeded. I've changed the `postgresUsername` from `sentry` to `postgres`... Will update the README and I think it's ready?

2019-10-20 12:20 UTC, paroxp commented
OK. I'm done here. Sorry if you started the tests before I made my change :(

Just waiting for the two flags :)

2019-10-20 12:30 UTC, okgolove commented
/retest

2019-10-20 12:33 UTC, okgolove commented
/lgtm

2019-10-20 12:35 UTC, merged

2019-11-14 03:19 UTC, ianks commented
This commit caused our deployment to break. `sentry-postgresql ` became `sentry-sentry-postgresql`, same with redis.

2019-11-14 03:34 UTC, ianks commented
@paroxp i think i can set `nameOverride: postgresql` for it to be fixed, but would this cause teh current instance of postgres to be overwritten?

2019-11-14 05:21 UTC, ianks commented
also just realize, all of the vars were renamed without warning... `postgresHost` vs `postgresqlHost`