New resource vpa for deployment controller resources
helm/charts pull request #17034
Opened 2019-09-10 10:34 UTC by santinoncs

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-09-10 10:40 UTC, santinoncs commented
/assign @taharah

2019-09-11 02:39 UTC, taharah requested changes
Isn't the `VerticalPodAutoscaler` CRD definition missing? As it stands, the values for the VPA definition are just being defined, but not utilized anywhere.

2019-09-11 02:39 UTC, taharah commented on stable/nginx-ingress/Chart.yaml
> +version: 1.20.1
This should be bumped to `1.21.0` now since another PR was merged earlier today.

2019-10-11 11:22 UTC, santinoncs commented
/assign @taharah

2019-10-11 16:39 UTC, ChiefAlexander commented on stable/nginx-ingress/Chart.yaml
> +version: 1.24.4
as this is a new feature this version should be `1.25.0`

2019-10-17 17:33 UTC, closed without merging