[stable/minio] Migrate MinIO chart to the newest version of Kubernetes API
helm/charts pull request #17072
Opened 2019-09-11 14:57 UTC by michal-hudy

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

 - Migrated MinIO chart to the newest version of Kubernetes API
 - Implemented pods recreation when secret/config is changed
 - Added accessKey/secretKey generation when not provided

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-09-11 15:05 UTC, michal-hudy commented
/assign @nitisht

2019-09-12 09:52 UTC, nitisht requested changes

2019-09-12 09:52 UTC, nitisht commented on stable/minio/templates/secrets.yaml
>  {{- if .Values.gcsgateway.enabled }}
IMO this is not needed, MinIO will automatically create credentials if not supplied.

2019-09-12 09:52 UTC, nitisht commented on stable/minio/Chart.yaml
> +version: 2.5.14
This can be a major release (`3.0.0`)

2019-09-12 09:52 UTC, nitisht commented on stable/minio/templates/statefulset.yaml
> +{{- if .Values.podAnnotations }}{{ toYaml .Values.podAnnotations | indent 8 }}{{- end }}
not clear why these new `annotations` are needed

2019-09-12 10:32 UTC, hudymi commented on stable/minio/templates/secrets.yaml
>  {{- if .Values.gcsgateway.enabled }}
O! I didn't know about that, can you point me to the documentation. Also, how can I get generated credentials in a cluster environment? If it is in secret I can just inject that secret to other resources, when it is generated by MinIO then we will lose that functionality :(

2019-09-12 10:37 UTC, hudymi commented on stable/minio/templates/statefulset.yaml
> +{{- if .Values.podAnnotations }}{{ toYaml .Values.podAnnotations | indent 8 }}{{- end }}
OK, so if for example, you want to change password or configuration in helm values/resources then pods are not recreated, because from Deployment/StatefulSet CR point of view nothing change. But if you inject secret/configmap sha in annotation then that value is calculated during applying to the cluster and if something change then pods are recreated. See https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change

2019-09-12 10:58 UTC, hudymi commented on stable/minio/templates/secrets.yaml
>  {{- if .Values.gcsgateway.enabled }}
Ok, found documentation ;) From more than one year I was using MinIO with my passwords, so forgot about it. Anyway, the problem with accessing and injecting accessKey/secretKey in cluster env will stay if these values will not be stored in secret :(.

2019-09-16 15:34 UTC, nitisht commented
/ok-to-test

2019-09-17 01:39 UTC, nitisht commented
/lgtm

2019-09-17 01:50 UTC, merged