[stable/falco]: Restrict the access to /dev on underlying host to rea…
helm/charts pull request #17101
Opened 2019-09-12 20:39 UTC by farshad-hobsons

#### What this PR does / why we need it:
This PR improves the security posture of falco container itself by only allowing readOnly access to `/dev` on underlying host. Following the [least-privilage access principle](https://en.wikipedia.org/wiki/Principle_of_least_privilege) is a nice to have, especially for a security tool itself.

#### Special notes for your reviewer:
I tested this change locally on minikube. Falco container was able to correctly load kernel modules and start cleanly. I also tested the detection by falco when a privileged container is spawned.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-09-13 08:48 UTC, bencer commented
I would feel more comfortable getting this merged into upstream first.

https://github.com/falcosecurity/falco/blob/dev/integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml#L34

2019-09-13 13:43 UTC, farshad-hobsons commented
> I would feel more comfortable getting this merged into upstream first.
> 
> https://github.com/falcosecurity/falco/blob/dev/integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml#L34

Upstream PR https://github.com/falcosecurity/falco/pull/834

2019-10-08 15:04 UTC, farshad-hobsons commented
@bencer - fyi - upstream is merged

2019-10-08 15:13 UTC, nestorsalceda commented
/ok-to-test

2019-10-08 15:13 UTC, nestorsalceda requested changes

2019-10-08 15:13 UTC, nestorsalceda commented on stable/falco/CHANGELOG.md
> +## v1.0.8
Add a whiteline here, on top of version number.

2019-10-09 18:52 UTC, farshad-hobsons commented
Apologies @nestorsalceda & @ryanaross - Since there were new falco-chart changes since my original changes/pr, I did a rebase and in the process corrupted this PR. I will close this PR and open a new one.

2019-10-09 18:52 UTC, closed without merging