[stable/prometheus-pushgateway] Add configurable ServiceMonitor
helm/charts pull request #17140
Opened 2019-09-15 09:37 UTC by edolinsky

#### What this PR does / why we need it:
This PR fixes a bug in which ServiceMonitors scrape all releases, regardless of whether those releases have ServiceMonitors enabled. Instead, a flexible selector configuration is introduced with the default selector matching only the service in the same release as the selector itself.

I've also done some minor cleanup in the ServiceMonitor.

#### Which issue this PR fixes
  - fixes #17138 
  - changes the `serviceMonitor.selector` variable so that it applies to the serviceMonitor's selector, not its labels. `serviceMonitor.labels` has been added, and are merged into the defaultLabels and applied to the serviceMonitor
  - removes `serviceMonitor.namespace`, which (unless I'm mistaken) does not provide functionality, and breaks the [technical requirement](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#technical-requirements) that the chart must launch with default values; the current default causes the chart to break if the `monitoring` namespace does not exist.
  - minor cleanup on the `serviceMonitor.interval` variable's default value

#### Special notes for your reviewer:
* Version bumped to `1.0.3` so as to not conflict with #17128 which is related.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-09-15 09:39 UTC, edolinsky commented
/assign @gianrubio

2019-10-15 15:37 UTC, zanhsieh commented
/ok-to-test

2019-11-08 09:57 UTC, cstaud requested changes

2019-11-08 09:57 UTC, cstaud commented on stable/prometheus-pushgateway/values.yaml
> +  interval: ''
Wouldn't it be better to provide the default value here? I guess its `10s`

2019-12-06 22:28 UTC, edolinsky commented
Sorry I haven't gotten back to this; looks like the functionality I needed has been implemented in the time since I opened this PR, so I'm going to close it.

Thanks for taking up the maintainer mantle @cstaud !

2019-12-06 22:28 UTC, closed without merging