[stable/airflow] Added option to mount dag volume as read-only in web deployment
helm/charts pull request #17210
Opened 2019-09-18 12:46 UTC by michieldhadamus

**What this PR does / why we need it:**
By default, webserver can write to dag volumes (and edit dags). We want to avoid this behaviour by mounting the dags volume as read-only. Compilation of dag.py to dag.pyc will be done by scheduler.

**Checklist**
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

 [x] DCO signed
 [x] Chart Version bumped
 [x] Variables are documented in the README.md
 [x] Title of the PR starts with chart name (e.g. [stable/chart])

2019-10-18 23:54 UTC, zanhsieh commented
@michieldhadamus 
Would you mind to resolve the conflict file please? stable/airflow/Chart.yaml

2019-10-19 10:26 UTC, michieldhadamus commented
@zanhsieh, resolved merge conflict

2019-10-19 14:18 UTC, zanhsieh commented
/ok-to-test

2019-12-07 19:47 UTC, davidkarlsen requested changes

2019-12-07 19:47 UTC, davidkarlsen commented on stable/airflow/templates/deployments-web.yaml
> +              readOnly: { .Values.web.dagsReadOnly }
typo

2019-12-09 10:10 UTC, closed without merging

2019-12-09 10:11 UTC, michieldhadamus commented
Messed up commit signing, will make a new PR later