[stable/mongodb] Feature: explicit service name
helm/charts pull request #17287
Opened 2019-09-20 09:37 UTC by cspengl

#### What this PR does / why we need it:

This PR adds the option to define a hard coded service name. This isn't a good practice in general but can be quite useful for special scenarios. (Referring to [Helm Chart Best Practices](https://github.com/helm/helm/blob/master/docs/chart_best_practices/templates.md#resource-naming-in-templates).
In this case it could be useful to have a "release-independent" service name to tell other applications where to connect with the database. The option is disabled per default and everything works like before - just an additional option.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-09-23 06:39 UTC, cspengl commented
/assign @carrodher

2019-09-23 07:49 UTC, miguelaeh requested changes
Thank you very much for the PR @cspengl !!!!!!!
Please take a look to my comments.

2019-09-23 07:49 UTC, miguelaeh commented on stable/mongodb/Chart.yaml
> +version: 7.2.9
Should bump the minor version as you are including a new feature.

2019-09-23 07:49 UTC, miguelaeh commented on stable/mongodb/templates/svc-headless-rs.yaml
> +  name: {{ template "mongodb.serviceName" . }}-headless
Why do you need to change the headless service too?

2019-09-23 07:49 UTC, miguelaeh commented on stable/mongodb/templates/_helpers.tpl
> +in the values file. If the name is set not explicitly it will take the "mongodb.fullname"
```diff
- If the name is set not explicitly
+ If the name is not explicitly set
```

2019-09-23 07:49 UTC, miguelaeh commented on stable/mongodb/values.yaml
> +  ## Specify an explicit service name. This is not recommended in general and therefore
Remove this part of the comment as it is already explained in the `_helpers.tpl` 
```diff 
- ## Specify an explicit service name. This is not recommended in general and therefore
- ## disabled by default. The service name will be set to the fullname of the chart.
+ ## Specify an explicit service name.
```

2019-09-23 15:32 UTC, cspengl commented
Thank you very much for your feedback @miguelaeh !
I am completely fine with the changes you suggested. I will change the code to match your suggestions. Regarding the name of the headless service - I just wanted to hold the service names consistent. When you see any advantages or disadvantages for one of the options please let me know.

2019-10-02 07:55 UTC, miguelaeh approved these changes
Thanks for address the changes!!!

2019-10-02 07:56 UTC, miguelaeh commented
/ok-to-test
/lgtm

2019-10-07 06:24 UTC, miguelaeh commented
/ok-to-test
/lgtm

2019-10-07 06:31 UTC, merged