[stable/cluster-autoscaler] remove sslCertPath host mapping
helm/charts pull request #17322
Opened 2019-09-20 20:26 UTC by steved

The certificates were added in https://github.com/kubernetes/autoscaler/pull/11#discussion_r113791551 and it shouldn't be necessary to reference the host itself.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-09-20 20:27 UTC, steved commented
/assign @yurrriq

2019-09-21 01:54 UTC, yurrriq requested changes
Thanks for this. According to https://github.com/kubernetes/autoscaler/pull/48/commits/be88af64d4f62213a99328c1e8276a506a381d06 this has been unnecessary since cluster-autoscaler-0.6.0

2019-09-21 01:54 UTC, yurrriq commented on stable/cluster-autoscaler/templates/deployment.yaml
>              {{- if eq .Values.cloudProvider "gce" }}
Will you please adjust this so we don't set `volumeMounts: null` when `ne .Values.cloudProvider "gce"`?

2019-09-21 01:54 UTC, yurrriq commented on stable/cluster-autoscaler/templates/deployment.yaml
>          {{- if eq .Values.cloudProvider "gce" }}
Will you please adjust this, so we don't set `volumes: null` when `ne .Values.cloudProvider "gce"`?

2019-09-21 21:24 UTC, yurrriq commented on stable/cluster-autoscaler/templates/podsecuritypolicy.yaml
> -    - pathPrefix: {{ .Values.sslCertHostPath }}
Same here. Will you please adjust so we don't set `allowedHostPaths: null`?

2019-09-23 18:57 UTC, yurrriq approved these changes
LGTM thanks!

2019-09-23 18:58 UTC, yurrriq commented
Looks like there's just a conflict with `Chart.yaml` now.

2019-09-23 19:01 UTC, yurrriq commented
If you rebase after https://github.com/helm/charts/pull/17273 gets merged, then we can merge this one. Thanks!

2019-09-23 19:29 UTC, steved commented
Done, thanks!

2019-09-24 02:49 UTC, yurrriq commented
Thanks!

2019-09-24 02:49 UTC, yurrriq commented
/approve

2019-09-24 02:50 UTC, yurrriq commented
/ok-to-test

2019-09-24 02:51 UTC, yurrriq commented
/lgtm

2019-09-24 02:57 UTC, merged

2019-09-24 14:38 UTC, InAnimaTe commented
@steved It doesn't seem you updated the README as it still shows `sslCertHostPath` and its not optional. For me, I have it changed to `sslCertHostPath: "/etc/ssl/certs/ca-bundle.crt"`as EKS AMI's have a different bundle location. Does this PR mean that this value is now completely irrelevant then?

2019-09-24 16:43 UTC, yurrriq commented
Yeah, since [cluster-autoscaler-1.6.0](https://github.com/kubernetes/autoscaler/commit/be88af64d4f62213a99328c1e8276a506a381d06) this should be irrelevant. Could someone please open an MR to update the README? If I do it, I can't merge it :)

2019-09-24 16:51 UTC, steved commented
https://github.com/helm/charts/pull/17406 sorry about that!

2019-09-24 16:57 UTC, yurrriq commented
Thanks!