[stable/falco] migrate API versions from deprecated, removed versions
helm/charts pull request #17339
Opened 2019-09-22 01:59 UTC by oke-py

Signed-off-by: Naoki Oketani <okepy.naoki@gmail.com>

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

NO
#### What this PR does / why we need it:
In k8s v1.16 some APIs are deprecated and removed.
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

As a result, installation failed. I migrate to use supported API versions.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #17338

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-09-22 02:00 UTC, oke-py commented
/assign @nestorsalceda

2019-10-07 09:09 UTC, nestorsalceda requested changes

2019-10-07 09:09 UTC, nestorsalceda commented on stable/falco/CHANGELOG.md
> +* migrate API versions from deprecated, removed versions to support Kubernetes v1.16
Capitalize migrate word

2019-10-07 10:18 UTC, oke-py commented on stable/falco/CHANGELOG.md
> +* migrate API versions from deprecated, removed versions to support Kubernetes v1.16
@nestorsalceda I fixed it.

2019-10-07 10:19 UTC, oke-py commented
There are 2 conflicting files.
Should I update chart version to 1.0.9?

2019-10-07 12:57 UTC, oke-py commented
rebased and force pushed

2019-10-08 01:53 UTC, zanhsieh commented
/ok-to-test

2019-10-12 04:34 UTC, oke-py commented
@nestorsalceda @zanhsieh There are some conflict. I rebased, resolved conflict, and force-pushed. PTAL. Thanks in advance.

2019-11-07 12:25 UTC, oke-py commented
@nestorsalceda Hi, could you review this PR again?

2019-11-25 15:11 UTC, mfdii commented
@nestorsalceda would you review for @frankreno

2019-11-25 15:14 UTC, nestorsalceda commented
/lgtm

Thanks for your contribution!

2019-11-25 15:53 UTC, merged