Promote initContainers to podspec
helm/charts pull request #1735
Opened 2017-08-15 12:35 UTC by dhilipkumars

Move initcontainers to podspec

2017-08-15 12:50 UTC, dhilipkumars commented
cc: @lachie83 PTAL

2017-08-16 10:51 UTC, prydonius requested changes

2017-08-16 10:51 UTC, prydonius commented on stable/consul/templates/consul-test.yaml
> +        - "ba$h"
typo

2017-08-16 10:51 UTC, prydonius commented on stable/consul/templates/consul-test.yaml
> +      - mountPath: /tools
inconsistent indentation for lists here, this line should probably indented another 2 spaces

2017-08-16 10:57 UTC, prydonius commented
/assign

2017-08-17 09:52 UTC, dhilipkumars commented
@prydonius Thanks for the review PTAL now.

2017-08-17 09:56 UTC, prydonius approved these changes

2017-08-17 09:57 UTC, prydonius commented
/test all

2017-08-17 10:21 UTC, prydonius commented
/retest

2017-08-17 10:26 UTC, prydonius commented
cc @lachie83 the tests appear to be failing here

2017-08-18 13:30 UTC, prydonius commented
@viglesiasce since we delete the namespace, we're not getting logs if tests fail. Helm test prints out a command to get the logs when tests fail, maybe we can parse that and execute it?

2017-09-17 13:28 UTC, unguiculus commented
/retest

2017-09-17 19:10 UTC, unguiculus commented
I guess CI doesn't wait long enough. Chart installs fine on my GKE cluster and test run successfully.

2017-09-17 19:12 UTC, unguiculus commented
/lgtm

2017-09-17 19:12 UTC, merged