[stable/consul] Add cpu/memory limits to consul chart
helm/charts pull request #1745
Opened 2017-08-15 18:20 UTC by bksteiny

Hello there- 

I'd like to add cpu and memory limits to the Consul chart. 

Thanks
Chris

2017-08-15 18:26 UTC, bksteiny commented
This wouldn't be a passive change. If you'd rather not bump the major version for this chart, I can make the changes in a way that are passive.

Please let me know your thoughts

2017-08-17 18:33 UTC, lachie83 commented
Thanks. Please bump major version

2017-08-17 19:01 UTC, jonstacks commented
Seems like a rather small thing to bump the major version for. It looks like we could incorporate these changes in while doing so in a passive way. Would it be possible to wrap the limit assignment with something like:

```
{{- if .Values.resources.limits }}
limits:
  cpu: "{{ .Values.resources.limits.cpu }}"
  memory: "{{ .Values.resources.limits.memory }}"
{{- end }}
```

And for the other stuff we could maybe do something like: 

`{{ .Values.resources.requests.cpu | default .Cpu }}`

If not, I'd agree that we'd have to bump the major version.

2017-08-18 07:15 UTC, unguiculus requested changes
We've started recommending not to specify defaults for resources. This should be a conscious choice of the user and makes it easier to test charts on smaller systems, such as Minikube.

2017-08-18 07:15 UTC, unguiculus commented on stable/consul/templates/consul.yaml
> +            memory: "{{ .Values.resources.limits.memory }}"
I'd suggest you change it like so:

```yaml
        resources:
{{ toYaml .Values.resources | indent 10 }}
```

2017-08-18 07:15 UTC, unguiculus commented on stable/consul/values.yaml
> +resources:
With above change do it like so:

```yaml
resources: {}
#  requests:     
#    cpu: "100m"
#    memory: "256Mi"
#  limits:
#    cpu: "500m"
#    memory: "512Mi"
```

2017-08-19 00:06 UTC, bksteiny commented on stable/consul/templates/consul.yaml
> +            memory: "{{ .Values.resources.limits.memory }}"
Nice suggestion

2017-08-19 00:06 UTC, bksteiny commented on stable/consul/values.yaml
> +resources:
👌

2017-08-24 19:04 UTC, unguiculus requested changes

2017-08-24 19:04 UTC, unguiculus commented on stable/consul/README.md
> +| `resources.requests.memory` | container requested memory        | `256Mi`                                                    |
Should be just one resoucres row (with proper spacing, of course).

```
| `Resources` | Pod resource requests and limits | `{}` |
```

2017-08-24 19:04 UTC, unguiculus commented on stable/consul/templates/consul.yaml
> +{{ toYaml .Values.resources | indent 10 }}
Make it start with a upper case letter for consistency (even though that does wouldn't match our best practices).

`{{ toYaml .Values.Resources | indent 10 }}`

2017-08-24 19:04 UTC, unguiculus commented on stable/consul/values.yaml
> +resources: {}
`Resources: {}`

2017-08-29 13:29 UTC, bksteiny commented
Hi @unguiculus - I've added your suggestions

2017-08-30 20:28 UTC, unguiculus commented
/ok-to-test

2017-09-10 19:46 UTC, unguiculus commented
/retest

2017-09-10 20:04 UTC, unguiculus commented
Tests pass on my GKE cluster.

2017-09-10 20:04 UTC, unguiculus approved these changes

2017-09-10 20:08 UTC, merged