[stable/sysdig] Fixes compatibility with 1.16
helm/charts pull request #17538
Opened 2019-09-30 05:52 UTC by daixiang0

To support 1.16. A quick overview of deprecated APIs can be found on their blog post: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/.

Signed-off-by: Xiang Dai 764524258@qq.com

2019-10-03 04:07 UTC, zanhsieh commented
@daixiang0 
Please resolve conflict on stable/sysdig/Chart.yaml. Thank you.

2019-10-03 06:14 UTC, zanhsieh requested changes

2019-10-03 06:14 UTC, zanhsieh commented on stable/sysdig/Chart.yaml
> +version: 1.4.17
Please bump to 1.4.18. Thank you.

2019-10-04 02:17 UTC, zanhsieh commented
/retest

2019-10-04 06:56 UTC, zanhsieh approved these changes

2019-10-04 06:57 UTC, zanhsieh commented
/ok-to-test
/lgtm

2019-10-04 06:58 UTC, zanhsieh commented
/assign @nestorsalceda

2019-10-04 07:00 UTC, zanhsieh commented
@nestorsalceda 
Please help.

2019-10-09 07:54 UTC, zanhsieh commented
@daixiang0 
Probably another version bump please.

2019-10-09 18:11 UTC, zanhsieh commented
/auto-cc

2019-10-10 07:11 UTC, zanhsieh approved these changes

2019-10-10 07:11 UTC, zanhsieh commented
/lgtm

2019-10-10 07:14 UTC, zanhsieh approved these changes

2019-10-14 14:06 UTC, bencer commented
Thanks for the PR, can we add a changelog entry?

2019-10-15 01:47 UTC, daixiang0 commented
@bencer done.

2019-10-16 08:35 UTC, bencer commented
/lgtm
/approve

2019-10-16 08:43 UTC, merged