[stable/rabbitmq-ha] Updating StatefulSet apiVersion for kubernetes 1.16
helm/charts pull request #17597
Opened 2019-10-01 23:44 UTC by EricLemieux

#### Is this a new chart
No, bug fix for existing chart

#### What this PR does / why we need it:
StatefulSet from `apps/v1beta1` was removed as part of k8s 1.16, this migrates to the stable version of the api, `apps/v1`.

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

#### Which issue this PR fixes
fixes #17561

#### Special notes for your reviewer:
I updated the minor version of the chart, rather than the patch, because this changes the minimum version of Kubernetes required. This can be adjusted to best reflect how you want to do versioning for the chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-10-01 23:47 UTC, EricLemieux commented
/assign @steven-sheehy

2019-10-02 00:23 UTC, steven-sheehy requested changes
This looks fine, but let's go ahead and take care of some other deprecations now as well if you don't mind:

- Role: `rbac.authorization.k8s.io/v1beta1` -> `rbac.authorization.k8s.io/v1`
- RoleBinding: `rbac.authorization.k8s.io/v1beta1` -> `rbac.authorization.k8s.io/v1`
- Remove `service.alpha.kubernetes.io/tolerate-unready-endpoints` annotation from service

2019-10-02 12:45 UTC, EricLemieux commented
Additional changes have been implemented.
The ingress from `extensions/v1beta1` will be removed in 1.20, but the new apiVersion ,`networking.k8s.io/v1beta1`, would bring the minimum cluster version up to 1.14. Do we want to bump that as well now?

2019-10-02 15:52 UTC, steven-sheehy commented
No, lets keep it at 1.9 compatibility for now.

/ok-to-test

2019-10-02 19:34 UTC, EricLemieux commented
/retest

2019-10-02 20:38 UTC, steven-sheehy commented
It looks good. Can you test an upgrade from a previous version to this version locally to ensure this isn't a breaking change? I think it's compatible, but if it's not we need to bump the major version and add some upgrade notes.

2019-10-03 13:00 UTC, EricLemieux commented
Upgrading locally using didn't run into any issues 👍

2019-10-03 14:44 UTC, steven-sheehy commented
Thanks for checking
/lgtm

2019-10-03 14:54 UTC, merged