[Prometheus] Make the health URL configurable
helm/charts pull request #1769
Opened 2017-08-18 11:19 UTC by andrewhowdencom

Currently, the Prometheus chart cannot be made to respond to a
non-default URL. Outside the chart, Prometheus can be made to do so with
the flag:

  -web.external-url

This flag modifies the behaviour of the application (both Prometheus and
AlertManager) to respond to URLs that start with the prefix defined by
the web external URL. For example, if the URL is:

  https://www.example.com/monitoring/

than Prometheus will generate CSS/JS resources etc for that URL, and
work as expected. This argument can be supplied via the extraArgs
configuration node for both Prometheus and the AlertManager.

However, the pod spec in both these declarations currently uses a fixed
"/status" (or variation thereof) for determining whether the
applications are alive. When configured as above, this results in a 404,
and the pods are never declared "healthy".

This commit makes the health check URL configurable, such that it can
query the correct status endpoint when the base URLs are configured.

Design Notes:

reverse proxy:

  Naively it's reasonable to assume that this problem can be solved by
  modifying the behaviour of the reverse proxy to drop the slug
  (/monitoring), thus enabling the current stack to work OK. This works
  to some extent -- however, the stack HTTP response includes a series
  of references which do not factor in this slug, and thus 404.

  It would be possible to rewrite the response in the reverse proxy,
  but that seems like a bad place to address this problem.

2017-08-18 11:22 UTC, andrewhowdencom commented
I signed it

2017-08-18 11:48 UTC, andrewhowdencom commented
Needs work.

2017-08-18 12:04 UTC, andrewhowdencom commented
In theory, adjusted, though the fix is perhaps less nice.

2017-09-02 15:02 UTC, mgoodness requested changes
Almost there.

2017-09-02 15:02 UTC, mgoodness commented on stable/prometheus/README.md
> +`alertmanager.baseURL` | The prefix slug at which the server can be accessed | `/#/status`
Default `alertmanager.baseURL` should be ``, no?

2017-09-02 15:02 UTC, mgoodness commented on stable/prometheus/values.yaml
> +  baseURL: "/status"
Should be ""

2017-09-02 15:02 UTC, mgoodness commented on stable/prometheus/templates/server-deployment.yaml
> +            - --alertmanager.url={{- if .Values.alertmanager.enabled }}http://{{ template "prometheus.alertmanager.fullname" . }}:{{ .Values.alertmanager.service.servicePort }}{{.Values.alertmanager.
Super-nit: `{{.Values.alertmanager.baseURL }}` needs a space before the first period.

2017-09-04 10:57 UTC, andrewhowdencom commented on stable/prometheus/values.yaml
> +  baseURL: "/status"
ooops!

2017-09-04 11:35 UTC, andrewhowdencom commented
Heyaa @mgoodness; 

I made the amendments, but squashed them into the last commit (I don't think that commit added anything of value to the patchset, and was defensively part of the second commit). 

Let me know if you need anything else. I haven't tested this just yet, but the changes seemed simple

2017-09-04 15:03 UTC, mgoodness approved these changes

2017-09-04 15:03 UTC, mgoodness commented
/ok-to-test

2017-09-04 15:14 UTC, merged