add Ghost chart
helm/charts pull request #177
Opened 2016-11-03 00:59 UTC by prydonius

Ghost needs to know the external host of the application at deploy-time so it can configure the application URLs correctly. I've been battling with different ways to solve this issue, and I've opted for a similar approach to @gtaylor's approach to requiring EULA in Minecraft. Essentially, if you don't provide the release with an external host, it will skip the deployment and tell you how to obtain the external IP from the service created and upgrade the deployment.

I feel this is a good approach because it makes it clear that the deployment is incomplete, and forces users to configure the correct host before using the application in a broken state.

That said, I'm open to hear other ideas on solving this problem. One other idea I had, and implemented in a separate workspace, was to use a post-install hook to launch a pod that uses the Kubernetes API to automatically configure the correct host. The issue with this is that it relies on automatic load balancer provisioning, is not obvious to the user, and is difficult to maintain.

cc @viglesiasce @migmartri @sameersbn @michelleN

2016-11-03 03:29 UTC, lachie83 commented
Thanks for the contribution @prydonius Will review!

2016-11-03 20:36 UTC, viglesiasce requested changes

2016-11-03 20:36 UTC, viglesiasce commented on stable/ghost/templates/NOTES.txt
> +1. Get the Ghost URL by running:
Can you note somewhere that in order to login you need to go to /admin?

2016-11-03 22:52 UTC, prydonius commented on stable/ghost/templates/NOTES.txt
> +1. Get the Ghost URL by running:
Added links to `/ghost` as well as `/` below :)

2016-11-06 09:55 UTC, sameersbn commented on stable/ghost/templates/NOTES.txt
> +        Watch the status with: 'kubectl get svc -w {{ template "fullname" . }}'
I think you should add `--namespace {{ .Release.Namespace }}` to the command?

2016-11-11 00:51 UTC, viglesiasce commented on stable/ghost/templates/NOTES.txt
> +        Watch the status with: 'kubectl get svc -w {{ template "fullname" . }}'
yep

2016-11-16 23:57 UTC, viglesiasce approved these changes

2016-11-16 23:57 UTC, merged