adding in node tolerations to cluster-autoscaler deployment
helm/charts pull request #1770
Opened 2017-08-18 12:02 UTC by ag237

Ability to add node tolerations

2017-08-18 13:28 UTC, unguiculus requested changes
Thanks for the PR.

2017-08-18 13:28 UTC, unguiculus commented on stable/cluster-autoscaler/values.yaml
> +deployment:
I don't think it makes sense to group it under `deployment`.

2017-08-18 13:29 UTC, unguiculus commented
/cc @mgoodness

2017-08-18 15:46 UTC, mgoodness requested changes
Don't forget to bump the chart version

2017-08-21 14:30 UTC, ag237 commented
I have made the suggested changes and bumped the chart version.

2017-08-21 17:00 UTC, unguiculus commented
/ok-to-test

2017-08-21 17:08 UTC, unguiculus approved these changes

2017-08-21 17:08 UTC, unguiculus commented
@mgoodness I guess we can ignore the failing test here.

2017-08-23 00:45 UTC, mgoodness approved these changes

2017-08-23 00:48 UTC, mgoodness commented
> @mgoodness I guess we can ignore the failing test here.

Indeed.

/lgtm

2017-08-23 09:54 UTC, merged