Include .Release.Namespace in chart
helm/charts pull request #17712
Opened 2019-10-05 05:02 UTC by dmyerscough

## What this PR does / why we need it:

This PR includes .Release.Namespace that is required when doing Helm deployments from Spinnaker.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-10-05 09:36 UTC, zanhsieh commented
/ok-to-test

2019-10-06 03:23 UTC, dmyerscough commented
/retest

2019-10-07 13:08 UTC, Smirl commented
/assign @gianrubio

@dmyerscough Could you please rename this to include the chart name in the title. Makes it easier to see what chart you are changing. For example:

*[stable/prometheus-node-exporter] Include .Release.Namespace in chart*

2019-10-08 06:46 UTC, dmyerscough commented
@Smirl just updated to include your recommendations

2019-10-09 22:57 UTC, dmyerscough commented
@Smirl @gianrubio any chance we can get this merged in?

2019-10-11 14:09 UTC, zanhsieh commented
@dmyerscough 
Please bump chart to the latest. Thank you.

2019-10-12 05:32 UTC, dmyerscough commented
@zanhsieh bumped version

2019-10-24 04:25 UTC, dmyerscough commented
Any chance this can be merged?

2019-10-24 13:30 UTC, zanhsieh commented
@maorfr @davidkarlsen 
Would you mind to help to LGTM this PR please? @gianrubio is the solely owner of this chart and he lost interest.

2019-10-30 04:58 UTC, dmyerscough commented
Bump

2019-10-30 12:01 UTC, zanhsieh commented
@vsliouniaev 
Would you mind to help with this PR please?

2019-10-30 12:14 UTC, vsliouniaev requested changes
You have ticked 

>Title of the PR starts with chart name (e.g. [stable/chart])

but it does not.

2019-10-30 12:14 UTC, vsliouniaev commented on stable/prometheus-node-exporter/templates/daemonset.yaml
> +  namespace: {{ .Release.Namespace }}
Please replace `{{ .Release.Namespace }}` with `{{ $.Release.Namespace }}` This is less error prone, especially when folks start copy-pasting it.

2019-10-30 12:14 UTC, vsliouniaev commented on stable/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
> +  namespace: {{ .Release.Namespace }}
This is not a namespaced resource

2019-10-30 12:14 UTC, vsliouniaev commented on stable/prometheus-node-exporter/templates/psp-clusterrole.yaml
> +  namespace: {{ .Release.Namespace }}
This is not a namespaced resource

2019-10-30 12:15 UTC, vsliouniaev commented
I do not have rights to LGTM this chart

2019-12-13 13:02 UTC, closed without merging