Allow configuration of daemonset.updateStrategy for datadog chart
helm/charts pull request #1775
Opened 2017-08-18 23:01 UTC by tvanhens

* Allows the updateStrategy to be set with a default of "OnDelete" set for backwards compatibility

2017-08-20 06:00 UTC, dhilipkumars commented
/ok-to-test
/assign

2017-08-20 06:30 UTC, dhilipkumars requested changes

2017-08-20 06:30 UTC, dhilipkumars commented on stable/datadog/templates/daemonset.yaml
> +    type: {{ default "OnDelete" .Values.daemonset.updateStrategy | quote }}
i cant find `updateStrategy ` in the `.Values` files, Im i missing something?

2017-08-20 14:54 UTC, tvanhens commented on stable/datadog/templates/daemonset.yaml
> +    type: {{ default "OnDelete" .Values.daemonset.updateStrategy | quote }}
Nope not missing anything. I am though. PR has been updated with a commented out line to document rolling updates.

2017-08-21 09:25 UTC, dhilipkumars approved these changes

2017-08-21 09:26 UTC, dhilipkumars commented
/test all

2017-08-21 10:49 UTC, merged

2017-08-21 10:50 UTC, dhilipkumars commented
@tvanhens Thanks for the contribution. :-)