stable/rabbitmq-ha
helm/charts pull request #17797
Opened 2019-10-08 18:40 UTC by wjdavis5

#### What this PR does / why we need it:
Bump rabbit version to latest bug fix

#### Special notes for your reviewer:
@steven-sheehy 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-10-08 18:43 UTC, wjdavis5 commented
/assign @steven-sheehy

2019-10-09 04:43 UTC, zanhsieh commented
/ok-to-test

2019-10-09 07:00 UTC, steven-sheehy requested changes
Also update version in README

2019-10-09 07:00 UTC, steven-sheehy commented on stable/rabbitmq-ha/Chart.yaml
> +version: 1.34.0
`1.33.1` since just bugfix bump

2019-10-09 13:38 UTC, wjdavis5 commented on stable/rabbitmq-ha/Chart.yaml
> +version: 1.34.0
Done.

2019-10-10 14:18 UTC, steven-sheehy approved these changes
/lgtm

2019-10-10 14:27 UTC, merged