stable/redis: add args parameter for custom command-line arguments
helm/charts pull request #1783
Opened 2017-08-20 02:52 UTC by mbrevoort

This PR adds an `args` parameter to the stable/redis chart for specifying arbitrary command-line arguments. For example, this will allow you to [configure Redis as an LRU cache](https://github.com/kubernetes/charts/issues/529) with the following:

```
args:
  - "redis-server"
  - "--maxmemory-policy volatile-ttl"
```

2017-08-20 06:09 UTC, dhilipkumars commented
/ok-to-test
/assign

2017-08-20 06:16 UTC, dhilipkumars requested changes
Please update the chart version.

2017-08-20 06:16 UTC, dhilipkumars commented on stable/redis/templates/deployment.yaml
> +        args:
Should it not be guarded around 
``
{{- if .Values.args }}
``

2017-08-20 21:07 UTC, mbrevoort commented
Bumped stable/redis version and added conditional around `args` in `deployment.yaml`.

2017-08-21 09:22 UTC, dhilipkumars approved these changes

2017-08-21 09:22 UTC, dhilipkumars commented
/lgtm

2017-08-21 09:27 UTC, dhilipkumars commented
/test all

2017-08-21 11:04 UTC, dhilipkumars commented
@mbrevoort Thanks for the contribution. i would have only incremented the patch version number and not a minor version number bump.

2017-08-21 11:04 UTC, merged