[stable/prometheus-operator] Sync prometheus operator dashboard and rules
helm/charts pull request #17844
Opened 2019-10-09 20:30 UTC by ElfoLiNk

Signed-off-by: Matteo Gazzetta <matteo_gazzetta@hotmail.it>

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-10-09 23:55 UTC, zanhsieh commented
@ElfoLiNk 
Could you bump the chart version to the latest one please? Thank you.

2019-10-17 12:44 UTC, vsliouniaev commented
Could you please update from latest, the tests should work
/test all

2019-10-20 12:56 UTC, zanhsieh commented
/ok-to-test

2019-10-21 10:22 UTC, vsliouniaev commented
/retest
/lgtm

2019-10-21 11:22 UTC, vsliouniaev commented
/retest

2019-10-22 00:29 UTC, zanhsieh commented
@ElfoLiNk @vsliouniaev 
I think e2e failed by unable to clean up CRD resources. What do you guys think?

2019-10-22 11:03 UTC, vsliouniaev commented
/retest

2019-10-23 17:42 UTC, vsliouniaev commented
/retest

2019-10-23 17:45 UTC, vsliouniaev approved these changes

2019-10-23 17:46 UTC, vsliouniaev commented
/lgtm

2019-10-23 17:55 UTC, vsliouniaev commented
/retest
Another CRD failure, Helm doesn't support CRDs 😡

2019-10-23 18:02 UTC, vsliouniaev commented
/retest

2019-10-23 18:28 UTC, vsliouniaev commented
/retest

2019-10-23 18:35 UTC, vsliouniaev commented
/retest

2019-10-23 18:46 UTC, vsliouniaev commented
/retest

2019-10-24 06:41 UTC, ElfoLiNk commented
/retest

2019-10-24 06:48 UTC, vsliouniaev commented
Looks like this is happening https://github.com/helm/charts/issues/9241#issuecomment-545771389

I'm going to try solve this by using two separate CI test files, get the CRDs into the cluster idempotently using the operator pod, and leave the CRDs in there after the test completes

2019-10-24 16:11 UTC, ElfoLiNk commented
/retest

2019-10-24 16:43 UTC, vsliouniaev commented
I doubt tg tests will pass before that PR gets in

2019-10-26 09:07 UTC, vsliouniaev commented
/retest

2019-10-28 14:14 UTC, vsliouniaev commented
/retest

2019-10-28 14:43 UTC, ElfoLiNk commented
Had to remove PrometheusRemoteWriteDesiredShards rule due to {{ template issue

2019-11-02 09:02 UTC, vsliouniaev commented
/ok-to-test

@ElfoLiNk These rules are not valid with the current version of the prometheus-operator image. I get
```
Error: UPGRADE FAILED: failed to create resource: admission webhook "prometheusrulemutate.monitoring.coreos.com" denied the request: Rules are not valid
```

- Updating the image to version 0.34.0 requires clearing out the unsupported -crd-apigroup flag.
- This also technically breaks the upgrade process for folks - they would have to upgrade to the 0.34.0 image first, then upgrade the rules, otherwise their release will fail.

We'll need to coordinate and do the following things:
1. I will do the image upgrade first, in a separate PR, so that a version of this chart exists that someone can upgrade to.
2. Doing a rules sync will require that we bump the major chart version, since the upgrade is no longer transparent and requires a minimum operator version.

2019-11-04 06:58 UTC, vsliouniaev requested changes
This still needs a section in the README.md file to describe the 7.x to the 8.x upgrade process:


### Upgrading from 7.x.x to 8.x.x
Due to new template functions being used in the rules in version `8.x.x` of the chart, an upgrade to Prometheus Operator and Prometheus is necessary in order to support them. First, upgrade to the latest version of `7.x.x`
```sh
helm upgrade <your-release-name> stable/prometheus-operator --version 7.4.0
```
Then upgrade to `8.x.x`
```sh
helm upgrade <your-release-name> stable/prometheus-operator 
```

2019-11-04 06:58 UTC, vsliouniaev commented on stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
> +apiVersion: {{ printf "%s/v1" (.Values.prometheusOperator.crdApiGroup | default "monitoring.coreos.com") }}
I see this `crdApiGroup` value has re-appeared. Could you please try re-sync the rules again?

2019-11-16 16:59 UTC, closed without merging