[stable/prometheus-operator] Allow to configure kube-proxy endpoints
helm/charts pull request #17918
Opened 2019-10-12 08:05 UTC by mcanevet

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-10-12 09:17 UTC, vsliouniaev commented
/ok-to-test

2019-10-19 05:41 UTC, mcanevet commented
@vsliouniaev @gianrubio conflict fixed

2019-10-19 12:09 UTC, vsliouniaev requested changes

2019-10-19 12:09 UTC, vsliouniaev commented on stable/prometheus-operator/templates/exporters/kube-proxy/endpoints.yaml
> +{{- if and .Values.kubeProxy.enabled .Values.kubeProxy.endpoints }}
I think the `kube-scheduler` should be `kube-proxy`

2019-10-20 12:49 UTC, zanhsieh commented
/retest

2019-10-21 10:21 UTC, vsliouniaev commented
Could you please resolve the DCO issues? @mcanevet

2019-10-22 11:12 UTC, vsliouniaev commented
/retest
/lgtm

2019-10-22 13:00 UTC, vsliouniaev commented
/retest

2019-10-22 13:11 UTC, merged