Upgrade nginx-ingress defaultbackend image
helm/charts pull request #1791
Opened 2017-08-21 11:58 UTC by rubenv

2017-08-21 12:05 UTC, rubenv commented
CLA signed!

2017-08-23 16:32 UTC, mgoodness commented
/ok-to-test

2017-08-23 16:43 UTC, mgoodness requested changes
Just need to bump the chart version (patch should be sufficient)

2017-08-23 17:17 UTC, rubenv commented
@mgoodness Done!

2017-08-23 17:25 UTC, mgoodness approved these changes

2017-08-23 17:26 UTC, mgoodness commented
/lgtm

2017-08-23 17:28 UTC, merged