Update README.md
helm/charts pull request #1802
Opened 2017-08-22 07:16 UTC by wuzhihui1123

2017-08-23 16:45 UTC, mgoodness commented
/ok-to-test

2017-08-23 16:47 UTC, mgoodness requested changes
Chart just needs a patch version bump

2017-09-02 14:52 UTC, mgoodness commented
CLA must be signed and chart version bumped. Please do so within 7 days or we'll close the PR.

2017-09-09 16:23 UTC, unguiculus commented
Closing as stale. Feel free to reopen when/if you decide to work on it again.

2017-09-09 16:23 UTC, closed without merging