[stable/zookeeper] Update api versions to support k8s 1.16
helm/charts pull request #18049
Opened 2019-10-16 15:55 UTC by antongorkovenko

Signed-off-by: Anton Gorkovenko <gostom@gmail.com>

#### Is this a new chart
no
#### What this PR does / why we need it:
Update api versions to support k8s 1.16
#### Which issue this PR fixes
no
#### Special notes for your reviewer:
no
#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-10-16 15:55 UTC, antongorkovenko commented
/assign @lachie83

2019-10-16 22:11 UTC, zanhsieh commented
@antongorkovenko 
Need to resolve conflict on incubator/zookeeper/Chart.yaml

2019-10-17 02:40 UTC, antongorkovenko commented
@zanhsieh resolved

2019-10-17 02:42 UTC, zanhsieh commented
/ok-to-test

2019-10-21 10:01 UTC, Aisuko requested changes
Thanks for your PR, There are some questions and expect your reply.

2019-10-21 10:01 UTC, Aisuko commented on incubator/zookeeper/templates/statefulset.yaml
> +apiVersion: apps/v1
I'm sorry, but could you please explain why change `v1beta1` to `v1`?

2019-10-21 10:01 UTC, Aisuko commented on incubator/zookeeper/README.md
> +* Kubernetes 1.10+
I'm sorry, What's the mean of this? Statefulset API version is not backward compatible?

2019-10-21 13:20 UTC, antongorkovenko commented on incubator/zookeeper/templates/statefulset.yaml
> +apiVersion: apps/v1
v1beta has been removed in 1.116: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

2019-10-21 13:21 UTC, antongorkovenko commented on incubator/zookeeper/README.md
> +* Kubernetes 1.10+
No, new API version is not available in 1.6

2019-10-21 17:35 UTC, lachie83 commented
/approve
/lgtm

2019-10-21 18:24 UTC, merged

2019-10-22 01:26 UTC, Aisuko commented
Thanks