[stable/influxdb] Add startup probe to stable/influxdb deployment
helm/charts pull request #18168
Opened 2019-10-21 20:47 UTC by reloaded

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Add kubernetes deployment startup probe to stable/influxdb deployment.

#### Which issue this PR fixes
  - fixes #18167 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-10-21 20:55 UTC, reloaded commented
Please review @jackzampolin  @Aisuko

2019-10-21 20:56 UTC, reloaded commented
/retest

2019-10-21 20:56 UTC, reloaded commented
/check-cla

2019-10-21 20:58 UTC, reloaded commented
/assign @Aisuko

2019-10-22 02:05 UTC, Aisuko requested changes
Thanks for your PR @reloaded. Please signed off first.

2019-10-22 02:05 UTC, Aisuko commented on stable/influxdb/Chart.yaml
> +version: 1.4.2
Please update the minor version, `1.5.0` could be good.

2019-10-22 18:43 UTC, reloaded commented
@Aisuko  This PR is ready for you to review again.

2019-10-22 20:53 UTC, zanhsieh commented
/ok-to-test

2019-10-23 01:42 UTC, Aisuko approved these changes
/LGTM

2019-10-23 01:52 UTC, merged

2019-10-23 01:53 UTC, Aisuko commented
Thanks a lot.