[stable/sentry] Fix wrong hierarchy of imagePullSecrets and imagePull…
helm/charts pull request #18244
Opened 2019-10-23 16:01 UTC by Antiarchitect

…Policy fields in README.

Signed-off-by: Andrey Voronkov <avoronkov@enapter.com>

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-10-23 17:48 UTC, okgolove commented on stable/sentry/README.md
> +`image.imagePullPolicy`                              | Image pull policy                                                                                          | `IfNotPresent`
```suggestion
`image.PullPolicy`                              | Image pull policy                                                                                          | `IfNotPresent`
```

https://github.com/helm/charts/blob/master/stable/sentry/values.yaml#L7

2019-10-23 17:49 UTC, okgolove requested changes
Hi @Antiarchitect. Thank you for the PR.

Nice catch. Could you also fix the pull policy variable name?

2019-10-24 11:15 UTC, Antiarchitect commented
@okgolove 
Should it be `image.pullPolicy` and `image.pullSecrets` ?

2019-10-24 12:43 UTC, okgolove commented
@Antiarchitect I think we shouldn't make breaking changes, so variables name will be the same.

2019-10-24 12:53 UTC, Antiarchitect commented
So nothing to do from my side?

2019-10-24 14:04 UTC, okgolove commented
I meant changing in the documentation, there is a value **pullPolicy** in the values.yaml
https://github.com/helm/charts/blob/master/stable/sentry/values.yaml#L7

And it is called **imagePullPolicy** in the doc. Could you change the name in the doc? Not change the value in the file.
https://github.com/helm/charts/pull/18244/files#diff-32a7042994b0ce85310e575475d30b81R67

2019-10-24 14:04 UTC, okgolove commented
I meant changing in the documentation, there is a value **pullPolicy** in the values.yaml
https://github.com/helm/charts/blob/master/stable/sentry/values.yaml#L7

And it is called **imagePullPolicy** in the doc. Could you change the name in the doc? Not change the value in the file.
https://github.com/helm/charts/pull/18244/files#diff-32a7042994b0ce85310e575475d30b81R67

2019-10-24 14:43 UTC, Antiarchitect commented
@okgolove Now I understand :) Fixed.

2019-10-24 14:50 UTC, okgolove commented
/lgtm

2019-10-24 15:43 UTC, merged