[stable/influxdb] Fix backups to GCS
helm/charts pull request #18274
Opened 2019-10-24 09:05 UTC by mauermann

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Fix backups to GCS

#### Which issue this PR fixes

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-10-24 11:44 UTC, Aisuko requested changes
Thanks for your PR

2019-10-24 11:44 UTC, Aisuko commented on stable/influxdb/templates/backup-cronjob.yaml
> +                value: /var/secrets/google/{{ .Values.backup.gcs.serviceAccountSecretKey }}
Could you please explain more details about this?

2019-10-24 11:55 UTC, mauermann commented on stable/influxdb/templates/backup-cronjob.yaml
> +                value: /var/secrets/google/{{ .Values.backup.gcs.serviceAccountSecretKey }}
We already have some existing service account secrets with the key field "credentials.json". I'm not sure why we use this name, but IMHO this is/was the default file name some apps/libs expect.
We also use https://github.com/kiwigrid/gcp-serviceaccount-controller, this creates secret with credentials.json field name too.

2019-10-24 12:46 UTC, monotek approved these changes
/lgtm

2019-10-24 19:55 UTC, zanhsieh commented
/ok-to-test

2019-10-30 06:36 UTC, Aisuko commented
Please resolve the conflict. Thanks.

2019-10-30 06:40 UTC, Aisuko commented on stable/influxdb/templates/backup-cronjob.yaml
> +                value: /var/secrets/google/{{ .Values.backup.gcs.serviceAccountSecretKey }}
Thanks

2019-10-31 01:46 UTC, Aisuko approved these changes
/lgtm

2019-10-31 01:55 UTC, merged