[stable/postgresql] Use array as default extraEnvs
helm/charts pull request #18341
Opened 2019-10-25 10:28 UTC by DReigada

Signed-off-by: Daniel Reigada <daniel@codacy.com>

#### What this PR does / why we need it:
Extra environment variables should be passed as an array to this chart. But the default value in `values.yaml` is an empty object. This is confusing for the users of the chart.

```yaml
#Correct:
  extraEnv:
   - name: POSTGRESQL_MAX_CONNECTIONS
     value: "300"

#Incorrect:
  extraEnv:
    POSTGRESQL_MAX_CONNECTIONS: "300"
```

This PR changes the default value to match the expected value.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-10-25 14:58 UTC, zanhsieh commented
/ok-to-test

2019-10-29 13:36 UTC, alemorcuq requested changes
Thanks for the PR. Can you add the same change to the `values-production.yaml` file?

2019-10-29 13:36 UTC, alemorcuq commented on stable/postgresql/Chart.yaml
> +version: 6.6.0
Increase this in a patch instead.

2019-11-04 09:43 UTC, DReigada commented on stable/postgresql/Chart.yaml
> +version: 6.6.0
Fixed

2019-11-04 09:44 UTC, DReigada commented
Just pushed the fixes requested by @alemorcuq

2019-11-04 15:26 UTC, alemorcuq commented
Thank you, @DReigada.

@carrodher you can proceed with the merge.

2019-11-04 15:27 UTC, alemorcuq approved these changes

2019-11-04 15:27 UTC, carrodher commented
/ok-to-test
/lgtm

2019-11-04 15:33 UTC, merged