[stable/mychartname] Fix: can't evaluate field Values in type string
helm/charts pull request #18348
Opened 2019-10-25 13:00 UTC by jonaskint

#### What this PR does / why we need it:
It fixes an issue where ipfs.servicename would error.
Example:
```
serviceName: {{ template "ipfs.servicename" . }}
```
Would error in: *can't evaluate field Values in type string*

Both the ingress files already have this defined, specifically for this issue: 
```
{{- $serviceName := include "ipfs.fullname" . -}}
```
And by switching to the serviceName variable, we fix this issue.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-10-25 15:05 UTC, zanhsieh commented
/retitle [stable/ipfs] Fix: can't evaluate field Values in type string

2019-10-25 15:05 UTC, zanhsieh commented
/ok-to-test

2019-10-25 15:12 UTC, bclermont requested changes
@jonaskint few things:

 >  Title of the PR starts with chart name (e.g. [stable/mychartname])

Please replace `mychartname` with `ipfs`.

and:

Rewrite all your commit message to have the same `[stable/ipfs]` prefix, like [most of this repository commits](https://github.com/helm/charts/commits/master)

2019-10-28 08:38 UTC, jonaskint commented
@bclermont fixed your remarks!

2019-10-30 03:31 UTC, bclermont approved these changes

2019-10-30 03:32 UTC, bclermont commented
/approve

2019-10-30 03:36 UTC, bclermont commented
/lgtm

2019-10-30 03:44 UTC, merged