stable/prometheus-mongodb-exporter: version bump percona mongdb exporter
helm/charts pull request #18388
Opened 2019-10-28 02:36 UTC by igaskin

also adding extra arg

2019-10-28 02:38 UTC, igaskin commented
/assign @steven-sheehy

2019-10-28 02:41 UTC, zanhsieh commented
@igaskin 
Would you mind to bump the chart version to latest please? Thank you.

2019-10-28 02:56 UTC, igaskin commented
> @igaskin
> Would you mind to bump the chart version to latest please? Thank you.

Sure thing, just bumped the chart a minor version

2019-10-28 03:24 UTC, zanhsieh commented
/ok-to-test

2019-10-31 13:38 UTC, cpanato commented
@igaskin can you please sign the dco as well

2019-11-06 19:51 UTC, steven-sheehy requested changes

2019-11-06 19:51 UTC, steven-sheehy commented on stable/prometheus-mongodb-exporter/Chart.yaml
> +appVersion: "v0.10.0"
Bump version in README and sign off your commits.

2019-11-08 01:31 UTC, zanhsieh commented
@igaskin 
I think you need to set up your git environment correctly. Git seems not be able to differ "iGaskin" and "Issac Gaskin" in your local git repo.

```
Commit sha: df1f1e1, Author: iGaskin, Committer: iGaskin; Expected "iGaskin gask0032@gmail.com", but got "Isaac Gaskin gask0032@gmail.com".
```

2019-11-11 18:57 UTC, igaskin commented
> @igaskin
> I think you need to set up your git environment correctly. Git seems not be able to differ "iGaskin" and "Issac Gaskin" in your local git repo.
> 
> ```
> Commit sha: df1f1e1, Author: iGaskin, Committer: iGaskin; Expected "iGaskin gask0032@gmail.com", but got "Isaac Gaskin gask0032@gmail.com".
> ```

Okay, let me take a peak and try to fix the signature.

2019-11-12 15:32 UTC, steven-sheehy approved these changes
/lgtm
Thanks!

2019-11-12 15:52 UTC, merged