stable/dex
helm/charts pull request #18380
Opened 2019-10-27 09:49 UTC by lohmag

Fix for openssl config which used by Job later when hook executed. Becouse of `"helm.sh/hook-delete-policy": hook-succeeded` Configmap deletes just after creates.

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-10-27 12:31 UTC, zanhsieh commented
@lohmag 
Would you mind to sign DCO please?

2019-10-28 15:54 UTC, vi7 commented
hi @lohmag , thanks for the contribution. Could you please squash commits into one and name it according to the introduced changes? Also please put a meaningful name for the PR (can be the same as for commit) and prefix it with `[stable/dex]`

2019-10-28 15:55 UTC, vi7 commented
/hold

2019-10-29 02:35 UTC, zanhsieh commented
/ok-to-test

2019-10-29 09:31 UTC, lohmag commented
/retest

2019-10-29 09:53 UTC, lohmag commented
/retest

2019-10-29 09:57 UTC, lohmag commented
I don't know how to squash commit into one and can't spend anymore time on it. And actually I don't know why I should do it if you can squash in web interface when it merges by just checking a box.

2019-10-30 12:06 UTC, vi7 commented
/hold cancel

2019-11-02 18:32 UTC, lohmag commented
/retest

2019-11-02 18:35 UTC, lohmag commented
/retest

2019-11-02 18:50 UTC, lohmag commented
/test pull-charts-e2e

2019-11-02 19:43 UTC, lohmag commented
/assign @vi7

2019-11-04 09:10 UTC, desaintmartin commented
With this change, we'll have one unused configmap, but it is better than a non-working Chart. Thanks!

Could you bump minor version of this chart instead of patch version since there is a new feature?

/assign

@vi7 FYI, AFAIK, merge bot will squash the commits anyway, so the important thing is the PR title.

2019-11-04 13:26 UTC, lohmag commented
> With this change, we'll have one unused configmap, but it is better than a non-working Chart. Thanks!
> 
> Could you bump minor version of this chart instead of patch version since there is a new feature?
> 
> /assign
> 
> @vi7 FYI, AFAIK, merge bot will squash the commits anyway, so the important thing is the PR title.

what do you mean by version bumping? i already bumped helm chart version

2019-11-04 16:12 UTC, desaintmartin requested changes
- bump minor version
- Please also document in the README the new value

2019-11-04 16:12 UTC, desaintmartin commented on stable/dex/Chart.yaml
> +version: 2.3.3
```suggestion
version: 2.4.0
```

This introduce a new feature, SemVer wants us to bump MINOR version.

2019-11-06 12:00 UTC, vi7 commented
> @vi7 FYI, AFAIK, merge bot will squash the commits anyway, so the important thing is the PR title.

@desaintmartin I'm ok with that in case merge commit will be named after the PR name, cause current commit names doesn't describe introduced changes and moreover have misleading names

2019-11-06 12:02 UTC, vi7 commented
/lgtm
/approve

2019-11-06 21:23 UTC, zanhsieh commented
/test pull-charts-e2e

2019-11-06 21:29 UTC, merged