[stable/sysdig] Add 'How to upgrade to last version' to the README
helm/charts pull request #18403
Opened 2019-10-28 15:43 UTC by tembleking

#### What this PR does / why we need it:

This adds documentation about how to upgrade the Sysdig Agent to the latest version.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/chart]`)

2019-10-28 15:44 UTC, tembleking commented
/assign @nestorsalceda

2019-10-28 16:57 UTC, nestorsalceda requested changes
Thank you Fede! Just a couple of changes and this will become merged! :metal:

2019-10-28 16:57 UTC, nestorsalceda commented on stable/sysdig/README.md
> +$ helm upgrade --set image.tag=<last_version> --reuse-values sysdig stable/sysdig
# Ensure you have the latest chart version

$ helm repo update

# And upgrade to the latest version:

$ helm upgrade  --reuse-values sysdig stable/sysdig

2019-10-28 16:57 UTC, nestorsalceda commented on stable/sysdig/README.md
> +$ helm upgrade --set image.tag=<last_version> --reuse-values sysdig stable/sysdig
I mean, you need to specify both commands, one for updating your local repository and the other to upgrade the chart to a newer version.

Perhaps just setting the image tag will work in most cases, but we want to upgrade the complete chart :)

Thank you!

2019-10-28 16:57 UTC, nestorsalceda commented on stable/sysdig/README.md
> +You will need to execute something like:
You will need to execute:

There's no need about `something like`, feels to vage :)

2019-10-29 11:08 UTC, tembleking commented on stable/sysdig/README.md
> +$ helm upgrade --set image.tag=<last_version> --reuse-values sysdig stable/sysdig
The `helm upgrade --set image.tag=<version>` is still needed right? otherwise `--reuse-values` will ensure you maintain the same image.

2019-10-29 12:33 UTC, zanhsieh commented
/ok-to-test

2019-10-31 16:03 UTC, nestorsalceda commented
/lgtm
/approve

2019-10-31 16:11 UTC, merged