[stable/prometheus-operator] Add support of bearer token for Prometheus' ServiceMonitor.
helm/charts pull request #18413
Opened 2019-10-29 10:19 UTC by cryptobioz

#### What this PR does / why we need it:

As we use [oauth-proxy](https://github.com/openshift/oauth-proxy) containers to protect our Prometheus servers, the `/metrics` cannot be scraped without authentication. Thus, the _self-scraping target_ appears to be down (the `oauth-proxy` returns a `403 Forbidden`).
To allow the Prometheus server to scrape its own metrics, it must use a bearer token to pass through the proxy.
This PR adds the support of bearer tokens in the Prometheus' ServiceMonitor.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-10-29 10:30 UTC, cryptobioz commented
/assign @gianrubio

2019-10-29 12:33 UTC, zanhsieh commented
/ok-to-test

2019-10-29 13:22 UTC, vsliouniaev requested changes

2019-10-29 13:22 UTC, vsliouniaev commented on stable/prometheus-operator/templates/prometheus/servicemonitor.yaml
> +    bearerTokenFile: {{ .Values.prometheus.serviceMonitor.bearerTokenFile }}
This should appear in the values file as well

2019-10-29 14:48 UTC, cryptobioz commented on stable/prometheus-operator/templates/prometheus/servicemonitor.yaml
> +    bearerTokenFile: {{ .Values.prometheus.serviceMonitor.bearerTokenFile }}
The variable has been added to the values file.

2019-10-29 16:48 UTC, vsliouniaev commented
/ok-to-test

2019-10-30 02:32 UTC, zanhsieh commented
/retest

2019-10-30 12:41 UTC, cryptobioz commented
/retest

2019-10-30 12:56 UTC, vsliouniaev commented
Should get better with https://github.com/helm/charts/pull/18430

2019-10-31 05:27 UTC, vsliouniaev commented
/retest

2019-10-31 05:28 UTC, vsliouniaev commented
Will merge once conflicts are resolved!
/lgtm

2019-10-31 08:27 UTC, vsliouniaev commented
/lgtm

2019-10-31 08:29 UTC, merged