Add deprecation notices to Dask chart
helm/charts pull request #18419
Opened 2019-10-29 11:55 UTC by jacobtomlinson

We are migrating the Dask community helm charts over to our own repository that will be registered on Helm Hub as per the instructions https://helm.sh/blog/intro-helm-hub/.

This PR adds deprecation notices to the chart in stable and points users to the new repository.

Please let me know if there is anything else I need to change here.

cc @mrocklin

2019-10-29 12:35 UTC, zanhsieh commented
@jacobtomlinson 
Could you sign DCO and bump the chart version to latest for one last time please?

2019-10-30 02:22 UTC, zanhsieh commented
/ok-to-test

2019-10-30 08:25 UTC, davidkarlsen commented
/lgtm

2019-10-30 08:26 UTC, davidkarlsen commented
/lgtm cancel

2019-10-30 08:27 UTC, davidkarlsen requested changes

2019-10-30 08:27 UTC, davidkarlsen commented on stable/dask/Chart.yaml
> +version: 3.1.1
please add the deprecation flag as well

2019-10-30 08:47 UTC, jacobtomlinson commented
Done @davidkarlsen. I hadn't seen that process in the docs, I think I've followed it correctly now.

2019-10-30 08:49 UTC, jacobtomlinson commented
/retest

2019-10-30 13:50 UTC, jacobtomlinson commented
Yeah seems a bit weird. I've updated to reflect that anyway.

2019-11-04 16:09 UTC, jacobtomlinson commented
Changes have been made @davidkarlsen. Can I get another review on this?

2019-12-04 16:30 UTC, jacobtomlinson commented
We've moved over to developing on our own hosted chart so please could we get this reviewed and merged so that folks know this one is deprecated?

2019-12-18 16:56 UTC, scottrigby requested changes
One more change, otherwise looks good

2019-12-18 16:56 UTC, scottrigby commented on stable/dask/Chart.yaml
> +# The foo chart is deprecated and no longer maintained. For details deprecation,
```suggestion
# This chart is deprecated and no longer maintained. For details deprecation,
```

2019-12-19 09:13 UTC, jacobtomlinson commented
Thanks @scottrigby. Changes made.

2019-12-19 09:16 UTC, jacobtomlinson commented
/test pull-charts-e2e

2019-12-19 16:41 UTC, davidkarlsen commented
/lgtm

2019-12-19 16:42 UTC, davidkarlsen approved these changes

2019-12-19 16:49 UTC, merged

2019-12-20 09:01 UTC, jacobtomlinson commented
🎉