add rbac for helm
helm/charts pull request #1843
Opened 2017-08-24 08:21 UTC by smelchior

picking up #1337 i added rbac for heapster
This adds an additional role for the pod nanny. 
I also renamed rbac.enabled to rbac.create as that is the flag most of the other charts tend to use

2017-08-24 09:03 UTC, rimusz commented
PR name should really include chart name as `[stable/heapster] add rbac` as otherwise you get confused which chart is PR for.

2017-08-24 09:09 UTC, smelchior commented
sorry, that does indeed make sense :)

2017-09-02 15:31 UTC, mgoodness requested changes
Looks pretty good. Just a few changes to finish it up. Don't forget to bump the chart version!

2017-09-02 15:31 UTC, mgoodness commented on stable/heapster/templates/role.yaml
> +  name: system:pod-nanny
Let's make this `{{ template "fullname" . }}-pod-nanny` and rename the file to `pod-nanny-role.yaml`.

2017-09-02 15:31 UTC, mgoodness commented on stable/heapster/templates/rolebinding.yaml
> +{{ if .Values.resizer.enabled -}}
Split these into individual files, `heapster-crb.yaml` and `pod-nanny-rolebinding.yaml`

2017-09-02 15:31 UTC, mgoodness commented on stable/heapster/templates/rolebinding.yaml
> +  name: {{ template "fullname" . }}-nanny
`{{ template "fullname" . }}-pod-nanny`

2017-09-02 15:31 UTC, mgoodness commented on stable/heapster/templates/rolebinding.yaml
> +  name: system:pod-nanny
`{{ template "fullname" . }}-pod-nanny`

2017-09-02 15:31 UTC, mgoodness commented on stable/heapster/templates/deployment.yaml
> +      serviceAccountName: {{ template "fullname" . }}
Create an `rbac.serviceAccountName` and use `serviceAccountName: {{ if .Values.rbac.create }}{{ template "fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}`

2017-09-04 18:10 UTC, mgoodness commented
/ok-to-test

2017-09-04 18:15 UTC, smelchior commented
/retest

2017-09-04 18:21 UTC, mgoodness approved these changes

2017-09-04 18:22 UTC, mgoodness commented
/lgtm

2017-09-04 18:22 UTC, merged

2017-09-04 18:31 UTC, smelchior commented
thanks :)!