Fix broken links
helm/charts pull request #18446
Opened 2019-10-30 12:37 UTC by mgrachev

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed

2019-10-31 06:40 UTC, zanhsieh commented
/ok-to-test

2019-11-11 11:08 UTC, mgrachev commented
@zanhsieh Is everything okay?

2019-11-11 17:35 UTC, zanhsieh commented
/assign @mattfarina

2019-11-11 17:37 UTC, zanhsieh commented
@mgrachev 
Thanks for your contribution. I am not a helm member so the change on meta (means outside of each chart) should go thru helm members to merge it. I suggest you go to kubernetes slack #charts channel to shout out about this PR.

2019-11-27 00:26 UTC, scottrigby requested changes
Links have updated

2019-11-27 00:26 UTC, scottrigby commented on CONTRIBUTING.md
> +  (especially for [labels](https://helm.sh/docs/chart_best_practices/#labels-and-annotations)
```suggestion
  (especially for [labels](https://helm.sh/docs/topics/chart_best_practices/labels/)
```

2019-11-27 00:26 UTC, scottrigby commented on CONTRIBUTING.md
> +  and [values](https://helm.sh/docs/chart_best_practices/#values))
```suggestion
  and [values](https://helm.sh/docs/topics/chart_best_practices/values/))
```

2019-11-27 00:26 UTC, scottrigby commented on CONTRIBUTING.md
> +* Follows [best practices](https://helm.sh/docs/chart_best_practices)
```suggestion
* Follows [best practices](https://helm.sh/docs/topics/chart_best_practices/)
```

2019-11-27 00:26 UTC, scottrigby commented on REVIEW_GUIDELINES.md
> +Anyone is welcome to review pull requests. Besides our [technical requirements](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#technical-requirements) and [best practices](https://helm.sh
```suggestion
Anyone is welcome to review pull requests. Besides our [technical requirements](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#technical-requirements) and [best practices](https://helm.sh/docs/topics/chart_best_practices/), here's an overview of process and review guidelines.
```

2019-11-27 00:26 UTC, scottrigby commented
/hold

2019-11-27 11:10 UTC, mgrachev commented
@scottrigby Updated.

2019-12-27 11:46 UTC, mgrachev commented
@scottrigby @mattfarina Is everything okay?

2020-01-26 13:26 UTC, mgrachev commented
Ping

2020-01-27 02:39 UTC, zanhsieh commented
/hold cancel

2020-03-12 06:45 UTC, closed without merging