[stable/traefik] Added ability to provide extra certs to traefik at deployment time
helm/charts pull request #18565
Opened 2019-11-04 19:06 UTC by wf-ryanorth

Signed-off-by: Ryan Orth <ryanorth@workfront.com>

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
This allows users of traefik to provide as many certificates up-front as they would like. While certs can be provided to each ingress object, having them in a central location is ideal for some situations.

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Chart Version bumped
- [ x] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-11-04 19:13 UTC, wf-ryanorth commented
hey @dtomcej - could you take a look at this when you get the chance? Thanks!

2019-11-05 09:23 UTC, zanhsieh commented
/ok-to-test
/assign @dtomcej

2019-11-05 14:48 UTC, dtomcej requested changes

2019-11-05 14:48 UTC, dtomcej commented on stable/traefik/values.yaml
> +  extraCerts: []
Should be commented out by default please.

2019-11-05 14:48 UTC, dtomcej commented on stable/traefik/README.md
> +| `ssl.extraCerts`                       | A list of any extra certificate/key filenames you want included in the traefik instance. You can use this in conjunction with the `secretFiles` parameter to
```suggestion
| `ssl.extraCerts`                       | A list of any extra certificate/key filenames you want added to the https entrypoint. This must be used in conjunction with the `secretFiles` parameter to include the certs on each traefik pod                                                                        | []         |
```

2019-11-05 17:57 UTC, wf-ryanorth commented on stable/traefik/README.md
> +| `ssl.extraCerts`                       | A list of any extra certificate/key filenames you want included in the traefik instance. You can use this in conjunction with the `secretFiles` parameter to
done!

2019-11-05 17:57 UTC, wf-ryanorth commented on stable/traefik/values.yaml
> +  extraCerts: []
fixed

2019-11-05 17:58 UTC, wf-ryanorth commented
thanks for the feedback @dtomcej ! I've updated my changes based on your review. Please let me know if there is anything else you see that needs to be done!

2019-11-05 18:11 UTC, wf-ryanorth commented
/retest

2019-11-05 18:11 UTC, wf-ryanorth commented
/retest

2019-11-10 17:21 UTC, ryaneorth commented
hey @dtomcej - could you take another look at these changes? Thanks!

2019-11-10 17:21 UTC, ryaneorth commented
/retest

2019-11-13 00:22 UTC, ryaneorth commented
@dtomcej - just a gentle poke asking if you could take another look at this PR... If there is someone else I should tag for review, let me know. Thanks!

2019-11-15 19:16 UTC, ryaneorth commented
@emilevauge
@timoreimann
@vdemeester
@nmengin
@mmatur
@ldez
@juliens
@jbdoumenjou
@geraldcroes
@SantoDE
@errm

Would one of you mind taking a look at this? Thanks!

2019-11-21 14:26 UTC, dtomcej commented
@wf-ryanorth Sorry for the delay. Reading week!

2019-11-21 14:26 UTC, dtomcej commented
/ok-to-test

2019-11-21 14:32 UTC, dtomcej commented
/lgtm

2019-11-21 14:33 UTC, merged

2019-11-21 15:58 UTC, ryaneorth commented
Thanks @dtomcej !