[stable/quassel] Update image and deployment apiVersion
helm/charts pull request #18569
Opened 2019-11-04 21:12 UTC by WyriHaximus

For fast feedback, please @-mention maintainers that are listed in the Chart.yaml file: @kiall

#### What this PR does / why we need it:

Ensures that this chart works on the latest versions of Helm and update to the latest version of the used Docker image

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-11-05 09:24 UTC, zanhsieh commented
/ok-to-test

2019-11-05 20:38 UTC, WyriHaximus commented
/assign @kiall

2019-11-05 20:58 UTC, davidkarlsen requested changes

2019-11-05 20:58 UTC, davidkarlsen commented on stable/quassel/Chart.yaml
>  appVersion: 0.12.4
make this match too?

2019-11-05 21:17 UTC, WyriHaximus commented on stable/quassel/Chart.yaml
>  appVersion: 0.12.4
Ah yes my bad :zipper_mouth_face:

2019-11-06 20:26 UTC, zanhsieh commented
/retest

2019-11-15 21:30 UTC, WyriHaximus commented
Is there a way I can help move this forward?

2019-12-16 00:36 UTC, WyriHaximus commented
Bump

2020-01-15 06:08 UTC, WyriHaximus commented
Bump

2020-02-14 07:32 UTC, WyriHaximus commented
Bump

2020-03-15 11:35 UTC, WyriHaximus commented
Bump

2020-04-14 12:57 UTC, WyriHaximus commented
Bump

2020-05-15 06:59 UTC, WyriHaximus commented
Bump

2020-06-14 15:38 UTC, WyriHaximus commented
Bump

2020-07-18 06:11 UTC, WyriHaximus commented
Bump

2020-07-18 13:03 UTC, davidkarlsen commented
/assign
/lgtm
Sorry for the delay!

2020-07-18 13:04 UTC, davidkarlsen approved these changes

2020-07-18 13:08 UTC, merged

2020-07-19 20:33 UTC, WyriHaximus commented
> Sorry for the delay!

No problem, I had a really good chat with `stale` 😋