[stable/external-dns] Added AWS access key environment variables
helm/charts pull request #1859
Opened 2017-08-25 18:49 UTC by micahhausler

* Applicable resources are now namespaced

2017-08-27 20:43 UTC, craigtracey commented
Needed in my environment as well.

:+1: LGTM

2017-09-01 23:05 UTC, mgoodness requested changes
Drop the Namespace fields & rebase. Should be ready after that.

2017-09-01 23:05 UTC, mgoodness commented on stable/external-dns/templates/deployment.yaml
> +  namespace: {{ .Release.Namespace }}
We don't set the namespace, delegating that to Tiller.

2017-09-01 23:05 UTC, mgoodness commented on stable/external-dns/templates/secret.yaml
> +  namespace: {{ .Release.Namespace }}
No namespace

2017-09-01 23:05 UTC, mgoodness commented on stable/external-dns/templates/service.yaml
> +  namespace: {{ .Release.Namespace }}
No namespace

2017-09-01 23:05 UTC, mgoodness commented on stable/external-dns/templates/serviceaccount.yaml
> +  namespace: {{ .Release.Namespace }}
No namespace

2017-09-02 22:42 UTC, micahhausler commented
@mgoodness fixed!

2017-09-04 18:12 UTC, mgoodness approved these changes

2017-09-04 18:15 UTC, mgoodness commented
/ok-to-test

2017-09-04 18:15 UTC, mgoodness commented
/lgtm

2017-09-04 18:17 UTC, merged