Adjusting storage to non alpha/beta if using v1.7 or higher
helm/charts pull request #1874
Opened 2017-08-28 22:03 UTC by venezia

Per https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1 moving storage class setting to `spec.storageClassName`

Also incrementing the version to account for the change

2017-09-04 22:33 UTC, mgoodness requested changes

2017-09-04 22:33 UTC, mgoodness commented on stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
> +        {{- end }}
This whole block can be deleted, as we don't currently support K8s < 1.6.

2017-09-04 22:33 UTC, mgoodness commented on stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
> +        {{- end }}
Copy the pattern introduced in #1332

2017-09-04 22:33 UTC, mgoodness commented
/ok-to-test

2017-09-13 19:31 UTC, unguiculus commented
This has been superseded by #2013.

Related issue: #1869

2017-09-13 19:31 UTC, closed without merging