Add daemon set 1.6 features
helm/charts pull request #1881
Opened 2017-08-29 18:11 UTC by flah00

@frankreno

* podAnnotations, tolerations, and updateStrategy

2017-08-30 19:49 UTC, frankreno reviewed
LGTM

2017-09-04 19:45 UTC, mgoodness requested changes

2017-09-04 19:45 UTC, mgoodness commented on stable/sumologic-fluentd/templates/daemonset.yaml
> +      {{- if .Values.daemonset.podAnnotations }}
Nit: the `if` and `else` statements should be indented only one level less than the block they wrap.

2017-09-04 19:45 UTC, mgoodness commented on stable/sumologic-fluentd/templates/daemonset.yaml
> +      {{- if .Values.daemonset.tolerations }}
Nit: the `if` and `else` statements should be indented only one level less than the block they wrap.

2017-09-04 19:45 UTC, mgoodness commented on stable/sumologic-fluentd/templates/daemonset.yaml
> +    type: {{ default "OnDelete" .Values.daemonset.updateStrategy | quote }}
See comment on `values.yaml`, then `type: "{{ .Values.updateStrategy }}"` is sufficient

2017-09-04 19:45 UTC, mgoodness commented on stable/sumologic-fluentd/values.yaml
> +daemonset:
Is anything gained by creating an intermediate `daemonset` object? Recommend making these top-level values.

2017-09-04 19:45 UTC, mgoodness commented on stable/sumologic-fluentd/values.yaml
> +  podAnnotations:
`podAnnotations: {}`

2017-09-04 19:45 UTC, mgoodness commented on stable/sumologic-fluentd/values.yaml
> +  # tolerations:
Uncomment and make `tolerations: []`

2017-09-04 19:45 UTC, mgoodness commented on stable/sumologic-fluentd/values.yaml
> +  # updateStrategy: RollingUpdate
Uncomment and make `updateStrategy: OnDelete`

2017-09-04 19:45 UTC, mgoodness commented
/ok-to-test

2017-09-05 16:06 UTC, flah00 commented
@mgoodness thanks for the review, should be good to go

2017-09-10 18:19 UTC, mgoodness approved these changes

2017-09-10 18:19 UTC, mgoodness commented
/lgtm

2017-09-10 18:31 UTC, merged