Split out Prometheus Node Exporter to its own chart
helm/charts pull request #1886
Opened 2017-08-30 00:27 UTC by kfox1111

Split out Prometheus Node Exporter to its own chart so it can be instantiated multiple times per Prometheus instance.

You may need a Node Exporter daemonset per type of hardware you have.

2017-08-30 00:28 UTC, kfox1111 commented
This should just be pulling node exporter out with no other changes. Other enhancements will come in a follow on patch set.

2017-08-30 00:31 UTC, kfox1111 commented
There is one minor difference between the before and after. The rbac.create property needs to be specified in the child chart too. It might be nice to have a new feature in helm to copy a value from the main chart's value space to a subchart's verbatim if not overridden. Ie, nodeExporter.rbac.create = rbac.create if nodeExporter.rbac.create is not explicitly set. @jascott1 are you interested?

2018-03-02 17:15 UTC, jdumars commented
/ok-to-test

2018-03-10 08:34 UTC, timstoop commented
It looks like this needs a rebase before it can be tested properly.

2018-04-06 19:21 UTC, timstoop requested changes

2018-04-06 19:21 UTC, timstoop commented on stable/prometheus/values.yaml
> +    create: false
This should default to true.

2018-04-06 19:21 UTC, timstoop commented on stable/node-exporter/values.yaml
> +  create: false
This should default to true.

2018-04-06 19:21 UTC, timstoop commented on stable/node-exporter/values.yaml
> +serviceAccountName: default
Please follow the best practises with regards to RBAC: https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

2018-04-07 10:56 UTC, unguiculus commented
In the meantime, a separate chart for node exporter has already been added.

2018-05-07 11:52 UTC, closed without merging