add testlink chart
helm/charts pull request #189
Opened 2016-11-03 16:29 UTC by sameersbn

2016-11-03 18:23 UTC, prydonius commented
@k8s-bot ok to test

2016-11-03 21:20 UTC, viglesiasce requested changes

2016-11-03 21:20 UTC, viglesiasce commented on stable/testlink/values.yaml
> +# smtpEnable:
Can you add examples of sane values in these parameters?

2016-11-04 05:26 UTC, sameersbn commented
Thanks for the review @viglesiasce.

I realized that the bitnami/testlink image does not currently support configuring SMTP parameter. Therefore I've gone ahead and removed these parameters from the chart. 

Will add these parameters in future updates of the chart when they are properly supported in the image.

2016-11-07 10:42 UTC, sameersbn commented
chart image updated to `bitnami/testlink:1.9.14-r4` which contains fixes for SMTP configuration.

2016-11-16 23:58 UTC, viglesiasce approved these changes

2016-11-16 23:58 UTC, merged