[stable/external-dns] Add connection specifics for Cloudflare
helm/charts pull request #1896
Opened 2017-08-31 05:40 UTC by compleatang

My work is based off of #1859 and assumes that it will be merged prior to review and possible merger of this work. 

- reference: https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/cloudflare.md

2017-08-31 05:46 UTC, compleatang commented
I have signed the CLA.

2017-09-04 18:09 UTC, mgoodness requested changes
Just a few formatting/convention nits.

2017-09-04 18:09 UTC, mgoodness commented on stable/external-dns/templates/deployment.yaml
> +          {{- if and .Values.cloudflare.api_key .Values.cloudflare.email }}
Nit: indent the `if` & `end` statements one level less than the block they wrap.

2017-09-04 18:09 UTC, mgoodness commented on stable/external-dns/templates/deployment.yaml
> +            value: {{ .Values.cloudflare.email }}
Wrap templates in quotes if they simply echo user-provided strings (e.g. `value: "{{ .Values.cloudflare.email }}"`).

2017-09-04 18:09 UTC, mgoodness commented on stable/external-dns/templates/secret.yaml
> +  namespace: {{ .Release.Namespace }}
Don't add `namespace` field to manifests; Tiller does that for us.

2017-09-04 18:10 UTC, mgoodness commented
/ok-to-test

2017-09-06 06:32 UTC, compleatang commented
Thanks for the nits; always good to learn convention! Everything is updated.

2017-09-10 18:10 UTC, mgoodness approved these changes

2017-09-10 18:10 UTC, mgoodness commented
/lgtm

2017-09-10 18:10 UTC, merged