stable/kibana-legacy-ingress-api-version
helm/charts pull request #18974
Opened 2019-11-19 02:16 UTC by japzio

Signed-off-by: Jasper Culong <jculongit10@yahoo.com>

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-11-19 02:40 UTC, japzio commented
/assign @monotek

2019-11-19 10:10 UTC, monotek requested changes
Thanks for your contribution but i dont think the api version should be a configurable value.
Instead you could use something like this, regarding to the K8s version:

```
{{- if semverCompare "> 1.19" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{- end }}
```

2019-11-19 12:57 UTC, japzio commented
> Thanks for your contribution but i dont think the api version should be a configurable value.
> Instead you could use something like this, regarding to the K8s version:
> 
> ```
> {{- if semverCompare "> 1.19" .Capabilities.KubeVersion.GitVersion }}
> apiVersion: networking.k8s.io/v1beta1
> {{ else }}
> apiVersion: extensions/v1beta1
> {{- end }}
> ```

Hi @monotek, just applied your suggestion.

2019-11-19 13:51 UTC, monotek requested changes
edit...

2019-11-19 13:53 UTC, monotek requested changes

2019-11-19 13:53 UTC, monotek commented on stable/kibana/values.yaml
> +  apiVersion: networking.k8s.io/v1beta1
pleae emove line

2019-11-19 13:55 UTC, monotek requested changes

2019-11-19 13:55 UTC, monotek commented on stable/kibana/README.md
> +| `ingress.apiVersion`                       | Ingress API Version                                                    | `networking.k8s.io/v1beta1`                               |
please remove line

2019-11-19 13:55 UTC, monotek commented on stable/kibana/templates/ingress.yaml
> +{{- if semverCompare "> 1.19" .Capabilities.KubeVersion.GitVersion }}
Sorry, for using an example version here.

New api will work form Kubernetes 1.14: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#deprecations

So it should be ">= 1.14"

2019-11-19 14:19 UTC, japzio commented
Oh yeah2x i came across that doc.

2019-11-19 15:28 UTC, monotek requested changes
Looks good to me.

But please sign your commits to get the DCO check passed.
See: https://github.com/helm/charts/pull/18974/checks?check_run_id=309996144

2019-11-20 14:42 UTC, japzio commented
Hi @monotek Check resolved thanks. :-)

2019-11-20 19:24 UTC, monotek approved these changes
/ok-to-test
/lgtm

2019-11-20 19:37 UTC, merged