[stable/redmine] Option to create a custom service account
helm/charts pull request #19005
Opened 2019-11-19 18:09 UTC by crmarques

#### What this PR does / why we need it:

Add option to create a custom service account.

#### Special notes for your reviewer:

It does not change chart's default behavior.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-11-28 16:01 UTC, crmarques commented
@carrodher, could you review this PR?

2019-12-02 15:56 UTC, crmarques commented
@javsalgar @tompizmor, could you review this PR? Thanks!

2019-12-05 00:39 UTC, davidkarlsen requested changes

2019-12-05 00:39 UTC, davidkarlsen commented on stable/redmine/values.yaml
> +  create: false
```suggestion
  create: true
```
https://helm.sh/docs/topics/chart_best_practices/rbac/

2019-12-05 00:39 UTC, davidkarlsen commented
/assign

2019-12-05 15:53 UTC, juan131 approved these changes
Sorry I missed this PR! But it looks great to me
Approving it

2019-12-05 15:53 UTC, juan131 commented
/ok-to-test

2019-12-06 14:37 UTC, crmarques commented
@juan131, Is it ok to proceed? =D

2019-12-08 02:20 UTC, davidkarlsen commented
/lgtm

2019-12-08 02:31 UTC, merged