]Support 'hostPath' persistent storage
helm/charts pull request #19037
Opened 2019-11-21 07:54 UTC by Cyreex

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-11-21 08:18 UTC, cpanato commented
@Cyreex thanks for this PR, can you please update your PR with latest master and resolve the conflict.
thanks!

2019-11-26 16:49 UTC, steven-sheehy requested changes
I'm against the complexity that this solution brings. I also believe hostPath is not possible to use with statefulsets, especially when scaling past one and has issues scheduling pods. See this [article](https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/) about it's limitations. 

The recommended solution for this scenario is to use [local volumes](https://kubernetes.io/docs/concepts/storage/volumes/#local) with either the [local-static-provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner) or Rancher's [local-path-provisioner](https://github.com/rancher/local-path-provisioner).

2019-11-28 09:20 UTC, Gsantomaggio commented
I agree with @steven-sheehy 
With Rancher's local-path-provisioner, is very easy:
```bash
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
```
then
```yaml
persistentVolume:
  enabled: true
  storageClass: "local-path"
```
done.

`statefulsets` should not use `hostPath` for scaling.

2019-12-07 03:37 UTC, zanhsieh commented
/ok-to-test

2019-12-08 01:27 UTC, steven-sheehy commented
@zanhsieh Again, please do not add ok-to-test labels to PRs you're not reviewing. The whole point of ok-to-test is to review the PR first and ensure it meets standards before wasting limited CI resources. This PR has already been rejected by the chart maintainer (me).

2019-12-08 11:25 UTC, davidkarlsen commented
I agree - local volume is a far more preferrable - which also avoids having to run as root.

2019-12-08 19:18 UTC, davidkarlsen commented
/do-not-merge
/hold

2020-01-21 20:23 UTC, closed without merging