Add flag for daemonset controllers so that hostPort can optionally be used
helm/charts pull request #1906
Opened 2017-08-31 19:29 UTC by digivava

This supports use cases that don't rely on the Service resource, such as a user pointing their own load balancer at a set of ingress nodes.

2017-08-31 19:39 UTC, digivava commented
Signed CLA

2017-09-04 15:24 UTC, mgoodness requested changes
Is there a use case for enabling this when the controller is a Deployment?

2017-09-04 15:24 UTC, mgoodness commented on stable/nginx-ingress/values.yaml
> +  daemonset:
Let's not add an intermediate object just for this.

2017-09-04 15:24 UTC, mgoodness commented on stable/nginx-ingress/values.yaml
> +    hostPort: false
How about `createHostPorts` or `enableHostPorts`?

2017-09-04 18:10 UTC, mgoodness commented
/ok-to-test

2017-11-09 05:00 UTC, viglesiasce commented
Closing as stale

2017-11-09 05:00 UTC, closed without merging