stable/prometheus-blackbox-exporter Add DaemonSet kind
helm/charts pull request #19097
Opened 2019-11-24 19:38 UTC by alexppg

#### What this PR does / why we need it:
It adds the possibility to set the blackbox exporter as a DaemonSet instead of a Deployment. 

It's useful because you sometimes may want to see from which nodes you can reach some resources and which not.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

@desaintmartin @gianrubio

2019-12-01 23:02 UTC, alexppg commented
ping @desaintmartin @gianrubio

2019-12-05 00:34 UTC, davidkarlsen requested changes

2019-12-05 00:34 UTC, davidkarlsen commented on stable/prometheus-blackbox-exporter/templates/daemonset.yaml
> +apiVersion: apps/v1beta2
```suggestion
apiVersion: apps/v1
```

2019-12-05 00:34 UTC, davidkarlsen commented
/ok-to-test

2019-12-23 14:27 UTC, alexppg commented
/retest

2020-01-14 21:40 UTC, alexppg commented
@davidkarlsen I think the bot get stucked, it says you have a request change but it's already done.

2020-01-30 09:39 UTC, desaintmartin commented
Thanks!
/assign
/ok-to-test
Could you rebase?

Do not worry about this request change, this is GitHub behavior.

2020-01-31 21:33 UTC, alexppg commented
Thanks @desaintmartin. It shouldn't be any problem now.

2020-02-03 17:47 UTC, desaintmartin commented on stable/prometheus-blackbox-exporter/Chart.yaml
> +version: 3.0.2
```suggestion
version: 3.1.0
```

2020-02-03 17:48 UTC, desaintmartin commented
Could you add a test file in the ci directory testing those values? Then it should be good!

2020-02-03 22:05 UTC, alexppg commented
How's that @desaintmartin? I don't know how this works. If you can point me to some documentation I'll be glad to change it.

2020-02-04 20:57 UTC, alexppg commented
Ok, I figured out the CI part, I believe it should work like this. Also, sorry for rewriting the history, it all become pretty messed up with all the merges from master I had to do.

2020-02-07 08:03 UTC, desaintmartin commented
Sorry, I could not answer before.
You have different files in https://github.com/helm/charts/tree/master/stable/prometheus-blackbox-exporter/ci where each of them is going to be used by the test CI to basically do "helm install -f ci/$FILE". This allows to prove that it deploys well.

I don't see any new file added, did you add them in your commit?

2020-02-07 15:30 UTC, alexppg commented
Yeah, it's here. https://github.com/alexppg/charts/blob/feature/blackbox_daemonset/stable/prometheus-blackbox-exporter/ci/daemonset-values.yml

2020-02-11 15:09 UTC, desaintmartin commented
Thanks!
/lgtm

2020-02-11 15:16 UTC, merged

2020-03-26 12:52 UTC, omerlh commented
@alexppg did you checked that? There are fields that are not supported in a daemonset, like `replicas` or `strategy` and defined in the daemonses:
```
error validating data: [ValidationError(DaemonSet.spec): unknown field "replicas" in io.k8s.api.apps.v1.DaemonSetSpec, ValidationError(DaemonSet.spec): unknown field "strategy" in io.k8s.api.apps.v1.DaemonSetSpec]
```

2020-08-02 14:58 UTC, Maxpain177 commented
This doesn't work

2020-08-03 07:23 UTC, desaintmartin commented
PRs wanted! ;)

2020-08-04 07:39 UTC, alexppg commented
@Maxpain177 What doesn't work? I'm using it and it does work.

2020-08-04 08:31 UTC, Maxpain177 commented
@alexppg I fixed this in my merge request yesterday :)

2020-08-04 08:32 UTC, Maxpain177 commented
@alexander-alvarez how did you use this with replicas and strategy keys?

2020-08-04 08:46 UTC, alexppg commented
Oh, I see, nice, thanks! @Max