[stable/prometheus-operator] Add release namespace to header in sync scripts
helm/charts pull request #19137
Opened 2019-11-25 22:08 UTC by mercul3s

#### What this PR does / why we need it:
This PR adds the release namespace to grafana dashboards and alerting rules generated from `sync_grafana_dashboards.py` and `sync_prometheus_rules.py`. This ensures that the rules and dashboards configmaps are deployed to the same namespace as prometheus and grafana.

Note: This change does not contain updates to the templates, as I was unsure if that was necessary at this point and ran into some issues with updated alertmanager rules which I don't have bandwidth to debug at this time (I've disabled them in our deployment for now). I can resubmit with updated templates if desired.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-12 17:43 UTC, mercul3s commented
/assign @gianrubio

2020-01-08 15:00 UTC, bismarck requested changes
@mercul3s  Thanks for the PR!  Could you try regenerating the rules and dashboards with the updated scripts and include those in your PR?

2020-01-08 15:00 UTC, bismarck commented on stable/prometheus-operator/hack/sync_grafana_dashboards.py
> +  namespace: {{ .Release.Namespace }}
Could you make this `$.Release.Namespace`?

2020-01-08 15:00 UTC, bismarck commented on stable/prometheus-operator/hack/sync_prometheus_rules.py
> +  namespace: {{ .Release.Namespace }}
Could you make this `$.Release.Namespace`?

2020-01-13 19:57 UTC, bismarck commented
/ok-to-test

2020-01-13 19:58 UTC, bismarck commented
@mercul3s Looks like you're going to have to bump the chart version one more time.  Everything else looks good.

2020-01-13 20:26 UTC, mercul3s commented
@bismarck thanks for taking a look! The chart version is up to date, it looks like the linter is failing on one of the charts generated from the upstream:
```
Linting chart with values file 'stable/prometheus-operator/ci/01-provision-crds-values.yaml'...

==> Linting stable/prometheus-operator
[ERROR] templates/: parse error in "prometheus-operator/templates/prometheus/rules-1.14/prometheus.yaml": template: prometheus-operator/templates/prometheus/rules-1.14/prometheus.yaml:171: bad character U+007B '{'

Error: 1 chart(s) linted, 1 chart(s) failed
```
I'm taking a look at it, but it's not obvious to me why it's failing the lint step there as it looks like it should be valid.

2020-01-14 19:34 UTC, bismarck commented
@mercul3s Looks like the script isn't encoding the prometheus query in the description properly (escaping a template in a template makes my head explode).

@vsliouniaev Do you think someone manually fixed the encoding [here](https://github.com/helm/charts/pull/19137/files#diff-365cff774eb3b04dae4571b2b53cbcb2L171)?

2020-01-14 20:32 UTC, mercul3s commented
@bismarck I was just going down that path and yes, it makes my head explode too. I'm guessing it's getting mangled in this step: https://github.com/helm/charts/blob/master/stable/prometheus-operator/hack/sync_prometheus_rules.py#L92-L119

2020-02-27 22:25 UTC, closed without merging