[stable/falco] Disable Service and AuditSink when running on EKS
helm/charts pull request #19180
Opened 2019-11-27 13:11 UTC by arminc

#### Is this a new chart
No

#### What this PR does / why we need it:

AWS EKS does not support auditregistration.k8s.io but in some cases, you still might want to run the webserver. For example to use it with [falco-eks-audit-bridge](https://github.com/xebia/falco-eks-audit-bridge). This PR allows you to enable the webserver without enabling the Service and the AuditSink.

#### Special notes for your reviewer:

@bencer @nestorsalceda

2019-11-27 13:14 UTC, arminc commented
/assign @bencer

2019-12-03 07:32 UTC, bencer commented
Have you considered implementing a flag outside the webserver scope to define on which platform we are running instead? Rather that a flag webserver:notOnAwsEks, something like platform:aws:eks? How other charts have approached defining on which platform are running? 

cc @nestorsalceda

2019-12-03 16:30 UTC, arminc commented
I will have a look and adjust the PR

2019-12-04 10:15 UTC, iverberk commented
@bencer @@nestorsalceda I've updated the chart to make the platform setting reusable across the chart and future-proof for new platforms. Please review and let me know if anything needs to be done to get this merged.

2019-12-18 12:42 UTC, iverberk commented
@bencer @nestorsalceda I added sign-off and updated the code. Could you please review and, if ok, merge?

2019-12-23 08:59 UTC, nestorsalceda requested changes
Don't include platform / vendor specific code.

2019-12-23 08:59 UTC, nestorsalceda commented on stable/falco/values.yaml
> +platform:
I don't want vendor / platform specific conditions

2020-01-11 23:54 UTC, zanhsieh commented
/ok-to-test

2020-02-27 05:25 UTC, closed without merging