[stable/mysql] #5154 MySql: Allow to override deployment strategy
helm/charts pull request #19201
Opened 2019-11-27 20:48 UTC by janario

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

* Allow to override mysql deployment strategy
* Change the default to `Recreate`

#### Which issue this PR fixes
  - fixes #5154

#### Special notes for your reviewer:
@olemarkus  @viglesiasce 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ x ] Chart Version bumped
- [ x ] Variables are documented in the README.md
- [ x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-11-27 20:51 UTC, janario commented
/assign @olemarkus

2019-11-27 21:08 UTC, olemarkus commented
/ok-to-test

2019-12-07 13:08 UTC, janario commented
@olemarkus @lachie83 

Any updates here? :)

2019-12-07 14:07 UTC, olemarkus requested changes

2019-12-07 14:07 UTC, olemarkus commented on stable/mysql/Chart.yaml
> +version: 1.4.1
You should bump minor version here

2019-12-07 14:07 UTC, olemarkus commented
Forgot to submit the review. sorry

2019-12-07 14:18 UTC, janario commented on stable/mysql/Chart.yaml
> +version: 1.4.1
I've just pulled master 1.5.0

Do you see it as `1.5.1` or `1.6.0` ?

2019-12-07 15:28 UTC, olemarkus commented
New feature means minor version bump. So 1.6

2019-12-07 15:33 UTC, janario commented on stable/mysql/Chart.yaml
> +version: 1.4.1
Done :+1:

2019-12-07 19:40 UTC, davidkarlsen commented
/assign
/lgtm

2019-12-07 19:41 UTC, merged

2019-12-07 20:12 UTC, janario commented
Thanks  🙂✌️