[stable/rabbitmq-ha] add option for StatefulSet annotations
helm/charts pull request #19261
Opened 2019-11-29 16:03 UTC by max-rocket-internet

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-11-29 16:04 UTC, max-rocket-internet commented
/assign @steven-sheehy

2019-12-07 03:49 UTC, zanhsieh commented
/ok-to-test

2019-12-09 09:10 UTC, max-rocket-internet commented
@lachie83 or @steven-sheehy can someone please review?

2019-12-12 21:16 UTC, steven-sheehy requested changes
Other than version bump it LGTM

2019-12-12 21:16 UTC, steven-sheehy commented on stable/rabbitmq-ha/Chart.yaml
> +version: 1.36.5
1.37.0 for new features

2019-12-13 08:57 UTC, max-rocket-internet commented on stable/rabbitmq-ha/Chart.yaml
> +version: 1.36.5
OK done

2019-12-13 10:09 UTC, max-rocket-internet commented
I've read the logs the test and can't really see what the problem is?

2019-12-13 15:47 UTC, steven-sheehy commented
/test pull-charts-e2e

2019-12-13 17:27 UTC, steven-sheehy commented
Think there's a general issue with the e2e test

2019-12-18 00:04 UTC, steven-sheehy commented
/retest

2019-12-18 00:26 UTC, steven-sheehy approved these changes
/lgtm

2019-12-18 00:27 UTC, merged