Enabling to control whether cluster role and cluster role binding will
helm/charts pull request #19278
Opened 2019-12-01 03:05 UTC by Hedingber

Is this a new chart
No

What this PR does / why we need it:
This PR enables to control whether cluster role and cluster role binding will be created when setting `rbac.create` to `true` by setting `crd.create` to `true`/`false`
I needed this since I'm running dex in a multi tenant (namespace) environment in which user tenants cannot have cluster role. The cluster role is needed in order to enable dex to create its CRDs, but creating CRDs should happen only once, so with this new value I can give only the "admin" tenant's dex the cluster role, and spawn dex on the "user" tenants without the cluster role.

Which issue this PR fixes
(optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged)

fixes #

Special notes for your reviewer:

Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

'[x]'DCO signed
'[x]'Chart Version bumped
'[x]'Variables are documented in the README.md
'[x]'Title of the PR starts with chart name (e.g. [stable/mychartname])

2019-12-01 03:13 UTC, Hedingber commented
/assign @vi7

2019-12-01 07:20 UTC, vi7 requested changes

2019-12-01 07:20 UTC, vi7 commented on stable/dex/templates/role.yaml
> +- apiGroups: ["dex.coreos.com"] # API group created by dex
when `crd.create` is `true` this rule will duplicate the same rule from the ClusterRole

2019-12-01 07:20 UTC, vi7 commented on stable/dex/Chart.yaml
> +version: 2.4.2
customer facing changes, minor version should be bumped (like `2.5.0`)

2019-12-01 08:47 UTC, vi7 commented
Hi @Hedingber! Thanks for the PR. Please consider the following.

There is no possibility to disable CRD creation for Dex as such unless another storage option is used instead of the CRD's (etcd, mysql etc.). Thus introduced `crd.create` switch sounds very misleading.

My proposal is to rename it to `crd.present` with the default value `false`. In that case if you need to deploy Dex to the cluster with already created CRD's this option should be set to `true` thus disabling creation of the ClusterRole and ClusterRoleBinding

2019-12-01 08:56 UTC, vi7 commented
/hold

2019-12-01 12:12 UTC, Hedingber commented
Hi @vi7, thanks for the review, 
I agree with what you've said and submitted commits that fix everything

2019-12-02 09:14 UTC, vi7 commented
/unhold
/lgtm

2019-12-02 09:14 UTC, vi7 commented
/approve

2019-12-02 09:15 UTC, vi7 commented
/ok-to-test

2019-12-02 09:19 UTC, merged