[stable/ambassador] - Changing the var podLabels to extraLabels to use in Pods and Deployments
helm/charts pull request #19311
Opened 2019-12-02 21:28 UTC by nullck

Signed-off-by: Thiago Dias <nullck@gmail.com>

#### What this PR does / why we need it:

The same way we can add new labels into the Pods resource I'm suggesting here to make usage of the same "additional" or "extra" labels and use them into the Deployment resource also
I believe other users are trying to track the labels in order to have cost report or maybe some Open Policy Rules where they want to keep a standard in their labels names and values.

#### Which issue this PR fixes

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-02 21:28 UTC, nullck commented
/assign @lukeshu

2019-12-03 23:28 UTC, Flydiverny requested changes

2019-12-03 23:28 UTC, Flydiverny commented on stable/ambassador/Chart.yaml
> +version: 5.1.1
this would be a breaking change and not a patch since its removing the podLabels, I'd prefer if we can make this a non breaking change for now.

2019-12-03 23:28 UTC, Flydiverny commented on stable/ambassador/templates/deployment.yaml
> +    {{- end }}
to be consistent with how other charts seems to use `extraLabels` I believe these should be added to all resources. 
Think I'd rather add `deployment.labels` option to set extra labels for the deployment.

```
deployment:
  labels: {}
```

to allow adding labels to the deployment

or we can add the `extraLabels` but set it on all resources while keeping `podLabels` for backwards compat for now.

2019-12-12 23:28 UTC, Flydiverny commented on stable/ambassador/Chart.yaml
> +version: 5.2.2
set to 5.3.0 :)

2019-12-12 23:28 UTC, Flydiverny commented
/ok-to-test

2019-12-13 19:54 UTC, Flydiverny commented
/assign

2019-12-13 21:19 UTC, nullck commented on stable/ambassador/Chart.yaml
> +version: 5.2.2
ok

2019-12-13 21:22 UTC, nullck commented on stable/ambassador/Chart.yaml
> +version: 5.2.2
done tks @Flydiverny

2019-12-15 18:08 UTC, Flydiverny commented
/lgtm

2019-12-15 18:13 UTC, Flydiverny commented
/retest

2019-12-15 18:16 UTC, Flydiverny commented
/retest

2019-12-16 02:22 UTC, Flydiverny commented
/retest

2019-12-16 18:31 UTC, nullck commented
/retest

2019-12-16 18:39 UTC, merged