[stable/sonarqube] Add ability to add/mount extra volumes
helm/charts pull request #19364
Opened 2019-12-04 09:41 UTC by sparqueur

#### What this PR does / why we need it:
Add the ability to add/mount extra volumes

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-07 03:54 UTC, zanhsieh commented
/ok-to-test

2019-12-17 15:33 UTC, sparqueur commented
@tsiddique  @rjkernick  Do you have an idea when you might be able to review this PullRequest ?
Thanks in advance,

2019-12-19 13:33 UTC, rjkernick requested changes

2019-12-19 13:33 UTC, rjkernick commented on stable/sonarqube/Chart.yaml
> +version: 3.2.7
Please bump the minor version because this adds features.

2019-12-20 08:58 UTC, sparqueur commented
@rjkernick Done => 3.2.8

2019-12-20 13:24 UTC, sparqueur commented
All should be good, sorry I had issue with gpd signature

2020-01-08 16:07 UTC, sparqueur commented
Hi, Is there any progress about this PR ?

2020-01-13 13:24 UTC, rjkernick commented
/lgtm

2020-01-13 13:29 UTC, merged