Add redis authoration configuration in prometheus-redis-exporter chart
helm/charts pull request #19447
Opened 2019-12-07 06:54 UTC by aixeshunter

Signed-off-by: aixeshunter <aixeshunter@gmail.com>

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.
no

#### What this PR does / why we need it:
There is no redis password configuration in prometheus-redis-exporter chart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-07 06:57 UTC, aixeshunter commented
@mattfarina, @acondrat  Please review and approve this PR, thx. :)

2019-12-11 13:28 UTC, acondrat requested changes
Please document all new values in the readme. Also, please make sure to document precedence when both secret and plain passwords are defined.

2019-12-11 13:28 UTC, acondrat commented on stable/prometheus-redis-exporter/values.yaml
> +  # when redis use password to attach
```suggestion
  # Use password authentication
```

2019-12-11 13:28 UTC, acondrat commented on stable/prometheus-redis-exporter/values.yaml
> +  # redis password stored in Secret
```suggestion
  # Use existing secret (ignores previous password)
```

2019-12-11 13:28 UTC, acondrat commented on stable/prometheus-redis-exporter/values.yaml
> +  # when redis password not be stored in Secret, point it directly
```suggestion
  # Redis password (when not stored in a secret)
```

2019-12-18 07:31 UTC, aixeshunter commented
> Please document all new values in the readme. Also, please make sure to document precedence when both secret and plain passwords are defined.

@acondrat Thx for review, I resolved all. Please check it again.

2019-12-23 10:19 UTC, acondrat requested changes
Please review values' description. 
Sorry for delays on this review.

2019-12-23 10:19 UTC, acondrat commented on stable/prometheus-redis-exporter/README.md
> +| `auth.secret.name`       | Name of redis existing secret (ignores redisPassword) ||
```suggestion
| `auth.secret.name`       | Name of existing redis secret (ignores redisPassword) ||
```

2019-12-23 10:19 UTC, acondrat commented on stable/prometheus-redis-exporter/README.md
> +| `auth.enabled`       | Specifies whether redis use authentication | `false` |
```suggestion
| `auth.enabled`       | Specifies whether redis uses authentication | `false` |
```

2019-12-23 10:19 UTC, acondrat commented on stable/prometheus-redis-exporter/README.md
> +| `auth.secret.key`       | Key of redis existing secret ||
```suggestion
| `auth.secret.key`       | Name of key containing password to be retrieved from the existing secret ||
```

2019-12-23 10:19 UTC, acondrat commented on stable/prometheus-redis-exporter/README.md
> +| `auth.redisPassword`       | Point the redis password when not stored in a secret ||
```suggestion
| `auth.redisPassword`       | Redis password (when not stored in a secret) ||
```

2019-12-23 11:31 UTC, acondrat approved these changes
/lgtm

2019-12-23 11:33 UTC, acondrat commented
/ok-to-test

2019-12-23 11:37 UTC, merged

2020-03-02 13:00 UTC, eh-am commented
```
key: {{ .Values.secret.key }}
```

shouldn't it be `{{ .Values.auth.secret.key }}`?

2020-03-02 14:10 UTC, acondrat commented
> ```
> key: {{ .Values.secret.key }}
> ```
> 
> shouldn't it be `{{ .Values.auth.secret.key }}`?

Yes, I think so. Good catch!

/lgtm cancel