[stable/wordpress] adds loadBalancerSourceRanges to service
helm/charts pull request #19549
Opened 2019-12-12 03:58 UTC by denniswebb

#### What this PR does / why we need it:
Allows restricting LoadBalancer service to specific CIDR ranges. Useful for restricting access to only CDNs such as CloudFlare

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-12 10:20 UTC, alemorcuq requested changes
Please, update the `values-production.yaml` file as well.

2019-12-12 10:20 UTC, alemorcuq commented
Thanks for the PR, @denniswebb !

2019-12-12 12:54 UTC, denniswebb commented
> Please, update the `values-production.yaml` file as well.

Completely overlooked that file. Done. Thanks for the quick comment.

2019-12-13 08:30 UTC, alemorcuq commented
Hi, @denniswebb. #19579 was merged so the chart version will need another bump. Thanks!

2019-12-13 12:40 UTC, denniswebb commented
@alemorcuq Rebased and updated.

2019-12-13 13:49 UTC, alemorcuq approved these changes
LGTM

2019-12-13 13:49 UTC, alemorcuq commented
Thanks, @denniswebb ! 

You can merge this one, @carrodher

2019-12-13 13:57 UTC, carrodher commented
/ok-to-test
/lgtm

2019-12-13 14:12 UTC, merged