[stable/sentry] bump dependency redis 0.9.0
helm/charts pull request #1958
Opened 2017-09-03 18:32 UTC by scottrigby

2017-09-04 20:09 UTC, mgoodness requested changes
Another one in which nothing got bumped.

2017-09-04 20:09 UTC, mgoodness commented
/ok-to-test

2017-09-06 14:47 UTC, scottrigby commented
Same discussion as https://github.com/kubernetes/charts/pull/1963#issuecomment-327506712

2017-09-10 18:17 UTC, mgoodness approved these changes

2017-09-10 18:22 UTC, mgoodness commented
/lgtm

2017-09-10 18:22 UTC, merged