[satable/kapacitor] Use an existing secret for the InfluxDB auth
helm/charts pull request #19594
Opened 2019-12-13 20:46 UTC by afausti

#### What this PR does / why we need it:

Sometimes you need to check in the values.yaml in a repo
and you don't want to expose the secrets. With the existingSecret
option you can use an existing Kubernetes secret with the keys
`influxdb-user` and `infuxdb-password` to set the corresponding
environment variables in Kapacitor. The keys are the same as the
ones used in the `influxdb-auth` secret created by the InfluxDB
Helm chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-14 21:13 UTC, afausti commented
/assign @jackzampolin

2019-12-14 21:16 UTC, afausti commented
/assign @deepaksood619

2019-12-14 21:18 UTC, afausti commented
/assign @aisuko

2019-12-24 06:59 UTC, Aisuko commented
/ok-to-test

2019-12-24 07:03 UTC, Aisuko requested changes
There may need some small changes

2019-12-24 07:03 UTC, Aisuko commented on stable/kapacitor/Chart.yaml
> +version: 1.1.4
Add the parameter `existingSecret ` as the backward compatibility feature. I think we should bump the middle version would make more sense here.

2019-12-25 01:49 UTC, Aisuko commented
@afausti Please join the Kubernets/charts channel on Slack, and copied the PR address into the channel, there need someone who is the @helm member can have the permission to merge the PR.

2019-12-25 01:51 UTC, Aisuko commented
The channel address please see the Slack address on the README.md at the project homepage.

2020-01-24 04:26 UTC, afausti commented
I’ve asked on Kubernetes/charts channel and InfluxDB/kapacitor channel for help to merge this PR.

2020-01-25 02:59 UTC, Aisuko commented
Looks good. Thanks for your patient.

2020-01-25 03:16 UTC, Aisuko approved these changes
/approve

2020-01-28 22:33 UTC, afausti commented
/assign @jackzampolin

2020-02-14 04:32 UTC, naseemkullah commented
bump, PRs are piling up for this chart @Aisuko do you need a hand? add me as an owner if you want

2020-02-15 04:45 UTC, Aisuko commented
I will make a discussion with helm members with merging this PR.

2020-02-17 13:27 UTC, Aisuko commented
@afausti It's so long time. Thanks for your patient. I believe we can merge this after resolving the conflict.

2020-02-17 19:43 UTC, afausti commented
Thanks @Aisuko, I've bumped the minor version of the chart as discussed above. It is now 1.2.0.

2020-02-18 10:35 UTC, Aisuko approved these changes
/LGTM

2020-02-18 10:35 UTC, Aisuko commented
Thanks

2020-02-18 10:39 UTC, merged