[stable/influxdb] Set the default user from an existing secret
helm/charts pull request #19601
Opened 2019-12-14 00:46 UTC by afausti

#### What this PR does / why we need it:
Set the default user name and password in InfluxDB from an existing secret. 

When using a GitOps workflow we cannot check in a `values.yaml` that contains secrets. In my case, the secret with the InfluxDB user name and password is created by the `vault-secrets-operator` and we need the option to use an existing secret instead of creating one.

The randomly generated password option did not work for me. I'm currently using Argo CD and it keeps out-of-sync every time the password changes, see https://argoproj.github.io/argo-cd/user-guide/diffing/. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-17 02:21 UTC, Aisuko requested changes
Thanks a lot, the new feature is awesome. There may hsa some little change.

2019-12-17 02:21 UTC, Aisuko commented on stable/influxdb/templates/secret.yaml
> +{{- if .Values.setDefaultUser.user.existingSecret -}}
We know the logic here, If the parameter .`Values.setDefaultUser.user.existingSecret==true`  we do nothing here. But I believe `{{- if  not(.Values.setDefaultUser.user.existingSecret) -}}` may more clearly.

2019-12-17 02:21 UTC, Aisuko commented on stable/influxdb/Chart.yaml
> +version: 3.0.3
The new feature was backward-compatible here. So, please bump the middle version, like`3.1.0`.

2019-12-17 22:55 UTC, afausti commented
Thanks @Aisuko for the suggestions.

2019-12-20 02:12 UTC, Aisuko commented
/ok-to-test

2019-12-26 05:20 UTC, naseemkullah commented
It seems extra to have the username in the secret, can we just do this for the password instead? I agree the password should absolutely come from an existing secret.

2019-12-26 14:35 UTC, afausti commented
The secret originally created by the chart `influxdb-auth` includes both keys `influxdb-user` and `influxdb-password` I wouldn't change that behavior. In fact, the [post-install-set-auth](https://github.com/helm/charts/blob/master/stable/influxdb/templates/post-install-set-auth.yaml#L26) hook expects that. Another reason for having the username in the secret is that other applications of the InfluxData stack like Kapacitor can share the same `existingSecret`.

2019-12-26 15:53 UTC, naseemkullah commented
> The secret originally created by the chart `influxdb-auth` includes both keys `influxdb-user` and `influxdb-password` I wouldn't change that behavior. In fact, the [post-install-set-auth](https://github.com/helm/charts/blob/master/stable/influxdb/templates/post-install-set-auth.yaml#L26) hook expects that. 

Sounds good, I think this chart has had enough breaking changes lately :) and that is definitely a good enough reason but FWIW I still think it is gratuitous to treat a username as sensitive data.

> Another reason for having the username in the secret is that other applications of the InfluxData stack like Kapacitor can share the same `existingSecret` to connect to InfluxDB.

FWIW Although it would require more (potentially breaking) changes, I'm sure we could supply an influxdb username to kapacitor non-sensitively while pointing it to the existingSecret for the influxdb password.

2020-01-02 22:49 UTC, naseemkullah commented
Sounds good @afausti , thanks for explaining

2020-01-03 07:24 UTC, Aisuko approved these changes
/LGTM

2020-01-03 07:25 UTC, Aisuko commented
Thanks a lot.

2020-01-03 07:29 UTC, merged