[stable/pomerium] Bump pomerium image to 0.5.2
helm/charts pull request #19610
Opened 2019-12-15 11:59 UTC by travisgroth

#### Is this a new chart

No

#### What this PR does / why we need it:

Updates default Pomerium version to 0.5.2

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-17 14:55 UTC, travisgroth commented
/retest

2019-12-30 17:11 UTC, travisgroth commented
/retest

2019-12-30 17:25 UTC, travisgroth commented
/cc @desimone

2019-12-30 17:50 UTC, davidkarlsen requested changes

2019-12-30 17:50 UTC, davidkarlsen commented on stable/pomerium/values.yaml
> +  tag: "v0.5.2"
Please make the readme match too: https://github.com/helm/charts/blob/master/stable/pomerium/README.md

2019-12-31 04:59 UTC, desimone approved these changes
LGTM other than what @davidkarlsen already pointed out 👍

2020-01-02 03:12 UTC, desimone approved these changes
/lgtm

2020-01-02 03:17 UTC, merged