[stable/drone] add autoscaler deployment
helm/charts pull request #19642
Opened 2019-12-17 15:18 UTC by davideagle

Signed-off-by: Davíð Örn Jóhannsson @davideagle <davideaglephotos@gmail.com>

#### What this PR does / why we need it:
Enables deployment and configuration of Drone Autoscaler
@zakkg3 @paulczar 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-17 15:32 UTC, davideagle commented
/assign @christian-roggia

2020-01-10 08:42 UTC, zakkg3 requested changes
This looks nice.
Can you add some documentation on the readme. on What is this for, how it works, a use case?

2020-01-10 08:42 UTC, zakkg3 commented on stable/drone/values.yaml
> +  enabled: true
this should be false by default.

2020-01-15 15:49 UTC, zakkg3 commented
Hey, your last commit failed the test, need a version bump from 2.5.0 to 2.5.1

```
 ✖︎ drone => (version: "2.3.3", path: "stable/drone") > Chart version not ok. Needs a version bump!
```

2020-01-16 16:07 UTC, zakkg3 commented
have you commited stable/drone/templates/deployment-autoscaler.yaml  ? see no lines.

2020-01-18 04:02 UTC, zanhsieh commented
/ok-to-test

2020-02-06 16:21 UTC, zakkg3 commented
/retest
bump the version and solve README conflict so we can merge this.
thanks.

2020-03-03 20:12 UTC, christian-roggia commented
This chart is now deprecated, please refer to https://github.com/drone/charts for further support and feature requests.
/close

2020-04-17 00:55 UTC, closed without merging