[stable/kong] Allow admin_gui_auth_conf to be defined as an external secret
helm/charts pull request #19678
Opened 2019-12-18 17:27 UTC by rifelpet

#### Is this a new chart
No

#### What this PR does / why we need it:

This adds support for providing a secret name rather than the contents of `admin_gui_auth_conf` directly.

For [LDAP authentication](https://docs.konghq.com/enterprise/1.3-x/kong-manager/authentication/ldap/), the `admin_gui_auth_conf` contents include an LDAP password which would be in plaintext in the pod spec's environment variables.

This prevents the LDAP password from being exposed by keeping it in a secret defined outside of the helm chart, similar to other sensitive data.

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:

Alternatively the chart user could set `enterprise.rbac.enabled: false` and define `KONG_ENFORCE_RBAC`, `KONG_ADMIN_GUI_AUTH`, and `KONG_ADMIN_GUI_AUTH_CONF` themselves in `env:` but this approach seems more intuitive.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-18 17:35 UTC, hbagdi commented
https://github.com/helm/charts/pull/19678/files#diff-84e57a62b9b7eb781fc0d9217a3b2958L192

If you include a secret in the `env` section, does that not work?

You can do something like this in the values.yaml:
```
env:
  admin_gui_auth_conf:
    valueFrom:
      secretKeyRef:
        name: my-secret
        key: conf
```

Might seem bizzare but we do support it for such cases exactly.

cc @rainest

2019-12-18 17:38 UTC, rifelpet commented
Yes, that does work but it requires keeping `enterprise.rbac.enabled: false` and setting the other env vars as well, as i mention above.  I'm not sure which method you'd prefer but it might be worth documenting regardless, as I feel it would be a common situation for users enabling LDAP auth.

2019-12-18 22:05 UTC, rainest requested changes
@hbagdi @rifelpet secret reference from the RBAC configuration block and removal of the existing plain JSON setting makes most sense IMO:
* Both openid-connect and ldap-auth-advanced should always require including credentials in their configuration. We should force users to always use Secrets for it as such.
* basic-auth effectively never needs configuration, and works fine if no `KONG_ADMIN_GUI_AUTH_CONF` is set. We can scope the template to not set it at all if basic-auth is used.
* Although this is a breaking change, it should be fairly obvious what's necessary to fix it when upgrading: new pods should come up and will fail obviously due to lack of a Secret.

Forgot to add a comment earlier on the file itself, but assuming we do replace the existing setting entirely with a secret reference, the changelog text should reflect that this change is breaking and that users should migrate their existing admin_gui_auth_conf into a Secret.

2019-12-18 22:05 UTC, rainest commented on stable/kong/templates/deployment.yaml
>          - name: KONG_ADMIN_GUI_AUTH_CONF
KONG_ADMIN_GUI_AUTH_CONF can simply be omitted entirely for `basic-auth`, and should be in a secret for all other current auth methods (the OIDC config's client ID/secret should not be public). You should be able to simplify this so that we only set auth conf if using an auth method that needs it like so:

```
       {{- if not (eq .Values.enterprise.rbac.admin_gui_auth "basic-auth") }}
        - name: KONG_ADMIN_GUI_AUTH_CONF
          valueFrom:
            secretKeyRef:
              name: {{ .Values.enterprise.rbac.admin_gui_auth_conf_secret }}
              key: admin_gui_auth_conf
        {{- end }}
```
Technically basic-auth can accept some configuration also, but none of its options are relevant for Kong Manager.

2019-12-18 22:05 UTC, rainest commented on stable/kong/values.yaml
> +    admin_gui_auth_conf_secret: ''
Following from the comment in the deployment template, we should simply remove the plain JSON `admin_gui_auth_conf` setting and have `admin_gui_auth_conf_secret` only. Comments should still indicate that it's not required for basic-auth.

Please also add a similar "you-must-create-an-admin-gui-auth-conf-secret" stub name here--it helps make the cause of forgetting it more clear in `kubectl describe` output.

2019-12-18 22:46 UTC, rifelpet commented
@rainest I addressed your comments, PTAL.

I noticed that none of the `enterprise.rbac.*` chart values are documented anywhere in the readme, and I was a bit hesitant to add detailed instructions like the [Sessions section](https://github.com/helm/charts/tree/master/stable/kong#sessions) so perhaps someone else could step in and do that in a followup PR.

2019-12-19 02:19 UTC, rainest approved these changes
LGTM. Tests fine on my OIDC-authorized instance.

https://github.com/helm/charts/blob/master/stable/kong/README.md#rbac is the designated section for RBAC-related instructions, but is generally focused on the bare minimum to get RBAC up and running (which effectively assumes basic-auth) and Kubernetes-specific gotchas for it (e.g. the readiness probes).

admin_gui_auth_conf doesn't differ significantly from non-Kubernetes deployments, so docs.konghq.com general-purpose documentation should suffice for it (although we need to improve its documentation there also). IMO the documentation within values.yaml comments is sufficient for this.

2019-12-19 16:57 UTC, rifelpet commented
/assign @hbagdi

2019-12-19 17:16 UTC, hbagdi approved these changes
@rifelpet Thank you for contributing this enhancement. Much appreciated!

/ok-to-test
/lgtm

2019-12-19 17:21 UTC, rifelpet commented
/test pull-charts-e2e

2019-12-19 17:36 UTC, rifelpet commented
/test pull-charts-e2e

2019-12-19 17:47 UTC, merged