[stable/prometheus-blackbox-exporter] Fix PodDisruptionBudget configuration
helm/charts pull request #19707
Opened 2019-12-19 22:25 UTC by darkstarmv

Signed-off-by: Maxim Valiarovski <maxim.valiarovski@target.com>

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
This PR is moving `podDisruptionBudget.enabled` out of the `podDisruptionBudget` yaml. 
Field `enabled` breaks `helm3` deployment:
```
helm upgrade --install blackbox-exporter stable/prometheus-blackbox-exporter --version 1.6.0 --dry-run --debug
history.go:52: [debug] getting history for release blackbox-exporter
upgrade.go:79: [debug] preparing upgrade for blackbox-exporter
upgrade.go:369: [debug] copying values from blackbox-exporter (v1) to new release.
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(PodDisruptionBudget.spec): unknown field "enabled" in io.k8s.api.policy.v1beta1.PodDisruptionBudgetSpec
helm.go:76: [debug] error validating "": error validating data: ValidationError(PodDisruptionBudget.spec): unknown field "enabled" in io.k8s.api.policy.v1beta1.PodDisruptionBudgetSpec
helm.sh/helm/v3/pkg/kube.scrubValidationError
	/home/circleci/helm.sh/helm/pkg/kube/client.go:525
helm.sh/helm/v3/pkg/kube.(*Client).Build
	/home/circleci/helm.sh/helm/pkg/kube/client.go:137
helm.sh/helm/v3/pkg/action.validateManifest
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:376
helm.sh/helm/v3/pkg/action.(*Upgrade).prepareUpgrade
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:188
helm.sh/helm/v3/pkg/action.(*Upgrade).Run
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:80
main.newUpgradeCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:134
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
UPGRADE FAILED
main.newUpgradeCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:136
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```  

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2019-12-19 23:50 UTC, darkstarmv commented
/assign @gianrubio
/assign @desaintmartin

2019-12-25 15:53 UTC, naseemkullah commented
Sorry to butt in but If I may:

Values file should look SOMETHING (set commented values, default values on a per chart basis) like: 
```
podDisruptionBudget: {}
  # maxUnavailable: 1
  # minAvailable: 2
```

then template:
```
{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
...
```

As such, the `enabled` is implicit.

2019-12-26 14:25 UTC, templarfelix approved these changes

2019-12-26 14:25 UTC, templarfelix commented
lgtm

2019-12-26 14:33 UTC, devsegur approved these changes

2019-12-27 17:12 UTC, davidkarlsen commented on stable/prometheus-blackbox-exporter/templates/poddisruptionbudget.yaml
> +{{- if .Values.global.podDisruptionBudgetEnabled -}}
```suggestion
{{- if .Values.podDisruptionBudget -}}
```

2019-12-27 17:12 UTC, davidkarlsen commented on stable/prometheus-blackbox-exporter/values.yaml
> +global:
```suggestion
```

2019-12-27 17:12 UTC, davidkarlsen commented on stable/prometheus-blackbox-exporter/README.md
> +  | `podDisruptionBudgetEnabled`                  | Enable pod disruption budget                             | `true`         |
```suggestion
```

2019-12-27 17:12 UTC, davidkarlsen commented on stable/prometheus-blackbox-exporter/values.yaml
>  podDisruptionBudget:
```suggestion
podDisruptionBudget: {}
  # maxUnavailable: 0
```

2019-12-29 17:51 UTC, desaintmartin commented
Thanks!
Because it is a breaking change, you should bump the MAJOR version of this chart and explain (like in other charts like Redis) how to upgrade.
I like the solution shown by David.

/ok-to-test
/assign

2020-01-03 15:48 UTC, desaintmartin requested changes

2020-01-03 15:48 UTC, desaintmartin commented on stable/prometheus-blackbox-exporter/README.md
> +This version removes `podDisruptionBudget` from chart `values.yaml` file.
```suggestion
This version removes the `podDisruptionBudget.enabled` parameter and change the default value of `podDisruptionBudget` to `{}`, in order to fix Helm 3 compatibility.
```

Please also change default values in the list of parameters of README.md

2020-01-03 15:48 UTC, desaintmartin commented on stable/prometheus-blackbox-exporter/README.md
> +If you would like to have `podDisruptionBudget` configured for your Release add additional values file with `-f` flag to your `helm` deployment command:
```suggestion
In order to upgrade, please remove `podDisruptionBudget.enabled` from your custom values.yaml file and set the content of `podDisruptionBudget`, for example:
```

2020-01-03 15:48 UTC, desaintmartin commented on stable/prometheus-blackbox-exporter/README.md
> +```bash
```suggestion
```yaml
```

2020-01-03 15:48 UTC, desaintmartin commented on stable/prometheus-blackbox-exporter/README.md
> +$ helm upgrade --install blackbox-exporter stable/prometheus-blackbox-exporter --version=2.0.0 -f my-values.yaml
```suggestion
podDisruptionBudget:
  maxUnavailable: 1
```

2020-01-08 17:39 UTC, desaintmartin commented
Thanks!
/lgtm

2020-01-08 17:43 UTC, merged