PR for Crunchy PostgreSQL Cluster Helm Example
helm/charts pull request #198
Opened 2016-11-04 20:35 UTC by jmccormick2001

here is the crunchy postgresql helm example, I tested it on Kube 1.4.5 and Helm 2.0.0.rc.1

2016-11-08 15:01 UTC, lachie83 requested changes
Thanks for the submission. I took a first pass at review. Please take a look at this document for tech requirements of charts. https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements

2016-11-08 15:01 UTC, lachie83 commented on incubator/crunchy-postgresql-cluster/templates/master-pod.yaml
> +    image: "crunchydata/crunchy-postgres:centos7-9.5-1.2.4"
Please add these ass variables in values.yaml

2016-11-08 15:01 UTC, lachie83 commented on incubator/crunchy-postgresql-cluster/templates/master-pod.yaml
> +      value: "{{.Values.MasterPassword}}"
How about we put the passwords in a secret and then pull them into envvars?

2016-11-08 15:01 UTC, lachie83 commented on incubator/crunchy-postgresql-cluster/templates/master-pod.yaml
> +  - emptyDir: {}
Please add support for PV if this is storing non-ephemeral content

2016-11-08 15:01 UTC, lachie83 commented on incubator/crunchy-postgresql-cluster/templates/master-service.yaml
> +  type: ClusterIP
Should we convert the type to a variable

2016-11-08 15:01 UTC, lachie83 commented on incubator/crunchy-postgresql-cluster/templates/master-pod.yaml
> +  name: "{{.Values.MasterName}}"
I would suggest using a name that includes the release name to covert multiple installs in the same namespace

2016-11-08 15:01 UTC, lachie83 commented on incubator/crunchy-postgresql-cluster/templates/master-pod.yaml
> +  - name: server
Should this be something from values.yaml?

2016-11-08 15:02 UTC, lachie83 commented
@jmccormick2001 Can you please address the following -- "commit missing GitHub user"

2016-11-14 20:14 UTC, jmccormick2001 commented
added support for PVs

2016-11-14 20:15 UTC, jmccormick2001 commented on incubator/crunchy-postgresql-cluster/templates/master-pod.yaml
> +  - name: server
made the container name a value

2016-11-14 20:15 UTC, jmccormick2001 commented on incubator/crunchy-postgresql-cluster/templates/master-pod.yaml
> +  name: "{{.Values.MasterName}}"
included the release name into the name

2016-11-14 20:15 UTC, jmccormick2001 commented on incubator/crunchy-postgresql-cluster/templates/master-pod.yaml
> +      value: "{{.Values.MasterPassword}}"
added secrets for holding passwords

2016-11-14 20:17 UTC, jmccormick2001 commented on incubator/crunchy-postgresql-cluster/templates/master-pod.yaml
> +      value: "{{.Values.MasterPassword}}"
done, added secrets to hold passwords.

2016-11-14 20:40 UTC, jmccormick2001 reviewed
I think I got all the changes made you had marked in your review.  cheers.

2016-11-22 18:31 UTC, viglesiasce requested changes

2016-11-22 18:31 UTC, viglesiasce commented on incubator/crunchy-postgresql-cluster/NOTES.txt
> +=== Testing
The NOTES.txt file needs to be moved to the templates folder.

2016-11-23 14:57 UTC, jmccormick2001 commented
relocated the NOTES.txt, also added comments about NFS

2016-11-30 04:19 UTC, viglesiasce commented
This chart does not work out of the box.
Can you either:
- Use a dynamic PVC like [the postgresql chart](https://github.com/kubernetes/charts/tree/master/stable/postgresql/templates)
- Add a dependent NFS server chart

2016-11-30 04:38 UTC, viglesiasce commented
This would benefit from using a PetSet/StatefulSet of size 1. Currently, if the master pod is deleted it wont be recreated. With PetSet/StatefulSet you would get a persistent network identity and a PVC.

2016-11-30 14:33 UTC, jmccormick2001 commented
the use of StatefulSet is an interesting one I've been thinking about...I suppose if I start using that feature that any users working with an older version of Kube however the example will not work so I'm kind of torn between using it or waiting till some of these features get more out there:  initcontainers, dynamic provisioning, StatefulSet....are these examples meant to be leading edge with respect to kube features or merely examples of using Helm?

2016-11-30 22:59 UTC, jmccormick2001 commented
question...I see the postgres example refers to a PVC storage class of "storageClass: generic"

I can't seem to find where that storage class is documented or how to enable it in the kube ...any pointers?  is this an experimental feature?

2016-12-05 18:44 UTC, viglesiasce commented
Hey @jmccormick2001!

We are in a bit of a transitional state with PVC's in that they have beta support but we are using the alpha annotation to enable them. With the alpha annotation the value is ignored and is only checked to be set to something. 

For more info on the path forward check out #116

2018-12-19 18:00 UTC, lubo commented
@jmccormick2001 I see you've been working on https://github.com/CrunchyData/postgres-operator/tree/master/chart/postgres-operator. Why did you close this PR, though? Are you no longer willing to put the afford into getting the chart merged into this repository?

2018-12-19 18:21 UTC, jmccormick2001 commented
I might give this another shot.

2019-02-01 22:44 UTC, closed without merging