[stable/oauth2-proxy] Fixes to make Google templates work
helm/charts pull request #19865
Opened 2020-01-05 11:49 UTC by abh

- Also upgrade oauth-proxy to 4.1.0

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-01-14 09:35 UTC, Miouge1 commented
Can you give an example of such a values.yaml?

/ok-to-test

2020-01-14 09:37 UTC, abh commented
```
  google:
    adminEmail: admin@example.org
    serviceAccountJson: ewogICJ0eXBlIjogI...
```

2020-01-14 10:15 UTC, Miouge1 requested changes

2020-01-14 10:15 UTC, Miouge1 commented on stable/oauth2-proxy/templates/_helpers.tpl
> +{{- define "oauth2-proxy.googleSecretName" -}}
The template should also be used for `name: ...`  in `google-secret.yaml`

2020-01-14 10:15 UTC, Miouge1 commented on stable/oauth2-proxy/templates/google-secret.yaml
> +{{- if and .Values.config.google .Values.config.google.serviceAccountJson (not .Values.config.google.existingSecret) }}
When testing this I did not manage to get `service-account.json:` to work.

Here is my test values.yaml:
```
config:
  google:
    adminEmail: admin@example.org
    serviceAccountJson: Zm9v
```

And test command: `helm template --name test . --values test.yaml`

2020-01-14 10:15 UTC, Miouge1 commented on stable/oauth2-proxy/Chart.yaml
> +appVersion: 4.1.0
AFAIK, the appVersion is still 4.0.0 in master

2020-02-18 08:01 UTC, Miouge1 commented
Can you rebase on latest master to resolve merge conflicts?

2020-04-02 09:47 UTC, closed without merging