[stable/prometheus-operator] NetworkPolicy support
helm/charts pull request #19872
Opened 2020-01-06 09:09 UTC by antongorkovenko

Implements support of Network Policies for Prometheus Operator

Signed-off-by: Anton Gorkovenko <gostom@gmail.com>

#### Is this a new chart
no
#### What this PR does / why we need it:
Implements support of Network Policies for Prometheus Operator
#### Which issue this PR fixes
no
#### Special notes for your reviewer:
no
#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-01-06 09:11 UTC, antongorkovenko commented
/assign @gianrubio

2020-01-08 14:48 UTC, bismarck commented
@antongorkovenko Thanks for the PR.  This might take a little time to review because network policies are a bit tricky.  What CNI plugin did you test these changes with?

2020-01-09 12:09 UTC, antongorkovenko commented
@bismarck Calico

2020-01-13 16:20 UTC, vsliouniaev requested changes

2020-01-13 16:20 UTC, vsliouniaev commented on stable/prometheus-operator/templates/alertmanager/networkPolicy.yaml
> +        - port: 9093
I believe this port is templated

2020-01-14 07:09 UTC, antongorkovenko commented on stable/prometheus-operator/templates/alertmanager/networkPolicy.yaml
> +        - port: 9093
fixed

2020-01-18 07:43 UTC, antongorkovenko commented
/assign @vsliouniaev

2020-01-20 16:47 UTC, bismarck commented
/ok-to-test

2020-01-23 15:28 UTC, bismarck commented
@antongorkovenko I think some of these NetworkPolicies are being installed in the wrong namespace.  For example, kube-controller-manager is in the kube-system namespace which isn't necessarily the same namespace that Prometheus is deployed to. In that case you may also need to [add a namespace selector (in addition to your pod selector)](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/07-allow-traffic-from-some-pods-in-another-namespace.md) to your network policy, which introduces other complications.

2020-01-23 15:28 UTC, bismarck requested changes

2020-01-23 15:28 UTC, bismarck commented on stable/prometheus-operator/templates/prometheus/networkPolicy.yaml
> +      - port: 9090
This is also templated out.

2020-02-01 07:21 UTC, antongorkovenko commented on stable/prometheus-operator/templates/prometheus/networkPolicy.yaml
> +      - port: 9090
@bismarck updated

2020-02-01 07:26 UTC, antongorkovenko commented
> @antongorkovenko I think some of these NetworkPolicies are being installed in the wrong namespace. For example, kube-controller-manager is in the kube-system namespace which isn't necessarily the same namespace that Prometheus is deployed to. In that case you may also need to [add a namespace selector (in addition to your pod selector)](https://github.com/ahmetb/kubernetes-network-policy-recipes/blob/master/07-allow-traffic-from-some-pods-in-another-namespace.md) to your network policy, which introduces other complications.

In progress

2020-02-19 06:59 UTC, closed without merging