[stable/nginx-ingress] Fix ClusterRole creation when using namespaces
helm/charts pull request #19886
Opened 2020-01-06 19:29 UTC by Graham42

#### Is this a new chart
no

#### What this PR does / why we need it:
We want to be able to choose to deploy to a namespace and still opt-in
to ClusterRole creation.

#### Which issue this PR fixes

  - fixes #18420 

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-01-06 19:35 UTC, Graham42 commented
/assign @chiefalexander

2020-01-07 15:38 UTC, ChiefAlexander commented
/ok-to-test

2020-01-07 15:38 UTC, ChiefAlexander requested changes

2020-01-07 15:38 UTC, ChiefAlexander commented on stable/nginx-ingress/templates/clusterrole.yaml
> +{{- if and .Values.rbac.create -}}
you will also need to remove the `and`

2020-01-07 16:39 UTC, Graham42 commented on stable/nginx-ingress/templates/clusterrole.yaml
> +{{- if and .Values.rbac.create -}}
Thanks! Fixed now

2020-01-07 19:17 UTC, ChiefAlexander commented
/lgtm
Thanks!

2020-01-07 20:00 UTC, merged