[stable/ghost] Use storageClassName for ghost.
helm/charts pull request #1991
Opened 2017-09-05 04:29 UTC by gyliu513

Fixed ghost for #1869

/cc @prydonius

2017-09-05 15:52 UTC, prydonius requested changes
wait for mariadb update

2017-09-06 02:27 UTC, gyliu513 commented
@prydonius mariadb here https://github.com/kubernetes/charts/pull/2004

2017-10-19 09:48 UTC, gyliu513 commented
/cc @prydonius ready for review

2017-12-22 16:41 UTC, unguiculus commented
/lgtm

2017-12-22 16:48 UTC, merged