add eventer to heapster chart
helm/charts pull request #1998
Opened 2017-09-05 07:41 UTC by smelchior

This PR adds eventer to the heapster chart. It is part of the heapster container so i figured it is best to add it to the same deployment.
Eventer allows you to ship the Kubernetes event logs to another location.

2017-09-10 20:39 UTC, mgoodness requested changes

2017-09-10 20:39 UTC, mgoodness commented on stable/heapster/values.yaml
> +  resources:
Set `resources: {}` and comment the sub-values.

2017-09-10 20:39 UTC, mgoodness commented on stable/heapster/values.yaml
> +    resources:
Set resources: {} and comment the sub-values.

2017-09-10 20:39 UTC, mgoodness commented
/ok-to-test

2017-09-11 07:23 UTC, smelchior commented
you mean like this?
Could you explain why?

2017-09-11 12:55 UTC, mgoodness commented
That's correct. We generally avoid setting default resource requests & limits because it can be difficult for users to override them later.

2017-09-12 15:50 UTC, smelchior commented
ok, then we should be ready to go :)

2017-12-09 16:34 UTC, unguiculus commented
/lgtm

2017-12-09 16:35 UTC, merged