Add linkerd chart
helm/charts pull request #200
Opened 2016-11-04 22:10 UTC by viglesiasce

https://linkerd.io/

This was generated from `helm create` so most of the things we find in review will need to be updated there too.

2016-11-11 07:00 UTC, lachie83 requested changes
Couple of small UX related changes

2016-11-11 07:00 UTC, lachie83 commented on stable/linkerd/templates/NOTES.txt
> +  kubectl port-forward $POD_NAME 9990:9990 4140:4140
Can you please add `--namespace= {{ .Release.Namespace }}`

2016-11-11 07:00 UTC, lachie83 commented on stable/linkerd/templates/service.yaml
> +  type: LoadBalancer
Is this needed given the type on line 13?

2016-11-11 07:00 UTC, lachie83 commented on stable/linkerd/values.yaml
> +    tag: 0.8.2
Should we bump to 0.8.3 now or in another PR?

2016-11-11 07:00 UTC, lachie83 commented on stable/linkerd/templates/NOTES.txt
> +Add ports on your services that have the name {{ .Values.linkerd.portName }}
By default this statement renders as

> Add ports on your services that have the name service

I feel that's a little vague given no prior knowledge to linkerd. Can we provide an example and make that `service` pop a little?

2016-11-11 07:02 UTC, lachie83 commented
Please add README

2016-11-30 05:02 UTC, viglesiasce commented
I believe I have things patched up now.

2016-12-01 02:02 UTC, viglesiasce commented
@k8s-bot e2e test this

2016-12-12 07:04 UTC, prydonius requested changes
Sorry for the delay in looking at this @viglesiasce. Just a couple of small comments.

2016-12-12 07:04 UTC, prydonius commented on stable/linkerd/Chart.yaml
> +name: linkerd
Can you add the appropriate metadata for home, source, maintainers, icon and some keywords? e.g.

```
home: https://linkerd.io/
sources:
- https://github.com/BuoyantIO/linkerd
maintainers:
- name: Vic Iglesias
  email: viglesias@google.com
```

2016-12-12 07:04 UTC, prydonius commented on stable/linkerd/templates/config.yaml
> +---
These separators are not generally need, as Helm automatically places them.

2016-12-12 07:04 UTC, prydonius commented on stable/linkerd/templates/config.yaml
> +  name: {{ template "fullname" . }}-config
Should this have an app label?

2016-12-14 23:40 UTC, viglesiasce commented
All patched up folks. Thanks for the feedback. Will roll this all up to a PR to the `helm create` command.

2016-12-20 00:54 UTC, prydonius commented
Worked great for me @viglesiasce, thanks!

2016-12-20 00:54 UTC, prydonius approved these changes

2016-12-20 00:55 UTC, prydonius commented
@lachie83 since you've requested changes, I'll give you a chance to take a quick look

2016-12-20 06:25 UTC, lachie83 approved these changes

2016-12-20 06:25 UTC, lachie83 commented
LGTM

2016-12-21 18:22 UTC, merged