[stable/kube-state-metrics] Add service type
helm/charts pull request #2002
Opened 2017-09-05 15:27 UTC by thedebugger

2017-09-08 18:30 UTC, thedebugger commented
Hi, can i get some eyes on this PR? Thanks!

2017-09-10 17:13 UTC, mgoodness requested changes
Mostly nits, but also needs rebase

2017-09-10 17:13 UTC, mgoodness commented on stable/kube-state-metrics/templates/service.yaml
> +  type: {{ .Values.service.type }}
Add double-quotes around templates that simply echo user-provided strings.

2017-09-10 17:13 UTC, mgoodness commented on stable/kube-state-metrics/templates/service.yaml
> +    {{- if .Values.service.nodePort }}
Nit: `if` and `end` statements should be indented one level less than the lines they wrap.

2017-09-10 17:13 UTC, mgoodness commented on stable/kube-state-metrics/templates/service.yaml
> +  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
Add double-quotes around templates that simply echo user-provided strings.

2017-09-10 17:13 UTC, mgoodness commented on stable/kube-state-metrics/templates/service.yaml
> +  {{- if .Values.service.loadBalancerIP }}
Nit: as above.

2017-09-10 17:13 UTC, mgoodness commented on stable/kube-state-metrics/values.yaml
> +##nodePort: 30001
Un-comment and set to `0` (zero)

2017-09-10 17:13 UTC, mgoodness commented on stable/kube-state-metrics/values.yaml
> +##loadBalancerIP: 78.11.24.19
Un-comment and set to `""`

2017-09-10 17:13 UTC, mgoodness commented
/ok-to-test

2017-09-12 11:47 UTC, thedebugger commented
Rebased and incorporated code review feedback

2017-09-13 16:49 UTC, thedebugger commented
@mgoodness can you look at this today if you have time?

2017-09-19 17:47 UTC, thedebugger commented
hello @kubernetes/charts-maintainers, it is been a while that someone has looked at this PR. I'm reaching a point where i have to fork and manage my repo but I don't want to do that.

2017-09-20 18:22 UTC, thedebugger commented
Did another rebase

2017-10-14 17:51 UTC, unguiculus commented
/lgtm

2017-10-14 17:51 UTC, merged