[stable/sonatype-nexus]: added support for service account
helm/charts pull request #20032
Opened 2020-01-10 14:48 UTC by emas80

#### What this PR does / why we need it:

Add the possibility to specify an existing Kubernetes service account, or let the system to create one automatically.
This allows to give specific permissions to the Kubernetes service account used by Nexus instead of using the default service account.

In particular, it makes simpler to give the permissions in order to be able to upload the backup to GCP.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-01-13 13:27 UTC, rjkernick requested changes

2020-01-13 13:27 UTC, rjkernick commented on stable/sonatype-nexus/Chart.yaml
> +version: 1.21.4
Please bump the minor version as this adds features

2020-01-13 13:28 UTC, rjkernick commented
/assign

2020-01-13 13:28 UTC, rjkernick commented
Hello, all commits need signed in order for the pull request to be merged into the repository: https://github.com/helm/charts/pull/20032/checks?check_run_id=383520783

2020-01-24 14:13 UTC, emas80 commented
Hi @rjkernick , sorry for the delay I did not get any notification from GitHub :-(
I've signed the commits and fixed the minor version.

2020-01-24 14:26 UTC, rjkernick commented
One last item. Merged in a PR in front of you, please merge in the latest master and increment the chart version if needed. Don't forget to sign the commits. Thanks!

2020-01-29 20:41 UTC, rjkernick commented
/lgtm

2020-01-29 20:48 UTC, merged