[stable/owncloud] Set deployment strategy with values
helm/charts pull request #20083
Opened 2020-01-13 12:25 UTC by zabudskyi

Signed-off-by: Pavlo Zabudskyi <pavlo.zabudskyi@gmail.com>

#### What this PR does / why we need it:
We need possibility to set `.spec.strategy.type` to `Recreate` for owncloud deployment. When PVC access mode is set to `ReadWriteOnce` and pod is deleted, it can't re-map volume. Default value is set to `RollingUpdate`.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-01-14 10:40 UTC, alemorcuq requested changes

2020-01-14 10:40 UTC, alemorcuq commented on stable/owncloud/Chart.yaml
> +version: 8.0.2
The version should be a new minor.

2020-01-14 10:40 UTC, alemorcuq commented on stable/owncloud/values.yaml
> +
I would do this instead, allowing for more customization:

```yaml
## Set up update strategy for the ownCloud installation.
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
## Example:
# updateStrategy:
#  type: RollingUpdate
#  rollingUpdate:
#    maxSurge: 25%
#    maxUnavailable: 25%
updateStrategy:
  type: RollingUpdate
```

2020-01-14 10:40 UTC, alemorcuq commented on stable/owncloud/README.md
> +| `updateStrategy`                    | Owncloud deployment strategy               | `RollingUpdate`                                         |
I would change the default value to:

```Markdown
`{type: "RollingUpdate"}`
```

See the other comments.

2020-01-14 10:40 UTC, alemorcuq commented on stable/owncloud/templates/deployment.yaml
> +    type: {{ .Values.updateStrategy }}
I would do this instead, allowing for more customization:

```yaml
{{- if .Values.updateStrategy }}
strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
{{- end }}
```

2020-01-14 10:41 UTC, alemorcuq commented
Thank you for your contribution, @zabudskyi. I've left some comments on what I think would be a better implementation.

2020-01-15 12:34 UTC, zabudskyi commented
@alemorcuq 
Thank you for your feedback. I updated PR. I added Signed-off part for merge commit as well.

2020-01-15 13:56 UTC, alemorcuq commented
Thanks, @zabudskyi! The DCO is missing, see this link for how to fix it: https://github.com/helm/charts/pull/20083/checks?check_run_id=391038032

2020-01-15 14:42 UTC, zabudskyi commented
I'll open new PR

2020-01-15 14:42 UTC, closed without merging