[stable/phpmyadmin] Fix an SSL certificates directory conflict
helm/charts pull request #20086
Opened 2020-01-13 12:58 UTC by ncamn

Mount the SSL certificates used to connect to the database in  /db_certs instead of /certs, as /certs is already used by the bitnami/phpmyadmin Docker image to configure Apache internally.

Signed-off-by: Nicolas Camus <nicolas@octopulse.io>

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

No.

#### What this PR does / why we need it:

When deploying this Chart with `db.sslEnabled` set to `true`, the PHPMyAdmin container failed to start with the following error :

`
E 2020-01-13T10:26:29.810047469Z [0m[38;5;2mINFO Mounting certificates files from /certs...
I 2020-01-13T10:26:32.586060989Z nami    INFO Initializing apache
I 2020-01-13T10:26:32.611706459Z nami    INFO  apache successfully initialized
I 2020-01-13T10:26:35.412699470Z nami    INFO  Initializing php
I 2020-01-13T10:26:35.452136893Z nami    INFO  php successfully initialized
I 2020-01-13T10:26:39.185558014Z nami    INFO  Initializing phpmyadmin
I 2020-01-13T10:26:39.433519635Z phpmyad INFO  Preparing PHP environment...
I 2020-01-13T10:26:39.444187884Z phpmyad INFO  Preparing Apache environment...
I 2020-01-13T10:26:39.444529964Z phpmyad INFO  Configuring App
I 2020-01-13T10:26:39.455265308Z phpmyad INFO  Enabling SSL
I 2020-01-13T10:26:39.463243301Z phpmyad INFO  Generating blowfish_ecret
I 2020-01-13T10:26:39.465742558Z nami    INFO  phpmyadmin successfully initialized
E 2020-01-13T10:26:39.482142037Z [0m[38;5;2mINFO [0m ==> Starting phpmyadmin... 
E 2020-01-13T10:27:13.105445906Z nami    ERROR Unable to start com.bitnami.apache: AH00526: Syntax error on line 6 of /opt/bitnami/apache/conf/vhosts/phpmyadmin-https-vhost.conf:
E 2020-01-13T10:27:13.105479125Z SSLCertificateFile: file '/opt/bitnami/apache/conf/bitnami/certs/server.crt' does not exist or is empty
`

When trying to understand the issue, I found out that when setting `db.sslEnabled` to true, the Chart mounts a _/certs_ directory in the container, in which live the SSL/TLS certificates used to reach the database.

However this directory, when it exists, seems also to be linked by the _bitnami/phpmyadmin_ Docker image [entrypoint script](https://github.com/bitnami/bitnami-docker-phpmyadmin/blob/master/4/debian-9/rootfs/apache-init.sh) to the Apache configuration.

This is problematic as, in our case, the certificates present in the _/certs_ directory are meant to be used to provide an SSL connection between PHPMyAdmin and the database, not between the user's browser and the web server (Apache).

Therefore the web server init fails, as Apache does not find the right certificates to serve PHPMyAdmin on port 443 even if the image [entrypoint script](https://github.com/bitnami/bitnami-docker-phpmyadmin/blob/master/4/debian-9/rootfs/apache-init.sh) script has configured it due to the presence of the _/certs_ directory.

Long story short, to fix this I renamed the directory hosting the SSL/TLS certificates for the database to _/db_certs_.

The other option would be to update the Docker image [entrypoint script](https://github.com/bitnami/bitnami-docker-phpmyadmin/blob/master/4/debian-9/rootfs/apache-init.sh) to find out which certificates are present in the _/certs_ directory instead, but it seems outside this repository's scope.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

No opened issue is related to this PR to my knowledge.

#### Special notes for your reviewer:

Sorry if my English is bad (I'm not a native speaker), I will gladly try to reword my PR if it's not clear enough.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-01-14 11:29 UTC, alemorcuq approved these changes
LGTM

2020-01-14 11:31 UTC, alemorcuq commented
Thanks for spotting this and submitting a fix, @ncamn. Please, increase the chart version as there is a conflict.

2020-01-14 11:31 UTC, alemorcuq requested changes
Please increase the chart version as there seems to be a conflict.

2020-01-15 09:59 UTC, ncamn commented
Hi @alemorcuq, thanks for reviewing this. I rebased and amended my commit to set a correct version as requested.

2020-01-15 10:12 UTC, alemorcuq commented
Ready to merge, @carrodher.

2020-01-15 10:12 UTC, alemorcuq approved these changes

2020-01-15 10:24 UTC, carrodher commented
/ok-to-test
/lgtm

2020-01-15 10:27 UTC, merged