[stable/mediawiki] Use storageClassName for mediawiki.
helm/charts pull request #2009
Opened 2017-09-06 03:05 UTC by gyliu513

Fixed mediawiki for #1869

/cc @prydonius

2017-09-10 20:28 UTC, mgoodness commented
/retest

2017-09-10 20:43 UTC, mgoodness requested changes

2017-09-10 20:43 UTC, mgoodness commented on stable/mediawiki/templates/apache-pvc.yaml
> +{{- if .Values.nginx.persistence.apache.storageClass }}
Delete `nginx.`

2017-09-10 22:47 UTC, gyliu513 commented on stable/mediawiki/templates/apache-pvc.yaml
> +{{- if .Values.nginx.persistence.apache.storageClass }}
Done, thanks @mgoodness

2017-09-20 03:57 UTC, gyliu513 commented
@mgoodness ping

2017-10-19 09:58 UTC, gyliu513 commented
/cc @prydonius for review

2017-12-22 16:36 UTC, unguiculus commented
/ok-to-test

2017-12-22 16:41 UTC, unguiculus commented
/lgtm

2017-12-22 17:00 UTC, merged