Add gitlab-ce chart to stable.
helm/charts pull request #202
Opened 2016-11-05 07:18 UTC by gtaylor

This PR adds a basic GitLab Community Edition chart. This is the barest of bones out of the gates. Most of the values and the structure are based off of GitLab's official [OpenShift template](https://gitlab.com/gitlab-org/omnibus-gitlab/raw/master/docker/openshift-template.json).

We'll need to see how people use this and what we need to make configurable. I suspect that serious users are going to end up needing to fork this chart on their own, though. The sheer number of configurable values is high enough that we may never obtain and maintain full coverage without getting convoluted or out of date with upstream.

Some implementation notes:

* The GitLab omnibus Docker image uses a `GITLAB_OMNIBUS_CONFIG` env var for the vast majority of its config. I had initially created a ConfigMap and substituted values in via templating, but this left sensitive secrets exposed. I ended up sticking Ruby `ENV['blah']` calls in the ConfigMap and passing the values and secrets in there. This should give us the `kubectl describe pod <>` output that most expect, while "protecting" our secrets (if k8s fixes up Secrets!).
* This chart requires an `externalUrl` be passed in at installation. NOTES.txt and deployments.yaml work similarly to the minecraft chart's EULA enforcer in that they'll get a big error and a non-functioning deploy if they don't pass it in. Instructions are included on how to get out of this state.
* There are going to be a ton of configurable values, so I'm punting on listing these all in README.md. It's going to get looooong as we go.

:eyeglasses: @viglesiasce @prydonius @stanhun001

2016-11-06 00:21 UTC, chrislovecnm commented
@k8s-bot ok to test

2016-11-06 00:24 UTC, chrislovecnm requested changes
one question

2016-11-06 00:24 UTC, chrislovecnm commented on stable/gitlab-ce/templates/deployment.yaml
> +          value: wwwwwwwwwwwwwwwww
Do we want this to be dynamic param in values.yaml??

2016-11-06 04:23 UTC, gtaylor commented on stable/gitlab-ce/templates/deployment.yaml
> +          value: wwwwwwwwwwwwwwwww
Ugh, that's accidental keypress. I'll fix that.

2016-11-06 06:42 UTC, gtaylor commented
@chrislovecnm Fixed the weird DB value!

2016-11-06 14:17 UTC, chrislovecnm commented
@k8s-bot e2e test this

2016-11-06 14:17 UTC, chrislovecnm commented
Build may not be happy

2016-11-10 07:48 UTC, gtaylor commented
@chrislovecnm Yeah, I'm not sure there's much that can be done about that :/ Unless there's a way to set a value just for testing?

2016-11-15 05:59 UTC, chrislovecnm requested changes
Should we link the docs for redis and Postgres?

2016-11-15 05:59 UTC, chrislovecnm commented on stable/gitlab-ce/templates/NOTES.txt
> +        --set externalUrl=http://your-domain.com stable/gitlab-ce
What about if we run it internal only? Proxy with kubectl, an serious edge case. Or install it locally on mini kube

2016-11-15 05:59 UTC, chrislovecnm commented on stable/gitlab-ce/templates/deployment.yaml
> +  replicas: 1
I assume that this does not scale?

2016-11-15 05:59 UTC, chrislovecnm commented on stable/gitlab-ce/templates/deployment.yaml
> +        - name: http
Do we need http?

2016-11-15 05:59 UTC, chrislovecnm commented on stable/gitlab-ce/templates/deployment.yaml
> +        - name: https
What SSL key are we using for https?

2016-11-15 05:59 UTC, chrislovecnm commented on stable/gitlab-ce/values.yaml
> +#externalUrl: http://your-domain.com/
If this is required, Uncomment it

2016-11-15 05:59 UTC, chrislovecnm commented on stable/gitlab-ce/values.yaml
> +#externalUrl: http://your-domain.com/
Actually scratch that. What about if the url is on a waf?

2016-11-15 17:40 UTC, sputnick commented
I would like to see in this chart like most a global persistence.enabled true/false. If this becomes a pattern in official charts then we could perhaps make that a standard flag --persistence false. This and ingress/loadbalancer is the most problematic for testing on non cloud providers

2016-11-16 01:13 UTC, gtaylor commented on stable/gitlab-ce/templates/deployment.yaml
> +  replicas: 1
Not without a distributed filesystem and some other things. That'll definitely be one of those cases where more advanced users will fork and customize to their setup.

2016-11-16 01:15 UTC, gtaylor commented on stable/gitlab-ce/templates/NOTES.txt
> +        --set externalUrl=http://your-domain.com stable/gitlab-ce
DNS or /etc/hosts entries still work for internal-only setups.

2016-11-16 01:16 UTC, gtaylor commented on stable/gitlab-ce/templates/deployment.yaml
> +        - name: https
This is more of a placeholder for now, in that GitLab supports it, but we're not configuring it yet. I wanted to get the ports situated so we don't need to change this and the Service in the future.

2016-11-16 01:16 UTC, gtaylor commented on stable/gitlab-ce/templates/deployment.yaml
> +        - name: http
Yes. This is the default way the omnibus image is deployed.

2016-11-16 01:17 UTC, gtaylor commented on stable/gitlab-ce/values.yaml
> +#externalUrl: http://your-domain.com/
We can't un-comment it without risking a bunked install. This and the notice in NOTES.txt along with the README instructions should make sure it gets done.

2016-11-16 01:23 UTC, gtaylor commented
@sputnick A global persistence.enabled flag is not a [technical requirement](https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements), so I'm going to leave as-is. 

Aside from that, a global persistence flag is not granular enough for every chart. For example, factorio has separate saved game and mod storage. You often want the former, but don't always need or want the latter. Cassandra has separate commit logs and SS tables that that often have different IO and size demands. There are situations where you may want one in a PVC and not the other.

Ingress (nginx controller) and LBs are supported for non-cloud setups as long as they are configured, so I'm hesitant to make the chart much more complex to guess at what people need. I'm expecting that people will need to fork this chart for more advanced or rigorous production environments.

2016-11-16 02:14 UTC, sputnick commented
@gtaylor Don't get me wrong, what you say is all true but on an environment with no PVs you have to go figure out what non standard parameters disable the PVC for the main chart and then also for the dependencies. The same is true for existing charts like WordPress in K8s Stable (you need to turn off PVs for MariaDB specifically). I just consider this UX problem for the Stable charts and newbies because on a cluster like "kube-solo" or "minikube" that many start on have no PVs and in those cases there will never be a mixed situation. Btw just to be clear I was not suggesting to only have one field but both the specific and the non specific. Feel free to ignore, I know it's extra work but useful if we could start to standardise this as option as a best-practice for testing scenarios.

2016-11-17 03:15 UTC, viglesiasce commented
Worked like a charm for me. Are CI runners pre configured?

2016-11-17 03:43 UTC, gtaylor commented
CI runners are optional, so I figured I'd tackle that separately. This
chart has the potential to be quite large and complex, so this is the bare
minimum I felt comfortable submitting as a starting point.

I'd like to follow up with more work after the initial merge so we can keep
subsequent review cycles smaller. This chart is already on the more complex
side.

On Nov 16, 2016 7:15 PM, "Vic Iglesias" <notifications@github.com> wrote:

> Worked like a charm for me. Are CI runners pre configured?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/charts/pull/202#issuecomment-261143593>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAEnJN6l3E9Vr63fuBfXyeSPPXd2qG98ks5q-8bCgaJpZM4KqMYb>
> .
>

2016-11-18 05:49 UTC, lachie83 commented on stable/gitlab-ce/templates/NOTES.txt
> +        Watch the status with: 'kubectl get svc -w {{ template "fullname" . }}'
Please add --namespace {{ .Release.Namespace }}

2016-11-18 05:54 UTC, lachie83 commented on stable/gitlab-ce/templates/NOTES.txt
> +  export SERVICE_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ template "fullname" . }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
AWS doesn't return an IP resulting in 
```
echo http://$SERVICE_IP/
http:///
```

How about this?
```
kubectl describe svc {{ template "fullname" . }} --namespace {{ .Release.Namespace }} | grep Ingress | awk '{print $3}'
```

2016-11-18 05:57 UTC, lachie83 commented
Following readme resulted in pod in crash backoff loop

```bash
$ kubectl get pods -n gitlab
NAME                               READY     STATUS             RESTARTS   AGE
gitlab-gitlab-ce-490283815-pj9y6   0/1       CrashLoopBackOff   4          6m
$ kubectl logs gitlab-gitlab-ce-490283815-pj9y6 -n gitlab
Thank you for using GitLab Docker Image!
Current version: gitlab-ce=8.13.3-ce.0

Configure GitLab for your system by editing /etc/gitlab/gitlab.rb file
And restart this container to reload settings.
To do it use docker exec:

  docker exec -it gitlab vim /etc/gitlab/gitlab.rb
  docker restart gitlab

For a comprehensive list of configuration options please see the Omnibus GitLab readme
https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/README.md

If this container fails to start due to permission problems try to fix it by executing:

  docker exec -it gitlab update-permissions
  docker restart gitlab
```

2016-11-18 06:10 UTC, gtaylor commented
Please provide more detail about your environment and cluster. Make sure
the pod isn't timing out before being marked as live.

On Nov 17, 2016 9:57 PM, "Lachlan Evenson" <notifications@github.com> wrote:

> Following readme resulted in pod in crash backoff loop
>
> $ kubectl get pods -n gitlab
> NAME                               READY     STATUS             RESTARTS   AGE
> gitlab-gitlab-ce-490283815-pj9y6   0/1       CrashLoopBackOff   4          6m
> $ kubectl logs gitlab-gitlab-ce-490283815-pj9y6 -n gitlab
> Thank you for using GitLab Docker Image!
> Current version: gitlab-ce=8.13.3-ce.0
>
> Configure GitLab for your system by editing /etc/gitlab/gitlab.rb file
> And restart this container to reload settings.
> To do it use docker exec:
>
>   docker exec -it gitlab vim /etc/gitlab/gitlab.rb
>   docker restart gitlab
>
> For a comprehensive list of configuration options please see the Omnibus GitLab readmehttps://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/README.md
>
> If this container fails to start due to permission problems try to fix it by executing:
>
>   docker exec -it gitlab update-permissions
>   docker restart gitlab
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/charts/pull/202#issuecomment-261455162>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAEnJOKrHm79pHGUzDw_csbLZkkGGft-ks5q_T47gaJpZM4KqMYb>
> .
>

2016-11-18 06:20 UTC, lachie83 commented
v1.4.6 cluster running on AWS

Here's the pod description
```
kubectl describe pods gitlab-gitlab-ce-490283815-pj9y6 -n gitlab
Name:		gitlab-gitlab-ce-490283815-pj9y6
Namespace:	gitlab
Node:		ip-10-0-10-113.us-west-2.compute.internal/10.0.10.113
Start Time:	Thu, 17 Nov 2016 21:48:35 -0800
Labels:		app=gitlab-gitlab-ce
		pod-template-hash=490283815
Status:		Running
IP:		10.2.22.16
Controllers:	ReplicaSet/gitlab-gitlab-ce-490283815
Containers:
  gitlab-gitlab-ce:
    Container ID:	docker://8c98e8cfdb625564703db27b1b1e286ae95756b779007540fdf641f0ddcc9f17
    Image:		gitlab/gitlab-ce:8.13.3-ce.0
    Image ID:		docker://sha256:95e200466ec2f95bc960e3924037b87a72ce7d7fb3062c8d95caf1188e150067
    Ports:		22/TCP, 80/TCP, 443/TCP
    Limits:
      cpu:	1
      memory:	2Gi
    Requests:
      cpu:		500m
      memory:		1Gi
    State:		Running
      Started:		Thu, 17 Nov 2016 22:15:38 -0800
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Thu, 17 Nov 2016 22:10:01 -0800
      Finished:		Thu, 17 Nov 2016 22:10:29 -0800
    Ready:		False
    Restart Count:	9
    Liveness:		http-get http://:http/help delay=200s timeout=1s period=10s #success=1 #failure=10
    Readiness:		http-get http://:http/help delay=30s timeout=1s period=10s #success=1 #failure=3
    Volume Mounts:
      /etc/gitlab from gitlab-etc (rw)
      /gitlab-data from gitlab-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8adik (ro)
    Environment Variables:
      GITLAB_OMNIBUS_CONFIG:	<set to the key 'gitlab_omnibus_config' of config map 'gitlab-gitlab-ce'>
      GITLAB_ROOT_PASSWORD:	
      EXTERNAL_URL:		http://gitlab.k8s.estrado.io/
      DB_HOST:			gitlab-postgresql
      DB_USER:			<set to the key 'db-user' in secret 'gitlab-gitlab-ce'>
      DB_PASSWORD:		<set to the key 'db-password' in secret 'gitlab-gitlab-ce'>
      DB_DATABASE:		gitlab
      REDIS_HOST:		gitlab-redis
      REDIS_PASSWORD:		<set to the key 'redis-password' in secret 'gitlab-gitlab-ce'>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  gitlab-etc:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	gitlab-gitlab-ce-etc
    ReadOnly:	false
  gitlab-data:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	gitlab-gitlab-ce-data
    ReadOnly:	false
  default-token-8adik:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-8adik
QoS Class:	Burstable
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  27m		27m		2	{default-scheduler }			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "gitlab-gitlab-ce-etc", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "gitlab-gitlab-ce-etc", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "gitlab-gitlab-ce-etc", which is unexpected.]
  27m		27m		1	{default-scheduler }			Normal		Scheduled		Successfully assigned gitlab-gitlab-ce-490283815-pj9y6 to ip-10-0-10-113.us-west-2.compute.internal
  27m		27m		2	{controller-manager }			Warning		FailedMount		Failed to attach volume "pvc-a480ba9e-ad52-11e6-9519-0617ef58ec17" on node "ip-10-0-10-113.us-west-2.compute.internal" with: Error attaching EBS volume: IncorrectState: vol-0234824a0a7cc86a9 is not 'available'.
		status code: 400, request id: 
  27m		27m	2	{controller-manager }		Warning	FailedMount	Failed to attach volume "pvc-a482a0e7-ad52-11e6-9519-0617ef58ec17" on node "ip-10-0-10-113.us-west-2.compute.internal" with: Error attaching EBS volume: IncorrectState: vol-0788ce542d4130926 is not 'available'.
		status code: 400, request id: 
  27m		27m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Pulling		pulling image "gitlab/gitlab-ce:8.13.3-ce.0"
  26m		26m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Created		Created container with docker id b19f110daccf; Security:[seccomp=unconfined]
  26m		26m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Pulled		Successfully pulled image "gitlab/gitlab-ce:8.13.3-ce.0"
  26m		26m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Started		Started container with docker id b19f110daccf
  25m		25m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Created		Created container with docker id 63fcf6bc2a08; Security:[seccomp=unconfined]
  25m		25m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Started		Started container with docker id 63fcf6bc2a08
  25m		24m	2	{kubelet ip-10-0-10-113.us-west-2.compute.internal}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "gitlab-gitlab-ce" with CrashLoopBackOff: "Back-off 10s restarting failed container=gitlab-gitlab-ce pod=gitlab-gitlab-ce-490283815-pj9y6_gitlab(a4829b9e-ad52-11e6-baf4-0663940826db)"

  24m	24m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Started		Started container with docker id 15c7ac30a4b3
  24m	24m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Created		Created container with docker id 15c7ac30a4b3; Security:[seccomp=unconfined]
  24m	23m	3	{kubelet ip-10-0-10-113.us-west-2.compute.internal}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "gitlab-gitlab-ce" with CrashLoopBackOff: "Back-off 20s restarting failed container=gitlab-gitlab-ce pod=gitlab-gitlab-ce-490283815-pj9y6_gitlab(a4829b9e-ad52-11e6-baf4-0663940826db)"

  23m	23m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Created		Created container with docker id 51168dc8d06e; Security:[seccomp=unconfined]
  23m	23m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Started		Started container with docker id 51168dc8d06e
  23m	22m	4	{kubelet ip-10-0-10-113.us-west-2.compute.internal}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "gitlab-gitlab-ce" with CrashLoopBackOff: "Back-off 40s restarting failed container=gitlab-gitlab-ce pod=gitlab-gitlab-ce-490283815-pj9y6_gitlab(a4829b9e-ad52-11e6-baf4-0663940826db)"

  22m	22m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Created		Created container with docker id 74e4125a26dd; Security:[seccomp=unconfined]
  22m	22m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Started		Started container with docker id 74e4125a26dd
  21m	21m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Warning	Unhealthy	Readiness probe failed: Get http://10.2.22.16:80/help: dial tcp 10.2.22.16:80: getsockopt: connection refused
  21m	20m	7	{kubelet ip-10-0-10-113.us-west-2.compute.internal}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "gitlab-gitlab-ce" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=gitlab-gitlab-ce pod=gitlab-gitlab-ce-490283815-pj9y6_gitlab(a4829b9e-ad52-11e6-baf4-0663940826db)"

  20m	20m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Created		Created container with docker id 36c5556376d0; Security:[seccomp=unconfined]
  20m	20m	1	{kubelet ip-10-0-10-113.us-west-2.compute.internal}	spec.containers{gitlab-gitlab-ce}	Normal	Started		Started container with docker id 36c5556376d0
  20m	17m	13	{kubelet ip-10-0-10-113.us-west-2.compute.internal}						Warning	Fai [...]

2016-11-18 06:23 UTC, gtaylor commented
Can you try drastically bumping the liveness and readiness values? Based on
how and where this failed, I suspect the crazy long initial start time may
be killing this.

Also, details about your nodes would be interesting. Mem/CPU. Also also,
did Postgres and Redis start?

On Nov 17, 2016 10:20 PM, "Lachlan Evenson" <notifications@github.com>
wrote:

> v1.4.6 cluster running on AWS
>
> Here's the pod description
>
> kubectl describe pods gitlab-gitlab-ce-490283815-pj9y6 -n gitlab
> Name:       gitlab-gitlab-ce-490283815-pj9y6
> Namespace:  gitlab
> Node:       ip-10-0-10-113.us-west-2.compute.internal/10.0.10.113
> Start Time: Thu, 17 Nov 2016 21:48:35 -0800
> Labels:     app=gitlab-gitlab-ce
>         pod-template-hash=490283815
> Status:     Running
> IP:     10.2.22.16
> Controllers:    ReplicaSet/gitlab-gitlab-ce-490283815
> Containers:
>   gitlab-gitlab-ce:
>     Container ID:   docker://8c98e8cfdb625564703db27b1b1e286ae95756b779007540fdf641f0ddcc9f17
>     Image:      gitlab/gitlab-ce:8.13.3-ce.0
>     Image ID:       docker://sha256:95e200466ec2f95bc960e3924037b87a72ce7d7fb3062c8d95caf1188e150067
>     Ports:      22/TCP, 80/TCP, 443/TCP
>     Limits:
>       cpu:  1
>       memory:   2Gi
>     Requests:
>       cpu:      500m
>       memory:       1Gi
>     State:      Running
>       Started:      Thu, 17 Nov 2016 22:15:38 -0800
>     Last State:     Terminated
>       Reason:       Error
>       Exit Code:    1
>       Started:      Thu, 17 Nov 2016 22:10:01 -0800
>       Finished:     Thu, 17 Nov 2016 22:10:29 -0800
>     Ready:      False
>     Restart Count:  9
>     Liveness:       http-get http://:http/help delay=200s timeout=1s period=10s #success=1 #failure=10
>     Readiness:      http-get http://:http/help delay=30s timeout=1s period=10s #success=1 #failure=3
>     Volume Mounts:
>       /etc/gitlab from gitlab-etc (rw)
>       /gitlab-data from gitlab-data (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-8adik (ro)
>     Environment Variables:
>       GITLAB_OMNIBUS_CONFIG:    <set to the key 'gitlab_omnibus_config' of config map 'gitlab-gitlab-ce'>
>       GITLAB_ROOT_PASSWORD:
>       EXTERNAL_URL:     http://gitlab.k8s.estrado.io/
>       DB_HOST:          gitlab-postgresql
>       DB_USER:          <set to the key 'db-user' in secret 'gitlab-gitlab-ce'>
>       DB_PASSWORD:      <set to the key 'db-password' in secret 'gitlab-gitlab-ce'>
>       DB_DATABASE:      gitlab
>       REDIS_HOST:       gitlab-redis
>       REDIS_PASSWORD:       <set to the key 'redis-password' in secret 'gitlab-gitlab-ce'>
> Conditions:
>   Type      Status
>   Initialized   True
>   Ready     False
>   PodScheduled  True
> Volumes:
>   gitlab-etc:
>     Type:   PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
>     ClaimName:  gitlab-gitlab-ce-etc
>     ReadOnly:   false
>   gitlab-data:
>     Type:   PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
>     ClaimName:  gitlab-gitlab-ce-data
>     ReadOnly:   false
>   default-token-8adik:
>     Type:   Secret (a volume populated by a Secret)
>     SecretName: default-token-8adik
> QoS Class:  Burstable
> Tolerations:    <none>
> Events:
>   FirstSeen LastSeen    Count   From            SubobjectPath   Type        Reason          Message
>   --------- --------    -----   ----            -------------   --------    ------          -------
>   27m       27m     2   {default-scheduler }            Warning     FailedScheduling    [SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "gitlab-gitlab-ce-etc", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "gitlab-gitlab-ce-etc", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "gitlab-gitlab-ce-etc", which is unexpected.]
>   27m       27m     1   {default-scheduler }            Normal      Scheduled       Successfully assigned gitlab-gitlab-ce-490283815-pj9y6 to ip-10-0-10-113.us-west-2.compute.internal
>   27m       27m     2   {controller-manager }           Warning     FailedMount     Failed to attach volume "pvc-a480ba9e-ad52-11e6-9519-0617ef58ec17" on node "ip-10-0-10-113.us-west-2.compute.internal" with: Error attaching EBS volume: IncorrectState: vol-0234824a0a7cc86a9 is not 'available'.
>         status code: 400, request id:
>   27m       27m 2   {controller-manager }       Warning FailedMount Failed to attach volume "pvc-a482a0e7-ad52-11e6-9519-0617ef58ec17" on node "ip-10-0-10-113.us-west-2.compute.internal" with: Error attaching EBS volume: IncorrectState: vol-0788ce542d4130926 is not 'available'.
>         status code: 400, request id:
>   27m       27m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Pulling     pulling image "gitlab/gitlab-ce:8.13.3-ce.0"
>   26m       26m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Created     Created container with docker id b19f110daccf; Security:[seccomp=unconfined]
>   26m       26m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Pulled      Successfully pulled image "gitlab/gitlab-ce:8.13.3-ce.0"
>   26m       26m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Started     Started container with docker id b19f110daccf
>   25m       25m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Created     Created container with docker id 63fcf6bc2a08; Security:[seccomp=unconfined]
>   25m       25m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Started     Started container with docker id 63fcf6bc2a08
>   25m       24m 2   {kubelet ip-10-0-10-113.us-west-2.compute.internal}                     Warning FailedSync  Error syncing pod, skipping: failed to "StartContainer" for "gitlab-gitlab-ce" with CrashLoopBackOff: "Back-off 10s restarting failed container=gitlab-gitlab-ce pod=gitlab-gitlab-ce-490283815-pj9y6_gitlab(a4829b9e-ad52-11e6-baf4-0663940826db)"
>
>   24m   24m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Started     Started container with docker id 15c7ac30a4b3
>   24m   24m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Created     Created container with docker id 15c7ac30a4b3; Security:[seccomp=unconfined]
>   24m   23m 3   {kubelet ip-10-0-10-113.us-west-2.compute.internal}                     Warning FailedSync  Error syncing pod, skipping: failed to "StartContainer" for "gitlab-gitlab-ce" with CrashLoopBackOff: "Back-off 20s restarting failed container=gitlab-gitlab-ce pod=gitlab-gitlab-ce-490283815-pj9y6_gitlab(a4829b9e-ad52-11e6-baf4-0663940826db)"
>
>   23m   23m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Created     Created container with docker id 51168dc8d06e; Security:[seccomp=unconfined]
>   23m   23m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Started     Started container with docker id 51168dc8d06e
>   23m   22m 4   {kubelet ip-10-0-10-113.us-west-2.compute.internal}                     Warning FailedSync  Error syncing pod, skipping: failed to "StartContainer" for "gitlab-gitlab-ce" with CrashLoopBackOff: "Back-off 40s restarting failed container=gitlab-gitlab-ce pod=gitlab-gitlab-ce-490283815-pj9y6_gitlab(a4829b9e-ad52-11e6-baf4-0663940826db)"
>
>   22m   22m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Created     Created container with docker id 74e4125a26dd; Security:[seccomp=unconfined]
>   22m   22m 1   {kubelet ip-10-0-10-113.us-west-2.compute.internal} spec.containers{gitlab-gitlab-ce}   Normal  Sta [...]

2016-11-18 06:34 UTC, lachie83 commented
Dependancies missing on my end. This did the trick
```bash
$helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "deis" chart repository
...Successfully got an update from the "levo-charts" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading redis from repo http://storage.googleapis.com/kubernetes-charts
Downloading postgresql from repo http://storage.googleapis.com/kubernetes-charts
```

2016-11-18 06:40 UTC, gtaylor commented
Hm, that's weird. Is this something that needs to be committed?

2016-11-18 06:43 UTC, lachie83 commented
I don't think so. I would like to try with a chart from a repo. I'm installing from directory

2016-11-18 06:44 UTC, lachie83 commented
I cannot login when creating a password via the webui upon first login. Can you confirm that I should be using admin as the username?

2016-11-18 07:00 UTC, lachie83 commented on stable/gitlab-ce/templates/NOTES.txt
> +  Username: admin
This should be root

2016-11-18 07:01 UTC, lachie83 commented
Confirmed default username should be root

2016-11-18 07:02 UTC, lachie83 commented
Noticed pathological logging of the following error in the gitlab container

```
ActionController::RoutingError (No route matches [POST] "/"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  sentry-raven (2.0.2) lib/raven/integrations/rack.rb:50:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  rack (1.6.4) lib/rack/urlmap.rb:66:in `block in call'
  rack (1.6.4) lib/rack/urlmap.rb:50:in `each'
  rack (1.6.4) lib/rack/urlmap.rb:50:in `call'
  unicorn (5.1.0) lib/unicorn/http_server.rb:562:in `process_client'
  unicorn-worker-killer (0.4.4) lib/unicorn/worker_killer.rb:52:in `process_client'
  unicorn (5.1.0) lib/unicorn/http_server.rb:658:in `worker_loop'
  unicorn (5.1.0) lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  unicorn (5.1.0) lib/unicorn/http_server.rb:132:in `start'
  unicorn (5.1.0) bin/unicorn:126:in `<top (required)>'
  /opt/gitlab/embedded/service/gem/ruby/2.3.0/bin/unicorn:22:in `load'
  /opt/gitlab/embedded/service/gem/ruby/2.3.0/bin/unicorn:22:in `<top (required)>'
  bundler (1.13.5) lib/bundler/cli/exec.rb:74:in `load'
  bundler (1.13.5) lib/bundler/cli/exec.rb:74:in `kernel_load'
  bundler (1.13.5) lib/bundler/cli/exec.rb:27:in `run'
  bundler (1.13.5) lib/bundler/cli.rb:332:in `exec'
  bundler (1.13.5) lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  bundler (1.13.5) lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  bundler (1.13.5) lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  bundler (1.13.5) lib/bundler/cli.rb:20:in `dispatch'
  bundler (1.13.5) lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  bundler (1.13.5) lib/bundler/cli.rb:11:in `start'
  bundler (1.13.5) exe/bundle:34:in `block in <top (required)>'
  bundler (1.13.5) lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
  bundler (1.13.5) exe/bundle:26:in `<top (required)>'
  /opt/gitlab/embedded/bin/bundle:22:in `load'
  /opt/gitlab/embedded/bin/bundle:22:in `<main>'
```

2016-11-30 15:59 UTC, dosire commented
@ maxlazio can you or DJ maybe help getting this to the finish line?

2016-12-01 02:05 UTC, viglesiasce commented
@k8s-bot ok to test

2016-12-01 02:07 UTC, gtaylor commented
Sorry for the radio silence. I'm erratic during paternity leave. Happy to answer questions. I spun my test GKE cluster down for the time being.

2016-12-05 18:45 UTC, viglesiasce commented
@k8s-bot ok to test

2016-12-05 18:53 UTC, viglesiasce requested changes

2016-12-05 18:53 UTC, viglesiasce commented on stable/gitlab-ce/requirements.lock
> +  repository: http://storage.googleapis.com/kubernetes-charts
The default repo changed to http://kubernetes-charts.storage.googleapis.com which is why CI is failing. 

Checkout:
#234

2016-12-08 11:00 UTC, maxlazio commented
We are happy to land a hand if necessary. /cc @gtaylor

2016-12-09 18:32 UTC, viglesiasce approved these changes

2016-12-10 08:14 UTC, gtaylor commented
Thanks a lot for the cleanup, @viglesiasce!

@maxlazio it might be good for us to circle back around as far as next steps for improving this chart after initial merge. We don't have CI runners in and only have a subset of the potentially configurable parameters represented in values.yaml. I'm sure there are quite a few things that could be done better than my initial attempt.

2016-12-12 06:14 UTC, prydonius commented
Thanks a lot @gtaylor!

2016-12-12 06:14 UTC, merged

2016-12-12 17:02 UTC, maxlazio commented
Thanks @gtaylor, I've created https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1790 as a holding issue for further improvements.

2016-12-12 17:46 UTC, stanhu commented
Great work, @gtaylor!

2016-12-12 17:48 UTC, stanhu commented on stable/gitlab-ce/values.yaml
> +image: gitlab/gitlab-ce:8.13.3-ce.0
We should bump this to 8.13.9 or 8.14.4.

2016-12-12 19:02 UTC, gtaylor commented
I can send a PR for 8.14.x tonight unless someone else beats me to it.

On Dec 12, 2016 9:48 AM, "Stan Hu" <notifications@github.com> wrote:

*@stanhu* commented on this pull request.
------------------------------

In stable/gitlab-ce/values.yaml
<https://github.com/kubernetes/charts/pull/202#pullrequestreview-12509886>:

> @@ -0,0 +1,89 @@
+## GitLab CE image
+## ref: https://hub.docker.com/r/gitlab/gitlab-ce/tags/
+##
+image: gitlab/gitlab-ce:8.13.3-ce.0

We should bump this to 8.13.9 or 8.14.4.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/charts/pull/202#pullrequestreview-12509886>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AAEnJIw5dp5ixU-r9UhiaZoVv6Dek-mjks5rHYjngaJpZM4KqMYb>
.