[stable/locsut] Adapt locust helm chart to k8s compatibility.
helm/charts pull request #20379
Opened 2020-01-27 10:39 UTC by stefanandres

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

This PR changes the objects used in the locust helm charts and makes them k8s 1.16 compatible.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-03-10 16:16 UTC, sekka1 commented
Will take a look.

2020-03-18 15:16 UTC, sekka1 commented
Sorry...still trying to find time to test this out.  Will update.

2020-04-27 11:02 UTC, haugene commented on stable/locust/templates/worker-deploy.yaml
> +{{ toYaml . | indent 8 }}
Getting a lint-error here: ```[ERROR] templates/: parse error at (locust/templates/worker-deploy.yaml:80): unexpected EOF```

You're missing an `{{- end }}` block at the end.

2020-04-27 11:04 UTC, haugene requested changes
Looks good to me overall. You need to add the {{- end }} block at the end of the worker-deploy template, but adding this it installs and works as expected.

2020-04-27 11:07 UTC, haugene commented
Hello @stefanandres and sorry about the terrible delay on this PR. I've had it in the back of my mind and never getting to prioritise it. I've spun up a new cluster now and I'm going to try to review and get merged as many of the PRs here as I can this week.

Could you add the `{{- end }}` line as I've suggested and then I think all the tests will pass and we can mark this ready for merging 😄

2020-04-29 13:39 UTC, haugene commented
The commit from this PR is now merged through #22186 with the lint error fix I mentioned.
This PR can be closed. Thank you @stefanandres for keeping the Chart up to date, sorry about the delay!

I can't close the PR, so either you can or the stale bot will do it at some point 😄

2020-04-29 13:39 UTC, haugene commented
/hold

2020-05-04 08:27 UTC, stefanandres commented
thanks!

2020-05-04 08:27 UTC, closed without merging