[stable/minio] Fixes Post-install-create-bucket-job fails on openshift
helm/charts pull request #20766
Opened 2020-02-14 17:25 UTC by Jaydee94

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
This PR adds a new value for optionally configuring the config-dir of the minIO-client.
The default config-dir (default: "/root/.mc") does not work on OpenShift.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #20757

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-02-14 17:28 UTC, Jaydee94 commented
/assign @wlan0

2020-02-14 18:10 UTC, harshavardhana requested changes

2020-02-14 18:10 UTC, harshavardhana commented on stable/minio/templates/_helper_create_bucket.txt
> +MC_CALL="/usr/bin/mc ${MC_CONFIG_DIR}"
you are missing `--config-dir`

2020-02-14 18:10 UTC, harshavardhana commented on stable/minio/templates/_helper_create_bucket.txt
> +MC_CALL="/usr/bin/mc"
Just call this `MC` to be simple

```suggestion
MC="/usr/bin/mc"
```

2020-02-14 18:10 UTC, harshavardhana commented on stable/minio/README.md
> +| `mcConfigDir`                             | Customize the config-dir of the MinIO client - mc (default: "/root/.mc")                                                                | `""`
This is not needed we already have `configPathmc` can that not be re-purposed?

2020-02-14 18:10 UTC, harshavardhana commented on stable/minio/templates/_helper_create_bucket.txt
> +{{- if .Values.mcConfigDir }}
This should be `configPathmc` instead of `mcConfigDir`

2020-02-14 18:10 UTC, harshavardhana commented on stable/minio/values.yaml
> +mcConfigDir: ""
As suggested `configPathmc` serves the same purpose unfortunately it was never used.

2020-02-14 18:11 UTC, harshavardhana commented
/approve cancel

2020-02-14 18:26 UTC, Jaydee94 commented
@harshavardhana Thanks for youre review. I have added your suggestions and reused the variable configPathmc.

2020-02-17 02:29 UTC, harshavardhana commented
/ok-to-test

2020-02-17 02:30 UTC, harshavardhana commented
/lgtm

2020-02-17 02:37 UTC, merged