[incubator/gitea] Initial commit of chart.
helm/charts pull request #2083
Opened 2017-09-10 20:02 UTC by jpds

2017-10-16 19:08 UTC, viglesiasce commented
/ok-to-test

2017-11-03 16:23 UTC, unguiculus requested changes
Note that we've started namespacing templates (see #1785). You should apply this to your chart (can be done in another PR) in order for this chart to move to stable.

2017-11-03 16:23 UTC, unguiculus commented on incubator/gitea/templates/configmap.yaml
> +    app: {{ template "fullname" . }}-config
`app` label should be `{{ template "name" . }}` on all resources.

2017-11-03 16:23 UTC, unguiculus commented on incubator/gitea/templates/configmap.yaml
> +  name: {{ template "fullname" . }}-config
All other resources are named `{{ template "fullname" . }}`. So should be the configmap.

2017-11-03 16:23 UTC, unguiculus commented on incubator/gitea/templates/configmap.yaml
> +    component: {{ default "gitea" .Values.service.nameOverride }}
I don't see why a `component` label on the configmap would make sense. I'd suggest you remove it.

2017-11-13 20:53 UTC, unguiculus commented
Marking this a stale. Please update within one week.

2017-11-22 21:09 UTC, viglesiasce commented
Closing as stale.

2017-11-22 21:09 UTC, closed without merging