[stable/coredns] Add RBAC support
helm/charts pull request #2087
Opened 2017-09-11 12:44 UTC by SeMeKh

This is needed in case of kubernetes' middleware being used.

Access rules are based on:
https://raw.githubusercontent.com/coredns/deployment/master/kubernetes/coredns-1.6.yaml.sed

2017-09-11 13:11 UTC, SeMeKh commented
Bump: Verify CLA.

2017-10-04 17:59 UTC, unguiculus commented
Thanks for the PR. We've developed kind of a best practice for configuring RBAC. Please take this PR as reference: https://github.com/coreos/alb-ingress-controller/pull/146

2017-10-05 06:57 UTC, SeMeKh commented
@unguiculus Thanks. Applied.

2017-10-12 12:36 UTC, unguiculus requested changes

2017-10-12 12:36 UTC, unguiculus commented on stable/coredns/templates/rbac.yaml
> +{{- if (.Values.middleware.kubernetes.enabled) and (.Values.rbac.create) }}
This won't work. `and` is a function in Go templates. This should work:

`{{- if and .Values.middleware.kubernetes.enabled .Values.rbac.create }}`

2017-10-12 12:36 UTC, unguiculus commented on stable/coredns/templates/rbac.yaml
> +  name: {{ template "coredns.fullname" . }}
Please add labels `chart`, `heritage`, `release`, `app` to all RBAC resources. You can copy them from the deployment.

2017-10-30 14:21 UTC, unguiculus commented
Marking this a stale. Please update within one week.

2017-11-02 06:10 UTC, SeMeKh commented
@unguiculus Done.

2017-11-02 16:18 UTC, unguiculus requested changes

2017-11-02 16:18 UTC, unguiculus commented on stable/coredns/values.yaml
> +  create: true
Default should be `false`.

2017-11-02 16:52 UTC, SeMeKh commented
@unguiculus Fixed.

2017-11-02 17:30 UTC, unguiculus approved these changes

2017-11-02 17:30 UTC, unguiculus commented
/ok-to-test

2017-11-02 17:41 UTC, merged