[Weave Scope] Add priorityClassName for DaemonSet
helm/charts pull request #20893
Opened 2020-02-20 04:33 UTC by titilambert

#### Is this a new chart
No

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-02-20 04:43 UTC, djsly requested changes

2020-02-20 04:43 UTC, djsly commented on stable/weave-scope/README.md
> +| **probeToken** | the token used to connect to Weave Cloud -- this is not needed for connecting to non-cloud Scope frontends | |
duplicated line

2020-02-20 17:13 UTC, djsly commented
@fbarl  @dholbach 

Could one of you two review and accept ?

Thanks!

2020-02-20 17:15 UTC, titilambert commented on stable/weave-scope/README.md
> +| **probeToken** | the token used to connect to Weave Cloud -- this is not needed for connecting to non-cloud Scope frontends | |
done

2020-02-26 17:00 UTC, titilambert commented
@fbarl @dholbach Any news on this PR ?

2020-02-26 18:30 UTC, djsly commented
@bboreham could you also help with this request

2020-02-26 22:22 UTC, davidkarlsen commented
/ok-to-test
/assign

2020-02-26 22:35 UTC, davidkarlsen commented
/lgtm

2020-02-26 22:43 UTC, merged

2020-02-27 01:40 UTC, djsly commented
thanks a lot @davidkarlsen , really appreciate