Add fluentd-cloudwatch log forwarder
helm/charts pull request #211
Opened 2016-11-06 22:58 UTC by icereval

Adds a [Fluentd](https://www.fluentd.org/) [Cloudwatch](https://aws.amazon.com/cloudwatch/) chart adapted from [fluentd-elasticsearch](https://github.com/kubernetes/kubernetes/blob/a1f20cbdf4bd2f29f1a9c19d8ca7dfa56ae22380/cluster/addons/fluentd-elasticsearch/fluentd-es-image/td-agent.conf).

@jmcarp

2016-11-10 19:30 UTC, prydonius commented on incubator/fluentd-cloudwatch/templates/daemonset.yaml
> +        {{- include "toYaml" .Values.annotations | indent 8 }}
Helm now comes with a built-in `toYaml` function, so you can change this to:
```
      annotations:
{{- toYaml .Values.annotations | indent 8 }}
```

Note though, that it needs to be unindented.

2016-11-10 19:30 UTC, prydonius commented on incubator/fluentd-cloudwatch/values.yaml
> +namespace: kube-system
Is the `kube-system` default a hard requirement? Generally we prefer the namespace be managed by `helm` using the `--namespace` flag.

2016-11-10 19:30 UTC, prydonius commented
@k8s-bot ok to test

2016-11-10 23:24 UTC, mgoodness requested changes

2016-11-10 23:24 UTC, mgoodness commented on incubator/fluentd-cloudwatch/README.md
> +| `image`                    | Image                                      | `18fgsa/fluentd-cloudwatch:{VERSION}`                      |
Don't need the `:{VERSION}` here since it's declared in `imageTag`

2016-11-10 23:24 UTC, mgoodness commented on incubator/fluentd-cloudwatch/templates/daemonset.yaml
> +        {{- include "toYaml" .Values.annotations | indent 8 }}
My approach for this is to use a simple key/value iterator:

```
annotations:
{{- range $key, $value := .Values.annotations }}
  {{ $key }}: {{ $value }}
{{- end }}
```

Annotations are only ever k:v anyway, so there's no need to feed them through the toYaml filter.

2016-11-10 23:24 UTC, mgoodness commented on incubator/fluentd-cloudwatch/templates/daemonset.yaml
> +    kubernetes.io/cluster-service: "true"
I don't think the `cluster-service` label is needed/useful. Per the [add-on docs](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons), it only has an effect on static manifests.

2016-11-10 23:24 UTC, mgoodness commented on incubator/fluentd-cloudwatch/templates/daemonset.yaml
> +      terminationGracePeriodSeconds: 30
Would you consider adding `hostNetwork: {{ default false .Values.hostNetwork }}` here? We rely on it to create journald log streams using the hostname.

2016-11-10 23:24 UTC, mgoodness commented on incubator/fluentd-cloudwatch/templates/configmap.yaml
> +    </match>
I recommend/request moving the fluentd config to a values.yaml key, then templating it into a ConfigMap. That would make this more of a generic fluentd chart (though with CloudWatch/ES defaults), allowing others to provide their own, custom image & settings.

2016-11-12 01:50 UTC, icereval commented
changes made from review, thanks!

found a bug when testing w/ annotations and reported:
- https://github.com/kubernetes/helm/issues/1540

2016-11-22 18:36 UTC, viglesiasce commented
Is it possible to make this the `fluentd` chart instead of the `fluentd-cloudwatch` chart? Can we move the config file (or at least its relevant parts) into the values file (similar to the [prometheus](https://github.com/kubernetes/charts/tree/master/stable/prometheus) chart)?

2016-11-27 21:20 UTC, icereval commented
I'll move the current `td-agent.conf` into the `values.yaml` and update the chart.

As for a generic chart, it seems possible though it might complicate the deployments and overall maintenance of the chart more than one would like.

Some thoughts on a possible implementation:

- Environment variables as a generic variable to support platforms like AWS.
- Platform & OS specific configurations in the `values.yaml` for `td-agent.conf` configurations.
- Image can be part of the platform/os `values.yaml` configuration or a generic image w/ all ruby gems installed.

```yaml
fluentd:
  env:
    AWS_REGION: us-east-1
    LOG_GROUP_NAME: kubernetes
  platform: googleCloud
  configurations:
    # source: https://github.com/kubernetes/kubernetes/blob/b5b47620f5f13ec2d45dd8879206b99f9a7ecc2f/cluster/addons/fluentd-gcp/fluentd-gcp-image/google-fluentd.conf
    googleCloud:
      image: kubernetes/fluentd-gcp:latest
      tdAgent: |
        # This configuration file for Fluentd / td-agent is used
        # to watch changes to Docker log files that live in the
        ...
    awsCloudWatch:
      image: 18fgsa/fluentd-cloudwatch:0.1.0
      tdAgent: |
        ...
    googleCloudJournal: |
      ...
    elasticsearch: |
      ...
```

Google Cloud

```console
$ helm install --name my-release \
  --set fluentd.platform=googleCloud \
    incubator/fluentd
```

Google Cloud Journal

```console
$ helm install --name my-release \
  --set fluentd.platform=googleCloudJournal \
    incubator/fluentd
```

AWS CloudWatch

```console
$ helm install --name my-release \
  --set fluentd.platform=awsCloudWatch, \
    fluentd.env.AWS_REGION=us-east-1, \
    fluentd.env.LOG_GROUP_NAME=kubernetes \
    incubator/fluentd
```

ElasticSearch

```console
$ helm install --name my-release \
  --set fluentd.platform=elasticseach, \
    fluentd.env.ELASTIC_SEARCH_HOST=elasticsearch-logging, \
    fluentd.env.ELASTIC_SEARCH_PORT=9200 \
    incubator/fluentd
```

Thoughts?

2016-11-30 05:52 UTC, viglesiasce commented
I really like the idea of allowing configurability of the platform to help guide users to the right set of working plugins and configs. How about something like:

```yaml
fluentd:
  env:
    AWS_REGION: us-east-1
    LOG_GROUP_NAME: kubernetes
  platform: googleCloud
```

Then having the logic for which image to use in an if statement of the DaemonSet and a similar block  in the ConfigMap.

2016-12-01 02:05 UTC, viglesiasce commented
@k8s-bot ok to test

2017-01-13 05:50 UTC, viglesiasce commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.kubernetes.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/charts/211)
<!-- Reviewable:end -->

2017-01-23 23:52 UTC, aaglenn commented
Apologies if this is out of line. I came across this PR while looking for a `fluentd` Chart. My use case is strictly as a `syslog` ingest to `influxdb` store. I would like to voice my support for a generic, configurable `fluentd` Chart.

2017-01-31 19:19 UTC, viglesiasce commented
@aaglenn not out of line at all! Thanks for providing your feedback.

2017-02-08 03:03 UTC, icereval commented
Time is spread to thin and I'm not finding an opportunity to investigate the complexities of making this more agnostic, gonna close for now.

2017-02-08 03:03 UTC, closed without merging

2017-02-08 03:09 UTC, prydonius commented
FWIW I'd be okay merging this as-is and perhaps someone else can work on making it more agnostic, given it's in incubator.

2017-02-08 03:30 UTC, mgoodness commented
@icereval Do you mind if I step in and work on it? Mostly there, IMHO. I have an idea about making it generic while providing some example (yet usable) out-of-the-box configs.

2017-02-08 09:15 UTC, icereval commented
@mgoodness please do, not a problem at all

2017-03-14 09:50 UTC, so0k commented
@mgoodness, as mentioned in https://github.com/fluent/fluentd-kubernetes-daemonset/issues/3 - I'm making the base fluentd configurable so that multiple tags exist based on the plugins available within. I had created a PR for a fluentd-logentries Chart previously, but will look at how to use this work to base on.

old PR: https://github.com/kubernetes/charts/pull/779

2017-03-15 05:15 UTC, so0k commented
PR for unified fluentd repository @icereval - is it ok if I add your cloudwatch fluentd conf in there?

https://github.com/fluent/fluentd-kubernetes-daemonset/pull/4

2017-03-15 07:31 UTC, so0k commented
@viglesiasce - I personally prefer config files to be in a separate folder and use the helm `toYaml` feature based on the config dir as follows: 

- [config file](https://github.com/kubernetes/charts/blob/6b20d270f48fd6f56001fbd657790664e1d18561/incubator/fluentd-logentries/secrets/logentries-tokens.sample) (in this case it has secrets)
- [helm template consuming all config files](https://github.com/kubernetes/charts/blob/6b20d270f48fd6f56001fbd657790664e1d18561/incubator/fluentd-logentries/templates/secret.yaml) 

The advantage this gives is that you do not need to worry about the yaml format (and spacing) which you do have to worry about if you work with config files that are embedded in yaml.

Your thoughts?

2017-04-05 17:29 UTC, so0k commented
I believe this is relevant to this PR; https://github.com/krallistic/kubernetes-fluentd