Neo4j configure auth
helm/charts pull request #2114
Opened 2017-09-14 11:33 UTC by mneedham

2017-09-17 08:46 UTC, unguiculus requested changes
It should be possible to specify or auto-generate the password instead of having to change it after the installation. Tests should then use this password instead of changing it. Use a secret for the password. Here's an example: https://github.com/kubernetes/charts/blob/master/stable/mariadb/templates/secrets.yaml

2017-09-17 08:46 UTC, unguiculus commented on incubator/neo4j/templates/NOTES.txt
> +kubectl logs -l "app=neo4j,component=core"
Don't hard-code the app label:
-> `kubectl logs -l "app={{ template "neo4j.name" . }},component=core"`

2017-09-17 08:46 UTC, unguiculus commented on incubator/neo4j/templates/tests/test-config.yaml
> +          kubectl exec $name -- bin/cypher-shell -u neo4j -p neo4j "CALL dbms.security.changePassword('newPassword')"
Tests should not change the password.

2017-10-01 14:53 UTC, mneedham commented
@unguiculus just got around to addressing your suggestions. I've now implemented something similar to the Maria DB one with auto generated password stored in secrets. 

Let me know if there's anything else I should change.

2017-10-11 11:03 UTC, mneedham commented
@unguiculus Pinging to see if there's anything else I need to do :)

2017-10-12 12:19 UTC, unguiculus requested changes
Sorry for the delay. We're almost there.

2017-10-12 12:19 UTC, unguiculus commented on incubator/neo4j/templates/secrets.yml
> +    app: {{ template "neo4j.secrets.fullname" . }}
`app: {{ template "neo4j.name" . }}`

2017-10-12 12:19 UTC, unguiculus commented on incubator/neo4j/templates/NOTES.txt
> +    --image=neo4j:3.2.1-enterprise \
`imageTag` is `3.2.3`

2017-10-12 16:41 UTC, mneedham commented
@unguiculus done!

2017-10-12 18:43 UTC, unguiculus requested changes
Please don't squash commits when updating the PR. Github can't show the changes then. The PR will be squashed anyway when it is merged.

2017-10-12 18:43 UTC, unguiculus commented on incubator/neo4j/templates/secrets.yml
> +    app: app: {{ template "neo4j.name" . }}
One `app:` too many

2017-10-12 18:43 UTC, unguiculus commented on incubator/neo4j/templates/secrets.yml
> +  name: app: {{ template "neo4j.name" . }}
You should have only changed the `app` label, not the name. Please change it back to `{{ template "neo4j.secrets.fullname" . }}`

2017-10-12 21:45 UTC, mneedham commented on incubator/neo4j/templates/secrets.yml
> +    app: app: {{ template "neo4j.name" . }}
@unguiculus ooops, sorry. Have tried again.

2017-10-13 07:33 UTC, unguiculus commented
/ok-to-test

2017-10-13 07:37 UTC, unguiculus approved these changes

2017-10-25 20:13 UTC, unguiculus commented
I installed the chart successfully and ran tests on my GKE cluster. Tests seems to never finish. Here's the test log I get:

```
$ stern misty-bat-neo4j-service-test-1xcb3                                                                                      ± ★ ✎ ⫘ (97e8557)
+ misty-bat-neo4j-service-test-1xcb3 › misty-bat-ui-test
misty-bat-neo4j-service-test-1xcb3 misty-bat-ui-test 1..2
misty-bat-neo4j-service-test-1xcb3 misty-bat-ui-test ok 1 Testing Neo4j cluster has quorum
misty-bat-neo4j-service-test-1xcb3 misty-bat-ui-test ok 2 Testing we can get the cluster role of each server
```

2017-11-03 11:38 UTC, unguiculus commented
@mneedham Did you get a chance to look at the tests?

2017-11-07 10:21 UTC, mneedham commented
@unguiculus I've just tried it locally using these commands:

```
$ helm init && kubectl rollout status -w deployment/tiller-deploy --namespace=kube-system
$ helm install incubator/neo4j --wait --name neo-helm

$ helm test neo-helm
RUNNING: neo-helm-neo4j-service-test-gmp9b
PASSED: neo-helm-neo4j-service-test-gmp9b
```

And it seems happy. I have similar logs to the ones you're seeing:

```
$ kubectl logs neo-helm-neo4j-service-test-gmp9b
1..2
ok 1 Testing Neo4j cluster has quorum
ok 2 Testing we can get the cluster role of each server
```

2017-11-07 10:24 UTC, mneedham commented
The lint checker is unhappy with the yml prefix so I've renamed the secret file

2017-11-07 16:43 UTC, unguiculus commented
Please update to latest master. This will probably fix the linting issue.

2017-11-07 16:43 UTC, unguiculus commented
/retest

2017-11-07 17:12 UTC, mneedham commented
I've rebased against master

2017-11-07 17:48 UTC, unguiculus commented
I ran Helm tests successfully on my cluster. CI probably just times out.

2017-11-07 17:48 UTC, unguiculus commented
/lgtm

2017-11-07 17:51 UTC, merged

2017-11-07 17:51 UTC, unguiculus commented
I think you could move the chart to stable.