[stable/cerebro] Add ability to set tls skip verify via vaules file
helm/charts pull request #21178
Opened 2020-03-02 13:30 UTC by rgarcia89

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
In order to use elastic search via ssl with self signed certificates

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-03-03 11:55 UTC, rgarcia89 reviewed
fixed true false behavior

2020-03-04 09:24 UTC, zanhsieh commented
/ok-to-test

2020-03-04 09:27 UTC, davidkarlsen requested changes

2020-03-04 09:27 UTC, davidkarlsen commented on stable/cerebro/Chart.yaml
> +version: 1.4.1
```suggestion
version: 1.5.0
```

2020-03-04 09:27 UTC, davidkarlsen commented
/assign

2020-03-04 09:31 UTC, davidkarlsen commented
/lgtm

2020-03-04 09:35 UTC, merged