[stable/mongodb] Introduce extra volumes for secondary stateful set
helm/charts pull request #21183
Opened 2020-03-02 14:44 UTC by sventschui

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Adds the ability to add extra volumes / mounts / claim templates to the secondary nodes. We want to use this to mount a PV to the secondaries where we will temporarily store backups. As our cluster does not support RWX storage we can not attach one PV to primary+secondary stateful sets/pods.

#### Which issue this PR fixes

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-03-02 16:15 UTC, javsalgar commented
Hi,

Thanks for the PR. Could you please bump the minor version? It is adding a non-breaking feature

2020-03-04 09:06 UTC, javsalgar requested changes
Thanks! Minor changes requested

2020-03-04 09:06 UTC, javsalgar commented on stable/mongodb/templates/statefulset-secondary-rs.yaml
> +{{- end }}
Indent the `{{-end }}`

2020-03-04 09:06 UTC, javsalgar commented on stable/mongodb/templates/statefulset-secondary-rs.yaml
> +{{ toYaml .Values.extraVolumeMountsSecondary | indent 12}}
Add a space after 12

2020-03-04 09:06 UTC, javsalgar commented on stable/mongodb/templates/statefulset-secondary-rs.yaml
> +{{- end}}
Add extra space after `end`

2020-03-04 09:06 UTC, javsalgar commented on stable/mongodb/templates/statefulset-secondary-rs.yaml
> +{{- end}}
Also indent the `if` and `end` like the rest

2020-03-21 10:11 UTC, sventschui commented
Closing as the use case is no longer applicable, this chart moved to another repo and I currently do not have the capacity to apply the requested changes

2020-03-21 10:11 UTC, closed without merging