[stable/chronograf] Add deprecation notice.
helm/charts pull request #21233
Opened 2020-03-04 01:41 UTC by naseemkullah

cc @scottrigby 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-03-04 08:45 UTC, davidkarlsen requested changes

2020-03-04 08:45 UTC, davidkarlsen commented on stable/chronograf/README.md
> +# DEPRECATED - Chronograf
Please see https://github.com/helm/charts/blob/master/PROCESSES.md for deprecation guideline

2020-03-04 12:59 UTC, naseemkullah commented
Thanks @davidkarlsen.

2020-03-06 17:06 UTC, davidkarlsen commented
/lgtm

2020-03-06 17:21 UTC, merged