[stable/kube2iam] Allow setting a custom secret name to use for AWS credentials
helm/charts pull request #21265
Opened 2020-03-05 08:24 UTC by mtougeron

Allow setting a custom secret name to use for AWS credentials in the event that the secret is populated from outside of helm for security purposes

Signed-off-by: Mike Tougeron <tougeron@adobe.com>

#### What this PR does / why we need it:

The PR allows you to use a custom secret name (`aws.custom_secret_name`) for AWS credentials in the event that the secret is populated by a process outside of Helm. e.g., via one of the several tools that sync Vault secrets into Kubernetes Secrets.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-03-06 16:59 UTC, mtougeron commented
Hi @jmcarp / @icereval / @mgoodness I wanted to touch in on this PR and see what you think. Thanks, Mike

2020-03-17 16:17 UTC, mtougeron commented
@jmcarp / @icereval / @mgoodness / @unguiculus / @maorfr any chance this can be reviewed this week? Thanks, Mike

2020-03-27 17:07 UTC, mtougeron commented
@jmcarp / @icereval / @mgoodness / @unguiculus / @maorfr any chance there can be some movement/feedback on this PR?

2020-04-13 12:20 UTC, mtougeron commented
@jmcarp / @icereval / @mgoodness / @unguiculus / @maorfr Hi all, wanted to try again to see if there can be some movement/feedback on this PR? Thanks

2020-04-14 08:30 UTC, unguiculus requested changes
The secret should either be created outside of the Helm chart and referenced here as `existingSecret` (there are many examples that do this) or completely managed by the chart itself. A secret that the chart creates should not be expected to be manipulated from the outside. In this case, the chart should not create the secret at all.

2020-04-14 15:05 UTC, mtougeron commented
@unguiculus sounds good. I've updated the PR accordingly

2020-04-14 15:25 UTC, unguiculus commented
/ok-to-test

2020-04-14 15:32 UTC, unguiculus commented
/lgtm

2020-04-14 15:34 UTC, merged