[stable/cluster-autoscaler] added support if rbac is true then allow options to create or skip se…
helm/charts pull request #21343
Opened 2020-03-09 16:57 UTC by aaronj314

Signed-off-by: Aaron T. Jones <aaronj3.14@gmail.com>

#### Is this a new chart
No

#### What this PR does / why we need it:
This PR allows to reuse an existing service accounts (for instance created with eksctl with its related IAM role) and still manage the role and cluster role bindings with the chart.
An IAM role created by eksctl has a condition on the service account name it also creates, so we cannot just use the serviceAccountAnnotations value to do the mapping, unless we modify the role.
We are aware of the --override-existing-serviceaccounts eksctl argument will put the annotation on the service account if it already exists, and create the missing ones.
I'm interested in a workflow where the infra is created first (applying a YAML config file with eksctl specifying the cluster, including the IAM Roles for Service Accounts) and then the add-ons are deployed with Helm, including cluster-autoscaler. Being able to specify all of that in config files in git and apply it to get a cluster fully configured is a challenge which today requires an extra step that could be eliminated with the help of this PR.

#### Special notes for your reviewer:
I've tested the PR, with the default value it behaves as before. The new feature is enabled only when both rbac.create is true, and rbac.serviceAccount is either true or false. 

Tested with Helm 3.1.1.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-03-09 17:03 UTC, aaronj314 commented
/assign @sameersbn

2020-03-10 08:23 UTC, miguelaeh requested changes
Thank you very much for the PR!!!
Please take a look at the comments

2020-03-10 08:23 UTC, miguelaeh commented on stable/external-dns/README.md
> -| `extraVolumes`                      | A list of volumes to be added to the pod                                                                 | `[]`
Why are you deleting the extra volumes?

2020-03-10 08:23 UTC, miguelaeh commented on stable/external-dns/templates/deployment.yaml
> +      # {{- if .Values.rbac.create }}
Please delete the commented lines.

2020-03-10 08:23 UTC, miguelaeh commented on stable/external-dns/templates/deployment.yaml
> -        # Extra volume mount(s)
I don't understand what is the problem of the extra volumes could you clarify why are you deleting them?

2020-03-10 08:23 UTC, miguelaeh commented on stable/external-dns/values.yaml
>  provider: aws
Please update the `values-production.yaml` too.

2020-03-10 08:23 UTC, miguelaeh commented on stable/external-dns/templates/_helpers.tpl
> +{{- define "serviceaccount.name" -}}
I would change this to, by default, let it create the service account, and, if `.Values.rbac.serviceAccount.name` is provided then use the existing one and not create a new one.

2020-03-10 17:17 UTC, aaronj314 commented
I'm going to close this pull request and create a new one....something with my fork had issues and commits where not correct.  I will create a new one shortly sorry for the time wasted on this :)

2020-03-10 17:17 UTC, closed without merging