[incubator/buzzfeed-sso] upgrade deprecated Kubernetes APIs
helm/charts pull request #21445
Opened 2020-03-13 04:19 UTC by cameronattard

Signed-off-by: Cameron Attard <cameron.attard@siteminder.com>

#### What this PR does / why we need it:

Removes usage of API versions removed in Kubernetes 1.16: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

@darioblanco @komljen

2020-04-13 07:31 UTC, bskim45 commented
/assign @komljen

2020-04-13 07:31 UTC, bskim45 commented
@komljen Can you look into this?

2020-04-13 08:00 UTC, komljen requested changes
This is a breaking change, it will not work for users with older k8s versions. Here is the simple solution:

```
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta1
{{- end }}
```

Same for networking. Please update the chart.

2020-04-14 12:00 UTC, zanhsieh commented
/ok-to-test

2020-04-14 23:20 UTC, cameronattard commented
> This is a breaking change, it will not work for users with older k8s versions. Here is the simple solution:
> 
> ```
> {{- if .Capabilities.APIVersions.Has "apps/v1" }}
> apiVersion: apps/v1
> {{- else }}
> apiVersion: apps/v1beta1
> {{- end }}
> ```
> 
> Same for networking. Please update the chart.

Done.

2020-04-15 08:02 UTC, komljen approved these changes

2020-04-15 08:02 UTC, komljen commented
/lgtm

2020-04-15 08:08 UTC, merged