[stable/grafana] Set resources for downloadDashboards initContainer
helm/charts pull request #21472
Opened 2020-03-16 06:34 UTC by bclermont

#### What this PR does / why we need it:

Add resource to an init container.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-03-16 08:02 UTC, bclermont commented
/assign @rtluckie

2020-03-16 19:13 UTC, zanhsieh requested changes

2020-03-16 19:13 UTC, zanhsieh commented on stable/grafana/Chart.yaml
> +version: 5.0.7
Should be 5.0.8 for now.

2020-03-16 19:14 UTC, zanhsieh commented
/assign

2020-03-25 04:11 UTC, bclermont commented
I rebased and bump version of chart to prevent conflict

2020-03-25 04:12 UTC, bclermont commented
/assign @zanhsieh

2020-03-25 22:42 UTC, zanhsieh commented
@bclermont 
Sorry need to bump again to latest.

2020-03-30 09:09 UTC, bclermont commented
@zanhsieh done

2020-03-30 11:46 UTC, zanhsieh commented
/lgtm

2020-03-30 11:54 UTC, zanhsieh commented
/test pull-charts-e2e

2020-03-30 11:59 UTC, merged