[incubator/solr] Allow adding a custom script to be run before starting Solr (using the entry point of the official Solr Docker Image)
helm/charts pull request #21598
Opened 2020-03-24 12:00 UTC by pai911

#### Is this a new chart
No

#### What this PR does / why we need it:
The official Solr Docker image supports the entry point for us to run a script before starting Solr.

This is a very common use case because there are a lot of times we need to add libs to each Solr installation.

Solr has limited support of adding libs dynamically, so supporting custom script is a must for production environment. 

#### Which issue this PR fixes
No

#### Special notes for your reviewer:
- Solr official Docker image: Extending the image
  - https://github.com/docker-solr/docker-solr#extending-the-image
- Solr has limited support of adding libs dynamically
  - https://issues.apache.org/jira/browse/SOLR-9175

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-03-24 12:07 UTC, pai911 commented
/assign @paulczar

2020-03-31 03:16 UTC, ted-lee commented
I need this wonderful feature as well, which will save a lot of my time. Hope it can be released as soon as possible.

2020-04-14 12:06 UTC, zanhsieh commented
/ok-to-test

2020-04-17 08:17 UTC, pai911 commented
/retest

2020-04-17 08:37 UTC, pai911 commented
@zanhsieh @paulczar 

Hi gurus!
looks like the test has passed. Could we move on to the next stage?

2020-04-17 11:49 UTC, zanhsieh commented
@pai911 
You should ping those ids in the OWNER file to LGTM this PR.
@lachie83
@prydonius
@sameersbn
@viglesiasce
@unguiculus
@scottrigby
@mattfarina
@davidkarlsen
@paulczar
@cpanato
@jlegrone
@maorfr
Could you guys LGTM this PR please? Thank you.

2020-04-17 12:03 UTC, pai911 commented
> @pai911
> You should ping those ids in the OWNER file to LGTM this PR.
> @lachie83
> @prydonius
> @sameersbn
> @viglesiasce
> @unguiculus
> @scottrigby
> @mattfarina
> @davidkarlsen
> @paulczar
> @cpanato
> @jlegrone
> @maorfr
> Could you guys LGTM this PR please? Thank you.

Thanks for the heads-up :)

2020-04-17 12:05 UTC, cpanato commented
please you don't need to ping everybody. You can try to contact the ones in the PR review.

2020-04-17 12:06 UTC, cpanato commented on incubator/solr/Chart.yaml
> +version: "1.4.1"
this is a new feature please bump
```suggestion
version: "1.5.0"
```

2020-04-17 12:07 UTC, cpanato requested changes
please check my comment

2020-04-17 13:30 UTC, pai911 commented
> please check my comment
Hi @cpanato 
I've accepted and committed your suggestion on the github interface.

https://github.com/helm/charts/pull/21598/commits/da198f178bd775fbabfcb3427b3de0fba21424ab

However, it doesn't have my sign-off on the commit.

I've tried to sign it off, it didn't seem to work. Could you shed some lights on how I can make this proceed? Many Thanks!

2020-04-17 13:48 UTC, cpanato commented
try `git commit --amend --signoff`

2020-04-17 15:25 UTC, pai911 commented
@cpanato 

Hi! I fixed the issue, and everything is back to normal.

If everything is ok, we move on to the next stage!

2020-04-22 08:17 UTC, pai911 commented
Hi!

@viglesiasce
@cpanato
@lachie83 

Could one of you find time to review this pull request? :)

Many thanks!

2020-04-28 03:26 UTC, pai911 commented
I'm sorry! I know I shouldn't ping this many people
but it's been a long time since I created this

@lachie83
@prydonius
@sameersbn
@viglesiasce
@unguiculus
@scottrigby
@mattfarina
@davidkarlsen
@paulczar
@cpanato
@jlegrone
@maorfr

Could you guys LGTM this PR please? Thank you.

2020-04-28 03:30 UTC, sameersbn reviewed
/ok-to-test

2020-04-28 05:24 UTC, pai911 commented
> /ok-to-test

Hi, @sameersbn 

I think the pull request has been tested.

Is it okay to move on to the next stage?

Many thanks!

2020-04-28 05:28 UTC, sameersbn commented
/lgtm

2020-04-28 05:28 UTC, sameersbn commented
Approved! Thanks for the contribution and sorry about the delay

2020-04-28 05:29 UTC, sameersbn approved these changes

2020-04-28 05:42 UTC, merged

2020-05-12 18:39 UTC, dunn commented
Is it possible to use this feature without copying a script into the Solr chart directory?  For example, I have a chart that uses Solr as a dependency, and it would be very nice to not have to unpack the Solr chart and copy in the script.

This would be possible if we could inline a script's contents as the value of initScript, instead of giving it a path.

2020-09-01 06:41 UTC, pai911 commented
> Is it possible to use this feature without copying a script into the Solr chart directory?  For example, I have a chart that uses Solr as a dependency, and it would be very nice to not have to unpack the Solr chart and copy in the script.
> 
> 
> 
> This would be possible if we could inline a script's contents as the value of initScript, instead of giving it a path.

Hi! Thank you for the feedback!

My initial solution is meant to be a more general solution since we the init script may be longer than we expected. I am not so sure if writing a long init script in the values.yaml is the best idea.

Anyway, one solution might be providing both capabilities (inline and independent file)so people can choose what best suits their needs.