stable/goldpinter: Only use pullSecrets if defined in values.yaml
helm/charts pull request #21823
Opened 2020-04-07 16:51 UTC by xbglowx

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

No

#### What this PR does / why we need it:

This was causing the DaemonSet to have an invalid key/value for imagePullSecrets

```
imagePullSecrets:
  - name:
```

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-04-07 17:04 UTC, xbglowx commented
/assign @okgolove

2020-04-07 17:08 UTC, okgolove commented on stable/goldpinger/templates/daemonset.yaml
> +        - name: {{ . }}
May be:
`{{ toYaml .Values.image.pullSecrets | indent 8 }}`  ?

2020-04-07 17:09 UTC, okgolove requested changes

2020-04-07 17:09 UTC, okgolove commented on stable/goldpinger/templates/daemonset.yaml
> +        - name: {{ . }}
May be use `toYaml`?

`{{ toYaml .Values.image.pullSecrets | indent 8 }}`

2020-04-07 17:16 UTC, xbglowx commented on stable/goldpinger/templates/daemonset.yaml
> +        - name: {{ . }}
Won't your approach only work if we also update the expected format of pullSecrets to be?

```
pullSecrets:
  - name: foo
  - name: bar
```

Instead of the current format of:

```
pullSecrets:
  - foo
  - bar
```

https://github.com/helm/charts/blob/master/stable/goldpinger/values.yaml#L12

2020-04-07 17:25 UTC, okgolove commented on stable/goldpinger/templates/daemonset.yaml
> +        - name: {{ . }}
Good catch!

2020-04-07 17:25 UTC, okgolove commented
/ok-to-test

2020-04-08 03:36 UTC, xbglowx commented
> /ok-to-test

@okgolove do you need to do this?

<img width="770" alt="Screen Shot 2020-04-07 at 11 35 44 PM" src="https://user-images.githubusercontent.com/1020898/78741900-90032780-7928-11ea-8a56-b2e69f2d9562.png">

2020-04-08 09:01 UTC, okgolove commented
/lgtm

2020-04-08 09:07 UTC, merged