[stable/elasticsearch-curator]add startingDeadlineSeconds cronjob spec
helm/charts pull request #21854
Opened 2020-04-09 16:28 UTC by ruccoon

[stable/elasticsearch-curator]add startingDeadlineSeconds cronjob spec

Signed-off-by: ruccoon <ruccoon@hotmail.com>

#### What this PR does / why we need it:
The current stable/elasticsearch-curator chart doesn't support **startingDeadlineSeconds** spec in curator cronjob

#### Which issue this PR fixes
  - fixes #21699

https://github.com/helm/charts/issues/21699

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-04-14 12:20 UTC, zanhsieh commented
/ok-to-test

2020-05-20 13:34 UTC, ruccoon commented
@desaintmartin @gianrubio could you help have a review, thx

2020-06-18 08:21 UTC, desaintmartin requested changes
Thanks for the PR!
/assign
/ok-to-test

2020-06-18 08:21 UTC, desaintmartin commented on stable/elasticsearch-curator/README.md
> +| `cronjob.startingDeadlineSeconds`    | Secondes until now the controller counts the missed jobs    | `nil`                                        |
```suggestion
| `cronjob.startingDeadlineSeconds`    | Optional deadline in seconds for starting the job if it misses scheduled time for any reason    | `nil`                                        |
```

2020-07-27 16:41 UTC, desaintmartin reviewed
Sorry, I completely forgot this one.

2020-07-27 16:41 UTC, desaintmartin commented on stable/elasticsearch-curator/Chart.yaml
> +version: 2.1.6
This is a new feature, could you bump minor version instead of patch?

2020-07-30 16:29 UTC, desaintmartin commented
/unassign
I removed myself from owners, @haad may be able to take over.

2020-07-30 16:41 UTC, ruccoon commented
the feature has already been added in the stable version

closing PR

2020-07-30 16:41 UTC, closed without merging