[stable/rabbitmq-ha] added network policy
helm/charts pull request #21934
Opened 2020-04-15 09:48 UTC by aksenk

#### What this PR does / why we need it:
This PR adds network policy template to the chart.

#### Special notes for your reviewer:
Network policy is disabled by default.
If we just enable netpol, than we allow cross-pod communication for cluster nodes in statefulset.
If we enable allowClientLabel, we allow external connects from pods with label "rabbitmq-client: true".
If we need more flexibility, we can add any custom config to our configuration.

This is my vision of a better path for network policies.
If you have any comments or suggestions, I am ready to listen to them.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-04-15 09:56 UTC, aksenk commented
/assign @steven-sheehy

2020-04-17 18:44 UTC, zanhsieh commented
/ok-to-test

2020-04-17 18:58 UTC, zanhsieh commented
/test pull-charts-e2e

2020-04-20 10:51 UTC, zanhsieh commented
@steven-sheehy
Could you LGTM this PR please? Thank you.

2020-04-25 16:11 UTC, steven-sheehy requested changes

2020-04-25 16:11 UTC, steven-sheehy commented on stable/rabbitmq-ha/templates/networkpolicy.yaml
> +    app.kubernetes.io/name: {{ include "rabbitmq-ha.fullname" . }}
Don't mix and match old labels and new. We should match what the rest of the chart uses:
```yaml
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ template "rabbitmq-ha.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
```

2020-04-25 16:11 UTC, steven-sheehy commented on stable/rabbitmq-ha/templates/networkpolicy.yaml
> +      port: {{ .Values.rabbitmqPrometheusPlugin.port }}
I would prefer the named port being used for these instead of the integer port

2020-06-09 00:51 UTC, closed without merging