[stable/rabbitmq-ha]  add configuration for initContainer
helm/charts pull request #22005
Opened 2020-04-18 13:15 UTC by PixelJonas

#### Is this a new chart
No

#### What this PR does / why we need it:
I'm currently using NFS mounts for my cluster. running as `root` and changing permissions does not work using these volumes. This resulted in the rabbitmq initContainer always crashing.

This PR adds multiple options to configure the initContainer including the default `securityContext` options and an extra option to disable the `chown` when using `runAsGroup` and/or `fsGroup`.

#### Which issue this PR fixes
none

#### Special notes for your reviewer:

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-04-18 13:20 UTC, PixelJonas commented
/assign @steven-sheehy

2020-04-25 16:26 UTC, steven-sheehy requested changes
/assign
/ok-to-test

2020-04-25 16:26 UTC, steven-sheehy commented on stable/rabbitmq-ha/templates/statefulset.yaml
> +            runAsGroup: {{ .Values.initContainer.runAsGroup }}
Would prefer setting entire security context as yaml:
```yaml
securityContext:
  {{- toYaml .Values.initContainer.securityContext | nindent X }}
```

2020-04-25 16:26 UTC, steven-sheehy commented on stable/rabbitmq-ha/templates/statefulset.yaml
> +            {{- if and (.Values.securityContext.runAsUser) (.Values.securityContext.fsGroup) (not .Values.initContainer.skipChown) }}
Would prefer negated property `chownFiles=true`

2020-04-25 16:26 UTC, steven-sheehy commented on stable/rabbitmq-ha/Chart.yaml
> +version: 1.44.3
Minor version bump since we have some new properties: 1.45.0

2020-05-19 06:45 UTC, PixelJonas commented
@steven-sheehy sorry it took me long but I resolved your comments.

2020-05-19 21:12 UTC, steven-sheehy approved these changes
/lgtm

2020-05-19 21:22 UTC, merged