[stable/prometheus-pushgateway] added relabelconfig to serviceMonitor
helm/charts pull request #22066
Opened 2020-04-22 15:39 UTC by benibr

#### What this PR does / why we need it:
This adds the possibility to add relabelConfig (prometheus-operator.relabelings) via prometheus-pushgateway serviceMonitor as described in  #22040

#### Which issue this PR fixes
  - fixes #22040

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-04-22 15:50 UTC, benibr commented
I changed the name of the paramter to `` after the definition in https://github.com/helm/charts/blob/master/stable/prometheus-operator/crds/crd-servicemonitor.yaml
I'd like feedback if this is the right style!
Other option would be to name is relabelConfig after https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#relabelconfig and https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

2020-04-22 15:53 UTC, benibr commented
Tested with:
```
serviceMonitor:
  enabled: true
  namespace: default
  additionalLabels: {}
  honorLabels: true
  relabelConfig:
    - regex: '.*'
      sourceLabels:
        - 'foo'
      separator: ';'
      targetLabel: 'bar'
      regex: '^baz.+'
      modulus: 2342
      replacement: 'bay'
      action: 'replace'
```

This config produces:
```
kubectl describe servicemonitor/pushgw-test-prometheus-pushgateway
Name:         pushgw-test-prometheus-pushgateway
Namespace:    default
[…]
Spec:
  Endpoints:
    Honor Labels:  true
    Path:          /metrics
    Port:          http
    Relabelings:
      Action:       replace
      Modulus:      2342
      Regex:        ^baz.+
      Replacement:  bay
      Separator:    ;
      Source Labels:
        foo
      Target Label:  bar
```

2020-04-22 15:53 UTC, benibr commented
/assign @gianrubio

2020-05-07 08:33 UTC, cstaud commented
/ok-to-test

2020-05-07 08:41 UTC, cstaud requested changes

2020-05-07 08:41 UTC, cstaud commented on stable/prometheus-pushgateway/README.md
> +| `serviceMonitor.relabelings`      | Array of RelabelConfigs to apply to samples before scraping                                                                   | `true`
This seems not correct as the description claims for an array but `true` is default? A default here would be `{}` could you provide an example how this could look like? I'm not experienced with relableconfigs. Anyway the defautl should be `{}` which is also evaluated as `false`.

From https://helm.sh/docs/chart_template_guide/control_structures/
> A pipeline is evaluated as false if the value is:
> an empty collection (map, slice, tuple, dict, array)

So the rest could stay as it is from my POV.

2020-05-13 14:02 UTC, benibr commented on stable/prometheus-pushgateway/README.md
> +| `serviceMonitor.relabelings`      | Array of RelabelConfigs to apply to samples before scraping                                                                   | `true`
thanks for the feedback! The `true` is a copy paste error.
As the example in my comment above shows ( https://github.com/helm/charts/pull/22066#issuecomment-617865561 ) an array of relabelConfig hashes can be set.
Shouldn't the default then be `[]`?

2020-05-27 12:48 UTC, benibr commented
I've corrected the readme and renamed the relabelConfig paramter to `relabelings` to keep it consistent with the CRD https://github.com/helm/charts/blob/master/stable/prometheus-operator/crds/crd-servicemonitor.yaml

2020-06-18 19:29 UTC, benibr commented
is there anything else needed to merge this?

2020-07-01 22:51 UTC, benibr commented
@gianrubio @cstaud can this be merged?

2020-07-20 14:39 UTC, benibr commented
#22040 now has automatically be closed due to inactivity. Has this any chance of getting merged? Am I missing something?

2020-08-15 18:15 UTC, scottrigby commented
/hold

Let’s hold PRs to `stable` prometheus charts for a short time until prometheus-community/community#28 (comment) is resolved. If you want to help with that effort, to test etc, that would be great!

2020-08-17 12:01 UTC, cstaud commented
/lgtm

2020-08-25 09:35 UTC, scottrigby commented
@benibr also feel free to recreate the PR there if that makes it easier for you to test (presumably you're already testing changes in this PR). The first step would be to upgrade a current (non-production) release to the new chart to ensure there are no regressions there. Then that your change still works as expected.

2020-09-09 21:03 UTC, scottrigby commented
🚧 This chart is now deprecated.

Further development has moved to [prometheus-community/helm-charts](https://github.com/prometheus-community/helm-charts). The chart has been renamed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to more clearly reflect that it installs the `kube-prometheus` project stack, within which Prometheus Operator is only one component.

If applicable, please re-open this PR there. Thanks!

2020-09-09 21:03 UTC, closed without merging

2021-01-15 21:38 UTC, benibr commented
Implemented in https://github.com/prometheus-community/helm-charts/pull/567