[stable/grafana] Removed extra schedulerName field
helm/charts pull request #22075
Opened 2020-04-23 08:02 UTC by thekalpesh7

#### What this PR does / why we need it:

There is a repeated `schedulerName` field in the `_pod.tpl` file on lines 3 and 7. If the `Values.schedulerName` is set in the values file then this will create a duplicate entry of the same key i.e. `schedulerName`. I have removed the duplicated `schedulerName` field.

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-04-23 08:17 UTC, zanhsieh commented
@thekalpesh7 
Could you bump the chart version to latest please? Thank you.

/assign

2020-04-23 17:24 UTC, thekalpesh7 commented
@zanhsieh I have updated the Chart version to 5.0.14. Let me know If that's okay.

2020-04-23 21:26 UTC, zanhsieh commented
/ok-to-test

2020-04-27 08:16 UTC, zanhsieh requested changes

2020-04-27 08:16 UTC, zanhsieh commented on stable/grafana/Chart.yaml
> +version: 5.0.14
Should be 5.0.17 now.

2020-04-29 15:46 UTC, zanhsieh commented
@thekalpesh7 
Could you bump the chart to latest version again?

2020-04-30 09:19 UTC, thekalpesh7 commented
/assign @zanhsieh

2020-04-30 23:56 UTC, zanhsieh commented
@thekalpesh7 
Could you bump the chart again to latest version please? Thank you.

2020-05-01 07:49 UTC, zanhsieh commented
/test pull-charts-e2e

2020-05-01 07:53 UTC, zanhsieh commented
/test pull-charts-e2e

2020-05-01 07:59 UTC, zanhsieh commented
/lgtm

2020-05-01 08:00 UTC, zanhsieh approved these changes

2020-05-01 08:00 UTC, merged