[stable/prometheus-blackbox-exporter] Add vars for liveness and readyness
helm/charts pull request #22201
Opened 2020-04-30 08:10 UTC by LucasBoisserie

#### What this PR does / why we need it:
Add vars for liveness and readyness and use them

If we set:
```yaml 
extraArgs:
  - "--web.route-prefix=/blackbox
```
Health url move from `/health` to `/blackbox/health`. Liveness and readyness fail because they are set in the code and are not configurable.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-04-30 08:12 UTC, LucasBoisserie commented
/assign @desaintmartin

2020-05-02 07:56 UTC, desaintmartin requested changes
Thanks!
/assign
/ok-to-test

2020-05-02 07:56 UTC, desaintmartin commented on stable/prometheus-blackbox-exporter/Chart.yaml
> +version: 3.5.1
Could you bump minor version instead of patch, according to semver? this is new feature.

2020-05-14 07:00 UTC, desaintmartin commented
Could you rebase?

2020-05-14 07:30 UTC, LucasBoisserie commented
@desaintmartin 
Rebase done and tests ok

2020-05-14 07:53 UTC, desaintmartin commented
Thanks for the contribution!
/lgtm

2020-05-14 07:54 UTC, merged