Revert "[stable/fluentd] Fix missing serviceName in HPA"
helm/charts pull request #22257
Opened 2020-05-05 02:51 UTC by jmthvt

Reverts helm/charts#21202

The serviceName had to be added on the statefulset resource, not the HPA.
Since it has been done on another PR, we only need to revert this breaking change.

2020-05-05 03:03 UTC, jmthvt commented
/assign @Miouge1

2020-05-05 08:38 UTC, Jonher937 commented on stable/fluentd/templates/hpa.yaml
> +    heritage: {{ .Release.Service }}
```suggestion
    heritage: {{ .Release.Service }}
```

Remove the tab at the end please

2020-05-23 02:49 UTC, scottrigby requested changes
Apart from this looks good

2020-05-23 02:49 UTC, scottrigby commented on stable/fluentd/templates/_helpers.tpl
> +{{- end -}}
Should keep newline at EOF

2020-05-25 12:16 UTC, jmthvt commented on stable/fluentd/templates/_helpers.tpl
> +{{- end -}}
resolved - PTAL

2020-05-28 14:12 UTC, uhthomas commented
Re: https://github.com/helm/charts/pull/21202

I'm also getting
```
unknown field "serviceName" in io.k8s.api.autoscaling.v2beta2.CrossVersionObjectReference
```
for v2.4.1. Could we get this merged please?

2020-05-28 14:55 UTC, Jonher937 approved these changes
Looks good

2020-06-09 17:56 UTC, scottrigby commented
/ok-to-test

2020-06-09 17:56 UTC, scottrigby approved these changes

2020-06-09 17:57 UTC, scottrigby commented
/lgtm

2020-06-09 17:59 UTC, merged