[stable/jenkins] Add Kubernetes plugin parameters
helm/charts pull request #22276
Opened 2020-05-06 15:26 UTC by BryanHunt

Signed-off-by: Bryan Hunt <bhunt@mac.com>

#### Is this a new chart

No

#### What this PR does / why we need it:

It add additional configuration parameters to the Kubernetes plugin

#### Which issue this PR fixes

  - fixes # 22212

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-05-08 04:27 UTC, wmcdona89 requested changes
thanks for the PR!

2020-05-08 04:27 UTC, wmcdona89 commented on stable/jenkins/README.md
> +| `master.slaveDefaultsProviderTemplate` | The name of the pod template to use for providing default values | Not set  |
are you defining your agents in the chart via `agent` and `additionalAgents`?
all `additionalAgents` inherit from `agent` when the chart is deployed

that said, there can be value in setting Defaults Provider Template to ensure configuration changes made via the Jenkins console will be inherited as well

2020-05-08 04:27 UTC, wmcdona89 commented on stable/jenkins/README.md
> +| `master.slaveReadTimeout`         | The read timeout in seconds for connections to Kubernetes API. Minimum value is 15. | 15 |
this does seem like the right place for all these values as they're used for the top-level configuration of the kubernetes plugin while `agent` values are used to configure pod templates. the `master.slave*` names could stand to be refactored down the road...perhaps `master.k8s.*`.

2020-05-08 04:27 UTC, wmcdona89 commented on stable/jenkins/README.md
> +| `agent.jenkinsUrl`         | Overrides the value of the JENKINS_URL env      | Not set                |
could `master.slaveJenkinsUrl` be used to set JENKINS_URL or is JENKINS_URL always a unique value?

issue #22219 references JENKINS_URL

2020-05-08 04:27 UTC, wmcdona89 commented on stable/jenkins/values.yaml
> +  slaveReadTimeout: 15
it seems like the defaults for `slaveConnectTimeout` and `slaveReadTimeout` should remain at 0

2020-05-08 04:27 UTC, wmcdona89 commented on stable/jenkins/templates/config.yaml
> +          <defaultsProviderTemplate>{{ default "" .Values.slaveDefaultsProviderTemplate }}</defaultsProviderTemplate>
please also add `defaultsProviderTemplate` to the JCasC [here](https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl#L91)

2020-05-08 04:27 UTC, wmcdona89 commented on stable/jenkins/templates/config.yaml
> +          <defaultsProviderTemplate>{{ default "" .Values.slaveDefaultsProviderTemplate }}</defaultsProviderTemplate>
should be `.Values.master.slaveDefaultsProviderTemplate`

2020-05-08 04:27 UTC, wmcdona89 commented on stable/jenkins/values.yaml
> +  slaveReadTimeout: 15
please include the other new configurable fields here as well along with useful comments. fields that don't have default values may be commented out.

2020-05-08 04:27 UTC, wmcdona89 commented on stable/jenkins/templates/config.yaml
> +          <jenkinsUrl>{{ .Values.master.slaveJenkinsUrl }}</jenkinsUrl>
please also add `master.slaveJenkinsUrl` to the JCasC [here](https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl#L93)

2020-05-08 04:27 UTC, wmcdona89 commented on stable/jenkins/templates/config.yaml
> +          <jenkinsTunnel>{{ .Values.master.slaveJenkinsTunnel }}</jenkinsTunnel>
please also add `master.slaveJenkinsTunnel` to the JCasC [here](https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl#L92)

2020-05-08 04:35 UTC, wmcdona89 commented
/assign wmcdona89

2020-05-08 04:40 UTC, wmcdona89 commented
Please also update the CHANGELOG

2020-05-08 13:14 UTC, BryanHunt commented on stable/jenkins/values.yaml
> +  slaveReadTimeout: 15
The documentation for the Kubernetes plugin states that the minimum value for `slaveConnectTimeout` and `slaveReadTimeout` is 5 and 15 respectively.  When using the UI to configure those values, you cannot enter values less that the minimum.

If you want the to default to 0, I'll change it, but that seems to be an invalid value.

2020-05-08 14:13 UTC, BryanHunt commented
I've made most of the changes requested.  I need to resolve the question on the JENKINS_URL environment variable and default provider template with a co-worker when they get in.

2020-05-08 20:40 UTC, BryanHunt commented on stable/jenkins/README.md
> +| `master.slaveDefaultsProviderTemplate` | The name of the pod template to use for providing default values | Not set  |
This is what I got from one of my co-workers:

> defaultProviderTemplate sets podTemplate() step to use the podTemplate we provide in the k8s cloud configuration. Without setting defaultProviderTemplate the template is just there but not used unless we do podTemplate(inheritFrom:'default)

2020-05-08 20:41 UTC, BryanHunt commented on stable/jenkins/README.md
> +| `agent.jenkinsUrl`         | Overrides the value of the JENKINS_URL env      | Not set                |
We are good with setting the environment variable the same as `master.slaveJenkinsUrl`.  Shall I make that change?

2020-05-10 03:17 UTC, wmcdona89 commented on stable/jenkins/README.md
> +| `master.slaveDefaultsProviderTemplate` | The name of the pod template to use for providing default values | Not set  |
got it. you're only configuring `agent` in the chart and then defining pod templates in your pipelines which need to inherit from the pod template configured by `agent`. thus Defaults Provider Template needs to point to the pod template configured by `agent`.

2020-05-10 03:19 UTC, wmcdona89 commented on stable/jenkins/README.md
> +| `agent.jenkinsUrl`         | Overrides the value of the JENKINS_URL env      | Not set                |
yes, please make the change. I think it would be confusing to have both `master.slaveJenkinsUrl` and `agent.jenkinsUrl`.

2020-05-10 04:02 UTC, wmcdona89 commented on stable/jenkins/values.yaml
> +  slaveReadTimeout: 15
It appears the Kubernetes plugin behaves differently when the Configuration As Code plugin is installed. Without the Configuration As Code plugin, the values get set to the minimums even though the chart configures them as 0. With the Configuration As Code plugin, a value of 0 is allowed and means no timeout. Let's leave the chart defaults as 0.

2020-05-10 04:16 UTC, wmcdona89 requested changes

2020-05-10 04:16 UTC, wmcdona89 commented on stable/jenkins/templates/config.yaml
> +          <connectTimeout>{{ .Values.master.slaveConnectTimeout }}</connectTimeout>
please also add `master.slaveConnectTimeout` to the JCasC as `connectTimeout` [here](https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl#L90)

2020-05-10 04:16 UTC, wmcdona89 commented on stable/jenkins/templates/config.yaml
> +          <readTimeout>{{ .Values.master.slaveReadTimeout }}</readTimeout>
please also add `master.slaveReadTimeout`to the JCasC as `readTimeout` [here](https://github.com/helm/charts/blob/master/stable/jenkins/templates/_helpers.tpl#L101)

2020-05-10 04:16 UTC, wmcdona89 commented on stable/jenkins/templates/_helpers.tpl
> +      {{- if .Values.master.slaveKubernetesNamespace }}
let's make this an `else if`

2020-05-10 04:16 UTC, wmcdona89 commented on stable/jenkins/templates/_helpers.tpl
>        {{- if .Values.master.slaveKubernetesNamespace }}
let's make this an `else if`

2020-05-10 04:16 UTC, wmcdona89 commented on stable/jenkins/templates/config.yaml
> +  {{- if .Values.master.slaveKubernetesNamespace }}
let's make this an `else if`

2020-05-10 04:16 UTC, wmcdona89 commented on stable/jenkins/templates/config.yaml
> +  {{- if .Values.master.slaveKubernetesNamespace }}
let's make this an `else if`

2020-05-11 15:48 UTC, BryanHunt commented
I think I've got all the requested changes in.  I still need to test locally and resolve the changelog conflict.

2020-05-11 21:38 UTC, BryanHunt commented
My co-worker has a couple of issues that need to be sorted out.  Please don't merge this just yet.

2020-05-12 20:37 UTC, BryanHunt commented
We are good to merge with my last fix if y'all are.

2020-05-13 04:32 UTC, wmcdona89 requested changes

2020-05-13 04:32 UTC, wmcdona89 commented on stable/jenkins/CHANGELOG.md
> +
looks like you missed committing your change description

2020-05-13 04:32 UTC, wmcdona89 commented on stable/jenkins/values.yaml
> +  slaveReadTimeout: 0
let's also add `master.slaveJenkinsUrl` and `master.slaveJenkinsTunnel` here so this file and the README are in sync

2020-05-13 04:32 UTC, wmcdona89 commented on stable/jenkins/values.yaml
> +  slaveReadTimeout: 0
oops...I discovered I was using an old version of the kubernetes plugin when looking into the minimum timeout values. looks like the minimums were established in [v1.21.5](https://github.com/jenkinsci/kubernetes-plugin/releases/tag/kubernetes-1.21.5)

so yeah...these should be 5 and 15 as you proposed

2020-05-13 04:32 UTC, wmcdona89 commented on stable/jenkins/Chart.yaml
> +version: 1.18.2
let's make this a minor version bump

2020-05-13 13:11 UTC, BryanHunt commented on stable/jenkins/CHANGELOG.md
> +
I used GitHub to resolve the merge conflict.  What do I need to do for this?

2020-05-13 21:38 UTC, wmcdona89 requested changes

2020-05-13 21:38 UTC, wmcdona89 commented on stable/jenkins/CHANGELOG.md
> +
this is currently just copy / paste of the verbiage from v1.18.1
it needs to be something like...

## 1.20.0

Add the following options for configuring the Kubernetes plugin.
- `master.slaveDefaultsProviderTemplate`
- `master.slaveJenkinsUrl`
- `master.slaveJenkinsTunnel`
- `master.slaveConnectTimeout`
-  `master.slaveReadTimeout`
```

2020-05-13 21:38 UTC, wmcdona89 commented on stable/jenkins/Chart.yaml
> +version: 1.19.0
v1.19.0 was just merged. please rebase and bump to v1.20.0

2020-05-14 18:26 UTC, BryanHunt commented
Did something go wrong with the rebase?  Why are there so many commits?  Sorry, I'm not a git expert :(

2020-05-14 20:25 UTC, wmcdona89 commented
what you pushed looks more like a merge than a rebase. are you aware of `git push --force-with-lease`?

first ensure your fork is up to date. see [Syncing a fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) or [Syncing your fork to the original repository via the browser](https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser).

then try the following...
```bash
git fetch 
git rebase -Xtheirs origin/master
# if the previous CHANGELOG entry was deleted, replace it and commit
git push --force-with-lease
```
[this article](https://demisx.github.io/git/rebase/2015/07/02/git-rebase-keep-my-branch-changes.html) explains `-Xtheirs`

2020-05-14 22:46 UTC, BryanHunt commented
I'm getting error messages about cherry picking and could not apply a commit.  I'm going to close this and start over.  That will be like 10x faster than trying to fix whatever git did.

2020-05-14 22:46 UTC, closed without merging

2020-05-14 23:05 UTC, wmcdona89 requested changes
it just occurred to me that `master.slaveJenkinsUrl` and `master.slaveJenkinsTunnel` should allow templating. if you don't mind making the updates I'd appreciate it. I believe there are 6 spots to update.

2020-05-14 23:05 UTC, wmcdona89 commented on stable/jenkins/templates/_helpers.tpl
> +      jenkinsUrl: "{{ .Values.master.slaveJenkinsUrl }}"
to allow templating this will be `jenkinsUrl: "{{ tpl .Values.master.slaveJenkinsUrl . }}"`

2020-05-14 23:05 UTC, wmcdona89 commented on stable/jenkins/templates/_helpers.tpl
> +      jenkinsTunnel: "{{ .Values.master.slaveJenkinsTunnel }}"
to allow templating this will be `jenkinsTunnel: "{{ tpl .Values.master.slaveJenkinsTunnel . }}"`

2020-05-14 23:05 UTC, wmcdona89 commented on stable/jenkins/templates/_helpers.tpl
> +          <value>{{ .Values.master.slaveJenkinsUrl }}</value>
to allow templating this will be `<value>{{ tpl .Values.master.slaveJenkinsUrl . }}</value>`

2020-05-14 23:05 UTC, wmcdona89 commented on stable/jenkins/templates/config.yaml
> +          <jenkinsUrl>{{ .Values.master.slaveJenkinsUrl }}</jenkinsUrl>
to allow templating this will be `<jenkinsUrl>{{ tpl .Values.master.slaveJenkinsUrl . }}</jenkinsUrl>`

2020-05-14 23:05 UTC, wmcdona89 commented on stable/jenkins/templates/config.yaml
> +          <jenkinsTunnel>{{ .Values.master.slaveJenkinsTunnel }}</jenkinsTunnel>
to allow templating this will be `<jenkinsTunnel>{{ tpl .Values.master.slaveJenkinsTunnel . }}</jenkinsTunnel>`

2020-05-14 23:05 UTC, wmcdona89 commented on stable/jenkins/templates/_helpers.tpl
> +        value: {{ .Values.master.slaveJenkinsUrl }}
to allow templating this will be `value: {{ tpl .Values.master.slaveJenkinsUrl . }}`

2020-05-14 23:08 UTC, wmcdona89 commented
> I'm getting error messages about cherry picking and could not apply a commit. I'm going to close this and start over. That will be like 10x faster than trying to fix whatever git did.

@BryanHunt good idea. please link to #22276 for reference. and one more request [here](https://github.com/helm/charts/pull/22276#pullrequestreview-412237838) if you don't mind.