Remove generation of unneeded secret
helm/charts pull request #22514
Opened 2020-05-25 14:46 UTC by wizard580

#### What this PR does / why we need it:
If/when I define env var GF_SECURITY_ADMIN_PASSWORD this chart will make K8S secret with auto-generated admin password, but this password will not be used. 

This PR fixes this.

Please review if I missed anything.

Thanks.

2020-05-25 14:47 UTC, wizard580 commented
/assign @rtluckie

2020-05-26 07:14 UTC, zanhsieh commented
@wizard580 
Thanks for contribution.
Please sign DCO and bump the chart to latest version as seen in the bottom of this PR (click Details for instructions).

2020-05-26 07:14 UTC, zanhsieh commented
/assign

2020-05-27 06:15 UTC, thesuperzapper commented
@wizard580, it's really not clear why `stable/airflow` commits have made their way into your PR, perhaps try rebase off remote master?

2020-05-28 01:24 UTC, thesuperzapper commented
@zanhsieh, it's weirder than that, those commits are not from this PR, they are just recent commits to the `stable/airflow`

2020-05-29 21:37 UTC, zanhsieh commented
@wizard580 @thesuperzapper 
Please rebase.

2020-05-30 15:57 UTC, wizard580 commented
Sorry for mistakes. Fixed.

2020-05-30 23:55 UTC, zanhsieh approved these changes

2020-05-30 23:55 UTC, zanhsieh commented
/ok-to-test

2020-06-01 01:37 UTC, zanhsieh approved these changes

2020-06-01 01:38 UTC, zanhsieh commented
/lgtm

2020-06-01 02:12 UTC, zanhsieh commented
/test pull-charts-e2e

2020-06-01 02:17 UTC, zanhsieh commented
/test pull-charts-e2e

2020-06-01 02:34 UTC, zanhsieh commented
/test pull-charts-e2e

2020-06-01 02:42 UTC, zanhsieh requested changes

2020-06-01 02:42 UTC, zanhsieh commented on stable/grafana/Chart.yaml
> +version: 5.1.1
Could you bump to 5.1.2 please? Thanks you.

2020-06-01 12:10 UTC, zanhsieh approved these changes

2020-06-01 12:11 UTC, zanhsieh commented
/lgtm

2020-06-01 12:13 UTC, zanhsieh commented
@wizard580 
Could you resolve stable/grafana/Chart.yaml conflict listed on the bottom of this PR?

2020-06-01 18:03 UTC, zanhsieh commented
/lgtm

2020-06-01 18:03 UTC, merged