[stable/elasticsearch-exporter] add ingress support (helm#22630)
helm/charts pull request #22632
Opened 2020-06-02 11:31 UTC by jinleileiking

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-06-03 10:40 UTC, jinleileiking commented
/assign @caarlos0

2020-06-03 12:23 UTC, svenmueller reviewed
What is the idea behind exposing the Prometheus exporter endpoint to the public? A common recommendation would be to deploy a proxy (with auth) in front of the ES Prometheus exporter.

2020-06-03 14:16 UTC, caarlos0 requested changes

2020-06-03 14:16 UTC, caarlos0 commented on stable/elasticsearch-exporter/Chart.yaml
> +version: 3.3.1
shoul be `3.4.0`, as its a new feature.

2020-06-03 14:16 UTC, caarlos0 commented on stable/elasticsearch-exporter/README.md
> +`ingress.hosts` | Ingress hostnames | `kafka-manager.local`
why kafka?

2020-06-05 04:06 UTC, jinleileiking commented
@caarlos0 all fixed.

2020-06-05 08:56 UTC, jinleileiking commented
> What is the idea behind exposing the Prometheus exporter endpoint to the public? A common recommendation would be to deploy a proxy (with auth) in front of the ES Prometheus exporter.

Here is one case needs ingress:

The web ui of  prometheus -> target -> endpoint 

If we use clusterip. Then cannot show then endpoint info. But ingress can

2020-06-06 18:01 UTC, caarlos0 commented
> The web ui of prometheus -> target -> endpoint

that makes sense if your prometheus is outside the cluster the exporter is running.

Still I think @svenmueller got a point in saying you should use a proxy with auth, otherwise anyone can see your metrics... 🤔

2020-06-08 09:49 UTC, svenmueller commented
Currently none of the standard Prometheus exporter is exposing metrics using an ingress out of the box. I don't think we should add this feature in the Elasticsearch Prometheus exporter Helm chart.

2020-06-09 05:42 UTC, jinleileiking commented
ok close for now.

2020-06-09 05:42 UTC, closed without merging