[stable/mongodb-replicaset] Add ServiceAccount option (#22694)
helm/charts pull request #22697
Opened 2020-06-05 22:14 UTC by krzysztof-miemiec

#### Is this a new chart
Nope.

#### What this PR does / why we need it:
It adds a ServiceAccount option which is handy if you'd like to use this chart with Consul Connect.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #22694

#### Special notes for your reviewer:
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-06-06 05:59 UTC, krzysztof-miemiec commented
/assign @steven-sheehy

2020-06-18 14:49 UTC, steven-sheehy requested changes
/assign
/ok-to-test

2020-06-18 14:49 UTC, steven-sheehy commented on stable/mongodb-replicaset/Chart.yaml
> +version: 3.15.2
Should be minor version bump for new features

2020-06-18 14:49 UTC, steven-sheehy commented on stable/mongodb-replicaset/templates/mongodb-serviceaccount.yaml
> +metadata:
Missing common labels and namespace that are present in other manifests.

2020-06-19 21:07 UTC, krzysztof-miemiec commented
Thanks for review @steven-sheehy! I added fixes in amend commit.

2020-06-19 21:15 UTC, steven-sheehy approved these changes
/lgtm

2020-06-19 21:16 UTC, merged