[stable/elasticsearch-exporter] Improvement: Use secrets to configure elasticsearch uri
helm/charts pull request #22734
Opened 2020-06-10 13:14 UTC by drazul

#### What this PR does / why we need it:
This PR fix one problem when we enable ssl connection and at the same time we disable the ssl authentication.

This PR also improve the chart running the command like from a script. With this new change we can edit the uri variable to get the value from a file or from an environment variable, that will be mounted previously.

Example values file will use this new configuration:

```yaml
es:
  uri: "$(cat /secrets/uri)"
secretMounts:
  - name: exporter-secrets
    secretName: elasticsearch-exporter
    path: /secrets
```

The alternative (working in the current stable chart) is
```yaml
es:
  uri: https://user:password@my-elasticsearch-cluster.example.com
```

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-06-10 13:37 UTC, caarlos0 commented on stable/elasticsearch-exporter/Chart.yaml
> +version: 3.3.1
if it adds new feature, should increase the minor instead of patch

https://semver.org/

2020-06-10 13:42 UTC, drazul commented on stable/elasticsearch-exporter/Chart.yaml
> +version: 3.3.1
true.
Increased to version 3.4.0

2020-06-12 07:58 UTC, drazul commented
> > This PR also improve the chart running the command like from a script. With this new change we can edit the uri variable to get the value from a file or from an environment variable, that will be mounted previously.
> 
> Wasn't this possible before with the inline command too?

No, I tried it. The use of environment variables or sub commands (as in my example) are not resolved inside of the pod.

This is the error log if I try to use `uri: "$(cat /secrets/uri)"` with the current chart:
```
level=error ts=2020-06-12T07:54:58.701668241Z caller=clusterinfo.go:174 msg="failed to retrieve cluster info from ES" err="Get $%28cat%20/secrets/uri%29: unsupported protocol scheme \"\""
```

2020-06-16 13:04 UTC, svenmueller requested changes
Please make sure the pods get rolled in case the ConfigMap or Secret change (https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments).

2020-06-18 14:31 UTC, drazul commented
> Please make sure the pods get rolled in case the ConfigMap or Secret change (https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments).

Thanks, I forgot it.

2020-06-29 17:57 UTC, svenmueller approved these changes
lgtm

2020-08-16 06:57 UTC, closed without merging