[stable/cockroachdb] deprecating this cockroachdb chart repository
helm/charts pull request #23000
Opened 2020-06-29 20:57 UTC by jlinder

#### What this PR does / why we need it:

Given the deprecation of `stable`, future CockroachDB Helm charts are
now located at:

  code repository: https://github.com/cockroachdb/helm-charts
  charts repository: https://charts.cockroachdb.com

Update this repository to point users to the new locations.

Signed-off-by: James H. Linder <jamesl@cockroachlabs.com>

#### Checklist
 
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-06-29 20:57 UTC, jlinder commented
cc @DuskEagle

2020-06-30 14:16 UTC, DuskEagle commented
/lgtm
/approve

2020-06-30 19:58 UTC, jlinder commented
/test pull-charts-e2e

2020-06-30 23:57 UTC, scottrigby requested changes
Congrats on moving the chart 👏 Please also add the `deprecated` flag and other details at https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart. Otherwise this looks good 😄

2020-06-30 23:59 UTC, scottrigby commented
/lgtm cancel

2020-07-01 00:00 UTC, scottrigby commented
/ok-to-test

2020-07-01 19:34 UTC, jlinder commented
> Congrats on moving the chart 👏 Please also add the `deprecated` flag and other details at https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart. Otherwise this looks good 😄

Hi @scottrigby , I've made the requested updates to follow the deprecation process. PTAL.

2020-07-07 13:16 UTC, DuskEagle commented
/retest

2020-07-07 16:00 UTC, davidkarlsen commented
/retest

2020-07-08 14:08 UTC, DuskEagle commented
/lgtm
/retest

2020-07-08 17:52 UTC, scottrigby commented
@jlinder this all looks perfect 👌 

@DuskEagle reached out on slack because the CI is failing in an odd way here. I've looked into it and it's unclear why these tests succeed manually but not in charts CI. We could continue to investigate, but since this is a deprecation-only PR, I'm going to go ahead and bypass tests to merge. Thanks everyone for your hard work!

2020-07-08 17:53 UTC, scottrigby approved these changes

2020-07-08 17:54 UTC, merged

2020-07-08 17:55 UTC, scottrigby commented
I updated the list at https://github.com/helm/charts/issues/21103

2020-07-08 19:08 UTC, jlinder commented
@scottrigby Thanks for your help in getting this through!