add chartmuseum 0.1.0 to incubator
helm/charts pull request #2302
Opened 2017-09-20 07:11 UTC by jdolitsky

Initial version of ChartMuseum chart using emptyDir volume per convo in #helm-users
https://github.com/chartmuseum/chartmuseum

2017-09-20 15:52 UTC, scottrigby reviewed
Preliminary syntax check. More substantive review later, or can tag-team with others

2017-09-20 15:52 UTC, scottrigby commented on incubator/chartmuseum/Chart.yaml
> +  email: chartmuseum@gmail.com
Needs newline at EOF.

2017-09-20 15:52 UTC, scottrigby commented on incubator/chartmuseum/templates/deployment.yaml
> +{{ toYaml .Values.resources | indent 10 }}
Needs newline at EOF.

2017-09-20 15:52 UTC, scottrigby commented on incubator/chartmuseum/templates/service.yaml
> +    app: {{ template "common.fullname" . }}
Needs newline at EOF.

2017-09-20 15:52 UTC, scottrigby commented on incubator/chartmuseum/values.yaml
> +    memory: 64Mi
Needs newline at EOF.

2017-09-20 16:27 UTC, unguiculus commented
/assign

2017-09-20 18:52 UTC, nickadmolina commented
CLA for nickadmolina now signed

2017-09-20 19:12 UTC, unguiculus requested changes
Please fix the CLA.

2017-09-20 19:12 UTC, unguiculus commented on incubator/chartmuseum/templates/deployment.yaml
> +{{ include "common.labels.standard" . | indent 8 }}
Only `app` and `release` label should go here.

2017-09-20 19:12 UTC, unguiculus commented on incubator/chartmuseum/templates/service.yaml
> +    app: {{ template "common.fullname" . }}
Selector should be:
```yaml
app: {{ template "common.name" . }}
release: {{ .Release.Name | quote }}
```

2017-09-21 14:54 UTC, prydonius commented on incubator/chartmuseum/.gitignore
> +*.tgz
this file isn't necessary, we ignore this in the repo's root .gitignore

2017-09-21 14:54 UTC, prydonius commented on incubator/chartmuseum/requirements.yaml
> +dependencies:
yay!

2017-09-21 15:12 UTC, jdolitsky reviewed
@unguiculus @prydonius comments have been addressed

2017-09-21 16:22 UTC, prydonius commented
/ok-to-test

2017-09-21 16:22 UTC, prydonius approved these changes
this lgtm, will let @unguiculus @scottrigby take another look

2017-09-21 16:23 UTC, jdolitsky commented
@prydonius thanks much. do you need us to squash commits?

2017-09-21 16:27 UTC, jdolitsky commented
Jenkins failing with
`template: no template "common.fullname" associated with template "gotpl"`
Does the build process grab chart dependencies?

2017-09-22 09:11 UTC, prydonius commented
/retest

2017-09-22 09:16 UTC, prydonius commented
@jdolitsky tests are looking good now, thanks again for the fix

2017-09-25 13:17 UTC, jdolitsky commented
@unguiculus @scottrigby anything else?

2017-09-27 19:33 UTC, unguiculus requested changes

2017-09-27 19:33 UTC, unguiculus commented on incubator/chartmuseum/Chart.yaml
> +version: 0.1.0
Add `appVersion`

2017-09-27 23:54 UTC, jdolitsky commented on incubator/chartmuseum/Chart.yaml
> +version: 0.1.0
done.

2017-09-28 17:09 UTC, unguiculus approved these changes

2017-09-28 17:09 UTC, merged