[stable/mongodb-replicaset] liveness/startupProbe tuning
helm/charts pull request #23046
Opened 2020-07-02 10:20 UTC by wonko

#### What this PR does / why we need it:

- Adds a startupProbe to the chart, so a larger mongo install won't be terminated by the livenessProbe (will only apply on semverMatch >= 1.16).
- Updated the metrics container to also use the livenessProbe values instead of hardcoded ones.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-07-02 10:21 UTC, wonko commented
/assign @unguiculus

2020-07-07 18:47 UTC, steven-sheehy requested changes
/assign
/ok-to-test

2020-07-07 18:47 UTC, steven-sheehy commented on stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
> +{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
Looks like startupProbe is not enabled by default (e.g. marked beta) until 1.18. Would prefer this be set to that.

2020-07-07 18:47 UTC, steven-sheehy commented on stable/mongodb-replicaset/values.yaml
> +  initialDelaySeconds: 5
These don't match the README. Please sync them

2020-07-07 18:47 UTC, steven-sheehy commented on stable/mongodb-replicaset/templates/mongodb-statefulset.yaml
> +                - mongo
This shouldn't test mongo directly but run the same test as the readiness probe. The readiness probe already tests the mongo connection itself.

2020-07-08 07:13 UTC, wonko commented
Addressed all remarks @steven-sheehy

2020-07-08 14:37 UTC, steven-sheehy commented
Please fix conflicts and ensure all tests pass

2020-07-14 11:19 UTC, wonko commented
/retest

2020-07-14 14:16 UTC, steven-sheehy approved these changes
/lgtm

2020-07-14 14:17 UTC, merged