Publish Swift chart
helm/charts pull request #2314
Opened 2017-09-21 22:00 UTC by tamalsaha

Swift is an Ajax proxy for Helm Tiller https://github.com/appscode/swift

2017-10-14 17:56 UTC, unguiculus requested changes
* Please allow for configuring container resources.
* We've started namespacing templates. Please see #1785 and apply accordingly.

2017-10-14 17:56 UTC, unguiculus commented on stable/swift/templates/_helpers.tpl
> +{{- default .Chart.Name .Values.nameOverride | trunc 24 -}}
Truncate to 63

2017-10-14 17:56 UTC, unguiculus commented on stable/swift/templates/_helpers.tpl
> +{{- printf "%s-%s" $name .Release.Name | trunc 45 -}}
Truncate to 63

2017-10-16 21:17 UTC, tamalsaha commented
@unguiculus PTAL

2017-10-17 11:42 UTC, tamalsaha commented
It seems circle ci setup has problem. I see no error.

2017-10-17 14:12 UTC, unguiculus commented
The error is because your chart does not have any tests. You can ignore this for now but in the near future we will require tests for any new charts.

Please consider my comment about namespacing templates.

2017-10-17 20:07 UTC, tamalsaha commented
oh! I missed that part about namespacing templates. I will check. I wish it rules did not change between 2 pr reviews. :(

2017-10-20 14:28 UTC, mattfarina commented
@tamalsaha if you rebase off of master that should either fix your circleci check or it will provide an actionable error.

2017-11-03 11:39 UTC, unguiculus commented
@tamalsaha Any change you'll get the namespacing of templates done?

2017-11-03 12:13 UTC, tamalsaha commented
I looked up what to do today . What I understood was that I need to update the `_helpers.tpl` to make it namespaced. And then update all the other places where those name/fullname templates are referred. is that all the change?

2017-11-04 17:15 UTC, tamalsaha commented
@unguiculus, PTAL. templates are namespaced, containers are more configurable.

2017-11-06 20:35 UTC, unguiculus commented
/ok-to-test

2017-11-06 20:38 UTC, unguiculus approved these changes

2017-11-06 20:38 UTC, unguiculus commented
/lgtm

2017-11-06 20:38 UTC, merged