[stable/oauth2-proxy] Use newer ingress API to be compatible with Kubernetes 1.16
helm/charts pull request #23161
Opened 2020-07-13 03:12 UTC by estahn

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:

Kubernetes 1.16 deprecates various APIs and therefore manifests require updates.
This PR updates the ingress API version and is backwards compatible so it can still be used with older Kubernetes versions.

#### Which issue this PR fixes

N/A

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-07-13 03:16 UTC, estahn commented
/assign @desaintmartin

2020-07-13 03:49 UTC, joeruello approved these changes

2020-07-13 04:01 UTC, arihantsurana approved these changes

2020-07-13 05:35 UTC, desaintmartin requested changes
Thanks ! 
1/ please see changes like https://github.com/helm/charts/pull/19245/files for helm 3 support. 
2/ do not worry, old ingress is compatible until something like 1.22.

2020-07-13 06:51 UTC, estahn commented
@desaintmartin 

> 1/ please see changes like https://github.com/helm/charts/pull/19245/files for helm 3 support.

Is this working with helm 2?

2020-07-13 08:47 UTC, desaintmartin commented
Although I haven't found the minimal version of this API, a quick test using Helm 2.14 and a new chart shows that yes, it works.

2020-07-13 23:15 UTC, estahn commented
@desaintmartin Thanks for pointing this out. I wasn't aware of `.Capabilities.APIVersions.Has`, which looks much cleaner.

2020-07-15 07:54 UTC, desaintmartin commented
Thanks!
/lgtm

2020-07-15 08:00 UTC, merged