[stable/prometheus] bump alertmanager version to v0.21.0
helm/charts pull request #23253
Opened 2020-07-19 12:34 UTC by radhus

## What this PR does / why we need it:

Updates the Alertmanager image version to v0.21.0, as was intended in #22849 but probably missed by mistake.

#### Which issue this PR fixes

  - corrects missing update in #22849

#### Special notes for your reviewer:

Alertmanager version 0.21.0 removes support from HipChat ([see release notes](https://github.com/prometheus/alertmanager/releases/tag/v0.21.0)).

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] ~Variables are documented in the README.md~
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-07-19 12:34 UTC, radhus commented
PTAL @monotek :)

2020-07-19 12:57 UTC, monotek requested changes
How about updating the other images too?
Prometheus 2.19.2 etc...

2020-07-19 13:58 UTC, radhus commented
@monotek good suggestion, fixed :)

2020-07-19 17:52 UTC, monotek reviewed
Have you checked the other images versions too?

2020-07-19 22:28 UTC, radhus commented
@monotek yep for `prom/alertmanager`, `prom/node-exporter`, `prom/prometheus` and `prom/pushgateway`. We could bump `jimmidyson/configmap-reload` to `v0.4.0` but I don't typically use that so I'll leave that for another PR.

2020-07-19 22:53 UTC, monotek approved these changes
/lgtm
/approve

2020-07-19 22:55 UTC, radhus commented
/assign @zanhsieh

2020-07-20 07:52 UTC, monotek commented
/ok-to-test

2020-07-21 01:17 UTC, zanhsieh approved these changes

2020-07-21 01:17 UTC, zanhsieh commented
/lgtm

2020-07-21 01:18 UTC, zanhsieh commented
/assign

2020-07-21 01:25 UTC, merged