[stable/minio] Don't display the ACCESS_KEY and SECRET_KEY to console...
helm/charts pull request #23404
Opened 2020-07-30 21:50 UTC by jjasghar

- This puts some logic in for the NOTES.txt so you don't display the
  access_key and secret_key to the console
- Fix a missing `--api` for the command

Co-authored-by: Paul Czarkowski <username.taken@gmail.com>
Signed-off-by: JJ Asghar <jjasghar@gmail.com>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-07-30 21:50 UTC, jjasghar commented
/cc @paulczar

2020-08-07 17:44 UTC, harshavardhana requested changes

2020-08-07 17:44 UTC, harshavardhana commented on stable/minio/templates/NOTES.txt
> +	2. Get the ACCESS_KEY=$(kubectl get secret minio -o jsonpath="{.data.accesskey}" | base64 --decode) and the SECRET_KEY=$(kubectl get secret minio -o jsonpath="{.data.secretkey}" | base64 --decode)
Please submit the PR here https://github.com/minio/charts

2020-08-08 19:00 UTC, davidkarlsen commented
This chart has been deprecated: https://github.com/helm/charts/pull/23414 - please submit any PRs to https://github.com/minio/charts

2020-08-08 19:00 UTC, closed without merging

2020-09-09 21:38 UTC, jjasghar commented
Opened: https://github.com/minio/charts/pull/14