Add a chart for Stack2Slack
helm/charts pull request #2357
Opened 2017-09-29 07:09 UTC by dunglas

[Stack to Slack](https://github.com/dunglas/stack2slack) is a Slack that bot monitors StackExchange tags and automatically publishes new questions in configured Slack channels.

2017-11-03 15:11 UTC, unguiculus requested changes
Thanks for the PR. Note that we've started namespacing templates (see #1785). Please apply this to your chart.

2017-11-03 15:11 UTC, unguiculus commented on stable/stack2slack/values.yaml
> +  tag: latest
Please use a release version.

2017-11-03 15:11 UTC, unguiculus commented on stable/stack2slack/README.md
> +- Kubernetes 1.2+ with Beta APIs enabled
1.7+

2017-11-03 15:11 UTC, unguiculus commented on stable/stack2slack/Chart.yaml
> +- name: Kévin Dunglas
Use Github username.

2017-11-03 15:11 UTC, unguiculus commented on stable/stack2slack/Chart.yaml
> +version: 0.1.0
Add `appVersion`

2017-11-03 15:12 UTC, unguiculus commented
Please rebase your PR. It is way behind the current master.

2017-11-16 20:30 UTC, unguiculus commented
Marking this as stale. Please update within one week.

2017-11-16 23:22 UTC, dunglas commented
I'll do (sorry about the delay).

2017-11-22 20:31 UTC, unguiculus commented
/ok-to-test

2017-11-22 20:31 UTC, unguiculus commented
Please fix linting issue.

2017-12-05 19:55 UTC, unguiculus commented
Please have a look at the failing CI.

2018-01-17 09:22 UTC, dunglas commented
The CI failing looks legit. Providing a secret is mandatory to run the bot. What the procedure in this case @unguiculus?

2018-02-24 10:53 UTC, unguiculus requested changes
Your chart can only be merged when CI is green. In order for this to achieve you need to conditionally create the deployment similar to what you do in the NOTES.txt.

2018-02-24 10:53 UTC, unguiculus commented on stable/stack2slack/templates/_helpers.tpl
> +{{/* vim: set filetype=mustache: */}}
Helm 2.8+ creates a much better `_helpers.tpl`. Please update.

2018-02-24 10:53 UTC, unguiculus commented on stable/stack2slack/templates/deployment.yaml
> +apiVersion: extensions/v1beta1
`apps/v1beta2`

2018-02-24 10:53 UTC, unguiculus commented on stable/stack2slack/templates/deployment.yaml
> +spec:
Add `spec.selector` (required with `apps/v1beta2`)

2018-02-24 10:53 UTC, unguiculus commented on stable/stack2slack/templates/deployment.yaml
> +          - name: SLACK_API_TOKEN
Please use consistent list indentation style throughout the chart. I'd suggest you always indent two spaces.

2018-02-24 10:53 UTC, unguiculus commented on stable/stack2slack/templates/secrets.yaml
> + slackApiToken : {{ default "MISSING" .Values.slackApiToken | b64enc | quote }}
Incorrect indentation.

2018-08-24 18:14 UTC, closed without merging