[incubator/buzzfeed-sso]
helm/charts pull request #23632
Opened 2020-08-27 14:50 UTC by anas-aso

#### Is this a new chart
no

#### What this PR does / why we need it:
to be able to expose multiple endpoints behind buzzfeed-sso

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-08-27 15:00 UTC, anas-aso commented
@darioblanco @komljen can I have you reviews please ?

2020-08-31 10:33 UTC, darioblanco requested changes

2020-08-31 10:33 UTC, darioblanco commented on incubator/buzzfeed-sso/templates/ingress.yaml
> +          {{- end }}
Good idea. Let's make this backwards compatible with the current clients and then will be ready to go

2020-08-31 10:44 UTC, anas-aso commented on incubator/buzzfeed-sso/templates/ingress.yaml
> +          {{- if .path }}
this is required since we set `.path` as deprecated.

2020-08-31 10:46 UTC, darioblanco approved these changes
/approve
/ok-to-test

2020-08-31 10:48 UTC, darioblanco commented
/approve
/ok-to-test

2020-08-31 10:51 UTC, darioblanco commented
/lgtm

2020-08-31 10:52 UTC, merged