[stable/prometheus] Unify labels and annotations
helm/charts pull request #23689
Opened 2020-09-04 08:56 UTC by hmlkao

#### Is this a new chart
No

#### What this PR does / why we need it:
This PR unify labels and annotations across all deploymets and statefulsets in stable/prometheus Helm chart.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-09-04 09:02 UTC, hmlkao commented
/assign @xtigyro

2020-09-04 09:09 UTC, hmlkao commented on stable/prometheus/templates/statefulsets/server.yaml
> -        {{- if .Values.server.statefulSet.labels}}
Removed according to current [Deployment template](https://github.com/helm/charts/pull/23689/files#diff-32b95905f07752b90f3b19f28816ead2L32-L34).

`.Values.server.statefulSet.labels` is used to add labels to StatefulSet itself, not pods.

2020-09-04 14:03 UTC, Xtigyro commented
/ok-to-test

2020-09-04 16:11 UTC, Xtigyro requested changes
@hmlkao Thanks for the contribution!

Could you please add all the `deploymentAnnotations` in the `values.yaml` file?

2020-09-04 22:15 UTC, Xtigyro commented
@hmlkao Also - we're in the middle of transition to the new repo for the Prometheus Helm charts. Where would you like this PR to be merged and to be a contributor - here or in the new repo (https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus)?

2020-09-05 06:08 UTC, scottrigby commented
See #23692. We're ready to deprecate stable/prometheus in favor of the new repo. Can this PR please be opened over there instead?

2020-09-05 06:48 UTC, Xtigyro commented
@hmlkao The only option has become the new repo. Please open the same PR there if it's okay for ya. Apologies for the double effort!

@scottrigby Agreed.

2020-09-05 06:54 UTC, closed without merging

2020-09-05 18:52 UTC, hmlkao commented
Well, I've created PR in new repo and add requested additions
https://github.com/prometheus-community/helm-charts/pull/45