Update keeper-statefulset.yaml
helm/charts pull request #23749
Opened 2020-09-11 02:57 UTC by wawa0210

Add pod anti-affinity to avoid pod being scheduled to the same node in high availability scenarios

#### Is this a new chart
> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

#### What this PR does / why we need it:
Add pod anti-affinity to avoid pod being scheduled to the same node in high availability scenarios

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
Add pod anti-affinity to avoid pod being scheduled to the same node in high availability scenarios

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-09-11 16:58 UTC, lwolf requested changes
Please make affinity configurable [values.yaml](https://github.com/helm/charts/blob/master/stable/coredns/values.yaml#L136-L147), [usage](https://github.com/helm/charts/blob/master/stable/coredns/templates/deployment.yaml#L65-L68). It also makes sense to make it configurable for all the components and please update the readme.

2020-09-12 05:47 UTC, wawa0210 commented
> Please make affinity configurable values.yaml, usage. It also makes sense to make it configurable for all the components and please update the readme.

Previously, values.yaml already had a default value of `{}` for `affinity`. If the keeper component does not have node anti-affinity, it may be deployed on the same node, which will cause some problems, such as pv binding Not on

2020-09-12 13:37 UTC, lwolf commented
Ok, so I misunderstood your PR, I thought that there was no way to configure affinity. 
Since it is already in place, your change doesn't make sense to me. 
It's up to the user to set environment-specific affinity values, which you can do currently using values.yaml.

2020-09-14 01:31 UTC, wawa0210 commented
> It's up to the user to set environment-specific affinity values

I understand your point. It is reasonable to set the affinity according to the user environment~~~ Do you think it is necessary for us to note the recommended usage (pod anti-affinity) in values.yaml or readme? If it is not necessary, I can close this pr

2020-09-14 09:05 UTC, lwolf commented
Personally, I don't think it's necessary, having the way to configure is enough.

2020-09-14 10:34 UTC, wawa0210 commented
> Personally, I don't think it's necessary, having the way to configure is enough.

Agree with you, i will close this pr :>

2020-09-14 10:34 UTC, closed without merging