[stable/chartmuseum] Add runAsNonRoot, supplementalGroups and containerSecurityContext as security options
helm/charts pull request #23810
Opened 2020-09-24 15:31 UTC by Tijmen34

#### What this PR does / why we need it: 

It adds runAsNonRoot and supplementalGroups as optional Pod securityContext options. It also adds containerSecurityContext, where people can define securityContext options on container level (ex. allowPrivilegeEscalation and capabilities).

#### Special notes for your reviewer:
I want to implement this chart, but am unable to currently due to OPA updates. Being able to add the necessary securityContext options gives users the possibility to add more security to their deployments of this chart! (and gives me the ability to deploy it as well :smile: )

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-09-24 21:19 UTC, Tijmen34 commented
Looping in @olemarkus & @yurrriq as well.

2020-09-30 17:42 UTC, yurrriq commented on stable/chartmuseum/templates/deployment.yaml
> +        {{- else if .Values.securityContext.supplementalGroups }}
why `else if` here?

2020-10-02 16:40 UTC, jdolitsky requested changes

2020-10-02 16:40 UTC, jdolitsky commented on stable/chartmuseum/Chart.yaml
> +version: 2.13.4
Can we make this 2.14.0 since we are adding features via new values?

2020-10-05 13:35 UTC, jdolitsky commented
/ok-to-test

2020-10-05 13:41 UTC, jdolitsky commented
/lgtm

2020-10-05 13:43 UTC, merged