[stable/airflow] Allow for separate custom readiness path
helm/charts pull request #23966
Opened 2020-10-27 22:57 UTC by Kristof-Mattei

#### What this PR does / why we need it:

Allow for a custom readiness probe path for the Airflow ingress.

When using the `nginx-ingress` we want to make sure that `https://internal/airflow` and `https://internal/airflow/` (notice trialing slash) work. 

To do this we append `(/|$)(.*)` to our paths for the ingresses in K8s. 

While the `livenessProbe` allows for a separate `livenessPath`, the `readinessProbe` has no such functionality, meaning when we set `ingress.web.path` to something like `/airflow(/|$)(.*)` the following probe gets generated:
```
           readinessProbe:
             httpGet:
               scheme: HTTP
               path: "/airflow(/|$)(.*)/health"
               port: web
```

This causes the probe to fail.

This PR adds a separate `readinessPath`, just like the `livenessPath`, fixing this problem.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)

2020-10-28 00:10 UTC, thesuperzapper requested changes
You might also want to implement this for the flower ingress, for example: `ingress.flower.readinessPath`

Is the README.md for URl prefixes still correct? https://github.com/helm/charts/tree/master/stable/airflow#url-prefix

Please squash your commits into one called: `[stable/airflow] create value for manual ingress readinessPath`

2020-10-28 00:10 UTC, thesuperzapper commented on stable/airflow/Chart.yaml
> +version: 7.13.2
If you add a value, yo must bump a minor version, and create documentation in UGRADE.md

So in this case `7.14.0`

2020-11-03 16:44 UTC, Kristof-Mattei commented
@thesuperzapper The Flower deployment doesn't have a `readinessProbe`. I'll add one and update the code as per your comments.

2020-11-05 08:50 UTC, thesuperzapper commented
@Kristof-Mattei  the `stable/airflow` helm chart has moved

Can you please raise your PR in the new repo?
https://github.com/airflow-helm/charts/tree/main/charts/airflow

2021-07-21 01:46 UTC, closed without merging