[WIP] Sensu Support
helm/charts pull request #241
Opened 2016-11-21 16:39 UTC by sstarcher

Adds https://sensuapp.org chart for Helm.

Sensu is made up of an api server and a worker process.  The worker process requires redis.  Uchiwa is a web interface for these components.  So a full setup requires
* Sensu Server
* Sensu Api Server
* Redis
* Uchiwa

A single Uchiwa setup can reference multiple sensu api servers.  Currently Uchiwa is it's own chart and makes sense for separate sensu environments.

The current setup is the Sensu chart depends on the Uchiwa and the Redis chart.  One difficulty I have is that the Uchiwa chart needs to know the name of the sensu api server to connect.  Which would currently be the svc created by the Sensu chart.  I don't see an easy way to pass this to the Uchiwa chart unless I inverted everything.  Uchiwa chart being the main chart that depends on sensu server, sensu api and redis.

I could also create the sensu server chart as a separate chart and create a sensu_stack or sensu_all chart that depends on uchiwa, redis, sensu?

2016-11-21 16:52 UTC, sstarcher commented
Current setup:
* Sensu
* * Uchiwa
* * Redis

I'm thinking it might be more flexible to restructure as
* Sensu Stack - Looking for a prefered name
* * Uchiwa
* * Redis
* * Sensu

2016-11-21 23:30 UTC, prydonius commented
@k8s-bot ok to test

2016-11-21 23:59 UTC, prydonius commented
@k8s-bot ok to test

2016-11-22 00:43 UTC, prydonius commented
@k8s-bot e2e test this

2016-11-22 15:34 UTC, sstarcher commented
Looks like I have a chicken and the egg problem.  This commit changes Uchiwa to reference the Sensu chart, but the Sensu chart does not exist yet.

2016-11-22 15:35 UTC, sstarcher commented
The current setup is
* Uchiwa
  * Sensu
    * Redis

2016-11-29 13:21 UTC, sstarcher commented
No longer a WIP

2016-11-29 13:34 UTC, sstarcher commented
I don't think the current failure is my setup as I truncate the metadata.name value

2016-11-30 06:09 UTC, viglesiasce commented
The issue is related to a change in CI. Fix is in flight. In the mean time I tried this out and things appear to be setup properly. 

I had to first package the sensu chart, then the uchiwa chart. 

Would it be too much of a pain to seperate the uchiwa changes out of this PR so we can move them after this gets in?

2016-11-30 15:49 UTC, sstarcher commented
@viglesiasce done and created a separate pull request for uchiwa

2016-12-01 02:07 UTC, viglesiasce commented
@k8s-bot ok to test

2016-12-02 15:37 UTC, sstarcher commented
@viglesiasce anything else you need me to do?  I'm going to be busy for the next week or so after today.

2016-12-05 19:17 UTC, viglesiasce requested changes
@sstarcher this looks good. Just one nit with the NOTES. Is there another way to test that sensu is accessible/working properly from outside the cluster. The HTTP endpoint in the NOTES does not seem to work (I'm guessing its just a socket waiting for events on the other side). 

Can you open this PR up to maintainer commits and I can take a stab at patching that NOTES output.

2016-12-05 19:17 UTC, viglesiasce commented on stable/sensu/templates/NOTES.txt
> +  echo http://127.0.0.1:4567
I was not able to connect over HTTP.

2016-12-05 19:25 UTC, sstarcher commented
It should work hit /info
https://sensuapp.org/docs/0.24/api/health-and-info-api.html

On Mon, Dec 5, 2016, 2:17 PM Vic Iglesias <notifications@github.com> wrote:

> *@viglesiasce* requested changes on this pull request.
>
> @sstarcher <https://github.com/sstarcher> this looks good. Just one nit
> with the NOTES. Is there another way to test that sensu is
> accessible/working properly from outside the cluster. The HTTP endpoint in
> the NOTES does not seem to work (I'm guessing its just a socket waiting for
> events on the other side).
>
> Can you open this PR up to maintainer commits and I can take a stab at
> patching that NOTES output.
> ------------------------------
>
> In stable/sensu/templates/NOTES.txt
> <https://github.com/kubernetes/charts/pull/241#pullrequestreview-11448098>
> :
>
> > +
> +
> +1. Get the Sensu API URL to visit by running these commands in the same shell:
> +{{- if contains "NodePort" .Values.serviceType }}
> +  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ template "fullname" . }})
> +  export NODE_IP=$(kubectl get nodes --namespace {{ .Release.Namespace }} -o jsonpath="{.items[0].status.addresses[0].address}")
> +  echo http://$NODE_IP:$NODE_PORT
> +
> +{{- else if contains "LoadBalancer" .Values.serviceType }}
> +**** NOTE: It may take a few minutes for the LoadBalancer IP to be available.                      ****
> +****       You can watch the status of by running 'kubectl get svc -w {{ template "fullname" . }}' ****
> +  export SERVICE_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ template "fullname" . }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
> +  echo http://$SERVICE_IP:{{ .Values.httpPort }}/login
> +{{- else if contains "ClusterIP"  .Values.serviceType }}
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "fullname" . }}" -o jsonpath="{.items[0].metadata.name}")
> +  echo http://127.0.0.1:4567
>
> I was not able to connect over HTTP.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/charts/pull/241#pullrequestreview-11448098>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADmpnmkz3rG5mXnn6M5g6gkQrk7NOJkeks5rFGM2gaJpZM4K4a1M>
> .
>

2016-12-05 19:27 UTC, sstarcher commented
it should work. Try /info https://sensuapp.org/docs/0.24/api/health-and-info-api.html

2016-12-05 20:11 UTC, viglesiasce commented
Yep that worked. Can you change the NOTES to point people there and maybe have a pointer to that endpoint documentation. They get a 404 as it stands now.

2016-12-19 14:09 UTC, sstarcher commented on stable/sensu/templates/NOTES.txt
> +  echo http://127.0.0.1:4567
updated docs

2016-12-19 21:46 UTC, viglesiasce commented
@k8s-bot ok to test

2016-12-19 21:47 UTC, viglesiasce approved these changes

2016-12-19 23:00 UTC, merged