Add the ability for the ElasticSearch chart to use emptyDir.
helm/charts pull request #2415
Opened 2017-10-05 15:26 UTC by dvonthenen

This is useful for testing and debugging to set the ElasticSearch persistent data to be saved to emptyDir.

2017-10-05 16:10 UTC, dvonthenen commented
Updated the initial commit comments. I believe this is good to go!

2017-10-05 16:11 UTC, dvonthenen commented
/ok-to-test

2017-10-12 17:08 UTC, dvonthenen commented
I will need to revisit this, after this PR https://github.com/kubernetes/charts/pull/1794

2017-10-13 14:37 UTC, dvonthenen commented
Hi @unguiculus I was hoping that you could take a look at this PR. Using this PR to make an additional change to the Jaeger chart to support ElasticSearch. Any feedback would be welcome.

2017-10-14 14:48 UTC, unguiculus commented
/cc @simonswine @icereval

2017-10-14 15:20 UTC, icereval requested changes
@dvonthenen, thanks for brining up such an obvious oversight in the chart.

Would you mind fully implementing the standard of moving storage for the `master` and `data` statefulset related keys under a `persistence` parent key. Here are a few charts I spot checked and seem to be very consistent.

[postgresql](https://github.com/kubernetes/charts/blob/master/stable/postgresql/values.yaml#L30)
[traefik](https://github.com/kubernetes/charts/blob/master/stable/traefik/values.yaml#L32)
[cassandra](https://github.com/kubernetes/charts/blob/master/incubator/cassandra/values.yaml#L14)

Thus the persistence toggle would be `<data/master>.persistence.enabled`.

Also an example from a [postgresql w/ replication chart](https://github.com/CenterForOpenScience/helm-charts/blob/master/postgresql/templates/master-statefulset.yaml#L104-L132) I've been working on I believe does most of what your looking for.

Thanks!

2017-10-20 13:13 UTC, dvonthenen commented
@icereval sure not a problem. Will update the PR shortly.

2017-10-20 13:15 UTC, closed without merging