Adding linting to Chart and values yaml files
helm/charts pull request #2429
Opened 2017-10-06 22:20 UTC by mattfarina

This does not lint yaml templates as they are templates rather
than valid yaml files. They cannot be linted with a normal linter

yamllint is used for linting. This is an existing Python project
https://github.com/adrienverge/yamllint

The rules are not the default rules and are stored in their
entirity so they can be controlled over time

The existance of a Chart.yaml file and values.yaml file is checked
and an error is thrown if one is missing. Helm lint will not
detect a chart if Chart.yaml is missing and if a values.yaml file
is missing it is noted as info.

The run function is introduced to enable running all the linters,
capturing non-zero exit codes, and exiting with a non-zdero code
if any of them fail. This is used instead of exiting when the
first failure happens to provide more feedback to chart developers.

/cc @prydonius @viglesiasce @unguiculus 

You can see an example of a failure at https://circleci.com/gh/mattfarina/charts/41

There are [docs on configuring yamllint](https://yamllint.readthedocs.io/en/latest/index.html) including the [rules](https://yamllint.readthedocs.io/en/latest/rules.html). I tried to tailor our rules to the existing charts. Though, many of the charts fail the rules and are inconsistent.

You can take a look at all the lint failures we have in the existing stable and incubator charts in [this gist](https://gist.github.com/mattfarina/7bf1ee3a757a8959fc8e4ea67e5a6d85) based on the rules in the config file here.

Once we agree on a set of rules I can create separate PRs to clean up the existing charts.

References #2373

2017-10-08 12:15 UTC, unguiculus requested changes
Just a few nits. Looks fine otherwise. Maybe we can use `helm template` in the future to generate Yaml files that we can feed into the linter.

2017-10-08 12:15 UTC, unguiculus commented on test/circle/lint.sh
> +    if [ -e ${directory}/Chart.yaml ]
I'd prefer if you stick to the existing style and put `then` on the same line.

`if [ -e ${directory}/Chart.yaml ]; then`

2017-10-08 12:15 UTC, unguiculus commented on test/circle/lint.sh
> +    if [ -e ${directory}/values.yaml ]
See above.

2017-10-08 12:15 UTC, unguiculus commented on test/circle/lint.sh
> +        run yamllint -c test/circle/lintconf.yml ${directory}/Chart.yaml
The rest of the file seems to be indented with two spaces. Can we agree on one style?

2017-10-08 12:15 UTC, unguiculus commented on test/circle/lint.sh
> +          exitCode=1
Inconsistent indentation.

2017-10-09 13:43 UTC, mattfarina commented
@unguiculus Sorry about that. Thanks for catching those. I'm too used to my editor fixing issues like these automatically. I see I don't have that setup for shell scripts.

I've updated with a fix for the formatting.

2017-10-09 19:23 UTC, unguiculus commented
/lgtm

2017-10-09 19:23 UTC, unguiculus approved these changes

2017-10-09 19:23 UTC, merged