[stable/gcloud-sqlproxy] bump image tag to 1.11
helm/charts pull request #2430
Opened 2017-10-07 02:07 UTC by mandrean

Bumps the gcloud-sqlproxy image tag and updates the README.

2017-10-12 10:05 UTC, rimusz commented
please remove `stable/nginx-ingress/values.yaml` change, also there is no image tag change there nor readme change

2017-10-13 16:17 UTC, mattfarina requested changes
Please fix this PR as the changes listed are for one chart but appear to be two disconnected charts without a full change in either.

2017-10-13 16:17 UTC, mattfarina commented on stable/gcloud-sqlproxy/Chart.yaml
> +version: 0.2.1
This is a version bump to the gcloud-sqlproxy chart. Yet, there are no changes to this chart in the PR.

2017-10-13 16:17 UTC, mattfarina commented on stable/nginx-ingress/values.yaml
> +    tag: "0.9.0-beta.15"
This image tag change is to something other than the title of the PR or the chart change. The corresponding changes appear to be against 2 different projects.

2017-10-16 17:01 UTC, mandrean commented
@rimusz @mattfarina Ah yes, thanks for the heads up. That was an accident. Should be fixed now!

2017-11-09 15:56 UTC, mattfarina commented
/ok-to-test

2017-11-09 15:56 UTC, mattfarina approved these changes

2017-11-09 16:01 UTC, merged