[incubator/elasticsearch] Add pod disruption budgets.
helm/charts pull request #2530
Opened 2017-10-20 03:13 UTC by jmcarp

So that clusters don't become unavailable during node restarts.

cc @icereval

2017-10-26 10:08 UTC, icereval requested changes
A couple small requests, thanks for the help!

2017-10-26 10:08 UTC, icereval commented on incubator/elasticsearch/templates/master-statefulset.yaml
> +---
Please move the inline definition to a file, naming suggestion `master-pdb.yaml`

2017-10-26 10:08 UTC, icereval commented on incubator/elasticsearch/templates/data-statefulset.yaml
> +---
Inline definition to a file, naming suggestion `data-pdb.yaml`

2017-10-26 10:08 UTC, icereval commented on incubator/elasticsearch/values.yaml
> +    minAvailable: 1
Need readme documentation for this value

2017-10-26 10:10 UTC, icereval commented on incubator/elasticsearch/templates/master-statefulset.yaml
> +  name: "{{ template "elasticsearch.master.fullname" . }}-master-budget"
Should not need the ending suffix, assuming there is no specific reason behind this choice.

2017-10-26 10:11 UTC, icereval commented on incubator/elasticsearch/templates/data-statefulset.yaml
> +  name: "{{ template "elasticsearch.master.fullname" . }}-data-budget"
same as below, but should be `{{ template "elasticsearch.data.fullname" . }}`

2017-11-17 16:14 UTC, unguiculus commented
Marking this as stale. Please update within one week.

2017-11-29 18:50 UTC, viglesiasce commented
@unguiculus this is ready for review.

2017-11-29 18:51 UTC, viglesiasce commented
/ok-to-test

2017-11-29 20:47 UTC, unguiculus commented
@jmcarp Readme update still missing.

2017-12-09 17:05 UTC, unguiculus commented
Marking stale. Please update readme.

2017-12-18 20:09 UTC, unguiculus commented
Closing as stale. Feel free to reopen if/when you decide to pick this up again.

2017-12-18 20:09 UTC, closed without merging