[stable/traefik]update rbac apiversion to v1.
helm/charts pull request #2550
Opened 2017-10-22 04:04 UTC by zouyee

2017-10-22 19:33 UTC, krancour commented
This PR doesn't make any sense.

2017-10-23 15:07 UTC, krancour commented on stable/traefik/Chart.yaml
> +version: 2.12.1
Why are major and patch numbers both being incremented?

2017-10-23 15:08 UTC, krancour commented on stable/traefik/templates/rbac.yaml
> +apiVersion: rbac.authorization.k9s.io/v1
k9s? That's not a thing.

2017-10-27 18:36 UTC, mattfarina requested changes
This PR can't be merged until after Kubernetes 1.9 is out. rbac/v1 is supported in Kubernetes 1.8 but not 1.7. The [charts repo needs to support the latest and the previous minor releases](https://github.com/kubernetes/charts/blob/master/README.md#supported-kubernetes-versions). [Beta APIs are supported for 2 versions/6 months after the v1 is out](https://kubernetes.io/docs/reference/deprecation-policy/) so we can continue to use beta1 until after 1.9 is out. [1.9 is slated to be released on Dec 13th](https://github.com/kubernetes/features/blob/master/release-1.9/release-1.9.md). At that time if you would like to contribute rbac/v1 support it would be appreciated.

Note, at that point the chart version will likely need to be changed from the version in the PR to be newer than the chart at that time.

2017-11-22 21:27 UTC, viglesiasce commented
This PR cannot be accepted as is due to the typos and version bump issues.

2017-11-29 18:53 UTC, viglesiasce commented
Closing as stale.

2017-11-29 18:53 UTC, closed without merging