[incubator/wekan] Initial commit of chart.
helm/charts pull request #2583
Opened 2017-10-24 22:47 UTC by jpds

2017-11-03 15:06 UTC, unguiculus requested changes
Thanks for the PR.

2017-11-03 15:06 UTC, unguiculus commented on incubator/wekan/README.md
> +| `resources.limits.cpu`  | Container requested CPU             | `nil`                                               |
Please align the table nicely.

2017-11-03 15:06 UTC, unguiculus commented on incubator/wekan/templates/deployment.yaml
> +          env:
For a consistent list indentation style, please add one level of indentation.

2017-11-03 15:06 UTC, unguiculus commented on incubator/wekan/values.yaml
> +  rootURL: ''
I'd suggest you go with `mongoUrl` and `rootUrl`.

2017-11-03 15:06 UTC, unguiculus commented
/ok-to-test

2017-11-03 15:21 UTC, unguiculus commented
Tests probably fail because of the missing MongoDB. Either add a chart dependency to MongoDB or make sure resources are only created when the URL is set showing a prominent warning via NOTES.txt along with directions how to fix this.

2017-11-16 20:29 UTC, unguiculus commented
Marking this as stale. Please update within one week.

2017-11-23 16:48 UTC, viglesiasce commented
Closing as stale

2017-11-23 16:48 UTC, closed without merging