introduce incubator/drone
helm/charts pull request #2614
Opened 2017-10-29 09:46 UTC by christian-roggia

This is a continuation of the PRs https://github.com/kubernetes/charts/pull/821 and https://github.com/kubernetes/charts/pull/353.

TODO:

- [x] upgrade to version 0.8.1
- [x] standardize source to helm 2.7
- [x] test service.type=ClusterIP
- [x] test ingress
- [x] test bare install
- [x] test source control provider installation
- [ ] README
- [ ] test service.type=LoadBalancer
- [ ] test service.type=NodePort

The Chart has been tested on a cluster configured via kubeadm with niginx-ingress installed and configured. The cluster version is 1.8.2. This cluster was installed on bare metal (Ubuntu 16.04) and unfortunately I do not have access to a LoadBalancer right now.

If you can contribute to the Chart by testing it on your cluster with different configurations and report if everything is working correctly it would be really appreciated.

Also, I really need help with the README, if anyone can improve it please let me know.

2017-11-06 21:00 UTC, unguiculus requested changes

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/templates/deployment-agent.yaml
> +    heritage: "{{ .Release.Service }}"
Add component label: `component: agent`

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/templates/deployment-agent.yaml
> +    app: {{ template "drone.fullname" . }}-agent
Should be: `app: {{ template "drone.name" . }}`

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/templates/deployment-agent.yaml
> +        app: {{ template "drone.fullname" . }}-agent
Should be: `app: {{ template "drone.name" . }}`

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/templates/deployment-agent.yaml
> +        heritage: "{{ .Release.Service }}"
Only `app`, `release`, and `component` labels should go here.

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/templates/deployment-server.yaml
> +    app: {{ template "drone.fullname" . }}-server
Should be: `app: {{ template "drone.name" . }}`

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/templates/deployment-server.yaml
> +    heritage: "{{ .Release.Service }}"
Add component label: `component: server`

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/templates/deployment-server.yaml
> +        heritage: "{{ .Release.Service }}"
Only `app`, `release`, and `component` labels should go here.

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/templates/secrets.yaml
> +    app: {{ template "drone.fullname" . }}
`app: {{ template "drone.name" . }}`

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/templates/service.yaml
> +    app: {{ template "drone.fullname" . }}
`app: {{ template "drone.name" . }}`

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/templates/service.yaml
> +  selector:
```yaml
app: {{ template "drone.name" . }}
release: {{ .Release.Name | quote }}
component: server
```

2017-11-06 21:00 UTC, unguiculus commented on incubator/drone/values.yaml
> +# shared_secret: supersecret
Use camel case: `sharedSecret`

2017-11-07 16:51 UTC, unguiculus commented
/ok-to-test

2017-11-07 18:02 UTC, unguiculus approved these changes

2017-11-07 18:16 UTC, unguiculus commented
I tested with a LoadBalancer service and Github. I get redirected to Github and then get "cannot register unguiculus. registration closed". Maybe I misconfigured something. I guess this shouldn't stop us from merging?

2017-11-07 18:23 UTC, christian-roggia commented
You have to uncomment/set the environment variable `server.env.DRONE_ADMIN="unguiculus"`

2017-11-07 19:40 UTC, unguiculus commented
Must have missed that. Working now.

2017-11-07 19:43 UTC, unguiculus commented
/lgtm

2017-11-07 19:47 UTC, merged

2017-11-22 15:46 UTC, steffenmllr commented
@christian-roggia I tried the chart on my fresh `v1.8.3` cluster. Syncing the git Repos worked fine. The build was also triggered. It seems like the communication between the worker doesn't work as expected:

### UI Log
```
+ git init
Initialized empty Git repository in /drone/src/github.com/my/repo/.git/
+ git remote add origin https://github.com/my/repo.git
+ git fetch --no-tags origin +refs/heads/mybranch:
fatal: unable to access 'https://github.com/my/repo.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
exit status 128
```

## drone-drone-agent log
```
{"time":"2017-11-22T15:18:27Z","level":"debug","message":"request next execution"}
INFO: 2017/11/22 15:18:27 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 10.3.197.142:9000: getsockopt: connection refused"; Reconnecting to {drone-drone:9000 <nil>}
INFO: 2017/11/22 15:18:28 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 10.3.197.142:9000: getsockopt: connection refused"; Reconnecting to {drone-drone:9000 <nil>}
{"time":"2017-11-22T15:19:41Z","level":"debug","repo":"my/repo","build":"1","id":"1","message":"received execution"}
{"time":"2017-11-22T15:19:41Z","level":"debug","repo":"my/repo","build":"1","id":"1","message":"listen for cancel signal"}
{"time":"2017-11-22T15:19:42Z","level":"debug","repo":"my/repo","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","exit_code":0,"exited":false,"message":"update step status"}
{"time":"2017-11-22T15:19:42Z","level":"debug","repo":"my/repo","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","exit_code":0,"exited":false,"message":"update step status complete"}
{"time":"2017-11-22T15:19:47Z","level":"debug","repo":"my/repo","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","message":"log stream opened"}
{"time":"2017-11-22T15:20:41Z","level":"debug","repo":"my/repo","build":"1","id":"1","message":"pipeline lease renewed"}
{"time":"2017-11-22T15:21:41Z","level":"debug","repo":"my/repo","build":"1","id":"1","message":"pipeline lease renewed"}
{"time":"2017-11-22T15:22:41Z","level":"debug","repo":"my/repo","build":"1","id":"1","message":"pipeline lease renewed"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","message":"log stream copied"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","message":"log stream uploading"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","message":"log stream upload complete"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","message":"log stream closed"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","exit_code":1,"exited":true,"message":"update step status"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","image":"plugins/git:latest","stage":"clone","exit_code":1,"exited":true,"message":"update step status complete"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","error":"","exit_code":1,"message":"pipeline complete"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","message":"uploading logs"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","message":"uploading logs complete"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","error":"","exit_code":1,"message":"updating pipeline status"}
{"time":"2017-11-22T15:22:51Z","level":"debug","repo":"my/repo","build":"1","id":"1","message":"stop listening for cancel signal"}
{"time":"2017-11-22T15:22:52Z","level":"debug","repo":"my/repo","build":"1","id":"1","message":"updating pipeline status complete"}
{"time":"2017-11-22T15:22:52Z","level":"debug","message":"request next execution"}
{"time":"2017-11-22T15:22:52Z","level":"debug","repo":"my/repo","build":"1","id":"1","message":"pipeline done"}
```


## drone-drone-dind log
```
time="2017-11-22T15:18:24.897826532Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found" 
time="2017-11-22T15:18:24.898018137Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]" 
time="2017-11-22T15:18:24.908200825Z" level=info msg="libcontainerd: new containerd process, pid: 19" 
time="2017-11-22T15:18:25.995581049Z" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2017-11-22T15:18:25.996235868Z" level=info msg="Loading containers: start." 
time="2017-11-22T15:18:25.997241996Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1" 
time="2017-11-22T15:18:25.997910115Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1" 
time="2017-11-22T15:18:25.998602435Z" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1" 
time="2017-11-22T15:18:26.194142059Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address" 
time="2017-11-22T15:18:26.249548225Z" level=info msg="Loading containers: done." 
time="2017-11-22T15:18:26.255982607Z" level=info msg="Daemon has completed initialization" 
time="2017-11-22T15:18:26.256009207Z" level=info msg="Docker daemon" commit=89658be graphdriver=overlay version=17.05.0-ce 
time="2017-11-22T15:18:26.263192510Z" level=info msg="API listen on [::]:2375" 
time="2017-11-22T15:18:26.263266912Z" level=info msg="API listen on /var/run/docker.sock" 
time="2017-11-22T15:19:47Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1" 
time="2017-11-22T15:19:47Z" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1" 
time="2017-11-22T15:22:51.354480591Z" level=error msg="Error closing logger: invalid argument" 
time="2017-11-22T15:22:51.808390049Z" level=error msg="Handler for POST /v1.26/containers/0_8410094534320841776_clone/kill returned error: Cannot kill container 0_8410094534320841776_clone: Container 6ee4d4c94ee7c36a769aeb69e59cad782579dca1837061581f39150fcd71fc6f is not running" 
```

2017-11-22 16:02 UTC, christian-roggia commented
Hi @steffenmllr thank you for your report, I installed the drone chart in my cluster and the build was successful. I was therefore unsuccessful in reproducing your bug, my logs are clean and the build did not fail.

Can you open a new issue and provide more information? That would help a lot!

2017-11-22 20:30 UTC, steffenmllr commented
Hey @christian-roggia thanks for your reply. I've put everything I know in #2837 - if you need more information let me know. For now I've switched back to my normal k8n deployment of an older drone version which works. Thanks for your work.