Indroduce incubator/keycloak
helm/charts pull request #2623
Opened 2017-10-30 22:25 UTC by nexeck

Todo:
- [ ] test service.type=ClusterIP
- [ ] test ingress
- [ ] test bare install
- [ ] test service.type=LoadBalancer
- [ ] test service.type=NodePort

2017-10-31 09:16 UTC, nexeck commented
I am not able to test this with an AWS ELB.
Can only verify, that k8s is trying to get the ELB, but i am not able to give aws access rights to the k8s for creating elb's.

2017-11-10 10:03 UTC, unguiculus requested changes
Thanks for the PR. I suggest you remove the configmap and use values from `values.yaml` directly. I think it is an unnecessary indirection.

The Postgres dependency should be optional. But this can be done in a follow-up PR.

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/templates/NOTES.txt
> +    export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "keycloak.fullname" . }}" -o jsonpath="{.items[0].metadata.name}")
`-l app={{ template "keycloak.name" . }},release={{ .Release.Name }}`

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/templates/configmap.yaml
> +    app: {{ template "keycloak.fullname" . }}
`{{ template "keycloak.name" . }}`

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/templates/deployment.yaml
> +    app: {{ template "keycloak.fullname" . }}
`{{ template "keycloak.name" . }}`

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/templates/deployment.yaml
> +        app: {{ template "keycloak.fullname" . }}
```yaml
app: {{ template "keycloak.name" . }}
release: "{{ .Release.Name }}"
```

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/templates/deployment.yaml
> +{{ toYaml .Values.keycloak.resources | indent 12 }}
12 doesn't look correct. Please use a consistent list indentation style and then fix the indentation level. Personally, I'd indent all lists one level.

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/templates/ingress.yaml
> +    app: {{ template "keycloak.fullname" . }}
`app: {{ template "keycloak.name" . }}`

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/templates/secrets.yaml
> +    app: {{ template "keycloak.fullname" . }}
`app: {{ template "keycloak.name" . }}`

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/templates/service.yaml
> +    app: {{ template "keycloak.fullname" . }}
`app: {{ template "keycloak.name" . }}`

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/templates/service.yaml
> +    app: {{ template "keycloak.fullname" . }}
```yaml
app: {{ template "keycloak.name" . }}
release: "{{ .Release.Name }}"
```

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/values.yaml
> +  postgresPassword: keycloak
Default should be auto-generated.

2017-11-10 10:03 UTC, unguiculus commented on incubator/keycloak/values.yaml
> +    requests:
Don't specify defaults for resource. We generally recommend to leave this a conscious choice of the user.

2017-11-10 15:27 UTC, unguiculus requested changes
Great addition, thanks. Coincidentally, I was planning to add a Keycloak chart as well. So, this comes just at the right time for me. I'll probably adapt the chart to allow for a HA setup once I get that up and running.

2017-11-10 15:27 UTC, unguiculus commented on incubator/keycloak/templates/deployment.yaml
> +          value: {{ default "INFO" .Values.keycloak.loglevel | quote }}
Remove `default` function. It is unnecessary since the default value comes from `values.yaml` anyways. Apply everywhere.

2017-11-10 15:27 UTC, unguiculus commented on incubator/keycloak/templates/secrets.yaml
> +  keycloak-password:  {{ .Values.keycloak.password | b64enc | quote }}
Allow a default password to be generated.

2017-11-13 07:10 UTC, unguiculus commented on incubator/keycloak/templates/NOTES.txt
> +    kubectl get secret --namespace {{ .Release.Namespace }} {{ template "keycloak.fullname" . }} -o jsonpath="{.data.keycloak-password}" | base64 --decode; echo
I wouldn't print the password in plain text. I think Redis has a good example for password directions:

https://github.com/kubernetes/charts/blob/master/stable/redis/templates/NOTES.txt

2017-11-13 07:11 UTC, unguiculus commented
/ok-to-test

2017-11-13 07:14 UTC, unguiculus approved these changes

2017-11-13 07:15 UTC, unguiculus commented
I'm merging this now. My comment in the NOTES.txt can be considered for a subsequent PR.

2017-11-13 07:16 UTC, merged