[elasticsearch] add podAnnotations value
helm/charts pull request #2649
Opened 2017-11-02 19:50 UTC by jslusher

This creates a `podAnnotations` value for the client, master and data
templates. This will enable downstream charts to add annotations to Pods
created by this chart.

2017-11-02 21:50 UTC, jslusher commented
I signed it!

2017-11-03 19:59 UTC, mattfarina requested changes

2017-11-03 19:59 UTC, mattfarina commented on incubator/elasticsearch/templates/client-deployment.yaml
> +      annotations:
Can you move the `annotation` inside the if statement. That way it's not in the generated yaml if it has no content. There are a few places to make this change.

2017-11-16 14:45 UTC, mattfarina approved these changes

2017-11-16 14:46 UTC, mattfarina commented
/ok-to-test

2017-12-01 03:24 UTC, mikn commented
This looks good to me. :)

2017-12-15 00:59 UTC, viglesiasce commented
/lgtm

2017-12-15 01:02 UTC, viglesiasce commented
/lgtm

2017-12-15 01:08 UTC, merged