Add sensu as a dependency and improve configuration
helm/charts pull request #265
Opened 2016-11-30 15:49 UTC by sstarcher

The sensu pull request needs merged first  #241

2016-11-30 18:52 UTC, prydonius commented
@k8s-bot ok to test

2016-11-30 21:12 UTC, prydonius commented on stable/uchiwa/requirements.yaml
> +dependencies:
Can you also add the requirements.lock?

2016-11-30 21:20 UTC, sstarcher commented on stable/uchiwa/requirements.yaml
> +dependencies:
I can after the sensu chart pull request is merged.  #241

2016-12-07 02:39 UTC, prydonius commented
Going to mark this with 'changes needed' given it depends on #241

2016-12-20 00:14 UTC, viglesiasce requested changes
Unable to install due to error with resource definition.

2016-12-20 00:14 UTC, viglesiasce commented on stable/uchiwa/templates/deployment.yaml
>  {{ toYaml .Values.resources | indent 8 }}
I couldnt get this chart to install anymore. I am getting:

```console
Error: release illocutionary-opossum failed: error validating "": error validating data: [found invalid field requests for v1.Container, found invalid field requests for v1.Container]
```

2016-12-20 15:59 UTC, sstarcher commented
This should function once #332 is merged

2017-01-03 17:31 UTC, viglesiasce approved these changes

2017-01-03 17:32 UTC, viglesiasce commented
@k8s-bot e2e test this

2017-01-03 17:33 UTC, sstarcher commented
@viglesiasce thanks

2017-01-04 23:40 UTC, viglesiasce commented
@k8s-bot e2e test this

2017-01-04 23:53 UTC, viglesiasce requested changes

2017-01-04 23:53 UTC, viglesiasce commented on stable/uchiwa/templates/deployment.yaml
> +{{ toYaml .Values.resources | indent 10 }}
Looks like this is still not quite right.

2017-01-05 00:10 UTC, viglesiasce commented on stable/uchiwa/templates/deployment.yaml
> +{{ toYaml .Values.resources | indent 10 }}
Actually it may be the Sensu chart that is screwed up. I believe K8s 1.5.1 is now being more strict about extraneous fields.

2017-01-05 00:57 UTC, sstarcher commented
@viglesiasce after fixing Sensu I never bumped the Sensu version Uchiwa was using.  So it was still using the bad sensu version.

2017-01-05 00:58 UTC, sstarcher commented on stable/uchiwa/templates/deployment.yaml
> +{{ toYaml .Values.resources | indent 10 }}
It's not k8s related it's using the Sensu 0.1.0 chart and that is messed up.  I updated it to the fixed 0.1.1 chart.

2017-01-09 19:58 UTC, viglesiasce commented
@k8s-bot e2e test this

2017-01-11 17:04 UTC, sstarcher commented
@viglesiasce does this need anything else?

2017-01-17 19:01 UTC, viglesiasce commented
Sorry for the delay @sstarcher!!

2017-01-18 22:58 UTC, lachie83 commented
@viglesiasce can you please approve the changes you requested?

2017-01-18 23:00 UTC, viglesiasce approved these changes

2017-01-18 23:18 UTC, merged