Make voyager chart namespaced
helm/charts pull request #2661
Opened 2017-11-04 16:43 UTC by tamalsaha

2017-11-04 18:21 UTC, tamalsaha commented
@unguiculus chart is namespaced

2017-11-06 20:33 UTC, unguiculus requested changes

2017-11-06 20:33 UTC, unguiculus commented on stable/voyager/templates/deployment.yaml
> +        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
Remove `default` function. It's unnecessary.

2017-11-06 20:35 UTC, tamalsaha commented
Addressed comments. PTAL

2017-11-06 20:39 UTC, unguiculus commented
/ok-to-test

2017-11-06 20:41 UTC, unguiculus commented
/lgtm

2017-11-06 20:41 UTC, unguiculus approved these changes

2017-11-06 20:41 UTC, merged