Make Stash chart namepaced
helm/charts pull request #2662
Opened 2017-11-04 17:37 UTC by tamalsaha

2017-11-04 18:21 UTC, tamalsaha commented
@unguiculus chart is namespaced

2017-11-06 20:18 UTC, unguiculus requested changes

2017-11-06 20:18 UTC, unguiculus commented on stable/stash/templates/deployment.yaml
> +        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
Remove the `default` function. It's unnecessary.

2017-11-06 20:18 UTC, unguiculus commented on stable/stash/templates/deployment.yaml
> +        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
Remove the `default` function. It's unnecessary.

2017-11-06 20:31 UTC, tamalsaha commented
Addressed comments. PTAL.

2017-11-06 20:37 UTC, unguiculus commented
/ok-to-test

2017-11-06 20:39 UTC, unguiculus approved these changes

2017-11-06 20:39 UTC, unguiculus commented
/lgtm

2017-11-06 20:39 UTC, merged