Publish kubed chart
helm/charts pull request #2664
Opened 2017-11-05 12:23 UTC by tamalsaha

```
Kubed (pronounced Cube-Dee) by AppsCode is a Kubernetes Cluster Operator Daemon. Kubed can do the following things for you:

Kubed can take periodic snapshot of a Kubernetes cluster objects.
Kubed provides a recycle bin for deleted and/or updated Kubernetes objects.
Kubed can keep ConfigMaps and Secrets synchronized across Namespaces.
Kubed can forward cluster events to various destinations.
Kubed can setup janitors for Elasticsearch and InfluxDB.
Kubed can send notifications via Email, SMS or Chat.
Kubed has a built-in search engine for your cluster objects using bleve.
```

2017-11-06 20:24 UTC, unguiculus requested changes

2017-11-06 20:24 UTC, unguiculus commented on stable/kubed/README.md
> +- Kubernetes 1.5+
1.7+ is officially supported.

2017-11-06 20:24 UTC, unguiculus commented on stable/kubed/templates/deployment.yaml
> +        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
Remove `default` function. It's unnecessary.

2017-11-06 20:32 UTC, tamalsaha commented
Addressed comments. PTAL.

2017-11-06 20:38 UTC, unguiculus commented
/ok-to-test

2017-11-09 17:52 UTC, unguiculus approved these changes

2017-11-09 17:52 UTC, merged