stable/kube2iam: added support for aws access keys
helm/charts pull request #2675
Opened 2017-11-06 23:56 UTC by jescarri

Added a secret resource to allow setting AWS access keys and region

2017-11-07 00:32 UTC, jescarri commented
bumping CLA.

2017-11-09 15:07 UTC, mgoodness requested changes
Couple of changes, otherwise LGTM

2017-11-09 15:07 UTC, mgoodness commented on stable/kube2iam/templates/secret.yaml
> +{{- if or (and .Values.aws.secret_key .Values.aws.access_key) -}}
Delete the `or` and the parens.

2017-11-09 15:07 UTC, mgoodness commented on stable/kube2iam/templates/secret.yaml
> +{{- if and .Values.aws.secret_key .Values.aws.access_key }}
Don't need this conditional.

2017-11-09 15:07 UTC, mgoodness commented
/ok-to-test

2017-11-09 18:35 UTC, mgoodness approved these changes

2017-11-09 18:35 UTC, mgoodness commented
/lgtm

2017-11-09 18:36 UTC, merged