Allowing usage of Kubernetes ingress in existing owncloud chart
helm/charts pull request #2681
Opened 2017-11-07 13:38 UTC by carmat88

With this PR we would like to add the option of using the Kubernetes' ingresses within the already existing owncloud chart. This is useful when load balancers are not available but an ingress controller is running in a Kubernetes cluster.

2017-11-07 13:44 UTC, carmat88 commented
The CI errors seem to be unrelated to what we have modified:

```
Linting the Chart.yaml and values.yaml files at stable/owncloud
stable/owncloud/values.yaml
  56:3      error    wrong indentation: expected 4 but found 2  (indentation)
  57:5      error    wrong indentation: expected 6 but found 4  (indentation)
  78:3      error    wrong indentation: expected 4 but found 2  (indentation)
  88:5      error    wrong indentation: expected 6 but found 4  (indentation)
  99:5      error    wrong indentation: expected 6 but found 4  (indentation)
  106:3     error    wrong indentation: expected 4 but found 2  (indentation)
  107:5     error    wrong indentation: expected 6 but found 4  (indentation)
```

Please let me know if I am wrong and whether I could correct the above lines anyway. Thanks!

2017-11-23 21:01 UTC, unguiculus requested changes
Thanks for the PR. Please bump chart version and fix linting issues.

2017-11-23 21:01 UTC, unguiculus commented on stable/owncloud/values.yaml
> +ingressController:
Should be `ingress` instead of `ingressController`.

2017-11-24 10:43 UTC, mcapuccini commented
@carmat88 @unguiculus I fixed requested edits, versioning, and linting problems. It should be ready to go now!

2017-11-25 14:03 UTC, unguiculus commented
Please indent with two spaces.

2017-11-25 20:59 UTC, mcapuccini commented
@unguiculus maybe I am missing something, but when indenting with 2 spaces the CI complains:

```
  106:3     error    wrong indentation: expected 4 but found 2  (indentation)
```

2017-11-25 21:26 UTC, unguiculus commented
/ok-to-test

2017-11-25 21:26 UTC, unguiculus approved these changes

2017-11-25 21:31 UTC, unguiculus commented
/lgtm

2017-11-25 21:31 UTC, merged

2017-11-25 21:31 UTC, mcapuccini commented
Thanks for fixing the last things!