[incubator/kibana] add Kibana chart
helm/charts pull request #2719
Opened 2017-11-10 23:16 UTC by compleatang

This PR adds a Kibana chart to the incubator library.

2017-11-16 21:08 UTC, unguiculus requested changes
Thanks for the PR. Can you explain/document the auth stuff better. You add an ingress for auth but don't add the oauth-proxy or a service for it. Why would that make sense?

2017-11-16 21:08 UTC, unguiculus commented on incubator/kibana/Chart.yaml
> +- name: Casey Kuhlman
Use Github username.

2017-11-16 21:08 UTC, unguiculus commented on incubator/kibana/README.md
> +`tolerations` | List of node taints to tolerate (requires Kubernetes >= 1.6) | `[]`
Remove `(requires Kubernetes >= 1.6)`. We support the current and the previous minor version, which is currently 1.7+.

2017-11-16 21:08 UTC, unguiculus commented on incubator/kibana/templates/deployment.yaml
> +      labels:
Only `release` and `app` labels should got here.

2017-11-16 21:08 UTC, unguiculus commented on incubator/kibana/templates/deployment.yaml
> +apiVersion: extensions/v1beta1
`apiVersion: apps/v1beta1`

2017-11-16 21:12 UTC, unguiculus commented
I've just seen #2717. It would probably make sense to add an optional dependency to it once it's merged. Since it has it's own ingress you probably don't need the additional ingress you added here.

2017-11-17 21:39 UTC, compleatang commented
Have pushed the requested changes. 

I am of two minds personally when it comes to the optional dependency. On the one hand I can see the handiness of it; on the other hand it doesn't work for my particular use case in that I deploy these under separate meta charts. Also, besides bitly/oauth-proxy there are probably other authentication daemons that are being used within the community. All this said, I'm happy to go in either direction the community thinks best as it is straightforward to add an optional dependency.

As to the extra ingress, the chart is built in line with [this documentation](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/external-auth); one important item is that the two ingress objects require different annotations for nginx-ingress to be able to effectively handle the authentication in an automated fashion. This, in turn, requires two different ingress objects. I have not seen (or worked out myself) an ability to collapse both into a single ingress object since we cannot place annotations on particular hosts/paths. If any one has other ideas I am all ears.

2017-11-29 16:38 UTC, rendhalver commented
Need help getting this tested?

2017-12-02 17:06 UTC, Morriz commented
I assume the oauth-proxy ingress should only live in that oauth-proxy chart, and not here. 
Also, any updates on this? Would love to use a nice clean kibana chart.

2017-12-04 12:22 UTC, compleatang commented
Any help moving this forward toward merge status would be welcome from my POV. 

Moving the ingress to another chart is sub-optimal for how we use this chart, namely to protect the domain that kibana is running on.

2017-12-04 12:31 UTC, Morriz commented
I believe from an open source chart maintenance perspective it wouldn't be preferred to have other functionality bleed into it. If you want to publish something as open source, please be aware of the unix philosphy. All charts published here are made that way, and do not have any implementation specifics in them.

But your problem touches on big issues with Helm charts in general: how to organize for orchestration of charts, but mostly their inter-part configuration. How do we publish/share sane defaults for likely scenarios?

2017-12-04 15:29 UTC, compleatang commented
Agree the "problem" sort of falls in a hole of how helm charts are being handled currently in my view -- at least from a best practices perspective. 

To be clear, I do not have strong opinions here. I'm just as happy to remove the ingress-auth and deal with that on my own installation. That is how we deal with protecting our kubernetes-dashboard deployment, for example. I do not see a clean way to put the ingress into the oauth-proxy chart. 

I added the ingress-auth to the PR as I do not see many use cases for deploying kibana where it would not be protected by some level of authentication. In distinction to, e.g., grafana which has in-built authentication, kibana does not have authentication inbuilt.

The ingress is built to not depend strongly on the oauth-proxy chart itself; any ingress authorization would likely work (although I have not tested it as such). 

This said, I'll happily defer to @unguiculus or any other maintainer as to how to deal with this inter-chart default challenge. If someone just let's me know a preferred default position here I will happily adapt the PR so this can get merged.

2017-12-04 16:24 UTC, Morriz commented
Yes, leaving any (auth) implementation to the end user is preferred.

Having said all that I think removing that auth-proxy ingress and supplying it as a seperate chart (which you already did, no?) would make the merge a no brainer.

2017-12-05 14:35 UTC, compleatang commented
Thanks to @jstriebel this should be good to go. @unguiculus hopefully everything is addressed now! :)

2017-12-05 19:05 UTC, unguiculus commented
/ok-to-test

2017-12-05 19:09 UTC, unguiculus requested changes
Looks pretty good. If you like, I'd suggest you move it to stable.

2017-12-05 19:09 UTC, unguiculus commented on incubator/kibana/Chart.yaml
> +description: Kibana is an open source data visualization plugin for Elasticsearch
Can you add an icon?

2017-12-06 00:21 UTC, compleatang commented on incubator/kibana/Chart.yaml
> +description: Kibana is an open source data visualization plugin for Elasticsearch
👍

2017-12-06 00:22 UTC, compleatang commented
Have changed to stable and added the icon. Hopefully g2g now! :)

2017-12-06 05:15 UTC, unguiculus commented
/ok-to-test

2017-12-06 05:23 UTC, unguiculus commented
/lgtm

2017-12-06 05:23 UTC, merged

2017-12-06 05:26 UTC, unguiculus commented
@compleatang After merging I noticed that the readme still refers to incubator. Could you create a new PR to fix this?

2017-12-06 10:52 UTC, jstriebel commented
@unguiculus, @compleatang Thanks for the new chart! I just opened PR #2947 for the README fix.

2017-12-06 21:47 UTC, compleatang commented
🎉  Thanks all! Especially @jstriebel @unguiculus and @Morriz