Add Verdaccio chart
helm/charts pull request #2727
Opened 2017-11-12 15:03 UTC by etiennetremel

This PR add a new stable chart for [Verdaccio](http://www.verdaccio.org/) (Lightweight private npm proxy registry).

2017-11-12 15:10 UTC, etiennetremel commented
CLA signed

2017-11-16 20:56 UTC, unguiculus requested changes
Thanks for the PR.

2017-11-16 20:56 UTC, unguiculus commented on stable/verdaccio/Chart.yaml
> +version: 0.1.0
Add `appVersion`

2017-11-16 20:56 UTC, unguiculus commented on stable/verdaccio/README.md
> +- Kubernetes 1.4+ with Beta APIs enabled
We support the current and the previous minor version. So, 1.7+ would be correct.

2017-11-16 20:56 UTC, unguiculus commented on stable/verdaccio/templates/deployment.yaml
> +apiVersion: extensions/v1beta1
`apiVersion: apps/v1beta1`

2017-11-16 20:57 UTC, unguiculus commented
/ok-to-test

2017-11-17 06:59 UTC, unguiculus commented
/retest

2017-11-17 06:59 UTC, unguiculus approved these changes

2017-11-17 07:11 UTC, unguiculus commented
/ok-to-test

2017-11-29 20:14 UTC, unguiculus commented
/lgtm

2017-11-29 20:14 UTC, merged