Add nginx-lego chart
helm/charts pull request #273
Opened 2016-12-03 00:29 UTC by jackzampolin

This chart runs an [`nginx-ingress-controller`](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx) and [`kube-lego`](https://github.com/jetstack/kube-lego) adding the ability to use `ingress` resources to route in your cluster as well as optionally generating `SSL` certs for you.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: foo
  annotations:
    # Add to route through the nginx service
    kubernetes.io/ingress.class: nginx
    # Add to generate certificates for this ingress
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    # With this configuration kube-lego will generate a secret in namespace foo called `example-tls`
    # for the URL `www.example.com`
    - hosts:
      - "www.example.com"
      secretName: example-tls
```

2016-12-05 20:38 UTC, viglesiasce commented
@k8s-bot ok to test

2016-12-07 02:22 UTC, prydonius commented
Thanks a lot @jackzampolin, will review!

2016-12-07 02:22 UTC, prydonius commented on stable/nginx-lego/README.md
> +- PV provisioner support in the underlying infrastructure
PV provisioner support isn't required for this chart

2016-12-07 02:25 UTC, prydonius commented
Would you be able to add a NOTES.txt file that describes possibles next steps for using this ingress controller? For example, printing out the example from the description of the PR would be good.

2016-12-08 00:37 UTC, jackzampolin commented
@prydonius Thanks for the review! Think I got it all!

2016-12-13 21:08 UTC, jackzampolin commented
Anything else needed for merge here?

2016-12-15 01:05 UTC, viglesiasce requested changes

2016-12-15 01:05 UTC, viglesiasce commented on stable/nginx-lego/templates/NOTES.txt
> +This chart runs an nginx-ingress-controller  {{- if .Values.lego.enabled -}}  and kube-lego  {{- end -}}  adding the ability to use ingress resources to route in your cluster  {{- if .Values.lego.ena
The two `-` on end causes the following typo in notes:
```
This chart runs an nginx-ingress-controllerand kube-legoadding
```

2016-12-15 01:05 UTC, viglesiasce commented on stable/nginx-lego/templates/NOTES.txt
> +apiVersion: extensions/v1beta1
This example ingress was not accepted for some reason. I keep getting:

```console
[root@centos-2939067299-844ns stable]# kubectl create -f ingress.yaml
error validating "ingress.yaml": error validating data: unexpected type: object; if you choose to ignore these errors, turn validation off with --validate=false
[root@centos-2939067299-844ns stable]# /usr/local/bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
[root@centos-2939067299-844ns stable]#
```

2016-12-15 01:05 UTC, viglesiasce commented on stable/nginx-lego/templates/default-service.yaml
> +  name: {{ template "fullname" . }}-default
Can we change these identifiers to be default-backend instead of default. I'd like it to be more clear if possible.

2016-12-15 19:38 UTC, jackzampolin commented on stable/nginx-lego/templates/default-service.yaml
> +  name: {{ template "fullname" . }}-default
+:+1:

2016-12-15 19:40 UTC, jackzampolin commented on stable/nginx-lego/templates/NOTES.txt
> +apiVersion: extensions/v1beta1
I was missing a whole section. I've added it.

2016-12-15 19:40 UTC, jackzampolin commented on stable/nginx-lego/templates/NOTES.txt
> +This chart runs an nginx-ingress-controller  {{- if .Values.lego.enabled -}}  and kube-lego  {{- end -}}  adding the ability to use ingress resources to route in your cluster  {{- if .Values.lego.ena
removed trailing `-`

2016-12-19 23:42 UTC, viglesiasce reviewed
One more change regarding default values. Once that is in we can merge this.

2016-12-19 23:42 UTC, viglesiasce commented on stable/nginx-lego/values.yaml
> +    email: "todd@influxdb.com"
Didn't notice this before but can we disable lego by default and put in fake emials and such. Id rather not have poor todd owning everydomain that people test with 😄

2016-12-20 00:38 UTC, jackzampolin commented on stable/nginx-lego/values.yaml
> +    email: "todd@influxdb.com"
🤕 Great catch.

2016-12-21 18:42 UTC, viglesiasce approved these changes

2016-12-21 19:28 UTC, merged