[stable/sentry] add config features
helm/charts pull request #2737
Opened 2017-11-14 00:46 UTC by gleeco

### summary

This PR adds new functionality for the Sentry chart to make it
more flexible and production-worthy.

### `required_backend`

A new top level object flags requirements for installation.
Both PG/Redis are default `true`.  
Example: install only Redis, put your Postgres on AWS RDS:

```
required_backend:
  redis: true
  postgresql: false
```

### `remoteHost` and alternate ports

if a required backend is false, `remoteHost` stands in.
Additionally, a template for the secret is rendered and 
creates the secret without the required chart; eg.

```
postgresql:
  remoteHost: sentry.xxxx.us-east-1.rds.amazonaws.com
  postgresUser: sentry
  postgresPassword: changeMe
  postgresDatabase: sentry
  postgresPort: "6432"
```

###  `tls_secret` and `ingress.tls_hosts`

A new top-level value for key/cert can be added automatically
with the notation, eg.

```
tls_secret:
  key: | 
  ....
  crt: |
  ...
```

This will populate a new TLS secret that can be used by ingress.
Leverage its use by leaving `ingress.tls` empty and instead using
`tls_hosts` to enumerate all hostnames on the cert. eg.

```
ingress:
  tls_hosts:
    - example.com
    - www.example.com
```

### fixup `user.password`

Whereas `user.password` did not take a value, a helm update on the
chart would overwrite this value with a new random.  Now, we allow
an input value to keep things pre-ordained and consistent.

2017-11-16 01:25 UTC, gleeco commented
cc @rothgar

2018-01-11 19:44 UTC, unguiculus requested changes
Sorry for the delay.

2018-01-11 19:44 UTC, unguiculus commented on stable/sentry/values.yaml
> +required_backend:
Use camel case.

2018-01-11 19:44 UTC, unguiculus commented on stable/sentry/templates/web-deployment.yaml
> +          value: {{ default "5432" .Values.postgresql.postgresPort | quote }}
Add defaults to `values.yaml` instead of using the `default` function.

2018-01-11 19:44 UTC, unguiculus commented on stable/sentry/templates/tls-secret.yaml
> +{{- if .Values.tls_secret }}
Use camel case.

2018-01-11 19:44 UTC, unguiculus commented
ping @rothgar

2018-02-27 04:35 UTC, mrgleeco commented
hello @unguiculus @rothgar  - this almost died on the vine.  Am happy to revisit - just lmk if you prefer a force push here of something up to date (w/ requested changes) or a new PR.

2018-02-27 07:05 UTC, rothgar commented
I guess that's up to @gleeco if he wants to incorporate the changes pointed out in comments. If not then I guess we should take the changes and put them in a new PR.

2018-02-27 15:11 UTC, mrgleeco commented
force pushed new / revised.   Please take a look

2018-02-27 18:09 UTC, mrgleeco commented
fyi @unguiculus @rothgar  - i've updated `sentry-featurer` here;  noting also that another PR came along doing the remote host thing too  at #3376

2018-02-27 20:17 UTC, unguiculus commented
Please fix your CLA.

2018-03-01 18:59 UTC, mrgleeco commented
hmm.. CLA is AFU.  I had changed the author commit to diff email/ github account.  
Too much headache

Please close this PR & take a look at https://github.com/kubernetes/charts/pull/3945

2018-03-01 20:30 UTC, closed without merging