[incubator/keycloak] Add high availability and various improvements
helm/charts pull request #2756
Opened 2017-11-15 15:39 UTC by unguiculus

* Add various improvements, such as node selector, tolerations, and pod anti-affinity
* Switch to StatefulSet due to length restrictions for WildFly node identifier and
  for potential advantages for cluster discovery when names pod stable
* Add high availability and clustering using JDBC_PING discovery for JGroups
* Add customizability via WildFly CLI

2017-11-15 15:39 UTC, unguiculus commented
cc @nexeck

2017-11-28 09:06 UTC, nexeck requested changes

2017-11-28 09:06 UTC, nexeck commented on incubator/keycloak/templates/NOTES.txt
> +    http://{{ .Values.keycloak.ingress.hostname }}
The hostname value does not exists anymore. It is a list with hosts.

2017-11-28 09:06 UTC, nexeck commented on incubator/keycloak/templates/NOTES.txt
> +  kubectl get secret --namespace {{ .Release.Namespace }} {{ template "keycloak.fullname" . }} -o jsonpath="{.data.password}" | base64 --decode; echo
The secret name is: { template "keycloak.fullname" . }}-http

2017-11-28 10:29 UTC, nexeck commented
Keycloak with external postgresql cluster and one keycloak instance is running on k8s 1.8.1

2017-11-28 16:41 UTC, unguiculus commented
Thanks for reviewing. Anything else?

2017-11-29 10:51 UTC, unguiculus commented
@nexeck I improved the configuration of external databases and tested it with PostgreSQL and MariaDB. Could you test it with your setup as well?

2017-11-29 13:06 UTC, unguiculus commented
/ok-to-test

2017-12-04 09:45 UTC, nexeck commented
Works for me with one replication. (Not tested with more)

2017-12-04 09:58 UTC, nexeck commented
Just had something strange with our keycloak setup.
The Statefulset started the pod and killed it after ~2 Minutes and started a new one.
This happens a few thousand times over the weekend.
But i was not able to detect the error in the keycloak logs, keycloak reported that it is up and running maybe 10-20 Seconds before the statefulset killed/restarted the pod.

2017-12-07 20:34 UTC, unguiculus commented
Have you checked kubelet logs? Maybe you have failing liveness probes or your pods get OOMKilled or something.

2017-12-07 20:39 UTC, nexeck commented
Will check this, if it happens again.

2017-12-07 20:40 UTC, nexeck commented
If keycloak is running with more then one replication, do i need to set something like sticky sessions at the ingress?
Just run with more then one replication in a strange redirect loop, which says that the login token is invalid. After removing one replication everything works fine.

2017-12-12 16:38 UTC, nexeck commented
For me, this looks fine.
We are running our keycloak instance with a single node, with the chart from this pr, since one week, without any errors, related to this chart.

2017-12-12 16:39 UTC, nexeck commented
@unguiculus Is there anything else i could test, before this can be merged?

2017-12-13 07:56 UTC, unguiculus commented
Did you set `keycloak.discovery` to `true` when running with more than one replica? Doing so will enable the replicated Infinispan cache. Sticky sessions should not be necessary. I tested it successfully accessing the replicas directly without a service or loadbalancer. You should see something like this in the logs:

```
keycloak-auth-1 keycloak 07:31:53,726 INFO  [org.infinispan.CLUSTER] (remote-thread--p8-t6) ISPN000310: Starting cluster-wide rebalance for cache authenticationSessions, topology CacheTopology{id=2, rebalanceId=2, currentCH=DefaultConsistentHash{ns=256, owners = (1)[keycloak-auth-1: 256+0]}, pendingCH=DefaultConsistentHash{ns=256, owners = (2)[keycloak-auth-1: 130+126, keycloak-auth-0: 126+130]}, unionCH=null, actualMembers=[keycloak-auth-1, keycloak-auth-0]}
```

2017-12-13 07:59 UTC, unguiculus commented
I thought about that again and removed `keycloak.discovery`. High availability is now automatically enabled if `keycloak.replicas > 1`. Could you test with that again?

2017-12-13 08:10 UTC, unguiculus commented
/retest

2017-12-13 08:50 UTC, clkao commented
This is working nicely on 1.8.4 on gke.  Thanks for the great work.

A small issue: If the postgres persistence secret is not defined, it's auto generated.  However subsequent `helm upgrade` seems to regenerate the one used by keycloak, while leaving the one used by postgres unchanged hence keycloak fails to connect to it.

2017-12-13 11:04 UTC, unguiculus commented
@clkao This is a common problem with all charts that auto-generated passwords. I'd suggest not to use auto-generated passwords for real-world installations. You may get around the issue using `helm upgrade --reuse-values`.

2017-12-17 15:15 UTC, unguiculus commented
/retest

2017-12-17 15:55 UTC, unguiculus commented
/retest

2017-12-17 16:03 UTC, unguiculus commented
/retest

2017-12-17 16:07 UTC, merged