Make value nameOverride overide name completely
helm/charts pull request #2773
Opened 2017-11-17 12:43 UTC by Tim-Smyth

The value "nameOverride" should set the complete name of the deployment/service, not just a part of it.
#2772

2017-12-05 20:39 UTC, unguiculus requested changes

2017-12-05 20:39 UTC, unguiculus commented on stable/gcloud-sqlproxy/templates/_helpers.tpl
> +{{- $name := .Values.nameOverride | default (printf "%s-%s" .Release.Name .Release.Name) -}}
`nameOverride` is meant for the `name` template. Either add a `fullnameOverride` or do something like this: https://github.com/kubernetes/charts/blob/master/incubator/oauth-proxy/templates/_helpers.tpl#L14-L18

2017-12-05 20:39 UTC, unguiculus commented
Also marking stale. Please fix your CLA.

2017-12-11 12:57 UTC, Tim-Smyth commented
@unguiculus  Thank you for your input. I added a new parameter fullnameOverride as you proposed. CLA should have been signed now by employer, will find out why its not shown yet.

2017-12-13 09:37 UTC, Tim-Smyth commented
/assign @unguiculus

2017-12-15 09:33 UTC, unguiculus approved these changes

2017-12-15 09:33 UTC, unguiculus commented
/ok-to-test

2017-12-15 10:08 UTC, unguiculus commented
/lgtm

2017-12-15 10:08 UTC, merged