Initial Commit
helm/charts pull request #279
Opened 2016-12-07 00:25 UTC by lodotek

2016-12-07 01:58 UTC, prydonius commented
@k8s-bot ok to test

2016-12-07 02:08 UTC, prydonius commented
Thanks for the submission @lodotek!

Can you remove the vendored mysql in the `charts/` directory? You should be able to use `helm dep update` to pull in the packaged mysql chart which will be ignored in git. The CI will automatically do this when packaging the chart for the repository.

Also, AFAICT this meets the [requirements](https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements) to be included in the stable repo, so you can move this to the stable folder :).

2016-12-07 02:11 UTC, prydonius commented on incubator/sapho/values.yaml
> +saphoDBpass: 7iro7Ux6Xl
looks like this isn't being used

2016-12-07 03:38 UTC, lodotek commented
I have made the requested changes, please test again. 

Thank you!

2016-12-09 03:43 UTC, aronchick commented
@prydonius I'd love to demo this soon - any chance this is ready to go?

2016-12-09 19:24 UTC, viglesiasce requested changes
The sapho pod never went to a healthy state. 

The following was found in the log:

```console
Cannot start Sapho:
- Sapho context cannot be started. Missing injection context.
Error creating bean with name 'entityManagerFactory' defined in class path resource [spring-sapho-database.xml]: Cannot resolve reference to bean 'dataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [spring-sapho-database.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Constructor threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
```

2016-12-09 19:24 UTC, viglesiasce commented on incubator/sapho/values.yaml
> +    cpu: 300m
We should bump this up by default. The initial startup is taking minutes and would likely benefit from more gas.

2016-12-10 21:10 UTC, lodotek commented on incubator/sapho/values.yaml
> +    cpu: 300m
I have upped the values a bit, let's see if that helps..

2016-12-10 21:13 UTC, lodotek reviewed
For some reason the mysql container failed to bind the PVC on every first attempt it appeared, resulting in our sapho container from trying to prematurely connect to MySQL. As a temporary solution, I have disable the persistent volume support for MySQL. 

Also tweaked the resource settings...

2016-12-12 19:56 UTC, lodotek commented
Anything else needed from me to get this PR approved?

2016-12-12 20:27 UTC, prydonius commented
@lodotek MySQL was failing for me due to `ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'` when persistence is enabled. Both MySQL and Sapho started up fine for me when I removed the `mysqlUser: root` setting from `values.yaml` and re-enabled persistence.

If you're having issues with PVCs getting bound, does your cluster support dynamic provisioning?

2016-12-12 20:28 UTC, prydonius commented on incubator/sapho/templates/NOTES.txt
> +MySQL can be accessed via port 3306 on the following DNS name from within your cluster:
I'm not sure you really need to mention how MySQL can be accessed here. If you do though, can you add a line break, as it looks like it's part of the previous statement:

```
  export SERVICE_IP=$(kubectl get svc --namespace default sapho-sapho -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo http://$SERVICE_IP:80
MySQL can be accessed via port 3306 on the following DNS name from within your cluster:
sapho-sapho.default.svc.cluster.local
```

2016-12-12 20:29 UTC, prydonius commented on incubator/sapho/values.yaml
> +  mysqlUser: root
This setting causes MySQL to crash, `root` is the default user created so with this it tries to create the root user twice. It should start up fine without this set.

2016-12-12 21:54 UTC, prydonius commented on incubator/sapho/templates/deployment.yaml
> +#        livenessProbe:
@lodotek this can be uncommented again right?

2016-12-12 21:55 UTC, lodotek reviewed
incubator/sapho/values.yaml:
Removed line 8 specifying mysqlUser
Changed Line 9, re-enabled persistence...

incubator/sapho/templates/NOTES.txt:
Removed section about MySQL

2016-12-12 21:56 UTC, lodotek commented on incubator/sapho/templates/deployment.yaml
> +#        livenessProbe:
Yes, I think you are right. I will test and push the changes.Thanks for all the help, sorry I am kind of a noob haha...

2016-12-12 21:57 UTC, prydonius commented on incubator/sapho/Chart.yaml
> +description: A Helm chart for Kubernetes
Could you change this to a short description of Sapho?

2016-12-12 21:57 UTC, prydonius commented on incubator/sapho/README.md
> +[Sapho](https://www.sapho.com/) is awesome.
Would be good to have a better description of what Sapho is here.

2016-12-12 21:58 UTC, prydonius commented on incubator/sapho/README.md
> +## Get this chart
Can you update these sections to use the Helm repo? For example, see: https://github.com/kubernetes/charts/tree/master/stable/mariadb#installing-the-chart

2016-12-12 22:01 UTC, prydonius commented
@lodotek is there any reason you want to keep this in incubator? I would move it to stable since it meets the requirements.

2016-12-12 22:26 UTC, lodotek commented
@prydonius Thank you for all you help and suggestions.  Regarding your comment about why am I keeping this in incubator. I thought this PR needs to be approved first, no?

2016-12-12 22:39 UTC, lodotek commented on incubator/sapho/README.md
> +[Sapho](https://www.sapho.com/) is awesome.
Thank you for the reminder, this has been completed! :-)

2016-12-12 22:46 UTC, prydonius commented
@lodotek no worries! As long as a chart meets the requirements listed in [CONTRIBUTING.md](https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#how-to-contribute-a-chart) it can be submitted in the stable repo. The incubator repo is for charts that don't meet these requirements (for example, using k8s alpha features), but can be improved on until they are ready to be moved into stable.

So since this already meets the requirements, it can be submitted directly to stable. Sorry for the confusion there.

2016-12-13 01:26 UTC, prydonius commented
@viglesiasce this worked for me, can you check again if you're seeing the same issue you had before?

2016-12-15 00:16 UTC, viglesiasce commented
Im still seeing the same issue as before when installing in a fresh cluster. This is likely due to the MySQL image being pulled for the first time and taking a while to come up. 

```console
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_111]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111]
        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        ... 63 common frames omitted
00:11:59.735 [localhost-startStop-1] ERROR s.s.SaphoServletContextListener -

********************************************************************************

Cannot start Sapho:
- Sapho context cannot be started. Missing injection context.
Error creating bean with name 'entityManagerFactory' defined in class path resource [spring-sapho-database.xml]: Cannot resolve reference to bean 'dataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [spring-sapho-database.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Constructor threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```

Eventually the pod was restarted due to failing its liveness check. At that point it came up fine.

@lodotek can you add something to the NOTES.txt that instructs user to be patient as the app and db come up?

2016-12-19 21:59 UTC, viglesiasce commented
@k8s-bot e2e test this

2016-12-19 21:59 UTC, viglesiasce approved these changes

2016-12-19 23:00 UTC, merged