Minio Chart
helm/charts pull request #280
Opened 2016-12-07 13:20 UTC by hunter

A basic Minio chart based off the [quickstart guide](https://docs.minio.io/docs/minio-docker-quickstart-guide)

* A single export backed by a configurable PV
* Default Access Key and Secret that can be overridden

2016-12-09 19:33 UTC, viglesiasce commented
@k8s-bot ok to test

2016-12-09 19:42 UTC, viglesiasce requested changes
Unable to start this app due to mismatched secret names (minio-user vs $release-minio-user.

2016-12-09 19:42 UTC, viglesiasce commented on stable/minio/README.md
> +By default a pre-generated Access Key and Secret will be used. If you'd like to set your own password change the AccessKey and SecretKeyt in the values.yaml.
Typo here `SecretKeyt`

2016-12-09 19:42 UTC, viglesiasce commented on stable/minio/templates/minio_secret.yaml
> +  name: minio-user
This name and the name declared in the deployment (line 34) do not line up. This causes the pod to fail to start.

2016-12-10 09:42 UTC, hunter commented on stable/minio/README.md
> +By default a pre-generated Access Key and Secret will be used. If you'd like to set your own password change the AccessKey and SecretKeyt in the values.yaml.
Fixed

2016-12-10 09:43 UTC, hunter commented on stable/minio/templates/minio_secret.yaml
> +  name: minio-user
Apologies, now fixed. Serves me right for only doing lint and dry-run testing.

2016-12-15 19:49 UTC, viglesiasce approved these changes

2016-12-15 19:50 UTC, viglesiasce commented
Thanks @hunter!! Worked like a charm this time around.

2016-12-15 21:13 UTC, merged