[stable/neo4j] add matchLabels with subset of labels for deployments
helm/charts pull request #2812
Opened 2017-11-21 14:34 UTC by Limess

This was missing from the core statefulset and read replica deployment. This can result in some weirdness when updating deployments where the release metadata changes: https://github.com/kubernetes/helm/issues/1844.

Additionally, these will _not_ be added by default in apps/v1beta2 and is [recommended as a best practise in helm](https://github.com/kubernetes/helm/blob/3ee50ccf8620e14efee7c15097a25bed7233afe9/docs/chart_best_practices/pods.md).

2017-12-07 20:48 UTC, unguiculus requested changes

2017-12-07 20:48 UTC, unguiculus commented on stable/neo4j/templates/core-statefulset.yaml
> +      app: {{ template "neo4j.name" . }}
Add the release label.

2017-12-07 20:48 UTC, unguiculus commented on stable/neo4j/templates/readreplicas-deployment.yaml
> +      app: {{ template "neo4j.name" . }}
Add the release label.

2017-12-15 10:20 UTC, unguiculus commented
cc @mneedham

2017-12-15 10:58 UTC, mneedham commented
@unguiculus ah cool didn't see this one.

@Limess Chart.yaml needs to be bumped to 0.4.1. There was another commit that took it from 0.3.1 to 0.4.0

2017-12-19 10:37 UTC, Limess commented
@mneedham done, rebased and updated the version to 0.4.1.

2017-12-22 16:15 UTC, unguiculus approved these changes

2017-12-22 16:15 UTC, unguiculus commented
/ok-to-test

2018-01-09 09:09 UTC, mneedham commented
@Limess selectors are now merged in via this commit - https://github.com/kubernetes/charts/commit/4c2f507494905fb020392d03b18c52dae367c4ee

2018-01-10 09:03 UTC, mneedham commented
@unguiculus can we close this one?

2018-01-10 09:24 UTC, Limess commented
Thanks @mneedham, closed.

2018-01-10 09:24 UTC, closed without merging