[incubator/cassandra] Add image pull secrets to statefulset template
helm/charts pull request #2832
Opened 2017-11-22 11:55 UTC by alebabai

* update statefulset template
* add new parameter to README
* bump chart version to 0.1.7

2017-11-22 14:10 UTC, alebabai commented
/cc @KongZ

2017-11-22 14:44 UTC, KongZ commented
cc @mattfarina @prydonius

2017-11-22 15:35 UTC, mattfarina requested changes
On the whole I like the idea of having this. I should discuss it with the other maintainers. Just one nit.

2017-11-22 15:35 UTC, mattfarina commented on incubator/cassandra/templates/cassandra-statefulset.yaml
> +        - name: {{ .Values.image.pullSecrets }}
`image.pullSecrets` should be in the `values.yaml` file, commented out, and documented.

2017-11-23 08:32 UTC, alebabai commented on incubator/cassandra/templates/cassandra-statefulset.yaml
> +        - name: {{ .Values.image.pullSecrets }}
done

2017-12-08 13:38 UTC, unguiculus commented
/ok-to-test

2017-12-09 11:01 UTC, unguiculus commented
/retest

2017-12-09 12:24 UTC, unguiculus commented
/lgtm

2017-12-09 12:24 UTC, merged