Upgrading zookeeper chart k8szk version
helm/charts pull request #2835
Opened 2017-11-22 19:29 UTC by brosander

v3 of gcr.io/google_samples/k8szk has significantly fewer vulnerabilities than v2.  Below are images from [clair scans of the two images.](https://github.com/coreos/clair)

This commit defaults to the newer image while adding the ability to specify another image and tag.
v2:
![image](https://user-images.githubusercontent.com/596137/33146230-5c9ddb08-cf91-11e7-9d21-2cb0d85d0fac.png)

v3:
![image](https://user-images.githubusercontent.com/596137/33146248-6aad1d44-cf91-11e7-883b-cc3791f02e04.png)

2017-12-06 15:21 UTC, timstoop approved these changes
Version is updated and the upgraded image seems indeed to be better. Even if not for the vulnerabilities, a newer version of this image is a good idea anyway.

2017-12-06 15:42 UTC, unguiculus requested changes

2017-12-06 15:42 UTC, unguiculus commented on incubator/zookeeper/values.yaml
> +image: gcr.io/google_samples/k8szk
Could you nest them:

```yaml
image:
  repository:
  tag:
  pullPolicy:
```

2017-12-06 15:46 UTC, brosander commented on incubator/zookeeper/values.yaml
> +image: gcr.io/google_samples/k8szk
Will do

2017-12-15 16:33 UTC, unguiculus commented
Marking stale. Please update within one week.

2018-01-06 10:01 UTC, unguiculus commented
Closing as stale. Feel free to reopen if/when you decide to pick this up again.

2018-01-06 10:01 UTC, closed without merging