[stable/nginx-ingress] Add flag for daemonset controllers so that hostPort can optionally be used
helm/charts pull request #2854
Opened 2017-11-24 15:14 UTC by jmatsushita

Reviving closed stale PR #1906

2017-11-24 15:47 UTC, jmatsushita commented
/joke

2017-11-24 15:50 UTC, jmatsushita commented
@mgoodness Hi there, I've addressed your comments on @digivava PR #2854 Let me know if there's anything else.

2017-12-15 00:56 UTC, viglesiasce commented
@jmatsushita can you make the port configurable and do something like:

```yaml
hostPort:
  enabled: false
  httpPort: 80
  httpsPort: 443
  statsPort: 18080
```

2018-05-11 07:34 UTC, unguiculus requested changes
Please update readme.

2018-05-11 07:34 UTC, unguiculus commented on stable/nginx-ingress/templates/controller-daemonset.yaml
> +              {{- if .Values.controller.enablehostPort }}
enablehostPort -> enableHostPort

2018-05-11 07:34 UTC, unguiculus commented on stable/nginx-ingress/templates/controller-daemonset.yaml
> +              {{- if .Values.controller.enablehostPort }}
enablehostPort -> enableHostPort

2018-05-11 07:34 UTC, unguiculus commented on stable/nginx-ingress/Chart.yaml
> +version: 0.8.17
Please bump minor version, since it's a new feature.

2018-05-11 07:36 UTC, unguiculus commented
Also, consider @viglesiasce's comment. Otherwise, please close the PR if you're not interesting in it any more.

2018-06-10 08:08 UTC, closed without merging