add kube-registry-proxy chart to incubator
helm/charts pull request #286
Opened 2016-12-08 20:55 UTC by bacongobbler

closes #285

2016-12-15 00:28 UTC, viglesiasce commented
@k8s-bot ok to test

2016-12-15 00:32 UTC, viglesiasce commented
Hey @bacongobbler!

Looks like this is a malformed chart. Its missing the _helpers file that provides some of the templates you are using. Its easiest to just use `helm create` then dump your templates into the templates folder. Also dont forget to add a NOTES.txt file in your templates folder that instructs user on how to get started.

2016-12-15 18:46 UTC, bacongobbler commented
thanks @viglesiasce. I have applied those changes :)

2016-12-15 22:38 UTC, viglesiasce requested changes
Please add a NOTES.txt file explaining how to use this chart. Also please fix tag version as the chart does not currently install properly.

Can you also move this to the stable folder?

2016-12-15 22:38 UTC, viglesiasce commented on incubator/kube-registry-proxy/values.yaml
> +  tag: 0.4
This tag was not found for the repo:
```console
  52s   12s     3       {kubelet gke-junkyard-default-pool-0ca72bdc-botz}                                         Warning  FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "kube-registry-proxy" with ErrImagePull: "Tag 0.4 not found in repository gcr.io/google_containers/kube-registry-proxy"
```

2016-12-15 23:18 UTC, bacongobbler commented on incubator/kube-registry-proxy/values.yaml
> +  tag: 0.4
Yeah, someone from the k8s maintainer team has got to push the new release (pinging @roberthbailey from https://github.com/kubernetes/kubernetes/pull/35797)

2016-12-15 23:26 UTC, bacongobbler commented on incubator/kube-registry-proxy/values.yaml
> +  tag: 0.4
Filed https://github.com/kubernetes/kubernetes/issues/38843 for posterity

2017-01-23 18:14 UTC, bacongobbler commented on incubator/kube-registry-proxy/values.yaml
> +  tag: 0.4
This image has been finally pushed to gcr.io:

```
><> d pull gcr.io/google_containers/kube-registry-proxy:0.4
0.4: Pulling from google_containers/kube-registry-proxy
5040bd298390: Pull complete 
d7a91cdb22f0: Pull complete 
9cac4850e5df: Pull complete 
decd9736c768: Pull complete 
2bb4bfc281bb: Pull complete 
Digest: sha256:1040f25a5273de0d72c54865a8efd47e3292de9fb8e5353e3fa76736b854f2da
Status: Downloaded newer image for gcr.io/google_containers/kube-registry-proxy:0.4
```

2017-01-23 18:18 UTC, bacongobbler commented
thanks for the review @viglesiasce. I'll get back to addressing your comments some time early this week now that kube-registry-proxy:0.4 has been pushed out.

2017-02-03 19:26 UTC, viglesiasce approved these changes

2017-02-03 20:17 UTC, lachie83 commented on incubator/kube-registry-proxy/templates/daemon.yaml
> +        - containerPort: 80
Should the port be configurable?

2017-02-03 20:27 UTC, bacongobbler commented on incubator/kube-registry-proxy/templates/daemon.yaml
> +        - containerPort: 80
You'd have to refactor the underlying image to change it, so I don't think there's any use in making it configurable.

2017-02-03 20:30 UTC, lachie83 commented on incubator/kube-registry-proxy/templates/daemon.yaml
> +        - containerPort: 80
No worries.

2017-02-03 20:31 UTC, lachie83 commented
Should we specific a default host. The UX if you don't is the container crashes because `REGISTRY_HOST` is not defined.

2017-02-03 23:27 UTC, lachie83 commented
Set default registry.host to "gcr.io"

2017-02-03 23:27 UTC, lachie83 commented
LGTM

2017-02-07 22:38 UTC, merged