Fix README to reflect latest cloudflare parameter changes
helm/charts pull request #2875
Opened 2017-11-28 14:42 UTC by thecodeassassin

* Removed redundant cloudflare.apiKey from the configuration table
* fixed change to camelCase format recently introduced

2017-12-01 09:39 UTC, timstoop approved these changes
Small change of what was already present in the actual deployment.

2017-12-06 20:21 UTC, timstoop requested changes
As charts are immutable, every change needs to bump the version in Chart.yaml.

2017-12-15 15:49 UTC, unguiculus requested changes

2017-12-15 15:49 UTC, unguiculus commented on stable/external-dns/README.md
> +| `cloudflare.email`        | `CF_API_EMAIL` to set in the environment (optional).                                                                       | `""`
This is there `cloudflare.email`.

2018-02-27 17:18 UTC, viglesiasce commented
Already fixed in master

2018-02-27 17:18 UTC, closed without merging