Add Kafka Manager chart
helm/charts pull request #2917
Opened 2017-12-03 21:49 UTC by oleh-ozimok

2018-01-10 09:50 UTC, oleh-ozimok commented
/assign @lachie83

2018-01-14 15:51 UTC, unguiculus requested changes
Thanks for the PR. I have just a few comments.

2018-01-14 15:51 UTC, unguiculus commented on stable/kafka-manager/values.yaml
> +  tag: alpine
Can you use a fix release version?

2018-01-14 15:51 UTC, unguiculus commented on stable/kafka-manager/README.md
> +- Kubernetes 1.4+ with Beta APIs enabled
1.8+

2018-01-14 15:51 UTC, unguiculus commented on stable/kafka-manager/templates/deployment.yaml
> +apiVersion: apps/v1beta1
We offically support the current and previous minor versions of Kubernetes. Currently that would be 1.8+. You should use `apps/v1beta2`.

2018-03-02 17:11 UTC, jdumars commented
/ok-to-test

2018-03-26 18:39 UTC, tedmiston commented
It looks like this PR is a bit stale.  I've pulled in the branch, and made the changes specified in comments and am able to run it myself locally.  Would it be worthwhile to open a fresh PR to push this over the finish line?

I looked into the above failed test `pull-charts-e2e`, but am unclear on how to resolve the error:

```
I0302 18:07:44.237] [info] o.a.z.ZooKeeper - Client environment:os.arch=amd64
I0302 18:07:44.238] [info] o.a.z.ZooKeeper - Client environment:os.version=4.4.86+
I0302 18:07:44.238] [info] o.a.z.ZooKeeper - Client environment:user.name=root
I0302 18:07:44.238] [info] o.a.z.ZooKeeper - Client environment:user.home=/root
I0302 18:07:44.238] [info] o.a.z.ZooKeeper - Client environment:user.dir=/kafka-manager-1.3.1.6
I0302 18:07:44.239] [info] o.a.z.ZooKeeper - Initiating client connection, connectString= sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@20fd4379
I0302 18:07:44.239] [info] o.a.z.ClientCnxn - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
I0302 18:07:44.239] [warn] o.a.z.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
I0302 18:07:44.240] java.net.ConnectException: Connection refused
I0302 18:07:44.240] 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_92]
I0302 18:07:44.240] 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_92]
I0302 18:07:44.240] 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[org.apache.zookeeper.zookeeper-3.4.6.jar:3.4.6-1569965]
I0302 18:07:44.241] 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[org.apache.zookeeper.zookeeper-3.4.6.jar:3.4.6-1569965]
I0302 18:07:44.241] [info] k.m.a.KafkaManagerActor - zk=
I0302 18:07:44.241] [info] k.m.a.KafkaManagerActor - baseZkPath=/kafka-manager
I0302 18:07:44.241] [info] play.api.Play - Application started (Prod)
I0302 18:07:44.242] [info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
```

Anyone have advice for this?  Is it possibly something specific to the CI environment?

2018-05-02 17:03 UTC, oleh-ozimok commented
Was busy, sorry. @tedmiston kafka-manager need zookeper server(s) for start. I can add as zookeer as  dependency, but I do not think that this is a good idea.

2018-05-02 17:55 UTC, tedmiston commented
Ah I must have botched the config passing them through.  I'll take another go at this today.  Thank you.

2018-06-03 00:06 UTC, sneko commented
Any news about this chart?

2018-09-18 00:38 UTC, tedmiston commented
I’m no longer using Kafka / Kafka Manager personally but please tag me if there’s anything I can do to help be useful here.

2018-10-31 19:13 UTC, unguiculus commented
Closing in favor of #8715

2018-10-31 19:13 UTC, closed without merging