Add rbac to concourse worker
helm/charts pull request #2922
Opened 2017-12-04 08:52 UTC by nexeck

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

2017-12-06 21:16 UTC, william-tran commented
@nexeck I have another PR #2911 that would also benefit from RBAC, but concourse-web needs a serviceAccount separate from the workers, as it (and not the workers), will need access to secrets in namespaces used solely for concourse. Would it be possible to include concourse-web as well in your PR?

2017-12-06 21:25 UTC, nexeck commented
Sure, is it enough to add this roles to the web serviceaccount?

```
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
```

2017-12-06 21:30 UTC, william-tran commented
Thanks @nexeck, just `get` is required. Here's the lookup scheme for background: https://github.com/autonomic-ai/charts/blob/8d038734d8a7f4421356ae5f324ca3f5b6d382dd/stable/concourse/README.md#kubernetes-secrets

2017-12-06 21:32 UTC, nexeck commented
So the web worker needs this as a clusterrole to access other namespaces?

2017-12-07 01:35 UTC, william-tran commented
Yes, the set of namespaces could default to just `[credentialManager.kubernetes.namespacePrefix]main` as main is the team that you start with and you can't control the teams that get created from the chart.

2017-12-07 08:23 UTC, nexeck commented
I would suggest something like this:
```
rbac:
  create: false

  ## Ignored if rbac.create is true
  ##
  serviceAccountName: default

  teams:
  - main
```

Maybe the teams would better fit something else in the configuration?

2017-12-08 02:09 UTC, william-tran commented
So the intent is that whenever a new team is created, that a new entry is added under rbac.teams (or a more appropriate key)?

2017-12-08 07:57 UTC, nexeck commented
Yes, that is the intention, otherwise the web SA needs to be able to read all secrets in all namespaces.
Do you have other ideas, how we could solve this?

2017-12-08 09:03 UTC, william-tran commented
No, I think its a totally reasonable approach to enumerate the teams. I
need to give a bit more thought to what key that list should fall under.

On Dec 7, 2017 23:57, "Marcel Beck" <notifications@github.com> wrote:

> Yes, that is the intention, otherwise the web SA needs to be able to read
> all secrets in all namespaces.
> Do you have other ideas, how we could solve this?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/charts/pull/2922#issuecomment-350198165>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABCMGWqPpgsqG8JmmDkK-ej3-r07E2Maks5s-OvZgaJpZM4Q0Tkm>
> .
>

2017-12-09 18:21 UTC, william-tran commented
@nexeck I've added a key in this commit https://github.com/kubernetes/charts/pull/2911/commits/4b36ab4fbd4e28a6222a43ec99f01fec924c2a31

#2911 now depends on RBAC, so let me know when you're done with this PR and I'll add those commits, retaining authorship of course, to #2911.

2017-12-09 20:42 UTC, nexeck commented
@william-tran Can you take a look at 2a53d44 ?
Haven't tested this against your branch.

2017-12-11 19:16 UTC, william-tran commented
@nexeck I found a few errors, corrected in this commit https://github.com/autonomic-ai/charts/commit/bd93bd6891e124a523e0124e597634193325c6be I'll let you know once I get this tested with `rbac.create: true`

2017-12-12 16:14 UTC, william-tran commented
@nexeck Since there are issues that need to be fixed in concourse to support #2911, lets consider this PR first. What are the motivations for adding RBAC to the workers only?

2017-12-12 16:31 UTC, nexeck commented
@william-tran the worker needs it to be able to run with privileged: true. Without this the worker are not able to run any jobs.
I can add it for the web, too. But at the moment i do not know if the web needs any role. In our current setup it is working finde, without giving the web any special rights.

But for completion, i would add it for the worker, too. Do you know, if i need to give it any role (Does the default SA have any rights/roles?)?
In our current setup it is running with the default SA.

2017-12-13 01:33 UTC, william-tran commented
@nexeck I would just provide the workers with the RBAC to have it run with `privileged: true` ad leave the web one alone, once I get the k8s secrets stuff working, tested and stable I'll add RBAC for concourse-web.

2017-12-13 05:16 UTC, nexeck commented
@william-tran  i have removed the web rbac commit

/assign @viglesiasce

2017-12-13 21:30 UTC, viglesiasce requested changes
Only one nit on the value name

2017-12-13 21:30 UTC, viglesiasce commented on stable/concourse/values.yaml
> +  create: false
Most other charts have this as `enabled`. Can you make the change?

2017-12-14 09:01 UTC, nexeck commented
@viglesiasce i have renamed the key from create to enabled

2017-12-14 23:40 UTC, viglesiasce commented
/retest

2017-12-14 23:50 UTC, viglesiasce approved these changes

2017-12-14 23:50 UTC, viglesiasce commented
/lgtm

2017-12-15 09:21 UTC, unguiculus commented
@viglesiasce Actually, our best practices suggest to use `rbac.create`. There's been quite a bunch of PRs now that follow this pattern. See https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md. 

@nexeck Care to open another PR to fix this?

2017-12-15 10:51 UTC, nexeck commented
@unguiculus Sure, if this PR is merged, i will open a new one, with rbac.create.

2017-12-15 11:04 UTC, prydonius commented
@mattfarina any idea why this one isn't getting auto-merged? Does it need `/ok-to-test`?

2017-12-15 11:04 UTC, prydonius commented
/ok-to-test

2017-12-15 11:16 UTC, unguiculus commented
@nexeck I thought this had been merged already. So you can fix it directly in this PR.

2017-12-15 11:20 UTC, nexeck commented
@unguiculus i have removed the last commit which switched from rbac.create to rbac.enabled

2017-12-15 11:22 UTC, nexeck commented
rbac.create is per default now true, like suggested in: https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

2017-12-15 11:26 UTC, nexeck commented
Doesn't the check runs with k8s 1.8?

2017-12-15 11:33 UTC, unguiculus commented
We support compatibility with the current and previous minor version, which would be 1.7+. The chart has to work on 1.7.

2017-12-15 11:49 UTC, nexeck commented
@unguiculus i have added a value for the rbac version, the default is now v1beta1

2017-12-15 12:16 UTC, unguiculus commented
/retest

2017-12-18 15:51 UTC, nexeck commented
@unguiculus is anything else missing here?

2017-12-18 18:21 UTC, unguiculus commented
/lgtm

2017-12-18 18:29 UTC, merged