stable/concourse: trunc of service name causes failures when the helm generated name is too long
helm/charts pull request #2928
Opened 2017-12-04 19:35 UTC by knuckolls

Attempting to get this chart online I had to fiddle with why the web process wasn't connecting to postgresql correctly. Turns out that the truncate to 24 chars on the concourse.postgresql.fullname was incorrectly truncating the service name too much and dns wouldn't properly resolve.

Putting this out here in case someone else has encountered this problem.

2017-12-04 19:38 UTC, knuckolls commented
I signed a CLA just now, fyi.

2017-12-06 18:13 UTC, timstoop requested changes
Charts are immutable, so every change requires a version bump in Chart.yaml. Can you add that please?

2017-12-15 16:58 UTC, unguiculus commented
Please check your CLA. You may have committed with the wrong e-mail address.

2018-02-27 17:20 UTC, viglesiasce commented
@william-tran do we still need this?

2018-02-27 19:37 UTC, william-tran commented
Addressed

2018-02-27 19:39 UTC, william-tran commented
@viglesiasce @knuckolls This was addressed in #3254

2018-02-27 19:39 UTC, william-tran commented
/close

2018-02-27 19:39 UTC, closed without merging