Adding values for liveness & readiness probe thresholds
helm/charts pull request #2957
Opened 2017-12-06 22:21 UTC by adamcharnock

This is an addition to the existing ``postgresql`` chart.

I have added the following values:

```
probes.liveness.initialDelay
probes.liveness.timeoutSeconds
probes.liveness.failureThreshold
probes.readiness.initialDelay
probes.readiness.timeoutSeconds
probes.readiness.failureThreshold
```

Each use the defaults already present.

## Reason

I'm adding these because the default ``probes.liveness.initialDelay`` value of 60 seconds was – for my cluster – not long enough for the initial database setup to take place. The pod would therefore get killed part way though setup, and before any login was created. The pod would then restart, believe the setup had been completed, and leave the database with no way to login.

I included the rest of the options for completeness.

2017-12-07 23:18 UTC, timstoop requested changes
As charts are immutable, you need to bump the version in Chart.yaml as well. The rest looks fine to me.

2017-12-08 01:18 UTC, adamcharnock commented
Thanks @timstoop, I've increased the chart version from `0.8.4` to `0.8.5`

2017-12-14 16:13 UTC, adamcharnock commented
I realised that the email address I gave to the Linux Foundation did not match my github email. I've fixed this now, hopefully that'll allow this to move forward soon.

2017-12-22 17:05 UTC, unguiculus requested changes

2017-12-22 17:05 UTC, unguiculus commented on stable/postgresql/templates/deployment.yaml
> +          initialDelaySeconds: {{ default "60" .Values.probes.liveness.initialDelay | quote }}
Remove the `default` function calls. They are redundant.

2018-01-06 13:02 UTC, unguiculus commented
Ping for CLA check.

2018-01-08 10:56 UTC, adamcharnock commented
Ping for CLA check

2018-01-11 18:50 UTC, unguiculus commented
/ok-to-test

2018-01-11 18:50 UTC, unguiculus approved these changes

2018-05-17 19:36 UTC, unguiculus commented
@adamcharnock Are you still interested in the PR? If so, please merge in the current master, so we can proceed. Otherwise, please close it. Thanks.

2018-05-18 08:44 UTC, adamcharnock commented
@unguiculus Done

2018-06-17 09:05 UTC, adamcharnock commented
@unguiculus Merged again. I've also bumped the version number again.

If we cannot get this merged this time around then I'm probably going to back away from this PR, the level of procedural faff is starting to feel prohibitive for me.

2018-06-17 12:19 UTC, unguiculus commented
/lgtm

2018-06-17 12:21 UTC, merged

2018-06-17 15:04 UTC, adamcharnock commented
Thank you @unguiculus!

2018-06-17 20:15 UTC, ib-steffen commented
seems like this change broke installation:

```
helm install --name postgres stable/postgresql

Error: release postgres failed: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment: Spec: v1beta1.DeploymentSpec: Template: v1.PodTemplateSpec: Spec: v1.PodSpec: Containers: []v1.Container: v1.Container: LivenessProbe: v1.Probe: FailureThreshold: readUint32: unexpected character: �, parsing 966 ...reshold":"... at {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"labels":{"app":"postgresql","chart":"postgresql-0.14.1","heritage":"Tiller","release":"postgres"},"name":"postgres-postgresql","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"postgresql","release":"postgres"}},"template":{"metadata":{"labels":{"app":"postgresql","release":"postgres"}},"spec":{"containers":[{"args":null,"env":[{"name":"POSTGRES_USER","value":"postgres"},{"name":"PGUSER","value":"postgres"},{"name":"POSTGRES_DB","value":""},{"name":"POSTGRES_INITDB_ARGS","value":""},{"name":"PGDATA","value":"/var/lib/postgresql/data/pgdata"},{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"postgres-password","name":"postgres-postgresql"}}},{"name":"POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"postgres:9.6.2","imagePullPolicy":"","livenessProbe":{"exec":{"command":["sh","-c","exec pg_isready --host $POD_IP"]},"failureThreshold":"6","initialDelaySeconds":"60","timeoutSeconds":"5"},"name":"postgres-postgresql","ports":[{"containerPort":5432,"name":"postgresql"}],"readinessProbe":{"exec":{"command":["sh","-c","exec pg_isready --host $POD_IP"]},"initialDelaySeconds":"5","periodSeconds":null,"timeoutSeconds":"3"},"resources":{"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/var/lib/postgresql/data/pgdata","name":"data","subPath":"postgresql-db"}]}],"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"postgres-postgresql"}}]}}}}

```

2018-06-18 10:27 UTC, desaintmartin commented
Those values don't need to be quoted!