[external-dns] Fix naming in condition for secret
helm/charts pull request #2998
Opened 2017-12-12 07:11 UTC by joerx

Fix for #2996

2017-12-12 07:25 UTC, joerx commented
bump

2017-12-12 09:17 UTC, timstoop requested changes
Charts are immutable so every change requires a version bump in Chart.yaml.

2017-12-12 14:40 UTC, mattfarina commented
/ok-to-test

2017-12-13 03:32 UTC, joerx commented
/assign @mattfarina

2017-12-15 16:04 UTC, unguiculus commented
/lgtm

2017-12-15 16:04 UTC, merged