[stable/rabbitmq-ha] Add RabbitMQ HA chart
helm/charts pull request #3005
Opened 2017-12-12 13:21 UTC by etiennetremel

Add RabbitMQ Hight Available chart. It rely on Statefulsets, use the official RabbitMQ image and the official Kubernetes node discovery plugin.

This PR can only be tested after the official RabbitMQ 3.7 image get merged to the official Docker repository, see https://github.com/docker-library/official-images/pull/3795. Hopefully in the coming days.

2017-12-13 09:18 UTC, etiennetremel commented
RabbitMQ 3.7 was released to few minutes ago to DockerHub.
This PR is now ready to be reviewed.

/assign @linki
/approve

2017-12-15 10:54 UTC, unguiculus requested changes

2017-12-15 10:54 UTC, unguiculus commented on stable/rabbitmq-ha/Chart.yaml
> +- name: Etienne Tremel
Use github username

2017-12-15 10:54 UTC, unguiculus commented on stable/rabbitmq-ha/templates/configmap.yaml
> +    app: {{ template "rabbitmq-ha.name" . }}
`app` label should be `{{ template "rabbitmq-ha.name" . }}`. Apply everywhere.

2017-12-15 12:19 UTC, unguiculus requested changes

2017-12-15 12:19 UTC, unguiculus commented on stable/rabbitmq-ha/values.yaml
> +serviceAccountName: default
Nest this under `rbac`.

2017-12-15 14:14 UTC, unguiculus approved these changes

2017-12-15 14:14 UTC, unguiculus commented
/ok-to-test

2017-12-18 19:01 UTC, unguiculus commented
/lgtm

2017-12-18 19:25 UTC, etiennetremel commented
/retest

2017-12-19 05:50 UTC, unguiculus commented
/retest

2017-12-19 05:53 UTC, merged