Better resource management for Artifactory
helm/charts pull request #3021
Opened 2017-12-13 08:25 UTC by eldada

* Update Artifactory version
* Add resources requests and limits to all pods
* Ability to set whitelist on Nginx LoadBalancer service
* Support setting a custom artifactory service name (that will also be set in nginx config)
* Add new parameters to README
* Fix artifactory replicas reference. Hardcode database replicas to 1
* Use resource memory requests and limits in Artifactory java options
* Add readinessProbe to Artifactory
* Add readme on creating a Kubernetes Docker registry secret and passing it to helm

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

2017-12-14 16:45 UTC, mattfarina commented
/ok-to-test

2017-12-15 10:51 UTC, unguiculus requested changes

2017-12-15 10:51 UTC, unguiculus commented on stable/artifactory/values.yaml
> +  resources:
We recommend not to specify defaults for resources. This should be a conscious choice of the user. Plus, it makes it easier to test charts on small systems, such as Minikube. Do it like so:

```yaml
resources: {}
  # requests:
    # memory: "512Mi"
    # cpu: "100m"
  # limits:
    # memory: "1Gi"
    # cpu: "500m"
```

2017-12-17 07:48 UTC, eldada commented
@unguiculus - I added the requested changes.

2017-12-18 18:23 UTC, unguiculus requested changes

2017-12-18 18:23 UTC, unguiculus commented on stable/artifactory/README.md
> +| `nginx.resources.limits.cpu`      | Nginx cpu limit               | `500m`    |
Defaults are not correct.

2017-12-18 18:36 UTC, eldada commented
@unguiculus - done! Default values corrected.

2017-12-18 19:56 UTC, unguiculus approved these changes

2017-12-18 19:56 UTC, unguiculus commented
/lgtm

2017-12-18 20:07 UTC, merged