adds orangehrm chart
helm/charts pull request #310
Opened 2016-12-16 08:27 UTC by sameersbn

2016-12-21 18:56 UTC, viglesiasce commented
@k8s-bot ok to test

2017-01-04 22:20 UTC, viglesiasce commented
@k8s-bot ok to test

2017-01-04 22:42 UTC, viglesiasce requested changes

2017-01-04 22:42 UTC, viglesiasce commented on stable/orangehrm/requirements.yaml
> +  version: 0.5.4
Bump this to 0.5.6 which has the fix for imagePullPolicy on Kubernetes 1.5.1

2017-01-05 07:05 UTC, sameersbn commented
done

2017-01-17 18:44 UTC, viglesiasce approved these changes

2017-01-17 18:47 UTC, viglesiasce commented
@k8s-bot e2e test this

2017-01-18 22:57 UTC, merged