grafana - allow for custom clusterIP to support headless services
helm/charts pull request #3101
Opened 2017-12-19 16:32 UTC by rsmitty

This PR adds a new field to the grafana values called clusterIP. When the specified service type is ClusterIP, specifying this value with allow for custom clusterIP values to be used. This allows for support of things like headless services with the grafana svc definition.

2017-12-22 16:11 UTC, rsmitty commented
/assign @linki

2018-01-09 17:12 UTC, rsmitty commented
/assign

2018-01-09 17:13 UTC, rsmitty commented
Hi @linki, is there anything else I need to do to get a go-ahead on testing this PR?

2018-01-14 15:40 UTC, unguiculus requested changes
Thanks for the PR. Just one comment.

2018-01-14 15:40 UTC, unguiculus commented on stable/grafana/templates/svc.yaml
> +{{- if contains "ClusterIP" .Values.server.service.type }}
Why `contains`? I think you should use `eq` instead.

2018-01-14 20:12 UTC, rsmitty commented
Hi @unguiculus. Thanks for taking a look! I agree that using `eq` makes more sense. However, I followed the same format as the other service type checks in the same file. `if contains "NodePort"` and `if contains "LoadBalancer"` are both specified. I'm happy to change mine to `eq` though if you think that's best. Let me know what you'd like to see!

2018-01-27 12:57 UTC, unguiculus commented
Consistency is always good. While you're at it, would you mind changing the other occurences to `eq` as well?

2018-01-27 15:21 UTC, rsmitty commented
Alrighty, @unguiculus, updated with that change as well as another version bump in the Chart.yml file.

2018-01-27 16:06 UTC, unguiculus commented
/ok-to-test

2018-01-27 16:06 UTC, unguiculus approved these changes

2018-01-27 16:07 UTC, unguiculus commented
cc @zanhsieh

2018-01-28 08:56 UTC, zanhsieh commented
LGTM

2018-01-28 09:02 UTC, unguiculus commented
/lgtm

2018-01-29 15:58 UTC, merged