[WIP] Add filebeat Chart
helm/charts pull request #3108
Opened 2017-12-19 21:48 UTC by rendhalver

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

2018-02-14 13:39 UTC, mishak87 commented
Filebeat now supports docker and kubernetes autodiscovery https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html#_kubernetes

2018-02-18 10:41 UTC, unguiculus requested changes
Please apply our RBAC best practices.
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

2018-02-18 10:41 UTC, unguiculus commented on incubator/filebeat/templates/_helpers.tpl
> +{{- define "filebeat.fullname" -}}
Please update the template to use that created by `helm create` and Helm 2.8+.

2018-02-18 10:41 UTC, unguiculus commented on incubator/filebeat/templates/daemonset.yaml
> +apiVersion: extensions/v1beta1
`apps/v1beta2`

2018-02-18 10:41 UTC, unguiculus commented on incubator/filebeat/templates/daemonset.yaml
> +      labels:
Add `app` and `release` labels.

2018-02-19 13:10 UTC, rendhalver commented
Thanks @unguiculus I will get those updated soon.

2018-03-02 17:09 UTC, jdumars commented
/ok-to-test

2018-03-09 18:37 UTC, sstarcher commented
@rendhalver do you think you will have some time to finish this chart up?  If not I can likely take over.

2018-03-12 17:30 UTC, sstarcher requested changes
any reason this is in incubator and not stable?  Incubator is for using alpha features of Kubernetes.

2018-03-12 17:31 UTC, sstarcher commented on incubator/filebeat/templates/clusterrolebinding.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
This should probably be wrapped by rbac.enabled: true

2018-03-12 17:53 UTC, sstarcher commented on incubator/filebeat/templates/filebeat-cm.yaml
> +  filebeat.yml: |-
this configuration is yaml and to support all of the endpoints it would be better to just allow the user to inject yaml.

2018-03-15 12:22 UTC, rendhalver commented
@sstarcher Sorry I missed your comments till now. I have been way too busy.
Thanks for continuing this in your new PR.

2018-03-15 12:36 UTC, sstarcher commented
@rendhalver does it make sense to close this out if you are good with #4133

2018-03-15 13:16 UTC, rendhalver commented
That does make sense.
I will close this out.

2018-03-15 13:16 UTC, closed without merging