odoo chart
helm/charts pull request #313
Opened 2016-12-16 17:28 UTC by sameersbn

2016-12-21 18:56 UTC, viglesiasce commented
@k8s-bot ok to test

2017-01-04 22:06 UTC, viglesiasce commented
@k8s-bot ok to test

2017-01-04 22:15 UTC, viglesiasce requested changes

2017-01-04 22:15 UTC, viglesiasce commented on stable/odoo/requirements.yaml
> +  version: 0.2.1
Change this to point to 0.3.0 which has the fix for imagePullPolicy on the init container.

2017-01-05 07:02 UTC, sameersbn commented
Completed the suggested changes, however I would like this chart to be merged after #318

2017-01-19 21:36 UTC, merged