Convert registry to k8s.gcr.io
helm/charts pull request #3141
Opened 2017-12-22 18:00 UTC by thockin

This PR was auto-generated.  Please apply human expertise to review for correctness.

Followup to https://github.com/kubernetes/kubernetes/pull/54174 and https://github.com/kubernetes/kubernetes/pull/57824

xref https://github.com/kubernetes/release/issues/281

2017-12-22 18:06 UTC, thockin commented
I am unfamiliar with the rules for version increments - does this really warrant that?

2017-12-27 15:01 UTC, mattfarina commented
@thockin Charts are immutable. We want people to be able to check for things like a changed hash at a version. So, the version matters.

I'll take this one on and carry it home. Might take a couple weeks given the holidays but poke me if I don't get it done.

2017-12-27 18:46 UTC, mattfarina commented
@thockin unless there's an objection, we're going to break this up into 12 separate pull requests. One for each chart so we can make sure all tests pass and the charts are immutable. We'll take care of it.

2017-12-27 18:46 UTC, mattfarina commented
/hold

2018-01-17 19:39 UTC, dekkagaijin requested changes

2018-01-17 19:39 UTC, dekkagaijin commented on stable/mongodb-replicaset/init/Makefile
> +PREFIX = k8s.gcr.io/mongodb-install
`PREFIX = staging-k8s.gcr.io/mongodb-install`

2018-01-17 21:43 UTC, thockin commented
Since you're merging these piecemeal, I'll repurpose this to the next tweak.  Pushes go to one place, pulls from another.

2018-01-17 21:43 UTC, thockin commented
@mattfarina

2018-01-18 16:28 UTC, mattfarina commented
/retest

2018-01-24 16:50 UTC, mattfarina commented
@foxish Any idea why these tests are failing on the mongodb-replicast chart?

2018-01-30 17:23 UTC, mattfarina commented
/retest

2018-01-30 17:31 UTC, viglesiasce commented
/assign

2018-01-30 23:20 UTC, viglesiasce commented
/retest

2018-01-30 23:30 UTC, viglesiasce commented
This test appears to be failing be cause our CI is not waiting until the RS is completely deployed, in the latest result only 2 of 3 replicas was up/running. Testing manually showed that this does indeed work.

2018-01-31 21:27 UTC, mattfarina commented
/retest

2018-01-31 21:46 UTC, mattfarina commented
@viglesiasce @unguiculus I think the issue is in how we test for statefulsets. When the first replica comes online all the pods are ready so it proceeds with the tests. If there are multiple replicas those start to come online but aren't ready. Testing shouldn't proceed until all the replicas are up. This is a bug in CI, I think.

2018-02-01 14:32 UTC, mattfarina commented
/retest

A change to CI was merged that, I think, fixes the issue.

2018-02-01 14:46 UTC, mattfarina commented
/lgtm

2018-02-01 15:30 UTC, mattfarina commented
/hold cancel

2018-02-01 15:32 UTC, merged

2018-04-06 15:37 UTC, thockin commented
@mattfarina I see a handful of new uses of the old names.  Do youw ant me to send a PR or can you handle it?