[stable/kong] Add a chart for Kong
helm/charts pull request #3150
Opened 2017-12-26 07:14 UTC by shashiranjan84

- Chart deploys Kong and its backing datastore either Cassandra or
  PostgreSql(default)
- Uses official [Kong](https://hub.docker.com/_/kong/) Docker image

Note: Opening this new PR instead of #3031.

2017-12-26 07:21 UTC, shashiranjan84 commented
/assign @unguiculus

2017-12-26 07:22 UTC, shashiranjan84 commented
I have updated the the labels and made few more changes as advised in best practices guide.

2018-01-07 17:45 UTC, unguiculus requested changes
Thanks for the PR. I did an initial review.

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/Chart.yaml
> +version: 0.1.0
Add `appVersion` field.

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/templates/NOTES.txt
> +     export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "kong.name" . }}" -o jsonpath="{.items[0].metadata.name}")
Add `release` label to selector.

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/templates/NOTES.txt
> +     export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "kong.name" . }}" -o jsonpath="{.items[0].metadata.name}")
Add `release` label to selector.

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/templates/NOTES.txt
> +     export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "kong.name" . }}" -o jsonpath="{.items[0].metadata.name}")
Add `release` label to selector.

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/templates/NOTES.txt
> +     export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "kong.name" . }}" -o jsonpath="{.items[0].metadata.name}")
Add `release` label to selector.

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/templates/deployment.yaml
> +      labels:
Only `app` and ` release` labels should go here.

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/templates/migrations.yaml
> +      labels:
Only `app` and ` release` labels should go here.

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/templates/deployment.yaml
> +    component: "kong_server"
It doesn't look like you have real components in your chart. There is only a single deployment. Usually, components are used to identify multiple deployments in a chart and then are added to label selectors. This is not the case here. Do they server any special purpose?

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/README.md
> +This chart allows you to choose either of them with the `kong.database.type`
`kong.database.type` is not set anywhere but mentioned here.

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/values.yaml
> +# Cassandra chart configs
It doesn't make sense to reproduce the whole Cassandra and Postgres values files here.

2018-01-07 17:45 UTC, unguiculus commented on stable/kong/values.yaml
> +  pg_password: kong
You should not added a second field for the DB password. There is already `postgresql.postgresPassword`. Also, by default, a random password is generated. Let's keep it that way.

2018-01-08 05:24 UTC, shashiranjan84 commented
@unguiculus thanks for review. I will make the changes you advised. Please expect some delay as I am travelling and have limited internet connectivity.

2018-01-08 07:38 UTC, shashiranjan84 commented
@unguiculus please review.

2018-01-11 18:49 UTC, unguiculus requested changes
Please don't squash commits. They will be squashed upon merge anyways.

2018-01-11 18:49 UTC, unguiculus commented on stable/kong/README.md
> +- Kubernetes 1.6+ with Beta APIs enabled.
1.8+

We offically support the current and previous minor versions.

2018-01-11 18:49 UTC, unguiculus commented on stable/kong/templates/deployment.yaml
> +apiVersion: extensions/v1beta1
Use `apps/v1beta2`

2018-01-11 18:49 UTC, unguiculus commented on stable/kong/values.yaml
> +  postgresDatabase: kong
Comment this out so the password is auto-generated by default.

2018-01-13 14:15 UTC, unguiculus commented
/ok-to-test

2018-01-13 16:25 UTC, unguiculus requested changes

2018-01-13 16:25 UTC, unguiculus commented on stable/kong/templates/deployment.yaml
> +      app: {{ template "kong.name" . }}
Add `release` label to selector.

2018-01-13 16:47 UTC, shashiranjan84 commented on stable/kong/templates/deployment.yaml
> +      app: {{ template "kong.name" . }}
Done.

2018-01-18 13:28 UTC, shashiranjan84 commented
@unguiculus are we still waiting on something?

2018-01-23 18:57 UTC, shashiranjan84 commented
ping @unguiculus

2018-01-27 13:26 UTC, unguiculus requested changes

2018-01-27 13:26 UTC, unguiculus commented on stable/kong/templates/migrations.yaml
> +        env:
For consistency, don't indent his list.

2018-01-27 13:26 UTC, unguiculus commented
/ok-to-test

2018-01-27 13:53 UTC, shashiranjan84 commented on stable/kong/templates/migrations.yaml
> +        env:
makes sense, @unguiculus I fixed it.

2018-01-27 14:08 UTC, unguiculus commented
/lgtm

2018-01-27 14:23 UTC, merged