[stable/redis] Allow customization of securityContext fsGroup/runAsUser fields
helm/charts pull request #3209
Opened 2018-01-03 18:57 UTC by rochacon

I use the [official repository](https://hub.docker.com/r/library/redis/) for Redis which creates a user with different UID/GID than the one currently used on the deployment manifest. This leads to permission errors when writing the RDB file to disk and service unavailability.

This pull request adds new values options for customizing the `pod.spec.securityContext.fsGroup` and `pod.spec.securityContext.runAsUser`, keeping the default the current value.

2018-01-04 05:04 UTC, sameersbn requested changes
Please bump the chart version in `Chart.yaml`

2018-01-04 14:21 UTC, rochacon commented
@sameersbn done, also signed the CLA, which was pending.

Anything else? Is the naming on the values good enough?

2018-01-04 14:36 UTC, sameersbn commented
/lgtm

2018-01-04 14:36 UTC, sameersbn approved these changes

2018-01-05 07:09 UTC, sameersbn commented
/lgtm

2018-01-05 07:11 UTC, sameersbn commented
/ok-to-test

2018-01-05 07:14 UTC, merged