Optionally adds liveness and readiness probes to jenkins
helm/charts pull request #3245
Opened 2018-01-05 20:50 UTC by jtslear

* Jenkins takes awhile to start the very first time, so we need to wait a bit before the first check
  * A value of 120 seconds seemed just right, but flexibility provided just in case it is not
* Setting the healthcheck endpoint to `/login` as that is what returns an HTTP200 when jenkins is alive
* This assists in addressing #772

2018-01-05 20:51 UTC, jtslear commented
/assign @sameersbn

2018-01-08 11:52 UTC, sameersbn commented
@jtslear I believe the probes should be enabled by default. Is there any reason for making the heath checks optional?

2018-01-08 11:52 UTC, sameersbn commented
/ok-to-test

2018-01-08 12:48 UTC, jtslear commented
I set it to false by default due to the fact that this was not included in the template from the start. Personally having these checks in place makes sense.  But due to not knowing why there weren't included in the first place, I imagine a reason must exist.  

Let me know and I'll gladly flip the boolean.

2018-01-08 15:21 UTC, sameersbn requested changes

2018-01-08 15:21 UTC, sameersbn commented on stable/jenkins/templates/jenkins-master-deployment.yaml
> +            initialDelaySeconds: {{ .Values.Master.HealthProbesTimeout | default 120 }}
please change this to `{{ .Values.Master.HealthProbesTimeout }}` and add the default value in the values.yaml file

2018-01-08 15:21 UTC, sameersbn commented on stable/jenkins/templates/jenkins-master-deployment.yaml
> +            initialDelaySeconds: {{ .Values.Master.HealthProbesTimeout | default 120 }}
please change this to `{{ .Values.Master.HealthProbesTimeout }}`

2018-01-08 15:21 UTC, sameersbn commented on stable/jenkins/values.yaml
> +  HealthProbes: false
please enable the probes by default and update the default value on the readme

2018-01-08 15:47 UTC, sameersbn approved these changes

2018-01-08 15:47 UTC, sameersbn commented
/lgtm

2018-01-08 15:48 UTC, merged