Set default imagePullPolicy to IfNotPresent
helm/charts pull request #325
Opened 2016-12-19 13:55 UTC by mstrzele

Fixes #295 for MySQL chart in the same way as #309 does it for MariaDB.

Related to kubernetes/kubernetes#38542.

PS I've changed `pod.alpha.kubernetes.io/init-containers` to
`pod.beta.kubernetes.io/init-containers`.

2016-12-19 22:36 UTC, viglesiasce commented
@k8s-bot ok to test

2016-12-21 18:52 UTC, viglesiasce commented
Thanks @mstrzele!

2016-12-21 19:16 UTC, prydonius requested changes

2016-12-21 19:16 UTC, prydonius commented on stable/mysql/values.yaml
>  ## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
Can we change the documentation here to:
```
## Specify an imagePullPolicy (Required)
## It's recommended to change this to 'Always' if the image tag is 'latest'
## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
```
Thanks!

2016-12-21 19:27 UTC, mstrzele commented on stable/mysql/values.yaml
>  ## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
Done!

2016-12-21 19:32 UTC, prydonius approved these changes

2016-12-21 19:32 UTC, prydonius commented
@k8s-bot e2e test this

2016-12-21 19:38 UTC, prydonius commented
Thanks a lot @mstrzele (and sorry to creep on @viglesiasce's lgtm!)

2016-12-21 23:28 UTC, merged