[incubator/oauth-proxy] Fix documentation typo for clientID value
helm/charts pull request #3255
Opened 2018-01-07 17:50 UTC by grugnog

The README.md references the key clientId whilst the actual name used in values.yaml and the templates is clientID (caps "ID").

2018-01-07 22:10 UTC, timstoop requested changes
Charts are immutable, so you always need to bump the version in the Charts file.

2018-01-09 16:58 UTC, grugnog commented
Thanks - forgot that was needed even for documentation changes.

2018-01-09 20:25 UTC, compleatang commented
LGTM

2018-01-14 15:41 UTC, unguiculus commented
/ok-to-test

2018-01-14 16:00 UTC, unguiculus commented
/lgtm

2018-01-14 16:04 UTC, merged