chaoskube: add chaoskube helm chart
helm/charts pull request #327
Opened 2016-12-19 16:52 UTC by linki

this adds a helm chart for [chaoskube](https://github.com/linki/chaoskube).

chaoskube is a little tool that periodically kills random pods in your cluster to test how well your applications can deal with failing pods.

2017-01-04 05:10 UTC, viglesiasce commented
@k8s-bot ok to test

2017-01-04 05:12 UTC, viglesiasce requested changes
One default change (dryRun->true).

2017-01-04 05:12 UTC, viglesiasce commented on incubator/chaoskube/README.md
> +| `dryRun`                  | defines whether pods should actually be terminated  | false                             |
Lets make dryRun on by default to protect users from accidentally shooting themselves (and others in the cluster) in the foot. Obviously that is the whole point of installing the chart but better to be safe than sorry.

2017-01-04 20:59 UTC, linki commented on incubator/chaoskube/README.md
> +| `dryRun`                  | defines whether pods should actually be terminated  | false                             |
I agree and changed it.

2017-01-04 21:01 UTC, linki commented
@viglesiasce I changed the default for dryRun to `true` so nobody can accidentally start killing stuff in the cluster.

2017-01-10 03:16 UTC, viglesiasce approved these changes

2017-01-10 03:17 UTC, viglesiasce commented
Looks good to me @linki! Do you want to move this to stable since it meets all the requirements?

2017-01-10 20:34 UTC, linki commented
@viglesiasce yes, I moved it. Thanks for your review!

2017-01-10 20:36 UTC, linki commented
wait, I have to update the docs as well...

2017-01-10 20:46 UTC, linki commented
alright, updated the docs as well.

2017-01-13 20:35 UTC, merged