[stable/grafana] fix grafana default config optoins
helm/charts pull request #3292
Opened 2018-01-10 16:42 UTC by jwhitcraft

Set the defaults as outlined by the values.yaml file.

fixes #1461

2018-01-10 16:46 UTC, jwhitcraft commented
/assign @sameersbn

2018-01-11 06:33 UTC, sameersbn requested changes

2018-01-11 06:33 UTC, sameersbn commented on stable/grafana/templates/job.yaml
> +        image: "{{ default "appropriate/curl:latest" .Values.server.setDatasource.image }}"
We recommend having the default values in the values.yaml. Please revert this change and uncomment the default value in the values.yaml file.

2018-01-11 06:33 UTC, sameersbn commented on stable/grafana/templates/job.yaml
> +          - "{\"name\":\"{{ default "default" .name }}\",\"type\":\"{{ default "prometheus" .type }}\",\"url\":\"{{ .url }}\",\"database\":\"{{ .database }}\",\"jsonData\":{ {{ .jsonData }} },\"acces
same as above

2018-01-11 06:33 UTC, sameersbn commented on stable/grafana/templates/job.yaml
> +      restartPolicy: {{ default "OnFailure" .Values.server.setDatasource.restartPolicy }}
same as above

2018-01-16 02:59 UTC, jwhitcraft commented
@sameersbn I updated this pr per your comments.

2018-01-16 07:07 UTC, sameersbn commented
/ok-to-test

2018-01-16 07:19 UTC, sameersbn approved these changes

2018-01-16 07:38 UTC, sameersbn commented
/lgtm

2018-01-16 07:39 UTC, merged