[incubator/anchore-engine] Adds incubator chart for Anchore Engine
helm/charts pull request #3293
Opened 2018-01-10 17:28 UTC by zhill

Adds Anchore Engine chart to incubator.

To test the service you can hit the API (as described in the NOTES.txt) or use the anchore-cli to query the system. The cli is available [here](https://github.com/anchore/anchore-cli) or via pip: `pip install anchorecli`. The instructions in NOTES indicates how to configure the cli.

2018-01-10 18:30 UTC, cblecker commented
bump

2018-01-10 18:35 UTC, zhill commented
/assign @sameersbn

2018-01-10 18:40 UTC, viglesiasce commented
/assign

2018-01-10 18:42 UTC, zhill commented
Working on the linter issues in the CircleCI result. Will update with commit to resolve those.

2018-01-11 18:20 UTC, viglesiasce commented
/ok-to-test

2018-01-11 18:36 UTC, viglesiasce requested changes

2018-01-11 18:36 UTC, viglesiasce commented on incubator/anchore-engine/Chart.yaml
> +appVersion: 0.1.3
nit, but can you move this to just under the version above.

2018-01-11 18:36 UTC, viglesiasce commented on incubator/anchore-engine/README.md
> +requires a PostgresSQL database (>=9.6) which may be handled by the chart of supplied externally,
/of/or/

2018-01-11 18:36 UTC, viglesiasce commented on incubator/anchore-engine/templates/NOTES.txt
> +If using an ingress:
Can you conditionally template this in/out based on whether the ingress is enabled?

2018-01-11 18:36 UTC, viglesiasce commented on incubator/anchore-engine/templates/NOTES.txt
> +    ANCHORE_CLI_URL=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ template "fullname" . }} -o jsonpath="{.spec.clusterIP}")":{{.Values.service.ports.api}}/v1/"
Can you add a "smoke test" here? How do users know that Anchore is installed properly? What can they do with it once its installed? Maybe also point to the user docs.

2018-01-11 18:44 UTC, viglesiasce commented
/hold

2018-01-12 17:40 UTC, zhill commented
I have addressed the review suggestions and also added a commit to clean up some labelling issues in the deployment definitions to ensure things like 'kubectl get pods -l' filters behave as expected.

2018-01-15 22:39 UTC, zhill commented
Moved chart from incubator to stable for PR review per discussion with @viglesiasce

2018-01-16 19:18 UTC, viglesiasce commented
Worked a treat! Thanks @zhill!

/lgtm

2018-01-16 19:18 UTC, viglesiasce approved these changes

2018-01-16 19:19 UTC, viglesiasce commented
/no-hold

2018-01-16 19:19 UTC, viglesiasce commented
/hold cancel

2018-01-16 19:25 UTC, merged

2018-01-16 20:02 UTC, zhill commented
Thanks @viglesiasce !