[incubator/chartmuseum] update documentation
helm/charts pull request #3296
Opened 2018-01-10 22:40 UTC by stefsuse

Update documentation to help move this chart into stable.

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

2018-01-10 22:58 UTC, stefsuse commented
/assign @jdolitsky

2018-01-10 23:35 UTC, jdolitsky requested changes

2018-01-10 23:35 UTC, jdolitsky commented on incubator/chartmuseum/README.md
> +Please also see https://github.com/chartmuseum/chartmuseum
Should be switched to https://github.com/kubernetes-helm/chartmuseum

2018-01-10 23:35 UTC, jdolitsky commented on incubator/chartmuseum/README.md
> +## Configuration
Can we add a comment here to say "check out values.yaml for all the possible configuration options" ?

2018-01-10 23:40 UTC, jdolitsky commented on incubator/chartmuseum/README.md
> +The following tables lists the configurable parameters of the vault chart and
"vault" chart?

2018-01-10 23:40 UTC, jdolitsky commented on incubator/chartmuseum/README.md
> +helm install --name my-chartmuseum -f values.yaml incubator/chartmuseum
This should probably be `-f custom.yaml` or something similar. `values.yaml` should contain defaults then be overridden by another yaml

2018-01-10 23:41 UTC, jdolitsky commented on incubator/chartmuseum/README.md
> +helm delete my-chartmuseum
Maybe want to add a `--purge` to the end of this

2018-01-11 16:56 UTC, stefsuse commented on incubator/chartmuseum/README.md
> +The following tables lists the configurable parameters of the vault chart and
fixed

2018-01-11 17:14 UTC, jdolitsky commented
/lgtm

2018-01-12 02:05 UTC, jdolitsky commented
/ok-to-test

2018-01-12 02:08 UTC, merged