Add Domoticz chart
helm/charts pull request #330
Opened 2016-12-20 11:35 UTC by nlamirault

Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

2016-12-22 02:13 UTC, prydonius commented
@k8s-bot ok to test

2016-12-22 02:28 UTC, prydonius requested changes
Thanks @nlamirault! You can actually submit this directly to the stable folder since incubator is only for charts that are in active development or are using K8S alpha features.

2016-12-22 02:28 UTC, prydonius commented on incubator/domoticz/Chart.yaml
> +home: https://www.domoticz.com/
Can you please add the appropriate metadata for maintainer, source, icon and optionally some keywords?

2016-12-22 02:28 UTC, prydonius commented on incubator/domoticz/templates/NOTES.txt
> +1. The Domoticz server can be accessed via port {{ .Values.server.httpPort }} on the following DNS name from within your cluster:
Could you describe the different ways to access the server based on the ServiceType used? Take a look at https://github.com/kubernetes/charts/blob/master/stable/drupal/templates/NOTES.txt for an example.

2016-12-22 02:28 UTC, prydonius commented on incubator/domoticz/templates/deployment.yaml
> +          imagePullPolicy: {{ default "Always" .Values.server.imagePullPolicy }}
It's good practice to have the default ImagePullPolicy be IfNotPresent rather than Always, unless absolutely required.

2016-12-22 02:28 UTC, prydonius commented on incubator/domoticz/templates/deployment.yaml
> +          readinessProbe:
can we add a livenessProbe also?

2016-12-22 02:28 UTC, prydonius commented on incubator/domoticz/values.yaml
> +persistentVolume:
looks like you're not using any volumes so you can remove this section

2016-12-22 02:28 UTC, prydonius commented on incubator/domoticz/README.md
> +| `server.persistentVolume.enabled`     | Create a volume to store data       | true                                              |
looks like you're not using any volumes so you can remove this section

2017-01-04 06:39 UTC, viglesiasce requested changes
Notes need more info.

2017-01-04 06:39 UTC, viglesiasce commented on incubator/domoticz/templates/NOTES.txt
> +1. The Domoticz server can be accessed via port {{ .Values.server.httpPort }} on the following DNS name from within your cluster:
Yes please

2017-02-03 00:53 UTC, prydonius commented
@nlamirault any update here?

2017-02-03 07:02 UTC, nlamirault commented
I will try to fix that asap

2017-03-22 22:45 UTC, seanknox commented
Closing due to inactivity. @nlamirault feel free to re-open.

2017-03-22 22:45 UTC, closed without merging