[spark/stable] Added persistence for notebooks and configuration
helm/charts pull request #3345
Opened 2018-01-16 15:20 UTC by jonaseck2

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

2018-01-16 15:22 UTC, jonaseck2 commented
Based on PR #3291

/assign @scottrigby

2018-01-25 07:29 UTC, jonaseck2 commented
/assign unguiculus

2018-01-27 13:42 UTC, unguiculus requested changes

2018-01-27 13:42 UTC, unguiculus commented on stable/spark/templates/spark-zeppelin-pvc.yaml
> +---
Create two separate files, please.

2018-01-27 13:42 UTC, unguiculus commented on stable/spark/values.yaml
> +      # storageClass: "-"
`# StorageClass: "-"`

2018-01-27 13:42 UTC, unguiculus commented on stable/spark/values.yaml
> +      Enabled: false
StorageClass missing

2018-01-27 13:42 UTC, unguiculus commented on stable/spark/README.md
> +| `Zeppelin.Persistence.Config.Size`       | Configuration Persistence AccessMode | `ReadWriteOnce`                            |
StorageClass missing.

2018-01-27 13:42 UTC, unguiculus commented
/assign @lachie83

2018-02-19 18:06 UTC, jonaseck2 commented
What are we waiting for?

2018-02-20 00:53 UTC, unguiculus commented
/ok-to-test

2018-02-20 00:58 UTC, unguiculus approved these changes

2018-07-15 16:13 UTC, unguiculus commented
/lgtm

2018-07-15 17:12 UTC, merged

2018-09-07 00:58 UTC, VinceMD commented
It's broken:

https://github.com/helm/charts/issues/7478
https://github.com/helm/charts/issues/6784 

Even though it's in stable