[stable/redis] add `volumeMount` `subPath` feature.
helm/charts pull request #3356
Opened 2018-01-17 11:39 UTC by Antiarchitect

Ability to use subdirectories in PV. Helps with Dev under minikube and cases when one PV for multiple services is used.

2018-01-22 13:31 UTC, sameersbn requested changes

2018-01-22 13:31 UTC, sameersbn commented on stable/redis/values.yaml
> +  supPath: ""
you have a typo here

2018-01-22 14:49 UTC, Antiarchitect commented
@sameersbn Thx, fixed.

2018-01-27 17:52 UTC, unguiculus commented
/ok-to-test

2018-01-27 17:57 UTC, unguiculus commented
/lgtm

2018-01-27 17:58 UTC, merged