Add kube-slack chart
helm/charts pull request #3357
Opened 2018-01-17 12:17 UTC by jstriebel

This PR adds an incubator chart for [`kube-slack`](https://github.com/wongnai/kube-slack).

I tried to incorporate best practices as far as possible. I did not enter any `maintainers` in the `Chart.yaml` yet. Should I enter myself there?

If all requirements are met, I can also move it to `stable`.

Thanks for considering this PR!

/cc @whs (author of `kube-slack`)

2018-01-17 12:18 UTC, jstriebel commented
/assign @foxish

2018-01-24 09:04 UTC, foxish commented
> I tried to incorporate best practices as far as possible. I did not enter any maintainers in the Chart.yaml yet. Should I enter myself there?

Yes, that would be a good idea.

2018-01-24 09:09 UTC, foxish commented
/ok-to-test

2018-01-24 09:47 UTC, jstriebel commented
@foxish done, added myself as maintainer. Is anything missing to move this to `stable`?

2018-02-05 12:40 UTC, jstriebel commented
@foxish anything else I should do about this chart?

2018-02-17 15:30 UTC, rawkode commented
Would love to see this merged 👍

2018-02-22 04:13 UTC, unguiculus commented
/hold

2018-02-22 04:13 UTC, unguiculus commented
/assign

2018-02-24 10:21 UTC, unguiculus requested changes
Thanks for the PR. I'd like you to do a few corrections. Please compare your templates with what you get with `helm create` using Helm 2.8+ and update accordingly.

Please follow our RBAC best practices.
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

2018-02-24 10:21 UTC, unguiculus commented on incubator/kube-slack/templates/_helpers.tpl
> +{{- if ge .Capabilities.KubeVersion.Minor "8" -}}
This will not work once Kubernetes 1.10 is out (8 > 10). You'd have to use `semvercompare`. However, I'd suggest you just use the `v1` api or do you absolutely have to support K8s < 1.8? Officially, we support the current and previous major versions, which would be 1.8+.

2018-03-01 17:02 UTC, rawkode commented
@jstriebel Are you able to make these changes, or can I pick them up?

2018-03-02 08:50 UTC, jstriebel commented
Sorry for the late reply, I was unavailable the last week. @rawkode, I would add the changes the next days, but feel free to pick it up.

2018-03-05 10:13 UTC, jstriebel commented
@unguiculus Thank you for the feedback, I changed the chart accordingly.

As I would still like to use this chart with kubernetes 1.7, I used `semverCompare`. The linter had a bug about the usage of , which [is already fixed](https://github.com/kubernetes/helm/issues/3349), only the [testing needs to be upgraded to the newest helm version](https://github.com/kubernetes/charts/blob/master/test/circle/install.sh#L17).

To support kubernetes 1.7, I used `apps/v1beta1` as the apiVersion for the deployment, I hope that's fine. I already use the explicit selector which is needed in future versions.

If you think that is to much clutter for the compatibility, I would change the rbac and deployment versions accordingly.

2018-04-05 14:28 UTC, jstriebel commented
As the newest helm version is now used, I guess this should be ready. Could you have another look, @unguiculus?

/assign @unguiculus

2018-04-07 12:09 UTC, unguiculus requested changes
Let me remind you to apply our RBAC best practices:
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

Also, I'd suggest you directly move the chart to stable.

2018-04-07 12:09 UTC, unguiculus commented on incubator/kube-slack/templates/_helpers.tpl
> +{{- if semverCompare ">= 1.8" .Capabilities.KubeVersion.GitVersion -}}
In order to be compatible with e. g. GKE, which names its release as pre-releases, please do this:

`if semverCompare ">= 1.8-0"`

See #3002

2018-04-18 15:03 UTC, jstriebel commented
@unguiculus Thanks for the feedback! I incorporated it and moved the chart to stable. I also renamed the `rbac.apiVersion` helper to `kube-slack.rbac.apiVersion`. Is anything else missing?

PS: Sorry for the delay.

2018-04-18 20:03 UTC, unguiculus commented
/lgtm

2018-04-18 20:08 UTC, unguiculus approved these changes

2018-04-18 20:08 UTC, unguiculus commented
/hold cancel

2018-04-18 20:23 UTC, merged