[nginx-lego] Trim '-' suffix from resource names
helm/charts pull request #339
Opened 2016-12-22 09:57 UTC by munnerz

Without this change, I get the following output with an OOTB config:

```
helm install stable/nginx-lego
Fetched stable/nginx-lego to nginx-lego-0.1.0.tgz
Error: release killjoy-butterfly failed: ConfigMap "killjoy-butterfly-nginx-" is invalid: metadata.name: Invalid value: "killjoy-butterfly-nginx-": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')
```

2016-12-22 11:23 UTC, munnerz commented
I signed it!

2016-12-23 01:46 UTC, prydonius commented on stable/nginx-lego/templates/_helpers.tpl
> +{{- default .Chart.Name .Values.nameOverride | trunc 24 | trimSuffix "-" -}}
This can also be updated to truncate to 63 chars (see #233)

2016-12-23 01:47 UTC, prydonius commented
@k8s-bot ok to test

2016-12-23 11:36 UTC, munnerz commented
@prydonius updated accordingly

2017-01-13 01:29 UTC, mgoodness commented on stable/nginx-lego/templates/_helpers.tpl
>  */}}
Update to 63 chars.

2017-01-13 01:30 UTC, mgoodness requested changes

2017-01-13 01:30 UTC, mgoodness commented on stable/nginx-lego/templates/_helpers.tpl
>  */}}
Update to 63 chars.

2017-01-13 01:32 UTC, mgoodness commented
Version rev? Be careful of conflict with #388

2017-01-13 17:46 UTC, jackzampolin commented
I haven't touched `NOTES.txt` so this should :crossed_fingers: be fine.

2017-01-23 18:39 UTC, viglesiasce commented
@mgoodness @jackzampolin do we still want this in? This would need a version bump since it touches the templates.

2017-01-23 18:52 UTC, jackzampolin commented
@viglesiasce My vote would be to close this in favor of #399 and #397.

2017-01-31 19:12 UTC, viglesiasce commented
@jackzampolin  Im fine with that. Closing in favor of the other 2 PRs since this chart is being split up.

2017-01-31 19:12 UTC, closed without merging