[stable/postgresql] makes secretKeyRefs configureable
helm/charts pull request #3393
Opened 2018-01-22 07:55 UTC by tonyfahrion

Changeclass: minor - backward compatible

**WHY**
We are using the `postgresql` chart by some other charts. In order to allow an out-of-the-box experience for our users, we need to control the generated secrets used by this chart. As discussed in https://github.com/kubernetes/helm/issues/2196#issuecomment-293738730 I don't know a way to resolve secrets on template resolution time; so this is an idea I came up with to solve this until there is a better way.

**Behaviour**
This commit is non-disruptive to the userbase, as it defaults to
the current behaviour. I does not fix a bug, but instead extends the functionality.

**Testing**
* `helm lint` is fine
* `helm install --name tester .` is fine (also checked the commands generated in NOTES.txt
* `helm template --name tester .` seems to be fine too

**TODO**
* increment minor version number

I'm very interested in your feedback! Is this an acceptable approach to achieve the goal of getting secrets defined externally? How do you handle those kind of issues?

Kind regards and a happy weekend
Tony

2018-01-22 13:34 UTC, tonyfahrion commented
/assign @linki

2018-01-23 19:56 UTC, tonyfahrion commented
Okay, version bump is done to `0.9.0`

2018-02-22 15:52 UTC, unguiculus commented
cc @swordbeta @databus23

2018-04-19 17:42 UTC, unguiculus requested changes
Sorry for the delay. Please fix conflicts and I'll try and get that merged soon.

2018-04-19 17:42 UTC, unguiculus commented on stable/postgresql/templates/_helpers.tpl
> +    generates a yaml secretKeyRef env structure and expects the folowing structure as input (dict):
folowing -> following

2018-04-20 06:28 UTC, tonyfahrion commented
@unguiculus Thx for processing this PR

I solved the conflicts and did a rebase + version bump to `0.11.0`

The main conflict was due to the introduction of getting the postgres password by file (#5013). I changed the code to not break the password-by-file concept. This requires changes within the `values.yaml`, `templates/NOTES.txt` and `templates/deployment.yaml` - please review those again.

This PR now also makes `NOTES.txt` aware of the possible password-by-file concept.

2018-04-20 06:28 UTC, tonyfahrion commented on stable/postgresql/templates/_helpers.tpl
> +    generates a yaml secretKeyRef env structure and expects the folowing structure as input (dict):
fixed

2018-04-20 09:18 UTC, tonyfahrion commented
@unguiculus please do **NOT** merge the PR right now - as I would like to discuss this concept a little bit more. And it seems that in #3394 there are concerns regarding this approach (I would like to come up with a more common solution, instead of introducing multiple concepts 🙂).

2018-05-02 19:41 UTC, WarheadsSE commented
@tonyfahrion I've proposed https://github.com/kubernetes/charts/pull/5293 as an alternative method to this, if you'd like to have look.

2018-05-03 15:32 UTC, unguiculus commented
/hold

2018-05-07 07:03 UTC, tonyfahrion commented
I'll close this PR in favour of #5413 

See https://github.com/kubernetes/charts/pull/5293#issuecomment-386517712 for more details

2018-05-07 07:03 UTC, closed without merging