External-dns improve azure support
helm/charts pull request #3404
Opened 2018-01-22 15:51 UTC by duga3

* Automatically mount the azure configuration as VolumeMount when using azure as provider.
* Bump external chart to latest stable version (0.4.8)
* Make RBAC api version configurable

2018-01-23 07:58 UTC, duga3 commented
#3389 should go in first

2018-01-28 21:06 UTC, unguiculus requested changes

2018-01-28 21:06 UTC, unguiculus commented on stable/external-dns/values.yaml
> +provider: azure
Why change the default?

2018-01-29 20:02 UTC, unguiculus commented
/cc @linki

2018-01-29 20:02 UTC, unguiculus approved these changes

2018-01-29 20:03 UTC, unguiculus commented
cc @rk295

2018-02-02 11:49 UTC, unguiculus commented
/ok-to-test

2018-02-02 12:11 UTC, unguiculus commented
/lgtm

2018-02-02 12:16 UTC, merged