New helm chart for kanister-operator
helm/charts pull request #3406
Opened 2018-01-22 18:15 UTC by depohmel

Incubator chart: https://kanister.io/
Quick start intrustion: https://github.com/kanisterio/kanister

2018-01-23 16:47 UTC, paulczar requested changes

2018-01-23 16:47 UTC, paulczar commented on incubator/kanister-operator/README.md
> +`rback.service_account`| porvided service account name will be used | `None`
should be `rbac.service_account`

2018-01-23 18:06 UTC, depohmel commented on incubator/kanister-operator/README.md
> +`rback.service_account`| porvided service account name will be used | `None`
@paulczar thanks.  /done

2018-01-23 21:48 UTC, depohmel commented
/assign @mgoodness 
/approve

2018-01-26 10:52 UTC, prydonius commented
@depohmel if the chart meets all the technical requirements and documentation requirements in https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements this can be put straight into the stable repository. Can't see anything obvious violating those requirements.

2018-01-26 16:34 UTC, depohmel commented
thanks, @prydonius 
Can I do move as part of this PR or will it be better to create a new one?

2018-01-26 17:26 UTC, prydonius commented
@depohmel ideally in this PR, so we can avoid it being in incubator at all.

2018-01-26 17:36 UTC, depohmel commented
@prydonius, thanks.  Just pushed a move.

2018-02-06 18:10 UTC, depohmel commented
/assign @prydonius

2018-02-08 18:53 UTC, tdmanv commented
@prydonius thanks for all the help. Is there anything left we can do to get this merged?

2018-02-15 09:42 UTC, unguiculus requested changes
In general, please follow our guidelines:
https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Make sure you use namespaced templates. Ideally you use `helm create` with Helm 2.8+ and take the `_helpers.tpl` you get.

Note that our RBAC best practices have been revised. Please update accordingly.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

Go over readme and notes again. From quickly skimming over them I noticed a few typos.

2018-02-15 09:42 UTC, unguiculus commented on stable/kanister-operator/Chart.yaml
> +version: 0.2.0
Add `appVersion` and `sources`. Use Github username for maintainers.

2018-02-15 19:05 UTC, depohmel commented
@unguiculus , thanks for the review.

2018-02-20 01:03 UTC, unguiculus requested changes
Almost there.

2018-02-20 01:03 UTC, unguiculus commented on stable/kanister-operator/templates/rbac.yaml
> +{{- if .Values.serviceAccount.create }}
Please put the service account into its own file.

2018-02-20 01:03 UTC, unguiculus commented on stable/kanister-operator/templates/_helpers.tpl
> +chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
Use the `chart` template.

2018-02-20 01:03 UTC, unguiculus commented on stable/kanister-operator/templates/deployment.yaml
> +apiVersion: extensions/v1beta1
`apps/v1beta2`

2018-02-20 01:03 UTC, unguiculus commented on stable/kanister-operator/README.md
> +  - Kubernetes 1.7+ with Beta APIs enabled
1.8+

We officially support the current and previous minor versions of Kubernetes.

2018-02-20 05:08 UTC, depohmel commented
@ultimateboy could you please do another look?

2018-02-24 10:27 UTC, unguiculus approved these changes

2018-02-24 10:27 UTC, unguiculus commented
/ok-to-test

2018-02-24 10:53 UTC, unguiculus commented
/lgtm

2018-02-24 10:57 UTC, merged

2018-02-24 23:08 UTC, depohmel commented
Thanks @unguiculus!