add support for explicit NodePort on jenkins chart
helm/charts pull request #342
Opened 2016-12-22 19:15 UTC by dannydavidson

2017-01-04 06:40 UTC, viglesiasce commented
Please bump the chart version.

2017-01-04 06:40 UTC, viglesiasce requested changes
Please bump the chart version.

2017-01-20 01:27 UTC, prydonius commented
@dannydavidson please rebase to resolve the conflicts

2017-01-23 18:43 UTC, viglesiasce approved these changes

2017-01-26 17:11 UTC, merged