Created chart for openvpn
helm/charts pull request #343
Opened 2016-12-22 21:01 UTC by jfelten

I though this might be useful to others so I thought I'd create a PR for it.

2016-12-22 21:37 UTC, alejandroEsc requested changes

2016-12-22 21:37 UTC, alejandroEsc commented on incubator/openvpn/README.md
> +This chart will install an openvpn server inside a kubernetes cluster.  New certificates are generated on install, and a script is provided to genreate client keys as needed.  The chart will automati
r/genreate/generate

2016-12-22 21:37 UTC, alejandroEsc commented on incubator/openvpn/Chart.yaml
> +description: A Helm chart to install an openvpn server inside a kubernetes cluster.  Certificate generation is also part of the deployment, and this chart will genreate cleint keys as needed.
r/genreate/generate

2016-12-22 21:37 UTC, alejandroEsc commented on incubator/openvpn/Chart.yaml
> +description: A Helm chart to install an openvpn server inside a kubernetes cluster.  Certificate generation is also part of the deployment, and this chart will genreate cleint keys as needed.
r/ceint/client

2016-12-22 21:37 UTC, alejandroEsc commented on incubator/openvpn/README.md
> +When ready generate a client key as follows:
When ready, generate....

2016-12-22 21:37 UTC, alejandroEsc commented on incubator/openvpn/README.md
> +Be sure to change KEY_NAME if genreating additional keys.  Import the .ovpn file into your favorite openvpn tool like tunnelblick and verify connectivity.
r/genreating/generating

2017-01-03 23:40 UTC, jfelten commented
cc @spiffxp

2017-01-04 04:31 UTC, alejandroEsc commented
@jfelten please squash your commits.

2017-01-10 00:57 UTC, viglesiasce requested changes
One issue in the NOTES but this worked super well for me. Tested with Tunnelblick and was able to reach my Pods without issue.

Thank you so much for this awesome chart!

2017-01-10 00:57 UTC, viglesiasce commented on incubator/openvpn/templates/NOTES.txt
> +&& kubectl exec -it $POD_NAME cat /usr/share/easy-rsa/pki/$KEY_NAME.ovpn > $KEY_NAME.ovpn
Not all of the kubectl commands in here are passing the namespace so this doesnt work in custom namespaces ATM.

2017-01-10 00:59 UTC, viglesiasce commented
@k8s-bot ok to test

2017-01-10 01:00 UTC, viglesiasce requested changes
Please move the chart to the stable folder

2017-01-10 01:48 UTC, viglesiasce requested changes

2017-01-10 01:48 UTC, viglesiasce commented on incubator/openvpn/README.md
> +Wait for the external load balancer IP to become available.  Check service status via: kubectl get svckubectl get svc
Typo here.

2017-01-10 18:19 UTC, jfelten commented on incubator/openvpn/templates/NOTES.txt
> +&& kubectl exec -it $POD_NAME cat /usr/share/easy-rsa/pki/$KEY_NAME.ovpn > $KEY_NAME.ovpn
removed namespace - wasn't needed anyways

2017-01-10 18:20 UTC, viglesiasce commented
Hey @jfelten, sorry for the confusion but I meant that all the commands needed the namespace added to them rather than removed.

2017-01-10 18:21 UTC, jfelten commented
changed as requested

2017-01-10 18:24 UTC, jfelten reviewed
changed as requested

2017-01-10 18:24 UTC, jfelten commented on incubator/openvpn/README.md
> +Wait for the external load balancer IP to become available.  Check service status via: kubectl get svckubectl get svc
changed to stable

2017-01-10 18:31 UTC, viglesiasce commented
@jfelten the exec commands also need the namespace flag

2017-01-10 18:33 UTC, jfelten commented
I'm not sure the namespace restriction is necessary, but it doesn't hurt.  I added back to the appropriate kubectl commands.

2017-01-10 18:34 UTC, viglesiasce commented
It is necessary when the namespace you deploy to is not the namespace in your current context.

2017-01-10 18:47 UTC, jfelten commented
gotcha - hadn't considered that use case.  Added to namespace exec commands also.

2017-01-10 19:06 UTC, viglesiasce approved these changes

2017-01-10 19:07 UTC, viglesiasce commented
Thanks @jfelten!

2017-01-11 23:59 UTC, merged

2018-09-19 13:25 UTC, so0k commented on stable/openvpn/templates/config-openvpn.yaml
> +      push "route NETWORK 255.255.240.0"
what is the purpose of this route and netmask, this causes validation errors on linux vpn clients as the cidr is invalid @jfelten