adds osclass chart
helm/charts pull request #345
Opened 2016-12-27 13:27 UTC by sameersbn

2017-01-03 16:11 UTC, prydonius commented
@k8s-bot ok to test

2017-01-04 23:09 UTC, viglesiasce commented
@k8s-bot ok to test

2017-01-04 23:10 UTC, viglesiasce requested changes

2017-01-04 23:10 UTC, viglesiasce commented on stable/osclass/requirements.yaml
> +  version: 0.5.4
Please update to 0.5.6 which has the fix for K8s 1.5.1

2017-01-05 06:53 UTC, sameersbn commented
- updated mariadb chart version to 0.5.6
- `imagePullPolicy` explicitly set to `IfNotPresent`

2017-01-09 19:55 UTC, viglesiasce commented
@k8s-bot e2e test this

2017-01-23 18:34 UTC, viglesiasce approved these changes

2017-01-26 17:12 UTC, merged