[incubator/jaeger] Adds ability to utilize a cloud providers firewall for services
helm/charts pull request #3457
Opened 2018-01-26 12:35 UTC by jtslear

* Adds declaration allowing the user to configure which IP CIDRs are
allowed to access a service via a cloud providers firewall
* An example configuration of `values.yaml` may look like this:
```
query:
  service:
    type: LoadBalancer
    loadBalancerSourceRanges:
      - "192.0.2.0/24"
      - "198.51.100.0/24"
```
* The above would configure a cloud provider's firewall with a ruleset
allowing only the configured IP ranges access to the query service
* This adds this declaration across the board for all services as it may
be valuable. One example, is to send metric data from applications that
do not reside in kubernetes
* This PR also updates the README to reflect other options for services
that have not been updated over time.

2018-01-26 12:41 UTC, jtslear commented
/assign @mgoodness

2018-02-22 16:00 UTC, unguiculus commented
/ok-to-test

2018-04-27 13:54 UTC, pavelnikolov requested changes
Please define a reusable template for the `loadBalancerSourceRanges`.

2018-04-27 13:54 UTC, pavelnikolov commented on incubator/jaeger/templates/agent-svc.yaml
> +{{- if .Values.agent.service.loadBalancerSourceRanges }}
This block is repeated four times, exactly the same. Please, define a template and reuse it instead.

2018-04-27 13:54 UTC, pavelnikolov commented on incubator/jaeger/values.yaml
> +
Please, remove empty line

2018-04-27 13:54 UTC, pavelnikolov commented on incubator/jaeger/values.yaml
> +
Please, remove empty line

2018-04-27 13:54 UTC, pavelnikolov commented on incubator/jaeger/values.yaml
> +
Please, remove empty line

2018-04-27 13:54 UTC, pavelnikolov commented on incubator/jaeger/values.yaml
> +
Please, remove empty line

2018-04-30 12:17 UTC, jtslear commented
I've addressed the comments and performed a rebase.  Please enjoy.

2018-05-09 21:31 UTC, unguiculus commented
ping @pavelnikolov

2018-05-09 21:31 UTC, unguiculus commented
/assign

2018-05-10 04:12 UTC, pavelnikolov commented
lgtm

2018-05-10 07:34 UTC, unguiculus commented
/lgtm

2018-05-10 07:56 UTC, merged