Update to 0.10.x release
helm/charts pull request #3462
Opened 2018-01-26 18:59 UTC by cap10morgan

Upgrade default upstream version to 0.10.2 and fix issues that that causes. Supplants #3180 and incorporates changes in #3369 because they are needed here.

2018-01-26 19:25 UTC, cap10morgan commented
/assign @mattfarina Since you reviewed my earlier (now obsolete) PR.

2018-01-26 19:30 UTC, cap10morgan commented
/assign @mattfarina

2018-01-26 20:11 UTC, unguiculus requested changes

2018-01-26 20:11 UTC, unguiculus commented on stable/nginx-ingress/README.md
> +`controller.image.tag` | controller container image tag | `0.9.0`
0.10.2

2018-01-26 21:33 UTC, cap10morgan commented
@unguiculus Updated. Thanks for catching that!

2018-01-27 11:58 UTC, unguiculus commented
/ok-to-test

2018-01-29 17:51 UTC, marc-sensenich commented
@unguiculus Are there any additional limitations for getting this chart merged in? I saw #3418 is open as well, I didn't know if there was a plan to merge that first before releasing this PR so that both a patch and minor version would be released

2018-01-29 18:04 UTC, unguiculus commented
/lgtm

2018-01-29 18:07 UTC, merged