add openldap
helm/charts pull request #347
Opened 2016-12-27 17:50 UTC by ekozan

WIP
For work tracking

Todo:

- Add more instruction
- Add reference
- Make test

2017-01-19 19:14 UTC, viglesiasce commented
@k8s-bot ok to test

2017-01-23 19:06 UTC, viglesiasce requested changes
Please fix the readme and add NOTES.txt

2017-01-23 19:06 UTC, viglesiasce commented on incubator/openldap/README.md
> +__DISCLAIMER:__ While this chart has been well-tested, testers have encountered occasional issues
This looks like a copy paste issue.

2017-01-23 19:06 UTC, viglesiasce commented on incubator/openldap/README.md
> +- You are deploying the chart to a cluster with a cloud provider capable of provisioning an
Is this true?

2017-01-25 19:41 UTC, ekozan commented on incubator/openldap/README.md
> +__DISCLAIMER:__ While this chart has been well-tested, testers have encountered occasional issues
spoted

2017-01-25 19:41 UTC, ekozan commented on incubator/openldap/README.md
> +- You are deploying the chart to a cluster with a cloud provider capable of provisioning an
spoted v2

2017-02-25 19:25 UTC, mgoodness commented
@ekozan is this still an active/WIP PR? Do you have an ETA for completion?

2017-03-10 17:23 UTC, mgoodness commented
Closing due to inactivity. Feel free to re-open if/when ready.

2017-03-10 17:23 UTC, closed without merging