Add support for multiple replica count to grafana
helm/charts pull request #3476
Opened 2018-01-29 12:06 UTC by simt2

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

This PR adds support for multiple replicas to the stable/grafana chart.

2018-01-29 12:15 UTC, simt2 commented
/retest

2018-01-30 07:44 UTC, simt2 commented
/assign @viglesiasce

2018-01-30 17:11 UTC, viglesiasce commented
/ok-to-test

2018-01-30 17:26 UTC, viglesiasce requested changes

2018-01-30 17:26 UTC, viglesiasce commented on stable/grafana/values.yaml
> +    enabled: true
Can you disable this by default?

2018-01-31 07:37 UTC, simt2 commented
Changed anti-affinity to false, @viglesiasce

2018-02-02 07:09 UTC, simt2 commented
Tests green now

2018-02-05 06:38 UTC, simt2 commented
Is there anything else I need to do to get this merged @viglesiasce ?

2018-02-05 16:51 UTC, josdotso commented
Can we get `.server.affinity` passed through without the hard/soft approach?  We've seen cases where more nuanced config is necessary in this map. Thanks!

2018-02-08 19:41 UTC, viglesiasce commented
@josdotso the issue with passing it straight through is that you cannot template it then.

@simt2 what do you think about passing it straight through from values to the manifests?

2018-02-09 07:30 UTC, simt2 commented
@josdotso @viglesiasce I was adhering to existing patterns but I agree that passing through `affinity` allows for more flexibility, similar to `nodeSelector` and `tolerations`. I will pass it through and add examples for the classic hard and soft approaches.

2018-02-13 08:02 UTC, simt2 commented
/reopen

2018-02-15 23:11 UTC, viglesiasce approved these changes

2018-02-15 23:11 UTC, viglesiasce commented
@simt2 lets get this first implementation in as is since it satisfies the use case ATM. in a future update lets think about how we could achieve this in a v1.0.0 version of this chart.

/lgtm

2018-02-15 23:14 UTC, merged