Added more options and README updated
helm/charts pull request #348
Opened 2016-12-28 01:36 UTC by NitishT

2016-12-28 01:37 UTC, NitishT commented
@hunter would like to know your views

2017-01-03 16:08 UTC, prydonius commented
this is really awesome @NitishT, thanks!

2017-01-03 16:08 UTC, prydonius commented
@k8s-bot ok to test

2017-01-03 16:39 UTC, NitishT commented
@prydonius 👍

2017-01-03 16:52 UTC, prydonius commented on stable/minio/templates/minio_configmap.yaml
> +     {{- if eq $nodeCount 4 }}
You should be able to reduce to a couple of lines with a loop:

```
{{- range $i := until $nodeCount }}
http://{{ template "fullname" $ }}-{{$i}}.{{ template "fullname" $ }}.{{ $.Release.Namespace }}.svc.cluster.local{{ $.Values.mountPath }} \
{{- end }}
```

You'll also need to deal with not including the final backslash.

2017-01-03 16:56 UTC, NitishT commented on stable/minio/templates/minio_configmap.yaml
> +     {{- if eq $nodeCount 4 }}
Thanks @prydonius ! I was looking to add a loop but wasn't able to get it working. I will make these changes.

2017-01-03 17:25 UTC, NitishT commented
As far as I understand `int` is a valid conversion(https://godoc.org/github.com/Masterminds/sprig). Please correct me if I am wrong. 

Also, linting passed locally:

![screen shot 2017-01-03 at 10 53 29 pm](https://cloud.githubusercontent.com/assets/5156139/21616445/95d01eb4-d207-11e6-9a13-d4e3a5717a69.png)

2017-01-04 15:37 UTC, NitishT commented
@k8s-bot e2e test this

2017-01-04 16:01 UTC, prydonius commented
@NitishT int was added recently, and unfortunately we're still on Helm 2.0.0. We will need to upgrade the Helm version in the CI /cc @viglesiasce.

2017-01-04 16:04 UTC, NitishT commented
Thanks for the info @prydonius . So, no action from my side needed then?

2017-01-04 16:10 UTC, prydonius commented
Thanks @NitishT, not for the moment. Sorry about the delay, will keep you updated!

2017-01-04 16:11 UTC, NitishT commented
Cool. Thanks @prydonius

2017-01-04 18:08 UTC, harshavardhana commented
:100:

2017-01-04 18:11 UTC, viglesiasce commented
My goal is to get 2.1.3 in the test cluster today.

2017-01-05 09:32 UTC, prydonius commented
@k8s-bot ok to test

2017-01-09 17:13 UTC, NitishT commented
@prydonius tests seem to be passing. Can we move forward here?

2017-01-10 03:08 UTC, viglesiasce requested changes
I tested both standalone and distributed modes without issue. Requesting on change to the storage annotation.

2017-01-10 03:08 UTC, viglesiasce commented on stable/minio/templates/minio_statefulset.yaml
> +        annotations:
Can you change this annotation to work like the one in #367? Namely use alpha annotation if the storageClass is not provided, otherwise use beta.

2017-01-10 03:14 UTC, NitishT commented on stable/minio/templates/minio_statefulset.yaml
> +        annotations:
Thanks @viglesiasce will do that today

2017-01-10 18:15 UTC, NitishT commented on stable/minio/templates/minio_statefulset.yaml
> +        annotations:
Done @viglesiasce

2017-01-11 20:22 UTC, NitishT commented
Hi @viglesiasce we have a Minio and Kubernetes demo scheduled for the K8S community meeting [PST 10.00 AM, 12th Jan], and we would love to show our official Helm Chart. 

If there is nothing blocking, it would be great if we can move ahead here..

2017-01-11 20:31 UTC, prydonius commented on stable/minio/templates/minio_deployment.yaml
>  {{ toYaml .Values.resources | indent 12 }}
`.Values.resources` was removed from values.yaml.

2017-01-11 20:33 UTC, prydonius commented on stable/minio/templates/minio_statefulset.yaml
> +            memory: {{ .Values.memory }}
memory and cpu are not defined in the volume claim spec, these should be defined in the containers object, I suggest you keep `.Values.resources` for cpu and memory and use that with the `toYaml` helper in the containers object.

2017-01-11 20:34 UTC, prydonius commented
thanks for the info @NitishT, this is close and we'll hopefully be able to merge it today

2017-01-11 20:59 UTC, NitishT commented on stable/minio/templates/minio_deployment.yaml
>  {{ toYaml .Values.resources | indent 12 }}
Good catch. Added `.Values.resources` in values.yaml

2017-01-11 21:01 UTC, NitishT commented on stable/minio/templates/minio_statefulset.yaml
> +            memory: {{ .Values.memory }}
Done.

2017-01-11 21:02 UTC, NitishT commented
Thanks for the consideration @prydonius

2017-01-11 21:45 UTC, prydonius commented
This is looking good to me now, will give @viglesiasce a chance to re-review.

2017-01-12 02:39 UTC, viglesiasce approved these changes

2017-01-12 02:42 UTC, viglesiasce commented
Thanks @NitishT!!

2017-01-12 02:42 UTC, merged

2017-01-12 02:56 UTC, viglesiasce commented
@NitishT chart is live! Thanks for the contribution.

```
$ helm search stable/minio
NAME        	VERSION	DESCRIPTION
stable/minio	0.0.2  	A Minio Helm chart for Kubernetes
```

2017-01-12 02:58 UTC, harshavardhana commented
Superb @NitishT @viglesiasce @prydonius :100:

2017-01-12 03:14 UTC, NitishT commented
Thanks @viglesiasce @prydonius @harshavardhana This is awesome!