Move oauth-proxy to stable
helm/charts pull request #3480
Opened 2018-01-29 21:33 UTC by compleatang

There appears to be usage and no major problems with the oauth-proxy chart. Therefore, am recommending graduation to stable repository.

2018-02-01 15:38 UTC, mattfarina commented
@compleatang thanks for looking to promote this to stable. We recently documented the process to do so. Could you make sure this PR meets with the guidelines at https://github.com/kubernetes/charts/blob/master/PROCESSES.md#promoting-a-chart-from-incubator-to-stable

2018-02-02 17:15 UTC, compleatang commented
@mattfarina sorry I missed those guidelines. Should comply now.

2018-02-07 14:55 UTC, mattfarina commented
/ok-to-test

2018-02-08 14:43 UTC, compleatang commented
No sure what the Tide Pool test is or when it would fire, but the other tests appear to be good and this should be ready to merge which would then unblock #3593

2018-02-20 18:43 UTC, emmanuel commented
I opened a PR against the incubator chart to rename it to align to the upstream project's name (`oauth-proxy` -> `oauth2-proxy`). In my estimation, it is valuable to match the upstream name. I propose making the jump to stable as `oauth2-proxy` (bundling together the promotion and rename). 

What do you think @compleatang and @mattfarina ?

2018-02-22 00:31 UTC, compleatang commented
@emmanuel that makes sense to me. Do want to PR your changes into this one?

2018-02-22 18:07 UTC, emmanuel commented
I don't know how to 'PR [my] changes into this one' (or I don't understand the suggestion). If you mean adding my changes (rename) to this PR, I don't know how to do it. If you mean something else, I didn't understand.

Given that, if I don't hear anything today, I'll open a new PR that promotes the chart to stable with the name `oauth2-proxy`. That will be the content of this PR, with the name changed to `oauth2-proxy`.

2018-02-23 03:57 UTC, unguiculus commented
Renaming means we have to copy the chart and deprecated the old one. We certainly don't want to do this twice. Thus, we should copy/rename to stable in one go in this PR.

@emmanuel: You could create a PR against @compleatang's branch or he just does it himself.

2018-02-23 10:07 UTC, jeff-knurek commented
@emmanuel the process that you probably want to take is:
* create a fork of @compleatang's charts repo (that he forked from here)
* checkout the `oauth-proxy-to-stable` branch of your new fork
* apply your renaming changes to it, and push to your fork
* open a PR with @compleatang 

----
another strategy you could do, but is less ideal, is to pull @compleatang's changes into your existing fork, then add your rename changes, and then create a new PR here that has both the rename and the move to stable, which would make this PR obsolete - as I said, less ideal, but you can find more info on how to do it here: https://stackoverflow.com/a/6022366

----
the last strategy, is hope that @compleatang likes the renaming so much that he does the work of applying the changes to this PR

2018-02-23 14:53 UTC, compleatang commented
@emmanuel sorry for the quick response as I was on the road the last couple of days. I've just manually applied your changes. This PR should now cover the same ground as #3755 . I've renamed the PR to reflect the additional renaming.

2018-02-23 18:56 UTC, unguiculus requested changes
* Please add a deprecation note to the readme of the deprecated chart.
* Please checkout the initial chart you get with `helm create` using Helm 2.8+ and compare things. In particular, I'd like you to update the `_helpers.tpl`.

2018-02-23 18:56 UTC, unguiculus commented on stable/oauth2-proxy/templates/deployment.yaml
> +          - containerPort: {{ .Values.service.internalPort }}
Don't make the port configurable. Changing it would break things. Give the port a name and refer to it by name from the service.

2018-02-23 19:13 UTC, emmanuel commented
@jeff-knurek thanks for spelling that out; makes total sense and I'm a little disappointed that I didn't understand in the first go. 

@compleatang thanks for your original suggestion, and sorry for being dense and not understanding. And thanks for applying the changes yourself. 

Yay open source!

2018-03-13 16:25 UTC, jeff-knurek commented
any update on this PR?

2018-03-15 14:31 UTC, compleatang commented
@unguiculus thanks for the review. I've made the requested port non-configurable, updated the helpers and generally put the chart inline with 2.8 create best practices (I hope I caught them all).

2018-03-16 07:43 UTC, unguiculus approved these changes

2018-03-16 07:43 UTC, unguiculus commented
/lgtm

2018-03-16 07:44 UTC, merged