[stable/consul] Clustering improvements
helm/charts pull request #3508
Opened 2018-02-01 03:54 UTC by coreypobrien

This avoids a few problems I experienced with new pods joining existing clusters, especially after a leader dies and is replaced.

The first is the issue essentially the one mentioned here: https://github.com/hashicorp/consul/issues/719#issuecomment-75183631
Because consul is saving the cluster key to the persistent volume, the replaced node can come up with the old key after a key rotation happens while it is gone. Using -disable-keyring-file keeps the key in memory and has the new pod re-acquire it from the remaining nodes like any new Pod would.

The second is this issue: https://github.com/hashicorp/consul/issues/2868
By excluding the current node from the list of nodes it should join, we avoid the problem of the node joining itself and using a mismatched key from the rest of the cluster which then prevents it from joining the remaining nodes.

2018-02-02 01:47 UTC, paulczar requested changes
Looks like a great fix, but can you please bump the chart version number?

2018-02-02 14:41 UTC, coreypobrien commented
👍 Bumped. Thanks!

2018-02-09 20:30 UTC, unguiculus commented
/cc @lachie83

2018-02-09 20:30 UTC, unguiculus commented
/ok-to-test

2018-02-18 09:41 UTC, unguiculus commented
/lgtm

2018-02-18 09:47 UTC, merged