[stable/grafana] Support Provisioner Configuration
helm/charts pull request #3514
Opened 2018-02-01 14:05 UTC by BugRoger

This PR extends the `stable/grafana` chart to allow for outside configuration of provisioners. 

With Grafana 5 it will be possible to manage datasources and dashboards using provisioners.  Adding a provisioner is done by adding one or more yaml configuration files in the `provisioning/datasources` and `provisioning/dashboards` directory. See also: http://docs.grafana.org/administration/provisioning/

For datasources the file can contain a list of datasources that will be added or updated during start-up. If the datasource already exists, Grafana will update it to match the configuration file. 

For dashboards the files contain the configuration for provisioning from external resources. It currently only support reading dashboards from file but more provisioners are in the works.

This functionality partly clashes with the jobs provided by this Helm chart. In order to support both Grafana 4/5 in the same chart, I think, it is a sensible approach to allow for both provisioning mechanisms. In the absence of more sophisticated provisioners (that allow the decoupling from Helm and dashboards) it is anyway required to load the dashboard from the filesystem and inject it using the existing mechanism.

2018-02-01 15:05 UTC, BugRoger commented
/assign @linki

2018-02-04 11:42 UTC, BugRoger commented
/assign @prydonius

2018-02-04 11:43 UTC, BugRoger commented
/unassign @linki

2018-02-16 22:04 UTC, NicolasT commented
Looking forward to this to land. Too bad though that creating a default datasource for e.g. Prometheus deployed by the stable Chart (in a Chart having both Grafana and Prometheus as requirements) still won't be possible using this approach, because its service name/DNS entry depends on the Helm release name 😞

2018-02-19 15:11 UTC, monotek commented
@BugRoger 
Looking forward to see this merged. Would you mind to fix the the merge conflict?

2018-02-19 19:35 UTC, BugRoger commented
Fixed. It was just some other change increasing the version

2018-02-19 19:37 UTC, BugRoger commented
/assign @prydonius

2018-03-01 12:38 UTC, pesimon commented
Can confirm that it works like a charm and grafana 5.0.0 was just released
https://github.com/grafana/grafana/releases

2018-03-01 16:48 UTC, unguiculus requested changes

2018-03-01 16:48 UTC, unguiculus commented on stable/grafana/templates/deployment.yaml
> +              mountPath: {{ default "/var/lib/grafana/provisioning" .Values.server.provisioningLocalPath }}/datasources
Don't use the `default` function. Defaults come from `values.yaml` anyways which is better. Apply to all your changes.

2018-03-02 16:55 UTC, jdumars commented
/ok-to-test

2018-03-02 17:38 UTC, monotek commented
/retest

2018-03-05 14:08 UTC, jpds commented
This merge proposal doesn't actually change the default version to `5.0.0` (relevant issue: #3937).

2018-03-08 16:59 UTC, sstarcher commented
This should bump the version to 5.0.1 and add the AppVersion to the charts.yaml

2018-03-09 20:55 UTC, unguiculus requested changes

2018-03-09 20:55 UTC, unguiculus commented on stable/grafana/templates/deployment.yaml
> +              mountPath: {{ default "/var/lib/grafana/provisioning" .Values.server.provisioningLocalPath }}/datasources
I figured this is common practice in the chart. So, let's leave it for now. Would be cool to get that fixed in a separate PR.

2018-03-09 20:55 UTC, unguiculus approved these changes

2018-03-22 10:51 UTC, sstarcher commented
@BugRoger could you fix the linting issues from the circleci build

2018-03-22 22:54 UTC, richerve commented
@BugRoger are you still working on this, if not I can help

2018-03-23 09:06 UTC, richerve commented
In my opinion is better to bump the minor version and remove at least the support to configure datasources using the Job, it is a hack that is difficult to maintain and not needed anymore. In general the dashboards Job will also not be needed but I think is handy to have the functionality to import remote dashboards.

About bumping the minor version (or major) of the Chart, Grafana is not a project that has Long Term Support releases so keeping a Chart that is compatible with version 4.6.x and another compatible with >= 5 is not a big issue I think, eventually the Chart versions compatible with Grafana <= 4 will not be updated anymore.

I want to use this Chart on cores/kube-prometheus "meta Chart", they maintain what is basically a copy of the stable Chart but adding *grafana-watcher* that essentially serves the same purpose as the Jobs here, both cases are basically hacks that with Grafana >= 5 are not required.

2018-03-23 14:38 UTC, BugRoger commented
Fixed the linter nitpicks. Bumped the version. Rebased on master.

2018-03-28 09:24 UTC, richerve commented
Any way to move this forward?

2018-03-28 15:50 UTC, monotek commented
Please update to the newest Grafana 5.0.4 Docker image as the older images don't work with Kubernetes 1.7.14, 1.8.9, or 1.9.4.

See: https://github.com/grafana/grafana-docker/issues/140

2018-03-28 18:53 UTC, BugRoger commented
Rebased. Updated Image to 5.0.4. Added `appVersion` to make Linter happy. Tests are green.

2018-03-29 21:48 UTC, richerve commented
@BugRoger, sadly again conflicting files. I think this should be coordinated with someone that can merge, do the fix and immediately apply it. I'm waiting for this PR to be merged to work on the integration in https://github.com/coreos/kube-prometheus

2018-03-30 18:52 UTC, knopkodav commented
The same issue on 1.9.6-gke.0

2018-04-04 08:14 UTC, matthope commented
How does this compare to #4541  ?

2018-04-04 10:01 UTC, richerve commented
@matthope In concept both are the same in approach are different, this PR include changes to support the new Grafana >= 5 config but also maintains backward compatibility. The PR on #4541 removes all backwards compatibility.

@BugRoger friendly ping about updating the branch.

2018-04-05 14:07 UTC, rtluckie commented
please check out #4713 before merging.

2018-04-09 12:27 UTC, BugRoger commented
It seems i can't fix this. There's a deadlock between the different checks.

The linter requires me to set the version to version in `chart.yaml` to `0.8.5`. This causes a conflict against master. That fails the e2e tests. 

I can either resolve the conflict or fix the version.

2018-04-09 12:32 UTC, sstarcher commented
master is already at 0.8.5.  You need to rebase and bump it to 0.8.6

2018-04-09 16:03 UTC, BugRoger commented
Ah, rebased and bumped the version again....

2018-04-10 15:21 UTC, unguiculus commented
/hold

2018-04-10 15:21 UTC, unguiculus commented
I'm inclined to close this in favor of #4713.

2018-04-10 15:36 UTC, sstarcher commented
@unguiculus if #4713 is merged it would make this PR no longer needed since #4713 is such a large overhaul and simplification.

I have not tested #4713, but the changes themselves are heading in a good direction.

2018-04-10 17:27 UTC, unguiculus commented
Closing in favor of #4713. Thanks @BugRoger.

2018-04-10 17:27 UTC, closed without merging