Create:  drone chart
helm/charts pull request #353
Opened 2017-01-02 19:48 UTC by ekozan

WIP : 

For drone Owner review 

Todo :
- add checks for correct env setup
- add readme 
- check source

2017-01-02 22:01 UTC, ekozan commented
ping @gtaylor

2017-01-03 15:21 UTC, prydonius commented
@k8s-bot ok to test

2017-01-04 00:04 UTC, gtaylor commented
I haven't forgotten about this! Time is scarce right now, but I'll take a look as soon as I can.

2017-01-04 00:24 UTC, naveensrinivasan commented on incubator/drone/README.md
> +- PV provisioner support in the underlying infrastructure
The PV is a Prerequisite only if we use the local `sqllite` ,if not it isn't. Do we want to add that clause?

2017-01-04 00:28 UTC, naveensrinivasan commented on incubator/drone/Chart.yaml
> +- http://drone.io
It should be `https` https://drone.io/

2017-01-04 00:38 UTC, naveensrinivasan commented on incubator/drone/templates/configmap.yaml
> +  # DB instances if you'd like: http://readme.drone.io/0.5/manage/database/
The above link is dead and the  correct URL is http://readme.drone.io/admin/database-engines/

2017-01-04 00:38 UTC, naveensrinivasan commented on incubator/drone/templates/configmap.yaml
> +# See http://readme.drone.io/0.5/manage/server/ for possible values here.
The same applies over here also http://readme.drone.io/admin/setup-github/

2017-01-04 00:38 UTC, naveensrinivasan commented on incubator/drone/templates/svc-server.yaml
> +    port: 443
Do we assume the SSL certificates are already setup for the https?

2017-01-04 00:40 UTC, naveensrinivasan commented on incubator/drone/values.yaml
> +    github:
IMHO there should be reference github http://readme.drone.io/admin/setup-github/ because lots of folks would likely use that section.

2017-01-04 00:53 UTC, ekozan commented
@naveensrinivasan thanks for the review I'll address all comments tomorrow

2017-01-04 23:50 UTC, viglesiasce commented
I tried installing this one but was unable get it running out of the box. The server pod is crashing with `time="2017-01-04T23:48:50Z" level=fatal msg="version control system not configured"` but the NOTES.txt did not mention anything about how to set that or that it is a hard dependency. Check out the ghost and gitlab-ce charts to see an example of the behavior of a chart that requires values to be set but cannot provide sane ones by default.

2017-01-05 19:29 UTC, ekozan commented
Yeah you need to setup an remote I'll make the checks like gitlab

2017-01-23 19:25 UTC, viglesiasce commented
I was able to get the chart installed but not access it over the https port that is exposed.

2017-01-26 07:12 UTC, viglesiasce commented
Fixed the issue with the HTTP port and was able to test with GH without issue.

2017-01-26 19:59 UTC, ekozan commented
Thx Vigle I have no time for the moment if you want more change i can adresse it this weekend :)

2017-02-01 14:52 UTC, mandrean requested changes

2017-02-01 14:52 UTC, mandrean commented on incubator/drone/values.yaml
> +    requests:
These are not actually used anywhere?

2017-02-01 14:52 UTC, mandrean commented on incubator/drone/templates/deployment-agent.yaml
> +            cpu: 100m
See https://github.com/kubernetes/charts/pull/353/files/741f2f3885f6509db89c7b4eed8815ac622dbb34#r98908835

2017-02-01 14:56 UTC, mandrean commented
Also, Drone.io (now defunct) is generally regarded as the hosted service while the open-source alternative is just simply "drone". They shared some similarities on the surface but used totally different code-bases.

I think all references to Drone**.io** should be removed from this chart to not cause confusion.

2017-02-17 08:49 UTC, BodySplash commented
Sorry to bother, but shouldn't oauth secrets be saved in secrets instead of configmap ? 

2017-02-21 21:43 UTC, clintberry commented
Is mounting the host's docker engine the right way to do this? That means drone will spin up docker containers directly on the host and Kubernetes won't know about any of the resource usage. This is currently how we are using it at my company, but we make sure it is only running on a non-production environment. I guess there isn't a better way just yet... :-(

2017-02-22 09:49 UTC, BodySplash commented
@clintberry there is an [issue](https://github.com/drone/drone/issues/1815) on the drone project discussing how kubernetes could be used as the runtime engine for drone. Not a simple matter, but it would be awesome.

2017-03-01 22:24 UTC, jackzampolin commented
Would love to see this merged!

2017-03-02 06:25 UTC, ekozan commented
drone 0.5 is not stable for the moment, it's ok for merge ?

2017-03-02 06:41 UTC, clintberry commented
We have it running in production on kubernetes for over 50 repos. Running
great.
On Wed, Mar 1, 2017 at 11:25 PM Maxime Franck <notifications@github.com>
wrote:

> drone 0.5 is not stable for the moment, it's ok for merge ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/charts/pull/353#issuecomment-283567879>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAcWxttYIJv8k1SsgDSCxFoiMs636A1Yks5rhmDLgaJpZM4LZLuU>
> .
>

2017-03-02 07:17 UTC, ekozan commented
well, i'll review all my code corect 1 or 2 things this night and remove wip tag ;)

2017-03-09 06:57 UTC, seanknox requested changes

2017-03-09 06:57 UTC, seanknox commented on incubator/drone/templates/NOTES.txt
> +        Watch the status with: 'kubectl get svc -w {{ template "fullname" . }}'
Hey @ekozan, the server service name should be: `{{ template "fullname" . }}-server`.

2017-03-09 06:57 UTC, seanknox commented on incubator/drone/templates/NOTES.txt
> +  export SERVICE_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} {{ template "fullname" . }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
Same here: change the service name to `{{ template "fullname" . }}-server`

2017-03-16 15:32 UTC, bacongobbler requested changes

2017-03-16 15:32 UTC, bacongobbler commented on incubator/drone/README.md
> +Alternatively, a YAML file that specifies the values for the parameters can be provided while installing the chart. For example,
this is all very basic helm usage that the tutorials go over. I don't think this should be documented here.

2017-03-16 15:32 UTC, bacongobbler commented on incubator/drone/templates/_helpers.tpl
> +{{- printf "%s-%s" .Release.Name $name | trunc 24 -}}
this should be 63 characters.

2017-03-16 15:32 UTC, bacongobbler commented on incubator/drone/templates/_helpers.tpl
> +{{- default .Chart.Name .Values.nameOverride | trunc 24 -}}
this should be 63 characters.

2017-03-16 15:32 UTC, bacongobbler commented on incubator/drone/templates/configmap.yaml
> +  server.debug.is.enabled: "true"
this should be configurable.

2017-03-16 15:32 UTC, bacongobbler commented on incubator/drone/templates/configmap.yaml
> +  agent.debug.is.enabled: "true"
this should be configurable.

2017-03-16 15:32 UTC, bacongobbler commented on incubator/drone/templates/deployment-agent.yaml
> +            path: /var/run/docker.sock
there's a bug in GKE currently with mounting in the host docker volume with drone: http://discourse.drone.io/t/drone-on-kubernetes-builds-fail-with-docker-errors/162

I would propose that instead we run a privileged container running docker-in-docker as a sidecar container in the pod, which then the agent is configured to point at that engine.

2017-03-16 15:32 UTC, bacongobbler commented on incubator/drone/values.yaml
> +image: drone/drone:0.5
it looks like drone 0.6 was just released a few hours ago? https://hub.docker.com/r/drone/drone/tags/

2017-03-16 15:32 UTC, bacongobbler commented on incubator/drone/values.yaml
> +  defaultCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVtekNDQTRPZ0F3SUJBZ0lKQUpBR1FsTW1DMGt5TUEwR0NTcUdTSWIzRFFFQkJRVUFNSUdQTVFzd0NRWUQKVlFRR0V3SlZVekVSTUE4R0ExVUVDQk1JUTI5c2IzSmhaRzh4RURBT0JnTlZC
are these default cert/keys documented somewhere? I'd argue that we should not be rolling "default" SSL unless it's fetched directly using something like kube-lego.

2017-03-16 16:39 UTC, bacongobbler commented on incubator/drone/values.yaml
> +image: drone/drone:0.5
nvm: https://twitter.com/bacongobbler/status/842397479400218624

2017-03-16 17:19 UTC, bacongobbler commented
@ekozan do you still have time to continue working on this chart? If not I'd be more than happy to take the helm (ha) and bring this over the finish line.

2017-03-17 19:57 UTC, bacongobbler commented
(/me grabs a puppet to speak on behalf of @ekozan)

> why yes, @bacongobbler, I am way too busy to continue working on this PR. Please feel free to take it and push it forward

Why thank you, @ekozan! ❤️ 

I'll rebase this PR off the reviewer's comments and start working on it over the weekend.

2017-03-18 15:02 UTC, ekozan commented
@bacongobbler thx man i'm soo sorry no time atm :/

2017-03-20 17:42 UTC, bacongobbler commented
efforts have been continued over in #821.

2017-03-20 18:51 UTC, closed without merging