[chartmuseum] upgrade and add new env var for anonymous GET operation…
helm/charts pull request #3550
Opened 2018-02-04 15:43 UTC by rawlingsj

…s, when basic auth enabled

- Upgrades to the latest chartmuseum v0.2.8
- Include default value for a new env var `AUTH_ANNONYMOUS_GET` so it's disabled OOTB

2018-02-04 16:14 UTC, jdolitsky requested changes

2018-02-04 16:14 UTC, jdolitsky commented on incubator/chartmuseum/values.yaml
> +    AUTH_ANNONYMOUS_GET: false
Misspelling

2018-02-05 09:35 UTC, rawlingsj commented on incubator/chartmuseum/values.yaml
> +    AUTH_ANNONYMOUS_GET: false
doh - corrected, thanks!

2018-02-06 01:41 UTC, jdolitsky commented
/lgtm

2018-02-06 02:13 UTC, jdolitsky commented
/ok-to-test

2018-02-06 02:16 UTC, merged