Add stable/unbound
helm/charts pull request #3564
Opened 2018-02-05 23:05 UTC by Markbnj

Unbound is a fast caching dns resolver that we use in production kubernetes clusters to provide upstream resolution of private zones through kube-dns. This chart uses an auto-built docker image based on alpine:latest with unbound 1.6.7, as well as bash and bind-tools. It uses googlecontainer/exechealthz as a side car to perform health checks against the unbound server on localhost (allowing the default configuration of this chart to run unbound with restricted network access). Uncompressed image size is ~20MB. Submitted into stable because I believe it meets all technical requirements.

2018-02-24 11:32 UTC, unguiculus requested changes
Thanks you for your PR. I'd like you to read our review guidelines and apply best practices.

https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Please compare with what you get with `helm create` using Helm 2.8+ and update accordingly. Thanks.

2018-03-02 16:52 UTC, jdumars commented
/ok-to-test

2018-04-03 15:50 UTC, unguiculus requested changes

2018-04-03 15:50 UTC, unguiculus commented on stable/unbound/templates/deployment.yaml
> +apiVersion: extensions/v1beta1
apps/v1beta2

2018-04-03 15:50 UTC, unguiculus commented on stable/unbound/templates/service.yaml
> +  ports:
Make list indentation level consistent. Since you did not indent lists in other places, don't do it here either.

2018-04-04 06:19 UTC, Markbnj commented on stable/unbound/templates/service.yaml
> +  ports:
Thanks, @unguiculus good catch.

2018-04-04 19:04 UTC, unguiculus approved these changes

2018-04-04 19:04 UTC, unguiculus commented
/lgtm

2018-04-04 19:42 UTC, merged