[stable/kubernetes-dashboard] Add `extraArgs` to `kubernetes-dashboard`
helm/charts pull request #3587
Opened 2018-02-07 00:48 UTC by filoozom

Adds `extraArgs` to `stable/kubernetes-dashboard`.

## Use-case:
I'd like to add `--enable-insecure-login` because I get a certificate from `cert-manager` and set it on Ingress, and don't get the login view without it.

2018-02-07 00:54 UTC, filoozom commented
/assign @mattfarina

2018-02-07 14:27 UTC, mattfarina requested changes
The version of the chart needs to be incremented. See the Chart.yaml file.

2018-02-07 14:27 UTC, mattfarina commented on stable/kubernetes-dashboard/templates/deployment.yaml
> +        {{- end }}
Can you wrap `args` in an if statement to only include the section if there are args.

2018-02-07 14:59 UTC, mattfarina approved these changes

2018-02-07 14:59 UTC, mattfarina commented
cc @kfox1111

/ok-to-test

2018-02-07 15:01 UTC, filoozom commented
Thought I had done a commit for that yesterday after looking at CircleCI, guess I forgot to push it.

I replaced the loop with `{{ toYaml .Values.extraArgs | indent 10 }}` after looking at a few other charts, I think it looks cleaner.

2018-02-07 16:05 UTC, kfox1111 commented
lgtm

2018-02-10 12:19 UTC, unguiculus commented
/lgtm

2018-02-10 12:21 UTC, merged