Add bitcoincashd cryptocurrency chart
helm/charts pull request #3643
Opened 2018-02-09 10:26 UTC by govale

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

2018-02-19 10:29 UTC, govale commented
/assign @sameersbn

2018-03-29 07:08 UTC, govale commented
/retest

2018-03-29 21:43 UTC, unguiculus requested changes

2018-03-29 21:43 UTC, unguiculus commented on incubator/bitcoincashd/README.md
> +`imageTag`                 | `bitcoincashd` release tag.        | `1.0`
image.tag

2018-03-29 21:43 UTC, unguiculus commented on incubator/bitcoincashd/README.md
> +`imagePullPolicy`          | Image pull policy                  | `IfNotPresent`
image.pullPolicy

2018-03-29 21:43 UTC, unguiculus commented on incubator/bitcoincashd/templates/configmap.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
Update `chart` labels: `chart: {{ template "bitcoincashd.chart" . }}`

2018-03-29 21:43 UTC, unguiculus commented
/assign

2018-03-30 06:53 UTC, govale commented on incubator/bitcoincashd/README.md
> +`imageTag`                 | `bitcoincashd` release tag.        | `1.0`
Fixed.

2018-03-30 06:53 UTC, govale commented on incubator/bitcoincashd/README.md
> +`imagePullPolicy`          | Image pull policy                  | `IfNotPresent`
Fixed.

2018-03-30 06:53 UTC, govale commented on incubator/bitcoincashd/templates/configmap.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
Fixed.

2018-03-30 06:54 UTC, govale commented
/assign

2018-03-30 06:55 UTC, govale commented
/assign @unguiculus

2018-04-16 16:01 UTC, unguiculus requested changes

2018-04-16 16:01 UTC, unguiculus commented on incubator/bitcoincashd/templates/deployment.yaml
> +              containerPort: {{ .Values.service.rpcPort }}
It probably doesn't make sense to have these configurable like this. Changing the service ports also changes container ports which is likely to break things. I'd suggest you hard-code container ports.

2018-04-16 16:01 UTC, unguiculus commented on incubator/bitcoincashd/templates/deployment.yaml
> +  {{ toYaml .Values.resources | indent 10 }}
`{{ toYaml .Values.resources | indent 12 }}`

2018-08-08 14:01 UTC, closed without merging