Add initialDelaySeconds and periodSeconds to Logstash livenessProbe, update image
helm/charts pull request #3651
Opened 2018-02-09 12:25 UTC by simt2

This PR adds  initialDelaySeconds and periodSeconds to the livenessProbe of Logstash. Without the delay, the Logstash Pod would be restarted if not started in under 10 seconds. I also updated the image from 6.0.0 to the current 6.2.1.

2018-02-09 12:26 UTC, simt2 commented
/assign @foxish

2018-02-09 20:45 UTC, paulczar approved these changes
LGTM

2018-02-10 12:22 UTC, unguiculus commented
Please add documentation in the readme.

2018-02-10 12:22 UTC, unguiculus commented
cc @rendhalver @jar361 @christian-roggia

2018-02-13 07:45 UTC, simt2 commented
Updated documentation accordingly.

2018-02-13 14:31 UTC, rendhalver commented
This sounds like it will fix a few issues we were seeing.
Do we need to increase the version to get those fixes?
From what I have seen ElasticStack is a very picky with versions in a cluster and updating default version of logstash may break peoples current setups.

2018-02-13 19:00 UTC, bdashrad requested changes

2018-02-13 19:00 UTC, bdashrad commented on incubator/logstash/templates/deployment.yaml
> +              periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
`initialDelaySeconds` and `periodSeconds` are properties of `livenessProbe` not `tcpSocket`

should be:
```
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
```

2018-02-13 19:06 UTC, bdashrad commented on incubator/logstash/templates/deployment.yaml
> +              periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
before the change:

```
~/.../charts/incubator on remotes/simt2/logstash
$ helm upgrade test-logstash ./logstash
Error: UPGRADE FAILED: error validating "": error validating data: [found invalid field periodSeconds for v1.TCPSocketAction, found invalid field initialDelaySeconds for v1.TCPSocketAction]
~/.../charts/incubator on remotes/simt2/logstash
$ helm upgrade test-logstash ./logstash
Error: UPGRADE FAILED: error validating "": error validating data: [found invalid field initialDelaySeconds for v1.TCPSocketAction, found invalid field periodSeconds for v1.TCPSocketAction]
```

2018-02-13 19:21 UTC, bdashrad commented
Should probably add delay seconds for `readinessProbe` too, I'm still seeing failures at startup

2018-02-14 08:50 UTC, simt2 commented
@bdashrad thank you very much for the PR, I really don't know why this was indented wrong. But I need to squash your commit later because the CLA check fails now. 

@rendhalver When people are picky with their versions, they should imo set the `image.tag` variable.

2018-02-14 12:46 UTC, rendhalver commented
@simt2 Not the point. the point is if someone is running an Elasticsearch cluster with version 6.1.1 and this code upgrades their logstash to 6.2.1 it will stop working. This isn't very good behaviour on our part.

2018-02-14 13:05 UTC, bdashrad commented
@simt2 i signed the CLA now, so that should be all set.

@rendhalver According to the [compatibility matrix](https://www.elastic.co/support/matrix#matrix_compatibility) this version of logstash is still fully compatible with elasticsearch 6.0.x. Not sure if that changes your opinion on the version or not.

2018-02-14 14:22 UTC, rendhalver commented
Thanks @bdashrad. That's interesting. We have been having occasional issues if logstash wasn't the same version.
I guess if ES says it compatible it should work.

2018-02-14 14:45 UTC, rendhalver commented
We just tested this locally it all looks good.
Logstash used to fail to startup properly when deployed with elastic-stack, This time it worked straight off.
Thank you!

2018-02-15 06:47 UTC, simt2 commented
Thank you @bdashrad , that makes things easier. @rendhalver that was kind of my point, people should make a habit of setting their image tags manually. I don't see how we could ever upgrade the default Logstash version from your point of view. 

@unguiculus added documentation, please review again.

2018-02-18 11:05 UTC, unguiculus commented
/ok-to-test

2018-02-20 01:21 UTC, unguiculus commented
/lgtm

2018-02-20 01:29 UTC, merged