Adds dnsPolicy as an option to nginx-ingress-controller in values.yaml
helm/charts pull request #3663
Opened 2018-02-10 02:35 UTC by juliohm1978

Following up #3656, which proposes a new value in values.yaml to allow nginx controller to run with host network and still be able to resolve names inside the k8s cluster.

2018-02-10 02:40 UTC, juliohm1978 commented
/assign @seanknox

2018-02-20 05:54 UTC, unguiculus requested changes

2018-02-20 05:54 UTC, unguiculus commented on stable/nginx-ingress/templates/controller-daemonset.yaml
> +      dnsPolicy: {{ .Values.controller.dnsPolicy | default "ClusterFirst" }}
Please add the default to `values.yaml` instead of using the `default` function.

2018-02-20 05:54 UTC, unguiculus commented on stable/nginx-ingress/templates/controller-deployment.yaml
> +      dnsPolicy: {{ .Values.controller.dnsPolicy | default "ClusterFirst" }}
Please add the default to `values.yaml` instead of using the `default` function.

2018-02-21 04:19 UTC, unguiculus approved these changes

2018-02-21 04:19 UTC, unguiculus commented
/ok-to-test

2018-02-21 04:36 UTC, unguiculus commented
/lgtm

2018-02-21 04:41 UTC, merged

2018-02-23 00:53 UTC, juliohm1978 commented
Out of curiosity, is it safe to delete the branch/repository after the PR is approved?