Add a Quassel IRC Helm Chart
helm/charts pull request #3680
Opened 2018-02-10 15:06 UTC by kiall

Add a Quassel IRC Helm Chart

Quassel IRC is a modern, cross-platform, distributed IRC client, meaning that one (or multiple) client(s) can attach to and detach from a central core.

Quassel Homepage: https://quassel-irc.org/

2018-02-22 18:15 UTC, kiall commented
/assign @seanknox

2018-02-22 18:16 UTC, kiall commented
Assigning seanknox as requested by the bot :)

2018-02-23 03:47 UTC, unguiculus requested changes
Thanks for the PR. Looks really good. I'd suggest you move it to stable directly.

2018-02-23 03:47 UTC, unguiculus commented on incubator/quassel/Chart.yaml
> +- name: Kiall Mac Innes
Please use Github username.

2018-02-23 20:07 UTC, kiall commented on incubator/quassel/Chart.yaml
> +- name: Kiall Mac Innes
Done

2018-02-23 20:07 UTC, kiall commented
> Thanks for the PR. Looks really good. I'd suggest you move it to stable directly.

Done.

2018-02-23 20:09 UTC, kiall commented
> EDIT: Let me update the readme references. Derp.

Done.

2018-02-24 10:02 UTC, unguiculus approved these changes

2018-02-24 10:02 UTC, unguiculus commented
/ok-to-test

2018-02-24 10:22 UTC, unguiculus commented
/lgtm

2018-02-24 10:22 UTC, merged