[GoCD Helm Chart] Minor changes in defaults, fixes in PVC.
helm/charts pull request #3711
Opened 2018-02-13 05:38 UTC by varshavaradarajan

* Have a server only deployment by default. GoCD agents can be deployed on the cluster using agent.replicaCount.
* Enable ingress by default.
* Enable dynamic provisioning of persistence on the server through the default storage class.
* Change the default failure threshold to 10, reduce initial delay for liveness and readiness probe.
* Minor fixes to the README.
* Bump up version to 0.1.1

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

2018-02-14 14:36 UTC, varshavaradarajan commented
/assign @foxish

2018-02-23 05:17 UTC, varshavaradarajan commented
/assign @unguiculus

2018-02-23 19:11 UTC, unguiculus requested changes
Thank you for this excellent contribution. Please follow our RBAC best practices.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

2018-02-24 02:23 UTC, varshavaradarajan commented
@unguiculus - we plan on announcing the GoCD helm chart very soon. Do you think it will be alright if I make the rbac changes, bump up the appVersion and move the chart to stable by next Friday in the same PR?

2018-02-24 09:41 UTC, unguiculus commented
@varshavaradarajan Please create a separate PR for the move to stable. Assign it to me and I'll try and get it through quickly. Please note that you'll have to copy that chart to stable and deprecate the one in incubator.

See https://github.com/kubernetes/charts/blob/master/PROCESSES.md#deprecating-a-chart

2018-02-26 05:38 UTC, varshavaradarajan commented
@unguiculus - Thank you for your prompt response. I have updated this PR with the changes you asked for. I'll have another PR ready for moving the GoCD helm chart to stable.

2018-02-26 21:20 UTC, unguiculus requested changes

2018-02-26 21:20 UTC, unguiculus commented on incubator/gocd/README.md
> +| `serviceAccount.name`                         | Name of the service account.                                                        | `gocd template`      |
The default is empty.

2018-02-27 03:01 UTC, varshavaradarajan commented on incubator/gocd/README.md
> +| `serviceAccount.name`                         | Name of the service account.                                                        | `gocd template`      |
Fixed.

2018-02-27 20:56 UTC, unguiculus commented
/ok-to-test

2018-02-27 21:01 UTC, unguiculus approved these changes

2018-02-27 21:01 UTC, unguiculus commented
/lgtm

2018-02-27 21:02 UTC, merged