Sentry kubernetes
helm/charts pull request #3748
Opened 2018-02-16 09:20 UTC by gianrubio

This PR is a review from the closed one #2708, I did all the changes requested by @unguiculus.

2018-02-16 09:20 UTC, gianrubio commented
/assign @unguiculus

2018-02-18 11:08 UTC, unguiculus requested changes
Our RBAC best practices have been revised. Please update accordingly.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

2018-02-19 18:24 UTC, gianrubio commented
@unguiculus done

2018-02-20 01:42 UTC, unguiculus requested changes
Please use a consistent list indentation style. I'd suggest you always indent two spaces. Currently, it's a mixture of zero and two spaces.

2018-02-20 01:42 UTC, unguiculus commented on incubator/sentry-kubernetes/Chart.yaml
> +version: 0.1.0
Add `appVersion` and `icon`, `sources`, `keywords`, etc. if possible.

2018-02-20 01:42 UTC, unguiculus commented on incubator/sentry-kubernetes/templates/_helpers.tpl
> +{{- define "sentry-kubernetes.fullname" -}}
Templates have been revised. Please have a look at the `_helpers.tpl` you get with `helm create` using Helm 2.8+. Please update.

2018-02-20 01:42 UTC, unguiculus commented on incubator/sentry-kubernetes/templates/deployment.yaml
> +apiVersion: extensions/v1beta1
`apps/v1beta2`

2018-02-20 01:42 UTC, unguiculus commented on incubator/sentry-kubernetes/templates/deployment.yaml
> +metadata:
Indent two spaces.

2018-02-20 01:42 UTC, unguiculus commented on incubator/sentry-kubernetes/templates/secret.yaml
> +metadata:
Indent two spaces.

2018-02-20 01:42 UTC, unguiculus commented on incubator/sentry-kubernetes/templates/serviceaccount.yaml
> +metadata:
Indent two spaces.

2018-02-23 13:02 UTC, gianrubio commented
@unguiculus your requested changes are done

2018-02-23 19:24 UTC, unguiculus requested changes

2018-02-23 19:24 UTC, unguiculus commented on incubator/sentry-kubernetes/templates/deployment.yaml
> +apiVersion: extensions/v1beta2
`apps/v1beta2`

2018-02-23 19:24 UTC, unguiculus commented
/ok-to-test

2018-02-24 09:13 UTC, gianrubio commented on incubator/sentry-kubernetes/templates/deployment.yaml
> +apiVersion: extensions/v1beta2
sorry, fixed

2018-02-24 09:21 UTC, unguiculus approved these changes

2018-02-24 09:22 UTC, unguiculus commented
/lgtm

2018-02-24 09:22 UTC, merged