fixed Prometheus Ingress path rules
helm/charts pull request #375
Opened 2017-01-09 14:23 UTC by ged15

Currently, the Ingress created only matches the `/` path. That means, that any other path (`/graph` for example) is not matched.

2017-01-10 02:45 UTC, viglesiasce requested changes
Please bump the chart version (Chart.yaml)

cc @mgoodness

2017-01-10 08:40 UTC, ged15 commented
@viglesiasce done!
I am a bit weary of the current chart versioning. It was trying to be in sync with Prometheus versioning as far as I understand, but now it is v1.4.2 already and latest version of Prometheus is 1.4.1. This could confuse people I think. Could it be an idea to bump the version to 2?
cc @mgoodness

2017-01-10 15:06 UTC, mgoodness commented
@ged15 I kick myself for trying to sync the chart's version with Prometheus's. But the damage is done. Bumping to 2.0 is likely the best way forward.

Regarding the Ingress path, what controller do you use? I'm on the "official" nginx 0.8.3, and everything works fine. As far as I can tell from the [API reference](http://kubernetes.io/docs/federation/api-reference/extensions/v1beta1/definitions/#_v1beta1_httpingressrulevalue), using `/` should be effectively the same as not specifying a path at all.

2017-01-10 15:42 UTC, ged15 commented
I'm using the GCE controller (which is the default and ships on GKE). It is possible that it does not follow standards or has a bug. That being said, if the proposed configuration works for the nginx controller, then it would make sense to merge this PR as it makes Ingress work on GKE as well.

2017-01-10 15:59 UTC, mgoodness commented
Omitting the path works with the nginx controller (though it does issue a warning: `Ingress rule...contains no path definition. Assuming /`). I agree that the PR makes sense.

Should probably mention the discrepancy to the upstream projects.

2017-01-13 01:27 UTC, mgoodness commented
@ged15 Rev to v2 and I'll sign off :)

2017-01-13 08:26 UTC, ged15 commented
@mgoodness done!

2017-01-13 18:22 UTC, mgoodness commented
Confirmed (still) working. LGTM!

2017-01-13 18:24 UTC, viglesiasce approved these changes

2017-01-13 20:34 UTC, merged