allow to define service type in Kafka/ZK
helm/charts pull request #3762
Opened 2018-02-19 08:03 UTC by stas2k

These changes allow to define type of exposed Kafka/ZooKeeper services.

2018-02-19 08:15 UTC, stas2k commented
/assign @seanknox

2018-02-19 15:18 UTC, josdotso commented
related: https://github.com/kubernetes/charts/pull/3754

2018-02-19 15:23 UTC, stas2k commented
@josdotso thanks, I like your Kafka solution

2018-03-02 16:45 UTC, jdumars commented
/ok-to-test

2018-03-05 15:04 UTC, stas2k commented
/retest

2018-03-08 17:33 UTC, unguiculus requested changes

2018-03-08 17:33 UTC, unguiculus commented on incubator/kafka/templates/service-brokers.yaml
> +  {{if eq .Values.serviceType "LoadBalancer"}}
For consistent formatting, please add a space after `{{` and before `}}`.

2018-03-08 17:33 UTC, unguiculus commented
/assign

2018-04-11 22:04 UTC, josdotso commented
related: https://github.com/kubernetes/charts/pull/4931

2018-04-13 20:31 UTC, unguiculus commented
/hold

2018-04-13 20:32 UTC, unguiculus commented
Please consider splitting this up into two PRs. Also, #4931 will likely make it in.

2018-05-11 07:38 UTC, unguiculus commented
@stas2k Are going to update the PR? Otherwise, please close it. Thanks.

2018-08-24 18:15 UTC, closed without merging