Setting up redis without password
helm/charts pull request #378
Opened 2017-01-10 10:56 UTC by ged15

2017-01-10 20:57 UTC, lachie83 commented
Thanks for the contrib @ged15. Just a quick question on this one. Should we make having a password default with the ability to disable? cc @prydonius @viglesiasce

2017-01-10 22:35 UTC, ged15 commented
I would say the default should be a password-less setup. Based on my experience, Redis is not exposed outside the private network thus authentication is unnecessary and the need for a password is a special case.

2017-01-11 23:30 UTC, prydonius commented
It is quite common to run Redis without authentication when not exposed externally, and reading through https://redis.io/topics/security it seems like they strongly suggest only exposing Redis within trusted environments (rather than making it externally available and enabling authentication).

Given the chart does not expose Redis externally by default, a password-less setup should be okay and is probably more in line with what people would expect out-of-the-box.

2017-01-17 02:11 UTC, miracle2k commented
Ran into this; I actually very much like that it has the ability to generate a password. I'd like to see that ability persist. It would suggest that there should be the ability to disable this though, possible by setting the password to an empty string.

2017-01-19 11:14 UTC, ged15 commented
If you ask me, generating passwords can be done using a script by the operations person that is installing this and there is no need to keep this feature in the charts. The way I see it, generating random passwords has minimal utility (Redis is used without a password usually) and can be easily substituted by an outside tool.
That being said, what do the maintainers think? If we decide to keep this feature, I can modify the chart to generate the password by default adding a feature to disable authentication.
@lachie83?

2017-01-19 19:17 UTC, viglesiasce commented
I would like us to keep the current default and allow users to set a value that disables authentication.

2017-01-20 13:09 UTC, miracle2k commented
It's actually not easy to manually set a redis password, because it seems the image only accepts the password on the first start, according to the docs.

It's true that redis is frequently used without a password, including by me, but I don't see how this is more secure than running an internal MySQL without a password. I like that the image encourages me to use one by making that easy/the default.

2017-02-03 00:56 UTC, prydonius commented
@ged15 would you be willing to update this PR to add an option for disabling the password, but keeping the current default?

2017-02-03 08:36 UTC, ged15 commented
@prydonius yes. Will try to take a look at this during the weekend.

2017-02-06 17:17 UTC, lachie83 commented
@ged15 This also needs a rebase.

2017-02-11 00:11 UTC, prydonius commented
Moving to Milestone 2

2017-02-13 17:45 UTC, lachie83 commented
@k8s-bot ok to test

2017-02-13 17:48 UTC, lachie83 commented
Rebased

2017-02-13 18:28 UTC, lachie83 requested changes

2017-02-13 18:28 UTC, lachie83 commented on stable/redis/values.yaml
>  # redisPassword:
Please keep the default to generate a password

2017-03-16 22:29 UTC, lachie83 commented
@ged15 Can you please provide a status update?

2017-04-05 07:40 UTC, gajus commented
> @ged15 Can you please provide a status update?

Looking at @ged15 GitHub publicly activity, its unlikely there will be a follow up.

Can you please update the PR and merge it? I am assuming the default setting is the only outstanding issue.

2017-04-05 15:49 UTC, sstarcher commented
@ged15 could you finish the changes on this?  If not I would be happy to do it for you.

2017-04-06 07:51 UTC, ged15 commented
Sorry for the inactivity, sorting out some personal stuff.
@sstarcher I would really like to finish this but realistically that won't happen any time soon. If you want to pick this up, go ahead!

2017-04-06 13:00 UTC, sstarcher commented
@lachie83 I looked into this issue more.  Currently with the use of rand in the chart itself will cause a helm upgrade to regenerate the password causing any pods that were referencing it to no longer connect to redis.

This certainly effects the `sensu` chart that exists.  The current only way around this is for the user to specify the password.  I considered using .Release.IsUpgrade around the redis secrets, but this of course causes the secret to be fully deleted which is also not helpful.  

I'm not currently seeing any good options outside of defaulting redis to password less.  I consider the current option of using rand to be a bad option due to how upgrades work.

2017-05-10 20:07 UTC, viglesiasce commented
@sstarcher should the NOTES.txt tell people to use --set redisPassword=<original password> ?

2017-05-10 21:14 UTC, sstarcher commented
@viglesiasce I believe the current way these charts functions is flawed.  As users can't upgrade the chart without the password changing.  The best course of action until this is resolved would be to default the redis configuration to no password, but we have a larger Helm question of how to handle generated information without regenerating that information on upgrade.

2017-05-10 21:20 UTC, viglesiasce commented
Sorry I mean that:

1) the chart should tell them that they must record the password for upgrades
2) We block the regeneration of the password based on the release number
3) tell them to enter their previous password or else things will break on upgrade

2017-05-10 22:03 UTC, sstarcher commented
@viglesiasce that would certainly work, but the UX would be sub-par.  To upgrade the user should not have to know the current password.

2017-05-10 23:04 UTC, viglesiasce commented
@sstarcher what do you suggest?

2017-05-11 14:50 UTC, sstarcher commented
I don't currently have a great suggestion, but the current mechanism that is being recommended to people is a bad practice that they won't notice until they attempt to upgrade.  Helm does not have any in-built solution that would make this easy.

2017-05-11 20:07 UTC, ianburrell commented
The [docs](https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change) mention a technique using annotations to update deployments when the configmap or secrets change. That could be used to fix problems where changing the password isn't propagated.

There is still the problem of generated password changing with every update and causing unnecessary updates. It seems like this issue needs to be addressed by Helm because it is a problem for lots of software.

2017-05-11 20:09 UTC, ianburrell commented
I have a branch that keeps random default password but supports not using a password. It does this by adding a value, usePassword, that defaults to "true". But setting it to "false" disables the secret and REDIS_PASSWORD.

2017-05-11 20:14 UTC, sstarcher commented
@ianburrell nice I had not seen that new addition to helm.  @ianburrell mind putting in a PR with that change.  That sounds like what this PR is trying to accomplish.

2017-05-23 15:41 UTC, viglesiasce commented
ping @ianburrell

2017-05-25 21:24 UTC, ianburrell commented
@viglesiasce I put in #1061. Working on getting CLA signed.

2017-06-07 13:26 UTC, prydonius commented
closing in favour of #1061

2017-06-07 13:26 UTC, closed without merging