[stable][selenium] Add the option of adding nodeSelectors
helm/charts pull request #3791
Opened 2018-02-20 23:24 UTC by gezb

These can be applied globally or per Selenium component (hub, chrome, chromeDebug, firefox or firefoxDebug) 

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

2018-02-21 10:03 UTC, gezb commented
/hold

Found some issues with this I will push a fix once I have sorted it

2018-02-21 11:18 UTC, gezb commented
/unhold 

This turned out to be the way I was using labels

2018-02-21 13:31 UTC, gezb commented
I have fixed a few issues I found, Let me know if yow want me to rebase and squash the changes into a single commit

2018-03-02 16:28 UTC, jdumars commented
/ok-to-test

2018-04-02 19:42 UTC, timstoop requested changes
Can you please update the README as well?

2018-04-02 19:42 UTC, timstoop commented on stable/selenium/Chart.yaml
> +version: 0.2.7
This adds a new feature, so please bump the minor version.

2018-04-02 20:34 UTC, gezb commented
I have rebased against master, updated the README.md and corrected the version then squashed all the changes into a single commit

2018-04-03 10:55 UTC, timstoop commented
No need to squash, they will be squashed when merged and for reviewers it's convenient to have all the changes serially applied instead. I'll take a look, though.

2018-04-03 10:56 UTC, timstoop commented
/lgtm

2018-04-07 09:58 UTC, unguiculus commented
The way you implemented this, a global node selector takes precendence over individual ones. I would actually expect it the other way around. Any reason why you implemented it this way?

2018-04-07 09:58 UTC, unguiculus commented
/assign

2018-04-07 13:25 UTC, gezb commented
@unguiculus I think nodeselectors for the individual items was a afterthought so thats why global  took precedence but it makes sense what you say I have changed this and updated the Readme to make this clear

2018-04-07 14:14 UTC, unguiculus commented
/lgtm

2018-04-07 14:24 UTC, merged