prometheus service annotations for elastisearch-exporter
helm/charts pull request #3842
Opened 2018-02-23 01:04 UTC by Stelminator

Adds annotations so that Prometheus running within Kubernetes will pick up the exposed metrics.

2018-02-23 08:46 UTC, Stelminator commented
/assign @sameersbn ?

New to this repo, ohai; let me know if I'm doing this incorrectly, please.

2018-02-23 19:08 UTC, unguiculus requested changes
Thanks for the PR.

2018-02-23 19:08 UTC, unguiculus commented on stable/elasticsearch-exporter/templates/service.yaml
> +  annotations:
I'd suggest you rather make annotations configurable in general. If you use the prometheus-operator you don't need them.

2018-03-01 00:33 UTC, Stelminator commented on stable/elasticsearch-exporter/templates/service.yaml
> +  annotations:
updated, copied a pattern found in other charts.

2018-03-01 05:39 UTC, unguiculus commented
/ok-to-test

2018-03-01 05:39 UTC, unguiculus commented
/lgtm

2018-03-01 05:46 UTC, merged