[stable/elastalert] Updated image for Elasticsearch 6 support, and other minor chart adjustments
helm/charts pull request #3859
Opened 2018-02-24 15:52 UTC by jertel

Updated image for Elasticsearch 6 support, removed supervisord since k8s deployments provide that capability already, and added apiVersion to support helm upgrades

*****************************************************************************************

Thank you for contributing to kubernetes/charts. Before you submit this PR we'd like to
make sure you are aware of our technical requirements and best practices:

* https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
* https://github.com/kubernetes/helm/tree/master/docs/chart_best_practices

For a quick overview across what we will look at reviewing your PR, please read
our review guidelines:

* https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

Following our best practices right from the start will accelerate the review process and
help get your PR merged quicker.

When updates to your PR are requested, please add new commits and do not squash the 
history. This will make it easier to identify new changes. The PR will be squashed 
anyways when it is merged. Thanks.

*****************************************************************************************

2018-02-24 15:54 UTC, jertel commented
/assign @viglesiasce

2018-02-24 19:04 UTC, unguiculus commented
cc @pickledrick

2018-02-24 19:04 UTC, unguiculus commented
/assign

2018-02-27 00:26 UTC, kskewes commented
Thank you for this. Have you published your dockerfile and/or image somewhere? I can't see it on docker hub. "jertel/elastalert-docker". 
Keen to test.

2018-02-27 00:53 UTC, jertel commented
Hello, yes I have the github repo containing the Dockerfile linked to the Docker hub build. It's on the right side of the screen when viewing the Docker hub page. Here's the direct link: https://github.com/jertel/elastalert-docker. This Dockerfile is very simple, stripped down to basics. I'm using this image today against an Elasticsearch 6.0 installation and it works well. Thanks for taking the time to review.

2018-02-27 16:56 UTC, viglesiasce commented
@jertel Please add your Dockerfile repo to the sources list

2018-02-27 17:08 UTC, jertel commented
Which sources list?

On Tue, Feb 27, 2018 at 11:56 AM, Vic Iglesias <notifications@github.com>
wrote:

> @jertel <https://github.com/jertel> Please add your Dockerfile repo to
> the sources list
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/charts/pull/3859#issuecomment-368947764>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AP3me0khxamHc_IlROlpNs-POGxUAFoRks5tZDOrgaJpZM4SR76I>
> .
>

2018-02-27 20:36 UTC, unguiculus commented
@jertel Update the sources list in `Chart.yaml`.

2018-02-27 20:45 UTC, jertel commented
I added the new repo to source list and removed the obsolete repo. Thanks.

2018-03-02 16:28 UTC, jdumars commented
/ok-to-test

2018-03-09 18:15 UTC, jertel commented
Anything I need to do on this? The test appears to have failed because the pod shuts down due to the inability to connect to an elasticsearch server (which makes sense since there is no such server included in this chart). I'm not waiting on the pull-req to be merged personally but if there's something I can do to help get it closed and off your PR list, let me know.

2018-03-09 20:49 UTC, unguiculus commented
CI has to be green. Otherwise the bot won't merge. You'll may have to conditionally create the deployment.

2018-03-12 20:32 UTC, unguiculus requested changes

2018-03-12 20:32 UTC, unguiculus commented on stable/elastalert/Chart.yaml
> +  - name: Jason Ertel
Use Github username and add e-mail.

2018-03-16 12:16 UTC, unguiculus approved these changes

2018-03-16 12:17 UTC, unguiculus commented
/lgtm

2018-03-16 13:02 UTC, merged