[traefik] - updating to use the latest chart template fullname format
helm/charts pull request #3867
Opened 2018-02-25 14:03 UTC by sstarcher

Changes the fullname to use the namespaced traefik.fullname along with updating the template to use the latest fullname format.  If a user has the chart installed as the name `traefik` the service will change from `traefik-traefik` to now `traefik` if the release name is not `traefik` no change will be seen for the user.

2018-02-25 14:04 UTC, sstarcher commented
/assign @krancour

2018-02-25 18:23 UTC, unguiculus commented
/ok-to-test

2018-02-25 18:26 UTC, unguiculus commented
Looking at this, I wonder why the chart doesn't have a `name` template, which should actually be used for the `app` label. There's another partial in `_helper.tpl` that should get updated as well (`trustedips`).

2018-02-25 18:27 UTC, unguiculus commented
/hold
/assign

2018-02-26 12:49 UTC, sstarcher commented
@unguiculus my plan was not to update everything, but just the single item.

2018-02-26 12:52 UTC, sstarcher commented
@unguiculus updated the name, but I'm not sure what you mean by the trustedips needs updated

2018-02-26 19:29 UTC, krancour commented
@unguiculus is this something that's being done widely across all charts?

2018-02-26 21:28 UTC, unguiculus commented
@sstarcher @krancour Yes, generally all partials should be namespaced. Here's the issue that kicked this off: #1785.

2018-02-26 21:40 UTC, sstarcher commented
@unguiculus makes sense I updated that one also

2018-02-27 21:00 UTC, unguiculus requested changes

2018-02-27 21:00 UTC, unguiculus commented on stable/traefik/templates/dashboard-service.yaml
> +    app: {{ template "traefik.name" . }}
Add `release` label to selector now that you switched to using the `app` label.

2018-02-27 21:00 UTC, unguiculus commented on stable/traefik/templates/deployment.yaml
> +      app: {{ template "traefik.name" . }}
Add `release` label to selector.

2018-02-27 21:00 UTC, unguiculus commented on stable/traefik/templates/service.yaml
> +    app: {{ template "traefik.name" . }}
Add `release` label to selector.

2018-02-28 08:12 UTC, siwyd commented
Perhaps values.yaml and README.md should get updated as well to inform users of the possible overrides?

2018-02-28 17:41 UTC, sstarcher commented
@unguiculus I think I fixed all the things you wanted

2018-02-28 18:55 UTC, unguiculus commented
/hold cancel

2018-02-28 18:55 UTC, unguiculus commented
/lgtm

2018-02-28 18:59 UTC, merged

2018-03-07 13:10 UTC, atze234 commented
This app selector (  app: {{ template "traefik.name" . }}  ) will break balancing when using multiple traefik instances per namespace (for example to route private and public traffic)
Since this resolves simply to "traefik" i then have two pods in the namespace that belongs to different helm release names (traefik-private and traefik-public ) and traffic gets routed randomly.

I had to rollback to chart version 1.21.1 because of this.

2018-03-08 16:55 UTC, unguiculus commented
I don't see how this PR changed the behavior. It just changed the selector from `fullname` to `name` which shouldn't make a difference.

2018-03-08 17:17 UTC, sstarcher commented
The release information is also in the selector so it should segregate releases.

2018-03-08 20:00 UTC, atze234 commented
Changing the selector from fullname to name do make a huge difference.
For example:
On older releases, if you deployed with a fullname like "traefik-foo-traefik" the app selector would have been "traefik-foo-traefik" too. After that you deployed a "traefik-bar-traefik" in the same namespace the selector was traefik-bar-traefik.
Now after this PR both, traefik-bar-traefik and traefik-foo-traefik, will just be "traefik" in the selector "backend" .
This leads to randomly routed packets from traefik-foo-traefik and traefik-bar-traefik to backend selector traefik.
Hope its a little more clear now.

2018-03-08 20:02 UTC, unguiculus commented
That's exactly why the release label is also part of the selector.

2018-03-08 20:05 UTC, atze234 commented
but isnt ```app: {{ template "traefik.name" . }}``` always "traefik" ? 
for my deployment mentioned it is always "traefik".

2018-03-08 20:26 UTC, unguiculus commented
Yes, but, as mentioned, it's not the only label in the selector.

2018-03-08 22:03 UTC, sstarcher commented
@atze234 https://github.com/kubernetes/charts/pull/3867/files#diff-d5b0dd2172770e5fa636182e2dda0d6eR15

2018-03-09 09:05 UTC, atze234 commented
ok, nevermind.
Im using "immutable" Services (type loadbalancer)  that points to traefik, because when names of resources are changed by helm (like here), i dont want dns records to be changed. Just missed that new release label selector in there.