Fix lego issue
helm/charts pull request #388
Opened 2017-01-12 19:50 UTC by jackzampolin

Fixes #385

2017-01-12 22:07 UTC, viglesiasce commented
cc @mgoodness for review

2017-01-12 22:17 UTC, viglesiasce requested changes

2017-01-12 22:17 UTC, viglesiasce commented on stable/nginx-lego/templates/lego-deployment.yaml
> +<<<<<<< HEAD
Merge conflict was checked in here

2017-01-12 23:01 UTC, mgoodness commented
Works on my cluster (minus the merge-conflict leftovers)! Not a fan of the forced `app` label, but that's an issue for upstream.

One (hopefully) last thing: the nginx `vts_status` port should be `18080`, not `8080`. Blame the docs :( Update [nginx-deployment.yaml](https://github.com/kubernetes/charts/blob/master/stable/nginx-lego/templates/nginx-deployment.yaml#L30) appropriately and that should do it.

2017-01-12 23:51 UTC, jackzampolin commented
@mgoodness Thank you for that port! I was wondering why `8080` didn't work! I'll go ahead and add that. I might put monitoring in there behind a flag like `monitoringEnabled`. If yes it would generate the service (ClusterIP) and expose the container port.

2017-01-12 23:54 UTC, jackzampolin commented on stable/nginx-lego/templates/lego-deployment.yaml
> +<<<<<<< HEAD
🙀

2017-01-13 00:53 UTC, mgoodness requested changes

2017-01-13 00:53 UTC, mgoodness commented on stable/nginx-lego/templates/nginx-monitoring.yaml
> +    name: vts_stats
Invalid name, I'm afraid. `vts-stats` works.

2017-01-13 17:44 UTC, jackzampolin commented on stable/nginx-lego/templates/nginx-monitoring.yaml
> +    name: vts_stats
🙈

2017-01-13 18:25 UTC, mgoodness commented
LGTM!

2017-01-13 18:26 UTC, viglesiasce approved these changes

2017-01-13 20:33 UTC, merged