[stable/chronograf] And OAuth support and bump version
helm/charts pull request #390
Opened 2017-01-13 00:48 UTC by jackzampolin

2017-01-17 19:17 UTC, viglesiasce requested changes
Looks like you left in your token and secret

2017-01-17 19:17 UTC, viglesiasce commented on stable/chronograf/values.yaml
> +    client_id: f612alskdfc91cad5ad
These shouldnt be set here

2017-01-17 22:47 UTC, jackzampolin commented on stable/chronograf/values.yaml
> +    client_id: f612alskdfc91cad5ad
That's actually a random string. Ok to leave?

2017-01-19 19:16 UTC, viglesiasce commented on stable/chronograf/values.yaml
> +    client_id: f612alskdfc91cad5ad
I would make that very clear by commenting this section out as they are not useful and ensuring that the value is something that denotes that it needs to be changed (ie `CHANGE_ME`)

2017-01-23 19:37 UTC, viglesiasce submitted a review, later dismissed

2017-01-23 19:37 UTC, viglesiasce commented on stable/chronograf/values.yaml
> +    kubernetes.io/ingress.class: "nginx"
I would leave this annotation off by default so that the cluster default is used out of the box

2017-02-25 19:15 UTC, mgoodness commented
@jackzampolin are you able to resolve this? I have additional review, but only if the PR is still active. Please let us know by 4 March, or we'll close.

2017-02-28 20:27 UTC, jackzampolin commented
@mgoodness Sorry this fell through the cracks when getting back up to speed. I just addressed the last comment. This should also close out https://github.com/kubernetes/charts/pull/677

2017-03-01 23:21 UTC, jackzampolin commented
I've added support for all of the different OAuth providers that are [currently supported](https://github.com/influxdata/chronograf/blob/master/docs/auth.md) by Chronograf.

I'm happy to make any other changes to this that are needed.

@viglesiasce

2017-03-07 18:29 UTC, prydonius reviewed
code review lgtm, just a minor comment

2017-03-07 18:29 UTC, prydonius commented on stable/chronograf/templates/ingress.yaml
> +      secretName: {{ template "fullname" . }}-tls
Could this be:

```
{{ .Values.ingress.secretName | default (printf "%s-tls" (include "fullname" .)) }}
```

2017-03-08 01:11 UTC, jackzampolin commented on stable/chronograf/templates/ingress.yaml
> +      secretName: {{ template "fullname" . }}-tls
Yes it could easily. And it will be!

2017-03-08 01:15 UTC, jackzampolin commented
@prydonius Good catch! Its ready to go!

2017-03-13 17:52 UTC, jackzampolin commented
@viglesiasce is this ready to go?

2017-03-20 20:07 UTC, mgoodness commented
@k8s-bot ok to test

2017-03-23 00:10 UTC, merged