Make it possible to add tolerations to fluentd-cw
helm/charts pull request #3931
Opened 2018-03-01 10:25 UTC by MattiasGees

This adds the possability to add tolerations to the fluentd-cloudwatch chart. This is handy if you also want to ship the logs from your master nodes.

This is mostly a copy from [fluentd-elasticsearch[(https://github.com/kubernetes/charts/blob/master/incubator/fluentd-elasticsearch/templates/daemonset.yaml#L80-L83) that has the same behaviour.

2018-03-01 10:49 UTC, MattiasGees commented
Verify myself

2018-03-01 10:49 UTC, MattiasGees commented
/assign @sameersbn

2018-03-01 16:50 UTC, unguiculus requested changes
Thanks for the PR.

2018-03-01 16:50 UTC, unguiculus commented on incubator/fluentd-cloudwatch/values.yaml
> +# tolerations:
Add an empty list as default:

`tolerations: [] `

2018-03-01 16:50 UTC, unguiculus commented on incubator/fluentd-cloudwatch/README.md
> +| `tolerations`                   | Add tolerations                            | `nil`                                                      |
Default: `[]`

2018-03-02 11:32 UTC, MattiasGees commented
@unguiculus I changed it to an empty list.

2018-03-02 16:07 UTC, jdumars commented
/ok-to-test

2018-03-02 18:58 UTC, unguiculus commented
/assign

2018-03-02 18:58 UTC, unguiculus approved these changes

2018-03-02 18:58 UTC, unguiculus commented
/lgtm

2018-03-02 21:10 UTC, MattiasGees commented
/retest

2018-03-02 21:13 UTC, merged