Add a stable Helm chart for MetalLB.
helm/charts pull request #3974
Opened 2018-03-04 02:31 UTC by danderson

The chart installs MetalLB 0.4.0, which was just released.

2018-03-04 02:37 UTC, danderson commented
I've tried to follow the various guidelines and requirements for stable charts, and I _think_ I got all of them.

While the chart does `helm install` correctly with no other parameters, the resulting installation doesn't do anything because MetalLB needs a config of its own. The chart's NOTES.txt warns of this, per the guidelines. The chart also has a couple of ways to pass in a configuration, to get a fully functioning Helm-managed install.

One thing I was unsure about is that the chart currently hardcodes the `metallb-system` namespace. My rationale here is that MetalLB is a cluster-wide infrastructure service. You cannot install multiple instances simultaneously, that's an entirely unsupported configuration. Given that, it doesn't make sense to me to allow configuring the namespace - and in fact the `metallb-system` namespace is currently hardcoded in the binaries in a few places. WDYT? I'm unfamiliar with Helm best practices when it comes to "cluster singleton" systems such as this.

2018-03-04 09:39 UTC, unguiculus commented
/assign

2018-03-06 19:26 UTC, unguiculus requested changes

2018-03-06 19:26 UTC, unguiculus commented on stable/metallb/Chart.yaml
> +- name: David Anderson
Use Github username

2018-03-06 19:26 UTC, unguiculus commented on stable/metallb/templates/config.yaml
> +  name: config
Add standard labels and use the `fullname` template for names. Apply everywhere.

2018-03-06 19:26 UTC, unguiculus commented on stable/metallb/templates/namespace.yaml
> +  name: metallb-system
Why do you hard-code the namespace and create it explicitly. Is this a requirement for MetalLB?

2018-03-06 19:26 UTC, unguiculus commented on stable/metallb/templates/rbac.yaml
> +## Service accounts
Please move service accounts to separate files and follow our RBAC best practices.
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

2018-03-06 19:26 UTC, unguiculus commented on stable/metallb/templates/controller.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
`chart: "{{ template "metallb.chart" . }}"`

2018-03-06 19:26 UTC, unguiculus commented on stable/metallb/templates/controller.yaml
> +  annotations:
Make annotations configurable. You don't need them if you use the Prometheus Operator.

2018-03-06 19:26 UTC, unguiculus commented on stable/metallb/templates/controller.yaml
> +      {{- if .Values.helmLabels }}
Remove `if` statement. Standard labels should always be added.

2018-03-07 07:54 UTC, danderson commented
Thank you for the review! I made the requested changes, PTAL.

2018-03-08 14:53 UTC, unguiculus requested changes

2018-03-08 14:53 UTC, unguiculus commented on stable/metallb/templates/config.yaml
> +  namespace: {{ .Release.Namespace | quote }}
Just remove the namespace completely. It is unnecessary. The result will be the same. Apply everywhere.

2018-03-08 14:53 UTC, unguiculus commented on stable/metallb/README.md
> +-	Kubernetes 1.9+
Remove unnecessary spaces.

2018-03-16 12:14 UTC, unguiculus approved these changes

2018-03-16 12:14 UTC, unguiculus commented
/ok-to-test

2018-03-16 12:17 UTC, unguiculus commented
/lgtm

2018-03-16 12:18 UTC, merged