Kubernetes Operational View
helm/charts pull request #398
Opened 2017-01-14 20:07 UTC by hjacobs

Create Helm Chart for [Kubernetes Operational View](https://github.com/hjacobs/kube-ops-view).

![screenshot](https://cloud.githubusercontent.com/assets/510328/21957691/a4c0a2de-da9c-11e6-8005-43d30712da9d.png)

The Chart should work, tested with helm 2.1.3 and Kubernetes 1.5.2 :smile: 

NOTE:
* the Chart does not yet expose "advanced" configurations to monitor multiple clusters (i.e. it only shows the cluster it currently runs in)
* the Chart does not yet configure a Redis backend, i.e. it uses a memory-only backend for message pub/sub which only works correctly for `replicaCount=1`.

2017-01-16 22:44 UTC, prydonius commented
@k8s-bot ok to test

2017-01-16 23:49 UTC, prydonius requested changes

2017-01-16 23:49 UTC, prydonius commented on incubator/kube-ops-view/templates/_helpers.tpl
> +{{- default .Chart.Name .Values.nameOverride | trunc 24 | trimSuffix "-" -}}
Could you change this to truncate to 63 chars as per https://github.com/kubernetes/charts/issues/233? Thanks!

2017-01-16 23:51 UTC, hjacobs commented on incubator/kube-ops-view/templates/_helpers.tpl
> +{{- default .Chart.Name .Values.nameOverride | trunc 24 | trimSuffix "-" -}}
@prydonius will do! I guess `helm init` should also be changed as I got it from there.

2017-01-16 23:52 UTC, prydonius commented on incubator/kube-ops-view/templates/_helpers.tpl
> +{{- default .Chart.Name .Values.nameOverride | trunc 24 | trimSuffix "-" -}}
@hjacobs ah good point, sorry about that!

2017-01-16 23:53 UTC, hjacobs commented
@prydonius updated to 63 chars :smile:

2017-01-19 19:06 UTC, viglesiasce commented
@prydonius ready for your next pass

2017-01-19 23:06 UTC, prydonius commented
thanks @hjacobs, lgtm!

2017-01-19 23:06 UTC, prydonius approved these changes

2017-01-20 00:41 UTC, merged