[stable/nginx-ingress] Add support for extraVolumeMounts, sidecarContainers and extraVolumes
helm/charts pull request #3983
Opened 2018-03-05 15:21 UTC by sathieu

Replaces #3810.

2018-03-13 18:01 UTC, paulczar commented
I really like this pattern.  Can you bump the version for a minor release as its adding features?

should be `0.12.0` based on current version.

2018-03-13 18:02 UTC, paulczar commented
/assign @paulczar

2018-03-13 18:06 UTC, paulczar requested changes
I really like this pattern. Can you bump the version for a minor release as its adding features?

should be 0.12.0 based on current version.

2018-03-13 18:06 UTC, paulczar commented
/ok-to-test

2018-03-13 19:19 UTC, sathieu commented
I have rebased and bumped the version to 0.12.0 as requested.

2018-03-13 21:00 UTC, sathieu commented
/retest

2018-03-16 12:43 UTC, unguiculus commented
/assign

2018-03-19 17:11 UTC, paulczar approved these changes
:+1:

2018-03-19 17:12 UTC, paulczar commented
/lgtm

2018-03-19 21:00 UTC, sathieu commented
/assign @unguiculus

2018-03-29 18:34 UTC, paulczar commented
@sathieu  you'll need to rebase from master to fix the conflicts.

2018-03-29 22:02 UTC, unguiculus commented
Please rename: `sidecarContainers`-> `extraContainers`

2018-03-30 04:11 UTC, sathieu commented
@paulczar @unguiculus Done.

2018-04-01 09:39 UTC, timstoop commented
/lgtm

2018-04-06 13:00 UTC, unguiculus commented
/lgtm

2018-04-06 13:57 UTC, merged