Jenkins/ingress support
helm/charts pull request #402
Opened 2017-01-15 22:18 UTC by electroma

Added option to create Ingress object for Jenkins master.
May be useful in case server uses Ingress controller.

2017-01-16 22:38 UTC, lachie83 commented
@electroma Thanks for the contrib. Just out of interest. What ingress controllers did you test this against?

2017-01-16 22:52 UTC, electroma commented
@lachie83 Tested with Traefik (chart stable/traefik).

2017-01-17 02:58 UTC, mgoodness commented
@lachie83 @electroma I'm going to give it a shot against the nginx controller. Will report back.

2017-01-23 19:44 UTC, viglesiasce submitted a review, later dismissed
Needs version bump as well

2017-01-23 19:44 UTC, viglesiasce commented on stable/jenkins/values.yaml
> +  HostName: ~
Looks like this is being set by default. Shouldnt it be commented out?

2017-01-23 19:44 UTC, viglesiasce commented on stable/jenkins/templates/jenkins-master-ingress.yaml
> +---
Remove this otherwise delete will fail.

2017-01-23 20:54 UTC, electroma commented
@viglesiasce fixed according to your comments

2017-01-23 20:55 UTC, electroma commented on stable/jenkins/values.yaml
> +  HostName: ~
I would prefer to have this key uncommeted, but empty. But if there is a convention to comment out empty keys - lets stick to it.

2017-01-25 14:57 UTC, electroma commented
@viglesiasce does it qualify as minor change (so the new version is 0.1.8)?

2017-01-31 19:44 UTC, viglesiasce commented
@k8s-bot ok to test

2017-02-04 18:30 UTC, mgoodness requested changes
nginx support requires an annotation on the Ingress. Recommend adding an `ingressAnnotations` value for this purpose.

Would also be nice if NOTES.txt output the Ingress endpoint (`http://{{ .Values.Master.HostName }}`) instead of the generic `kubectl port-forward ...`.

2017-02-04 18:30 UTC, mgoodness commented on stable/jenkins/templates/jenkins-master-ingress.yaml
> +  name: {{ template "fullname" . }}
The nginx controller requires at least a `kubernetes.io/ingress.class: nginx` annotation on the Ingress resource, but supports others as well. Perhaps provide an `ingressAnnotations` value ?

values.yaml:
```
...
ingressAnnotations:
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
...
```

jenkins-master-ingress.yaml:
```
...
metadata:
{{- if .Values.ingressAnnotations }}
  annotations:
{{ toYaml .Values.ingressAnnotations | indent 4 }}
{{- end }}
...
```

2017-02-09 23:06 UTC, mgoodness approved these changes

2017-02-10 23:12 UTC, lachie83 commented
@mgoodness We waiting on anything else here?

2017-02-10 23:15 UTC, mgoodness commented
@lachie83 if it lgtu it lgtm

2017-02-13 04:25 UTC, merged