[stable/neo4j] Fix dataVolume Persistence
helm/charts pull request #4046
Opened 2018-03-08 07:12 UTC by smelchior

The current chart was not really persisting the data volume as `volumemounts` was defined twice and the second one for `plugins` was active. 
The data PVC was created but not mounted. This caused some data loss during our testing as we did run the Set with only 1 core server.
I also made the subPath optional to make the definition a little more readable.

2018-03-08 07:14 UTC, smelchior commented
/assign @mgoodness

2018-03-08 07:37 UTC, unguiculus requested changes
Thanks for the PR. I have only one nit.

2018-03-08 07:37 UTC, unguiculus commented on stable/neo4j/README.md
> +| `core.persistentVolume.subPath`    | Subdirectory of the volume to mount                                                                                                       | `nil`
Proper alignment, please.

2018-03-08 07:37 UTC, unguiculus commented
@mneedham

2018-03-08 08:01 UTC, smelchior commented
whoops, yes indeed. Fixed now :-)

2018-03-27 09:58 UTC, smelchior commented
ping @unguiculus

2018-04-01 09:34 UTC, timstoop requested changes

2018-04-01 09:34 UTC, timstoop commented on stable/neo4j/Chart.yaml
> +version: 0.5.1
As you're adding a feature, please bump the minor version.

2018-04-01 09:35 UTC, timstoop commented
/ok-to-test

2018-04-01 13:50 UTC, timstoop commented
Can you please rebase and check the version in Chart again?

2018-04-02 03:39 UTC, smelchior commented
sorry, did not see that, it is done now

2018-04-02 19:10 UTC, timstoop commented
/lgtm

2018-04-07 09:39 UTC, unguiculus approved these changes

2018-04-07 09:39 UTC, unguiculus commented
/lgtm

2018-04-07 09:50 UTC, merged