Adding support for Service annotations
helm/charts pull request #4060
Opened 2018-03-08 17:51 UTC by marcostvz

I needed to add annotations to service to allow an internal load balancer in GCP. I guess this could be useful for others.

Inspired in https://github.com/kubernetes/charts/blob/master/stable/kong/templates/service-kong-admin.yaml

2018-03-08 17:54 UTC, marcostvz commented
/assign @unguiculus

2018-03-08 18:45 UTC, unguiculus commented
cc @rjkernick

2018-03-08 18:46 UTC, unguiculus commented
/ok-to-test

2018-03-08 18:46 UTC, unguiculus commented
/assign

2018-03-10 06:07 UTC, shashiranjan84 commented
@marcostvz please try https://github.com/kubernetes/charts/pull/3947, it has more flatten value file.

2018-03-12 20:37 UTC, unguiculus commented
Please add documentation.

2018-03-12 22:21 UTC, marcostvz commented
/test pull-charts-e2e

2018-03-12 22:30 UTC, marcostvz commented
Hey @unguiculus tell me if is enough adding that to README.md

2018-03-16 12:29 UTC, unguiculus commented
Please also add an empty default to `values.yaml`.

2018-03-16 19:23 UTC, marcostvz commented
Done, thanks for your comment

2018-03-16 21:57 UTC, marcostvz commented
/test pull-charts-e2e

2018-03-16 22:34 UTC, marcostvz commented
/retest

2018-03-19 23:12 UTC, marcostvz commented
/test pull-charts-e2e

2018-04-01 09:31 UTC, timstoop requested changes

2018-04-01 09:31 UTC, timstoop commented on stable/sonarqube/Chart.yaml
> +version: 0.3.7
This adds a feature, so please bump the minor version.

2018-04-01 09:32 UTC, timstoop commented
Making that change will retest and hopefullt fix the container not ready error.

2018-04-11 12:06 UTC, rjkernick commented
Please rebase off of master. The tests should pass with the fixes that are on master.

2018-04-17 08:15 UTC, marcostvz commented
Thanks @rjkernick , it looks good now 🎉

2018-04-17 15:52 UTC, rjkernick commented
/assign
/lgtm

2018-04-17 15:59 UTC, merged