[WIP] Add chart for selenium grid
helm/charts pull request #409
Opened 2017-01-16 09:12 UTC by yuvipanda

Sets up an installation of https://github.com/SeleniumHQ/selenium/wiki/Grid2

Slightly stolen from @sgoings's https://github.com/helm/charts/tree/master/selenium-hub

2017-02-03 23:44 UTC, lachie83 commented on stable/selenium-grid/values.yaml
> +      cpu: 2
Can you please confirm if these are the lowest resource requirements possible?

2017-02-03 23:46 UTC, yuvipanda commented on stable/selenium-grid/values.yaml
> +      cpu: 2
I needed these when I ran a 100 count hub but can lower these since the default is just 2.

2017-02-06 18:13 UTC, lachie83 requested changes
Can you please add a README? Also please double check that you've me all the tech requirements for this to be merged? 
https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements

2017-02-22 20:49 UTC, flah00 commented
@yuvipanda what do you think of #665? There are a number of options which this chart doesn't include, which are pretty critical to my environment

* ability to use debug nodes
* ability to turn on and off nodes, which aren't needed
* ability to set `JAVA_OPTS` and `SE_OPTS`
* ability to set screen size, tz, etc
* support for chrome shared memory above docker default of 64m

2017-02-22 20:51 UTC, yuvipanda commented
@flah00 w00t! I like that one much better! You seem to actually know things about selenium, while I was just trying to get a minimal setup up. I'll close this one in favor of yours :)

2017-02-22 20:51 UTC, closed without merging