[traefik] Enable HTTP authentication for the dashboard
helm/charts pull request #413
Opened 2017-01-16 16:30 UTC by tolbrino

Also allow configuration of the dashboard's service address and whether the Ingress should be generated.

2017-01-16 16:46 UTC, tolbrino commented
I signed it!

2017-01-16 22:41 UTC, lachie83 commented
cc @krancour

2017-01-17 08:13 UTC, unguiculus commented on stable/traefik/README.md
> +| `dashboard.http_auth`           | List of user/password combinations to be used via HTTP Auth          | none                                      |
Can we stick with camel case to be consistent with the other properties?
-> `dashboard.httpAuth`

2017-01-17 08:16 UTC, unguiculus requested changes

2017-01-17 08:16 UTC, unguiculus commented on stable/traefik/README.md
> +| `dashboard.http_auth`           | List of user/password combinations to be used via HTTP Auth          | none                                      |
Can we stick with camel case to be consistent with the other properties?
-> `dashboard.httpAuth`

2017-01-17 08:16 UTC, tolbrino commented on stable/traefik/README.md
> +| `dashboard.http_auth`           | List of user/password combinations to be used via HTTP Auth          | none                                      |
Definitely, will fix it.

2017-01-21 23:44 UTC, krancour commented
This is a duplicate of #414. This may have been submitted first, but #414 has been more thoroughly reviewed, requested changes already applied, etc.

2017-01-23 11:18 UTC, tolbrino commented
@krancour Agreed, I could strip the http auth part from this PR and leave that to #414. Then only the `address` and `public` parameters would be handled here.

2017-01-25 00:09 UTC, krancour commented
@tolbrino ya... let's take the basic auth stuff out of this PR and consider what remains on its own merit. tbh, I haven't looked to closely at those others changes yet.

2017-02-13 20:36 UTC, lachie83 commented
@tolbrino @krancour What would you like me to do with this?

2017-02-14 08:18 UTC, tolbrino commented
@lachie83 I forgot to adapt the PR so far. Will do so in the coming days, then you can review it again.

2017-03-16 22:28 UTC, lachie83 commented
@tolbrino can you please provide a status update?

2017-03-22 22:48 UTC, seanknox commented
Closing due to inactvitiy. @tolbrino feel free to re-open.

2017-03-22 22:48 UTC, closed without merging