adding filebeat chart
helm/charts pull request #4133
Opened 2018-03-13 13:13 UTC by sstarcher

This is an addition for adding a filebeat chart.  This work is a continuation of #3108.  I removed some of the assumptions and made it more generic to support other configuration options, such as redis.

Other updates were made to bring it more in-line with https://raw.githubusercontent.com/elastic/beats/master/deploy/kubernetes/filebeat-kubernetes.yaml
and additionally updated for Kubernetes 1.9 apis and general helm best practices.

@rendhalver and @unguiculus

2018-03-13 14:32 UTC, sstarcher commented
/assign unguiculus
/assign rendhalver

2018-03-13 14:33 UTC, sstarcher commented
/assign @lachie83

2018-03-14 17:22 UTC, unguiculus requested changes

2018-03-14 17:22 UTC, unguiculus commented on stable/filebeat/templates/clusterrolebinding.yaml
> +  name: {{ template "filebeat.fullname" . }}
name: {{ template "filebeat.serviceAccountName" . }}

2018-03-14 17:22 UTC, unguiculus commented on stable/filebeat/templates/daemonset.yaml
> +      serviceAccountName: {{ template "filebeat.fullname" . }}
{{ template "filebeat.serviceAccountName" . }}

2018-03-14 17:22 UTC, unguiculus commented on stable/filebeat/values.yaml
> +    - add_cloud_metadata:
Please use consistent list indentation style. Either zero or two spaces. Don't mix.

2018-03-14 17:28 UTC, sstarcher commented
Fixed - @unguiculus thanks for the reviews.

2018-03-15 12:25 UTC, rendhalver commented
Nice work @sstarcher!
Thanks for massaging this into a state that's more compatible with best practices and new version of Kube.

2018-03-17 00:01 UTC, unguiculus approved these changes

2018-03-17 00:01 UTC, unguiculus commented
/ok-to-test

2018-03-17 00:04 UTC, unguiculus commented
/lgtm

2018-03-17 00:09 UTC, merged