Allow full use of duplicate input/ouputs in telegraf configuration
helm/charts pull request #4170
Opened 2018-03-15 22:41 UTC by amoskyler

**What this PR does / why we need it**:
This change converts the `inputs` and `outputs` fields from an object with keys associated to configs, to an array of objects which contain keys associated to objects.

Before:
```
config:
  outputs:
     influxdb:
      ...config...
```

After:
```
config:
  outputs:
    - influxdb:
       ...config...
```

Telegraf supports duplicate same type input and output configurations. In the current chart implementation, each input and output is configured with keys in the objects `inputs` and `outputs` respectively. `YAML` overrides the first key in the object however, and therefore the templating process from `YAMl` to `TOML` drops configuration valid `TOML` configurations, which limits . use of possible valid configurations.

2018-03-15 22:50 UTC, amoskyler commented
CLA signed.

2018-03-15 23:18 UTC, amoskyler commented
/assign @scottrigby

2018-04-01 09:21 UTC, timstoop requested changes
I'd love to see some documentation in README as well.

2018-04-01 09:21 UTC, timstoop commented on stable/telegraf/templates/deployment.yaml
> +    type: RollingUpdate
Any reason why you do not make this settable?

2018-04-01 09:21 UTC, timstoop commented on stable/telegraf/Chart.yaml
> +version: 0.3.3
This change adds features, please bump the minor version.

2018-04-01 09:21 UTC, timstoop commented
/ok-to-test

2018-04-07 09:04 UTC, unguiculus commented
cc @jackzampolin

2018-04-09 23:01 UTC, amoskyler commented
I've added some brief documentation for how to add inputs.
I have also updated the documentation in values.yaml to include details on setting updateStrategy.

Unrelated...Why is this chart marked as deprecated? I don't see any alternative charts. The README mentions telegraf-s and telegraf-ds charts, however I can't find them in the charts repo.

2018-04-13 20:19 UTC, unguiculus commented
Deprecated charts are not updated. The chart was deprecated in #823.

See https://github.com/kubernetes/charts/blob/master/PROCESSES.md

Please reach out to the original maintainer @jackzampolin in order to see what can be done.

2018-04-13 20:19 UTC, closed without merging

2018-04-13 23:29 UTC, amoskyler commented
I just went ahead and read that documentation. I didn't read the "deprecated charts are not updated" as an order, but more of implication of the status of deprecation. Why turn down good code?

Do we really need to go through a process where I take over maintenance, make a single PR, and re-deprecate until I'm ready to start the process over again at a later date when I have another PR? (aka, I'm not sure I'm ready to be a maintainer, but I can't contribute to it unless I become the sole maintainer?)

If this project is truly un-maintained, what is the purpose of reaching out to the old maintainer? It would also seem the owner is still listed in the chart, which would seem to be a violation of the deprecation policy.

2018-04-13 23:31 UTC, amoskyler commented
Also, please note the following issue: https://github.com/kubernetes/charts/issues/3113

This chart was deprecated in favor of two other charts - which appear to be missing.

2018-04-14 05:56 UTC, unguiculus commented
Both of these PRs were closed but you can find them upstream in the InfluxDB repo. I thought it would make sense to ask the maintainer if they still intend to add them here.