add prometheus node exporter chart
helm/charts pull request #4260
Opened 2018-03-17 10:14 UTC by gianrubio

This is the first chart moved from prometheus-operator to this repo.

Related to #3490

2018-03-17 10:15 UTC, gianrubio commented
/assign @prydonius

2018-03-19 20:17 UTC, gtaylor commented
Are we going to be breaking the node exporter out of the main `prometheus` chart?

2018-03-23 11:43 UTC, prydonius commented
@gianrubio see my comment in https://github.com/kubernetes/charts/pull/3490#issuecomment-375633248, could you add an OWNERS file here and would you be able to join the Kubernetes org?

2018-03-23 11:43 UTC, prydonius commented
/ok-to-test

2018-03-23 13:54 UTC, gianrubio commented
@prydonius I added the OWNER file and yes I would like to join the kubernetes org. What else do you need from me to sponsor my membership?

2018-03-23 14:43 UTC, prydonius commented
@gianrubio I'm happy to sponsor you. @mattfarina @unguiculus @viglesiasce could be one of your other sponsors. You will need to put a request together stating the sponsors, and links to contributions: https://github.com/kubernetes/community/blob/master/community-membership.md#requirements. If you don't have multiple contributions yet, is there someone else you could add the OWNERS file for now? @brancz is already in the org.

2018-03-23 14:50 UTC, brancz commented
I'm happy to sponsor @gianrubio as well! Regarding the OWNERS file, I'd prefer not be part of it as I already have more than enough things on my plate. :slightly_smiling_face:

2018-03-28 12:38 UTC, gianrubio commented
@prydonius I'm not part of the organization thanks for sponsoring me, could you review this PR?

2018-03-28 15:33 UTC, timstoop commented
/lgtm

2018-03-28 15:36 UTC, gianrubio commented
/assign @prydonius

2018-03-29 21:04 UTC, unguiculus requested changes

2018-03-29 21:04 UTC, unguiculus commented on stable/prometheus-node-exporter/values.yaml
> +rbac:
This is not used.

2018-03-29 21:04 UTC, unguiculus commented
/assign

2018-03-30 10:11 UTC, timstoop commented
/lgtm still

2018-03-30 14:51 UTC, gianrubio commented
/assign @prydonius

2018-03-30 14:51 UTC, gianrubio commented
/assign @unguiculus

2018-03-30 16:03 UTC, unguiculus commented
/lgtm

2018-03-30 16:03 UTC, unguiculus approved these changes

2018-03-30 16:18 UTC, merged