support GPU for tensorflow inception
helm/charts pull request #4262
Opened 2018-03-18 04:01 UTC by cheyang

**What this PR does / why we need it**:

This PR for 2 things:

1. Make the parameters Cpu, Memory work as described in the Document
2. Support GPU for TensorFlow Inception Model

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-03-18 04:06 UTC, cheyang commented
/ok-to-test

2018-03-18 12:13 UTC, cheyang commented
@viglesiasce Please take a look, thanks.

2018-03-21 23:21 UTC, cheyang commented
/assign @unguiculus

2018-03-28 15:31 UTC, timstoop requested changes

2018-03-28 15:31 UTC, timstoop commented on incubator/tensorflow-inception/values.yaml
> +Gpu: 0
Although this works fine, it seems that we're moving to standardising on the `resources` variable for this instead, which just takes freestyle yaml so someone is able to set the resources like normal. I think that's cleaner, although adding the cpu option to the docs and/or the values.yaml example might be good as well.

2018-03-29 00:48 UTC, closed without merging