added Apache superset charts
helm/charts pull request #4263
Opened 2018-03-18 17:30 UTC by alitari

Helm charts for  [Apache superset](https://superset.incubator.apache.org/)

2018-03-18 20:53 UTC, alitari commented
/assign @seanknox

2018-03-26 18:58 UTC, unguiculus requested changes

2018-03-26 18:58 UTC, unguiculus commented on incubator/superset/values.yaml
> +resources:
Don't specify defaults for resources. Comment them out.

2018-03-26 18:58 UTC, unguiculus commented on incubator/superset/Chart.yaml
> +- name: Alexander Krieg
Use Github username

2018-03-26 18:58 UTC, unguiculus commented
/assign

2018-03-27 18:14 UTC, closed without merging

2018-03-27 18:20 UTC, alitari commented
Something went wrong with my repo, so so i made a new pr #4481