[stable/minio] add ingress resource and general refactor
helm/charts pull request #4281
Opened 2018-03-19 16:21 UTC by rtluckie

- add ingress resource
- consolidate svc resource to support all deployment modes
- update labels and selectors to align with helm best practices
- general cleanup to align with helm best practices/patterns observed in `helm create`
- update values, README and _helpers accordingly
- bump image tag
- bump chart version

2018-03-19 20:40 UTC, rtluckie commented
/assign @unguiculus

2018-03-19 20:40 UTC, rtluckie commented
/assign @viglesiasce

2018-03-21 23:14 UTC, rtluckie commented
/assign @sameersbn

2018-03-27 17:53 UTC, unguiculus requested changes

2018-03-27 17:53 UTC, unguiculus commented on stable/minio/Chart.yaml
> +version: 0.6.0
Maybe this deserves a 1.0.0?

2018-03-27 17:54 UTC, unguiculus commented
/ok-to-test

2018-03-27 23:50 UTC, rtluckie commented on stable/minio/Chart.yaml
> +version: 0.6.0
@unguiculus SGTM.  Fixed.

2018-03-28 07:51 UTC, unguiculus commented
/lgtm

2018-03-28 07:52 UTC, merged