Add the ability to add extra env variables
helm/charts pull request #4291
Opened 2018-03-20 00:12 UTC by zapur1

**What this PR does / why we need it**:
This affects the `incubator/fluentd-cloudwatch` chart.

This adds the ability for the user to add custom environment variables to daemonset pod. For example the below could be added
```
- name: NODE_NAME
   valueFrom:
     fieldRef:
       fieldPath: spec.nodeName
```
Which allows the result to be used like
```
<filter kube-api-server-audit.*>
  @type record_modifier

  <record>
    node_hostname "#{ENV['NODE_NAME']}"
  </record>
</filter>
```
in the Fluentd config like

@jmcarp , @icereval , @kenden

2018-03-26 18:40 UTC, unguiculus requested changes

2018-03-26 18:40 UTC, unguiculus commented on incubator/fluentd-cloudwatch/README.md
> +| `envs`                          | Add pod environment variables (must be specified as a single line object)             | `[]`
Please rename this to `extraVars`. There are already quite some charts to use this. Let's be consistent.

2018-03-26 18:40 UTC, unguiculus commented on incubator/fluentd-cloudwatch/test-values.yml
> +envs:
What is this file for?

2018-03-26 18:40 UTC, unguiculus commented
/assign

2018-03-28 21:32 UTC, zapur1 commented
@unguiculus I have made those changes

2018-03-29 21:35 UTC, unguiculus commented
/ok-to-test

2018-03-29 21:38 UTC, unguiculus approved these changes

2018-07-02 19:56 UTC, unguiculus commented
/lgtm

2018-07-04 18:37 UTC, unguiculus commented
/approve

2018-07-04 18:42 UTC, merged