[stable/traefik] Allow annotations and labels on Service and UI Ingress
helm/charts pull request #434
Opened 2017-01-20 05:34 UTC by c-knowles

Should resolve https://github.com/kubernetes/charts/issues/334.

Allows for many additional use cases such as setup of various AWS ELB
and Route 53 annotations including use of
https://github.com/fairfaxmedia/area53.

I've avoided bumping the Chart version for now to avoid clashes with other PRs.

cc @krancour the chart maintainer

2017-01-20 22:04 UTC, krancour requested changes

2017-01-20 22:04 UTC, krancour commented on stable/traefik/README.md
> +| `service.labels`                | Additional labels for the Traefik Service definition                 | None                                      |
Can we make it clear that these are maps?

2017-01-20 22:05 UTC, krancour commented
This looks pretty good. I do want to manually test this.

2017-01-21 20:20 UTC, krancour requested changes

2017-01-21 20:20 UTC, krancour commented on stable/traefik/templates/dashboard-ingress.yaml
> +  {{- end }}
Testing this, I found that you're really going to have to wrap this in a double-if condition similar to what you have done in #414.

2017-01-21 20:20 UTC, krancour commented on stable/traefik/templates/service.yaml
> +  {{- end }}
Testing this, I found that you're really going to have to wrap this in a double-if condition similar to what you have done in #414.

2017-01-21 20:20 UTC, krancour commented on stable/traefik/templates/service.yaml
> +  {{- end }}
Testing this, I found that you're really going to have to wrap this in a double-if condition similar to what you have done in #414.

2017-01-22 03:42 UTC, c-knowles commented
@krancour I've updated those, there's still an assumption that `dashboard` exists but I think that's a fair assumption. I hope golang templates improve in that regard or Helm adds some custom functions to deal with this.

2017-01-22 19:00 UTC, krancour commented
> there's still an assumption that `dashboard` exists

That's an easier assumption to make, because a `dashboard` section has been present in the default `values.yaml` since the very first version of this chart-- which means it necessarily exists in anyone's existing (custom) `values.yaml`. By contrast, anyone who uses their existing `values.yaml` with the new / improved chart would be missing the sections we added the extra guards for. It's those folks that I wanted to look out for here. Backwards compatibility between the updated chart and old `values.yaml` is the name of the game.

2017-01-25 01:10 UTC, krancour commented
@c-knowles, I've manually tested this and it works great.

One question... do you think there's any value in allowing labels and annotations to be set the same way on the dashboard's service as well (if the dashboard is enabled)?

2017-01-25 01:55 UTC, c-knowles commented
@krancour could do if you wanted. I can't think of many use cases but perhaps some companies have requirements over labels, for example we like to label apps with a tier.

2017-01-25 02:59 UTC, krancour commented
@c-knowles up to you. If you can rationalize a use case for, add it. If not, then don't bother.

This LGTM either way.

2017-01-25 11:53 UTC, c-knowles commented
@krancour most of the ones I've thought of so far overlap with https://github.com/kubernetes/helm/issues/1800. I'd much prefer for label uniformity issues to be dealt with at a higher level rather than every chart. As for annotations, I can't spot much value right now. Let's skip it until a use case comes up?

2017-01-25 16:41 UTC, krancour commented
SGTM @c-knowles

2017-01-31 21:30 UTC, viglesiasce commented
@k8s-bot ok to test

2017-02-01 02:23 UTC, merged