[stable/artifactory] Small fix for ingress
helm/charts pull request #4373
Opened 2018-03-20 20:40 UTC by jainishshah17

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-03-23 02:29 UTC, maguro commented
/joke

2018-03-23 02:29 UTC, maguro commented
/meow

2018-03-23 05:02 UTC, eldada requested changes

2018-03-23 05:02 UTC, eldada commented on stable/artifactory/values.yaml
> +    loadBalancerIP:
Add `loadBalancerIP` to README.md

2018-03-23 05:02 UTC, eldada commented on stable/artifactory-ha/values.yaml
> +    loadBalancerIP:
Add `loadBalancerIP` to README.md

2018-03-23 20:50 UTC, jainishshah17 commented on stable/artifactory-ha/values.yaml
> +    loadBalancerIP:
done

2018-03-24 04:05 UTC, eldada approved these changes

2018-04-07 18:00 UTC, closed without merging