[stable/mysql] Adding BYO SSL certificates option
helm/charts pull request #4387
Opened 2018-03-21 15:21 UTC by alika

**What this PR does / why we need it**: This PR adds the option to setup SSL for MySQL connections by allowing the chart user to specify the CA certificate, server certificate, and server key in values file. 

**Special notes for your reviewer**: 

- I've also added a helm test to verify the SSL connection is setup correctly only when SSL has been enabled.
- To enable SSL you also need to enable a custom configuration in the `configurationFiles` section

2018-03-21 16:01 UTC, alika commented
/assign @scottrigby

2018-03-27 21:16 UTC, timstoop requested changes

2018-03-27 21:16 UTC, timstoop commented on stable/mysql/Chart.yaml
> +version: 0.3.7
You're adding new features, please bump the minor version of the Chart.

2018-03-27 21:16 UTC, timstoop commented
/ok-to-test

2018-04-02 19:14 UTC, timstoop commented
Please rebase and bump the version again, another commit got merged.

2018-04-03 22:49 UTC, alika commented
Apologies @timstoop. I seem to have really messed up this rebase. Is there an easy way to undo this or will this be easier to create a new PR?

2018-04-04 08:16 UTC, timstoop commented
/lgtm

2018-04-06 20:19 UTC, mattfarina commented
/cc @viglesiasce

because you're the maintainer

2018-04-06 20:42 UTC, mattfarina commented on stable/mysql/README.md
> +| `ssl.key`                            | Server key (private key)                  | `nil`                                                |
The wordpress chart is an example of one that does ssl and secrets with a slightly different pattern (]you can see it here](https://github.com/kubernetes/charts/blob/master/stable/wordpress/values.yaml#L170)). The idea is that setting the secret to use is different from passing in the values and creating a secret. This way you can use an outside secret, not managed, by the chart if you want.

2018-04-12 18:32 UTC, alika commented
@mattfarina How does this look now?

2018-04-24 16:53 UTC, mattfarina commented
/lgtm

2018-04-24 17:00 UTC, merged

2018-06-26 18:08 UTC, whereisaaron commented
Hi @alika, thank you very much for add the SSL support to this chart!

This PR also added a helm hook heath test. I personally don't want to also run that hook, as I prefer to leave that health check to the k8s health probes. Also, the current test embeds the MySQL root password in a ConfigMap, which kind of defeats the purpose of keeping it in a Secret 😄 

Could I request you add an `enabled` option to the `values.yaml` to give user the option to disable the test if users don't happen to want it?