rabbitmq-ha add prometheus operator stats and alerts
helm/charts pull request #4401
Opened 2018-03-21 21:57 UTC by bradenwright

**What this PR does / why we need it**:
This PR allows for stats to be exposed and scraped by the prometheus operator.  I've also setup some default alerts that I think would be helpful.

**Special notes for your reviewer**:
@etiennetremel please review

2018-03-22 15:55 UTC, bradenwright commented
/assign @etiennetremel

2018-03-22 15:57 UTC, bradenwright commented
/ok-to-test

2018-03-23 15:49 UTC, bradenwright commented
@etiennetremel please review when you have a chance.

2018-03-25 21:38 UTC, etiennetremel commented
Hi @bradenwright, thanks for spending the time to improve this chart.
I'm totally fine with the Prometheus exporter but assuming the user is using the Prometheus Operator seems wrong. Users should be able to spin-up their own version of Prometheus 1.x, 2.x or operator.
But maybe one of the repo admin can guide of us with best practices.

2018-03-25 21:45 UTC, etiennetremel requested changes

2018-03-25 21:45 UTC, etiennetremel commented on stable/rabbitmq-ha/templates/NOTES.txt
> +    {{ if .Values.secret.name }}
I might be looking at something old but where does this come from, I only the following in the values.yaml:
```
secret:
  autogenerate: true
```

2018-03-25 21:45 UTC, etiennetremel commented on stable/rabbitmq-ha/values.yaml
> +  autogenerate: true
This doesn't seem to be used anywhere?

2018-03-25 21:45 UTC, etiennetremel commented on stable/rabbitmq-ha/values.yaml
> +secret:
Could keep the file consistent and add descriptions for fields that require it?
Also, the README.md should be updated if you add new fields.

2018-03-25 21:45 UTC, etiennetremel commented on stable/rabbitmq-ha/values.yaml
> +  exporter:
I suggest removing the alerts section and flatten a bit as suggested in the chart best practices:
```
prometheusExporter:
  enabled: true
  [...]
```

2018-03-25 23:19 UTC, bradenwright commented
I'll see about making those changes.

And I agree that others may very well want support for Prometheus without the Operator.  I don't know the details of implementing without the operator, if someone else wanted to contribute supporting it without operator I'd be for it.

2018-03-27 20:11 UTC, timstoop requested changes
With regards to Prometheus without the Operator, it works with simple Pod or Service Annotations that Prometheus can discover and use to scrape for a certain endpoint. So by simply allowing custom annotation to the exporter Pod you'd be handling that case as well, if you'd like.

2018-03-27 20:11 UTC, timstoop commented on stable/rabbitmq-ha/Chart.yaml
> +version: 1.0.3
Your adding a new feature, so please bump the minor version.

2018-03-27 20:50 UTC, unguiculus commented
The service monitor for the operator should be optional in case a users wants to configure Prometheus integration with annotation as @timstoop mentioned.

2018-04-24 18:17 UTC, bradenwright commented
Ok so I was working on Kafka chart to add support for metrics as well.  I tried to keep changes here consistent with variable naming on Kafka chart:

https://github.com/kubernetes/charts/pull/5120

There was also an example of using Prometheus without the Operator, so I added code for that as well, but have no way to test it.

My apologies it took me a while to reply, other work trumped this for a little while.

2018-04-24 18:35 UTC, bradenwright commented
@etiennetremel if you can look over PR again when you have a chance, it would be much appreciated

2018-04-25 10:45 UTC, etiennetremel commented
Thanks, do you mind updating the README.md with the variable change you just made?

2018-04-26 16:13 UTC, bradenwright commented
@etiennetremel I added to the readme.  I also tried to make some tweaks to secrets, looks like some stuff was merge since I opened my PR, so tried to find a middle ground for var naming since I was adding more granularity.  I'm open to suggestions.

2018-04-27 19:33 UTC, timstoop commented
/ok-to-test
/assign

2018-04-28 02:05 UTC, bradenwright commented
/retest

2018-04-30 12:59 UTC, bradenwright commented
@timstoop @etiennetremel when you get a chance

2018-05-02 13:31 UTC, bradenwright commented
@timstoop @etiennetremel ping

2018-05-03 10:18 UTC, timstoop commented
/lgtm

2018-05-03 16:43 UTC, etiennetremel approved these changes
Thanks @bradenwright!

2018-05-03 17:21 UTC, bradenwright commented
Thanks for reviewing!  Sorry for the gap in between I know you basically did it 2x

2018-05-03 17:26 UTC, unguiculus commented
/assign

2018-05-03 18:31 UTC, bradenwright commented
Fixed merge conflict on chart version

2018-05-03 18:48 UTC, unguiculus requested changes
I don't think you need both `overrideName` and `autogenerate`. I'd prefer you keep `existingSecret`. This is what's commonly used. Also, I think `autogenerate` is misleading. It implies that certs are generated which is not the case.

You could create a partial for the secret name. Here's an example: https://github.com/kubernetes/charts/blob/master/stable/mongodb-replicaset/templates/_helpers.tpl#L34-L54.

2018-05-03 19:34 UTC, bradenwright commented
@unguiculus the use case I have that we implemented that way for is that we like to setup 1 secret per namespace in some situations and then have a few rabbitmq-ha releases using the same secret.

I don't see any drawback to doing it this way, just gives more flexibility.

2018-05-03 19:37 UTC, bradenwright commented
Certs have their own section so I did the identical thing there, have the ability to autogenerate and overrideName, I'd be open to moving them both to a more generic area, or renaming top level secret so its more descriptive if you have a better suggestion

2018-05-04 21:48 UTC, bradenwright commented
@unguiculus I updated the variable naming to use `existing` instead of `autogenerate` as requested.  I left the ability to override the name of the secret b/c we use that feature as I mentioned above.  Hopefully this satisfies both of us

2018-05-07 16:31 UTC, bradenwright commented
@unguiculus ping

2018-05-08 15:47 UTC, unguiculus commented
There's a separate PR for an exporter. It's probably better to add it as a dependency once it's merged.

cc @gianrubio

2018-05-09 02:12 UTC, bradenwright commented
@unguiculus @gianarb just to be clear this PR already includes the rabbitmq exporter

2018-05-09 02:22 UTC, bradenwright commented
@unguiculus @gianarb I didn't do a separate chart b/c I am running the rabbitmq-exporter as a sidecar and there isn't a way to do that with a dependency.  Running as a sidecar feel appropriate to me as the monitoring scales automatically with the pods, especially for monitoring things like rabbitmq nodes that are up.  Kafka chart is running a jmx exporter as a sidecar fwiw.

2018-05-10 15:39 UTC, gianrubio commented
I'd recommend to add the sidecar container in [rabbit-mq chart](https://github.com/kubernetes/charts/blob/master/stable/rabbitmq/README.md).

Adding a [`serviceMonitor`](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/examples/basic-auth/service-monitor.yaml) makes sense in this case but not deploying prometheus-operator because it should be deployed in a separate chart.

2018-05-10 15:59 UTC, bradenwright commented
@gianrubio not sure I fully follow, if I missed something please clarify.  

This chart has no dependencies on stable/rabbitmq chart, tbh I don't even know why both exist.  Really seems like the 2 should be merged together, as this chart can be run with 1 replica if desired, I really don't see the point of stable/rabbitmq, but that maybe another discussion.  If someone wants to add changes to stable/rabbitmq chart they can, I have no use case for stable/rabbitmq chart.  So feel that should be a separate PR.

This PR does deploy a `ServiceMonitor` but doesn't deploy Prometheus or Prometheus Operator, as you mention.

2018-05-10 19:50 UTC, gianrubio commented on stable/rabbitmq-ha/templates/alerts.yaml
> +{{- if .Values.prometheus.operator.alerts.labels }}
this line is duplicated on 41

2018-05-10 21:22 UTC, bradenwright commented
Also I'm looking to fix merge conflicts and it seems like there was just a PR merged that used `customSecret: false` instead of `existingSecret` which was already being used for Certificate. 
 @unguiculus I still haven't got confirmation from you, its says changes requested but I've replied to that.   I'm going to change it to be `existingSecret` since you mentioned earlier on this PR wanting to be consistent.

If you can please confirm if other changes are needed

2018-05-11 05:31 UTC, bradenwright commented
I updated the wording of variable with `customSecret`, `customConfigMap` to `existing` b/c I was asked to use wording for secret above, and then figured configmap should probably be consistent name with other variables.

2018-05-15 14:33 UTC, bradenwright commented
@unguiculus @timstoop @gianrubio any comments, changes, etc.  I've tried to make the changes requested but haven't had any feedback in a min.

2018-05-16 05:02 UTC, unguiculus commented
I still don't see why you need to override the name of the secret if it is created by the chart. Either you use an existing secret or you have the chart create it. Why would you want to change the name then?

Maybe I wasn't clear in my comments. I wanted you to change it such that `existingSecret` is not a boolean but refers to the name of the existing secret. If set, use it, and otherwise create a secret with the name being based on the `fullname` template.

2018-05-16 13:48 UTC, bradenwright commented
@unguiculus I'm doing both using an existing secret and overriding the name so it can be used for a few rabbitmq clusters.  The secret defaults to using a name with the release in it so I need to do both.

2018-05-16 14:32 UTC, bradenwright commented
I can make change you asked about having `existingSecret` double up as a boolean and override name.  The reason I didn't do that is I felt leaving it defaulting to template fullname seemed like an appropriate default, and to do that I'm gonna have to do some slight of hand in templates/_helpers, I thought it felt cleaner to do it in the values.

@unguiculus let me know if want me to make changes or not after explanation.

2018-05-16 14:34 UTC, steven-sheehy commented
@bradenwright I added fullnameOverride override value which is used in template "rabbitmq-ha.fullname". The secret will use that fullnameOverride so you can set that value if you don't want secret name to contain release name. Will that cover your use case?

2018-05-16 14:40 UTC, bradenwright commented
@steven-sheehy thanks for the suggestion, it wouldn't b/c I'd have to set the fullnameOverride to be the same for multiple helm installs, and they will conflict for resources chart tries to create.

2018-05-16 17:21 UTC, steven-sheehy commented
Maybe due how long this PR has been opened and since there's disagreement on only the secret changes those can be separated into a different PR? I'm very interested in having the prometheus exporter support that you so kindly implemented be merged in. Just my observation as an outsider, feel free to disregard.

2018-05-16 17:33 UTC, bradenwright commented
@steven-sheehy I hear you, I really want to get this merged too.  I've pushed back a deploy with my company 2x now, hoping to get this merged rather than deploying a fork.

I'll make changes that @unguiculus wants, I just need feedback at this point.  I feel its really close so I'd rather make the tweak and merge than go through another PR this late in the game.

2018-05-17 17:37 UTC, unguiculus commented
I don't think it makes sense to install the chart multiple times when one installation creates the secret and the others use that secret making them dependent on this installation. Uninstalling the release that installed the secret would break all other. If you need a shared secret you should install it separately.

2018-05-17 18:01 UTC, bradenwright commented
@unguiculus that's exactly what I'm trying to do (install secret separately), but after I manually create 1 secret I want to use it for multiple installs (I don't want to create a new secret for every install in the same namespace).  For instance we have a number of rabbitmq sandboxes and want to use the same existing secret for all of them.  My solution solves this issue.

2018-05-18 05:57 UTC, unguiculus commented
So, I think we're on the same line, but there seems to be some misunderstanding. If `existingSecret` is not a flag but contains the name of the secret, why would you need a name override? Here's an example:

https://github.com/kubernetes/charts/blob/master/incubator/keycloak/templates/_helpers.tpl#L42-L51

There are several charts that do it like this.

2018-05-22 17:43 UTC, bradenwright commented
@unguiculus I made the change requested.  I think it should be good to go now, but if anything else is needed let me know.

2018-05-25 09:10 UTC, unguiculus requested changes

2018-05-25 09:10 UTC, unguiculus commented on stable/rabbitmq-ha/values.yaml
> +      tag: latest
Use a stable version

2018-05-31 15:46 UTC, bradenwright commented
@unguiculus sorry that took a min, I was out of town and didn't have access to a computer.

2018-06-01 15:33 UTC, unguiculus approved these changes

2018-06-01 15:35 UTC, unguiculus commented
/lgtm

2018-06-01 15:43 UTC, merged

2018-06-05 09:26 UTC, francesco-beccaria commented
Hi @bradenwright, @unguiculus,
I have some doubts on how to use the changes made in this PR.
I installed `prometheus` using the stable chart, so I thought that meant I should not get the `operator` enabled, so I set:
```
operator:
  enabled: false
```
When I tried to upgrade my existing rabbitmq-ha release, Helm complained with the message:
```
Error: UPGRADE FAILED: failed to create resource: namespaces "monitoring" not found
```
I didn't modify the default `# Namespace Prometheus is installed in`
```
operator:
  serviceMonitor:
    namespace: monitoring
```
as it's indented under the `operator` section, which I disabled, and I was expecting it would not be considered.

I'm probably just confused.

Any chance you could help me understand?

Also, I noticed that the default for `prometheus.exporter.enabled` in the `Readme` is set to `true`, but I think it should be `false`? I know it's "just" the `Readme` but I thought I'd point it out.

Thanks in advance,
Fran

2018-06-05 10:30 UTC, francesco-beccaria commented
To add to my confusion, I saw the `monitoring` `namespace` is also in the `alerts.yaml` file, but in this case it's hardcoded.
Is it supposed to be the same as in the `servicemonitor.yaml` file (`{{ .Values.prometheus.operator.serviceMonitor.namespace }}`) or is it a different thing?