Fix Vault for `cert` and `token` auth
helm/charts pull request #4425
Opened 2018-03-23 03:31 UTC by arbourd

**What this PR does / why we need it**:

- `caCert` was renamed to `useCaCert` but not in README or values.yaml
- `vault-client-key` and `vault-client-cert` should only need to be set
  when the auth mode has been set to `cert`. Without the check, `approle`
  and `token` auth will fail (due to Go not being able to parse the PEM
  of "")

2018-03-26 16:02 UTC, arbourd commented
/assign @william-tran

2018-03-27 18:59 UTC, timstoop approved these changes

2018-03-27 18:59 UTC, timstoop commented
/lgtm

2018-03-27 20:23 UTC, unguiculus commented
/ok-to-test

2018-03-27 20:23 UTC, unguiculus commented
/lgtm

2018-03-27 20:53 UTC, william-tran approved these changes

2018-03-27 20:54 UTC, william-tran commented
Thanks for the fixes @arbourd

2018-03-27 20:54 UTC, william-tran commented
/lgtm

2018-03-27 21:48 UTC, william-tran requested changes

2018-03-27 21:48 UTC, william-tran commented on stable/concourse/Chart.yaml
> +version: 1.0.7
You'll need to bump the chart version to 1.0.8 as another PR was merged before yours.

2018-03-28 12:23 UTC, arbourd commented
I bumped the minor version because 1.0.x will cause any vault configuration to break. Let me know if you'd prefer a patch.

2018-03-28 13:42 UTC, timstoop commented
/lgtm

2018-03-28 13:43 UTC, merged