[stable/sonatype-nexus] fix reusability of existing claim
helm/charts pull request #4438
Opened 2018-03-23 14:17 UTC by rodesousa

Deployment does not use the existing volume claim name when mounting
volume

2018-03-23 14:22 UTC, rodesousa commented
/assign @unguiculus

2018-03-28 08:27 UTC, timstoop requested changes

2018-03-28 08:27 UTC, timstoop commented on stable/sonatype-nexus/Chart.yaml
> +version: 0.1.9
This adds a new feature so please bump the minor version.

2018-03-28 09:29 UTC, rodesousa commented
done @timstoop

2018-03-28 10:29 UTC, timstoop commented
/ok-to-test

2018-03-28 10:31 UTC, timstoop commented
/lgtm

2018-03-28 11:10 UTC, timstoop commented
/lgtm

2018-03-29 20:28 UTC, unguiculus commented
/ok-to-test

2018-03-29 20:28 UTC, unguiculus commented
/lgtm

2018-03-29 20:33 UTC, merged