Fix redis-ha README.md with correct server values param
helm/charts pull request #4444
Opened 2018-03-23 22:02 UTC by victortrac

https://github.com/kubernetes/charts/blob/master/stable/redis-ha/templates/redis-server-deployment.yaml#L34-L35 contains this:

```yaml
        resources:
{{ toYaml .Values.resources.server | indent 10 }}
```

The README.md refers to keys for master/slave that aren't accurate.

2018-03-26 11:19 UTC, carrodher requested changes
You should increment chart version (`version`) in `Chart.yaml`

2018-03-26 23:10 UTC, timstoop requested changes

2018-03-26 23:10 UTC, timstoop commented on stable/redis-ha/README.md
> +| `resources.server`               | CPU/Memory for master/slave nodes resource requests/limits                                                                   | Memory: `200Mi`, CPU: `100m`
All changes, however small, require a bump in the Charts.yaml `version`. For this, you can just use a patch number increase.

2018-05-11 08:13 UTC, unguiculus commented
/ok-to-test

2018-05-11 08:20 UTC, unguiculus commented
/assign

2018-05-11 08:22 UTC, unguiculus commented
/lgtm

2018-05-23 18:18 UTC, timstoop commented
/retest

2018-05-23 18:22 UTC, merged