[stable/neo4j] Add support for imagePullSecrets
helm/charts pull request #4454
Opened 2018-03-25 17:02 UTC by olemarkus

@mneedham 

**What this PR does / why we need it**:
Adds support for registry secrets

2018-03-26 22:46 UTC, timstoop requested changes
Looks fine to me and a good feature to add.

2018-03-26 22:46 UTC, timstoop commented on stable/neo4j/Chart.yaml
> +version: 0.5.2
This adds a new feature, so you can bump the minor version.

2018-03-27 06:27 UTC, timstoop approved these changes
Thanks! Looks fine now.

2018-03-27 06:27 UTC, timstoop commented
/lgtm

2018-03-27 06:29 UTC, timstoop commented
/assign @mattfarina

2018-03-27 16:13 UTC, unguiculus requested changes

2018-03-27 16:13 UTC, unguiculus commented on stable/neo4j/values.yaml
> +# ImagePullSecret: registry-secret
lower case: `imagePullSecret`

2018-03-27 16:20 UTC, olemarkus commented on stable/neo4j/values.yaml
> +# ImagePullSecret: registry-secret
Good catch

2018-03-27 18:44 UTC, timstoop commented
/lgtm again

2018-03-27 20:24 UTC, unguiculus commented
/ok-to-test

2018-03-27 20:39 UTC, unguiculus approved these changes

2018-03-27 20:39 UTC, unguiculus commented
/lgtm

2018-03-27 21:45 UTC, merged