Added `extraVolumes` configuration point to attach additional
helm/charts pull request #4456
Opened 2018-03-25 23:00 UTC by logicfox

volumes to the nginx-controller pod in order to address
use-cases where additional configuration files may be needed,
as in the case of custom ModSecurity configuration.

**What this PR does / why we need it**: 
Added `extraVolumes` configuration point to attach additional volumes to the nginx-controller pod in order to address use-cases where additional configuration files may be needed, as in the case of custom ModSecurity configuration.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4417

**Special notes for your reviewer**:
The specification of additional volumes is now generic and supersedes the current mechanism of mounting the nginx.tmpl. The current way of specifying this file has been preserved to maintain compatibility with existing deployments.

2018-03-26 22:44 UTC, timstoop requested changes
So I don't personally use this controller that much, but is there a specific reason why you wouldn't want to add those ModSecurity files via a ConfigMap? I don't think it's very user friendly to require users to create their own Volume with the correct data in there, when they simply want to add some files. I would prefer to see this rewritten to make use of ConfigMaps instead, as it's much easier to add those.

2018-03-26 22:44 UTC, timstoop commented on stable/nginx-ingress/Chart.yaml
> +version: 0.11.3
This PR adds a new feature, so you can bump the minor version.

2018-03-27 00:18 UTC, logicfox commented
The ModSecurity WAF ships with the default OWASP ruleset which unfortunately is quite strict resulting in false positives. The typical solution suggested is to customise the ruleset. 

This often results in modifying/overriding multiple files in the OWASP ruleset located in `/etc/nginx/owasp-modsecurity-crs`. Putting this kind of configuration in the `values.yaml` would bloat it considerably. 

Besides, a further resolving was that the addition of custom volumes and mounts would allow for edge use-cases driven by configuration, like the WAF, to work without additional changes to the chart. 

The typical ruleset that ships with the ingress controller is here:
https://github.com/SpiderLabs/owasp-modsecurity-crs/tree/v3.0/master/rules

2018-03-27 14:30 UTC, timstoop commented
I understand, but I wonder if for the regular user adding a Volume with those files is really that easy. You can create a ConfigMap using the source files instead and mount that one. I'd expect that to be a lot easier to do for most people.

2018-03-27 17:34 UTC, unguiculus commented
Closing this in favor of #3983.

@timstoop You may want to follow the discussion here: #4283.

2018-03-27 17:34 UTC, closed without merging