Optionally set mariadb securityContext
helm/charts pull request #4464
Opened 2018-03-26 16:40 UTC by djzager

**What this PR does / why we need it**:

This makes it possible to disable the `securityContext` settings when using mariadb, for example: when installing the chart in OpenShift.

**Special notes for your reviewer**:

N/A

2018-03-26 16:47 UTC, djzager commented
Manual Testing:

```
$  helm install ./mariadb-2.1.15.tgz --name=dz-test --namespace=mariadb-test --set securitySettings.enabled=false

$  oc get all -n mariadb-test
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/dz-test-mariadb   1         1         1            1           1m

NAME                            DESIRED   CURRENT   READY     AGE
rs/dz-test-mariadb-7457949548   1         1         1         1m

NAME                                  READY     STATUS    RESTARTS   AGE
po/dz-test-mariadb-7457949548-wlwbj   1/1       Running   0          1m

NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
svc/dz-test-mariadb   ClusterIP   172.30.92.234   <none>        3306/TCP   1m
```

2018-03-26 16:48 UTC, djzager commented
/assign @sameersbn @prydonius

2018-03-26 22:23 UTC, timstoop requested changes

2018-03-26 22:23 UTC, timstoop commented on stable/mariadb/Chart.yaml
> +version: 2.1.15
For a new feature, the minor version should increase.

2018-03-27 03:24 UTC, sameersbn commented on stable/mariadb/Chart.yaml
> +version: 2.1.15
@timstoop  I believe a minor version bump is not required here. We normally require that the minor versions be updated when there is a breaking change. This commit adds an optional parameter to turn off the `securityContext` configuration (enabled by default), so it should be fine if existing users upgrade to a chart version that has this change.

2018-03-27 03:25 UTC, sameersbn commented
/ok-to-test
/lgtm

2018-03-27 03:29 UTC, merged

2018-03-27 06:31 UTC, timstoop commented on stable/mariadb/Chart.yaml
> +version: 2.1.15
Not to contradict you, but I've been told on other PRs that any new option would warrant a minor version increase. I'll bring it to the table in #3011, as it's probably good to have some guidelines!