Added chart for firmament-poseidon
helm/charts pull request #4479
Opened 2018-03-27 17:38 UTC by nikita15p

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-03-27 18:01 UTC, nikita15p commented
/assign @dhilipkumars

2018-03-27 18:11 UTC, dhilipkumars commented
@nikita15p Thanks for the PR, there is a lot needs to be done to get this PR in a good shape.  Please have a look at [best practices](https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md).

Once all the work is done we could remove [WIP] from the titile. 

Pleae sign the Linux Foundation CLA to start with.

2018-04-02 05:43 UTC, nikita15p commented
Bump to verify CLA.

2018-04-07 09:30 UTC, unguiculus commented
@nikita15p You created this as a WIP and did not specify any description. With all due respect but I'm not inclined to review this. We get lots of PRs here which is great and keeps us maintainers busy. But next time, please finish you stuff first and then create a PR. If you have questions on how to implement things, please join Slack and ask there before creating a PR. Thank you.

2018-06-18 21:51 UTC, dhilipkumars commented
/ok-to-test

2018-06-18 21:54 UTC, dhilipkumars commented
@kubernetes/charts-maintainers PTAL.

2018-06-22 08:42 UTC, unguiculus requested changes
I made an initial review. Please read our review guideliones and apply best practices. Apply my comments throughout the chart.

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/templates/_helpers.tpl
> +{{- end -}}
The two separarte fullname partials may clash. Also, all partials should have the chart name prefix. how about toing this:

```
{{- define "firmament-poseidon.firmamentFullname" -}}
{{- template "firmament-poseidon.fullname" . -}}-firmament
{{- end -}}

{{- define "firmament-poseidon.poseidonFullname" -}}
{{- template "firmament-poseidon.fullname" . -}}-poseidon
{{- end -}
```

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/templates/firmament_deployment.yaml
> +apiVersion: apps/v1beta1
Use `apps/v1`

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/templates/firmament_deployment.yaml
> +  namespace: {{ .Values.namespace }}
Why do you need the namespace here? It can be passed to the Helm CLI when installing the chart.

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/templates/firmament_deployment.yaml
> +        scheduler: {{ .Values.firmament.scheduler }}
Pods should at least have `app` and `release` labels.

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/templates/firmament_service.yaml
> +    scheduler: firmament
While you make the label configurable in the deployment, you hard-code it here. Common practice is to use a `component` label. Add `app` and `release` labels.

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/templates/poseidon_service.yaml
> +  name: {{.Values.serviceAccount.name}}
You partial from `_helpers.tpl`

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/templates/firmament_deployment.yaml
> +    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
Use `chart` partial everywhere.

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/templates/poseidon_serviceaccount.yaml
> +  name: {{.Values.serviceAccount.name}}
You partial from `_helpers.tpl`

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/templates/rbac.yaml
> +  name: {{ .Values.clusterrolebinding.name }}
Resource names should be based on the fullname parial. Is there a reason why you want this to be configurable?

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/values.yaml
> +  name: poseidon
Leave default empty

2018-06-22 08:42 UTC, unguiculus commented on stable/firmament-poseidon/templates/poseidon_deployment.yaml
> +      serviceAccountName: {{.Values.serviceAccount.name}}
Use partial for service account

2018-06-26 13:58 UTC, dhilipkumars commented
@nikita15p Could you please apply all the review comments on this chart?

2018-11-04 11:20 UTC, closed without merging