Update stable/chronograf/README.md
helm/charts pull request #4490
Opened 2018-03-28 15:29 UTC by AdamDang

Delete dulicated word.
Line 71: a Persistent Volume volume

2018-03-28 15:39 UTC, timstoop commented
/ok-to-test

2018-03-28 15:39 UTC, timstoop commented
/lgtm

2018-03-28 15:44 UTC, timstoop commented
The reason that it's failing is that some of the requirements of the Chart.yaml have changed recently and this Chart is missing an appVersion key. You could add it and simply set it to the version of the image that's default. That would move this forward and fix it for future commits to this Chart as well.

2018-03-28 16:20 UTC, timstoop commented
/lgtm

2018-03-28 16:21 UTC, AdamDang commented
@timstoop
Thanks a lot. I've add a appVersion key.

2018-03-28 23:06 UTC, AdamDang commented
/assign @foxish

2018-03-29 04:30 UTC, sameersbn requested changes

2018-03-29 04:30 UTC, sameersbn commented on stable/chronograf/Chart.yaml
> +appVersion: "0.4.3"
should probably be 1.3, as seen in https://github.com/AdamDang/charts/blob/48692b2314e44bf3881b5e542e84977bf1101802/stable/chronograf/values.yaml#L5

2018-03-29 05:27 UTC, sameersbn requested changes

2018-03-29 05:27 UTC, sameersbn commented on stable/chronograf/Chart.yaml
> +appVersion: 1.3-alpine
you dont need to add the `-alpine` part. it should just be the version part

2018-03-29 06:49 UTC, sameersbn approved these changes

2018-03-29 06:49 UTC, sameersbn commented
/lgtm

2018-03-29 06:49 UTC, sameersbn commented
/lgtm

2018-03-29 06:54 UTC, merged