Update stable/influxdb/README.md
helm/charts pull request #4491
Opened 2018-03-28 15:33 UTC by AdamDang

Delete dulicated word.
 Line 72: a Persistent Volume volume

2018-03-28 15:39 UTC, timstoop commented
/ok-to-test

2018-03-28 15:39 UTC, timstoop commented
/lgtm

2018-03-28 15:43 UTC, timstoop commented
The reason that it's failing is that some of the requirements of the Chart.yaml have changed recently and this Chart is missing an appVersion key. You could add it and simply set it to the version of the image that's default. That would move this forward and fix it for future commits to this Chart as well.

2018-03-28 16:25 UTC, timstoop commented
/lgtm

2018-03-28 16:25 UTC, AdamDang commented
@timstoop Thanks! I've add the appVersion key.

2018-03-28 23:07 UTC, AdamDang commented
/assign @lachie83

2018-03-29 04:28 UTC, sameersbn requested changes

2018-03-29 04:28 UTC, sameersbn commented on stable/influxdb/Chart.yaml
> +appVersion: 0.8.4
looking at https://github.com/AdamDang/charts/blob/5afd5234e898ab4d0a79e28016d6bceb554b8bca/stable/influxdb/values.yaml#L5, the appVersion should probably be `1.4`

2018-03-29 05:27 UTC, sameersbn requested changes

2018-03-29 05:27 UTC, sameersbn commented on stable/influxdb/Chart.yaml
> +appVersion: 1.4-alpine
you dont need to add the `-alpine` part. it should just be the version part

2018-03-29 06:48 UTC, sameersbn approved these changes

2018-03-29 06:48 UTC, sameersbn commented
/lgtm

2018-03-29 06:54 UTC, merged