Update stable/postgresql/README.md
helm/charts pull request #4495
Opened 2018-03-28 15:48 UTC by AdamDang

Delete dulicated word.
 Line 107: a Persistent Volume volume

2018-03-28 15:49 UTC, timstoop commented
/ok-to-test

2018-03-28 15:49 UTC, timstoop commented
/lgtm

2018-03-28 15:52 UTC, timstoop commented
The reason that it's failing is that some of the requirements of the Chart.yaml have changed recently and this Chart is missing an appVersion key. You could add it and simply set it to the version of the image that's default. That would move this forward and fix it for future commits to this Chart as well. (Do I sound like a broken record yet? ;-) )

2018-03-28 16:31 UTC, AdamDang commented
Thanks @timstoop I've add the appVersion key.

2018-03-28 16:49 UTC, timstoop commented
/lgtm

2018-03-28 23:12 UTC, AdamDang commented
/assign @unguiculus

2018-03-29 04:25 UTC, sameersbn requested changes

2018-03-29 04:25 UTC, sameersbn commented on stable/postgresql/Chart.yaml
> +appVersion: 0.9.4
@AdamDang the appVersion should reflect the version of the psql server installed by the chart which is `9.6.2`

2018-03-29 05:12 UTC, AdamDang commented
@sameersbn 
 I've modified the appVersion to 9.6.2. Thanks,

2018-03-29 05:13 UTC, sameersbn approved these changes

2018-03-29 05:13 UTC, sameersbn commented
/lgtm

2018-03-29 05:14 UTC, merged