Added Elasticsearch Curator chart
helm/charts pull request #4515
Opened 2018-03-29 14:11 UTC by tmestdagh

This PR adds the elasticsearch curator Helm chart.
After installing this chart, a CronJob will be created which runs the curator according to a schedule and configuration you can set.

2018-03-29 14:22 UTC, tmestdagh commented
/assign @gianrubio

2018-03-29 14:33 UTC, gianrubio commented on incubator/elasticsearch-curator/README.md
> +$ helm install stable/elasticsearch-curator
should be incubator

2018-03-29 14:35 UTC, gianrubio commented on incubator/elasticsearch-curator/templates/configmap.yaml
> +  name: curator-config
you missed labels here

2018-03-29 14:37 UTC, gianrubio commented on incubator/elasticsearch-curator/templates/NOTES.txt
> +    kubectl -n logging delete job -l app=elasticsearch-curator
don't hardcode labels here, use app={{ template "elasticsearch-curator.name" . }}

2018-03-29 14:42 UTC, gianrubio commented on incubator/elasticsearch-curator/templates/cronjob.yaml
> +apiVersion: batch/v1beta1
don't hardcode the apiVersion here, see these example [helper](https://github.com/kubernetes/charts/blob/master/incubator/jaeger/templates/_helpers.tpl#L3-L12) and [how to apply it](https://github.com/kubernetes/charts/blob/ae2a474b0c832edc92345bd87e48130c50ced50c/incubator/jaeger/templates/spark-cronjob.yaml#L2-L3)

2018-03-29 14:43 UTC, gianrubio requested changes
just minor changes

2018-03-29 18:51 UTC, timstoop requested changes

2018-03-29 18:51 UTC, timstoop commented on incubator/elasticsearch-curator/values.yaml
> +resources: {}
This one is not in the table on your README.

2018-03-29 18:51 UTC, timstoop commented on incubator/elasticsearch-curator/values.yaml
> +nodeSelector: {}
This one and the next two are also not in you README.

2018-03-30 10:03 UTC, gianrubio commented
/lgtm

2018-03-30 10:04 UTC, gianrubio commented
/ok-to-test

2018-03-30 10:10 UTC, timstoop commented
/lgtm too

2018-03-30 11:06 UTC, tmestdagh commented
/assign @linki

2018-03-30 16:29 UTC, unguiculus requested changes

2018-03-30 16:29 UTC, unguiculus commented on incubator/elasticsearch-curator/OWNERS
> +  - gianrubio
@gianrubio I guess you should be added as maintainer as well.

2018-03-30 16:29 UTC, unguiculus commented on incubator/elasticsearch-curator/templates/cronjob.yaml
> +{{- if or (.Capabilities.APIVersions.Has "batch/v1beta1") (.Capabilities.APIVersions.Has "batch/v2alpha1") -}}
We shouldn't have to support `batch/v2alpha1` any more.

2018-03-30 16:29 UTC, unguiculus commented on incubator/elasticsearch-curator/templates/cronjob.yaml
> +              - name: config-volume
Make list indentation consistent. This should indent one more level.

2018-03-30 16:29 UTC, unguiculus commented
/assign

2018-04-03 12:11 UTC, gianrubio commented
/lgtm
/ok-to-test

2018-04-03 15:19 UTC, unguiculus requested changes

2018-04-03 15:19 UTC, unguiculus commented on incubator/elasticsearch-curator/templates/_helpers.tpl
> +{{/*
Remove obsolete comment.

2018-04-03 15:19 UTC, unguiculus commented on incubator/elasticsearch-curator/templates/_helpers.tpl
> +{{/*
This comment belongs to the name partial below.

2018-04-05 11:40 UTC, gianrubio commented
/lgtm
/ok-to-test

2018-04-07 11:52 UTC, unguiculus commented
/lgtm

2018-04-07 12:04 UTC, merged

2018-04-09 14:07 UTC, tmestdagh commented
PullRequest got merged!  Thanks for the reviews @gianrubio @timstoop @unguiculus