[stable/prometheus]: remove unnecessary clusterrolebindings for alert…
helm/charts pull request #4516
Opened 2018-03-29 15:35 UTC by eviln1

**What this PR does / why we need it**:
This PR removes unneeded `clusterRoleBindings` for `node-exporter` and `alertmanager` components.
Since they do not communicate with the kubernetes API, they do not need any kind of RBAC.
The `clusterRoleBindings` that were created, however, gave the `cluster-admin` role to `node-exporter` and `alertmanager` service accounts.

See https://github.com/kubernetes/charts/pull/1443#pullrequestreview-56912581

2018-03-29 15:37 UTC, eviln1 commented
/assign @mgoodness

2018-03-29 18:52 UTC, timstoop commented
/ok-to-test
/lgtm

2018-03-30 08:33 UTC, eviln1 commented
Rebased and resolved conflicts after https://github.com/kubernetes/charts/pull/4397 was merged.

2018-03-30 08:34 UTC, timstoop commented
/lgtm

2018-03-30 08:41 UTC, eviln1 commented
/retest

2018-03-30 08:58 UTC, unguiculus commented
Would you mind updating this to match our current RBAC best practices?

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

2018-03-30 08:58 UTC, unguiculus commented
/assign

2018-03-30 12:01 UTC, timstoop commented
/lgtm

2018-03-30 16:24 UTC, unguiculus requested changes

2018-03-30 16:24 UTC, unguiculus commented on stable/prometheus/values.yaml
> +    create: false
Set all defaults to `true`.

2018-04-03 08:30 UTC, eviln1 commented
/retest

2018-04-03 09:33 UTC, eviln1 commented
@unguiculus all should be good now.

2018-04-04 15:04 UTC, eviln1 commented
@mgoodness any chance of your blessing ?

2018-04-07 09:24 UTC, unguiculus requested changes
There should be a manifest for each of the service accounts you configured. The conditions to create them must be based on the respective `create` flag, not `rbac.create` which is only for RBAC resources, not service accounts.

The readme must be updated regarding service accounts.

2018-04-10 12:46 UTC, eviln1 commented
@unguiculus Hopefully this is suitable.

2018-04-12 14:56 UTC, unguiculus commented
Next time please merge instead of rebasing, so Github can show your changes. Thanks.

2018-04-12 14:59 UTC, unguiculus approved these changes

2018-04-12 14:59 UTC, unguiculus commented
/lgtm

2018-04-12 16:08 UTC, merged