[stable/redis-ha] Consistent label "name" for all deployments (Issue 4517)
helm/charts pull request #4518
Opened 2018-03-29 16:51 UTC by roychri

**What this PR does / why we need it**:

Make the label "name" of the deployments consistent.

**Which issue this PR fixes**:

fixes #4517

**Special notes for your reviewer**:

I didn't know if I should have bumped the version or not or if that is done when you pull, I am new to this contributing stuff. Let me know how I can improve things.

@smileisak  @ianmaddox

2018-03-29 16:54 UTC, roychri commented
/assign @linki

2018-03-29 18:54 UTC, timstoop commented
/ok-to-test
/lgtm

2018-03-29 22:15 UTC, unguiculus commented
I'd prefer it if you update the chart to have standard labels. See review guidelines.

https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

2018-03-29 22:48 UTC, roychri commented
@unguiculus Standard labels are already being addressed by the template `labels.standard`.
However, I see that `app` is defined both in the deploy file and then in the template `labels.standard` and that it uses a non standard label called `name`.

Do you mean that I should do one or more of the following?
* Remove the dupe `app` label
* Use the name instead of fullname for the `app` label
* Remove the non standard `name` label
* Add the `component` label (since we are using 2 components)

Or are you referring to something else like not using a template for the standard labels?

Thanks.

2018-03-30 09:38 UTC, unguiculus commented
Sorry, I overlooked that standard labels are set. Dupes should be removed, the `app` label in `standard.labels` is correct. Adding components would be a good thing as well as namespacing. Compare with what `helm create` using Helm 2.8+ give you.

2018-03-30 16:36 UTC, unguiculus requested changes
Test pods should also have standard labels.

2018-03-30 17:07 UTC, roychri commented
@unguiculus oops, my bad. I followed this and they do not use standard labels on this page.
Maybe I should do a PR to include standard labels on that page too! :)
https://github.com/kubernetes/helm/blob/master/docs/chart_tests.md
I will update my PR as soon as I figure out a way to fix my local and remote repo which I think I screwed up when trying to put the previous change. I am new to this fork/contrib stuff...

2018-03-30 22:04 UTC, roychri commented
/retest

2018-03-30 22:11 UTC, roychri commented
@unguiculus Sorry about all the activity, I fixed my local repo and pushed the changes for the standard labels in the tests too.

2018-04-20 20:28 UTC, roychri commented
@unguiculus Are my changes appropriate for what you were expecting?

2018-04-22 07:43 UTC, unguiculus requested changes
Sorry for the delay.

2018-04-22 07:43 UTC, unguiculus commented on stable/redis-ha/templates/tests/test-redis-master-service.yaml
> +  name: "{{ .Release.Name }}-master-service-test"
{{ template "redis-ha.fullname" . }}-master-service-test

2018-04-22 07:43 UTC, unguiculus commented on stable/redis-ha/templates/tests/test-redis-sentinel-service.yaml
> +  name: "{{ .Release.Name }}-sentinel-service-test"
{{ template "redis-ha.fullname" . }}-sentinel-service-test

2018-04-22 07:43 UTC, unguiculus commented on stable/redis-ha/templates/tests/test-redis-slave-service.yaml
> +  name: "{{ .Release.Name }}-slave-service-test"
{{ template "redis-ha.fullname" . }}-slave-service-test

2018-04-25 01:45 UTC, roychri commented on stable/redis-ha/templates/tests/test-redis-master-service.yaml
> +  name: "{{ .Release.Name }}-master-service-test"
Changed

2018-04-25 01:45 UTC, roychri commented on stable/redis-ha/templates/tests/test-redis-sentinel-service.yaml
> +  name: "{{ .Release.Name }}-sentinel-service-test"
Changed

2018-04-25 01:45 UTC, roychri commented on stable/redis-ha/templates/tests/test-redis-slave-service.yaml
> +  name: "{{ .Release.Name }}-slave-service-test"
Changed

2018-04-25 03:23 UTC, unguiculus commented
/lgtm

2018-04-25 03:25 UTC, merged