[stable/traefik] Add Entrypoint whiteListSourceRange support
helm/charts pull request #4522
Opened 2018-03-30 02:33 UTC by colinhoglund

**What this PR does / why we need it**:

Adds the ability to add `whiteListSourceRange` for Entrypoints. This is useful for long whitelists that might hit API limits in cloud providers when using `loadBalancerSourceRanges`

2018-03-30 02:34 UTC, colinhoglund commented
/assign @krancour

2018-03-30 07:05 UTC, timstoop commented
We set the whitelists in the Ingress resources, what would be a scenario where you prefer it in the traefik config?

2018-03-30 07:06 UTC, timstoop requested changes

2018-03-30 07:06 UTC, timstoop commented on stable/traefik/Chart.yaml
> +version: 1.27.1
This would add a feature, so please increment the minor component of the version.

2018-03-30 07:06 UTC, timstoop commented
/ok-to-test

2018-03-30 14:25 UTC, colinhoglund commented
@timstoop Thanks for the review. The idea behind this change was to allow user's to set a sort of "global" whitelist at the Entrypoints for cases where the whitelist might not change across the various ingress resources. However, it should also be noted that once 1.6 is released, this will need to be updated to support the new syntax for `X-Forwarded-For` support (https://github.com/containous/traefik/pull/3070).

Apologies is this is at all misinformed, as i'm fairly new to traefik.

2018-03-30 18:37 UTC, timstoop commented
Not misinformed at all, it's a good reason!

2018-03-30 18:37 UTC, timstoop commented
/ok-to-test
/lgtm

2018-04-05 04:46 UTC, krancour commented
/lgtm

2018-04-05 04:50 UTC, merged