[incubator/openmpi] generic openmpi support
helm/charts pull request #4549
Opened 2018-03-31 07:42 UTC by cheyang

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

This PR is for 

**Special notes for your reviewer**:

2018-03-31 10:28 UTC, cheyang commented
/assign @timstoop , PTAL. thanks in advanced.

2018-03-31 12:00 UTC, timstoop commented
I don't mind taking a look at it this evening, when I have a bit more time, but I overlook a lot of things with such large commits, so I tend to leave them to the more experienced reviewers. It's not good for my ego when I add a LGTM and the next reviewer finds several glaring problems ;-)

2018-03-31 12:36 UTC, cheyang commented
I see, thanks. @timstoop

2018-04-01 09:02 UTC, timstoop requested changes
Clear and concise, I like it.

2018-04-01 09:02 UTC, timstoop commented on incubator/openmpi/README.md
> +| `persistence.pvc.matchLabels`| the selector for pv | `{}` |
I know this is nit-picky, but can you please align the pipe-symbols?

2018-04-01 09:02 UTC, timstoop commented on incubator/openmpi/values.yaml
> +  privileged: true
This line needs to move either up or down, so `resources` is 'connected' to the example resources.

2018-04-02 00:48 UTC, cheyang commented
Updated based on comments, thx.

2018-04-02 19:09 UTC, timstoop commented
/ok-to-test
/lgtm

2018-04-03 11:59 UTC, cheyang commented
/assign @sameersbn

2018-04-07 10:05 UTC, unguiculus requested changes

2018-04-07 10:05 UTC, unguiculus commented on incubator/openmpi/templates/config.yaml
> +    app: {{ template "openmpi.fullname" . }}
app: {{ template "openmpi.name" . }}

2018-04-07 10:05 UTC, unguiculus commented on incubator/openmpi/templates/statefulset.yaml
> +    chart: {{ template "openmpi.chart" . }}
Remove `release` and `heritage` labels from selector.

2018-04-07 10:05 UTC, unguiculus commented on incubator/openmpi/templates/statefulset.yaml
> +      chart: {{ template "openmpi.chart" . }}
Remove `release` and `heritage` labels from selector.

2018-04-07 10:05 UTC, unguiculus commented on incubator/openmpi/templates/config.yaml
> +  name: {{ template "openmpi.fullname" . }}-cm
I'd remove the suffix from the name.

2018-04-07 10:05 UTC, unguiculus commented on incubator/openmpi/templates/service.yaml
> +  name: {{ template "openmpi.fullname" . }}-svc
I'd remove the suffix from the name.

2018-04-07 10:05 UTC, unguiculus commented on incubator/openmpi/templates/statefulset.yaml
> +    role: mpiworker
Is the `role` label required, since this is the only role I see here?

2018-08-08 14:01 UTC, closed without merging