[stable/elastalert] Allow communication with https ES instances
helm/charts pull request #4617
Opened 2018-04-03 09:29 UTC by AlexRRR

**What this PR does / why we need it**:
Currently it is not possible to communicate with https only endpoints (i.e. AWS Elasticsearch instances) enabling this simple flag in the configuration allows it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-03 09:37 UTC, AlexRRR commented
CLA signed

2018-04-03 11:08 UTC, timstoop commented
You also need to bump the minor version in Chart.yaml, all changes in a chart require a version bump and as you're adding a new feature, you can bump the minor.

2018-04-03 11:46 UTC, AlexRRR commented
Thanks for the heads up @timstoop, I've bumped the minor version of the chart to `0.1.3`

2018-04-04 12:33 UTC, timstoop commented
That's the patch level :) You can bump it to 0.2.0, as you're adding a new feature and can thus bump the minor (MAJOR.MINOR.PATCH).

2018-04-07 06:24 UTC, AlexRRR commented
I see! Thanks for the hand-holding @timstoop , really appreciate it

2018-04-07 07:17 UTC, timstoop commented
/ok-to-test
/lgtm

2018-04-07 14:07 UTC, unguiculus requested changes

2018-04-07 14:07 UTC, unguiculus commented on stable/elastalert/values.yaml
> +  use_ssl: "False"
Camel case, please.

2018-04-07 14:08 UTC, unguiculus commented
cc @pickledrick @jertel

2018-04-07 14:27 UTC, jertel commented
Looks ok to me.

2018-04-09 07:46 UTC, AlexRRR commented
@unguiculus thanks for reviewing. I never know with 3 letter acronyms how to camelcase. hopefully `useSsl` is the right choice. It seems other charts in stable have that.

2018-04-27 19:56 UTC, AlexRRR commented
Closing in favor of #5269

2018-04-27 19:56 UTC, closed without merging