fix a typo and add home link
helm/charts pull request #4669
Opened 2018-04-04 02:20 UTC by jonyhy96

Fix a typo in Readme.md line 37
Change tables->table
Add home link in Chart.yaml
```release-note
None
```

2018-04-04 02:20 UTC, jonyhy96 commented
/assign @seanknox

2018-04-04 07:46 UTC, timstoop commented
/ok-to-test
/lgtm

2018-04-04 09:47 UTC, jonyhy96 commented
/test pull-charts-e2e

2018-04-04 10:27 UTC, mycapatin commented
/test pull-charts-e2e

2018-04-04 15:09 UTC, timstoop requested changes

2018-04-04 15:09 UTC, timstoop commented on stable/prometheus-postgres-exporter/templates/deployment.yaml
> +          args: ["-extend.query-path", "/config"]
Seems like the exporter doesn't actually know this argument:
```
I0404 14:27:46.285] postgres_exporter: error: unexpected extend.query-path=/config, try --help
```

2018-04-08 01:38 UTC, jonyhy96 commented
Can't fix pull-charts-e2e — Job failed promblem 
close it

2018-04-08 01:38 UTC, closed without merging