add service annotations
helm/charts pull request #4680
Opened 2018-04-04 11:27 UTC by jungmann

**What this PR does / why we need it**:

Add annotations to service. Eg use
```
service:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
```

to create internal loadbalancer on AKS.

2018-04-04 12:04 UTC, timstoop requested changes

2018-04-04 12:04 UTC, timstoop commented on stable/sonarqube/Chart.yaml
> +version: 0.3.7
You're adding a new feature, so please bump the minor version.

2018-04-04 12:04 UTC, timstoop commented on stable/sonarqube/templates/service.yaml
> +{{- if .Values.service.annotations }}
You'll have to add the key to values.yaml as well as providing some documentation about it in README.

2018-04-04 13:06 UTC, timstoop commented
/ok-to-test
/lgtm

2018-04-04 17:13 UTC, jungmann commented
/assign @prydonius

2018-04-07 10:53 UTC, unguiculus commented
/lgtm

2018-04-25 19:30 UTC, unguiculus commented
Already implemented in #4060.

2018-04-25 19:30 UTC, closed without merging