zookeeper: parameterized image and imageTag
helm/charts pull request #4729
Opened 2018-04-05 04:18 UTC by squ1d123

**What this PR does / why we need it**:
Allows the user to specify the zookeeper images as a parameter.
This is required for people trying to run this helm chart in a air gapped environment.
Default is left as current behaviour.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
Lets users workaround issue #4540

**Special notes for your reviewer**:

2018-04-05 04:44 UTC, squ1d123 commented
Hey can you please review this? 
/assign @kow3ns

2018-04-05 09:26 UTC, timstoop requested changes

2018-04-05 09:26 UTC, timstoop commented on incubator/zookeeper/Chart.yaml
> +version: 0.6.4
This adds a new feature, please bump the minor part of the version.

2018-04-05 22:51 UTC, cristian04 commented
+1

2018-04-06 06:52 UTC, timstoop commented
/ok-to-test

2018-04-06 16:15 UTC, tedmiston commented
+1 to this idea

I think we might need to template more than this to be able to drop in eg Confluent's ZooKeeper Docker image though.

We're also doing some work on this locally in https://github.com/astronomerio/kafka-bundle/issues/3 and will send a PR back assuming it's successful.

2018-04-06 17:01 UTC, timstoop commented
/lgtm

2018-04-07 13:34 UTC, unguiculus commented
I'd suggest you follow our guidelines:
https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md#configuration

2018-04-07 13:34 UTC, unguiculus commented
/assign

2018-04-08 08:23 UTC, squ1d123 commented
Hey can this please be reviewed?
/assign @lachie83

2018-04-08 08:56 UTC, unguiculus commented
@squ1d123 I did review and made a comment. Please follow that.

2018-04-08 22:01 UTC, cristian04 commented on incubator/zookeeper/values.yaml
>  imagePullPolicy: "Always"
pullPolicy: IfNotPresent

2018-04-11 22:03 UTC, josdotso commented
related: https://github.com/kubernetes/charts/pull/4931

2018-04-13 20:32 UTC, unguiculus commented
Closing this in favor of #4931. Thanks.

2018-04-13 20:32 UTC, closed without merging