[stable/rabbitmq-ha] Add ingress for management and customizable probes
helm/charts pull request #4749
Opened 2018-04-06 04:34 UTC by coreypobrien

Merging features from `stable/rabbitmq` to get toward single rabbit chart for #4748

2018-04-06 07:08 UTC, timstoop commented
/ok-to-test
/lgtm

2018-04-07 11:33 UTC, unguiculus requested changes
I've made a couple of comments, but I'd suggest you use the ingress template you get with `helm create` using Helm 2.8+.

2018-04-07 11:33 UTC, unguiculus commented on stable/rabbitmq-ha/templates/ingress.yaml
> +  - host: {{ .Values.ingress.hostName }}
Make list indentation consistent. The rest of the chart seems to indent two spaces.

2018-04-07 11:33 UTC, unguiculus commented on stable/rabbitmq-ha/templates/ingress.yaml
> +        - path: {{ default "/" .path }}
Don't use the default function. Defaults should go in to `values.yaml`. Also, it should be `.Values.path`.

2018-04-07 16:54 UTC, coreypobrien commented
@unguiculus I updated the indentation and fixed that path default etc. I'm open to making this whole chart move closer to other standards in general, but I'm trying to keep this minimally different from the `rabbitmq` chart so we can work toward merging them in #4748.

2018-04-08 15:23 UTC, unguiculus approved these changes

2018-04-08 15:23 UTC, unguiculus commented
/lgtm

2018-04-08 15:24 UTC, merged