[drone] Add RBAC support
helm/charts pull request #4769
Opened 2018-04-06 20:04 UTC by puradox

**What this PR does / why we need it**:
RBAC support is vital for using Drone for continuous delivery on a Kubernetes stack that is running in RBAC mode. [drone-kubernetes][2] is one such plugin that will not work on RBAC-enabled Kubernetes stack with the current version of this chart.

**Which issue this PR fixes**: fixes #4143 

**Special notes for your reviewer**:
These changes add RBAC support to Drone by creating a Service Account, Role, and Role Binding. Many of these templates were taken from the more popular [nginx-ingress][3] chart, which implements RBAC support well.

[2]: https://github.com/honestbee/drone-kubernetes
[3]: https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress

2018-04-06 20:22 UTC, timstoop requested changes

2018-04-06 20:22 UTC, timstoop commented on incubator/drone/values.yaml
> +rbac:
Can you add these to the README as well, please?

2018-04-06 20:23 UTC, timstoop commented
/ok-to-test

2018-04-06 20:37 UTC, puradox commented on incubator/drone/values.yaml
> +rbac:
Nice catch. I'll add those entries in right now

2018-04-07 05:29 UTC, timstoop commented
/lgtm

2018-04-07 06:38 UTC, puradox commented
/assign @mattfarina

2018-04-07 13:53 UTC, unguiculus commented
Please follow our RBAC best practices:
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

/hold
/assign

2018-04-08 17:44 UTC, unguiculus requested changes

2018-04-08 17:44 UTC, unguiculus commented on incubator/drone/templates/role-binding.yaml
> +    app: {{ template "drone.fullname" . }}
`app: {{ template "drone.name" . }}`

2018-04-08 17:44 UTC, unguiculus commented on incubator/drone/templates/role.yaml
> +    app: {{ template "drone.fullname" . }}
`app: {{ template "drone.name" . }}`

2018-04-08 17:44 UTC, unguiculus commented on incubator/drone/templates/service-account.yaml
> +    app: {{ template "drone.fullname" . }}
`app: {{ template "drone.name" . }}`

2018-04-10 22:47 UTC, puradox commented on incubator/drone/templates/service-account.yaml
> +    app: {{ template "drone.fullname" . }}
I have changed the app label to match 👍

2018-04-13 19:42 UTC, unguiculus commented
/lgtm

2018-04-13 19:49 UTC, timstoop commented
@unguiculus can this continue or is it waiting on another fix before this one gets applied?

2018-04-13 20:49 UTC, unguiculus approved these changes

2018-04-13 20:50 UTC, unguiculus commented
/hold cancel

2018-04-13 20:54 UTC, merged