[stable/kubernetes-dashboard] set ingress Secure-Backends as default value
helm/charts pull request #4803
Opened 2018-04-09 04:42 UTC by MnrGreg

Sets Secure-Backends = "true" by default to fix #4204 without requiring values changes.

Note it is currently not possible to set this configuration via the CLI. Helm converts "true" to boolean. With future helm 2.9.0 release one will be able to force this configuration as string using the "--set-string" option. For example:
`helm install stable/kubernetes-dashboard --set-string ingress.annotations."nginx\.ingress\.kubernetes\.io/secure-backends"="true"`

This PR sets the 'secure-backends' as a default value within the charts values.yaml file. At the moment the README states that "kubernetes.io/ingress.class: nginx" is already a default setting. Therefor adding the secure-backends should not be too prescriptive either. Ingress environments still require that ingress.enabled=false be overridden to true in values.yaml.

Maintainers
@kfox1111

2018-04-09 16:02 UTC, kfox1111 commented
I haven't heard that there was a way yet to load the backends ca into the ingress-controller smoothly yet. So setting the secure backend flag only works if you somehow have out of band done so. I'd recommend defaulting it to false until nginx-ingress has a path forward for ingress specified ca's.

Uncommenting out the ingress class setting is also a breaking change I believe. Folks may not be using nginx, and after this change it will switch it to nginx unless they re-specify the option.

2018-04-15 12:36 UTC, rjkernick commented
/assign

2018-04-15 12:36 UTC, rjkernick commented
/ok-to-test

2018-04-15 12:49 UTC, rjkernick commented
/lgtm

2018-04-15 16:09 UTC, MnrGreg commented
/assign @viglesiasce

2018-04-18 16:14 UTC, kfox1111 commented
/lgtm

2018-04-18 19:35 UTC, unguiculus requested changes

2018-04-18 19:35 UTC, unguiculus commented on stable/kubernetes-dashboard/README.md
> +| `ingress.annotations`     | Specify ingress class                                                                                                       | `kubernetes.io/ingress.class: nginx`, `ngin
Remove the defaults as there are none.

2018-04-18 19:35 UTC, unguiculus commented
/assign

2018-04-25 16:04 UTC, MnrGreg commented on stable/kubernetes-dashboard/README.md
> +| `ingress.annotations`     | Specify ingress class                                                                                                       | `kubernetes.io/ingress.class: nginx`, `ngin
Removed default from README

2018-04-25 16:05 UTC, MnrGreg commented
/assign @unguiculus

2018-05-02 19:34 UTC, unguiculus commented
/lgtm

2018-05-02 19:34 UTC, unguiculus approved these changes

2018-05-02 19:37 UTC, merged

2018-05-02 19:43 UTC, kfox1111 commented
No one ever responded to my question. :( without loading a cert somehow into the ingress container, it will always fail. Please revert asap.

2018-05-02 19:44 UTC, kfox1111 commented
oh. nm. just saw it was commented out.