[prometheus] kube-state-metrics v1.3.0
helm/charts pull request #4829
Opened 2018-04-09 17:50 UTC by jhyelton

**What this PR does / why we need it**: Updating the prometheus chart to use a new version of kube-state-metrics.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**: https://github.com/kubernetes/kube-state-metrics#container-image mentions that quay.io is the preferred registry for kube-state-metrics, so I'm changing the chart to pull from that repo rather than k8s.gcr.io.  k8s.gcr.io does not have an image for v1.3.0.

2018-04-10 17:59 UTC, jhyelton commented
/assign @mgoodness

2018-04-17 08:44 UTC, gianrubio requested changes
Should update readme.md

2018-04-17 08:44 UTC, gianrubio commented on stable/prometheus/values.yaml
> +    repository: quay.io/coreos/kube-state-metrics
please update the Readme.md

2018-04-17 20:57 UTC, jhyelton commented
@mgoodness Is there anything else you need to review/test this PR?  Or is there someone else I could tag for review?

2018-04-24 16:35 UTC, monotek commented
will this fix the broken kubernetes-service-endpoints / monitoring-prometheus-kube-state-metrics which fails with "context deadline exceeded" from chart version 6.2.0?

2018-04-25 11:39 UTC, monotek commented
By the way...

v.1.3.1 is available on gcr.io too:

See: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/kube-state-metrics?gcrImageListsize=50

2018-05-10 15:48 UTC, gianrubio commented
/ok-to-test

2018-05-10 15:55 UTC, gianrubio commented
@jhyelton I'd like to merge your PR, could you reopen it?

2018-05-14 14:20 UTC, gianrubio commented
/ok-to-test
/lgtm

2018-05-14 14:25 UTC, merged

2018-05-14 14:42 UTC, monotek commented
Why was this merged?
The images is updated on gcr.io as well.

2018-05-15 07:31 UTC, gianrubio commented
there's a [note](https://github.com/kubernetes/kube-state-metrics#container-image) on the kube-state-metrics repo explaining why

> Note: The recommended docker registry for kube-state-metrics is quay.io. kube-state-metrics on gcr.io is only maintained on best effort as it requires external help from Google employees.

2018-05-15 13:54 UTC, monotek commented
OK, thanks :-)