[stable/moodle] Chart for moodle
helm/charts pull request #485
Opened 2017-01-24 15:39 UTC by sameersbn

2017-01-31 19:20 UTC, viglesiasce commented
@k8s-bot ok to test

2017-02-01 07:03 UTC, sameersbn commented
/cc @adnan @lachie83

2017-02-24 05:54 UTC, sameersbn commented
fixed: 
 - command to fetch password from secrets volume
 - updated locked mariadb chart version
 - remove mariadb persistent volume `storageClass` default

2017-03-15 23:08 UTC, lachie83 commented on stable/moodle/.helmignore
> +.git
This isn't the standard .helmignore. Did you generate using `helm create`

2017-03-15 23:11 UTC, lachie83 commented
@sameersbn Thanks for the contrib. This LGTM

2017-03-17 05:47 UTC, seanknox requested changes

2017-03-17 05:47 UTC, seanknox commented on stable/moodle/.helmignore
> +.git
Here's the standard `.helmignore` you can use:

```
# Patterns to ignore when building packages.
# This supports shell glob matching, relative path matching, and
# negation (prefixed with !). Only one pattern per line.
.DS_Store
# Common VCS dirs
.git/
.gitignore
.bzr/
.bzrignore
.hg/
.hgignore
.svn/
# Common backup files
*.swp
*.bak
*.tmp
*~
# Various IDEs
.project
.idea/
*.tmproj
```

2017-03-22 22:49 UTC, seanknox approved these changes

2017-03-22 22:55 UTC, merged