Improving MariaDB chart NOTES.txt
helm/charts pull request #4869
Opened 2018-04-10 16:14 UTC by juan131

**What this PR does / why we need it**:

Improves the Notes displayed to the user when installing the MariaDB Chart:

- Provides information about how to connect to MariaDB from outside the cluster.
- Adds a Security Warning when using LoadBalancer as Service Type.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-10 16:21 UTC, sameersbn requested changes

2018-04-10 16:21 UTC, sameersbn commented on stable/mariadb/templates/NOTES.txt
> +    most  likely exposed the MariaDB service externally withoy any authentication
typo `withouy`

2018-04-10 16:21 UTC, sameersbn commented on stable/mariadb/templates/NOTES.txt
> +    "NodePort". As alternative, you can also switch to "userPassword=true"
typo `userPassword`

2018-04-10 16:21 UTC, sameersbn commented on stable/mariadb/templates/NOTES.txt
> +    kubectl port-forward $POD_NAME 3306:3306 &
add `--namespace {{ .Release.Namespace }}` to the port-forward command

2018-04-10 16:34 UTC, tompizmor commented on stable/mariadb/templates/NOTES.txt
> +    By specifying "service.type=LoadBalancer" and "userPassword=false" you have
`usePassword` here too

2018-04-10 18:13 UTC, juan131 commented on stable/mariadb/templates/NOTES.txt
> +    By specifying "service.type=LoadBalancer" and "userPassword=false" you have
👍

2018-04-10 18:14 UTC, juan131 commented on stable/mariadb/templates/NOTES.txt
> +    most  likely exposed the MariaDB service externally withoy any authentication
👍

2018-04-10 18:14 UTC, juan131 commented on stable/mariadb/templates/NOTES.txt
> +    kubectl port-forward $POD_NAME 3306:3306 &
👍

2018-04-11 03:14 UTC, sameersbn approved these changes

2018-04-11 03:14 UTC, sameersbn commented
/ok-to-test

2018-04-11 04:02 UTC, sameersbn commented
/lgtm

2018-04-11 04:02 UTC, merged