Fix for concourse version on statefulset for workers picking up TSA host
helm/charts pull request #4905
Opened 2018-04-11 10:48 UTC by brunoban

**What this PR does / why we need it**:
Concourse workers are currently not being able to communicate to TSA due to a problem with the environment variable CONCOURSE_TSA_HOST. It's being checked against version 3.10 instead of 3.10.x.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes #4902 #4812 

**Special notes for your reviewer**:
@frodenas
@william-tran 
Not sure if this is the best way to solve this, but it seemed to work with my cluster.

2018-04-23 17:06 UTC, william-tran commented
/ok-to-test

2018-04-23 17:08 UTC, william-tran requested changes
@brunoban Thanks for the fix, please update the chart version to bump the patch version to 1.3.1 and I can merge this in.

2018-04-23 17:08 UTC, william-tran commented on stable/concourse/Chart.yaml
> +version: 1.2.4
bump the patch version to 1.3.1

2018-04-25 05:40 UTC, brunoban commented
Done! Thanks @william-tran

2018-04-25 15:23 UTC, william-tran commented
/lgtm

2018-04-25 15:33 UTC, merged