[stable/datadog] Add nodeSelector and affinity values for daemonset
helm/charts pull request #4928
Opened 2018-04-11 18:08 UTC by snebel29

Adding `nodeSelector` and `affinity` values for the agent daemonset to have more control on where to install it.

Testing chart changes locally I've noticed that there is a new `kube-state-metrics` minor version `0.5.3` available, if this changes are merged might make sense to bump also the dependency version for the packaging and push of the new chart.

@hkaj @irabinovitch @xvello

2018-04-11 18:12 UTC, snebel29 commented
/assign @irabinovitch

2018-04-13 10:44 UTC, xvello commented
Hi @snebel29 ,

What is your use case for affinity and node selector? Our supported deployment method is to run a daemonset on all nodes of a cluster, otherwise cluster-level metrics (kube_state, k8s events) will not match an existing host.

2018-04-13 13:21 UTC, snebel29 commented
Hi @xvello ,
I'm running big heterogeneous clusters with several node pools, where I want the agent running in some nodes but not in others, for example I have some node pools with a substantial amount of very small burstable nodes and I don't want the agent installed on them because for those nodes 

- Metrics and/or alerting is not important for me to have.
- This would considerably increase my datadog bill.
- The datadog agent might request enough resources to not allow my intended pods to deploy in.

Having nodeSelectors and/or affinity labels would allow me to handle that scenario easily, and in general decide where do I want datadog monitoring and alerting without having to change my k8s cluster architecture from big heterogeneous to smaller homogeneous ones.

I guess a similar effect (avoid DD agent to be scheduled into some nodes) could already be achieved using a taints/tolerations combination, so if I end up being right with this, adding nodeSelector and affinity would be more of a convenience.

I hope that makes sense somehow,

Thanks

2018-05-11 07:40 UTC, unguiculus commented
I think it's a reasonable change. Can we go ahead with it?

2018-05-11 07:40 UTC, unguiculus commented
/assign

2018-06-07 11:22 UTC, hkaj approved these changes

2018-06-07 11:22 UTC, hkaj requested changes
hi @snebel29 thanks for the PR, the changes look good, could you bump the version to 0.15 so we can merge? There's also a small conflict on `values.yaml`

2018-06-07 13:11 UTC, snebel29 commented
Hi @hkaj 
What about that? for consistency with the other optional values in the file, I've decided to keep the new values commented, besides a previous and recently merged PR provided daemonSet.nodeSelector as an empty map, I don't think any of both approaches should impact functionality...

I hope that makes sense, let me know

Regards

2018-06-07 13:53 UTC, hkaj requested changes
That makes sense yeah. I left 2 additional comments, once fixed we should be good to go.

2018-06-07 13:53 UTC, hkaj commented on stable/datadog/templates/daemonset.yaml
> +{{ toYaml .Values.daemonset.nodeSelector | indent 8 }}
actually the nodeSelector part already exists https://github.com/snebel29/charts/blob/65e989c14377634d3b5c3dc6c0bbd05e39017b0b/stable/datadog/templates/daemonset.yaml#L181-L184

2018-06-07 13:53 UTC, hkaj commented on stable/datadog/values.yaml
> +  # nodeSelector: {}
Can we keep the reference comment from before? It's helpful for users not familiar with node selectors.

2018-06-07 14:19 UTC, hkaj approved these changes
/ok-to-test
/lgtm

2018-06-07 14:36 UTC, hkaj commented
/ok-to-test

2018-06-07 14:37 UTC, merged