[stable/concourse]fix typo in README.md
helm/charts pull request #4941
Opened 2018-04-12 03:07 UTC by scf0920

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-18 12:23 UTC, rjkernick commented
Please fix merge conflict on chart.yaml

2018-04-23 17:09 UTC, william-tran commented
Thanks for the fix @scf0920, please update the chart version so it can be merged.

2018-04-23 17:10 UTC, william-tran requested changes

2018-04-23 17:10 UTC, william-tran commented on stable/concourse/Chart.yaml
> +version: 1.2.4
bump patch version 1.3.x

2018-04-24 02:24 UTC, scf0920 commented
@william-tran @rjkernick  Thanks. The version has already updated. Please continue merge 😄

2018-04-26 21:43 UTC, william-tran commented
/ok-to-test

2018-04-26 21:43 UTC, william-tran commented
sorry @scf0920 this might need another bump, but your next in line!

2018-04-27 01:51 UTC, scf0920 commented
@william-tran The version update so fast...Now version has already updated. Please merge. 😀 Thanks

2018-04-27 02:35 UTC, william-tran commented
/lgtm

2018-04-27 02:36 UTC, merged