[stable/gocd] Add a post start lifecycle hook for GoCD server to preconfigure the server
helm/charts pull request #4945
Opened 2018-04-12 05:15 UTC by varshavaradarajan

**What this PR does / why we need it**:

* This makes it easier for getting started with GoCD for new users. 
* Added a changelog to keep track of releases and changes for each.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-12 05:20 UTC, varshavaradarajan commented
/assign @unguiculus

2018-04-13 20:39 UTC, unguiculus requested changes

2018-04-13 20:39 UTC, unguiculus commented on stable/gocd/templates/configmap.yaml
> +    app: {{ template "gocd.fullname" . }}
`app: {{ template "gocd.name" . }}`

2018-04-13 20:39 UTC, unguiculus commented on stable/gocd/CHANGELOG.md
> +### 1.0.4
How about 1.0.5 in the changelog?

2018-04-17 05:17 UTC, varshavaradarajan commented
@unguiculus - done. Thank you. 

Apart from being in the OWNERS file, how do we ensure that we can maintain and merge PRs for the GoCD helm charts ourselves?

2018-04-18 20:21 UTC, unguiculus approved these changes

2018-04-18 20:21 UTC, unguiculus commented
/lgtm

2018-04-18 20:21 UTC, unguiculus commented
/ok-to-test

2018-04-18 20:22 UTC, unguiculus commented
@varshavaradarajan You must become a member of the Kubernetes Github org.

See https://github.com/kubernetes/charts#owning-and-maintaining-a-chart

I can sponsor that.

2018-04-18 21:48 UTC, merged

2018-04-19 03:32 UTC, varshavaradarajan commented
@unguiculus - thank you. Every release, we want to bump up the app version to be the latest GoCD version. We are thinking of setting up CI for that. So, I was thinking if it was possible for the ci bot user to have commit access to the chart as well. Is that possible?