[stable/heapster] Add annotations to service
helm/charts pull request #4949
Opened 2018-04-12 07:29 UTC by wwojcik

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-12 07:31 UTC, wwojcik commented
/assign @lachie83

2018-04-19 19:24 UTC, rjkernick requested changes

2018-04-19 19:24 UTC, rjkernick commented on stable/heapster/values.yaml
> +  annotations: {}
Please add empty default to the readme

2018-04-19 19:24 UTC, rjkernick commented
/assign
/ok-to-test

2018-04-19 20:02 UTC, wwojcik commented on stable/heapster/values.yaml
> +  annotations: {}
Thanks, added to README

2018-04-19 20:07 UTC, rjkernick commented
/lgtm

2018-04-19 20:28 UTC, unguiculus commented
/lgtm

2018-04-19 20:31 UTC, merged