[stable/postgresql] Add option to inject password via file
helm/charts pull request #5013
Opened 2018-04-13 13:56 UTC by coreypobrien

This adds an option to inject the password by volume mount instead of by environment variable for users that have policies against keeping secrets in environment variables.

2018-04-13 14:46 UTC, timstoop requested changes

2018-04-13 14:46 UTC, timstoop commented on stable/postgresql/Chart.yaml
> +version: 0.9.6
This adds a new feature, so please bump the minor version.

2018-04-13 14:46 UTC, timstoop commented on stable/postgresql/templates/deployment.yaml
> +      {{- if and .Values.usePasswordFile }}
I might be misreading this, but I don't think that "and" should be here?

2018-04-13 19:38 UTC, timstoop commented
/ok-to-test

2018-04-13 19:42 UTC, timstoop commented
/assign @databus23 
As maintainer, what do you think?

2018-04-13 22:18 UTC, databus23 commented
LGTM

2018-04-16 06:34 UTC, timstoop commented
/lgtm

2018-04-18 19:21 UTC, unguiculus commented
/lgtm

2018-04-18 19:45 UTC, merged