Updating GroupID, and moving to using kafka coordinator master election
helm/charts pull request #5019
Opened 2018-04-13 15:32 UTC by bradenwright

**What this PR does / why we need it**:
Updates GroupID to default to release name but can be overridden.  This allows each Release to be its own group of schema registry workers by default.  Also using Kafka Coordinator Master Election instead of ZooKeeper.

Details: https://docs.confluent.io/current/schema-registry/docs/design.html#kafka-coordinator-master-election

2018-04-13 19:51 UTC, timstoop requested changes

2018-04-13 19:51 UTC, timstoop commented on incubator/schema-registry/Chart.yaml
> +version: 0.1.2
Please update the minor, as you're adding new features.

2018-04-13 22:45 UTC, benjigoldberg commented
/ok-to-test

2018-04-14 00:52 UTC, benjigoldberg commented
/lgtm

2018-04-17 00:26 UTC, benjigoldberg commented
/lgtm

2018-04-17 00:26 UTC, benjigoldberg commented
/approve cancel

2018-04-17 00:26 UTC, benjigoldberg commented
@bradenwright can you bump the version? We're good to go once you've done that

2018-04-17 14:53 UTC, benjigoldberg commented
/lgtm

2018-04-17 14:54 UTC, merged

2018-04-23 20:56 UTC, alexander-alvarez commented
Since this change, https://github.com/kubernetes/charts/tree/master/incubator/schema-registry#parameters (`zookeeperUrl`, and `zookeeperPort`) have been out of sync.

Similarly https://github.com/kubernetes/charts/blob/master/incubator/schema-registry/templates/_helpers.tpl#L18..L29 is not longer used, so should be removed

2018-04-23 22:12 UTC, benjigoldberg commented
@bradenwright can you have a look at this ^^

2018-04-26 17:37 UTC, bradenwright commented
@alexander-alvarez what do you mean by out of sync.  I believe the parameters you are referring to have been removed.  If you feel that both methods of electing a master should be supported, to prevent errors in upgrading or something of that nature, I'm open.  If you can provide a little more detail we can figure something out.

Nice catch on unused code, I'll address that when we resolve other issue you are having.

2018-04-27 06:05 UTC, alexander-alvarez commented
@bradenwright The parameters have been removed, but they're still in the documentation. So the code is out of sync with the documentation. Nothing sophisticated and challenging :smiley:

2018-05-02 14:01 UTC, bradenwright commented
@alexander-alvarez fyi, https://github.com/kubernetes/charts/pull/5352 nice catch, 💯don't want to leave unused code and documentation around.