add init container for configs, fixes #4666
helm/charts pull request #5044
Opened 2018-04-15 16:00 UTC by emsixteeen

**What this PR does / why we need it**: 
Adds an init container to copy CouchDB configs, since configMap mounts are now read-only, and the CouchDB image has an explicit `chown -R`.

**Which issue this PR fixes**
fixes #4666 

**Special notes for your reviewer**:
/cc @kocolosk

2018-04-15 18:45 UTC, emsixteeen commented
CLA signed

2018-04-19 13:48 UTC, rjkernick requested changes

2018-04-19 13:48 UTC, rjkernick commented on incubator/couchdb/Chart.yaml
> +version: 0.1.1
Please add 'appVersion'

2018-04-19 13:48 UTC, rjkernick commented on incubator/couchdb/templates/statefulset.yaml
> +            initialDelaySeconds: 60
Please make this tunable via the values file

2018-04-19 13:48 UTC, rjkernick commented on incubator/couchdb/templates/statefulset.yaml
> +          emptyDir: {}
Should you now add a persistent volume to ensure config sticks around as the container moves through the cluster?

2018-04-19 13:48 UTC, rjkernick commented
/assign

2018-05-17 02:20 UTC, kocolosk commented
Bit late on the review here ... this looks quite similar (though not identical) to the approach by @mainephd that was merged in #5440. Does that work for you?

2018-07-02 19:19 UTC, unguiculus commented
Fixed in #5440

2018-07-02 19:19 UTC, closed without merging