Added nodeSelector to elasticsearch
helm/charts pull request #5053
Opened 2018-04-16 13:41 UTC by todoesverso

**What this PR does / why we need it**:
It adds the nodeSelector option to the client-deployment, data-statefulset and master-statefulset.
Elasticsearch is a heavy resource consuming process and I am deploying a cluster with dedicated nodes for monitoring.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
I was not sure to add node affinity, because helm creates node selectors as default template.

2018-04-17 14:16 UTC, mattfarina commented
/ok-to-test

2018-04-19 20:17 UTC, rjkernick requested changes

2018-04-19 20:17 UTC, rjkernick commented on incubator/elasticsearch/values.yaml
> +  nodeSelector: {}
Please document all default values in the readme

2018-06-11 19:27 UTC, unguiculus commented
Closing in favor of #5910.

2018-06-11 19:27 UTC, closed without merging