Added support for authenticating with SASL-SCRAM:
helm/charts pull request #5076
Opened 2018-04-17 04:50 UTC by squ1d123

- added secrets file for kafka and zookeeper auth
 - updated values.yaml with config for sasl-scram
 - add config-map for jaas file to use for java authentication
 - added KAFKA_OPTS environment variable for specifying location of jaas file
 - added init container to substitute secrets into jaas file before application startup

**What this PR does / why we need it**:
This enables the schema-registry to authenticate with kafka clusters using SASL-SCRAM.
It does so by creating kubernetes secrets and injecting them into tempfs in the form of a jaas file for the schema registry to use, therefore the secrets are only available in memory.

Default behaviour has not been changed.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-17 04:52 UTC, squ1d123 commented
Hey can this please be reviewed?
I know its a decent size change, however sasl-scram requires quite a few additions to get working.
/assign @benjigoldberg

2018-04-17 13:21 UTC, benjigoldberg requested changes
This is a really great enhancement to the chart @squ1d123 -- Handful of comments but a great start!

2018-04-17 13:21 UTC, benjigoldberg commented on incubator/schema-registry/templates/deployment.yaml
> +
rm extra newline

2018-04-17 13:21 UTC, benjigoldberg commented on incubator/schema-registry/templates/sasl-scram-config-map.yaml
> +  {{/* - range $i, $e := until (int .Values.replicas) */}}
Why is a range needed?

Also - spacing seems off here for your range

2018-04-17 13:21 UTC, benjigoldberg commented on incubator/schema-registry/values.yaml
> +## Additional Java arguments to pass to Kafka.
Do you mean to define these as `schemaRegistryOpts` instead? If you want to configure the kafka subchart, these settings should go under `kafka`

2018-04-17 13:21 UTC, benjigoldberg commented on incubator/schema-registry/values.yaml
> +    clientUser: "kafka-client"
I think there should be an option with the secrets config where the user can specify the name of an already existing secret in Kubernetes for consumption. We should definitely allow the user to optionally generate the secret with the chart if desired, but in some environments/installations it will be preferable to have the ability to specify a secret separately.

2018-04-17 20:24 UTC, squ1d123 commented on incubator/schema-registry/values.yaml
> +## Additional Java arguments to pass to Kafka.
Yes you are correct, I am also working on the Kafka helm chart, which is why I had this mixed up, will change to `schemaRegistryOpts`

2018-04-17 20:27 UTC, squ1d123 commented on incubator/schema-registry/values.yaml
> +    clientUser: "kafka-client"
Yep that's a fair point and I agree with you. I will add an option for the user to specify if they want to use their own secret or not, and the path to their own secret if opting to use their own.

2018-04-17 20:31 UTC, squ1d123 commented on incubator/schema-registry/templates/sasl-scram-config-map.yaml
> +  {{/* - range $i, $e := until (int .Values.replicas) */}}
Yep, not needed here, was working on the `kafka` chart, and potentially creating a jaas file per broker with unique Client user/pass for authentication with zookeeper. Will remove the range.

2018-04-19 07:03 UTC, squ1d123 commented
@benjigoldberg thanks for the feedback, I have made the fixes recommended, could you please review again. Thanks

2018-04-23 09:48 UTC, timstoop commented
/ok-to-test
Looks good to me, but @benjigoldberg will know best :)

2018-04-23 11:59 UTC, benjigoldberg commented
/lgtm

2018-04-23 12:01 UTC, merged