Add pod annotations and checksum for configmap to deployment
helm/charts pull request #5080
Opened 2018-04-17 11:50 UTC by rendhalver

The will allow us to annotate the pod as necessicary and will restart the Deployemnt on ConfigMap changes

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-19 14:40 UTC, rjkernick requested changes

2018-04-19 14:40 UTC, rjkernick commented on stable/docker-registry/values.yaml
> +
Please document this in the readme

2018-04-19 14:41 UTC, rjkernick commented
/assign
/ok-to-test

2018-04-19 14:45 UTC, rendhalver commented on stable/docker-registry/values.yaml
> +
Good point.
I will add that.

2018-04-19 18:30 UTC, rjkernick commented
/lgtm

2018-04-23 14:08 UTC, rendhalver commented
/assign @prydonius

2018-04-23 14:09 UTC, rendhalver commented on stable/docker-registry/values.yaml
> +
I have added this to the README.

2018-04-25 19:34 UTC, unguiculus commented
/lgtm

2018-04-26 11:42 UTC, rendhalver commented
@unguiculus There was a PR merged that updated the docker-registry so I had to rebase.
Can I get another review please?

2018-04-26 17:08 UTC, rjkernick commented
/lgtm

2018-04-26 17:14 UTC, merged