refactor fluentd-cloudwatch
helm/charts pull request #5087
Opened 2018-04-17 16:10 UTC by cheyang

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-18 23:44 UTC, cheyang commented
/assign @unguiculus

2018-04-19 19:50 UTC, unguiculus commented
/ok-to-test

2018-04-26 09:08 UTC, cheyang commented
/ok-to-test

2018-05-02 19:40 UTC, unguiculus requested changes

2018-05-02 19:40 UTC, unguiculus commented on incubator/fluentd-cloudwatch/README.md
> +| `image.pullPolicy`              | Image pull policy                          | `Always` if `imageTag` is `image.pullPolicy`
Default is `IfNotPresent`

2018-05-02 19:40 UTC, unguiculus commented on incubator/fluentd-cloudwatch/Chart.yaml
>  appVersion: 0.1.1
Could you also fix the appVersion which is v0.12.33-cloudwatch

2018-05-09 20:29 UTC, unguiculus approved these changes

2018-05-14 12:17 UTC, cheyang commented
/ok-to-test

2018-05-14 13:17 UTC, cheyang commented
@unguiculus , the reason of failure is that the docker image of fluentd in testing machine is not update to date.
```
I0514 12:28:35.914]   9m		7m		5	kubelet, gke-jenkins-default-pool-51cafeba-czr7	spec.containers{fluentd-9762-1-fluentd-cloudwatch}	Normal		Pulled			Container image "fluent/fluentd-kubernetes-daemonset:v0.12.33-cloudwatch" already present on machine
```

Its SHA is `sha256:0a6763c174ac9456ae3b71ae4485ff5f9ab7ecd5a1542e71248a72c54666f02c`, while the latest docker image with the same tag is `9c467e632224d5060218362d5efc585477870272ebb803fe2341d3261d65c58d`. I run the test in my local machine, the test can be passed.  So what's your idea? Cleaning the docker images in test machine or Just changing pull policy to Always?

2018-05-14 15:25 UTC, cheyang commented
``` 
---Logs from container fluentd-9768-1-fluentd-cloudwatch in pod fluentd-9768-1-fluentd-cloudwatch-tn5zs:---
I0514 15:05:14.332] sed: can't create temp file '/fluentd/etc/fluent.confXXXXXX': Read-only file system
I0514 15:05:14.337] ---End of logs for container fluentd-9768-1-fluentd-cloudwatch in pod fluentd-9768-1-fluentd-cloudwatch-tn5zs---
```

I'm not able to reproduce it in my test environment. @unguiculus Do you have any ideas?

2018-05-17 17:55 UTC, unguiculus commented
It looks like it is due to configmap mounts being readonly from Kubernetes 1.9.4. What's you cluster version?

2018-05-17 21:56 UTC, cheyang commented
My cluster version is 1.9.3.

2018-05-18 05:12 UTC, unguiculus commented
/lgtm

2018-05-18 05:39 UTC, merged