[stable/kube2iam] Support extra container environment variables
helm/charts pull request #5091
Opened 2018-04-17 17:06 UTC by ewbankkit

**What this PR does / why we need it**:
Add support for extra container environment variables.
Useful when using an HTTP proxy for communication with AWS APIs.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #5088 

**Special notes for your reviewer**:
Some testing.
No extra environment variables:
```
helm install --dry-run --debug stable/kube2iam

COMPUTED VALUES:
affinity: {}
aws:
  access_key: ""
  region: ""
  secret_key: ""
extraArgs: {}
extraEnv: {}
host:
  interface: docker0
  ip: $(HOST_IP)
  iptables: false
  port: 8181
image:
  pullPolicy: IfNotPresent
  repository: jtblin/kube2iam
  tag: 0.10.0
nodeSelector: {}
podAnnotations: {}
podLabels: {}
probe: true
rbac:
  create: false
  serviceAccountName: default
resources: {}
tolerations: []
updateStrategy: OnDelete
verbose: false

HOOKS:
MANIFEST:

---
# Source: kube2iam/templates/daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: kube2iam
    chart: kube2iam-0.8.7
    heritage: Tiller
    release: goodly-crab
  name: goodly-crab-kube2iam
spec:
  template:
    metadata:
      labels:
        app: kube2iam
        release: goodly-crab
    spec:
      containers:
        - name: kube2iam
          image: "jtblin/kube2iam:0.10.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --host-interface=docker0
            - --iptables=false
            - --app-port=8181
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8181
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          resources:
            {}
            
      hostNetwork: true
      serviceAccountName: "default"
      tolerations:
        []
        
  updateStrategy:
    type: OnDelete
```

Extra environment variables:
```
helm install --dry-run --debug stable/kube2iam

COMPUTED VALUES:
affinity: {}
aws:
  access_key: ""
  region: ""
  secret_key: ""
extraArgs: {}
extraEnv:
  NO_PROXY: localhost,127.0.0.1
  http_proxy: http://example.com:8080
host:
  interface: docker0
  ip: $(HOST_IP)
  iptables: false
  port: 8181
image:
  pullPolicy: IfNotPresent
  repository: jtblin/kube2iam
  tag: 0.10.0
nodeSelector: {}
podAnnotations: {}
podLabels: {}
probe: true
rbac:
  create: false
  serviceAccountName: default
resources: {}
tolerations: []
updateStrategy: OnDelete
verbose: false

HOOKS:
MANIFEST:

---
# Source: kube2iam/templates/daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: kube2iam
    chart: kube2iam-0.8.7
    heritage: Tiller
    release: awesome-fly
  name: awesome-fly-kube2iam
spec:
  template:
    metadata:
      labels:
        app: kube2iam
        release: awesome-fly
    spec:
      containers:
        - name: kube2iam
          image: "jtblin/kube2iam:0.10.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --host-interface=docker0
            - --iptables=false
            - --app-port=8181
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NO_PROXY
              value: localhost,127.0.0.1
            - name: http_proxy
              value: http://example.com:8080
          ports:
            - containerPort: 8181
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          resources:
            {}
            
      hostNetwork: true
      serviceAccountName: "default"
      tolerations:
        []
        
  updateStrategy:
    type: OnDelete
```

2018-04-17 17:34 UTC, ewbankkit commented
/assign @mgoodness

2018-04-17 17:35 UTC, ewbankkit commented
Validated in my environment FWIW.

2018-04-17 21:01 UTC, ewbankkit commented
Implementation is based on similar for Prometheus: https://github.com/kubernetes/charts/blob/d170629cc67d25c8528152348f027d64a4763414/stable/prometheus/templates/alertmanager-deployment.yaml#L35-L38

2018-05-03 19:34 UTC, unguiculus commented
/assign

2018-05-03 19:34 UTC, unguiculus requested changes

2018-05-03 19:34 UTC, unguiculus commented on stable/kube2iam/templates/daemonset.yaml
> +              value: {{ $value }}
You should make sure the value is quoted.

2018-05-04 12:07 UTC, ewbankkit commented
Made requested review changes to quote environment variables values.

Testing:

```
helm install --dry-run --debug stable/kube2iam

COMPUTED VALUES:
affinity: {}
aws:
  access_key: ""
  region: ""
  secret_key: ""
extraArgs: {}
extraEnv:
  NO_PROXY: localhost,127.0.0.1
  http_proxy: http://example.com:8080
host:
  interface: docker0
  ip: $(HOST_IP)
  iptables: false
  port: 8181
image:
  pullPolicy: IfNotPresent
  repository: jtblin/kube2iam
  tag: 0.10.0
nodeSelector: {}
podAnnotations: {}
podLabels: {}
probe: true
rbac:
  create: false
  serviceAccountName: default
resources: {}
tolerations: []
updateStrategy: OnDelete
verbose: false

HOOKS:
MANIFEST:

---
# Source: kube2iam/templates/daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: kube2iam
    chart: kube2iam-0.8.7
    heritage: Tiller
    release: cantankerous-horse
  name: cantankerous-horse-kube2iam
spec:
  template:
    metadata:
      labels:
        app: kube2iam
        release: cantankerous-horse
    spec:
      containers:
        - name: kube2iam
          image: "jtblin/kube2iam:0.10.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --host-interface=docker0
            - --iptables=false
            - --app-port=8181
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NO_PROXY
              value: "localhost,127.0.0.1"
            - name: http_proxy
              value: "http://example.com:8080"
          ports:
            - containerPort: 8181
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          resources:
            {}
      hostNetwork: true
      serviceAccountName: "default"
      tolerations:
        []
  updateStrategy:
    type: OnDelete
```

2018-05-09 20:19 UTC, unguiculus commented
/ok-to-test

2018-05-09 20:33 UTC, unguiculus approved these changes

2018-05-10 20:56 UTC, unguiculus commented
/lgtm

2018-05-10 21:00 UTC, merged