Ad hoc add kolide fleet
helm/charts pull request #5093
Opened 2018-04-17 18:00 UTC by andrewhowdencom

This will probably need a little work. At this time, 

> https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements

doesn't pass. In particular, I'm not quite sure how to set a persistent mysql password for the parent chart that propagates to the child chart.

**What this PR does / why we need it**:

This PR creates a kolide/fleet chart. Kolide's fleet tool is usefulf or querying a large chunk of hosts for specific requirements.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Nah this is random.

**Special notes for your reviewer**:

This is chunked in this was as I was writing a tutorial. See  https://medium.com/@andrewhowdencom/deploying-on-kubernetes-1-the-use-case-b4c201e2f049

2018-04-19 14:11 UTC, andrewhowdencom commented
/assign @prydonius

2018-05-03 19:53 UTC, unguiculus requested changes
Please read up on our guidelines. Make sure standard labels are correctly applied to all resources.

Please compare with what you get from `helm create` using Helm 2.8+ nd update accordingly.

2018-05-03 19:53 UTC, unguiculus commented on stable/kolide-fleet/LICENSE
> +The MIT License (MIT)
Remove this file. This repo is Apache license.

2018-05-03 19:53 UTC, unguiculus commented on stable/kolide-fleet/MAINTAINERS.md
> +The following document lists the maintainers of the project, as well as the username for each.
Remove this file. Maintainers are listed in Chart.yaml. Plus, you may add an OWNERS file.

2018-05-03 19:53 UTC, unguiculus commented
/assign

2018-05-04 13:04 UTC, prydonius commented
@andrewhowdencom if you think it'll need more work to meet the technical requirements, you could submit it to incubator for now?

2018-05-07 07:09 UTC, andrewhowdencom commented
Hola @prydonius; 

Done. I intend to address the feedback; I just haven't had the budget yet. ^^

2018-05-22 15:41 UTC, andrewhowdencom commented
Hola @unguiculus ;

I've implemented the requested changes. I'm still a little fuzzy about how to handle the MySQL stuff. 

The problem is that I need to set the MySQL password for two distinct values at the same time, or hoist the value from the MySQL chart to fleet. 

Do you have any preference as to which one it should be? In the case it's hoisted, I can sort of rely on MySQL to keep it consistent through releases (which I'm not sure if this chart does -- at any rate, it's that charts' problem). 

My initial plan of "mark it as an install job" doesn't work, as I can't override the MySQL secret. 

I might see if I can hoist it for now. :thinking:

2018-05-22 15:42 UTC, andrewhowdencom commented
Also PKI which is a whole other thing :sweat:

2018-06-18 19:35 UTC, unguiculus commented
Please merge in latest master.

You can specify custom values for CI:
https://github.com/kubernetes/charts/blob/master/test/README.md#providing-custom-test-values

2018-06-29 13:32 UTC, andrewhowdencom commented
So, *in theory* this is done. However, I can't see where the CI is running anymore to check it. Did the integration get removed or?

Also rebased on top of latest master (as opposed to merging) -- I hope this is okay. I like the linear history ^^ (I know it gets squashes but habits gonna habit)

2018-07-01 15:54 UTC, unguiculus commented
@andrewhowdencom It's actually better to merge instead of rebasing so Github can show your changes.

2018-07-01 16:09 UTC, unguiculus requested changes

2018-07-01 16:09 UTC, unguiculus commented on incubator/kolide-fleet/README.md
> +- Kubernetes 1.3+ with Beta APIs enabled
1.9+

2018-07-01 16:09 UTC, unguiculus commented on incubator/kolide-fleet/templates/deployment.yaml
> +apiVersion: "extensions/v1beta1"
apps/v1

2018-07-01 16:09 UTC, unguiculus commented on incubator/kolide-fleet/templates/deployment.yaml
> +        checksum.helm.kubernetes.io/secret: {{ include (print $.Chart.Name "/templates/secret.yaml") . | sha256sum }}
You should do this:

`{{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}`

2018-07-01 16:09 UTC, unguiculus commented on incubator/kolide-fleet/templates/deployment.yaml
> +  replicas: {{ default 2 .Values.deployment.replicas }}
Don't use the default function for simple default values. Defaults should be in `values.yaml`.

2018-07-01 16:09 UTC, unguiculus commented on incubator/kolide-fleet/templates/service.yaml
> +{{- if .Values.pod.annotations }}
.Values.service.annotations

2018-07-01 16:09 UTC, unguiculus commented on incubator/kolide-fleet/templates/service.yaml
> +    {{ if eq .Values.service.type "LoadBalancer" }}service.beta.kubernetes.io/external-traffic: "OnlyLocal"{{ end }}
This if statement is unnecessary. The annnotation can be added with `service.annotations`. However, the annotation is obsolete with the field `externalTrafficPolicy` on the service spec. Add that and make it configurable.

2018-07-01 16:09 UTC, unguiculus commented on incubator/kolide-fleet/values.yaml
> +resources:
Don't add defaults for resources. Comment them out.

2018-07-01 16:09 UTC, unguiculus commented on incubator/kolide-fleet/values.yaml
> +
Nesting by `mysql`, `redis`, and `fleet` makes sense. Move `pod`, `service`, and `resources` under `fleet`. The `image` and `replicas` should be directly under `fleet` then.

2018-07-01 16:09 UTC, unguiculus commented on incubator/kolide-fleet/values.yaml
> +    image: kolide/fleet
```yaml
image:
  repository:
  tag:
  pullPolicy:
```

2018-07-02 07:04 UTC, andrewhowdencom commented
Thanks for the review! I will take a look at this ... probably tomorrow afternoon. I will merge changes as required in future!

2018-07-08 06:18 UTC, andrewhowdencom commented on incubator/kolide-fleet/README.md
> +- Kubernetes 1.3+ with Beta APIs enabled
:heavy_check_mark:

2018-07-08 06:18 UTC, andrewhowdencom commented on incubator/kolide-fleet/templates/deployment.yaml
> +apiVersion: "extensions/v1beta1"
:heavy_check_mark:

2018-07-08 06:19 UTC, andrewhowdencom commented on incubator/kolide-fleet/templates/deployment.yaml
> +        checksum.helm.kubernetes.io/secret: {{ include (print $.Chart.Name "/templates/secret.yaml") . | sha256sum }}
:heavy_check_mark:

2018-07-08 06:22 UTC, andrewhowdencom commented on incubator/kolide-fleet/templates/deployment.yaml
> +  replicas: {{ default 2 .Values.deployment.replicas }}
I'm reading this as "anything that can be defined in values.yaml should be", in which case :heavy_check_mark:

2018-07-08 06:22 UTC, andrewhowdencom commented on incubator/kolide-fleet/templates/service.yaml
> +{{- if .Values.pod.annotations }}
:heavy_check_mark:

2018-07-08 08:07 UTC, andrewhowdencom reviewed
I used checkboxes to denote stuff as I've done it.

2018-07-08 08:07 UTC, andrewhowdencom commented on incubator/kolide-fleet/templates/service.yaml
> +{{- if .Values.pod.annotations }}
:heavy_check_mark:

2018-07-08 08:07 UTC, andrewhowdencom commented on incubator/kolide-fleet/templates/service.yaml
> +    {{ if eq .Values.service.type "LoadBalancer" }}service.beta.kubernetes.io/external-traffic: "OnlyLocal"{{ end }}
:heavy_check_mark:

2018-07-08 08:07 UTC, andrewhowdencom commented on incubator/kolide-fleet/values.yaml
> +
This one makes a little less sense to me. I will implement it as i've literally understood it, but I feel like `image` should be a property of `pod` and not directly. So, 

`fleet.pod.image` 

and not

`fleet.image`

whereas I understand you to be asking for the latter. I'll implement it as I understand in case I'm missing something, but I wanted to raise it.

2018-07-08 08:07 UTC, andrewhowdencom commented on incubator/kolide-fleet/values.yaml
> +    image: kolide/fleet
:heavy_check_mark:

2018-07-08 08:07 UTC, andrewhowdencom commented on incubator/kolide-fleet/values.yaml
> +resources:
:heavy_check_mark:

2018-07-15 16:13 UTC, unguiculus requested changes

2018-07-15 16:13 UTC, unguiculus commented on incubator/kolide-fleet/values.yaml
> +  pod:
I understand your concerns but it is commonly done as follows. Please change accordingly.

```yaml 
fleet:
  podAnnotations:
  resources: {}
```

2018-07-15 16:13 UTC, unguiculus commented on incubator/kolide-fleet/values.yaml
> +    tag: "latest"
Use a stable image

2018-07-15 16:13 UTC, unguiculus commented on incubator/kolide-fleet/templates/secret.yaml
> +  fleet.redis.password: {{ required "A valid Redis password is required" .Values.redis.redisPassword | b64enc }}
This duplicates credentials which are already managed in secrets by their respective charts. Why don't you reuse these secrets?

2018-07-15 16:13 UTC, unguiculus commented on incubator/kolide-fleet/values.yaml
> +    disable_banner: true
Add newline at end of file

2018-07-16 07:22 UTC, andrewhowdencom commented on incubator/kolide-fleet/templates/secret.yaml
> +  fleet.redis.password: {{ required "A valid Redis password is required" .Values.redis.redisPassword | b64enc }}
So, when I was initially writing this I found it difficult to reconcile the credentials from the child chart to the parent chart over multiple releases (See commit https://github.com/kubernetes/charts/pull/5093/commits/d0e959db514158dcb54eb93150d6b98e0e29cfc9)

Essentially, because MySQL (absent a specific password supplied) would regenerate the password with reach release *but* not overwrite the password in the configuration, each `helm upgrade --install` would regenerate the password in the `helm` configuration (and in the MySQL configuration) but wouldn't apply to the mysql configuration. I think. It's been a while lol.

So, the first install would work fine, but subsequent installs would be unable to connect to the database.

If this should be possible, I can take another look at it, but my impression is that unless the MySQL password is stored somewhere in persistence when the application is booted then the upgrade of this chart will fail.

2018-08-18 10:03 UTC, andrewhowdencom commented
I haven't forgotten stale bot -- just struggling for time at the minute.

2018-10-19 12:38 UTC, andrewhowdencom commented
Hiii stale bot I won't get to this for a couple of weeks yet. Super busy! Plus a new version of kolide was released. If anyone wants to carry this go nuts.

2018-12-02 13:57 UTC, closed without merging