[stable/prometheus] prometheus.yml contents as server config. Allow a…
helm/charts pull request #5105
Opened 2018-04-18 08:49 UTC by tuxpiper

…dditional scrape configs

**What this PR does / why we need it**:
Addresses kubernetes/charts#5092 (opened by me). Splits the prometheus.yml generation in such a way that's easy to have additional scrape_configs, without repeating the whole block of default scrape configs

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #5092 

**Special notes for your reviewer**:
Pending:
- [ ] Update README . Will do if the PR is considered useful.

2018-04-18 09:18 UTC, tuxpiper commented
/assign @mgoodness as suggested

2018-05-03 19:45 UTC, unguiculus requested changes
/assign @gianrubio

2018-05-03 19:45 UTC, unguiculus commented on stable/prometheus/Chart.yaml
> +version: 6.2.1-alpha
Drop alpha.

2018-06-11 18:57 UTC, steven-sheehy commented
Some overlap with https://github.com/kubernetes/charts/pull/3328

2018-09-21 02:02 UTC, RickyCook commented
Hey @steven-sheehy, I've updated #3328 (finally; sorry), and it looks like both PRs now serve very similar purposes. Perhaps we should combine them so that there aren't 2.

The additional parts that #3328 solves is the ability to _edit_ the current scrape configs, as well as not changing how the `serverFiles.prometheus.yml` is specified to avoid compatibility issues.

2018-10-10 19:03 UTC, steven-sheehy commented
I think this can be closed since PR #7984 has been merged.

2018-11-23 20:09 UTC, closed without merging

2019-10-22 23:55 UTC, TheNotary commented
ok...