[stable/mysql] Add prometheus metrics
helm/charts pull request #5131
Opened 2018-04-19 11:40 UTC by xasor

2018-04-19 12:19 UTC, andrewhowdencom commented
Oh dude yes thanks!

(I am not a project just excited about this PR)

2018-04-19 12:25 UTC, xasor commented
;)

2018-04-19 13:39 UTC, xasor commented
/assign @seanknox

2018-05-09 22:16 UTC, unguiculus commented
/assign

2018-05-10 20:39 UTC, unguiculus requested changes

2018-05-10 20:39 UTC, unguiculus commented on stable/mysql/templates/svc.yaml
> +  annotations:
Don't hard-code the annotations. Just make them configurable. You don't need them if you use the prometheus-operator.

2018-05-10 20:39 UTC, unguiculus commented on stable/mysql/Chart.yaml
> +version: 0.4.5
Should be a minor bump.

2018-05-10 20:39 UTC, unguiculus commented
cc @gianrubio

2018-05-29 11:03 UTC, xasor commented
Thanks for the review @unguiculus

2018-05-29 11:11 UTC, gianrubio commented
/lgtm

2018-06-06 20:35 UTC, unguiculus approved these changes

2018-06-06 20:36 UTC, unguiculus commented
/lgtm

2018-06-08 15:23 UTC, unguiculus commented
/ok-to-test

2018-06-08 15:32 UTC, unguiculus commented
/lgtm

2018-06-08 15:35 UTC, merged