Concourse: Add miscellaneous concourse atc flags.
helm/charts pull request #5153
Opened 2018-04-20 03:52 UTC by jmcarp

**What this PR does / why we need it**:

Adds a few missing configuration options to the concourse atc, mostly useful to us for compliance purposes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

@frodenas @william-tran

2018-04-23 16:46 UTC, william-tran reviewed
Thanks @jmcarp, I'd like to hold off on an update to 3.11 until this issue gets sorted out: https://github.com/concourse/concourse/issues/2165#issuecomment-382869258

2018-04-23 16:46 UTC, william-tran commented
/hold

2018-05-01 18:52 UTC, brianmartin commented
Hey @jmcarp, these changes look quite useful to us as well!

Looks like 3.12 has been released and resolves the memory leak concern. Moreover, 3.13 is out as of yesterday.

2018-05-01 19:37 UTC, william-tran commented
I'd be good to go with 3.13 in this PR, let us know if you want to take that on or have those new features added in another PR. I see:
- `The ATC can now be configured with a global default build_logs_to_retain`
- `This requires a new port to be reachable on the worker node from the web node: 7799`
- `Added a new authentication provider for teams using OpenID Connect (OIDC)`

2018-05-02 19:35 UTC, jmcarp commented
@william-tran: I just bumped the image tag to `3.13.0`, exposed `7799` on workers, and added build log retention options.

2018-05-02 22:39 UTC, brianmartin commented
@jmcarp Looks good to me! I do see a few more flags added for 3.13 related to Datadog metrics (see: https://github.com/concourse/atc/pull/269#issue-183163123). No worries if you want to keep this PR more tightly scoped though – I can add those a little later if they don't make sense in this PR.

2018-05-03 04:25 UTC, jmcarp commented
@brianmartin it looks like we're missing a bunch of options around metrics, so maybe we can add them all together in a separate patch.

2018-05-03 19:13 UTC, brianmartin commented
@jmcarp Sounds totally reasonable.

2018-05-03 20:15 UTC, william-tran commented
/ok-to-test

2018-05-03 20:16 UTC, william-tran commented
@jmcarp could you minor bump the chart to 1.5.0? We have a 1.4.0 about to be merged.

2018-05-05 02:42 UTC, jmcarp commented
Bumped to 1.5.0 @william-tran

2018-05-07 16:05 UTC, william-tran requested changes
We also need to add entries to the values table in the README

2018-05-07 16:05 UTC, william-tran commented on stable/concourse/values.yaml
> +  cookieSecure: false
Is this a sensible default?

2018-05-07 16:05 UTC, william-tran commented on stable/concourse/values.yaml
> +    level: ""
what does blank mean here?

2018-07-15 13:54 UTC, william-tran commented
With generic env vars support via #6441, I will close this PR, as you can use that instead. There are so many options that can be enabled via env vars alone. To keep the chart from getting too complicated with features, I won't take any more PRs that are a straight value to env var / command line arg thing.

2018-07-15 13:55 UTC, william-tran commented
/close

2018-07-15 13:55 UTC, closed without merging