[mssql-linux] Added feature to enable HADR
helm/charts pull request #5165
Opened 2018-04-20 14:43 UTC by thomasliddledba

Adding feature to enable SQL Server deployment with HADR (Availability Groups)

2018-05-03 00:59 UTC, thomasliddledba commented
/cc @unguiculus

2018-05-06 11:31 UTC, thomasliddledba commented
Fixed merge conflicts #5291

2018-05-09 13:42 UTC, thomasliddledba commented
/cc @unguiculus - could you merge this

2018-05-09 13:44 UTC, thomasliddledba commented
/cc @timstoop

2018-05-09 21:18 UTC, unguiculus requested changes

2018-05-09 21:18 UTC, unguiculus commented on stable/mssql-linux/README.md
> +| persistence.enabled | Presist the Data and Log files for SQL Server                                               | `false`                          |
Revert `Presist` to `Persist`

2018-05-09 21:18 UTC, unguiculus commented
/assign

2018-05-10 23:55 UTC, thomasliddledba commented on stable/mssql-linux/README.md
> +| persistence.enabled | Presist the Data and Log files for SQL Server                                               | `false`                          |
Fat finger - Fixed.

2018-05-11 05:17 UTC, unguiculus commented
/ok-to-test

2018-05-11 15:09 UTC, timstoop commented
/lgtm

2018-05-11 15:18 UTC, timstoop approved these changes

2018-05-11 16:00 UTC, unguiculus commented
/lgtm

2018-05-11 16:05 UTC, merged