[NEW] registry
helm/charts pull request #517
Opened 2017-01-26 22:54 UTC by ravishivt

Installs a docker private registry.  I based it off of https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry but improved it to match helm's best practices (deployment instead of RC, health checks, customization).

2017-01-27 16:10 UTC, unguiculus requested changes

2017-01-27 16:10 UTC, unguiculus commented on stable/registry/templates/service.yaml
> +    "helm.sh/created": {{.Release.Time.Seconds | quote }}
Don't use this annotation anymore. See PR #425.

2017-01-27 16:10 UTC, unguiculus commented on stable/registry/templates/deployment.yaml
> +    "helm.sh/created": {{.Release.Time.Seconds | quote }}
Don't use this annotation anymore. See PR #425.

2017-01-27 16:55 UTC, ravishivt commented on stable/registry/templates/service.yaml
> +    "helm.sh/created": {{.Release.Time.Seconds | quote }}
Thanks!  Fixed.

2017-02-25 15:21 UTC, mgoodness commented
@k8s-bot ok to test

2017-02-25 17:46 UTC, mgoodness requested changes
Looks really good. Mostly best practice stuff.

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/Chart.yaml
> +sources:
Is there an icon we can display for this chart on [KubeApps](https://kubeapps.com/)?

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/_helpers.tpl
> +{{- default .Chart.Name .Values.nameOverride | trunc 24 | trimSuffix "-" -}}
Truncate at 63 characters

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/_helpers.tpl
> +{{- printf "%s-%s" .Release.Name $name | trunc 24 | trimSuffix "-" -}}
Truncate at 63 characters

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/values.yaml
> +resources:
Set `resources: {}` and comment out limits & requests. This provides end-users with suggested values without making it difficult to override. Update README accordingly.

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/values.yaml
> +  # nodePort: <If service.type is set to NodePort, optionally choose a port between 30000-32767>
Provide a default `nodePort` value. Makes the conditional logic in the Service template a little simpler if we don't have to check that it's set. README would need the value added.

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/service.yaml
> +    app: {{ template "fullname" . }}
Set `app: {{ template "name" . }}`

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/service.yaml
> +    app: {{ template "fullname" . }}
Set `app: {{ template "name" . }}` and add `release: {{ .Release.Name }}`.

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/deployment.yaml
> +    app: {{ template "fullname" . }}
Set `app: {{ template "name" . }}`. It allows better use of labels when querying, and is a pattern I'm pushing to adopt.

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/deployment.yaml
> +      app: {{ template "fullname" . }}
The selector can be dropped IMHO. If it's retained, set `app: {{ template "name" . }}` and add `release: {{ .Release.Name }}`.

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/deployment.yaml
> +        app: {{ template "fullname" . }}
Set `app: {{ template "name" . }}`

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/deployment.yaml
> +      - name: {{ .Chart.Name }}
Set `name: {{ template "name" . }}` so it can be overridden by user.

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/deployment.yaml
> +			{{- if .Values.persistence.enabled }}
Nit: fix indentation

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/image-store-pvc.yaml
> +    app: {{ template "fullname" . }}
Set `app: {{ template "name" . }}`

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/values.yaml
> +  name: registry
Delete. AFAICT it's not used anywhere.

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/image-store-pvc.yaml
> +spec:
Do
```
{{- if .Values.persistence.annotations }}
  {{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
```
instead. It's cleaner IMHO. Be sure to add `annotations: {}` to the `persistence:` map in `values.yaml`.

2017-02-25 17:46 UTC, mgoodness commented on stable/registry/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} -l "app={{ template "fullname" . }}" -o jsonpath="{.items[0].metadata.name}")
Label query needs to be `-l "app={{ template "name" . }},release={{ .Release.Name}}"`

2017-03-07 18:21 UTC, prydonius commented
@ravishivt gentle nudge - any update on this?

2017-03-28 22:21 UTC, mgoodness commented
Closing for inactivity.

2017-03-28 22:21 UTC, closed without merging