[stable/prometheus] more careful conditional deployment behaviour
helm/charts pull request #5184
Opened 2018-04-22 04:44 UTC by indigoid

**What this PR does / why we need it**:

I wanted to deploy the node exporter and kube-state-metrics separately to the
rest of Prometheus and discovered that there was no conditional deployment
setting in `values.yaml` for that.

While making these changes I also noticed that deploying individual components
would still generate RBAC resources for the other components, so I fixed that too.

I think this should not introduce any chart default behaviour changes, or release
upgrade issues for users of earlier revisions of the chart, as `server.enabled`
defaults to `true`.

**Special notes for your reviewer**:

Tested on Kubernetes 1.10.

(ping @mgoodness — Thanks for maintaining this chart!)

2018-04-22 04:46 UTC, indigoid commented
/assign @mgoodness

2018-04-22 20:46 UTC, gianrubio requested changes
I requested you to change all if conditions

2018-04-22 20:46 UTC, gianrubio commented on stable/prometheus/Chart.yaml
> +version: 6.2.2
you are introducing breaking changes, so change it to 6.3.1

2018-04-22 20:46 UTC, gianrubio commented on stable/prometheus/templates/alertmanager-serviceaccount.yaml
> +{{- if .Values.alertmanager.enabled }}
please also add this conditional [here](https://github.com/indigoid/charts/blob/831c9fcb5c500590dc0396a44b96ba2b222b97ee/stable/prometheus/templates/alertmanager-networkpolicy.yaml)

2018-04-22 20:46 UTC, gianrubio commented on stable/prometheus/templates/alertmanager-serviceaccount.yaml
>  {{- if .Values.serviceAccounts.alertmanager.create }}
group all this news conditions like this:

 ```{{ if and  .Values.alertmanager.enabled .Values.serviceAccounts.alertmanager.create }}```

2018-04-22 20:46 UTC, gianrubio commented on stable/prometheus/templates/kube-state-metrics-clusterrole.yaml
> +{{- if .Values.kubeStateMetrics.enabled }}
should be 
``` 
{{ if and . Values.kubeStateMetrics.enabled .Values.rbac.create }}
```

2018-04-23 00:05 UTC, indigoid commented
thanks @gianrubio, have updated per your comments

2018-04-23 07:21 UTC, gianrubio approved these changes

2018-04-23 07:21 UTC, gianrubio commented
/lgtm

2018-04-25 19:37 UTC, unguiculus commented
I don't like the `server.enabled` flag. The whole chart is about Prometheus. I kind of defeats its purpose if we can disable it.

/hold

2018-04-26 00:02 UTC, indigoid commented
@unguiculus OK. Would you be more interested in a PR adding a `prometheus-alertmanager` chart?

I see there are already charts for `pushgateway`, `node-exporter` and `kube-state-metrics`

2018-04-26 20:01 UTC, unguiculus commented
Yes, I think the Prometheus chart is bloated. Alertmanager and exporters should be separate charts that could be pulled in as dependencies.

2018-05-01 17:11 UTC, mattfarina commented
/ok-to-test

2018-10-02 17:35 UTC, closed without merging