Artifactory ha nginx bugfix
helm/charts pull request #5233
Opened 2018-04-24 18:00 UTC by jainishshah17

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-24 18:02 UTC, eldada approved these changes

2018-04-27 13:41 UTC, rjkernick requested changes

2018-04-27 13:41 UTC, rjkernick commented on stable/artifactory-ha/templates/nginx-deployment.yaml
> +          periodSeconds: 10
Please make these configurable through the values.yaml.

2018-05-01 13:15 UTC, rjkernick approved these changes

2018-05-01 13:15 UTC, rjkernick commented
/ok-to-test

2018-05-01 13:21 UTC, rjkernick requested changes

2018-05-01 13:21 UTC, rjkernick commented on stable/artifactory-ha/README.md
> +| `artifactory.livenessProbe.successThreshold`     | Minimum consecutive successes for the probe to be considered successful after having failed. | 3 |
The livenessProbe.successThreshold must be 1

2018-05-01 16:28 UTC, jainishshah17 commented on stable/artifactory-ha/README.md
> +| `artifactory.livenessProbe.successThreshold`     | Minimum consecutive successes for the probe to be considered successful after having failed. | 3 |
done

2018-05-01 21:40 UTC, jainishshah17 commented
/retest

2018-05-01 23:06 UTC, jainishshah17 commented
@rjkernick  
Test is failing because of : ```I0501 21:51:27.549]   9m		3m		22	default-scheduler			Warning		FailedScheduling	0/5 nodes are available: 5 MaxVolumeCount.```

2018-05-02 17:55 UTC, jainishshah17 commented
/retest

2018-05-03 17:36 UTC, unguiculus commented
/retest

2018-05-04 20:39 UTC, unguiculus commented
/lgtm

2018-05-04 20:39 UTC, merged