added helm chart for vsts
helm/charts pull request #5245
Opened 2018-04-25 13:35 UTC by bramvdklinkenberg

**What this PR does / why we need it**: Simple deployment of a vsts build agent on your kubernetes cluster instead of setting up and managing a vm.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # N/A

**Special notes for your reviewer**:
/assign @mattfarina

Maintainer @bramvdklinkenberg

2018-04-25 13:38 UTC, bramvdklinkenberg commented
/assign @mattfarina

2018-04-26 07:42 UTC, bramvdklinkenberg commented
@mattfarina do I need to do something or is it your turn? :smiley:

2018-05-08 16:32 UTC, unguiculus commented
/assign

2018-05-08 16:33 UTC, unguiculus commented
Please compare with what you get with `helm create` using Helm 2.8+ and update accordingly.

2018-05-09 08:00 UTC, bramvdklinkenberg commented
@unguiculus what issue are you facing?
I deployed it with helm version 2.9.0 on an Azure Kubernetes cluster with k8s version 1.9.6.
I also tested it with minikube version 0.26.1 and works.

2018-05-09 21:17 UTC, unguiculus commented
I did mention I had issues. I just want you to apply our current best practices.

2018-05-09 21:49 UTC, bramvdklinkenberg commented
@unguiculus , I know. I read it wrong but when I read it again I swa what you ment!

2018-05-14 08:40 UTC, bramvdklinkenberg commented
@unguiculus , I changed the chart (structure).

2018-05-17 17:58 UTC, unguiculus requested changes

2018-05-17 17:58 UTC, unguiculus commented on stable/vstsagent/Chart.yaml
> +kubeVersion: ">1.7.7"
\>1.8

2018-05-17 17:58 UTC, unguiculus commented on stable/vstsagent/templates/deployment.yaml
> +apiVersion: v1
One file per resource please.

2018-05-17 17:58 UTC, unguiculus commented on stable/vstsagent/values.yaml
> +  tag: latest
Use a stable version.

2018-05-17 19:52 UTC, bramvdklinkenberg commented
@unguiculus I made changes but haven't changed the tagging.
The latest tag always points at a standard image based on the best supported OS that targets VSTS and includes capabilities enabling many of the built-in VSTS build and release tasks.

2018-05-17 20:09 UTC, unguiculus commented
Chart releases should have stable image versions. We require that in our guidelines. Using latest is a bad practice and not suitable for production use cases.

2018-05-18 07:11 UTC, bramvdklinkenberg commented
@unguiculus , I changed the tag.

2018-05-18 15:44 UTC, unguiculus commented on stable/vstsagent/values.yaml
> +  tag: ubuntu-16.04
This doesn't seem to be a stable tag either.

2018-05-18 19:13 UTC, bramvdklinkenberg commented
It is confusing what "image tag" is the stable. Microsoft says this about the images:

> Derived images that are based on the standalone agent images provide a variety of capabilities that enable it to support specific VSTS build and release tasks.
The latest tag always points at a standard image based on the best supported OS that targets VSTS and includes capabilities enabling many of the built-in VSTS build and release tasks.

They have a whole bunch of images and tags that can be used, see https://hub.docker.com/r/microsoft/vsts-agent/. But nowhere am I able to see/find a specific image that Mcirsoft points out as stable. You just have a wide variety of images to pick from.

2018-05-24 18:53 UTC, unguiculus commented
/ok-to-test

2018-05-24 18:55 UTC, unguiculus approved these changes

2018-05-24 19:54 UTC, bramvdklinkenberg commented
@unguiculus , the test failed because of this error;
"error: missing VSTS_ACCOUNT environment variable"

I guess the test doesn't fill in the parameters that are needed. By default these parameters are empty but the need to be provided. But with dummy parameters the deployment will fail.

2018-05-25 11:27 UTC, unguiculus commented
You can provide test values for CI: https://github.com/kubernetes/charts/blob/master/test/README.md#providing-custom-test-values

2018-05-25 11:32 UTC, bramvdklinkenberg commented
@unguiculus , the test values (I can use my own vsts account plus access token) to test with will not be visible for others?

2018-06-06 20:29 UTC, unguiculus commented
Anything you commit is visible, of course.

2018-06-08 11:53 UTC, bramvdklinkenberg commented
Any idea of when the last step will take place?

2018-06-08 15:24 UTC, unguiculus commented
/hold

2018-06-11 07:04 UTC, bramvdklinkenberg commented
hi @unguiculus , I am/ was wondering why the request has been put on hold.

2018-06-11 19:41 UTC, unguiculus commented
@bramvdklinkenberg I put it on hold due to your comment about access tokens.

2018-06-12 09:20 UTC, bramvdklinkenberg commented
@unguiculus the only way to test it is with a real vsts account, acces token en agentpool. they have to be provided or else it won;t work.
for testing purposes i just created a temporary access token to pass the tests aand after it passed I deleted the token in for my vsts account.
default values will not work.

2018-06-17 12:39 UTC, unguiculus commented
This will not work. Anyone may create PR to the chart and testing won't work then. Also, the chart will be retested when the bot tries to merge it.

2018-06-17 19:23 UTC, bramvdklinkenberg commented
then I guess there is nothing left to do and close this PR.

2018-06-17 19:24 UTC, bramvdklinkenberg commented
/close

2018-06-17 19:24 UTC, closed without merging