Version 0.1.0 of the Schema-Registry-UI
helm/charts pull request #5258
Opened 2018-04-25 23:20 UTC by cristian04

**What this PR does / why we need it**:
This PR adds a new Chart into the incubator. 
Schema-Registry UI is a web tool for the confluentinc/schema-registry in order to create / view / search / evolve / view history & configure Avro schemas of your Kafka cluster.

More info here: https://github.com/Landoop/schema-registry-ui

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-26 03:52 UTC, cristian04 commented
Hey /assign @prydonius, could you please review this? Thanks :)

2018-04-26 03:53 UTC, cristian04 commented
/assign @prydonius

2018-04-27 20:05 UTC, timstoop commented
/ok-to-test

2018-04-27 20:05 UTC, timstoop commented
/assign

2018-05-07 02:10 UTC, cristian04 commented
/test

2018-05-07 02:10 UTC, cristian04 commented
/retest

2018-05-07 08:16 UTC, timstoop commented
Could you please add an OWNERS file as well? That's the only thing that I think is missing. The rest is nice and simple and looks ok.

2018-05-07 14:25 UTC, unguiculus commented
/assign

2018-05-07 22:17 UTC, timstoop commented
Heh you added yourself to the repo owners, that's not what I meant. Please revert that.

I requested that you add an OWNERS file to this Chart. Check https://github.com/kubernetes/charts/blob/master/stable/cert-manager/OWNERS for an example.

2018-05-08 02:03 UTC, cristian04 commented
Done. Sorry for the mistake regarding the OWNERS file.

/joke

2018-05-09 20:17 UTC, unguiculus requested changes
I'd suggest you move the chart to stable directly.

2018-05-09 20:17 UTC, unguiculus commented on incubator/schema-registry-ui/README.md
> +* Kubernetes 1.6
1.8+

2018-05-09 20:17 UTC, unguiculus commented on incubator/schema-registry-ui/OWNERS
> +approvers:
Don't put all the chart maintainers in there. You should also add yourself as approver. However, for the mechanism to work, you'd have to become a member of the Kubernetes org on Github.

See https://github.com/kubernetes/charts#owning-and-maintaining-a-chart

2018-05-09 20:17 UTC, unguiculus commented on incubator/schema-registry-ui/README.md
> +### Installed Components
I'd remove this section. `helm status <release>` is probably the better choice anyways.

2018-05-09 20:18 UTC, unguiculus commented
/assign

2018-05-10 07:37 UTC, unguiculus commented on stable/schema-registry-ui/OWNERS
> +approvers:
Again, only maintainers of this chart should be in the file, which is you only.

2018-05-11 05:18 UTC, unguiculus commented on stable/schema-registry-ui/Chart.yaml
> +  name: Cristian Russo
Use Github username

2018-05-11 06:28 UTC, unguiculus commented
/lgtm

2018-05-11 06:29 UTC, merged