added persistent volumes for openvpn certs
helm/charts pull request #526
Opened 2017-01-30 21:31 UTC by jfelten

This avoids having to regenerate client certs after each pod restart.  Persistence is optional.

2017-01-30 21:41 UTC, spiffxp commented
@k8s-bot ok to test

2017-01-30 21:59 UTC, viglesiasce requested changes

2017-01-30 21:59 UTC, viglesiasce commented on stable/openvpn/templates/config-openvpn.yaml
> +<<<<<<< HEAD
Merge conflict was checked in.

2017-01-30 22:04 UTC, jfelten commented on stable/openvpn/templates/config-openvpn.yaml
> +<<<<<<< HEAD
oops :( - fixed

2017-02-01 07:06 UTC, sameersbn requested changes

2017-02-01 07:06 UTC, sameersbn commented on stable/openvpn/README.md
> +New certificates are generated with each deployment.  If persistence is enabled certificate data will be persisted accross pod restarts.  Otherwise new client certs will be needed after each deployme
typo `accross`

2017-02-09 16:53 UTC, jfelten commented
fixed the typo

2017-02-09 17:04 UTC, jfelten commented
@k8s-bot e2e test this

2017-02-13 20:11 UTC, jfelten commented
bump - anything else needed?

2017-03-14 14:56 UTC, prydonius reviewed
Thanks @jfelten, took a pass at this

2017-03-14 14:56 UTC, prydonius commented on stable/openvpn/templates/certs-pvc.yaml
> +    volume.alpha.kubernetes.io/storage-class: {{ .Values.persistence.StorageClass | quote }}
This should conditionally switch between alpha and beta as in https://github.com/kubernetes/charts/blob/master/stable/chronograf/templates/pvc.yaml#L12 to be portable.

2017-03-14 14:56 UTC, prydonius commented on stable/openvpn/values.yaml
> +  tag: latest
Can you version your image, and is there a source repo you can add to Chart.yaml?

2017-03-14 14:56 UTC, prydonius commented on stable/openvpn/values.yaml
> +  StorageClass: generic
This should be commented out so beta can be used when storage class is supplied (e.g. https://github.com/kubernetes/charts/blob/master/stable/chronograf/values.yaml#L15)

2017-03-15 20:36 UTC, jfelten commented on stable/openvpn/templates/certs-pvc.yaml
> +    volume.alpha.kubernetes.io/storage-class: {{ .Values.persistence.StorageClass | quote }}
Should beta storage be the default since it is more stable?  It will will default to alpha per your example.

2017-03-15 20:52 UTC, jfelten commented on stable/openvpn/templates/certs-pvc.yaml
> +    volume.alpha.kubernetes.io/storage-class: {{ .Values.persistence.StorageClass | quote }}
changed per the example

2017-03-15 20:52 UTC, jfelten commented on stable/openvpn/values.yaml
> +  tag: latest
added sources to chart.yaml

2017-03-15 20:52 UTC, jfelten commented on stable/openvpn/values.yaml
> +  StorageClass: generic
OK - commented out.

2017-03-15 20:58 UTC, jfelten commented
Thanks for taking a look @prydonius

2017-04-18 17:46 UTC, prydonius requested changes
Sorry for the slow turnaround on this one. A couple more comments.

2017-04-18 17:46 UTC, prydonius commented on stable/openvpn/values.yaml
> +  Enabled: true
These values should be lower camel case to be consistent with the other values

2017-04-18 17:46 UTC, prydonius commented on stable/openvpn/Chart.yaml
> +version: 1.0.2
Bump to 1.1.0 to follow semver spec

2017-04-18 18:15 UTC, jfelten commented on stable/openvpn/Chart.yaml
> +version: 1.0.2
version is now 1.1.0

2017-04-18 18:15 UTC, jfelten commented on stable/openvpn/values.yaml
> +  Enabled: true
OK I made capitalization consistent with the rest of the values

2017-04-18 20:36 UTC, jfelten commented on stable/openvpn/values.yaml
> +  tag: latest
set image version to 1.1.0

2017-04-18 20:41 UTC, jfelten commented
@k8s-bot e2e test this

2017-04-18 20:57 UTC, jfelten commented
I think I got everything - let me know if there is anything else

2017-04-24 19:17 UTC, jfelten commented
Bump - Anything I can do to close this out?

2017-05-10 21:49 UTC, viglesiasce commented
Sorry for the delay @jfelten!

2017-05-10 21:49 UTC, merged