[stable/datadog] Allow skipping Secret creation
helm/charts pull request #5285
Opened 2018-04-27 13:29 UTC by timurkhafizov

Allow skipping Secret creation since there are situations where one may not want create Secret automatically.

In order to determine if chart need to create DaemonSet and/or Deployment logical expression has been changed to be a logical implication, which means it doesn't create DaemonSet and/or Deployment only if `secret.create` is `true` and `datedog.apiKey` is missing.

2018-04-27 19:22 UTC, timstoop requested changes

2018-04-27 19:22 UTC, timstoop commented on stable/datadog/Chart.yaml
> +version: 0.11.3
This adds a new feature, please bump the minor version.

2018-04-27 19:22 UTC, timstoop commented on stable/datadog/README.md
> +Secret and disables an API key presence check, so DaemonSet and/or Deployment will be created anyway, and will expect a Secret to be present.
I'd recommend the following instead: "By default, this Chart creates a Secret and puts an API key in that Secret. However, this behaviour can be disabled when the `secret.create` is set to false. You can use this in cases where you want to manually create the Secret instead."

2018-04-27 19:22 UTC, timstoop commented on stable/datadog/templates/NOTES.txt
> +You disabled creation of Secret containing API key, therefore it is expected
"it is expected that"

2018-04-27 19:22 UTC, timstoop commented on stable/datadog/templates/NOTES.txt
> +you create Secret named '{{ template "datadog.fullname" . }}' including a key 'api-key'.
"create Secret named '{{ template "datadog.fullname" . }}' which includes a key called 'api-key', which actually contains the API key."

2018-04-27 19:22 UTC, timstoop commented on stable/datadog/templates/daemonset.yaml
> +{{- if (or (not .Values.secret.create) (.Values.datadog.apiKey)) }}
It looks like from this diff, that you didn't create a corresponding {{ end }} for this if, did you?

2018-04-27 19:22 UTC, timstoop commented on stable/datadog/templates/deployment.yaml
> +{{- if (or (not .Values.secret.create) (.Values.datadog.apiKey)) }}
It looks like from this diff, that you didn't create a corresponding {{ end }} for this if, did you?

2018-04-27 19:23 UTC, timstoop commented
/assign

2018-04-30 07:45 UTC, timurkhafizov commented on stable/datadog/templates/daemonset.yaml
> +{{- if (or (not .Values.secret.create) (.Values.datadog.apiKey)) }}
Nope, because it replaces `{{- if .Values.datadog.apiKey }}`

2018-04-30 07:45 UTC, timurkhafizov commented on stable/datadog/templates/deployment.yaml
> +{{- if (or (not .Values.secret.create) (.Values.datadog.apiKey)) }}
Nope, because it replaces {{- if .Values.datadog.apiKey }}

2018-04-30 07:45 UTC, timurkhafizov commented on stable/datadog/templates/NOTES.txt
> +You disabled creation of Secret containing API key, therefore it is expected
Ah sorry, I rephrased it that much times

2018-04-30 08:08 UTC, timstoop commented on stable/datadog/templates/daemonset.yaml
> +{{- if (or (not .Values.secret.create) (.Values.datadog.apiKey)) }}
Ah indeed!

2018-04-30 08:08 UTC, timstoop commented on stable/datadog/templates/deployment.yaml
> +{{- if (or (not .Values.secret.create) (.Values.datadog.apiKey)) }}
Totally correct :)

2018-04-30 08:09 UTC, timstoop commented
/ok-to-test

2018-04-30 08:13 UTC, timstoop commented
@hkaj @irabinovitch @xvello This change seems good to me, what do you think?

2018-05-14 12:08 UTC, timurkhafizov commented
@hkaj @irabinovitch @xvello any chance to have this reviewed?
I am preparing another PR to the chart, and this one is a kind of blocker.

Thanks!

2018-05-18 06:26 UTC, unguiculus commented
If the chart doesn't create the secret, if should be possible to specify the name of the existing secret. This is commonly done with `existingSecret`. If set, use an existing secret and otherwise generate one with the standard fullname.

2018-05-18 06:26 UTC, unguiculus commented
/assign

2018-05-18 06:26 UTC, unguiculus commented
/hold

2018-06-21 10:02 UTC, xvello commented
/assign

Hello @timurkhafizov and sorry for the delay.

I think it's indeed legit to consume an existing secret, this way, the values.yaml can be committed to git without leaking the apikey.

I agree with @unguiculus though, I'd rather have a `.Values.datadog.apiKeyExistingSecret` option, that will disable secret creation from `.Values.datadog.apiKey` and use that secret instead. WDYT?

2018-06-22 18:06 UTC, timurkhafizov commented
Hey @xvello 

I am fine with both options `.Values.existingSecret` and `.Values.datadog.apiKeyExistingSecret` actually. I'd prefer stick to `.Values.existingSecret` if that's a best practice though.

I am going to update PR this weekend as I am back from vacation.

2018-06-22 22:32 UTC, xvello commented
Hey @timurkhafizov,

As we are in the process of adding two more secret-backed credentials, I think it would be better to explicitly name what secret were are configuring, to avoid confusions down the road. This is why I wanted to go with `.Values.datadog.apiKeyExistingSecret`, to tie it with the value it is overriding ( `.Values.datadog.apiKey`). Is that OK with you?

2018-06-24 18:38 UTC, timurkhafizov commented
@xvello yeah, that sounds good and reasonable. I'll change `.Values.existingSecret` to `.Values.datadog.apiKeyExistingSecret`

2018-06-25 12:34 UTC, timurkhafizov commented
@xvello @unguiculus I've changed the logic and value name. Could you please review the PR once again?

2018-06-25 15:35 UTC, xvello commented
Thanks @timurkhafizov ,

I'll review it today.

2018-06-26 18:53 UTC, xvello commented
All good for me, thanks a bunch!

/ok-to-test
/lgtm

2018-06-26 19:03 UTC, xvello commented
/hold cancel
/woof

2018-06-26 19:03 UTC, merged