If RBAC is enabled in the cluster, the init container needs permissions
helm/charts pull request #5298
Opened 2018-04-28 01:15 UTC by ephur

@benjigoldberg

**What this PR does / why we need it**:

This optionally creates a service account with needed permissions for the Kafka init container. On an RBAC enabled cluster the expose remote is not able to complete due to permissions needed. 

**Special notes for your reviewer**:

In addition to RBAC which is most of the PR, this also adds an additional label to the services created. We have a custom ingress solution and need to be able to identify which service is tied to a pod since our ingress selects only on services. In order to minimize changes, I reused the same logic that the pod is labeled with. If there's a desire to not label a service with 'pod' I'm happy to adjust this label, but in this case the service will always be a 1:1 mapping to a pod, so it seemed to make sense.

2018-04-28 07:15 UTC, timstoop requested changes

2018-04-28 07:15 UTC, timstoop commented on incubator/kafka/templates/service-brokers-external.yaml
> +    pod: {{ $responsiblePod | quote }}
Where is this set?

2018-04-28 07:15 UTC, timstoop commented on incubator/kafka/Chart.yaml
> +version: 0.6.2
This PR adds a feature, please update the minor.

2018-04-28 07:16 UTC, timstoop commented on incubator/kafka/templates/service-brokers-external.yaml
> +    pod: {{ $responsiblePod | quote }}
Ah found it, nvm

2018-04-28 21:35 UTC, timstoop commented
/ok-to-test

2018-04-30 14:59 UTC, benjigoldberg commented
@ephur thanks for the PR and the improvement to the chart!

2018-04-30 14:59 UTC, benjigoldberg commented
/lgtm

2018-04-30 15:10 UTC, merged