Added prometheus-rabbitmq-exporter helm chart
helm/charts pull request #5311
Opened 2018-04-29 21:01 UTC by Juanchimienti

**What this PR does / why we need it**:
Hi this is a new chart for a prometheus exporter for rabbitmq

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

There are no issues related 

**Special notes for your reviewer**:

This is my first chart submit

2018-05-01 21:11 UTC, Juanchimienti commented
/assign @foxish

2018-05-07 18:45 UTC, Juanchimienti commented
Hey guys, any comments?

2018-05-08 15:43 UTC, unguiculus commented
/assign

2018-05-08 15:43 UTC, unguiculus commented
/assign @gianrubio

2018-05-09 16:15 UTC, gianrubio reviewed
/lgtm

2018-05-09 16:23 UTC, bradenwright commented
@gianrubio @unguiculus @Juanchimienti I currently have an open PR for adding the RabbitMQ exporter as a sidecar.  I found this PR last night when a comment was made on mine https://github.com/kubernetes/charts/pull/4401

I feel that running this exporter as a sidecar so metrics/alerting/etc can autoscale with the pods is important and can't be done using a separate chart as a dependency.  For that reason I added it to the rabbitmq-ha chart.

2018-05-09 16:51 UTC, Juanchimienti commented
@bradenwright We are running rabbit without helm right now so thats why we did it this way.

Anyhow I'm new here so I will follow what you guys thinks its best

2018-05-09 19:18 UTC, bradenwright commented
@Juanchimienti I'm open to discussion as well, I'd rather do what works best.  But metrics on new nodes that autoscaled seemed like a need feature for running with rmq in k8s, and unless I'm wrong with this approach would need a controller or something to watch for changes and then publish a new config.  B/c of that I went with the sidecar approach.

But right now my PR would not allow deploying the exporter without rabbitmq, I could add some enable/disable options.  But not sure that would be preferred, as you have a number of configurations that are probably useful for monitoring rmq clusters outside of k8s.  This may be a situation where it makes sense to merge both.  It maybe cleaner for supporting the separate use cases (monitoring rmq running inside and outside of k8s).

2018-05-09 20:52 UTC, Juanchimienti commented
I agree to merge both

2018-05-10 11:35 UTC, Juanchimienti commented
@unguiculus what do you think?

2018-05-10 14:05 UTC, unguiculus requested changes

2018-05-10 14:05 UTC, unguiculus commented on stable/prometheus-rabbitmq-exporter/README.md
> +- Kubernetes 1.6+ with Beta APIs enabled
1.8+

2018-05-10 14:05 UTC, unguiculus commented on stable/prometheus-rabbitmq-exporter/README.md
> +    incubator/prometheus-rabbitmq-exporter
Fix references to incubator.

2018-05-10 14:05 UTC, unguiculus commented on stable/prometheus-rabbitmq-exporter/templates/deployment.yaml
> +          - name: RABBIT_URL
Please make list indentation consistent throughout the chart. Either indent zero or two spaces.

2018-05-10 14:05 UTC, unguiculus commented on stable/prometheus-rabbitmq-exporter/values.yaml
> +annotation:
Pleae comment the annotations out. They should be optional. You don't need them if you use prometheus-operator.

2018-05-10 15:33 UTC, gianrubio commented on stable/prometheus-rabbitmq-exporter/README.md
> +$ helm install incubator/prometheus-rabbitmq-exporter
s/incubato/stable

2018-05-10 15:33 UTC, gianrubio commented on stable/prometheus-rabbitmq-exporter/README.md
> +$ helm install --name my-release incubator/prometheus-rabbitmq-exporter
s/incubator/stable

2018-05-10 15:33 UTC, gianrubio commented on stable/prometheus-rabbitmq-exporter/README.md
> +$ helm install --name my-release -f values.yaml incubator/prometheus-rabbitmq-exporter
s/incubator/stable

2018-05-10 20:45 UTC, gianrubio commented
/lgtm

2018-05-10 21:05 UTC, bradenwright commented
@gianrubio @Juanchimienti this should be going in `incubator` first, doesn't seem correct to go straight to `stable` IMHO

2018-05-10 21:07 UTC, unguiculus commented
It's ok to add it to stable.

2018-05-10 21:09 UTC, unguiculus commented
/lgtm

2018-05-12 12:41 UTC, Juanchimienti commented
This is missing the ok-to-test label. @unguiculus would you do the honors?

2018-05-16 13:06 UTC, timstoop commented
/ok-to-test

2018-05-16 13:10 UTC, merged