refactor etcd to meet the chart tech requirement
helm/charts pull request #5316
Opened 2018-04-30 10:53 UTC by cheyang

**What this PR does / why we need it**:

1. de-capitalize variables in etcd
2. make the image pull policy as "IfNotPresent"
3. Use image.repository to replace image

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-04-30 10:54 UTC, cheyang commented
/assign @timstoop

2018-04-30 17:17 UTC, unguiculus commented
/assign @lachie83

2018-04-30 17:18 UTC, unguiculus requested changes

2018-04-30 17:18 UTC, unguiculus commented on incubator/etcd/Chart.yaml
> +version: 0.3.10
This should be a major bump. Once this is through, we should move the chart to stable.

2018-04-30 17:18 UTC, unguiculus commented
/assign

2018-05-01 02:17 UTC, cheyang commented
/ok-to-test

2018-05-01 16:04 UTC, cheyang commented
/retest

2018-05-02 16:30 UTC, unguiculus commented
So, let's go with a minor bump for now as long as it is in incubator. Moving it to stable would warrant a 1.0.0.

2018-05-02 16:31 UTC, unguiculus approved these changes

2018-05-02 16:31 UTC, unguiculus commented
/lgtm

2018-05-03 16:10 UTC, unguiculus commented
/retest

2018-05-03 16:42 UTC, cheyang commented
@unguiculus I noticed the reason of the e2e testing failed due to the following error:

```
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  11s (x8 over 1m)  default-scheduler  PersistentVolumeClaim is not bound: "datadir-etcd-etcd-0" (repeated 6 times)
```
My solution is adding `if .Values.storage` to determine if needing volumeClaimTemplates:
```
{{- if .Values.storage }}
  volumeClaimTemplates:
  ...
  {{- end }}
```

2018-05-03 17:27 UTC, unguiculus commented
CI had problems with PVCs not getting bound.

2018-05-03 17:37 UTC, cheyang commented
Do you think my change of not using pvc by default is fine?

2018-05-03 18:59 UTC, unguiculus commented
@cheyang Please revert that change. You could make persistence optional, but please follow the standard approach and provide an emptyDir instead.

Here's an example:
https://github.com/kubernetes/charts/blob/master/stable/mongodb-replicaset/templates/mongodb-statefulset.yaml#L218-L244

2018-05-06 02:44 UTC, cheyang commented
@unguiculus pls review when you have time, thx.

2018-05-10 19:37 UTC, unguiculus requested changes
Please update `_helpers.tpl` as well.

2018-05-10 19:37 UTC, unguiculus commented on incubator/etcd/values.yaml
> +  pullPolicy: "Always"
IfNotPresent

2018-05-10 19:37 UTC, unguiculus commented on incubator/etcd/templates/service.yaml
> +    component: "{{ .Release.Name }}-{{ .Values.component }}"
The chart doesn't have multiple components. Why not remove the label? Instead you should add the `app` label.

2018-05-10 19:37 UTC, unguiculus commented on incubator/etcd/templates/statefulset.yaml
> +  replicas: {{ default 3 .Values.replicas }}
Remove the default funtion. It's redundant.

2018-05-14 15:01 UTC, cheyang commented
/ping @unguiculus

2018-05-16 11:44 UTC, unguiculus requested changes
A few more things.

2018-05-16 11:44 UTC, unguiculus commented on incubator/etcd/README.md
> +$ kubectl get pods -l "release=${RELEASE-NAME}"
You also need to add the `app` label to selectors.

2018-05-16 11:44 UTC, unguiculus commented on incubator/etcd/templates/statefulset.yaml
> +          value: {{ default 3 .Values.replicas | quote }}
Don't use the `default` function if not really necessary. Defaults should come from `values.yaml`.

2018-05-16 11:44 UTC, unguiculus commented on incubator/etcd/templates/statefulset.yaml
>            requests:
Don't specify defaults for resources. Just do this:

`{{ toYaml .Values.resources | indent 10 }}`

2018-05-17 12:01 UTC, unguiculus commented on incubator/etcd/templates/statefulset.yaml
> +  replicas: {{ default 3 .Values.replicas }}
Remove `default` function. Please check again and apply my comments to the whole chart.

2018-05-18 05:01 UTC, unguiculus approved these changes

2018-05-18 05:01 UTC, unguiculus commented
/lgtm

2018-05-18 05:07 UTC, merged