[stable/prometheus] Add alertmanager extra args
helm/charts pull request #533
Opened 2017-02-01 20:32 UTC by danielfm

Add support for extra command line arguments for alertmanager deployment.

One use case for this is allow the user to specify the `web.external-url` command line flag, useful when exposing the alertmanager via Ingress or some other method.

2017-02-01 20:43 UTC, danielfm commented
I signed it!

2017-02-12 20:04 UTC, mgoodness requested changes
Make it clear in the README and values files that `extraArgs` should be a hash/map.

2017-02-12 20:04 UTC, mgoodness commented on stable/prometheus/README.md
> +| `alertmanager.extraArgs` | Additional Alertmanager container arguments | `[]` |
Change the `[]` to `{}` to make it clear that extraArgs should be a hash/map, not an array/list.

Would be awesome if you did it for `server.extraArgs` as well.

2017-02-12 20:04 UTC, mgoodness commented on stable/prometheus/values.yaml
> +  # extraArgs:
Uncomment and make `extraArgs: {}`

Same for `server.extraArgs`, please.

2017-02-12 20:04 UTC, mgoodness commented
@k8s-bot ok to test

2017-02-13 09:55 UTC, danielfm commented
Is there anything missing?

2017-02-13 15:03 UTC, mgoodness approved these changes

2017-02-13 15:04 UTC, mgoodness commented
@danielfm nope, you nailed it. Thanks for the contribution!

2017-02-13 15:10 UTC, mgoodness commented
/lgtm

2017-02-13 16:52 UTC, merged