[stable/cert-manager]: add pod labels
helm/charts pull request #5332
Opened 2018-04-30 21:48 UTC by khrisrichardson

**What this PR does / why we need it**:

* adds pod labels
* deduplicate fullname if name and release name are identical

2018-05-01 17:24 UTC, mattfarina commented
/ok-to-test

2018-05-03 19:48 UTC, timstoop requested changes

2018-05-03 19:48 UTC, timstoop commented on stable/cert-manager/Chart.yaml
> +version: 0.2.11
You're adding a new feature, so that warrant a minor version bump instead of patch level.

2018-05-11 17:18 UTC, unguiculus commented
This chart is maintained upstream. Please create a PR there.
https://github.com/jetstack/cert-manager

2018-05-11 17:19 UTC, unguiculus commented
/close

2018-05-11 17:19 UTC, closed without merging