Add api addr
helm/charts pull request #5342
Opened 2018-05-01 16:13 UTC by jbialy

**What this PR does / why we need it**:

- Allows for passing additional `env` values to the Vault containers. As an example, this is required in a situation where `VAULT_CLUSTER_ADDR` needs to be defined manually when dealing with backends other than Consul. When deploying a cluster backed by DynamoDB, vault returns an error, `api_addr not set`.

- Add an example of how to use type:loadbalancer and AWS ELB when working with a `kops` kubernetes cluster on AWS. Also shows how to use the `dns-controller` annotation to have the controller automatically provision the route 53 records.

- Add an example of how to pass the `VAULT_API_ADDR` as an environment variable to the vault containers.

2018-05-01 16:34 UTC, jbialy commented
CLA signed.

2018-05-01 16:37 UTC, jbialy commented
/assign @seanknox

2018-05-01 16:42 UTC, jbialy commented
/assign @foxish

2018-05-01 16:44 UTC, jbialy commented
/assign @coreypobrien

2018-05-01 17:21 UTC, mattfarina commented
/ok-to-test

2018-05-02 16:47 UTC, jbialy commented
Anything else I need to do before this gets tested?

2018-05-09 21:47 UTC, unguiculus requested changes

2018-05-09 21:47 UTC, unguiculus commented on incubator/vault/templates/deployment.yaml
> +        {{- if .Values.vault.env }}
Please call it `extraEnv` or `extraVars`. This is what's commonly used.

2018-05-22 20:00 UTC, jbialy commented
/assign @foxish

2018-05-24 20:11 UTC, unguiculus requested changes

2018-05-24 20:11 UTC, unguiculus commented on incubator/vault/values.yaml
> +  # extraEnv:
Don't comment it out.

```yaml
  # Configure additional environment variables for the Vault containers
  extraEnv: {}
  #   - name: VAULT_API_ADDR
  #     value: "https://vault.internal.domain.name:8200"
```

2018-05-24 20:11 UTC, unguiculus commented
/assign

2018-05-24 20:12 UTC, unguiculus requested changes

2018-05-24 20:12 UTC, unguiculus commented on incubator/vault/Chart.yaml
> +version: 0.8.1
Bump minor version for a new feature.

2018-05-25 11:10 UTC, unguiculus commented
/lgtm

2018-05-25 11:10 UTC, unguiculus approved these changes

2018-05-25 12:00 UTC, merged