Reload sentry-kubernetes deployment after configuration change
helm/charts pull request #5370
Opened 2018-05-03 08:54 UTC by gianrubio

2018-05-03 19:38 UTC, timstoop commented
/lgtm
I'm not entirely sure if you're adding a feature or not, so whether this would warrant a minor version increase instead of patch level. Not against just increase the patch level for this, though.

2018-05-03 20:02 UTC, gianrubio commented
/assign @lachie83

2018-05-09 21:56 UTC, unguiculus requested changes

2018-05-09 21:56 UTC, unguiculus commented on incubator/sentry-kubernetes/templates/deployment.yaml
> +        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
The `$` sign is unnecessary in this case.

2018-05-09 21:56 UTC, unguiculus commented
/assign

2018-05-10 12:14 UTC, unguiculus commented
/lgtm

2018-05-10 12:24 UTC, merged