[stable/kube-lego] Update link to migration guide
helm/charts pull request #5371
Opened 2018-05-03 10:08 UTC by rolandboon

**What this PR does / why we need it**:
The docs of cert-manager are moved from the repo to readthedocs.io. The current link to migration guide in readme is dead.

2018-05-03 10:14 UTC, rolandboon commented
/assign @prydonius

2018-05-03 19:35 UTC, timstoop requested changes
Charts are immutable, so all changes, even documentation changes, require a bump of the version in Chart.yaml. Simply increase the patch level by 1.

2018-05-04 13:00 UTC, prydonius commented
@rolandboon the CI requires a `home` and `apiVersion` field be added to the Chart.yaml. Even though this chart is deprecated, the migration guide is an important link that we should update. We can try adding the `home` and `apiVersion` here, if there are further issues we may consider bypassing CI.

2018-05-09 22:36 UTC, unguiculus commented
/ok-to-test

2018-05-09 22:45 UTC, unguiculus commented
/assign

2018-05-09 22:45 UTC, unguiculus commented
/lgtm

2018-05-09 23:37 UTC, merged