Added prometheus mysql exporter chart
helm/charts pull request #5373
Opened 2018-05-03 13:02 UTC by Juanchimienti

**What this PR does / why we need it**:

This is a new helm chart for the prometheus mysql exporter 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-05-03 13:09 UTC, Juanchimienti commented
/assign @seanknox

2018-05-03 16:06 UTC, unguiculus commented
/assign

2018-05-03 16:06 UTC, unguiculus commented
Please make sure you compare with what you get from `helm create` using Helm 2.8+ and update accordingly.

2018-05-03 16:07 UTC, unguiculus commented
/assign @gianrubio

2018-05-04 18:13 UTC, gianrubio commented
/lgtm

2018-05-04 18:13 UTC, gianrubio commented on stable/prometheus-mysql-exporter/README.md
> +This chart bootstraps a prometheus [mysqk exporter](http://github.com/prometheus/mysql_exporter) deployment on a [Kubernetes](http://kubernetes.io) cluster using the [Helm](https://helm.sh) package m
> can connectto... 

you missed a space here

2018-05-04 19:02 UTC, Juanchimienti commented
/assign @seanknox

2018-05-07 18:44 UTC, Juanchimienti commented
Hey guys, any comments?

2018-05-10 19:03 UTC, unguiculus requested changes
I'd like you to indent lists consistently throughout the chart. Either use zero or two spaces.

2018-05-10 19:03 UTC, unguiculus commented on stable/prometheus-mysql-exporter/templates/_helpers.tpl
> +{{- define "prometheus-mysql-exporter.cloudsqlsecret" -}}
Should be based on the fullname partial. I'd suggest this:

`{{ template "prometheus-mysql-exporter.fullname" }}-cloudsqlsecret`

2018-05-10 19:03 UTC, unguiculus commented on stable/prometheus-mysql-exporter/templates/deployment.yaml
> +        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
The `$` symbol is unnecessary here and could be confusing. Please remove it.

2018-05-12 12:42 UTC, Juanchimienti commented
Changes applied

2018-05-16 13:07 UTC, timstoop commented
/ok-to-test

2018-05-16 13:25 UTC, Juanchimienti commented
@gianrubio can you re add the lgtm ?

2018-05-16 13:41 UTC, gianrubio commented
/lgtm

2018-05-16 13:49 UTC, Juanchimienti commented
/assign @seanknox

2018-05-17 12:04 UTC, unguiculus requested changes

2018-05-17 12:04 UTC, unguiculus commented on stable/prometheus-mysql-exporter/templates/_helpers.tpl
> -{{- define "prometheus-mysql-exporter.cloudsqlsecret" -}}
You should have kept it but changed as I suggested. It is still used in the chart.

2018-05-17 17:02 UTC, Juanchimienti commented
Sorry @unguiculus I didn't get your suggestion at first.

Is this what you mean ?

2018-05-17 19:04 UTC, unguiculus approved these changes

2018-05-17 19:04 UTC, unguiculus commented
/lgtm

2018-05-17 19:30 UTC, merged