added identity service
helm/charts pull request #5387
Opened 2018-05-04 03:22 UTC by rcladmin

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-05-04 03:42 UTC, rcladmin commented
/assign @seanknox

2018-05-04 03:45 UTC, rcladmin commented
/test (|all)

2018-05-04 03:47 UTC, rcladmin commented
/retest

2018-05-09 22:05 UTC, unguiculus requested changes
Please make sure you follow our best practices. Compare with what you get from `helm create` and update accordingly.

2018-05-09 22:05 UTC, unguiculus commented on incubator/identityservice/README.md
> +* KUBE-LEO
- Helm is a prerequisite anyways. No need to specify it here.
- Why is nginx-ingress a requirement? Can't you use any other ingress controller?
- kube-lego is deprecated. It shouldn't be required either.

2018-05-09 22:05 UTC, unguiculus commented on incubator/identityservice/README.md
> +helm repo add rcl-apps https://rcladmin.github.io/helm-charts/
Wrong repo.

2018-05-09 22:05 UTC, unguiculus commented on incubator/identityservice/README.md
> +
Add all params to readme

2018-05-09 22:06 UTC, unguiculus commented
/assign

2018-05-10 07:42 UTC, unguiculus requested changes

2018-05-10 07:42 UTC, unguiculus commented on incubator/identityservice/README.md
>  ### Helm repository
Remove line

2018-05-10 07:42 UTC, unguiculus commented
Please fix your CLA

2018-05-10 08:06 UTC, rcladmin commented
/check-cla

2018-05-10 08:33 UTC, rcladmin commented
/check-cla

2018-05-10 08:43 UTC, rcladmin commented on incubator/identityservice/README.md
>  ### Helm repository
made change. How do I regain cla?

2018-05-10 10:09 UTC, rcladmin commented
/check_cla

2018-05-17 19:51 UTC, unguiculus requested changes
Please compare with what you get from `helm create` using Helm 2.8+ and update accordingly.

Also, please study our review guidelines and apply best practices: https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md

2018-05-24 13:53 UTC, closed without merging