Setup eventrouter chart
helm/charts pull request #5390
Opened 2018-05-04 09:30 UTC by gianrubio

This is a replacement from #1023

2018-05-04 09:36 UTC, gianrubio commented
/assign @sameersbn

2018-05-09 22:12 UTC, unguiculus commented
Move it to stable directly.

2018-05-09 22:12 UTC, unguiculus commented
/assign

2018-05-10 14:23 UTC, unguiculus requested changes

2018-05-10 14:23 UTC, unguiculus commented on stable/eventrouter/templates/deployment.yaml
> +      app: {{ template "eventrouter.name" . }}
Add `release` label to selector.

2018-05-10 14:23 UTC, unguiculus commented on stable/eventrouter/templates/deployment.yaml
> +        release: {{.Release.Name }}
Add space after `{{`.

2018-05-10 14:23 UTC, unguiculus commented on stable/eventrouter/values.yaml
> +  pullPolicy: Always
IfNotPresent

2018-05-10 14:23 UTC, unguiculus commented on stable/eventrouter/templates/deployment.yaml
> +      - name: {{ .Chart.Name }}
Make list indentation consistent throughout the chart. Either use zero or two spaces.

2018-05-24 17:34 UTC, unguiculus requested changes

2018-05-24 17:34 UTC, unguiculus commented on stable/eventrouter/Chart.yaml
> +- eventrouter
Add maintainers

2018-05-24 17:34 UTC, unguiculus commented on stable/eventrouter/templates/deployment.yaml
> +          - name: config-volume
Indent one more level here for consistency.

2018-05-24 17:34 UTC, unguiculus commented on stable/eventrouter/values.yaml
> +
Add

```yaml
tolerations: []

nodeSelector: {}
```

2018-06-01 12:35 UTC, gianrubio commented on stable/eventrouter/Chart.yaml
> +- eventrouter
done

2018-06-01 12:35 UTC, gianrubio commented on stable/eventrouter/values.yaml
> +
done

2018-06-01 15:24 UTC, unguiculus commented
/lgtm

2018-06-01 15:27 UTC, merged