[incubator/horovod] support horovod
helm/charts pull request #5415
Opened 2018-05-06 12:51 UTC by cheyang

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-05-09 22:33 UTC, unguiculus requested changes
Please make list indentation consistent throughout the chart. Either use zero or two spaces.

Please move the chart to stable.

2018-05-09 22:33 UTC, unguiculus commented on incubator/horovod/templates/service.yaml
> +---
Separate files per resource, please.

2018-05-09 22:33 UTC, unguiculus commented on incubator/horovod/values.yaml
> +  hostKey: |-
Don't add keys to the chart.

2018-05-09 22:33 UTC, unguiculus commented
/assign

2018-05-13 16:03 UTC, cheyang commented on incubator/horovod/templates/service.yaml
> +---
Sure.

2018-05-13 16:04 UTC, cheyang commented on incubator/horovod/values.yaml
> +  hostKey: |-
Thx for reminding.

2018-05-17 18:21 UTC, unguiculus commented
Why don't you use the official image? Also, the latest release is v0.13.0 while your versioning is different?

2018-05-17 22:28 UTC, cheyang commented
Sure, let me change to the official image.

I was asking them to provide official docker image, because they only provided Dockerfile before.  :)  see https://github.com/uber/horovod/issues/261 .

2018-05-18 04:58 UTC, unguiculus commented
/ok-to-test

2018-05-18 04:59 UTC, unguiculus approved these changes

2018-05-18 04:59 UTC, unguiculus commented
/lgtm

2018-05-18 05:02 UTC, merged