[stable/spinnaker] Allow users to register arbitrary Kubernetes clusters
helm/charts pull request #5456
Opened 2018-05-08 21:00 UTC by viglesiasce

**What this PR does / why we need it**:
Adds ability to manage arbitrary clusters using the Spinnaker chart. Currently you can only (easily) manage the one that you deploy to.

2018-05-08 21:48 UTC, ameer00 commented
Tested on a GKE cluster running 1.9.6-gke.1.  Works great!!

2018-05-09 12:35 UTC, timstoop requested changes
Nice change!

2018-05-09 12:35 UTC, timstoop commented on stable/spinnaker/Chart.yaml
> +version: 0.4.2
As you're adding a new feature, please bump the minor version.

2018-05-15 06:03 UTC, viglesiasce commented
/retest

2018-05-15 06:25 UTC, viglesiasce commented
Thanks for the review @timstoop! I updated the version and fixed an issue with the default pod spec.

2018-05-23 09:48 UTC, timstoop commented
/lgtm

2018-05-23 09:56 UTC, merged