[grafana/stable] add support for database credentials
helm/charts pull request #5458
Opened 2018-05-08 22:10 UTC by mikeraimondi

**What this PR does / why we need it**:
Allows database credentials to be stored in a configurable secret.

2018-05-08 22:11 UTC, mikeraimondi commented
/assign @sameersbn

2018-05-09 08:44 UTC, sameersbn requested changes

2018-05-09 08:44 UTC, sameersbn commented on stable/grafana/templates/deployment.yaml
> +          imagePullPolicy: {{ .Values.image.pullPolicy }}
`cloudSQL.image` should define it's own image pull policy, i.e. `cloudSQL.image.pullPolicy`

2018-05-09 08:44 UTC, sameersbn commented on stable/grafana/values.yaml
> +    # existingSecret: ""
Please uncomment the default values, else users would need to define all the params when they want to enable this feature.

2018-05-09 12:31 UTC, timstoop requested changes
Can you please document the new options in the README as well?

2018-05-09 12:31 UTC, timstoop commented on stable/grafana/Chart.yaml
> +version: 1.3.1
As this adds a new feature, please bump the minor version.

2018-05-10 10:19 UTC, timstoop commented
There have been merges to stable/grafana, could you merge from master and fix any conflicts? You probably need to look at the version in Chart.yaml again after that.

2018-05-11 22:31 UTC, jasongwartz commented on stable/grafana/templates/deployment.yaml
> +            - name: GF_DATABASE_USER
Couldn't this be implemented using the changes from https://github.com/kubernetes/charts/pull/5435?

2018-05-12 06:23 UTC, unguiculus commented on stable/grafana/templates/deployment.yaml
> +            - name: GF_DATABASE_USER
Agreed. Closing this.

2018-05-12 06:23 UTC, closed without merging