Allow alternate elasticsearch schedulers
helm/charts pull request #5462
Opened 2018-05-09 00:31 UTC by knorby

**What this PR does / why we need it**: Adds ability to use alternative schedulers, like stork

2018-05-09 00:32 UTC, knorby commented
/assign @simonswine

2018-05-09 11:24 UTC, timstoop requested changes

2018-05-09 11:24 UTC, timstoop commented on incubator/elasticsearch/Chart.yaml
> +version: 0.4.10
You're adding a new feature, so please bump the minor.

2018-05-09 18:04 UTC, knorby commented
Sorry! I noticed a big bug here after submitting that I somehow didn't catch before.

2018-05-10 07:26 UTC, unguiculus commented
/ok-to-test

2018-05-10 10:37 UTC, timstoop commented
From the errors, I'm guessing that discovery is broken (again). Please be aware that there's currently a full rewrite under way for this Chart, which (among lots of other things) changes the way discovery works as the current one is not very reliable, it seems.

If you're really bent on getting this PR accepted anyway, you may consider changing the default `rbac.enable` to `true` instead, which I think will fix the e2e error.

Pinging @rendhalver @mikn as they're doing most of the rewrite. You guys might want to see if this PR can be incorporated as well, as I think it's a useful one. Due to ES storage requirements, it makes sense to use non-default, more specialised StorageClasses. IMHO, of course.

2018-05-10 10:38 UTC, timstoop commented
PR #3074 is btw the main one for the rewrite, I think.

2018-05-10 12:29 UTC, rendhalver commented
All the ES fixes are in #2889.
As you would expect the elastic-stack chart is basically a wrapper around elasticsearch/kibana/logstash/curator and probably fluentd when I get the chance.

2018-05-10 17:57 UTC, knorby commented
It doesn't seem like RBAC fixes the discovery issues on the e2e test. I'm not anxious to get this merged, but I do want to make sure there are good options on storage on the rewrite, including the scheduler obviously.

2018-07-16 11:17 UTC, rendhalver commented
@knorby The DNS discovery fixes got merged a while ago. Do you want to make another pass at this or rebase this PR?

2018-07-16 18:01 UTC, knorby commented
@rendhalver thanks for the reminder, I hadn't been tracking the state of the chart! It is now rebased and should be fine. This is still a really small change, and the bugs from discovery/RBAC weren't related anyway, so it should be fine now.

2018-07-16 20:00 UTC, knorby commented
/retest

2018-09-19 06:46 UTC, davidkarlsen commented
@knorby can you please sign off your commits? TIA

2018-11-02 08:18 UTC, closed without merging