Allow setting of command and args on elastalert deployment
helm/charts pull request #5530
Opened 2018-05-11 19:40 UTC by brosander

**What this PR does / why we need it**: Allowing for custom commands and args will give more flexibility to the helm chart. :smile:

I hope to use it with https://github.com/jertel/elastalert-docker/pull/1 but it should be pretty generically useful.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-05-15 19:05 UTC, rjkernick requested changes

2018-05-15 19:05 UTC, rjkernick commented on stable/elastalert/Chart.yaml
> +version: 0.2.1
Please bump the minor version as this adds a new feature

2018-05-15 19:05 UTC, rjkernick commented
/ok-to-test

2018-05-15 21:36 UTC, brosander commented
@rjkernick bumped minor version, rebased on master

thanks for feedback :smile:

2018-05-16 12:17 UTC, rjkernick commented
/lgtm

2018-05-17 14:13 UTC, brosander commented
@rjkernick I rebased on master to remove a conflict in Chart.yaml

2018-05-17 14:13 UTC, brosander commented
/assign @prydonius

@prydonius the CI robot suggested you :smile:

2018-05-18 06:44 UTC, unguiculus commented
cc @jertel @pickledrick

2018-05-18 11:39 UTC, jertel commented
/lgtm

2018-05-21 18:11 UTC, brosander commented
@pickledrick thoughts?

2018-05-23 15:53 UTC, brosander commented
@unguiculus @rjkernick @jertel 

Is there someone else I should tag on this?

2018-05-23 16:05 UTC, jertel commented
Not that I'm aware of. The original chart author, pickledrick, hasn't chimed in on the past several PRs.

2018-05-25 09:28 UTC, unguiculus commented
/lgtm

2018-05-25 10:42 UTC, merged