Metrics api fixes
helm/charts pull request #5538
Opened 2018-05-12 12:45 UTC by olemarkus

**What this PR does / why we need it**:

This PR adds a new chart to the incubator repository for the Kubernetes metrics-server.
https://github.com/kubernetes-incubator/metrics-server

**Special notes for your reviewer**:
I have not come across a chart that adds a new API service so unsure how to do something like that. Right now, this chart just assumes that the API service does not exist.

2018-05-16 06:35 UTC, olemarkus commented
/assign @seanknox

2018-05-18 15:56 UTC, unguiculus requested changes
Thanks for the PR. Please compare with what you get with `helm create` using Helm 2.8+ and update accordingly. Also, please follow our RBAC best practices.

https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/rbac.md

Is the namespace kube-system required? Otherwise, remove it and let the user decide.

2018-05-18 15:56 UTC, unguiculus commented
/assign

2018-05-18 18:14 UTC, kennethaasan commented
Thanks for the feedback @unguiculus. I tried to compare with `helm create` and make changes accordingly. Also applied the RBAC best practices.

Regarding namespace kube-system, it looks like it's required here: https://github.com/kubernetes-incubator/metrics-server/pull/4

2018-05-24 19:24 UTC, unguiculus requested changes

2018-05-24 19:24 UTC, unguiculus commented on incubator/metrics-server/Chart.yaml
> +- https://github.com/kubernetes-incubator/metrics-server
Add maintainer

2018-05-24 19:24 UTC, unguiculus commented on incubator/metrics-server/templates/metrics-server-serviceaccount.yaml
> +{{- if .Values.rbac.create -}}
`{{- if .Values.serviceAccount.create -}}`

2018-05-24 19:24 UTC, unguiculus commented on incubator/metrics-server/values.yaml
> +  pullPolicy: Always
IfNotPresent

2018-05-24 21:04 UTC, olemarkus commented on incubator/metrics-server/Chart.yaml
> +- https://github.com/kubernetes-incubator/metrics-server
Should I just add myself like below? I removed it from the initial commit as it didn't pass the tests.

2018-05-25 11:28 UTC, unguiculus requested changes

2018-05-25 11:28 UTC, unguiculus commented on incubator/metrics-server/Chart.yaml
> +- name: Ole Markus With
You need to specify your Github username

2018-05-25 16:31 UTC, DirectXMan12 commented
kube-system isn'd required for metrics-server itself

2018-05-30 17:28 UTC, DirectXMan12 commented
metrics-server should also be granted the `system:auth-delegator` clusterrole, and the `extension-apiserver-authentication-reader` role, specifically in the `kube-system` namespace.

2018-05-31 12:27 UTC, olemarkus commented
@unguiculus do the changes done in response to your review look okay?

2018-06-01 15:49 UTC, unguiculus commented
@DirectXMan12 thanks for reviewing. Could you have another look, please?

2018-06-01 15:49 UTC, unguiculus commented
/ok-to-test

2018-06-01 17:19 UTC, olemarkus commented
The failure there looks a bit tricky. A plain cluster typically will not have that clusterrole role, but e2e does?

2018-06-06 15:38 UTC, olemarkus commented
Should I do anything about the failed test? I see some charts have some sort of default values CI overrides, but i couldn't find any documentation on how this works. If so it would be nice to know which resources the CI server already have.

2018-06-06 20:01 UTC, unguiculus commented
The test cluster is on GKE.

Here's the docs you were looking for:
https://github.com/kubernetes/charts/blob/master/test/README.md#providing-custom-test-values

2018-06-06 20:19 UTC, olemarkus commented
Thanks. So as GKE comes with metrics-server, I assume everything put into kube-system must be configurable and disabled for the tests. Should it be enabled or disabled by default?

2018-06-08 15:25 UTC, unguiculus commented
I guess it makes sense to enable it by default.

2018-06-09 09:14 UTC, olemarkus commented
CI passing now. @unguiculus / @DirectXMan12: can you have another look?

2018-06-14 20:25 UTC, DirectXMan12 requested changes
nit about permissions -- update deployments is only needed for pod-nanny, IIRC

2018-06-14 20:25 UTC, DirectXMan12 commented on incubator/metrics-server/templates/cluster-role.yaml
> +      - deployments
you don't need this unless you're trying to run pod-nanny

2018-06-15 10:02 UTC, olemarkus commented
Removed the mentioned rule and the server still works.

2018-06-15 16:36 UTC, unguiculus commented
Your branch is outdated. Please merge in the latest master to get the latest CI updates. This should help.

2018-06-15 16:52 UTC, unguiculus requested changes

2018-06-15 16:52 UTC, unguiculus commented on incubator/metrics-server/templates/NOTES.txt
> +The metric server has been deployed. In a few minutes you should be able to
You may want to print a warning if `apiService.create` is `false`.

2018-06-15 16:52 UTC, unguiculus commented on incubator/metrics-server/README.md
> +`image.pullPolicy` | Image pull policy | `Always`
IfNotPresent

2018-06-15 19:05 UTC, olemarkus commented
Thanks for the feedback. Have tried to update accordingly. To be honest, this is starting to reach the quality of many of the stable charts now. Would be lovely to merge this soon so more people can test and put this to use.

2018-06-17 12:25 UTC, unguiculus commented
I'd suggest you move it to stable before we merge it.

2018-06-17 12:25 UTC, unguiculus approved these changes

2018-06-19 13:41 UTC, olemarkus commented
@unguiculus: Cool. Moved!

2018-06-24 14:16 UTC, unguiculus commented
/lgtm

2018-06-24 14:25 UTC, merged

2018-07-05 13:51 UTC, mf-lit commented
@olemarkus I notice the metrics-server deployment container spec doesn't have any provision for setting resources. Before I attempt a PR, I just wanted to make sure I didn't miss something?

2018-07-05 13:56 UTC, olemarkus commented
You didn't miss anything. A PR would for this would be good. Thanks

2018-07-05 15:17 UTC, mf-lit commented
https://github.com/kubernetes/charts/pull/6488

2018-07-13 09:14 UTC, sebastien-prudhomme commented
@olemarkus are you sure on the file cluster-role.yaml?

If i compare to deploy files in the metrics-server github project (https://github.com/kubernetes-incubator/metrics-server/blob/master/deploy/1.8%2B/resource-reader.yaml), some rights are missing:

```diff
@@ -14,9 +14,18 @@ rules:
     resources:
       - pods
       - nodes
+      - nodes/stats
       - namespaces
     verbs:
       - get
       - list
       - watch
+  - apiGroups:
+    - "extensions"
+    resources:
+      - deployments
+    verbs:
+      - get
+      - list
+      - watch
 {{- end -}}
```

Doest the upstream YAML file give too many rights?

2018-07-13 09:48 UTC, olemarkus commented
Yes. The upstream one has permissions that is noecessary only with pod-nannny. Was discussed earlier in this PR.

2018-07-13 10:33 UTC, sebastien-prudhomme commented
@olemarkus Not this one?

https://github.com/kubernetes-incubator/metrics-server/pull/59

2018-07-18 14:38 UTC, olemarkus commented
In K8s 1.11, some RBAC stuff shifted and from then on you do need the `nodes/stats` resource permission. So that one should get merged in as well.