[stable/newrelic-infrastructure] Retain support for Kubernetes 1.8
helm/charts pull request #5557
Opened 2018-05-14 14:09 UTC by coreypobrien

#4917 switched the Daemonset to `apps/v1`. This change re-adds support for Kubernetes 1.8 using `apps/v1beta2`.

2018-05-17 20:37 UTC, unguiculus requested changes

2018-05-17 20:37 UTC, unguiculus commented on stable/newrelic-infrastructure/templates/daemonset.yaml
> +apiVersion: apps/v1beta2
I'd just go for this and remove the if block. This is what we commonly use now.

2018-05-18 04:37 UTC, unguiculus commented
cc @rk295

2018-05-18 04:37 UTC, unguiculus approved these changes

2018-05-18 04:37 UTC, unguiculus commented
/ok-to-test

2018-05-31 03:11 UTC, coreypobrien commented
@unguiculus Anything else needed here?

2018-06-08 16:42 UTC, unguiculus commented
/lgtm

2018-06-08 16:42 UTC, unguiculus commented
Sorry for the delay.

2018-06-08 16:45 UTC, merged