Grfana: Prepare chart for 5.1.x
helm/charts pull request #5576
Opened 2018-05-15 14:28 UTC by sylr

When upgrading to 5.1.x we need to chown the whole /var/lib/grafana dir in order to comply with the new grafana user id used in the latest docker image.

2018-05-15 14:41 UTC, sylr commented
/assign unguiculus

2018-05-15 20:34 UTC, christian-roggia commented on stable/grafana/templates/deployment.yaml
> +        - /var/lib/grafana
I would use `command: ["chown", "-R", "472:472", "/var/lib/grafana"]` here.

2018-05-15 20:43 UTC, sylr commented on stable/grafana/templates/deployment.yaml
> +        - /var/lib/grafana
All right

2018-05-16 04:43 UTC, unguiculus commented
#5386 updated Grafana to 5.1.2. I think this PR is now obsolete.

2018-05-16 06:15 UTC, sylr commented
It's not if you think about upgrading your helm installed grafana from anything below 5.1.0.

If the permissions are wrong grafana will crash.

It's why I did this.

2018-05-16 16:52 UTC, OndroNR commented
I wanted to deploy grafana with clean persistent volume and encountered this issue. I made one-run Job, based on initial container in this PR, to fix ownerhip. This PR is still needed.

2018-05-17 07:31 UTC, sylr commented
Could we merge this ASAP for people like @OndroNR that are going to upgrade grafana and be stuck.

2018-05-17 07:38 UTC, OndroNR commented
I was doing clean install with enabled persistence.

2018-05-17 11:49 UTC, unguiculus commented
/ok-to-test

2018-05-17 14:01 UTC, unguiculus requested changes

2018-05-17 14:01 UTC, unguiculus commented on stable/grafana/templates/deployment.yaml
> +{{- if semverCompare ">= 5.1.0" .Values.image.tag }}
This is not ideal. If you use a custom image that has a different versioning scheme, this won't work. I think it would be best to make this optional with a flag.

2018-05-18 08:03 UTC, FrederikNS commented
As I mentioned in #5635, I also just ran into the permission problem with persistent volumes.

2018-05-18 10:35 UTC, sylr commented on stable/grafana/templates/deployment.yaml
> +{{- if semverCompare ">= 5.1.0" .Values.image.tag }}
I prefer to let it like this, if you want to use custom images you should tag them correctly.

2018-05-19 20:13 UTC, scottrigby commented
Hi everyone, after a Charts maintainers conversation, the root of the problem appears to be that semver was not properly followed in #5386 in a way that was non-obvious: 
- The MINOR version was bumped (from `1.8.0` to `1.9.0`) which made sense, because a new feature was added (RBAC)
- However, the image and app version was also bumped (from `5.0.4` to `5.1.2`), which is the Grafana version that introduced backwards incompatible changes. Even though Grafana version did not follow semver here, the chart should.
    - Note that while our automated do semver comparison, AFAIK we don't explicitly mention semver as a requirement anywhere except in the [Un-deprecating A Chart](https://github.com/kubernetes/charts/blob/master/PROCESSES.md#un-deprecating-a-chart) section of our PROCESSES doc

Given that we accidentally missed this in #5386, we should change this PR from attempting to automatically handle this change, to adding a note to the user that if upgrading from < `1.9.0`, to run a k8s-specific command (`kubectl exec ... -it chown -R 472:472 /var/lib/grafana`), and link to the [Grafana documentation page on this](http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later) in the same note rather than in an automated template step.

Additionally this PR should address the earlier oversight by properly bumping the MAJOR version (to `2.0.0`). 

Let's use #5657 for tracking creating and documenting the charts-wide policy for handling cases like this. Practically, the question for this PR now is where to communicate the above info to upgrading users so that they're less likely to miss it? I'm thinking maybe a new `Upgrading` section just above `Installing the chart`?

2018-05-22 12:59 UTC, willejs commented
Would setting the fsGroup in securitycontext of the pod fix this for new installs?

2018-05-29 19:48 UTC, thomasbarton commented
currently stable/grafana is broken when doing a clean install with a persistent volume.  This pr fixes the issue.  Any update on merging?

2018-06-08 07:53 UTC, xmartinez commented
@scottrigby Not sure the semver reasoning applies to this issue. This is broken for fresh installs, where backwards compatibility consideration do not apply (there is no previous install to be compatible with).

For the sake of anyone encountering this issue, the following workaround can be applied:
```
kubectl create --filename=- <<'EOF'
apiVersion: batch/v1
kind: Job
metadata: {name: grafana-chown}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: grafana-chown
        command: [chown, -R, "472:472", /var/lib/grafana]
        image: busybox:latest
        volumeMounts:
        - {name: storage, mountPath: /var/lib/grafana}
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: grafana
EOF
```
Note that `kubectl exec` cannot be used, because the container is crash-looping on startup, so it does not live long enough to be able to run any command.

2018-07-01 16:36 UTC, monotek commented
@sylr 
could you resolve the merge conflicts please?

2018-07-02 13:38 UTC, sylr commented
@monotek AFAIU This is not going to be merged.

2018-07-02 13:59 UTC, monotek commented
ok, thanks for the info anyway :-)

2018-07-05 19:07 UTC, immunda commented
This was a real pain to get to the bottom of and is still broken on fresh installs as outlined above.

I independently came up with the same `initContainer` solution as the only viable option after exploring `fsGroup` for the pod's security context.

Any chance of a revisit @scottrigby?

2018-08-08 11:00 UTC, closed without merging

2018-08-21 18:03 UTC, trinitronx commented
This is still a valid issue with fresh install of this Helm chart.  As previous posters mentioned, SemVer bump was missed for users with persistent volumes created before Grafana `5.1.x`, however **this still affects new installs** and this PR is still needed regardless of SemVer upgrade considerations.