Adding HTTPS using AWS ACM with whitelisting option to the concourse chart
helm/charts pull request #5594
Opened 2018-05-16 10:22 UTC by danielwhatmuff

**What this PR does / why we need it**:

* Provides a way to whitelist the spawned AWS load balancer when service type is set to LoadBalancer.
* Provides a way to run concourse over HTTPS with an existing AWS ACM certificate when using service type LoadBalancer.

**Special notes for your reviewer**:
Tested successfully on a kops managed cluster with the following versions
```
$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

2018-05-18 08:15 UTC, timstoop commented
@danielwhatmuff Please make sure you sign the CLA!

2018-05-22 13:00 UTC, danielwhatmuff commented
@timstoop I have joined the CNCF with the same email/username as for github. Do I need to do anything else?

2018-05-22 13:02 UTC, danielwhatmuff commented
@frodenas @william-tran

2018-05-22 13:02 UTC, danielwhatmuff commented
/assign @william-tran

2018-05-22 15:14 UTC, william-tran commented
@danielwhatmuff please bump the version to 1.6.0 since we're using semver and this is a new feature.

2018-05-22 15:14 UTC, william-tran commented
/ok-to-test

2018-05-22 15:15 UTC, william-tran requested changes

2018-05-22 15:15 UTC, william-tran commented on stable/concourse/Chart.yaml
> +version: 1.5.2
please bump to 1.6.0

2018-05-24 15:43 UTC, danielwhatmuff commented on stable/concourse/Chart.yaml
> +version: 1.5.2
@william-tran - done.

2018-05-24 16:54 UTC, william-tran approved these changes

2018-05-24 16:54 UTC, william-tran commented
/lgtm

2018-05-24 17:05 UTC, merged

2018-05-29 09:15 UTC, danielwhatmuff commented
🎉