[incubator/vault] Add Ingress labels
helm/charts pull request #5634
Opened 2018-05-18 06:52 UTC by mathieuherbert

**What this PR does / why we need it**:
- Add custom ingress labels
- fix default replicas count on Readme
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
- the capacity to have custom labels in the ingress 
- error in documentation
**Special notes for your reviewer**:

2018-05-18 06:57 UTC, mathieuherbert commented
CLA signed

2018-05-18 07:51 UTC, timstoop requested changes
Please add the ingress.labels key to both the values.yaml and the README.

2018-05-18 07:51 UTC, timstoop commented on incubator/vault/Chart.yaml
> +version: 0.8.1
You're adding a new feature, please bump the minor version.

2018-05-18 09:14 UTC, mathieuherbert commented
@timstoop thanks for the review, I did a commit :)

2018-05-24 18:40 UTC, unguiculus commented
/ok-to-test

2018-05-24 18:40 UTC, unguiculus commented
/assign

2018-05-24 18:48 UTC, unguiculus commented
/lgtm

2018-05-24 18:49 UTC, merged