[stable/artifactory] adding support for edge node and replicator
helm/charts pull request #5649
Opened 2018-05-18 22:58 UTC by jainishshah17

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-05-25 09:45 UTC, unguiculus requested changes

2018-05-25 09:45 UTC, unguiculus commented on stable/artifactory/README.md
> +| `artifactory.internalPortReplicator` | Replicator service internal port | `6061`   |
Could you fix the alignment of the table?

2018-05-25 09:46 UTC, unguiculus commented
/ok-to-test

2018-05-29 18:11 UTC, jainishshah17 commented on stable/artifactory/README.md
> +| `artifactory.internalPortReplicator` | Replicator service internal port | `6061`   |
@unguiculus done

2018-06-04 16:13 UTC, jainishshah17 commented
@unguiculus Can you take a look.

2018-06-07 18:27 UTC, jainishshah17 commented
@unguiculus This chart is ready.

2018-06-13 04:18 UTC, eldada commented
@unguiculus - can you give us a status on this?

2018-06-13 20:21 UTC, unguiculus commented
/lgtm

2018-06-13 20:24 UTC, unguiculus approved these changes

2018-06-13 20:31 UTC, merged