[stable/concourse] Add optional datadog metrics config
helm/charts pull request #5650
Opened 2018-05-18 22:59 UTC by wendorf

**What this PR does / why we need it**:
Concourse 3.13.0 adds support for exporting metrics to Datadog (see concourse/atc#269). This adds support for the new flags, and bumps the Concourse version.

2018-05-18 23:00 UTC, wendorf commented
/assign @william-tran

2018-05-24 18:56 UTC, unguiculus requested changes

2018-05-24 18:56 UTC, unguiculus commented on stable/concourse/values.yaml
> +      agent_host: 127.0.0.1
Camel case, please.

2018-05-24 18:57 UTC, unguiculus commented
/assign

2018-05-24 20:06 UTC, wendorf commented
Thanks for the feedback, @unguiculus . I fixed the key names, and made a couple other changes:

* Values are used to define environment variables, which are then used to set command flags. This brings the config more in line with other parameters.
* Add `web.metrics.datadog.agentHostUseHostIP` to set agent host IP to the underlying node's IP

2018-05-25 11:05 UTC, unguiculus commented
cc @frodenas @viglesiasce @william-tran @nexeck

2018-05-25 11:05 UTC, unguiculus approved these changes

2018-05-25 12:33 UTC, william-tran commented
@wendorf if upgrading to 3.13, this also needs the changes in https://github.com/kubernetes/charts/pull/5153, would you be willing to incorporate those changes in to this PR?

2018-05-25 14:43 UTC, wendorf commented
Certainly. I'm a bit confused about the need to do so, though. When I was
first working on it, I was expecting to need to open 7799, but saw that my
test deployment was operating fine, and also saw nothing in the logs
indicating a problem. We're now using this PR in our production instance
with no problems.

So it's kinda spooky. I don't mind opening the port, but I'd like to
understand why it's working fine for us if it's actually required. I don't
want to hold up the merging of this PR, so I can just add it, but I'd love
a second pair of eyes on this confusion.

On Fri, May 25, 2018, 5:33 AM Will Tran <notifications@github.com> wrote:

> @wendorf <https://github.com/wendorf> if upgrading to 3.13, this also
> needs the changes in #5153
> <https://github.com/kubernetes/charts/pull/5153>, would you be willing to
> incorporate those changes in to this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/charts/pull/5650#issuecomment-392044016>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAY3LhlH1mvzNLVzsT-iSr9gq7tfGZgqks5t1_oTgaJpZM4UFdFQ>
> .
>

2018-05-29 20:43 UTC, william-tran commented
@wendorf yeah that certainly is weird. I'm gonna /ok-to-test for now and see what happens while I do some testing on my end. I'd really like to get to 3.13.0 as well.

2018-05-29 21:29 UTC, william-tran commented
/ok-to-test

2018-05-30 14:42 UTC, william-tran commented
@wendorf So it looks like you don't need to specify a port for it to be reachable from within the network: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#container-v1-core
> `ports` List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network.

2018-05-30 14:46 UTC, wendorf commented
Okay, that doesn't match the internal model I had. Thanks for investigating! I'll add the port to the service for completeness/explicitness. Would you also like me to add the other flags in #5153 then, or would you prefer to have that PR rebased on this once it gets merged?

2018-05-30 14:49 UTC, william-tran approved these changes

2018-05-30 14:49 UTC, william-tran commented
/lgtm

2018-05-30 14:55 UTC, william-tran commented
@wendorf I'm going to make some updates to #5153 which will add the rest. Thanks!

2018-05-30 14:57 UTC, merged