Split readiness and liveness probes
helm/charts pull request #5704
Opened 2018-05-23 13:31 UTC by mnuttall

**What this PR does / why we need it**: ReadinessProbe and LivenessProbe times were set to the same period. This PR splits the two into separate values. We need readiness to be shorter than liveness to ensure that Jenkins starts reliably without being repeatedly killed in our environment. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-05-25 09:22 UTC, unguiculus requested changes
Please bump the minor version.

2018-05-25 09:22 UTC, unguiculus commented on stable/jenkins/values.yaml
> +  HealthProbesTimeout: 90
For consistency, you should rename `HealthProbesTimeout` to `HealthProbesLivenessTimeout`.

2018-06-08 11:13 UTC, mnuttall commented
@unguiculus sorry for the delay - changes pushed.

2018-06-13 19:07 UTC, unguiculus approved these changes

2018-06-13 19:07 UTC, unguiculus commented
/ok-to-test

2018-06-13 19:24 UTC, unguiculus commented
/lgtm

2018-06-13 19:33 UTC, merged