fix cmd for grafana admin password
helm/charts pull request #571
Opened 2017-02-07 00:16 UTC by vise890

2017-02-08 06:35 UTC, sameersbn requested changes

2017-02-08 06:35 UTC, sameersbn commented on stable/grafana/Chart.yaml
> +version: 0.2.2
@vise890 IMO, the changeset does not warrant a chart version

2017-02-08 06:35 UTC, sameersbn commented on stable/grafana/templates/NOTES.txt
> +   kubectl get secret --namespace {{ .Release.Namespace }} {{ template "server.fullname" . }} -o jsonpath="{.data.grafana-admin-password}" | base64 --decode ; echo
Is there an issue that this change resolves?

2017-02-08 11:08 UTC, vise890 commented
It's related to issue #366. This works for me in 1.5 but I haven't tried it with 1.4.

The version bump was requested in #516 by @prydonius .

2017-02-08 11:45 UTC, sameersbn commented
> It's related to issue #366. This works for me in 1.5 but I haven't tried it with 1.4.

I think that particular change was handled in #445. This PR simply drops the `printf` wrapper, don't think it's worthy of a version bump.

@prydonius thoughts?

2017-02-08 11:52 UTC, vise890 commented
oh right. I didn't realise it had been merged when i rebased. then yes, this just drops the printf wrapper.

2017-02-09 07:19 UTC, sameersbn commented
i think we can close this pr without a merge, wdyt?

2017-02-12 17:55 UTC, mgoodness commented
@k8s-bot ok to test

2017-02-12 18:05 UTC, mgoodness commented
@sameersbn @vise890 I'm inclined to merge this change. The command is simpler without the `printf` wrapper, and lines up with (at least most of) the other charts.

Agree that the version doesn't strictly need a bump, though I'm not opposed to one either.

2017-02-12 20:17 UTC, vise890 commented
ok, removed the version bump

2017-02-13 06:13 UTC, sameersbn commented
lgtm :+1:

2017-02-13 15:09 UTC, mgoodness commented
/lgtm

2017-02-13 16:53 UTC, merged