stable/memcached: Add support for metrics
helm/charts pull request #5782
Opened 2018-05-26 16:28 UTC by olemarkus

**What this PR does / why we need it**:

This pull request adds memcached_exporter as a sidecar container to the memcached pod.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-05-26 16:29 UTC, olemarkus commented
/assign @linki

2018-07-12 10:35 UTC, olemarkus commented
Ping @gtaylor

2018-07-26 18:20 UTC, paulczar requested changes
Please bump the chart version and address the inline comments.

2018-07-26 18:20 UTC, paulczar commented on stable/memcached/templates/statefulset.yaml
> +{{ toYaml .Values.metrics.resources | indent 10 }}
add `metrics.resources` to the README values table.

2018-07-26 18:20 UTC, paulczar commented on stable/memcached/values.yaml
> +  image: quay.io/prometheus/memcached-exporter:v0.4.1
please add to README values table.

2018-07-26 18:21 UTC, paulczar commented
/ok-to-test

2018-07-26 20:28 UTC, closed without merging