[incubator/fluentd-elasticsearch] Extended Readme and added OWNERS file
helm/charts pull request #5785
Opened 2018-05-27 12:10 UTC by monotek

**What this PR does / why we need it**:
Extended Readme and added OWNERS file

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-05-28 07:20 UTC, monotek commented
/assign @unguiculus

2018-05-28 08:25 UTC, timstoop requested changes

2018-05-28 08:25 UTC, timstoop commented on incubator/fluentd-elasticsearch/README.md
> +Its meant to be a drop in replacement for fluentd-gcp on GKE which sends logs to Googles Stackdriver service but can be also used anywhere else where Elasticsearch logbackend is needed.
"It's mean to be" (as it's shorthand for "it is")
"... Google's Stackdriver service, but can also be used in other places where logging to ElasticSearch is required." (sounds better to me)

2018-05-28 08:25 UTC, timstoop commented on incubator/fluentd-elasticsearch/README.md
> +The used Docker image also contains Googles detect exeptions (for Java multiline stacktraces), Prometheus exporter, Kubernetes metadata filter & Systemd plugins.
"Google's detect exceptions" (add the apostrophe and the c)

2018-05-28 19:43 UTC, monotek commented on incubator/fluentd-elasticsearch/README.md
> +Its meant to be a drop in replacement for fluentd-gcp on GKE which sends logs to Googles Stackdriver service but can be also used anywhere else where Elasticsearch logbackend is needed.
done

2018-05-28 19:43 UTC, monotek commented on incubator/fluentd-elasticsearch/README.md
> +The used Docker image also contains Googles detect exeptions (for Java multiline stacktraces), Prometheus exporter, Kubernetes metadata filter & Systemd plugins.
done

2018-05-28 19:46 UTC, timstoop commented
/ok-to-test

2018-06-06 10:03 UTC, timstoop commented
/lgtm

2018-06-06 16:24 UTC, unguiculus commented
/lgtm

2018-06-06 16:29 UTC, merged