[stable/sonarqube] Add MySQL database support to Sonarqube
helm/charts pull request #5803
Opened 2018-05-29 09:27 UTC by irajdeep

**What this PR does / why we need it**:
This PR adds `MySQL` database support to Sonarqube. Currently Sonarqube has only`Postgresql` support to store the data. It has the relevant changes to the template files and README.md for the new MySQL database support

**Which issue this PR fixes** *
fixes #5654 

**Special notes for your reviewer**:
`/assign`  @rjkernick

2018-05-29 12:24 UTC, rjkernick requested changes

2018-05-29 12:24 UTC, rjkernick commented on stable/sonarqube/Chart.yaml
> +version: 0.6.1
Please bump the minor version since this adds a new feature

2018-05-29 12:24 UTC, rjkernick commented on stable/sonarqube/templates/secret.yaml
> +  postgres-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
Key should be mysql-password

2018-05-29 12:24 UTC, rjkernick commented on stable/sonarqube/templates/secret.yaml
> +{{- if eq .Values.mysql.enabled false -}}
We also only need this if the database type is mysql. Same with the postgres secret above only is needed is database is postgres and postgres is disabled.

2018-05-29 12:32 UTC, irajdeep commented on stable/sonarqube/templates/secret.yaml
> +  postgres-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
Ah my bad , this is a blunder . Sorry

2018-05-29 13:24 UTC, irajdeep commented on stable/sonarqube/Chart.yaml
> +version: 0.6.1
Fixed

2018-05-29 13:25 UTC, irajdeep commented on stable/sonarqube/templates/secret.yaml
> +{{- if eq .Values.mysql.enabled false -}}
Added the check , thanks for pointing out

2018-05-29 13:25 UTC, irajdeep commented on stable/sonarqube/templates/secret.yaml
> +  postgres-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
Fixed

2018-05-29 14:01 UTC, rjkernick commented
/ok-to-test

2018-05-29 14:02 UTC, rjkernick commented
I am going to try and test out the different combinations this afternoon before I merge it. Thanks for the quick turnaround on the changes!

2018-05-29 14:03 UTC, irajdeep commented
Sure, let me know if you find any issues . Thanks !!

2018-05-29 18:54 UTC, rjkernick commented
/assign

2018-05-30 05:57 UTC, irajdeep commented
@rjkernick Can we go ahead with merging .

2018-05-31 19:49 UTC, rjkernick commented
/lgtm

2018-05-31 19:55 UTC, merged

2019-08-14 07:49 UTC, runzexia commented
In the sonarqube 7.1 version, mysql support was `Deprecated`. Do we need to roll back these changes?
https://docs.sonarqube.org/display/SONARqube71/Release+7.1+Upgrade+Notes