Adding the possibility to pull the image from a private repository
helm/charts pull request #5811
Opened 2018-05-29 15:16 UTC by grebois

Adding the possibility to pull the image from a private repository, very useful when using the sentry:onbuild docker image.

2018-05-29 15:16 UTC, grebois commented
/assign @prydonius

2018-05-30 07:03 UTC, grebois commented
/ok-to-test

2018-06-04 13:54 UTC, grebois commented
@rothgar could you take a look at this?

2018-06-05 06:04 UTC, rothgar commented on stable/sentry/values.yaml
>    tag: "8.20"
Please bump the default tag to 8.22 to match the chart yaml

2018-06-05 06:49 UTC, rothgar commented
This setting also needs to be applied to the db-init and create-user jobs that are run during install. The same base image is applied to each of those jobs but the secret isn't being used so image pulls are failing when I try to use this setting with a private image.

![image](https://user-images.githubusercontent.com/371796/40959554-d6aadcc6-6851-11e8-83ab-260148e2c4ac.png)

2018-06-05 12:53 UTC, grebois commented
@rothgar tested locally and looks good now, didn't notice that before, sorry.

2018-06-05 16:21 UTC, rothgar commented
No need to apologize. This is why we test.

The db-init and user-create jobs need the secret too
https://github.com/kubernetes/charts/blob/master/stable/sentry/templates/hooks/db-init.job.yaml#L27
https://github.com/kubernetes/charts/blob/master/stable/sentry/templates/hooks/user-create.job.yaml#L26

2018-06-07 05:31 UTC, rothgar commented
/ok-to-test

2018-06-07 11:32 UTC, grebois commented
thanks @rothgar, are you able to approve this as well or only @prydonius ?

2018-06-12 08:58 UTC, grebois commented
/assign @rothgar

2018-06-12 13:21 UTC, rothgar commented
I'm not an owner so I can't approve but it /lgtm

/meow

2018-06-17 19:25 UTC, unguiculus requested changes
Please follow this example:

https://github.com/kubernetes/charts/blob/bc178b63c7df469f1bbccd86629f8cb573a32292/stable/nginx-ingress/templates/default-backend-deployment.yaml#L29-L32

https://github.com/kubernetes/charts/blob/bc178b63c7df469f1bbccd86629f8cb573a32292/stable/nginx-ingress/values.yaml#L341-L342

2018-06-17 19:25 UTC, unguiculus commented
/assign

2018-06-18 16:40 UTC, unguiculus requested changes

2018-06-18 16:40 UTC, unguiculus commented on stable/sentry/values.yaml
> +  #  name:
# - name:

2018-06-18 18:14 UTC, unguiculus commented on stable/sentry/values.yaml
> +  #  name:
Just fixed it myself.

2018-06-18 18:14 UTC, unguiculus approved these changes

2018-06-18 18:17 UTC, unguiculus commented
You need to merge in master to make CI happy.

2018-06-18 19:07 UTC, grebois commented
@unguiculus merged

2018-06-24 14:01 UTC, unguiculus commented
/lgtm

2018-06-24 14:08 UTC, merged