[incubator/kube-spot-termination-notice-handler] Add Support for Tolerations
helm/charts pull request #5813
Opened 2018-05-29 16:23 UTC by stevenpall

**What this PR does / why we need it:**
- Add tolerations section to daemonset template
- Add tolerations section to values file (with example configs)

**Which issue this PR fixes** (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged):
- N/A

**Special notes for your reviewer:**
- N/A

2018-05-29 16:30 UTC, stevenpall commented
/assign @sameersbn

2018-07-01 19:43 UTC, unguiculus requested changes

2018-07-01 19:43 UTC, unguiculus commented on incubator/kube-spot-termination-notice-handler/templates/daemonset.yaml
> +{{- end }}
Please change as follows:

```yaml
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}

2018-07-01 19:43 UTC, unguiculus commented on incubator/kube-spot-termination-notice-handler/values.yaml
> +tolerations: {}
`tolerations: []`

2018-07-01 19:43 UTC, unguiculus commented on incubator/kube-spot-termination-notice-handler/Chart.yaml
> +version: 0.2.2
Bump minor version for a new feature.

2018-07-01 19:43 UTC, unguiculus commented
/assign

2018-07-03 16:33 UTC, stevenpall commented
@unguiculus Let me know if that looks good now!

2018-07-15 15:30 UTC, unguiculus approved these changes

2018-07-15 15:30 UTC, unguiculus commented
/ok-to-test

2018-07-15 15:41 UTC, unguiculus commented
/lgtm

2018-07-15 15:41 UTC, merged