[stable/minio] Use variable for kubernetes cluster name
helm/charts pull request #5867
Opened 2018-06-01 09:54 UTC by minhdanh

**What this PR does / why we need it**: This PR adds a variable for kubernetes cluster name, instead of always using `cluster.local`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #5797 

**Special notes for your reviewer**:

2018-06-01 09:57 UTC, minhdanh commented
/assign @prydonius

2018-06-01 14:05 UTC, mattjmcnaughton commented
Hi @minhdanh - thanks for the pr!

Do you mind sharing a little more about your motivation to use a cluster name other than `cluster.local`? From a quick search of charts, I think almost all assume `cluster.local` as the cluster name. And to be honest, I'm not sure if certain kubernetes internals assume `cluster.local`.

So while I think this change will technically work, I wonder if its a tricky precedent to introduce into helm charts.

Would love to hear your thoughts :)

2018-06-01 14:21 UTC, tompizmor commented
I would also document this new value in the [configuration table](https://github.com/kubernetes/charts/tree/master/stable/minio#configuration) in the README.

2018-06-01 14:35 UTC, sznmaran commented
/assign @prydonius

2018-06-01 16:38 UTC, prydonius reviewed
lgtm in general, small comments

as @tompizmor suggested please also add the option to the README

2018-06-01 16:38 UTC, prydonius commented on stable/minio/values.yaml
> +kubernetes_cluster_name: cluster.local
convention is to user lowerCamelCase

2018-06-01 16:38 UTC, prydonius commented on stable/minio/Chart.yaml
> +version: 1.3.4
this can be 1.4.0 as this is a backwards-compatible feature not a bug fix!

2018-06-07 10:11 UTC, minhdanh commented
@prydonius I've just added some changes. Please see if they're good.

2018-06-20 17:20 UTC, verwilst commented
Why even include the cluster name? resolv.conf is usually set up to allow <service>.<namespace> or <service>.<namespace>.svc to be resolvable.

2018-06-20 17:22 UTC, verwilst commented
# ping minio-0.minio.minio.svc.cluster.local
ping: bad address 'minio-0.minio.minio.svc.cluster.local'
# ping minio-0.minio.minio.svc
PING minio-0.minio.minio.svc (10.231.65.141): 56 data bytes
64 bytes from 10.231.65.141: seq=0 ttl=64 time=0.026 ms

2018-07-02 19:37 UTC, unguiculus requested changes

2018-07-02 19:37 UTC, unguiculus commented on stable/minio/values.yaml
> +kubernetesClusterName: cluster.local
I think `clusterDomain` would be a better name.

2018-07-02 19:37 UTC, unguiculus commented
/assign

2018-08-24 18:15 UTC, closed without merging