add containers and init containers for drone
helm/charts pull request #5896
Opened 2018-06-04 14:44 UTC by magicalbanana

**What this PR does / why we need it**:
When running Elasticsearch when deploying a drone chart causing a `vm.max_map_count` error. There should be a way to modify that config value when initializing the containers/pods.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # N/A

**Special notes for your reviewer**:
This is my first contribution to this repository.

2018-06-04 16:35 UTC, magicalbanana commented
/assign @foxish

2018-06-05 18:46 UTC, christian-roggia requested changes
Can you also better explain why is "initContainers" required and how it can be useful to the community?

Thank you for your contribution!

2018-06-05 18:46 UTC, christian-roggia commented on incubator/drone/templates/deployment-agent.yaml
> +{{ toYaml .Values.agent.initCcontainers | indent 8 }}
There is a typo in "initCcontainers".

2018-06-05 18:46 UTC, christian-roggia commented on incubator/drone/templates/deployment-server.yaml
> +{{ toYaml .Values.agent.initCcontainers | indent 8 }}
Same typo here.

2018-06-05 18:47 UTC, christian-roggia commented
This new value should also be added to values.yaml and to the README file.

2018-06-09 16:26 UTC, neumachen commented
@christian-roggia thanks for looking it at. I'll address your comments shortly.

2018-06-09 16:27 UTC, magicalbanana commented
@christian-roggia so the reason I'm adding init containers is so that we can configure certain things that may be needed for an image that's needed for the CI. 

Example, `elastcisearch` requires that we set `vm.max_map_count`. Without it, `elasticsearch` wouldn't run.

2018-06-09 16:31 UTC, magicalbanana commented
@christian-roggia addressed your comments sir.

2018-06-12 19:29 UTC, christian-roggia commented
Please update this PR so that it points to **stable/drone** instead of **incubator/drone**.

2018-06-12 20:34 UTC, magicalbanana commented
@christian-roggia done.

2018-06-12 20:41 UTC, christian-roggia commented
If it's easier for you, you can close this PR and open a new one, otherwise you will have to squash the commits because there are too many.

2018-06-12 20:42 UTC, magicalbanana commented
@christian-roggia I'll just squash them.

2018-06-17 19:30 UTC, unguiculus requested changes
Please rename to `extraInitContainers` to be consistent with other charts and bump the minor version for a new feature.

2018-06-17 19:31 UTC, unguiculus commented
@christian-roggia There's no need to squash commits. They will be squashed when merged anyways. In fact, rebasing makes reviews harder because Github won't be able to show changes.

2018-06-17 19:32 UTC, unguiculus commented
/assign

2018-06-17 19:58 UTC, christian-roggia commented
@unguiculus I requested the squashing of the commits because there were 10+ commits due to the migration from incubator/drone to stable/drone creating a high amount of noise in the history of the PR. I will keep in mind for the next PRs your advice.

2018-06-29 08:08 UTC, christian-roggia commented
Please solve the conflicts.

2018-08-24 18:15 UTC, closed without merging