[stable/kibana] Support custom labels on Service
helm/charts pull request #5901
Opened 2018-06-04 18:57 UTC by NicolasT

In line with various other charts, allow to set custom labels on the rendered `Service` object by setting values.

2018-06-04 18:58 UTC, NicolasT commented
CC @compleatang

2018-06-04 19:03 UTC, NicolasT commented
CLA has been signed, I believe.

2018-06-04 19:25 UTC, NicolasT commented
CC @JessicaGreben 
/assign @viglesiasce

2018-06-04 19:57 UTC, compleatang requested changes

2018-06-04 19:57 UTC, compleatang commented on stable/kibana/templates/service.yaml
> +    {{- range $key, $value := .Values.service.labels }}
in keeping with helm defaults, can you outdent this line and the `{{- end }} line two spaces please? in general this makes the chart more readable.

2018-06-04 19:58 UTC, compleatang commented
@NicolasT I added one minor change request. Also, can you please add a line in the README so that folks understand the functionality exists without having to parse the values.yaml file? 

Thanks!

2018-06-05 09:51 UTC, compleatang commented
LGTM

2018-06-08 07:30 UTC, NicolasT commented
Anything I can do to make this move forward?

2018-06-17 13:31 UTC, unguiculus commented
/ok-to-test

2018-06-17 13:34 UTC, unguiculus commented
Your branch is outdated. You need to merge in the current master so CI works.

2018-07-15 19:04 UTC, unguiculus commented
/lgtm

2018-07-15 19:07 UTC, merged