[incubator/sentry-kubernetes] Add release/environment values
helm/charts pull request #5952
Opened 2018-06-05 17:14 UTC by hobochild

This allows you to customize settings here: https://github.com/getsentry/sentry-kubernetes/blob/master/sentry-kubernetes.py#L27-#L28

**What this PR does / why we need it**:
This add environment variable configurations for the sentry-kubernetes docker image. This allows you to customize settings here: https://github.com/getsentry/sentry-kubernetes/blob/master/sentry-kubernetes.py#L27-#L28

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-06-05 17:25 UTC, gianrubio commented on incubator/sentry-kubernetes/templates/deployment.yaml
> +            value: {{ .Values.sentry.release }}
wdyt to use the [k8s metadata](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-container-fields-as-values-for-environment-variables) information to fill this value?

ex:
```
        - name: RELEASE
          valueFrom:
            resourceFieldRef:
              containerName: {{ .Chart.Name }}
              resource: image
```

2018-06-05 17:53 UTC, hobochild commented on incubator/sentry-kubernetes/templates/deployment.yaml
> +            value: {{ .Values.sentry.release }}
Ah, good point!

2018-06-05 17:58 UTC, gianrubio requested changes
please align the table

2018-06-07 18:03 UTC, hobochild commented
Hey @gianrubio let me know if you'd like me to squash the commits or do anything further. 

Thanks for the review!

2018-06-07 18:35 UTC, gianrubio commented
/ok-to-test
/lgtm

2018-06-07 18:38 UTC, merged

2018-06-10 08:19 UTC, robdefeo commented
I tried to run this change and got an error when deploying with helm ```Error: release sentry-kubernetes failed: Deployment.apps "sentry-kubernetes" is invalid: spec.template.spec.containers[0].env[2].valueFrom.resourceFieldRef.resource: Unsupported value: "image": supported values: "limits.cpu", "limits.ephemeral-storage", "limits.memory", "requests.cpu", "requests.ephemeral-storage", "requests.memory"``` What version on kubernetes does this need to run on? I am running `"v1.9.6"` but I cant find anything about this in the docs

2018-06-10 08:44 UTC, hobochild commented
Hey @robdefeo, yea the release value was added to the or with out proper testing, there is a PR to revert the change (#6002).

2018-06-10 15:28 UTC, robdefeo commented
@hobochild Perfect, thanks for the information, I'll watch that PR