[incubator/vault] Add ability to define side containers
helm/charts pull request #5974
Opened 2018-06-06 19:46 UTC by jbialy

**What this PR does / why we need it**:

This PR enables the addition of sidecar containers to the vault pod. A use for a sidecar container could include an `unsealer`, where any unseal logic can be done in a separate container that lives outside of the official vault image. This allows for separation of concerns where tasks that don't necessarily belong in the vault container could live along side in the same pod and share the same network layer.

2018-06-06 19:47 UTC, jbialy commented
/assign @viglesiasce

2018-06-06 19:48 UTC, jbialy commented
/assign @unguiculus

2018-06-06 19:50 UTC, jbialy commented
/assign

2018-06-06 19:54 UTC, jbialy commented
/assign @seanknox

2018-06-06 19:54 UTC, jbialy commented
/assign @mattfarina

2018-06-08 07:03 UTC, unguiculus requested changes
Please make this more flexible and change the naming to `extraContainers`, `extraSecrets`, etc. don't put. See e. g. https://github.com/kubernetes/charts/tree/master/stable/keycloak or https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress how this kind of stuff should be implemented.

2018-06-08 07:04 UTC, unguiculus commented
cc @jpds

2018-06-08 15:45 UTC, jbialy commented
@unguiculus I see how the naming scheme and keeping `extraContainers` more flexible (allowing more than one container) makes sense. I was originally thinking of taking this route.

Looking how the `customSecrets` are currently defined:
https://github.com/kubernetes/charts/blob/0e79b3de568dab9fcab0eb5d38ecc94b27a9afc3/incubator/vault/values.yaml#L109-L111

Wouldn't it make sense to change that to `extraVolumeMounts` instead? Secrets in this context are nothing more but extra `.spec.containers.volumeMounts`?

2018-06-11 19:52 UTC, unguiculus approved these changes

2018-06-11 19:52 UTC, unguiculus commented
/ok-to-test

2018-06-11 20:04 UTC, unguiculus commented
/lgtm

2018-06-11 20:08 UTC, merged