Added Cpu and Memory limit for master jenkins server
helm/charts pull request #5978
Opened 2018-06-07 07:11 UTC by oguzy

CPU and Mem request values are updated. With low values,
Jenkins is not able to up and running

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-06-08 19:40 UTC, oguzy commented
Signed the CLA.

2018-06-08 19:42 UTC, oguzy commented
/assign @viglesiasce

2018-06-17 15:55 UTC, unguiculus requested changes

2018-06-17 15:55 UTC, unguiculus commented on stable/jenkins/values.yaml
> +  MemoryLimit: "2048Mi"
Our best practice is to not specify defaults for resources at all. It should be possible to install and test charts on clusters with little resources, such as Minikube.

2018-07-31 17:52 UTC, viglesiasce commented
Agree that we will not set the limit by default. Can you change this to add the limit but not set it in the Values file?

2018-09-13 19:14 UTC, closed without merging