Missing chart in helm install statement
helm/charts pull request #598
Opened 2017-02-07 16:31 UTC by VDuda

Usage: (v2.1.3)
  helm install [CHART] [flags]

* Include chart in install statement
* Fix set flag to use strings as required

2017-02-07 16:42 UTC, VDuda commented
I signed it!

2017-02-08 02:51 UTC, mgoodness requested changes

2017-02-08 02:51 UTC, mgoodness commented on stable/kube2iam/README.md
> +    host.iptables=true,host.interface=cbr0"
Even this doesn't work correctly. Let's just trim it down to:
```console
$ helm install stable/kube2iam --name my-release \
  --set=extraArgs.base-role-arn=arn:aws:iam::0123456789:role/,host.iptables=true,host.interface=cbr0
```

2017-02-08 02:57 UTC, VDuda commented on stable/kube2iam/README.md
> +    host.iptables=true,host.interface=cbr0"
It worked on my end - at least when I checked by running an AWS s3 call through a test container. Will apply the change, should def be trimmed down. 👍

2017-02-08 03:22 UTC, mgoodness approved these changes

2017-02-08 15:53 UTC, mgoodness commented
Nit/request: would you mind also changing line 68 so the chart name is listed before the arguments? Consistency FTW.

2017-02-08 18:21 UTC, mgoodness commented
@k8s-bot ok to test

2017-02-09 17:27 UTC, merged