Add initial helm chart for graylog
helm/charts pull request #6006
Opened 2018-06-08 18:17 UTC by bjaworski3

**What this PR does / why we need it**: Adds Helm chart for graylog

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-06-08 18:59 UTC, alexander-alvarez commented
@edmundoa can someone in your org take a look at this?

2018-06-11 10:26 UTC, bernd commented
@alexander-alvarez I can take a look over the next days.

2018-06-17 15:57 UTC, unguiculus commented
Please compare with what you get from `helm create` using Helm 2.8+ and update accordingly.

2018-06-25 14:53 UTC, bjaworski3 commented
@unguiculus I did my tests with the chart on 2.9.1, did you want me to test it pre 2.8?

2018-08-12 18:53 UTC, davidkarlsen commented
@bjaworski3 Still want this merged? I suggest going straight for stable and not via incubating

2018-08-13 15:50 UTC, bjaworski3 commented
@davidkarlsen Yeah it would still be good to get this merged. I can move it over to the stable folder

2018-08-13 21:34 UTC, davidkarlsen requested changes

2018-08-13 21:34 UTC, davidkarlsen commented on stable/graylog/README.md
> +$ helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
still references incubator - also in other places

2018-08-13 21:34 UTC, davidkarlsen commented on stable/graylog/README.md
> +$ helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
also see linting errors for whitespaces

2018-09-29 17:03 UTC, closed without merging

2018-10-18 12:13 UTC, billimek commented
@bjaworski3 did you give up on this one?  If so I'll pick it up as I'd really like to see a graylog chart.

2018-10-18 14:57 UTC, billimek commented
@bjaworski3 good question - I know some PRs take a long time to get movement, let's try to get this one across the finish-line!  Can you post a comment with `/reopen` ?  I think that should instruct the bot to reopen it - I'll try but I think that author needs to do it.

/reopen

2018-10-18 15:00 UTC, bjaworski3 commented
/reopen

2018-10-18 15:06 UTC, billimek commented
@davidkarlsen or @unguiculus or @bernd is it possible to get this PR `/reopen`ed to (hopefully) complete the path to getting this merged?

2018-10-22 17:00 UTC, billimek commented
@bjaworski3 any chance you can submit this as a new PR?  I don't think we're having any luck getting anyone to reopen this.  I asked in the #charts channel and the response was to create a new PR instead of re-opening this one.  It doesn't make a lot of sense to me in that all of the history will be split across multiple PRs but maybe that's the only way to get some progress on this.