[stable/prometheus-postgres-exporter] add support for Google Cloud SQL
helm/charts pull request #6009
Opened 2018-06-08 21:47 UTC by mikeraimondi

Cloud SQL, Google's managed database product, requires use of an authentication
proxy when accessed from dynamic IPs. To limit access to the proxy, it is
recommended to use a sidecar.
More info: https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine

Cloud SQL, like other managed databases, does not allow use of
superuser accounts. Therefore, add support for a configurable
database in `datasource`.
More info: https://github.com/wrouesnel/postgres_exporter#running-as-non-superuser

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-06-08 21:56 UTC, mikeraimondi commented
/assign @lachie83

2018-06-12 17:04 UTC, mikeraimondi commented
/assign @gianrubio

2018-06-15 14:16 UTC, gianrubio commented on stable/prometheus-postgres-exporter/templates/deployment.yaml
> +    {{- if .Values.cloudSQL.enabled  }}
I'd rather add an `extraContainer` here so it'll be easier to other users customise it.
Take a look on this [example](https://github.com/kubernetes/charts/blob/24e6370f09a3fbca58f2e761e7fba3fa2e702ec3/stable/elastabot/templates/deployment.yaml#L39)

2018-06-15 14:17 UTC, gianrubio commented on stable/prometheus-postgres-exporter/templates/deployment.yaml
> +    {{- if .Values.cloudSQL.enabled  }}
same here, add `extraConfigmap:`

ex:
```
extraConfigmap: 
  - name: cloudsql-instance-credentials
    secret:
      secretName: my-secret-name
```

2018-06-15 14:18 UTC, gianrubio requested changes
pleas read my comments

2018-06-17 20:29 UTC, unguiculus commented
I agree with @gianrubio. Have a look at the Keycloak chart for reference. The readme documents how to the proxy.

https://github.com/kubernetes/charts/tree/master/stable/keycloak

2018-06-17 20:29 UTC, unguiculus commented
/assign

2018-06-18 19:12 UTC, mikeraimondi commented
@gianrubio @unguiculus great feedback, wasn't aware of the `extraContainers` pattern. Made the change, let me know how it looks.

2018-06-19 10:20 UTC, gianrubio commented
/ok-to-test
/lgtm

2018-06-24 14:14 UTC, unguiculus commented
/lgtm

2018-06-24 14:20 UTC, merged