[stable/coredns] Make CoreDNS chart more configurable
helm/charts pull request #6073
Opened 2018-06-12 09:55 UTC by andor44

**What this PR does / why we need it**:
Makes CoreDNS more configurable. Currently, the chart defines a single server block with a fixed zone, and a fixed set of plugins. Now you can define as many server zones as you want, with any number of zones and plugins.

**Special notes for your reviewer**:
This flexibility of course comes at a tradeoff. The chart is not as hands-off anymore, as the plugins aren't known beforehand. That being said, the supplied `values.yaml` produces an almost-identical default `Corefile`, the only difference being that I didn't hardcode the reverse zone for the k8s plugin.
Additionally, I made the chart "smart" by making it automatically derive the ports for the service and the containers based on the server blocks and zones defined. The caveat is that I tried passing an extra argument to my template helpers to determine whether it's templating the service (use key `port`) or the container (use key `containerPort`), but this did not work for reasons described on Slack, to which I didn't receive any answers. Therefore the template helper is essentially repeated twice, with the only difference being a single line.

2018-08-08 17:01 UTC, unguiculus commented
cc @shashidharatd @Acaleph

2018-08-08 17:01 UTC, unguiculus commented
/assign

2018-08-08 17:01 UTC, unguiculus commented
/ok-to-test

2018-08-08 17:03 UTC, unguiculus commented
It'd be good to also update the chart to apply our current RBAC best practices (can be done in a separate PR).

https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md

2018-08-23 05:35 UTC, shashidharatd reviewed
@andor44, My Apologies. Somehow i missed the notifications.
This PR's approach of configuring plugin configuration is good given the complexity of configuration in CoreDNS.
Thanks for doing this!
Just a minor suggestion

2018-08-23 05:35 UTC, shashidharatd commented on stable/coredns/Chart.yaml
> +appVersion: 1.1.3
Update to 1.2, now that 1.2 is released. Also request to update the default image tag to 1.2 in Values.yaml

2018-08-23 09:30 UTC, andor44 commented
Rebased and bumped app version

2018-08-23 12:01 UTC, shashidharatd commented
/lgtm

2018-08-30 15:20 UTC, scottrigby requested changes

2018-08-30 15:20 UTC, scottrigby commented on stable/coredns/Chart.yaml
> +version: 0.10.0
Bump MAJOR version, since there are backwards-incompatible values & template file changes. See [semver spec item 8](https://semver.org/#spec-item-8).

2018-08-30 15:20 UTC, scottrigby commented on stable/coredns/templates/_helpers.tpl
> +{{- define "coredns.servicePorts" -}}
See [this Slack convo](https://kubernetes.slack.com/archives/C6E3XH1ED/p1535642358000100) about creating a follow-up issue and potential PR if this gets resolved in helm/helm.

2018-08-30 15:24 UTC, scottrigby commented on stable/coredns/Chart.yaml
> +version: 0.10.0
Note that even though this chart was in MAJOR version 0 (dev), this is in the charts stable repo, so it should have already been at least `1.0.0`. We're going to try to help the other charts with this too.

2018-08-30 15:37 UTC, andor44 commented on stable/coredns/templates/_helpers.tpl
> +{{- define "coredns.servicePorts" -}}
Opened helm/helm#4569

2018-08-30 16:00 UTC, scottrigby approved these changes

2018-08-30 16:01 UTC, scottrigby commented
/lgtm

2018-08-30 16:03 UTC, merged