Add a Chart for GitLab CI Runner
helm/charts pull request #608
Opened 2017-02-10 01:37 UTC by twk3

In order for this Chart to properly work, you need to specify the GitLab URL that you want to register the runner to. And the registration token, taken from the GitLab instance. (Either from the Shared Runners page for Admins, or any Project's CI/CD Pipelines settings)

2017-02-10 01:49 UTC, rothgar commented
Getting the token requires manual involvement from a user and `kubectl exec`ing into the gitlab pod. Is that correct?

Is there a way to export that token from the gitlab pod as a secret and consume the secret in the runner?

2017-02-10 05:11 UTC, sameersbn commented on stable/gitlab-runner/templates/deployment.yaml
> +          value: {{ default "" .Values.runners.namespace | quote }}
when not specified would it make sense to default to `Release.Namespace` instead?
ref: https://github.com/kubernetes/helm/blob/master/docs/charts.md#predefined-values

2017-02-12 18:43 UTC, kwiesmueller commented
Hey, tested this with k8s on GCE and am getting errors with docker builds.
Seams like it is not mounting the docker.sock or the privileged flag is not working.

Is this a mistake on our side or something intended?

2017-02-14 07:44 UTC, so0k commented
@rothgar - I tried to automate the token retrieval process here: https://github.com/honestbee/gitlab-infra#registering-multi-runner

2017-02-16 23:39 UTC, twk3 commented
@sameersbn thanks, I added that in

@kwiesmueller there was a bug in how I passed the privileged env variable. I updated it, and it should now be fixed. kube clusters that allow privileged should work with dind if you flag privileged to true now.

2017-02-17 15:50 UTC, kwiesmueller approved these changes
That fixed it on my side as well. Thanks.

2017-03-01 12:37 UTC, Dexyon commented
What can I do to help here? I just deployed the chart from a local clone and at first sight everything looks ok!

2017-03-16 15:58 UTC, prydonius requested changes
This is looking great, I just have a few comments.

2017-03-16 15:58 UTC, prydonius commented on stable/gitlab-runner/templates/NOTES.txt
> +{{- if default "" .Values.gitlabUrl }}
Why do you use `default` here?

2017-03-16 15:58 UTC, prydonius commented on stable/gitlab-runner/Chart.yaml
> +description: GitLab Runner
Can we improve the description and add an icon?

2017-03-23 17:36 UTC, kwiesmueller requested changes
Hey, there is a mismatch of the values in values.yaml and the template files.
The rest looks good, so far. Test instance is starting up.

2017-03-23 17:36 UTC, kwiesmueller commented on stable/gitlab-runner/values.yaml
> +# gitlabURL: http://gitlab.your-domain.com/
You got a not matching value here: gitlabURL in default values but gitlabUrl in all templates.
Just discovered this while testing.

2017-04-04 18:22 UTC, twk3 commented on stable/gitlab-runner/templates/NOTES.txt
> +{{- if default "" .Values.gitlabUrl }}
Copying what was used in the gitlab-ce chart. I've dropped them here now.

2017-04-04 18:22 UTC, twk3 commented on stable/gitlab-runner/Chart.yaml
> +description: GitLab Runner
Updated with better description and added icon

2017-04-04 18:23 UTC, twk3 commented on stable/gitlab-runner/values.yaml
> +# gitlabURL: http://gitlab.your-domain.com/
Thanks, fixed

2017-04-04 18:23 UTC, twk3 commented
@prydonius I've updated the chart with the requested changes

2017-04-04 18:39 UTC, kwiesmueller approved these changes

2017-04-24 17:37 UTC, twk3 commented
@prydonius are there any additional changes needed?

2017-04-25 09:17 UTC, lsjostro commented
@twk3 would be nice if you could enable the metrics server for the runner.

2017-04-25 09:32 UTC, rimusz commented
+1 for metrics

2017-05-10 10:05 UTC, rimusz commented
@twk3 also `readme` should really include how to get `runner Registration Token` for selfhosted/hosted gitlab
I have intensively tested it with gitlab-ce, have not find any issues

2017-05-10 12:45 UTC, kwiesmueller commented
Metrics would be nice to have, that's true...
We are using this chart in production for over 1 Month and got no issues. Everything is working great.

2017-05-10 14:16 UTC, rimusz commented
@kwiesmueller can you share the image you use for `kubernetes executors` via `runners.image:`?

2017-05-10 14:26 UTC, lsjostro commented
@rimusz @kwiesmueller this is my take on it:
https://gist.github.com/lsjostro/4dfbe304a5d105f686e57c98fbffb28b

2017-05-10 14:41 UTC, kwiesmueller commented
@rimusz the few builds currently running are using golang:1.8
The image set as default under runners.image is ubuntu:16.04 as it is not used anyways.

2017-05-25 22:02 UTC, mgoodness commented
At the risk of offending everyone who's worked on this so far, I have to ask: is there value in adding & maintaining this chart when GitLab has their own, supported one?

https://gitlab.com/charts/charts.gitlab.io/tree/master/charts/gitlab-runner

#justasking

2017-05-25 22:15 UTC, rothgar commented
Benefits of keeping this chart

- Possible to have different implementations (maybe not a benefit)
- Single repo to discover the chart from

Downsides

- Probably not going to have as many features or be supported
- Duplicating work
- Need to add a separate repo

I'm in favor or getting rid of this one and using the chart provided by gitlab. Similarly I'm in favor of using containers from any project that provides their own containers (e.g. postgres) over community built/maintained containers.

It makes discovery harder but reduces duplicate work and gets features and fixes out faster. On the flip side, if someone is running kubernetes and wants to deploy gitlab they may not know about helm+charts. If gitlab documents "Here's how to deploy gitlab on kubernetes with this chart" it may let more people discover helm and the work happening here.

2017-05-26 01:23 UTC, kwiesmueller commented
@mgoodness:
I didn't even know about the gitlab chart before I started working on my own one and then stumbled about this PR.
I would favor to keep it here, as it might help people looking for it in the official repos.  Also I can not see any special features that would make a good reason to stay with the "official" gitlab one.

2017-05-26 01:25 UTC, kwiesmueller commented
@rothgar:
I agree on the container part of your comment.
For various reasons we build all containers used in our clusters by ourselves as community managed containers tend to loose our trust by missing security updates etc.

2017-06-10 06:11 UTC, twk3 commented
A similar conversation regarding the gitlab repo charts is taking place in this issue: https://github.com/kubernetes/charts/issues/1138

2017-07-05 21:06 UTC, viglesiasce commented
@twk3 I also agree that we should lean on the officially supported chart. I don't think the duplicate work is worth the maintenance burden. 

We will be looking at how to delegate chart responsibility to other repositories soon and will update accordingly. 

Do you mind if we close this out until then?

2017-08-02 00:46 UTC, mgoodness commented
Closing in favor of the upstream chart. Feel free to re-open if/when it's decided otherwise.

2017-08-02 00:46 UTC, closed without merging