Adding helm test hooks for mongodb-replicaset
helm/charts pull request #609
Opened 2017-02-10 09:53 UTC by foxish

This is a proof of concept using [bats](https://github.com/sstephenson/bats) for testing mongodb.
It has 4 tests in use:

Test output looks like:

```
1..4
ok 1 Testing mongodb client is accessible
ok 2 Connect mongodb client to mongodb pods
ok 3 Write key to master
ok 4 Read key from slaves
```

/cc @michelleN @viglesiasce @erictune

2017-03-22 23:07 UTC, seanknox commented on incubator/mongodb-replicaset/templates/mongo-up-test.yaml
> +            echo {{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}-$1.{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}.default.svc.cluster.local
@foxish Can you bump the truncation limit to 63? Otherwise this looks good.

2017-04-07 20:10 UTC, viglesiasce requested changes
@foxish this LGTM but can you:

1) make all the tabs into spaces 😄 
2) rename anything that says "bat" to "bats" (ie bat_wrapper.sh)

I updated the truncation limit already per @seanknox

2017-04-07 20:11 UTC, viglesiasce commented
@foxish oh and i forgot to mention the merge conflict that also needs to be resolved.

2017-04-08 01:11 UTC, foxish commented
@viglesiasce Thanks for reviewing. Addressed comments. PTAL

2017-04-13 22:08 UTC, viglesiasce requested changes
(Writing down results from convo with @foxish)

1) Remove need for bats_wrapper by using configmap for test file
2) Remove need for inlining bash script in configmap file by using Files.Get like [in the Spinnaker chart](https://github.com/kubernetes/charts/blob/master/stable/spinnaker/templates/configmap/spinnaker-config.yaml#L8)

2017-04-13 22:08 UTC, viglesiasce commented on incubator/mongodb-replicaset/templates/mongo-up-test.yaml
> +      image: mongo:latest
This should match the image set in values

2017-04-18 22:36 UTC, foxish commented
@viglesiasce, Addressed review comments and switched over to using a configmap.

2017-04-18 22:44 UTC, viglesiasce requested changes

2017-04-18 22:44 UTC, viglesiasce commented on incubator/mongodb-replicaset/Dockerfile
> +FROM dduportal/bats:0.4.0
Since we don't need the wrapper anymore, we shouldn't need this Dockerfile.

2017-04-18 22:44 UTC, viglesiasce commented on incubator/mongodb-replicaset/templates/mongo-up-test.yaml
> +        "image": "foxish/bats:0.4",
use dduportal/bats:0.4.0

2017-04-18 22:59 UTC, foxish commented on incubator/mongodb-replicaset/Dockerfile
> +FROM dduportal/bats:0.4.0
Done. Thanks!

2017-04-18 23:00 UTC, foxish commented on incubator/mongodb-replicaset/templates/mongo-up-test.yaml
> +        "image": "foxish/bats:0.4",
Also switched from init-container beta annotation to the field.

2017-04-27 20:29 UTC, foxish commented
@k8s-bot e2e test this

2017-04-27 20:35 UTC, foxish commented
Just renamed files from incubator to stable/ because mongodb-replicaset itself has moved.

2017-04-27 20:42 UTC, foxish commented
@k8s-bot e2e test this

2017-04-27 20:53 UTC, foxish commented
Seeing odd test failures to do with the main chart although I haven't modified it. 
Could this be a flake? @viglesiasce

2017-05-04 02:48 UTC, foxish commented
@k8s-bot e2e test this

2017-05-04 03:11 UTC, merged