[incubator/kafka] Update to StatefulSet & Bumb zk dependecy
helm/charts pull request #612
Opened 2017-02-10 15:37 UTC by krallistic

Updated PetSet to StatefulSet.
Updated zookeeper chart version to newer 0.2.0 Version (contains affinity&pdb)

2017-02-13 22:42 UTC, mgoodness commented
@k8s-bot ok to test

2017-02-13 22:42 UTC, mgoodness commented
Addresses #630

2017-02-13 22:57 UTC, mgoodness requested changes
Incubator repo URL needs to be changed in `requirements.yaml`. Let's also use the latest Zookeeper chart.

2017-02-13 22:57 UTC, mgoodness commented on incubator/kafka/requirements.yaml
> +  version: 0.2.0
Latest version is 0.2.1

2017-02-13 22:57 UTC, mgoodness commented on incubator/kafka/requirements.yaml
>    repository: http://storage.googleapis.com/kubernetes-charts-incubator
Please update to new URL: `https://kubernetes-charts-incubator.storage.googleapis.com`, update your cache (`helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com`), then re-run `helm dep update incubator/kafka`

2017-02-15 16:54 UTC, krallistic commented
Changed

If i want to add struktural changes to the chart, should i open a second PR or use that one? (Also do i need a Issue? )

2017-03-14 14:28 UTC, prydonius commented
@krallistic it's up to you - you're welcome to make more changes in this PR, but it might be easier to merge this as is and iterate on it with successive PRs.

2017-03-14 14:29 UTC, prydonius commented
Waiting for @mgoodness to re-review. Can you bump the chart version?

2017-03-14 20:47 UTC, krallistic commented
Thanks for the information.

Sadly i couldnt find out why the test is failing, my guess is that its because the kafka pods are failing till zookeeper is finally up. Maybe a init container wich waits for zK would be a good idea.

2017-03-20 14:57 UTC, mgoodness approved these changes

2017-03-20 15:01 UTC, mgoodness commented
Changes look good, but we really should try to fix the failing test.

2017-05-10 20:06 UTC, viglesiasce commented
@k8s-bot e2e test this

2017-05-10 20:15 UTC, viglesiasce commented
This PR is actually creating a new file rather than updating the existing one. Please make your changes in the existing file templates/kafka-ss.yaml or move the file using git. 

As it stands this does not work. as the tests show.

2017-05-12 14:39 UTC, krallistic commented
Also fixed in https://github.com/kubernetes/charts/pull/989, closing this PR

2017-05-12 14:39 UTC, closed without merging