Add updateStrategy parameter for redis StatefulSet.
helm/charts pull request #6121
Opened 2018-06-14 21:04 UTC by qlikcoe

**What this PR does / why we need it**:
Implements updateStrategy parameter for `redis-master-statefulset`

**Special notes for your reviewer**:

2018-06-15 09:26 UTC, juan131 reviewed
Thanks for this contribution! I suggested you an improvement.

2018-06-15 09:26 UTC, juan131 commented on stable/redis/values-production.yaml
> +  statefulset:
I would add the ability to use partitions (in case someone wants to add more customisation):

```
## Update strategy, can be set to RollingUpdate or onDelete by default.
## https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets
statefulset:
## Partition update strategy
## https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions
# rollingUpdatePartition:
```

2018-06-15 09:26 UTC, juan131 commented on stable/redis/templates/redis-master-statefulset.yaml
> +    type: {{ .Values.master.statefulset.updateStrategy }}
I would add the ability to use partitions (in case someone wants to add more customisation):
```
updateStrategy:
  type: {{ .Values.master.statefulset.updateStrategy }}
  {{- if Values.master.statefulset.rollingUpdatePartition }}
  rollingUpdate: 
    partition: {{ Values.master.statefulset.rollingUpdatePartition }}
  {{- end }}
```

2018-06-15 09:26 UTC, juan131 commented on stable/redis/README.md
> +| `master.statefulset.updateStrategy`        | Update strategy for StatefulSet                                                                                | onDelete
I would add the ability to use partitions (in case someone wants to add more customisation)

2018-06-15 13:09 UTC, qlikcoe commented on stable/redis/values-production.yaml
> +  statefulset:
Good point! Done.

2018-06-18 09:45 UTC, juan131 approved these changes
Great! Thanks for adding it

2018-06-18 09:45 UTC, juan131 commented
/ok-to-test

2018-06-18 09:54 UTC, juan131 requested changes

2018-06-18 09:54 UTC, juan131 commented on stable/redis/values-production.yaml
> +    updateStrategy: onDelete
It should be: `OnDelete`. Tests are failing because `onDelete` is not recognised as a valid value.

2018-06-18 09:54 UTC, juan131 commented on stable/redis/values.yaml
> +    updateStrategy: onDelete
It should be: `OnDelete`. Tests are failing because `onDelete` is not recognised as a valid value.

2018-06-18 13:24 UTC, qlikcoe commented on stable/redis/values.yaml
> +    updateStrategy: onDelete
Fixed.

2018-06-18 14:53 UTC, juan131 commented
/lgtm

2018-06-18 14:54 UTC, merged