Implement CouchDB chart
helm/charts pull request #6144
Opened 2018-06-15 21:07 UTC by alexvicegrab

Signed-off-by: Alejandro Vicente Grabovetsky <sasha@aid.technology>

**What this PR does / why we need it**:

Implements Hyperledger Fabric node hosting custom CouchDB instance for holding Blockchain data.

**Special notes for your reviewer**:

A future chart (hlf-peer) will sometimes make use of this chart.

2018-06-24 13:39 UTC, unguiculus requested changes
Please follow our best practices for persistence: 
https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md#persistence

2018-06-24 13:39 UTC, unguiculus commented on incubator/hlf-couchdb/templates/deployment.yaml
> +apiVersion: apps/v1beta2
`apps/v1`

2018-06-24 13:39 UTC, unguiculus commented
/assign

2018-06-24 13:58 UTC, unguiculus commented
I'd suggest you move the chart to stable directly.

2018-06-25 10:45 UTC, alexvicegrab commented
Hi @unguiculus, thank you for reviewing the chart and suggesting improvements. Please review at your convenience!

2018-06-28 17:44 UTC, unguiculus approved these changes

2018-06-28 17:44 UTC, unguiculus commented
/ok-to-test

2018-06-28 17:47 UTC, unguiculus commented
/lgtm

2018-06-28 17:53 UTC, merged