[stable/minio] Bring back config map support
helm/charts pull request #6152
Opened 2018-06-18 05:23 UTC by nitisht

**What this PR does / why we need it**: Brings back ConfigMap support to Minio chart

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-06-24 13:50 UTC, unguiculus requested changes

2018-06-24 13:50 UTC, unguiculus commented on stable/minio/values.yaml
> +  replicas: 4
Why would it make sense to have that under `nasgateway` and only apply if `nasgateway.enabled` is `true`?

2018-06-24 13:50 UTC, unguiculus commented on stable/minio/values.yaml
> +  storageClass: standard
Why don't you simply use `persistence.storageClass`? You could avoid the conditional logic.

2018-06-24 13:51 UTC, unguiculus commented
cc @Acaleph @Minio

2018-06-24 13:51 UTC, unguiculus commented
This should also bump the minor version.

2018-06-25 07:23 UTC, nitisht commented on stable/minio/values.yaml
> +  storageClass: standard
done

2018-06-25 07:24 UTC, nitisht commented on stable/minio/values.yaml
> +  replicas: 4
I am not sure if I get the problem here. Do you mean I should use `replicas` instead of `nasgateway.replicas` ?

2018-06-28 13:12 UTC, nitisht commented
@unguiculus could you please take a look again. We have few users waiting on Minio helm chart support for NAS Gateway and config maps -- it would be great it we can take this in soon.

2018-07-09 05:32 UTC, nitisht commented
cc @mattfarina could you please take a look, looks like current reviewers are busy..

2018-07-10 00:55 UTC, prydonius commented
/ok-to-test

this lgtm, @unguiculus can you have another look?

2018-07-10 18:20 UTC, prydonius commented
Actually, I'm not sure why tests are passing because I'm seeing this error: 

```
I0710 02:16:50.974] 7ERROR 8Config migration failed: Failed to migrate config from ‘25’ to ‘26��
I0710 02:16:50.974] 7      8�. rename /root/.minio/$tmpfile.config.json.571856591 /root/.minio/config.
I0710 02:16:50.975] 7      8json: device or resource busy.
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/charts/6152/pull-charts-e2e/11487/?log#log

cc @mattfarina @unguiculus any ideas why the tests are silently passing here?

2018-07-11 09:51 UTC, nitisht commented
> Actually, I'm not sure why tests are passing because I'm seeing this error:

Thanks for bringing this up @prydonius I missed this too. Looks like ConfigMaps are readonly now (https://github.com/kubernetes/kubernetes/issues/62099). I will update the chart to copy the configMap to an `emptyDir`.

2018-07-12 05:46 UTC, nitisht commented
> This LGTM now, I do still want to find out why the test didn't fail before, though.

Sure.

2018-07-12 17:31 UTC, prydonius commented
@nitisht it looked like the readiness probe needs to be improved in this chart. It becomes ready so the CI thinks it's good, but then later fails. It would be great if you could improve this in a future PR.

/lgtm

2018-07-12 17:35 UTC, merged

2018-07-12 18:05 UTC, nitisht commented
> It would be great if you could improve this in a future PR.

Sure, will do @prydonius

2018-07-12 18:10 UTC, harshavardhana commented
Thanks everyone.