Implement hlf-ord chart
helm/charts pull request #6163
Opened 2018-06-18 10:32 UTC by alexvicegrab

Signed-off-by: Alejandro Vicente Grabovetsky <sasha@aid.technology>

**What this PR does / why we need it**:

Implements Hyperledger Fabric node hosting Orderer (consensus mechanism) instance for Blockchain network.

**Special notes for your reviewer**:

Chart requires setting two external secrets (a genesis block for the orderer, and the certificate of the Orderer organisation)

2018-06-24 13:55 UTC, unguiculus requested changes
Please follow our best practices for persistence:
https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md#persistence

2018-06-24 13:55 UTC, unguiculus commented on incubator/hlf-ord/templates/deployment.yaml
> +apiVersion: apps/v1beta2
`apps/v1`

2018-06-24 13:58 UTC, unguiculus commented
I'd suggest you move the chart to stable directly.

2018-06-24 13:58 UTC, unguiculus commented
/assign

2018-06-25 10:43 UTC, alexvicegrab commented
Hi @unguiculus, thank you for reviewing the chart and suggesting improvements. Please review at your convenience!

2018-06-28 18:37 UTC, unguiculus commented
/ok-to-test

2018-06-28 18:38 UTC, unguiculus approved these changes

2018-06-28 20:06 UTC, unguiculus commented
/lgtm

2018-06-28 20:07 UTC, merged