Rookout Agent Chart
helm/charts pull request #6167
Opened 2018-06-18 12:51 UTC by Zohar2506

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-06-18 13:26 UTC, Zohar2506 commented
/assign @unguiculus

2018-06-18 18:21 UTC, unguiculus requested changes

2018-06-18 18:21 UTC, unguiculus commented on incubator/rookout/values.yaml
> +  tag: latest
Use stable image

2018-06-18 18:21 UTC, unguiculus commented on incubator/rookout/templates/service.yaml
> +    app: {{ template "rookout.name" . }}
Ad `release` label to selector.

2018-06-18 18:21 UTC, unguiculus commented on incubator/rookout/templates/service.yaml
> +  labels:
Add standard labels.

2018-06-18 18:21 UTC, unguiculus commented on incubator/rookout/templates/deployment.yaml
> +          - name: ROOKOUT_TOKEN
Indent one more level for consistency.

2018-06-22 08:18 UTC, unguiculus requested changes
I'd suggest you move the chart to stable directly.

2018-06-22 08:18 UTC, unguiculus commented on incubator/rookout/templates/deployment.yaml
> +apiVersion: apps/v1beta2
Could you use `apps/v1`?

2018-06-22 08:18 UTC, unguiculus commented on incubator/rookout/templates/deployment.yaml
> +          periodSeconds: 20
Needs to be indented one more level:
```yaml
initialDelaySeconds: 15
periodSeconds: 20
```

2018-06-25 18:26 UTC, unguiculus requested changes
Now you have two charts, one in stable and one in incubator. Go for the stable one add yourself as maintainer to the `Chart.yaml`.

2018-06-26 07:18 UTC, Zohar2506 reviewed
Done

2018-06-26 07:18 UTC, Zohar2506 commented on incubator/rookout/templates/deployment.yaml
> +apiVersion: apps/v1beta2
Done

2018-06-28 07:43 UTC, Zohar2506 commented
Hi @unguiculus is it ok now?

2018-06-28 17:51 UTC, unguiculus commented
Looks good but you need to add a readme and NOTES.txt.

2018-07-01 15:49 UTC, unguiculus approved these changes

2018-07-01 15:49 UTC, unguiculus commented on stable/rookout/README.md
> +- Kubernetes 1.4+ with Beta APIs enabled
1.9+

2018-07-01 15:49 UTC, unguiculus commented on stable/rookout/templates/deployment.yaml
> +              value: {{.Values.token}}
Add a space after `{{` and before `}}` everywhere.

2018-07-11 08:13 UTC, Zohar2506 commented
Hey @unguiculus can you merge this pull request?
Is there anything missing?

2018-07-15 17:02 UTC, unguiculus commented
/ok-to-test

2018-07-16 07:11 UTC, Zohar2506 commented
@unguiculus

2018-07-23 07:42 UTC, Zohar2506 commented
/assign @unguiculus

2018-07-25 16:05 UTC, unguiculus commented
/ok-to-test

2018-07-25 17:34 UTC, unguiculus commented
/lgtm

2018-07-25 17:42 UTC, merged