Implement Hyperledger Fabric CA chart
helm/charts pull request #6181
Opened 2018-06-18 16:21 UTC by alexvicegrab

Signed-off-by: Alejandro Vicente Grabovetsky <sasha@aid.technology>

**What this PR does / why we need it**:

This PR adds a new Chart, which deploys the Hyperledger Fabric CA (Certificate Authority), or `hlf-ca`

**Special notes for your reviewer**:

N/A

2018-06-24 13:57 UTC, unguiculus requested changes
Please follow our best practices for persistence:
https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md#persistence

I'd suggest you move the chart to stable directly.

2018-06-24 13:57 UTC, unguiculus commented on incubator/hlf-ca/templates/deployment.yaml
> +apiVersion: apps/v1beta2
`apps/v1`

2018-06-24 13:58 UTC, unguiculus commented
/assign

2018-06-25 10:36 UTC, alexvicegrab commented
Hi @unguiculus, thanks for the feedback, thanks to which I've improved this chart to conform to the best practices.

However, explicitly including an empty storageClassName did not enable deploying, so I omit the storageClassName (as per  https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaultstorageclass) when it is specified as null, which automatically activates the default (similarly to what happens in the postgresql chart, for instance).

Hope this is acceptable, and thanks again!

2018-06-28 18:37 UTC, unguiculus commented
/ok-to-test

2018-06-28 18:37 UTC, unguiculus approved these changes

2018-06-28 20:06 UTC, unguiculus commented
/lgtm

2018-06-28 20:22 UTC, merged