Sqlproxy optional secret creation
helm/charts pull request #6298
Opened 2018-06-25 10:58 UTC by tjespers

**What this PR does / why we need it**: 
This PR makes it possible for users to specify an existing secret where the credentials for the cloud-sql proxy are stored. By doing so we allow users to make use of additional tooling e.g. [sealed-secrets](https://github.com/bitnami-labs/sealed-secrets) which converts encrypted secrets to regular secrets when entering the cluster.

**Which issue this PR fixes**: 
none

**Special notes for your reviewer**:

2018-06-25 10:59 UTC, tjespers commented
ping to @rimusz as chart maintainer

2018-06-25 13:13 UTC, rimusz commented
/lgtm

2018-06-25 13:15 UTC, rimusz commented
/assign @unguiculus

2018-06-25 13:17 UTC, rimusz commented
/approve

2018-06-25 18:49 UTC, unguiculus requested changes
This is commonly done with `existingSecret`. If you search for it, you'll find many examples. You could e. g. look here:

* https://github.com/kubernetes/charts/blob/master/incubator/keycloak/templates/db-secret.yaml
* https://github.com/kubernetes/charts/blob/master/incubator/keycloak/values.yaml#L175-L179
* https://github.com/kubernetes/charts/blob/master/incubator/keycloak/templates/_helpers.tpl#L51-L62

2018-06-25 18:50 UTC, unguiculus commented
/hold

2018-06-26 08:15 UTC, tjespers commented
@unguiculus your comments have been addressed could you take another look at it?

2018-06-28 18:33 UTC, unguiculus requested changes

2018-06-28 18:33 UTC, unguiculus commented on stable/gcloud-sqlproxy/README.md
> +| `existingSecretName`              | Name of an existing secret to be used for the cloud-sql credentials | `""`                                                            |
existingSecretName -> existingSecret

2018-06-28 19:36 UTC, tjespers commented
@unguiculus sharp one! & patched 👍

2018-07-01 16:13 UTC, unguiculus approved these changes

2018-07-01 16:13 UTC, unguiculus commented
/ok-to-test

2018-07-01 16:13 UTC, unguiculus commented
/hold cancel

2018-07-01 16:17 UTC, unguiculus commented
/lgtm

2018-07-01 16:21 UTC, merged