[incubator/spring-cloud-data-flow] Update to new SCDF version 1.5.1
helm/charts pull request #6378
Opened 2018-06-28 16:48 UTC by chrisjs

- update app version to 1.5.1
- update chart version to 0.2.3
- update skipper to 1.0.5
- update metrics to 2.0.0
- enable secured liveness and readiness endpoints on metrics
- update maintainers

**What this PR does / why we need it**:

Update the version of SCDF server, Skipper and Metrics.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-06-28 16:50 UTC, chrisjs commented
/assign @unguiculus

2018-06-28 17:50 UTC, unguiculus requested changes

2018-06-28 17:50 UTC, unguiculus commented on incubator/spring-cloud-data-flow/values.yaml
> +  metricsPassword: password
Leave default empty

2018-07-05 21:03 UTC, chrisjs commented
/assign @unguiculus

2018-07-13 18:50 UTC, sabbyanandan commented
Hi, @unguiculus. At your convenience, please let us know if you have any other suggestions for us to improve. Thanks for your time.

2018-07-15 16:38 UTC, unguiculus commented
/ok-to-test

2018-07-15 16:38 UTC, unguiculus approved these changes

2018-07-15 16:59 UTC, unguiculus commented
/lgtm

2018-07-15 17:20 UTC, merged