Update of data.replicas documentation
helm/charts pull request #6381
Opened 2018-06-28 19:33 UTC by mskjeret

The default value of data.replicas is 2 and not 3 as documented

2018-06-28 19:42 UTC, mskjeret commented
Signed CNCF Individual Contributor License Agreement

2018-08-05 18:45 UTC, mskjeret commented
/assign @simonswine

2018-08-05 19:08 UTC, davidkarlsen requested changes

2018-08-05 19:08 UTC, davidkarlsen commented on incubator/elasticsearch/README.md
> -| `data.replicas`                      | Data node replicas (statefulset)                                    | `3`                                  |
The Chart.yaml version will need to be bumped too.

2018-08-05 19:26 UTC, closed without merging