Make liveness and readiness settings configurable for the metrics con…
helm/charts pull request #6477
Opened 2018-07-05 08:28 UTC by svein-hallsteinsen

Need to make liveness / readiness settings configurable for the metrics container.
Background: Low timeout values may mark the metrics container unavailable, which in turn means new connections to mysql cannot be made.

2018-07-05 08:32 UTC, svein-hallsteinsen commented
/assign @scottrigby

2018-07-12 16:21 UTC, whereisaaron commented
Thanks for this PR @svein-hallsteinsen I was coming here specifically to propose the same fix!

The default 1s readiness probe time for the metrics sidecar seems to low in practice. Maybe if the probe was ':9104/' rather than ':9104/metrics' the response would be fast enough. Otherwise 2s might be better. Either way, we should be able to adjust it with the chart.

2018-07-12 17:55 UTC, svein-hallsteinsen commented
Hi @whereisaaron , in case you (and others) need it this is the workaround we currently use:

kubectl patch deployment -n mysql mysql -p '{"spec": {"template": {"spec": {"containers": [{"name": "metrics","readinessProbe": {"timeoutSeconds": 5},"livenessProbe": {"timeoutSeconds": 5}}]}}}}'

Add this patch after installing the chart. This will set timeouts to 5 seconds, running the patch will restart mysql if values change. We have the same issue as you, a readiness timeout of 1 seconds sometimes is too little. Sometimes it's enough and other times it's not.

Hopefully someone will look at this PR so we can avoid ugly hacks :-)

2018-07-16 21:15 UTC, whereisaaron commented
Thanks for the workaround patch @svein-hallsteinsen hopefully this small fix/patch will get merged pretty quickly since it causes operational errors (unless you disable metrics entirely).

2018-07-26 18:16 UTC, paulczar requested changes
Please bump the chart version (probably should be a minor bump) and update the README to add the new values to the table.

2018-07-26 18:16 UTC, paulczar commented on stable/mysql/templates/deployment.yaml
> +          initialDelaySeconds: {{ .Values.metrics.livenessProbe.initialDelaySeconds }}
please add this variable to README.md

2018-07-26 18:16 UTC, paulczar commented on stable/mysql/templates/deployment.yaml
> +          timeoutSeconds: {{ .Values.metrics.livenessProbe.timeoutSeconds }}
please add this variable to README.md

2018-07-26 18:16 UTC, paulczar commented on stable/mysql/templates/deployment.yaml
> +          initialDelaySeconds: {{ .Values.metrics.readinessProbe.initialDelaySeconds }}
please add this variable to README.md

2018-07-26 18:16 UTC, paulczar commented on stable/mysql/templates/deployment.yaml
> +          timeoutSeconds: {{ .Values.metrics.readinessProbe.timeoutSeconds }}
please add this variable to README.md

2018-07-26 18:18 UTC, paulczar commented
/ok-to-test

2018-08-02 08:18 UTC, svein-hallsteinsen commented
/retest

2018-08-02 08:26 UTC, svein-hallsteinsen commented
Thanks for your feedback @paulczar - I have pushed the changes you requested now. I'm new to this so I hope I'm doing it the right way.

2018-08-02 16:06 UTC, paulczar commented
/approve

2018-08-06 08:09 UTC, svein-hallsteinsen commented
Hi @scottrigby - any chance you can take a look at this? Very small pull request.

2018-08-16 13:57 UTC, mattfarina approved these changes

2018-08-16 13:58 UTC, mattfarina commented
/lgtm

2018-08-16 14:06 UTC, merged