Metrics server specs
helm/charts pull request #6488
Opened 2018-07-05 15:15 UTC by mf-lit

**What this PR does / why we need it**:
Adds support for the following specs in the metric-server deployment:
```
resources: {}
tolerations: []
nodeSelector: {}
affinity: {}
```
**Special notes for your reviewer**:
@olemarkus : Perhaps you should be in an OWNERS files for this chart? Not sure what the policy is here?

2018-07-05 16:25 UTC, olemarkus requested changes

2018-07-05 16:25 UTC, olemarkus commented on stable/metrics-server/values.yaml
> +  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
I think this is meant more as a documentation of the template than a user documentation. So this can/should be removed

2018-07-05 16:26 UTC, olemarkus requested changes

2018-07-05 16:26 UTC, olemarkus commented on stable/metrics-server/Chart.yaml
> +version: 0.0.3
I think we may as well bump this to 1.0.0. This is after all the stable branch.

2018-07-05 16:35 UTC, mf-lit commented on stable/metrics-server/values.yaml
> +  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
done

2018-07-05 16:35 UTC, mf-lit commented on stable/metrics-server/Chart.yaml
> +version: 0.0.3
done, now 1.0.0

2018-07-05 16:46 UTC, olemarkus approved these changes

2018-07-05 16:46 UTC, olemarkus commented
/lgtm
For whatever its worth

2018-07-15 20:41 UTC, NicolasT approved these changes

2018-07-15 21:53 UTC, olemarkus commented
/assign @mgoodness

2018-07-24 06:08 UTC, olemarkus commented
/assign

2018-07-24 06:13 UTC, olemarkus commented
Can you merge current master into your PR?

2018-07-24 17:59 UTC, olemarkus commented
/lgtm

2018-07-24 18:01 UTC, olemarkus commented
/ok-to-test

2018-07-24 21:25 UTC, NicolasT commented on stable/metrics-server/Chart.yaml
> +version: 1.0.0
Bit of a big version jump for something backwards-compatible.

2018-07-24 22:43 UTC, mattfarina commented
/ok-to-test

Fixed @olemarkus so he can manage this again

2018-07-25 04:55 UTC, olemarkus commented
/assign

2018-07-25 04:55 UTC, olemarkus commented
/lgtm

2018-07-25 04:56 UTC, merged