Allow user to specify a static IP for the Concourse loadbalancer
helm/charts pull request #6503
Opened 2018-07-06 14:01 UTC by ddadlani

Signed-off-by: Divya Dadlani <ddadlani@pivotal.io>

**What this PR does / why we need it**: Allows the user to specify a static load balancer IP for their Concourse deployment.

**Which issue this PR fixes**: fixes #3682

**Special notes for your reviewer**:

2018-07-15 14:20 UTC, william-tran commented
@xtremerui is the the version of the chart you have running in your test env?

2018-07-16 12:41 UTC, william-tran commented
/ok-to-test

2018-07-16 13:44 UTC, xtremerui commented
@william-tran I checked the failure message. Does it mean that I need to edit my PR to bump the chart version myself? Not entirely sure what to do here. Thx for reviewing!

2018-07-16 16:17 UTC, william-tran commented
@xtremerui yes every change need to bump the chart semver and this is done manually to control what gets bumped. Take a look at the other PRs to see what gets done. You also need to add an entry to the table in the readme for this new value.

2018-07-18 21:04 UTC, william-tran requested changes
Needs readme table entry and minor chart version bump

2018-07-27 17:51 UTC, william-tran commented
/retest

2018-07-27 17:54 UTC, william-tran commented on stable/concourse/README.md
> +| `web.service.loadBalancerIP` | Concourse Web Service Load Balancer IP | `nil` |
The IP to use when web.service.type is LoadBalancer would be more descriptive here.

2018-07-27 18:16 UTC, william-tran commented
/lgtm

2018-07-27 18:18 UTC, merged