[stable/influxdb] Adds option to create default user to influxDB
helm/charts pull request #659
Opened 2017-02-15 08:41 UTC by jose5918

Reasons for change:
- When authentication is enabled, at least one admin user must be
  available

Changes made:
- Adds job.yaml template
- This job creates a default user if job is enabled in values.yaml

Testing done:
- Deployed in cluster and verified the creation of a user in InfluxDB

2017-03-01 21:08 UTC, jackzampolin commented on stable/influxdb/templates/job.yaml
> +          - "http://{{ template "fullname" . }}:{{ .Values.config.http.bind_address }}/query"
Does this need to be `https://{{ template "fullname" . }}.{{ .Release.Namespace }}:{{ .Values.config.http.bind_address}}/query`?

2017-03-01 21:08 UTC, jackzampolin commented on stable/influxdb/templates/job.yaml
> +{{- if .Values.setDefaultUser.enabled -}}
rename file to `post-install-set-auth.yaml`?

2017-03-01 21:08 UTC, jackzampolin commented on stable/influxdb/templates/job.yaml
> +          - "http://{{ template "fullname" . }}:{{ .Values.config.http.bind_address }}/query"
Does this need to be `https://{{ template "fullname" . }}.{{ .Release.Namespace }}:{{ .Values.config.http.bind_address }}/query`?

2017-03-01 21:09 UTC, jackzampolin commented
@jose5918 This looks great! A couple of small things. Also could you add some info about this the the `stable/influxdb/README.md`?

This has been on my list! Thank you for putting this together.

2017-03-01 22:04 UTC, jose5918 commented
@jackzampolin I am actually currently working on a change to this. I think it would be considered better to pull in the values being set from a secret so i will let you know once I have it fixed.

2017-03-01 22:10 UTC, jose5918 commented on stable/influxdb/templates/job.yaml
> +          - "http://{{ template "fullname" . }}:{{ .Values.config.http.bind_address }}/query"
From my understanding this only needs to be done when across namespaces and the job should remain within the same namespace when deployed by helm as a chart

2017-03-01 22:10 UTC, jose5918 commented on stable/influxdb/templates/job.yaml
> +{{- if .Values.setDefaultUser.enabled -}}
Sure

2017-03-02 00:10 UTC, jose5918 commented
@jackzampolin I have moved the sensitive information to a secret and made your requested changes.

2017-03-02 18:05 UTC, jackzampolin requested changes

2017-03-02 18:05 UTC, jackzampolin commented on stable/influxdb/README.md
> +Make sure to uncomment or configure the job settings after enabling it.
Adding a note that if you don't set a password, a 'random' one will be created would be nice here.

2017-03-02 18:05 UTC, jackzampolin commented on stable/influxdb/values.yaml
> +    ## Default: "admin"
This is no longer correct. The password will default to `{{ randAscii 10 }}`. Please be sure to note this in the `values.yaml` file.

2017-03-02 18:05 UTC, jackzampolin commented
A couple more small things. Looks good with the secret!

2017-03-02 19:22 UTC, jose5918 commented
@jackzampolin Should be good to go

2017-03-02 20:19 UTC, jackzampolin commented
@jose5918 LGTM! 👍

2017-03-16 23:10 UTC, lachie83 commented
@k8s-bot ok to test

2017-03-17 05:14 UTC, seanknox commented
Hi @jose5918: can you bump the chart version to `0.3.0`? I'll then merge in. Thanks!

2017-03-17 05:44 UTC, jose5918 commented
@seanknox Thanks! Should be ready now

2017-03-17 05:49 UTC, merged

2017-03-17 05:49 UTC, seanknox commented
Thanks @jose5918!

2018-08-29 09:49 UTC, vanto commented
Question: Is there a reason why this has been solved via a post install hook job instead of relying on the environment variable support for this, provided by the [official influxdb docker image](https://hub.docker.com/_/influxdb/)? There are the variables `INFLUXDB_ADMIN_USER` and `INFLUXDB_ADMIN_PASSWORD` defined for the same purpose of this ticket.

2018-08-29 18:50 UTC, jose5918 commented
@vanto Looks like this was simpler to do at the time. Those environment variable options were not available for the container yet.

They came in a few months later https://github.com/influxdata/influxdata-docker/commit/98b260574b332e654478d64334dfb27513292a42#diff-d4e0a564e2a8ab5a97797191488eada4

Probably a good idea to open an issue and update this