[incubator/graphite] adds Graphite 1.1.3 chart
helm/charts pull request #6593
Opened 2018-07-11 08:07 UTC by monotek

**What this PR does / why we need it**: Adds Graphite metrics server chart

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-07-11 08:08 UTC, monotek commented
/assign @mgoodness

2018-07-11 09:33 UTC, costimuraru commented
Nice!

2018-07-16 23:40 UTC, monotek commented
/assign @unguiculus

2018-07-25 17:37 UTC, unguiculus requested changes
Please move the chart to stable.

2018-07-25 17:37 UTC, unguiculus commented on incubator/graphite/README.md
> +- Has been tested on Kubernetes 1.7+
Won't install on 1.7. I'd suggest you go for 1.9+

2018-07-25 17:37 UTC, unguiculus commented on incubator/graphite/templates/deployment.yaml
> +apiVersion: apps/v1beta2
`apps/v1`?

2018-07-25 19:03 UTC, monotek commented
@unguiculus 
Thanks for the review :-)
Changed everything as requested.

2018-07-26 19:42 UTC, unguiculus commented
I'd suggest you move the chart to stable.

2018-07-26 19:48 UTC, monotek commented
Why? Isn't it normal to have new charts in the incubator first?
But i'm on vacation until next Tuesday anyway. So I could make the change in the middle of next week.

2018-07-28 14:48 UTC, unguiculus commented
We tend to add charts to stable directly. I'd rather see incubator die. We don't need a place for have-baked stuff here. The chart looks pretty good. I don't see why you would want to add it to incubator.

2018-07-30 09:40 UTC, monotek commented
@unguiculus Thanks for the info :-)
I moved graphite to the stable repo now.

P.s.: What about the other incubator charts?
Will these be moved in one go or does the chart owners need to do this one by one?

2018-08-01 14:08 UTC, monotek commented
@unguiculus 
Imho we're ready to merge :-)

2018-08-08 21:40 UTC, davidkarlsen requested changes

2018-08-08 21:40 UTC, davidkarlsen commented on stable/graphite/README.md
> +$ helm install incubator/graphite --name graphite
still references to incubator

2018-08-08 22:20 UTC, monotek commented on stable/graphite/README.md
> +$ helm install incubator/graphite --name graphite
thanks. fixed :-)

2018-08-10 21:57 UTC, davidkarlsen commented
/ok-to-test

2018-08-10 22:14 UTC, davidkarlsen commented
/lgtm

2018-08-15 20:15 UTC, unguiculus commented
/lgtm

2018-08-15 20:21 UTC, merged