[stable/nginx-ingress] Add hostPort options for TCP/UDP ports.
helm/charts pull request #6618
Opened 2018-07-12 08:37 UTC by desaintmartin

Allows to define a `hostPort` option for each UDP and/or TCP port if using `DaemonSet`.

The `hostPort` value will be the same as the `port` one.

2018-07-12 08:41 UTC, desaintmartin commented
ping @chancez @mgoodness @jackzampolin

2018-07-12 15:15 UTC, chancez commented on stable/nginx-ingress/templates/controller-daemonset.yaml
> +              hostPort: {{ $key }}
Like the options above, this should be configurable to a specific hostPort, not necessarily the same value as the `containerPort`. Eg you could add a new variable  .Values.controller.daemonset.hostPorts.tcp` could be a map of string -> int just like .Values.udp` mapping container port to hostPort.

2018-07-12 15:16 UTC, chancez requested changes
For consistency and flexibility I think if this is to be added, the hostPort values should be configurable.

Additionally, these changes should probably be done to the deployment resource in addition to the daemonset.

2018-09-02 06:11 UTC, desaintmartin commented
I don't have the time to finish it properly. I'm going to close it, if anyone wants to take over, feel free. Otherwise I'll probably push a new PR for this later.

2018-09-02 06:11 UTC, closed without merging