[stable/kibana] Add support for loadBalancerSourceRanges
helm/charts pull request #6666
Opened 2018-07-17 06:12 UTC by wandergeek

**What this PR does / why we need it**:

Adds support for loadBalancerSourceRanges to the kibana chart. This is required for some installations which need to limit IP access.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-07-17 06:19 UTC, wandergeek commented
CLA has been verified

2018-07-24 06:13 UTC, wandergeek commented
/assign @sameersbn

2018-08-29 09:12 UTC, compleatang commented
@wandergeek can you rebase this and update the chart's versioning in the Chart.yaml? 

Happy to move this forward now that I'm on the Owners file of the chart.

2018-09-17 08:09 UTC, greenlionio commented
@compleatang It seems that no one is going to take care of this any time soon. I'd be happy to take over and have this moved forward, if that's OK.

2018-09-18 08:39 UTC, compleatang requested changes

2018-09-18 08:39 UTC, compleatang commented on stable/kibana/README.md
> +`service.loadBalancerSourceRanges` | Limit load balancer source IPs to list of CIDRs (where available)) | None:
let's change the last cell in this row of the table to `[]` so that users know it is an array.

2018-09-18 08:39 UTC, compleatang commented
@wandergeek sorry for the delay, I was only recently added to the chart owners. Happy to move this forward now.

@greenlionio happy to have a co-maintainer for the chart.

2018-09-18 08:40 UTC, compleatang commented
/ok-to-test

2018-09-18 08:41 UTC, compleatang commented
/assign

2018-09-18 08:42 UTC, greenlionio commented
@compleatang Great. Do you want me to re-base the code?

2018-09-18 08:46 UTC, compleatang commented
@greenlionio to move this PR forward someone will indeed need to rebase and also fix the test failure.

2018-09-18 08:48 UTC, greenlionio commented
@compleatang On it.

2018-09-18 12:01 UTC, greenlionio commented
@compleatang Noob question, how do I contribute to this PR? I've forked wandergeek's charts repo, did a rebase but given that he's not around how should I proceed?

2018-09-18 22:03 UTC, compleatang commented
@greenlionio cleanest way is to PR into OP's branch on his fork. less clean way is to cherry-pick the commit on your own fork and then resubmit a new PR.

2018-09-19 07:07 UTC, greenlionio commented
@compleatang Thought so . Given that OP hasn't been active since July I don't know when he'll approve my PR to his fork. OK, let's try that and if I don't hear from him in a day or two I will create my own PR.

2018-09-19 07:34 UTC, greenlionio commented
I've created a PR. Let's see if @wandergeek sees it any time soon.

2018-09-20 10:13 UTC, greenlionio commented
My bad, I didn't update chart version. I'll have that fixed so that tests pass.

2018-09-20 10:29 UTC, greenlionio commented
Chart version bumped. Tests should pass now. New PR created.

2018-09-25 09:02 UTC, compleatang commented
@greenlionio and @wandergeek still need to make the DCO bot happy. If you click details on the status failure it provides instructions.

2018-09-25 11:06 UTC, greenlionio commented
@wandergeek Can you, please, do this? I don't think this requires yet another PR. :)

2018-09-26 07:01 UTC, wandergeek commented
Is there an easy way to sign old commits? The instructions in the bot don't work. I've also tried the following. 
```
git filter-branch --commit-filter 'if [ "$GIT_COMMITTER_EMAIL" = "innernetz@gmail.com" ];
  then git commit-tree -S "$@";
  else git commit-tree "$@";
  fi' HEAD
```

2018-09-26 08:19 UTC, cpanato commented
@wandergeek  you can rebase an squash the commits

2018-09-27 06:53 UTC, greenlionio commented
@wandergeek Looks good. :)
@compleatang I think we're good to go.

2018-09-27 08:39 UTC, compleatang commented
/approve
/lgtm

2018-09-27 08:41 UTC, merged