dex: configure gRPC and generate the certificates (CA/server/client) during deployment
helm/charts pull request #6679
Opened 2018-07-17 13:46 UTC by ccojocar

In addition, the web cert values were refatored to be consistent with gRPC values.

**What this PR does / why we need it**:

`dex chart`: configure gRPC and generate the certificates (CA/server/client) during deployment

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-07-17 16:06 UTC, unguiculus requested changes

2018-07-17 16:06 UTC, unguiculus commented on stable/dex/templates/job-grpc-certs.yaml
> +  name: dex-grpc-certs
Resource names should be based on the fullname template.

2018-07-17 16:06 UTC, unguiculus commented on stable/dex/templates/job-web-certs.yaml
> +  name: dex-web-certs
Resource names should be based on the fullname template.

2018-07-17 16:06 UTC, unguiculus commented on stable/dex/values.yaml
> +resources:
Don't specify defaults for resources. Comment them out.

2018-07-17 16:06 UTC, unguiculus commented on stable/dex/templates/config-openssl.yaml
> +  name: dex-openssl-config
Resource names should be based on the fullname template.

2018-07-17 16:06 UTC, unguiculus commented
/assign

2018-07-18 11:45 UTC, ccojocar commented
@unguiculus Thanks! I fixed all review comments.

2018-07-25 07:42 UTC, ccojocar commented
@unguiculus Pease could you have a look at this PR? Is there anything left to get it merged?

2018-07-25 17:50 UTC, kfox1111 requested changes

2018-07-25 17:50 UTC, kfox1111 commented on stable/dex/values.yaml
> +  - type: github
This actually changes a hint to enabled config. Not sure this is desirable.

2018-07-25 17:50 UTC, kfox1111 commented on stable/dex/values.yaml
> -#  staticClients:
This was a useful example of how to use this. Please put it back.

2018-07-26 07:07 UTC, ccojocar commented
@unguiculus @kfox1111 I pushed the changes for review.

2018-07-26 15:35 UTC, kfox1111 commented
lgtm

2018-07-26 19:26 UTC, unguiculus approved these changes

2018-07-26 19:40 UTC, unguiculus commented
/lgtm

2018-07-26 19:49 UTC, merged

2018-08-02 14:27 UTC, andrewrynhard commented
@ccojocar What is the recommended way to use the cert generation feature? There is sort of a chicken and egg problem here is there not? You need to have the `--oidc-ca-file` to the API server set to use the web CA secret generated, but you don't have that until you deploy this chart.

2018-08-03 07:59 UTC, ccojocar commented
@andrewrynhard Are you talking about web endpoint CA or gRPC CA? Where do you need to set the `--oidc-ca-file` flag?

The job which generates the self-signed certificate for the web endpoint was there before my changes. It basically creates a self-signed certificate which is stored in a secret along with the CA. The public certificate of the CA is in addition stored in a configmap, which you can mount in a POD.