Update fluentd-cloudwatch tag
helm/charts pull request #6694
Opened 2018-07-18 09:41 UTC by swibrow

@kenden 
What this PR does / why we need it:
This affects the incubator/fluentd-cloudwatch chart.

Fix ```standard_init_linux.go:178: exec user process caused "no such file or directory"``` issue
with latest fluentd-cloudwatch version v0.12.43-cloudwatch

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-07-19 13:07 UTC, swibrow commented
this is actually a breaking change

[https://github.com/fluent/fluentd-kubernetes-daemonset/issues/172](https://github.com/fluent/fluentd-kubernetes-daemonset/issues/172)

2018-08-18 11:52 UTC, davidkarlsen requested changes

2018-08-18 11:52 UTC, davidkarlsen commented on incubator/fluentd-cloudwatch/values.yaml
> +  tag: v0.12.43-cloudwatch
can you update the README to match? TIA

2018-08-20 09:09 UTC, kenden commented
LGTM

2018-08-21 19:13 UTC, swibrow commented on incubator/fluentd-cloudwatch/values.yaml
> +  tag: v0.12.43-cloudwatch
@davidkarlsen

2018-08-27 22:51 UTC, davidkarlsen commented
/ok-to-test

2018-08-27 22:54 UTC, davidkarlsen commented
/lgtm

2018-08-27 22:55 UTC, davidkarlsen commented
/assign @mgoodness

2018-08-28 03:25 UTC, lachie83 commented
/approve

2018-08-28 03:41 UTC, merged