[stable/gocd] Enable use of host aliases
helm/charts pull request #6724
Opened 2018-07-19 11:41 UTC by rcjames

**What this PR does / why we need it**:
Enables use of [HostAliases](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#hostalias-v1-core)

2018-07-19 11:49 UTC, rcjames commented
I believe that I have signed the CLA and appropriately linked it to my account now. Can this be re-checked?

2018-07-19 15:51 UTC, rcjames commented
/assign @varshavaradarajan

2018-07-23 08:30 UTC, rcjames commented
Hello @mattfarina 

I'm not quite sure why @varshavaradarajan was unassigned from this PR, as I was just following the instructions left for me by the bot. Are you able to provide additional information on how I can get this PR moving?  As far as I can tell I am following all the instructions and guidelines which have been provided.

Thanks

2018-07-23 08:38 UTC, GaneshSPatil commented
@rcjames -- Thanks for the PR.
either I or @varshavaradarajan will take a look at this PR in sometime.

2018-07-23 09:02 UTC, varshavaradarajan requested changes
Please update the readme and the changelog as well. One of us will test this out and leave our review. Thanks. :)

2018-07-23 09:02 UTC, varshavaradarajan commented on stable/gocd/values.yaml
> +  hostAliases:
The convention is to document the usage of this property.  See other properties.

2018-07-23 09:33 UTC, rcjames commented
Thank you both for your responses.

@varshavaradarajan - I have added documentation to values.yaml and updated the README to list the new property. I have additionally update the version and update the changelog, but I won't know the commit reference until after this PR has been merged. Is that correct?

2018-08-09 07:49 UTC, GaneshSPatil commented
@rcjames -- you can make another commit on top of this one for changelog updates. Use the current commit reference in the changelog.

2018-08-09 19:07 UTC, mattfarina commented
@arvindsv @ganeshspatil @ganeshspatil @varshavaradarajan Does this look ok?

2018-08-09 19:07 UTC, mattfarina commented
/ok-to-test

2018-08-10 03:46 UTC, GaneshSPatil commented
/approve

2018-08-10 13:36 UTC, mattfarina commented
This still needs a /lgtm from one of the owners

2018-08-13 03:47 UTC, GaneshSPatil commented
@rcjames -- can we resolve the conflicts and make another commit on top of this one for changelog updates. Use the latest commit reference in the changelog.

2018-08-16 16:09 UTC, rcjames commented
@GaneshSPatil - I've resolved the merge conflicts and updated the changelog. Let me know if anything else looks amiss.

2018-08-17 05:15 UTC, bdpiparva commented
/lgtm

2018-08-17 05:21 UTC, merged

2018-08-17 05:31 UTC, arvindsv commented
Thank you veru much, @rcjames!