Add delayBeforeCheck parameter.
helm/charts pull request #6734
Opened 2018-07-20 03:10 UTC by kunickiaj

**What this PR does / why we need it**:
Add delayBeforeCheck parameter.

This is helpful in the scenario where you want to use dns-01
challenges in a public route53 zone, but your cluster's
resolver is using a private route53 zone and the initial TXT
check fails. This allows you to skip the check and instead
use a fixed delay before the ACME verification happens.

2018-07-20 03:46 UTC, kunickiaj commented
/assign @juliens

2018-08-02 01:49 UTC, dtomcej commented
Can you put that in an `if` block, so that it is not specified if it is not included in the `values.yaml`?

2018-08-12 19:17 UTC, davidkarlsen commented
@kunickiaj ping?

2018-08-13 16:03 UTC, kunickiaj commented
Just posted an update. Thanks for the reminder!

2018-08-13 17:57 UTC, davidkarlsen commented
/ok-to-test

2018-08-13 18:02 UTC, davidkarlsen commented
/lgtm

2018-08-13 22:07 UTC, kunickiaj commented
I think the edited approval tag did not trigger tide.

2018-08-13 22:17 UTC, dtomcej commented
/approve

2018-08-13 22:25 UTC, davidkarlsen requested changes

2018-08-13 22:25 UTC, davidkarlsen commented on stable/traefik/Chart.yaml
> +version: 1.40.0
can you bump the version again - something was merged before this

2018-08-14 07:02 UTC, davidkarlsen commented on stable/traefik/Chart.yaml
> +version: 1.40.0
@kunickiaj

2018-08-14 07:22 UTC, merged