[stable/openebs] Upgrade to openebs release 0.6
helm/charts pull request #6768
Opened 2018-07-23 12:04 UTC by kmova

**What this PR does / why we need it**:

This PR includes the following changes:
- Update the image tags to 0.6
- Add a new deployment introduced in 0.6 for supporting snapshots
- Identation fix with templates
- Updated README and Chart.yaml

Signed-off-by: kmova <kiran.mova@openebs.io>

2018-07-24 13:50 UTC, kmova commented
/assign @viglesiasce

2018-07-28 05:02 UTC, kmova commented
@unguiculus @mgoodness @seanknox - can you please help reviewing this PR.

2018-08-08 14:18 UTC, unguiculus requested changes

2018-08-08 14:18 UTC, unguiculus commented on stable/openebs/templates/deployment-maya-snapshot-operator.yaml
> +      tolerations:
affinity

2018-08-08 14:19 UTC, unguiculus requested changes

2018-08-08 14:19 UTC, unguiculus commented on stable/openebs/values.yaml
> +  tolerations: {}
`tolerations: []`

2018-08-08 16:54 UTC, kmova commented on stable/openebs/templates/deployment-maya-snapshot-operator.yaml
> +      tolerations:
thank you! fixed it.

2018-08-08 16:54 UTC, kmova commented on stable/openebs/values.yaml
> +  tolerations: {}
thank you! fixed it.

2018-08-08 16:58 UTC, unguiculus approved these changes

2018-08-08 16:58 UTC, unguiculus commented
/ok-to-test

2018-08-08 17:03 UTC, unguiculus commented
/lgtm

2018-08-08 17:04 UTC, merged