Added optional imagePullSecret at install time
helm/charts pull request #6771
Opened 2018-07-23 13:12 UTC by dirkmoors

**What this PR does / why we need it**:
This PR adds the possibility to provide an image pull secret at install time via the config param `image.pullSecret`. This allows for using customized, private Datadog agent images.

Example:
`helm install --set image.pullSecret=my-pull-secret,image.repository=acme/my-private-dd-agent-image stable/datadog`

2018-07-23 13:36 UTC, rendhalver commented
Please add the chart name [stable/datadog] to the PR title so it's easy to see at a glance what the PR is for.

2018-08-12 19:05 UTC, davidkarlsen requested changes

2018-08-12 19:05 UTC, davidkarlsen commented on stable/datadog/templates/daemonset.yaml
> +      imagePullSecrets:
README should be updated as well

2018-08-12 19:06 UTC, davidkarlsen commented
/assign
/assign @sameersbn

2018-09-03 11:42 UTC, davidkarlsen commented on stable/datadog/templates/daemonset.yaml
> +      imagePullSecrets:
@dirkmoors ping

2018-10-17 13:08 UTC, closed without merging