stable/metrics-server: add parameter image.custom_command_args
helm/charts pull request #6795
Opened 2018-07-24 17:27 UTC by mpratsch

* add label part to _helpers.tpl
  * add dynamic resources part
  * update README
  * change metrics-server.name to metrics-server.fullname in some parts of the deployment
  * bump version

We need to use additional arguments after the command like:  ```?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250&insecure=true"```.
Without the kubeletPort given it tries to connect to port 10255 (form. heapster) what is not available anymore. I think this is fixed in a higher k8s version.
We are running Kubernetes v1.9.5 right now.

Just a side note: kubelet_authentication_token_webhook must be true but that is set as default in the kubespray by commit c192a01b20608379510f030320ee4754eae444b7 if you use kubespray of course.

2018-07-24 21:26 UTC, NicolasT commented on stable/metrics-server/templates/metrics-server-deployment.yaml
> +        - name: {{ .Chart.Name }}
Why?

2018-07-24 21:26 UTC, NicolasT commented on stable/metrics-server/templates/metrics-server-deployment.yaml
> +            {{- if .Values.image.custom_command_args }}
Already handled in #6620

2018-07-24 21:27 UTC, NicolasT commented on stable/metrics-server/templates/metrics-server-deployment.yaml
> +            - --source=kubernetes.summary_api:''{{ .Values.image.custom_command_args }}
A bit surprised by the `''` *before* the `{{ .Values.... }}`

2018-07-24 21:28 UTC, NicolasT commented on stable/metrics-server/templates/metrics-server-deployment.yaml
> +          resources:
Already handled (and more) by #6488

2018-07-24 21:28 UTC, NicolasT commented on stable/metrics-server/templates/metrics-server-deployment.yaml
> +            {{- if .Values.image.custom_command_args }}
Inconsistent casing.

2018-07-24 21:29 UTC, NicolasT commented on stable/metrics-server/templates/metrics-server-deployment.yaml
> +  namespace: {{ .Release.Namespace }}
AFAIK Helm already takes care of this?

2018-07-24 21:30 UTC, NicolasT commented on stable/metrics-server/README.md
> +`image.custom_command_args` | Additionally command args | You can pass different values like ```kubeletPort``` to change the port. Example: ```?useServiceAccount=true&kubeletHttps=true&kubeletPort=10
A bit odd to have this in the `image` namespace.

2018-07-24 21:30 UTC, NicolasT requested changes
Overlaps with other in-progress PRs, and some inconsistencies.

2018-07-26 13:39 UTC, olemarkus commented
@mpratsch All the other PRs for metrics-server has been merged in now. You can pull in those changes and see what is left, but I suspect this one can just be closed now.

2018-07-26 13:40 UTC, olemarkus commented
/assign

2018-07-26 15:23 UTC, mpratsch commented
Thanks a lot @olemarkus.
I think your PRs solve all my "problems" and I also think that PR can be close.
I'm really sorry that I have overseen the already open PRs.

2018-07-26 15:23 UTC, closed without merging