[stable/verdaccio]: Avoid hard-coding gid in securityContext
helm/charts pull request #6814
Opened 2018-07-25 15:51 UTC by ercanucan

**What this PR does / why we need it**:
Currently, deploying verdaccio on OpenShift fails because when containers are deploying on OpenShift clusters, the gid 1000 does not exist. Containers on OpenShift are created with randomized IDs.

This PR avoids forcing volume with a specific gid which may not exist.

2018-07-25 15:55 UTC, ercanucan commented
@etiennetremel Here is another PR. We have been able to deploy verdaccio-gitlab on OpenShift successfully after this modification.

Again, I am not entirely sure what the best practices are here, so I would appreciate your input. I have looked at postgres helm charts as a reference (which we were able to deploy on OpenShift right off-the-shelf without any modifications)

2018-07-25 15:56 UTC, ercanucan commented
/assign @foxish

2018-07-25 15:57 UTC, ercanucan commented
cc @prydonius, @mattfarina

2018-07-25 16:21 UTC, etiennetremel approved these changes

2018-07-25 16:34 UTC, etiennetremel requested changes
Could you keep it behind a feature flag and enable it by default, see how it is done in the mongodb chart:

https://github.com/helm/charts/blob/2a0fd9884d8dc811a046977b93ea9f1ba9a190a2/stable/mongodb/templates/statefulset-secondary-rs.yaml#L27-L31

2018-07-31 13:53 UTC, dlouzan commented
@etiennetremel I will take over this since my colleague Ercan is on holiday. But there's something I don't understand about the current default for the `securityContext`. It didn't work for us in our OpenShift cluster, that's understandable because the uid is randomized on startup.

What I don't understand is how this code even works on vanilla kubernetes: checking the source verdaccio Dockerfile for 3.x, it creates and runs the process as user-group `verdaccio:verdaccio`, which get assigned the next uid and gid, in my current docker env are `100` and `101`. The base image for `node` seems to create the user & group `node:node` that actually both are `1000`:

```bash
/usr/local/app $ cat /etc/passwd | grep -iE 'node|verdaccio'
node:x:1000:1000:Linux User,,,:/home/node:/bin/sh
verdaccio:x:100:101:Linux User,,,:/home/verdaccio:/bin/false

/usr/local/app $ cat /etc/group | grep -iE 'node|verdaccio'
node:x:1000:node
verdaccio:x:101:verdaccio
```

So, I don't understand how mounting volumes under group `1000` allows the process running as user `verdaccio` to access the data. Shouldn't the defaults be (I will template this with a flag as you suggested):

```yaml
 securityContext: 
   runAsUser: 100
   fsGroup: 101
```

/cc @ercanucan @bufferoverflow

2018-07-31 15:11 UTC, etiennetremel commented
You are right, the following is actually what should have been there:
```
      securityContext:
        fsGroup: 101
```
The runAsUser is not necessary since it is set in the container. fsGroup is mandatory if you want users different than root to write files to persistent volumes.
So if you make these change that would be great, you don't need to make it behind a feature flag.

2018-07-31 15:42 UTC, dlouzan commented
Thank you for the quick answer, it's good to know that I'm not crazy :-)

Nevertheless, we still need to make this configurable with a feature flag, because in openshift, under certain deployment restrictions, we get assigned a random uid on startup. Trying to force it via a fixed number in the `securityContext` fails.

```
[fsGroup: Invalid value: []int64{101}: 101 is not an allowed group]
```

As I would make a PR to make it configurable, if it's ok for you, I would also add default values for `runAsUser = 100` and `fsGroup = 101`, I have seen in other charts that both are usually configurable.

2018-07-31 15:45 UTC, dlouzan commented
Also, I was working on improvements for this in the upstream verdaccio project, they have been merged into the future 4.x release, so this will probably need a refactoring in the future:
https://github.com/verdaccio/verdaccio/pull/864

At the moment we are working with our own custom builds based on that PR.

2018-07-31 21:12 UTC, etiennetremel commented
Sounds good, thanks!

2018-08-07 15:45 UTC, dlouzan commented
This can be closed, changes in https://github.com/helm/charts/pull/6957 have been accepted

2018-08-09 18:12 UTC, mattfarina commented
Closing due to other PR being accepted. If this should be re-opened please let me know.

2018-08-09 18:12 UTC, closed without merging