Correctly set options.path in dashboardProviders
helm/charts pull request #6815
Opened 2018-07-25 16:14 UTC by Segflow

`path` must be `/var/lib/grafana/dashboards/<provider_name>` while the example is `/var/lib/grafana/<provider_name>/dashboards/.

2018-07-25 16:15 UTC, Segflow commented
/assign @prydonius

2018-08-04 13:16 UTC, costimuraru approved these changes

2018-08-05 04:37 UTC, davidkarlsen requested changes

2018-08-05 04:37 UTC, davidkarlsen commented on stable/grafana/Chart.yaml
> +version: 1.12.1
Version needs bumping again after previous merges.

2018-08-05 04:38 UTC, davidkarlsen commented
/assign

2018-08-05 07:57 UTC, davidkarlsen commented
/lgtm
/ok-to-test

2018-08-05 08:05 UTC, davidkarlsen commented
/assign @prydonius

2018-08-07 15:31 UTC, unguiculus commented
/lgtm

2018-08-07 15:36 UTC, merged