Gogs chart
helm/charts pull request #690
Opened 2017-02-20 17:39 UTC by tvon

This adds a chart for Gogs (https://github.com/gogits/gogs).  It is currently functional for a development install (e.g., minikube).

2017-02-20 21:05 UTC, spxtr commented
@k8s-bot ok to test

2017-02-21 18:04 UTC, tvon commented
Is this failing due to [this helm 2.1 bug](https://github.com/kubernetes/helm/issues/1807)?  Can/should the e2e test be updated for helm 2.2?

2017-02-21 19:03 UTC, Unknwon commented on incubator/gogs/README.md
> +| `image.tag`                      | Gogs image version                                           | `0.9.141`                                                  |
`0.10 RC` just release, probably should use that?

2017-02-21 19:05 UTC, Unknwon commented on incubator/gogs/values.yaml
> +    appName: 'Gogs: Go Git Service'
Should probably simplify to just **Gogs**, official repo has removed verbose part, but not a big deal..

2017-02-22 17:43 UTC, tvon commented on incubator/gogs/README.md
> +| `image.tag`                      | Gogs image version                                           | `0.9.141`                                                  |
I'm inclined to leave it as the 0.9.141 as opposed to specifying an RC, and it's an easy thing to override for an installation.

2017-02-22 17:43 UTC, tvon commented on incubator/gogs/values.yaml
> +    appName: 'Gogs: Go Git Service'
Updated, thanks.

2017-03-23 00:01 UTC, seanknox commented on incubator/gogs/requirements.yaml
> +    version: 0.3.0
Consider bumping this to `0.6.0` (current version of the PostgreSQL chart)

2017-03-23 00:03 UTC, seanknox commented on incubator/gogs/templates/pvc.yaml
> +    volume.alpha.kubernetes.io/storage-class: default
Thoughts on using `volume.beta.kubernetes.io/storage-class` instead?

2017-03-23 00:06 UTC, seanknox commented
Hi @tvon, this looks pretty good. In addition to my comments, this needs `NOTES.txt`. Here's a [good example](https://github.com/kubernetes/charts/blob/master/stable/drupal/templates/NOTES.txt) from the Drupal chart.

2017-03-23 16:17 UTC, tvon commented on incubator/gogs/templates/pvc.yaml
> +    volume.alpha.kubernetes.io/storage-class: default
Thanks for looking at this. 

I was under the impression that the fallback to `volume.alpha.kubernetes.io/storage-class: default` was the right thing to do if no `storageClass` was provided.  Is this not the case?

2017-03-29 17:56 UTC, tvon commented
Note that the failure is the same as it was before, which appears to be a helm 2.1 bug.  Let me know how to proceed on the volume and this should be good to go.

2017-03-31 16:40 UTC, ekozan commented on incubator/gogs/templates/pvc.yaml
> +    volume.alpha.kubernetes.io/storage-class: default
yeap dont touch this one ;)

2017-04-10 16:31 UTC, tvon commented
@seanknox Does this still need changes?

2017-04-10 16:48 UTC, wstrange commented
Would really like to see this chart published soon!

Perhaps a future RFE:  For development, deploy using the embedded sqlite3 database engine. It would eliminated the need for postgres and would slim down the footprint.

2017-04-11 04:29 UTC, seanknox requested changes

2017-04-11 04:29 UTC, seanknox commented on incubator/gogs/templates/configmap.yaml
> +---
Can you remove these delimiters from your templates? While they *should* be valid there's an issue with helm that causes problems deleting resources when you delete a release.

2017-04-11 04:29 UTC, seanknox commented on incubator/gogs/templates/_helpers.tpl
> +We truncate at 24 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
Please bump truncation up to 63 characters.

2017-04-11 04:58 UTC, seanknox commented
LGTM! Thanks @tvon.

2017-04-11 17:14 UTC, seanknox approved these changes

2017-04-13 05:14 UTC, merged