[stable/fluentd-elasticsearch] moved fluentd-elasticsearch from incubator to stable
helm/charts pull request #6925
Opened 2018-07-31 12:50 UTC by monotek

**What this PR does / why we need it**: 
*  moved fluentd-elasticsearch from incubator to stable (as mentioned by @unguiculus incubator will die -> https://github.com/helm/charts/pull/6593#issuecomment-408612805)
* also added changes of https://github.com/helm/charts/pull/6707 & https://github.com/helm/charts/pull/6696

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-07-31 12:52 UTC, monotek commented
/assign @mgoodness

2018-08-08 21:08 UTC, monotek commented
/assign @unguiculus

2018-08-08 21:11 UTC, davidkarlsen commented
/ok-to-test

2018-08-08 23:08 UTC, davidkarlsen requested changes

2018-08-08 23:08 UTC, davidkarlsen commented on stable/fluentd-elasticsearch/Chart.yaml
> +- https://github.com/kubernetes/charts/incubator/fluentd-elasticsearch
old reference

2018-08-09 09:32 UTC, monotek commented
Thanks! Its also fixed in chart.yaml now.

2018-08-09 14:08 UTC, davidkarlsen commented
/lgtm

2018-08-13 20:15 UTC, unguiculus commented
/lgtm

2018-08-13 20:20 UTC, merged