Schema registry update kafka zk
helm/charts pull request #6963
Opened 2018-08-02 14:42 UTC by benjigoldberg

Updating Schema Registry Kafka dependency to 0.8.5 to keep up with the latest. This required a few minor changes to the subchart configuration:
* default persistence off
* change the zookeeper `servers` variable to the new `replicaCount` variable

Also added some missing documentation to README and the values file.

2018-08-02 14:49 UTC, benjigoldberg commented
@unguiculus @viglesiasce if either of you have a moment to take a quick glance at these changes it would be much appreciated!

2018-08-05 11:41 UTC, davidkarlsen commented on incubator/schema-registry/values.yaml
> +    enabled: false
is a more sane value to enable persistence by default? see https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#Persistence

2018-08-05 11:41 UTC, davidkarlsen commented on incubator/schema-registry/Chart.yaml
> +version: 0.4.6
since some parameters are removed/change name, would it make more sense to change the major version?

2018-08-05 14:32 UTC, benjigoldberg commented
@davidkarlsen thank you for the review! Excellent points -- addressed both

2018-08-05 19:55 UTC, davidkarlsen requested changes

2018-08-05 19:55 UTC, davidkarlsen commented on incubator/schema-registry/README.md
> +| `kafka.persistence.enabled` | Whether or not to use a persistent volume for kafka | `false` |
this does not match the default

2018-08-05 23:49 UTC, benjigoldberg commented
@davidkarlsen updated again -- thank you for the detailed review 👍

2018-08-05 23:50 UTC, davidkarlsen commented
/lgtm
/ok-to-test

2018-08-05 23:56 UTC, merged