[incubator/logstash] update to logstash version 6.3.2
helm/charts pull request #6966
Opened 2018-08-02 22:35 UTC by monotek

**What this PR does / why we need it**: updates logstash to version 6.3.2**

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-08-02 22:36 UTC, monotek commented
/assign @foxish

2018-08-03 16:59 UTC, davidkarlsen requested changes

2018-08-03 16:59 UTC, davidkarlsen commented on incubator/logstash/values.yaml
> +  tag: 6.3.2
could you update the README to be consistent with the values.yaml?

2018-08-03 17:21 UTC, monotek commented
@davidkarlsen 
sure, done :-)

2018-08-04 18:39 UTC, davidkarlsen commented
/lgtm
/ok-to-test

2018-08-07 15:02 UTC, unguiculus commented
/lgtm

2018-08-07 15:08 UTC, merged