upgrade image tag to 0.17.1
helm/charts pull request #7001
Opened 2018-08-05 12:50 UTC by ravicm

**What this PR does / why we need it**:

Upgrade nginx-ingress image tag go 0.17.1

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

I am using Azure kubernetes. 
```
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

The ingress works fine on setup. However, doesn't pick up any updates to Ingress objects later. The behavior was inconsistent with 0.15.0. After upgrade image to 0,17.1. I see nginx.conf not getting an update on every ingress change.

If the new version of images working fine, it's really useful to have come that by default. So that people are not losing time trying to debug the problems. This could also be achieved by passing values on the command line to helm, at the time of installation. In this case, I would recommend updating the readme with a note.

I am happy to run any kind of testing required to make this happen. Kindly guide me.

**Special notes for your reviewer**:
Thanks for you love.

2018-08-05 12:51 UTC, ravicm commented
/assign @scottrigby

2018-08-05 13:50 UTC, davidkarlsen requested changes

2018-08-05 13:50 UTC, davidkarlsen commented on stable/nginx-ingress/values.yaml
> +    tag: "0.17.1"
please update the README and Chart.yaml as well (both chart version and the appVersion)

2018-08-05 13:51 UTC, davidkarlsen commented on stable/nginx-ingress/values.yaml
> +    tag: "0.17.1"
also the CLA needs signing - see comments from the robot.

2018-08-06 07:31 UTC, jpds commented
This is missing the `securityContext` pieces required with the nginx upgrade (found in my linked PR).

2018-08-06 08:42 UTC, davidkarlsen commented
@jpds Nice catch.
I think this one should be closed in favour of #6745.
/close

2018-08-10 14:57 UTC, cpanato commented
/close

already merge here: https://github.com/helm/charts/pull/6745

2018-08-21 09:32 UTC, jpds commented
/close

2018-10-04 10:59 UTC, closed without merging