Comment out persistence.storageClass to accomodate K8s default storag…
helm/charts pull request #7003
Opened 2018-08-05 15:07 UTC by rcompos

Comment out persistence.storageClass to accomodate K8s default storage class.

K8s will by default use the storage class with annotation 'storageclass.kubernetes.io/is-default-class:  true'.   Setting the value persistence.storageClass to 'standard' hardcodes the storage class name to 'standard'.   By not defining value persistence.storageClass, K8s will use the default storage class, whatever it's name may be.

2018-08-05 15:32 UTC, davidkarlsen requested changes
Chart.yaml needs a version-bump as well, and also the README should be updated accordingly.

Also remember to sign the cla.

2018-08-05 17:06 UTC, rcompos commented
I've signed the CLA.  Thanks.

2018-08-05 18:00 UTC, davidkarlsen commented
/ok-to-test

2018-08-05 18:04 UTC, davidkarlsen commented on stable/minio/README.md
> +| `persistence.storageClass` | Storage class name of PVC           | `""`                                                    |
actually 'nil' is more correct here too - since the value in fact is not defined. Maybe nitpicking.

2018-08-05 19:57 UTC, davidkarlsen commented
/lgtm

2018-08-05 19:58 UTC, davidkarlsen commented
/assign @scottrigby

2018-08-07 14:57 UTC, unguiculus commented
/lgtm

2018-08-07 15:02 UTC, merged