[stable/grafana] Add sidecar options for env and useCurrentNamespace
helm/charts pull request #7060
Opened 2018-08-07 11:21 UTC by eloo

Adding values for configuring the sidecar with additional envs or use the current namespace of the pods for configmap lookups.

Related to: https://github.com/kiwigrid/k8s-sidecar/issues/2

2018-08-08 19:45 UTC, eloo commented
CLA signed

2018-08-20 10:01 UTC, stealthybox commented
It would be good to downgrade the ClusterRole and ClusterRoleBinding to a Role and RoleBinding when using this feature, as the sidecar shouldn't need to be able to read ConfigMaps across the entire cluster.

2018-08-20 22:20 UTC, stealthybox commented
The sidecar would not be able to get ConfigMaps from the Kubernetes API without a permitting RoleBinding or ClusterRoleBinding.

If it's working, you may have some leftover object from a previous installation.
It's also common misadvice to bind very permissive roles to the default ServiceAccount.
If you've modified the default SA in the namespace you're testing in, this may be where your API permissions are coming from.

2018-08-21 06:47 UTC, eloo commented
@stealthybox 
thanks for clarification but i'm not that familiar with the rbac concept.
i hope my changes are going into the correct way to fit your needs ;)

2018-08-22 23:02 UTC, stealthybox requested changes
Thanks @eloo -- this is totally what I was thinking

Here's something I noticed on the conditionals:

2018-08-22 23:02 UTC, stealthybox commented on stable/grafana/templates/clusterrole.yaml
> +{{- if and (or .Values.sidecar.dashboards.enabled .Values.sidecar.datasources.enabled) .Values.sidecar.useCurrentNamespace  }}
this line can probably just be:
```
{{- if .Values.sidecar.useCurrentNamespace  }}
```

The entire file should probably be wrapped in:
```
{{- if and .Values.rbac.create (or .Values.sidecar.dashboards.enabled .Values.sidecar.datasources.enabled) }}
```

2018-08-22 23:02 UTC, stealthybox commented on stable/grafana/templates/clusterrolebinding.yaml
> +{{- if and (or .Values.sidecar.dashboards.enabled .Values.sidecar.datasources.enabled) .Values.sidecar.useCurrentNamespace  }}
same as above

2018-08-23 06:06 UTC, eloo commented
@stealthybox okay i've adapted my PR

2018-08-23 22:27 UTC, stealthybox commented
/lgtm

@mattfarina would you mark this as `/ok-to-test` ?
I'm not in the Helm org since we moved things over.

2018-09-10 23:49 UTC, stealthybox commented
/assign @linki 

got a sec for this one @linki ? :)

2018-09-14 19:35 UTC, giacomoguiulfo commented
@eloo thanks for the effort!

The k8s-sidecar now supports lookup in the current namespace "natively", and `AFAIK`, there is no need to make the chart more complex by adding `RBAC` and `ClusterRole` resources because the pod no longer needs them to get the namespace information.

Take a look at #7702. IMHO, I think this PR should perhaps drop that part of the changes. However, the additonal envs feature can still go as part of this PR 👍

2018-09-14 19:36 UTC, giacope requested changes
👆

2018-09-16 17:52 UTC, eloo commented
@giacomoguiulfo okay so i will close this PR

2018-09-18 20:18 UTC, giacomoguiulfo commented
@stealthybox You are correct, my bad 😞. We should have this changes in, (ping @eloo). Perhaps, the only modification will be the use of `useCurrentNamespace`, depending on what do you guys think is the most appropiate way for configuring that (either letting the sidecar figure it out by not passing an env variable or by setting `NAMESPACE` to `fieldPath: metadata.namespace`).

However, for the case of using the current namespace, the RBAC resources can still be optional since the default `ServiceAccount` is enough for the task. This doesn't affect the changes though.

2018-09-18 23:42 UTC, stealthybox commented
We should explicitly define the Role.

We shouldn't rely on a namespace's configured default SA, as it's managed outside the chart.
(It may be modified by a user/operator or another chart)

The Role for the current namespace use-case would also be more specific than most default SA's.
( can only read configmaps )

2018-09-19 06:15 UTC, eloo commented
@stealthybox so whats the plan?

2018-09-19 16:12 UTC, stealthybox commented
@eloo I think your patch is good and can be merged right now. (cc @davidkarlsen)

#7702 needs some edits and could benefit from your work.

2018-09-20 21:02 UTC, stealthybox commented
@eloo see instructions for signing off on your commits: https://github.com/helm/charts/pull/7060/checks?check_run_id=18506998

2018-09-21 08:43 UTC, eloo commented
something went wrong with the signoff step.. i will reopen this PR

2018-09-21 08:43 UTC, closed without merging