stable/concourse: use the correct work dir in the container preamble
helm/charts pull request #7061
Opened 2018-08-07 11:22 UTC by norbertbuchmueller

There's a short preamble (written in shell) in the container that cleans up before the container starts. It had the work dir hard-coded, while its value has been configurable since a few chart versions.

Now it uses the same configured value.

2018-09-03 19:59 UTC, paulczar requested changes
this looks okay to me, just needs merge conflict fixed.

2018-09-03 19:59 UTC, paulczar commented
/ok-to-test

2018-09-04 08:59 UTC, norbertbuchmueller commented
@paulczar i just fixed the merge conflict.

2018-09-04 09:06 UTC, cpanato commented
/lgtm

2018-09-06 21:02 UTC, paulczar commented
/approve

2018-09-06 21:17 UTC, merged