Make mariadb's service supports NodePort mode
helm/charts pull request #7094
Opened 2018-08-09 05:41 UTC by zacharyzhao

In my case, the MariaDB which is deployed on kubernetes is going to be used by apps out of kubernetes, so I did such things to achieve that goal:

- Move `service` to each of master and slave's configure content
- Add new service type: NodePort
- Update NOTES.txt
- Update values.yaml and values-production.yaml

2018-08-09 06:12 UTC, zacharyzhao commented
I move `MariaDB` service configuration to each of master and slave's config block, so their `NodePort` can be different, then apps running outside k8s can use the different port for writing or reading. @sameersbn @juan131

2018-08-09 15:42 UTC, juan131 requested changes
@zacharyzhao moving `service` to each of master and slave's configure content breaks compatibility with previous versions and, therefore, you can't upgrade from previous versions... I don't see any advantage on this and.. since it means a major version of the chart. I'd try to avoid it.

On the other hand, I agree with including the possibility of configuring the `nodePort`.

2018-08-10 02:48 UTC, zacharyzhao commented
@juan131  I updated this PR, I put service block back and add configures for `NodePort` in it.

2018-08-10 08:41 UTC, juan131 reviewed
Much better! Please take a look to my suggestions

2018-08-10 08:41 UTC, juan131 commented on stable/mariadb/templates/master-svc.yaml
> +{{- if eq .Values.service.type "NodePort" }}
You can use a single line:

```
{{- if (and (eq .Values.serviceType "NodePort") (not (empty .Values.service.nodePort.master))) }}
```

2018-08-10 08:41 UTC, juan131 commented on stable/mariadb/templates/slave-svc.yaml
> +{{- if eq .Values.service.type "NodePort" }}
You can use a single line:
```
{{- if (and (eq .Values.serviceType "NodePort") (not (empty .Values.service.nodePort.slave))) }}
```

2018-08-10 08:41 UTC, juan131 commented on stable/mariadb/values-production.yaml
> +  nodePort:
Great! Please add some comments:

```
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePort:
  ...
```

2018-08-11 16:18 UTC, zacharyzhao commented
Hi, @juan131 , thanks for your advises, and I've already updated the branch, please check if it is ok now.

Thank you very much!~

2018-08-13 07:27 UTC, merged