[stable/selenium] upgrade version to 3.14.0
helm/charts pull request #7113
Opened 2018-08-09 22:04 UTC by Chr1st0ph

upgrade version to 3.14.0

2018-08-09 22:07 UTC, Chr1st0ph commented
/assign @seanknox

2018-08-10 11:24 UTC, davidkarlsen requested changes

2018-08-10 11:24 UTC, davidkarlsen commented on stable/selenium/values.yaml
> +  tag: "3.14.0"
can you update the readme to the according values (for all of them)

2018-08-10 11:42 UTC, Chr1st0ph commented on stable/selenium/values.yaml
> +  tag: "3.14.0"
@davidkarlsen done

2018-08-10 13:55 UTC, mattfarina commented
@flah00 @diemol Can you please review this PR?

2018-08-10 14:00 UTC, cpanato commented
I can help if need. I tested locally and look good so far

2018-08-10 14:15 UTC, flah00 commented
/lgtm

2018-08-10 14:53 UTC, cpanato commented
/lgtm

2018-08-10 16:02 UTC, davidkarlsen commented
/lgtm

2018-08-10 21:00 UTC, davidkarlsen commented
/ok-to-test

2018-08-11 09:28 UTC, Chr1st0ph commented
/assign @seanknox

2018-08-13 18:05 UTC, mattfarina commented
/approve

2018-08-13 18:12 UTC, merged