Ark schedules
helm/charts pull request #7165
Opened 2018-08-14 08:12 UTC by plumdog

**What this PR does / why we need it**:
- Refactors the Ark chart's handling of CRDs and creation of instances of those CRDs.
- Adds an option to add schedules via the helm chart.

**Which issue this PR fixes** : fixes #6448 #6438 

**Special notes for your reviewer**:
This makes use of helm's `crd-install` hook, which is included in helm 2.10, which has release candidates, but is not actually released yet. Using this means that we can get rid of the post-install hook that was running `kubectl create ...`, which is what caused the two issues linked above.

2018-08-14 21:26 UTC, paulczar commented
I think we need to wait until helm 2.10 is released and we should probably document that it requires helm 2.10 or higher.

2018-08-14 21:44 UTC, plumdog commented
@paulczar sounds good.

I will investigate whether the `pre-install` hook is a reasonable fallback.

2018-08-15 07:56 UTC, plumdog commented
My experiments suggest that the answer to https://github.com/helm/charts/pull/7165#issuecomment-413026401 is "no".

I have set the required helm version in Chart.yaml.

This should not be considered for merging until helm 2.10 is released.

2018-08-17 20:56 UTC, plumdog commented
Helm 2.10 is [now released](https://github.com/helm/helm/releases/tag/v2.10.0) which is lovely.

So I now claim that this PR should be considered for merging.

2018-10-31 19:50 UTC, unguiculus requested changes
I think this change warrants a major chart version bump.

2018-10-31 19:50 UTC, unguiculus commented on stable/ark/templates/config.yaml
> +{{ with .Values.configuration }}
If you move this further down as it was, you don't need to capture the root context in a separate variable.

2018-11-08 17:42 UTC, jrnt30 commented
This seems very aligned with the way I would want to approach this as well.  Started looking at upgrading to the 0.10 RC internally via Helm and this would make adjusting the CRDs much easier

2018-11-09 14:29 UTC, unguiculus commented
FYI, there are issues with the new crd hook: https://github.com/helm/helm/issues/4697

2018-12-13 11:17 UTC, plumdog commented
Have rebased and made the suggested CR change.

However the `crd-install` hook issues are a bit more worrying. Do we have an accepted _least bad_ way of handling CRD's in helm? Should the current state of `crd-install` be considered better or worse than the existing behaviour in this chart?

2019-01-16 19:18 UTC, unguiculus commented
Sorry for the delay. Please fix DCO and resolve conflicts so we can move this forward.

2019-01-17 09:01 UTC, plumdog commented
@unguiculus No problem!

Rebased and DCO-ed.

2019-01-17 11:33 UTC, unguiculus commented
/ok-to-test

2019-01-17 11:50 UTC, unguiculus approved these changes

2019-01-17 11:50 UTC, unguiculus commented
/lgtm

2019-01-17 11:52 UTC, merged