NOTES: change port-forward to single command
helm/charts pull request #7178
Opened 2018-08-14 17:36 UTC by inodb

**What this PR does / why we need it**:
Change NOTES to forward the port of the service instead of pod which is a bit more readable

2018-08-14 21:11 UTC, paulczar commented
/ok-to-test

2018-08-15 08:44 UTC, davidkarlsen commented
@inodb Chart.yaml needs version bump. Also can you sign the CLA?

2018-08-15 08:46 UTC, davidkarlsen commented on stable/mysql/templates/NOTES.txt
> +    kubectl port-forward svc/{{ template "mysql.fullname" . }} {{ default "3306" .Values.service.port }}:{{ default "3306" .Values.service.port }}
is the default needed, see: https://github.com/helm/charts/blob/master/stable/mysql/templates/svc.yaml - it uses .Values.service.port

2018-08-15 16:25 UTC, inodb commented
@davidkarlsen thanks for reviewing - bumped version and removed 3306 port defaults

2018-08-15 16:52 UTC, davidkarlsen requested changes

2018-08-15 16:52 UTC, davidkarlsen commented on stable/mysql/templates/NOTES.txt
> +    kubectl port-forward svc/{{ template "mysql.fullname" . }} {{ .Values.service.port }}:{{ .Values.service.port }}
.Values.service.port is double up

2018-08-15 17:48 UTC, inodb commented on stable/mysql/templates/NOTES.txt
> +    kubectl port-forward svc/{{ template "mysql.fullname" . }} {{ .Values.service.port }}:{{ .Values.service.port }}
fixed

2018-08-15 18:21 UTC, davidkarlsen commented on stable/mysql/templates/NOTES.txt
> +    kubectl port-forward svc/{{ template "mysql.fullname" . }} {{ .Values.service.port }}:{{ .Values.service.port }}
ah - silly me - that wasn't really wrong - but anyways - it looks good either way

2018-08-15 20:01 UTC, unguiculus commented
/lgtm

2018-08-15 20:02 UTC, merged