[stable/oauth2-proxy] Adds additional configuration options for oauth2 providers
helm/charts pull request #7189
Opened 2018-08-15 07:03 UTC by tombotch

**What this PR does / why we need it**:
This PR adds configuration for the `google` and `github` providers. This allows authentication to easily be restricted to certain groups, orgs and teams. The `google` provider configuration specifically adds the required credentials to the existing oauth2_proxy secret.

It also moves the e-mail domains configuration to its own field within `values.yaml`, which allows these to more easily be configured within a values file.

**Special notes for your reviewer**:
I've added some additional checks in to ensure that backwards compatibility is maintained.

2018-08-15 07:05 UTC, tombotch commented
/cc @compleatang

2018-08-15 09:07 UTC, compleatang requested changes

2018-08-15 09:07 UTC, compleatang commented on stable/oauth2-proxy/templates/deployment.yaml
> +        {{- if (not (index .Values.extraArgs "email-domain")) and (.Values.emailDomains) }}
for readability IMV it's best to outdent `if`, `range` and `end` statements.

2018-08-15 09:07 UTC, compleatang commented on stable/oauth2-proxy/values.yaml
> +# Provider-specific configuration
personally, i like this method. but it needs documenting in the README.

2018-08-15 09:09 UTC, compleatang commented
@tombotch unfortunately i'm not currently a member of the helm organization so I can't drive this forward too far. These are pretty major changes so will require a minor version bump of the Chart.yaml to version `0.6.0`. In addition, as noted above we'll need to document the changes in the values table within the README.

2018-08-15 17:15 UTC, tombotch commented
Thanks for taking the time to review @compleatang - I've made changes based on your feedback.

2018-08-15 22:17 UTC, compleatang commented
👍

2018-08-15 22:17 UTC, compleatang commented
/assign @unguiculus

2018-09-14 10:18 UTC, unguiculus commented
This chart has been deprecated and will no longer receive update. I'm, thus, closing this.

2018-09-14 10:18 UTC, closed without merging