Added affinity.
helm/charts pull request #7194
Opened 2018-08-15 13:57 UTC by michalschott

**What this PR does / why we need it**:
It adds affinity to external-dns pod.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
N/A

**Special notes for your reviewer**:
None

2018-08-15 14:18 UTC, michalschott commented
/assign @scottrigby

2018-08-15 14:18 UTC, davidkarlsen requested changes
You need to bump the Chart.yaml version too

2018-08-15 16:11 UTC, davidkarlsen commented
/ok-to-test

2018-08-15 18:40 UTC, davidkarlsen commented on stable/external-dns/templates/deployment.yaml
> +{{ toYaml .Values.affinity | indent 8 }}
should maybe be outside the tolerations conditional?

2018-08-16 09:01 UTC, michalschott commented
Updated

2018-08-28 03:30 UTC, lachie83 commented
/approve

2018-08-28 03:41 UTC, merged