add missing namespace to mongodb notes
helm/charts pull request #7216
Opened 2018-08-16 08:46 UTC by eguven

**What this PR does / why we need it**:

Adds namespace to the `kubectl run` command in NOTES.txt for connecting to database.

2018-08-16 10:01 UTC, davidkarlsen requested changes

2018-08-16 10:01 UTC, davidkarlsen commented on stable/mongodb/templates/NOTES.txt
> +    kubectl run --namespace {{ .Release.Namespace }} {{ template "mongodb.fullname" . }}-client --rm --tty -i --image bitnami/mongodb --command -- mongo admin --host {{ template "mongodb.fullname" .
can you bump the chart-version too? TIA

2018-08-16 11:54 UTC, tompizmor commented
Yes please, bump the chart version so the circle-ci job pass.

https://circleci.com/gh/helm/charts/21563?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2018-08-16 11:55 UTC, tompizmor requested changes
Yes please, bump the chart version so the circle-ci job pass.

https://circleci.com/gh/helm/charts/21563?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2018-08-20 09:10 UTC, juan131 commented
/ok-to-test
/lgtm

2018-08-20 09:14 UTC, merged