[NEW stable/busybox] added busybox chart
helm/charts pull request #723
Opened 2017-02-23 19:18 UTC by jfelten

We use this to exercise our CI pipeline

2017-03-16 22:38 UTC, lachie83 commented
@k8s-bot ok to test

2017-03-22 23:27 UTC, seanknox commented on stable/busybox/values.yaml
> +    memory: 128Mi
These resources don't appear to be used. [Here's](https://github.com/kubernetes/charts/blob/master/stable/datadog/templates/daemonset.yaml#L20) an example of a chart using them.

2017-03-22 23:28 UTC, seanknox commented
Works like a charm! :) One comment around resource quotas, but otherwise LGTM.

2017-03-27 18:06 UTC, jfelten commented
ok I added a resources section per the review comments

2017-03-27 20:37 UTC, unguiculus requested changes

2017-03-27 20:37 UTC, unguiculus commented on stable/busybox/templates/_helpers.tpl
> +{{- printf "%s-%s" .Release.Name $name | trunc 24 | trimSuffix "-" -}}
I think you should truncate at 63 characters.

2017-03-27 20:37 UTC, unguiculus commented on stable/busybox/values.yaml
> +    memory: 128Mi
I think it is best practice not to set resources by default. Here's an example: https://github.com/kubernetes/charts/blob/master/stable/nginx-ingress/values.yaml#L41

2017-03-27 20:37 UTC, unguiculus commented on stable/busybox/templates/deployment.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
Use best practices for label.
https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md#standard-labels

2017-03-27 20:39 UTC, seanknox commented
Good suggestions @unguiculus. @jfelten would you mind updating based on @unguiculus's feedback?

2017-03-27 20:42 UTC, seanknox commented on stable/busybox/templates/deployment.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
👍  to standard labels

re: not setting resources by default—while we don't call for this explicitly in our technical requirements, I can see the merit. Wouldn't consider it blocking for this PR.

2017-04-06 11:16 UTC, prydonius commented
I'm not convinced this chart provides much value to the stable chart repo, which is intended for pre-packaging useful application. This seems more like a debugging tool. Why would I use this instead of simply using `kubectl run`? What if I wanted to use alpine, or debian -- I don't see us having a chart for every base OS?

2017-04-11 17:17 UTC, seanknox commented
@jfelten Agree with @prydonius on this. Charts are meant to facilitate services running in a Kubernetes cluster, and busybox as a one-off command doesn't fit that model. I'm sorry to we left you hanging as long as we did on this and will try to do a better job at assessing in the future.

2017-04-11 17:17 UTC, closed without merging

2017-04-19 00:05 UTC, jfelten commented
Sorry for not replying - I forgot about this.  We have an actual need for this in a client helm build pipeline, and from experience it is useful to spin up a pod through helm vs kubectl.  I do understand the need to keep the charts repo clean and purposeful and will publish this elsewhere.