Updated Artifactory version to 5.1.0
helm/charts pull request #725
Opened 2017-02-24 01:22 UTC by jainishshah17

2017-03-10 17:20 UTC, mgoodness requested changes
Let's be explicit about using the `image` & `image tag` values rather than depending on the `default` function.

2017-03-10 17:20 UTC, mgoodness commented on incubator/artifactory/templates/deployment.yaml
> +        image: "{{default "docker.bintray.io/jfrog/artifactory-oss" .Values.image}}:{{default "5.1.0" .Values.imageTag}}"
Let's drop the `default` statements here and use the `image` & `imageTag` values explicitly.

2017-03-10 17:20 UTC, mgoodness commented on incubator/artifactory/values.yaml
>  #image: "docker.bintray.io/jfrog/artifactory-pro"
Since we're dropping the `default` statements, set the image to `docker.bintray.io/jfrog/artifactory-oss`.

2017-03-10 21:12 UTC, jainishshah17 commented
@mgoodness made changes per suggestion. Please check

2017-03-16 23:14 UTC, lachie83 commented
@mgoodness Can you please review again?

2017-03-24 16:51 UTC, jainishshah17 commented
@mgoodness @lachie83  any update?

2017-03-24 17:15 UTC, mgoodness approved these changes

2017-03-24 17:17 UTC, mgoodness commented
@jainishshah17 Sorry about the delay. Ready to merge!

2017-03-26 17:59 UTC, merged