zookeeper terminationGracePeriodSeconds on template spec rather than StatefulSet
helm/charts pull request #7262
Opened 2018-08-20 13:39 UTC by aster-anto

**terminationGracePeriodSeconds on StatefulSet is in incorrect place and current chart is broken**:

Currently for zookeper
```
helm install .
```
fails with following :

```
Error: error validating "": error validating data: found invalid field terminationGracePeriodSeconds for v1beta1.StatefulSetSpec
```
I suppose this is due to `terminationGracePeriodSeconds` is mentioned incorrectly. This PR fixes it.

@lachie83 @kow3ns please have a look and merge to fix. Thanks

2018-08-20 13:48 UTC, aster-anto commented
/assign @lachie83

2018-08-20 13:57 UTC, aster-anto commented
/check-cla

2018-08-20 14:00 UTC, aster-anto commented
/lint

2018-08-28 03:35 UTC, lachie83 commented
Please bump the chart version

2018-08-28 03:35 UTC, lachie83 requested changes
Needs a chart version bump please

2018-08-28 11:36 UTC, aster-anto commented
version updated to 1.1.2. thanks @lachie83

2018-08-28 14:26 UTC, davidkarlsen commented
/ok-to-test

2018-09-03 16:30 UTC, merged