[stable/chaoskube] Use version version 10 + Adding minimum age to the chart
helm/charts pull request #7289
Opened 2018-08-22 10:17 UTC by shaikatz

**What this PR does / why we need it**:
Use version version 10 + Adding minimum age to the chart

2018-08-22 10:18 UTC, shaikatz commented
/assign @linki

2018-08-27 08:04 UTC, linki commented on stable/chaoskube/Chart.yaml
> +appVersion: 0.10.0
We need to update the `imageTag` in `values.yaml` to `v0.10.0` as well.

2018-08-27 08:04 UTC, linki requested changes
We need to bump `imageTag` in `values.yaml`

2018-08-27 21:37 UTC, davidkarlsen requested changes

2018-08-27 21:37 UTC, davidkarlsen commented on stable/chaoskube/README.md
> +| `minimumAge`              | Set minimum pod age to filter pod by                | `0s`                             |
version tag in README should match too

2018-08-28 07:54 UTC, davidkarlsen approved these changes

2018-08-28 07:56 UTC, davidkarlsen commented
@shaikatz Can you sign off your commits? TIA. See: https://github.com/helm/charts/pull/7289/checks?check_run_id=14283858

2018-08-28 08:19 UTC, shaikatz commented
I'll reopen that. it became a mess with this DCO.

2018-08-28 08:19 UTC, closed without merging