Changed label to labels to fix syntax error
helm/charts pull request #7295
Opened 2018-08-22 16:39 UTC by Matei207

**What this PR does / why we need it**:
Fixes syntax error in `prometheus-adapter` chart

**Which issue this PR fixes** : fixes #7293

2018-08-23 12:35 UTC, mattjmcnaughton commented
I don't have approve rights, but this looks good to me :)

2018-09-06 18:00 UTC, hairyhenderson commented
@Matei207 there's another occurrence in https://github.com/helm/charts/blob/98b48cb722047701477029658a4a5b78962c4d7f/stable/prometheus-adapter/templates/secret.yaml#L5 that maybe could be fixed too?

2018-09-06 18:51 UTC, davidkarlsen commented
/ok-to-test
/assign

2018-09-06 18:52 UTC, davidkarlsen requested changes

2018-09-06 18:52 UTC, davidkarlsen commented on stable/prometheus-adapter/templates/custom-metrics-apiserver-service.yaml
> +  labels:
Please fix https://github.com/helm/charts/blob/98b48cb722047701477029658a4a5b78962c4d7f/stable/prometheus-adapter/templates/secret.yaml#L5 too - as was mentioned in the comments

2018-09-08 11:44 UTC, davidkarlsen commented on stable/prometheus-adapter/templates/custom-metrics-apiserver-service.yaml
> +  labels:
@Matei207 bump

2018-09-17 08:54 UTC, Matei207 commented
Hi @davidkarlsen, sorry for the long wait, I was on holiday. Thanks for pointing it out to me, I've updated the PR to also include the fix in `secret.yaml`. 

Let me know if there is anything else that's missing!

2018-09-19 20:34 UTC, davidkarlsen approved these changes

2018-09-19 20:34 UTC, davidkarlsen commented
/lgtm

2018-09-19 20:41 UTC, merged