Update Jenkins to Latest LTS fixes #731
helm/charts pull request #733
Opened 2017-02-27 21:18 UTC by jwhitcraft

Also updated the plugins.

2017-02-27 21:21 UTC, jwhitcraft commented
I signed it!

2017-03-10 17:08 UTC, lachie83 commented
@viglesiasce can you confirm if the containers will be automatically built?

2017-03-10 17:08 UTC, lachie83 commented
@k8s-bot ok to test

2017-03-17 01:01 UTC, scottrigby commented
@jwhitcraft Just checking, it looks like `v0.7.0` isn't in the [registry](https://console.cloud.google.com/gcr/images/kubernetes-charts-ci/global/jenkins-master-k8s)?

> Failed to pull image "gcr.io/kubernetes-charts-ci/jenkins-master-k8s:v0.7.0": image pull failed for gcr.io/kubernetes-charts-ci/jenkins-master-k8s:v0.7.0, this may be because there are no credentials on this request. details: (Tag v0.7.0 not found in repository gcr.io/kubernetes-charts-ci/jenkins-master-k8s)
> Error syncing pod, skipping: failed to "StartContainer" for "copy-default-config" with ErrImagePull: "image pull failed for gcr.io/kubernetes-charts-ci/jenkins-master-k8s:v0.7.0, this may be because there are no credentials on this request. details: (Tag v0.7.0 not found in repository gcr.io/kubernetes-charts-ci/jenkins-master-k8s)"

2017-03-17 01:03 UTC, jwhitcraft commented
@scottrigby I don't believe I have access to push that into the repo or even if i should be the one to do it.

Do you know where i can find documentation around it?

2017-03-17 05:38 UTC, seanknox requested changes

2017-03-17 05:38 UTC, seanknox commented on stable/jenkins/values.yaml
> +  ImageTag: "v0.7.0"
I believe v0.6.0 is the latest version of this image (there's no v0.7.0).

2017-03-17 13:24 UTC, jwhitcraft commented
@seanknox and @lachie83 

I just followed what was done in #341 where he updated the Dockerfile and also updated the image.  I'm not sure if @dserodio has access to push the image as well, but if given access i would be more than happy to build the image locally and push it to the registry.

2017-03-17 15:57 UTC, lachie83 commented
@viglesiasce can you let us know the procedure to get a new image pushed to the repo?

2017-03-17 22:09 UTC, scottrigby commented
Yep, I built a [test image](https://hub.docker.com/r/r6by/jenkins/) from the master Dockerfile, and it installed the latest LTS.

We should also update the Jenkins git plugin to latest `3.1.0`. 
<img width="822" alt="screen shot 2017-03-17 at 6 03 24 pm" src="https://cloud.githubusercontent.com/assets/407675/24064705/62453dd6-0b3c-11e7-90fd-8bddba69623d.png">


Of course we'll want to wait for the official image, but here's a diff you can run locally just to see that it works:
```diff
diff --git a/stable/jenkins/master-image/Dockerfile b/stable/jenkins/master-image/Dockerfile
index 5dec9fa..777f5f0 100644
--- a/stable/jenkins/master-image/Dockerfile
+++ b/stable/jenkins/master-image/Dockerfile
@@ -1,4 +1,4 @@
 FROM jenkins:2.32.2
-RUN /usr/local/bin/install-plugins.sh kubernetes:0.11 workflow-aggregator:2.5 credentials-binding:1.10 git:3.0.1 \
+RUN /usr/local/bin/install-plugins.sh kubernetes:0.11 workflow-aggregator:2.5 credentials-binding:1.10 git:3.1.0 \
     && mkdir -p /usr/share/jenkins/ref/secrets/ \
     && echo "false" > /usr/share/jenkins/ref/secrets/slave-to-master-security-kill-switch
diff --git a/stable/jenkins/values.yaml b/stable/jenkins/values.yaml
index eef289b..39facfe 100644
--- a/stable/jenkins/values.yaml
+++ b/stable/jenkins/values.yaml
@@ -5,8 +5,8 @@
 
 Master:
   Name: jenkins-master
-  Image: "gcr.io/kubernetes-charts-ci/jenkins-master-k8s"
-  ImageTag: "v0.7.0"
+  Image: r6by/jenkins
+  ImageTag: "0.1.0"
   ImagePullPolicy: "Always"
   Component: "jenkins-master"
   UseSecurity: true
```

Another interesting note - locally I can see the version is correct, but I still see a UI prompt to download the latest LTS (the one you can see is already installed). Probably unrelated, I just have not seen that before:

<img width="781" alt="screen shot 2017-03-17 at 5 59 58 pm" src="https://cloud.githubusercontent.com/assets/407675/24064762/d231123c-0b3c-11e7-8a78-4504cef90ddc.png">

2017-03-17 22:38 UTC, scottrigby requested changes

2017-03-17 22:38 UTC, scottrigby commented on stable/jenkins/master-image/Dockerfile
> +RUN /usr/local/bin/install-plugins.sh kubernetes:0.11 workflow-aggregator:2.5 credentials-binding:1.10 git:3.0.1 \
Also update to latest jenkins git plugin `git:3.1.0`.

2017-03-20 17:47 UTC, dserodio commented
No @jwhitcraft, my PR refered to a non-existing image and @viglesiasce build and pushed that image afterwards.

2017-03-20 21:47 UTC, seanknox commented on stable/jenkins/values.yaml
> +  ImageTag: "v0.7.0"
@jwhitcraft That image isn't publicly available. Would you be opening a separate PR/issue for that? That'd allow us to merge in the rest of the changes now.

```
$ docker pull gcr.io/kubernetes-charts-ci/jenkins-master-k8s:v0.7.0
Pulling repository gcr.io/kubernetes-charts-ci/jenkins-master-k8s
Tag v0.7.0 not found in repository gcr.io/kubernetes-charts-ci/jenkins-master-k8s
```

2017-03-20 22:07 UTC, jwhitcraft commented on stable/jenkins/values.yaml
> +  ImageTag: "v0.7.0"
@seanknox, the rest of the changes don't make sense without having the updated docker image for the chart to pull down, IMO.

2017-03-20 22:10 UTC, jwhitcraft commented
@dserodio that is what mine does, the 0.7.0 tag currently doesn't exist and i'm just waiting to someone with access to create and push the image up, so that PR can be merged.

2017-03-21 18:13 UTC, seanknox commented
hey @viglesiasce, could you push up `gcr.io/kubernetes-charts-ci/jenkins-master-k8s:v0.7.0`?

2017-03-25 19:13 UTC, scottrigby commented on stable/jenkins/values.yaml
> +  ImageTag: "v0.7.0"
@seanknox Agreed, they are valueless without updating the image. I have spoken with @lachie83 on Slack about the build process, and while I realize automating that with dependable security may be a longer-term effort, the fact that it has taken so long to do a simple image update means perhaps there should be more than one person with ability to do this. I would be happy to do so (as have done in my test image mentioned in [this comment](https://github.com/kubernetes/charts/pull/733#issuecomment-287483737). Is there someone else already on the team who can do this in the meantime, until the build process is reworked?

2017-03-25 19:15 UTC, scottrigby commented on stable/jenkins/master-image/Dockerfile
> +RUN /usr/local/bin/install-plugins.sh kubernetes:0.11 workflow-aggregator:2.5 credentials-binding:1.10 git:3.0.1 \
👍

2017-03-26 07:06 UTC, dtzar commented
If it's open - I'd be game to help move the gcr.io repo for this to an automated public Docker hub build linked to a GitHub repo backed by a community of people who want to support the image/chart to make image updates go quicker/easier...

2017-03-27 14:53 UTC, scottrigby commented
@dtzar I spoke with @lachie83 on Slack, offering a similar thing (it's quite a long conversation, threaded in between others. For anyone interested, [see archives here](https://kubernetes.slack.com/archives/C0NH30761/p1490030121198993)). There is a very easy way to do this in gcr.io (set up a build trigger), but that's not desired by the maintainers.

Tl;dr, The current state is that the CI is being reworked/relocated, so that there is a proper security review for image creation. The last note I made about this. In the meantime people can build the image themselves, or use the image I created and steps mentioned in [my comment above](https://github.com/kubernetes/charts/pull/733#issuecomment-287483737).

2017-03-27 14:55 UTC, scottrigby commented
Also, I agree the image could be built/pushed manually again in the meantime. Given how fast/easy that is to do, it would be a good thing to do for chart adoption even before the CI is reworked.

2017-03-28 17:42 UTC, scottrigby commented
@jwhitcraft Can you also rebase this PR? `Chart.yaml` had an update in the meantime.

2017-03-30 18:08 UTC, viglesiasce commented
I will push this up today.

2017-03-30 18:14 UTC, viglesiasce commented
Image has been pushed. Sorry for the delay.

2017-03-30 21:33 UTC, jwhitcraft commented
We might want to wait to merge this since a new lts was cut today for Jenkins.

2017-03-30 22:44 UTC, dtzar commented
@jwhitcraft you'd have to wait for another image to be pushed, so IMO I'd just make sure the Jenkins Charts e2e passes and ship it.  You could do another PR for the new Jenkins lts :)

2017-03-31 18:21 UTC, jwhitcraft commented
@k8s-bot e2e test this

2017-03-31 18:35 UTC, seanknox approved these changes

2017-03-31 18:36 UTC, seanknox commented
LGTM. Let get this combined labor of love in! @lachie83  @mgoodness

2017-03-31 19:30 UTC, mgoodness commented
Nice work, everyone! Merging.

2017-03-31 19:31 UTC, merged