[stable/grafana] Fix deployment strategy when changing from rollingUpdate
helm/charts pull request #7437
Opened 2018-08-30 08:18 UTC by mtparet

**What this PR does / why we need it**: 
* Deployment is failing when stratey is changed from RollingUpdate to Recreate.
```
"Error: UPGRADE FAILED: Deployment.apps \"grafana\" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'"
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
https://github.com/rancher/rancher/issues/13584#issuecomment-393753794

2018-08-30 10:30 UTC, mtparet commented
cc @rtluckie @zanhsieh

2018-08-30 14:32 UTC, zanhsieh approved these changes

2018-08-30 14:32 UTC, zanhsieh commented
/lgtm

2018-08-30 14:36 UTC, mtparet commented
/assign @scottrigby

2018-09-04 19:46 UTC, davidkarlsen requested changes
@mtparet can you fix the conflict?

2018-09-05 07:59 UTC, mtparet commented
@davidkarlsen conflict fixed :)

2018-09-05 08:15 UTC, davidkarlsen approved these changes

2018-09-05 08:17 UTC, davidkarlsen commented
/lgtm

2018-09-05 12:50 UTC, davidkarlsen commented
rerunning tests after changes
/lgtm cancel
/retest

2018-09-05 12:50 UTC, davidkarlsen commented
/ok-to-test

2018-09-05 12:50 UTC, davidkarlsen commented
/retest

2018-09-05 13:05 UTC, davidkarlsen commented
/lgtm

2018-09-05 13:09 UTC, merged