[stable/mariadb] Feature/allow for existing pvc
helm/charts pull request #7535
Opened 2018-09-04 21:42 UTC by jldeen

**What this PR does / why we need it**:
Allows for users to add existing PVs/PVCs

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Doesn't so much fix an issue, but does allow for users to use the chart with an existing PV/PVC
**Special notes for your reviewer**:

2018-09-04 21:46 UTC, cpanato commented
@jldeen please bump the chart version and sign the DCO

2018-09-04 21:46 UTC, cpanato commented
/assign

2018-09-04 23:33 UTC, jldeen commented
@cpanato Chart version bumped and DCO signed

2018-09-05 08:02 UTC, juan131 requested changes
Please update the README.md file accordingly to the changes you introduced.

Check Redis README.md section for existing claims for instance.

2018-09-05 08:02 UTC, juan131 commented on stable/mariadb/Chart.yaml
> +version: 4.4.1
Increase minor version

2018-09-05 18:24 UTC, jldeen commented on stable/mariadb/README.md
> +| `master.persistence.mountPath`            | Configure existing `PersistentVolumeClaim` mount path  | `""`
readme updated

2018-09-06 10:00 UTC, juan131 commented
/ok-to-test

2018-09-06 10:03 UTC, juan131 approved these changes
Great! Thanks

2018-09-06 11:19 UTC, juan131 commented
/retest

2018-09-06 14:10 UTC, jldeen commented
Believe the failing is related to open [issue #148](https://github.com/bitnami/bitnami-docker-mariadb/issues/148) on the bitnami/bitnami-docker-mariadb repo and is not related to the proposed changes in this PR.

2018-09-07 08:23 UTC, juan131 requested changes
Could you please take a look to my comments?

2018-09-07 08:23 UTC, juan131 commented on stable/mariadb/templates/master-statefulset.yaml
> +      {{- if (.Values.master.persistence.enabled) and (.Values.master.persistence.existingClaim) }}
You're not using **and** correctly. It should be:

```
{{- if and .Values.master.persistence.enabled .Values.master.persistence.existingClaim }}
```

2018-09-07 08:23 UTC, juan131 commented on stable/mariadb/templates/master-statefulset.yaml
> +        - name: {{ .Values.master.persistence.existingClaim | default (include "mariadb.fullname" .) }}
Do not use defaults.

2018-09-07 08:23 UTC, juan131 commented on stable/mariadb/templates/master-statefulset.yaml
> +            claimName: {{ .Values.master.persistence.existingClaim | default (include "mariadb.fullname" .) }}
Do not use defaults.

2018-09-07 13:52 UTC, jldeen commented on stable/mariadb/templates/master-statefulset.yaml
> +      {{- if (.Values.master.persistence.enabled) and (.Values.master.persistence.existingClaim) }}
Corrected in latest push

2018-09-07 13:52 UTC, jldeen commented on stable/mariadb/templates/master-statefulset.yaml
> +        - name: {{ .Values.master.persistence.existingClaim | default (include "mariadb.fullname" .) }}
Corrected in latest push

2018-09-07 13:53 UTC, jldeen commented on stable/mariadb/templates/master-statefulset.yaml
> +            claimName: {{ .Values.master.persistence.existingClaim | default (include "mariadb.fullname" .) }}
Corrected in latest push

2018-09-07 13:56 UTC, jldeen commented
Hi @juan131 

I have made the proposed changes.

2018-09-07 13:56 UTC, jldeen commented
/retest

2018-09-10 09:31 UTC, merged