[stable/openiban] Add OpenIBAN chart
helm/charts pull request #7536
Opened 2018-09-04 22:58 UTC by verwilst

Signed-off-by: Bart Verwilst <bart@verwilst.be>

**What this PR does / why we need it**: Add OpenIBAN chart

2018-09-04 23:01 UTC, verwilst commented
/assign davidkarlsen

2018-09-04 23:01 UTC, verwilst commented
/assign lachie83

2018-09-05 12:52 UTC, davidkarlsen requested changes

2018-09-05 12:52 UTC, davidkarlsen commented on stable/openiban/templates/deployment.yaml
> +    app: {{ template "openiban.name" . }}
use updated labels best practices: https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md (for all resources)

2018-09-05 12:53 UTC, davidkarlsen commented
/ok-to-test

2018-09-05 13:07 UTC, davidkarlsen commented on stable/openiban/templates/deployment.yaml
> +    app: {{ template "openiban.name" . }}
Let's see what comes out of https://github.com/helm/charts/issues/7550

2018-09-10 07:29 UTC, verwilst commented
Could this be merged since #7550 is quite dormant.

2018-09-10 20:32 UTC, davidkarlsen commented on stable/openiban/templates/deployment.yaml
> +    app: {{ template "openiban.name" . }}
No response on that - so let's keep it

2018-09-10 20:32 UTC, davidkarlsen commented on stable/openiban/Chart.yaml
> +version: 0.1.0
go straight for 1.0.0 since we're in stable?

2018-09-10 20:35 UTC, davidkarlsen commented on stable/openiban/Chart.yaml
> +appVersion: 1.0.0
image is 1.0.1?

2018-09-10 20:50 UTC, davidkarlsen commented
/lgtm

2018-09-10 20:50 UTC, davidkarlsen approved these changes

2018-09-11 19:36 UTC, merged