Allow service labels of jenkins to be configurable
helm/charts pull request #7547
Opened 2018-09-05 11:43 UTC by waseem-h

**What this PR does / why we need it**:
This PR allows us to add custom labels on jenkins service. This is needed for some kubernetes controllers like `exposecontroller` which looks for a specific label on services and exposes ingress if that label has a specific value.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
None
**Special notes for your reviewer**:
It would be great if this PR could be merged quickly. Thanks

2018-09-05 13:13 UTC, davidkarlsen requested changes

2018-09-05 13:13 UTC, davidkarlsen commented on stable/jenkins/Chart.yaml
> +version: 0.17.1
new feature - use version 0.18.0

2018-09-05 13:14 UTC, davidkarlsen commented
/ok-to-test

2018-09-12 08:55 UTC, kahootali commented
@davidkarlsen made the changes, kindly review it

2018-09-24 06:39 UTC, waseem-h commented
Can you please review? @davidkarlsen I've made the changes requested

2018-11-07 08:06 UTC, closed without merging