[stable/rabbitmq-ha] Add custom definitions
helm/charts pull request #7571
Opened 2018-09-06 11:07 UTC by didjcodt

Since v1.9.0, a definitions.json file have been created, needed for users
creation for health check, prometheus, etc.
It is thus impossible to get these features using a custom definitions.json
This commit allows you to add :
 - Users
 - Vhosts
 - Permissions
 - Policies (already present, just moved)
 - Queues
 - Exchanges
 - Bindings

Signed-off-by: Clement Decoodt <clement@decoodt.eu>

Chart maintainer: @etiennetremel 

**Which issue this PR fixes**: fixes #7553

2018-09-06 20:29 UTC, steven-sheehy requested changes

2018-09-06 20:29 UTC, steven-sheehy commented on stable/rabbitmq-ha/README.md
> +| `definitions.policies`                         | HA policies to add to definitions.json | `{}` |
Changing the path of policies breaks existing users, so chart version should see a minor version increase to 1.10.0.

2018-09-06 20:29 UTC, steven-sheehy commented on stable/rabbitmq-ha/values.yaml
> +#     "name": "/"
There's already a vhost and permission for / present in the definitions. It would be more accurate and less confusing to show a different vhost name being added as an example.

2018-09-06 20:29 UTC, steven-sheehy commented on stable/rabbitmq-ha/README.md
> +| `definitions.users`                            | Additional users | `{}` |
The default values for all these should be empty string since the values are actually a string containing json, not a yaml map.

2018-09-06 20:29 UTC, steven-sheehy commented on stable/rabbitmq-ha/templates/_helpers.tpl
> +  ]{{- if .Values.definitions.policies -}},
I think it's cleaner the way it was before to have an empty policies array if `.Values.policies` is empty versus having the if statements. I don't think it causes any issues in rabbitmq to list all the keys whether their contents are empty or not.

2018-09-06 20:36 UTC, didjcodt commented on stable/rabbitmq-ha/README.md
> +| `definitions.policies`                         | HA policies to add to definitions.json | `{}` |
Would you prefer to keep the policies path as before?

2018-09-06 20:39 UTC, didjcodt commented on stable/rabbitmq-ha/templates/_helpers.tpl
> +  ]{{- if .Values.definitions.policies -}},
Should I do the same as what did `policies` before with the other fields or let it like that? It does not cause any issues (I added these statements to get a nicely readable rendered file, at the price of a not-that-nicely readable template :))

2018-09-06 20:45 UTC, steven-sheehy commented on stable/rabbitmq-ha/templates/_helpers.tpl
> +  ]{{- if .Values.definitions.policies -}},
I think it's still nicely rendered even if it's an empty array, so the old approach would be preferred. E.g.
```json
"policies" : [],
"queues" : [],
...
```

2018-09-06 20:49 UTC, didjcodt commented on stable/rabbitmq-ha/templates/_helpers.tpl
> +  ]{{- if .Values.definitions.policies -}},
Ok. Are there any other items I should add in the definitions?

2018-09-06 20:52 UTC, steven-sheehy commented on stable/rabbitmq-ha/templates/_helpers.tpl
> +  ]{{- if .Values.definitions.policies -}},
I think there's also a parameters section that can be added to the definitions. Please double check

2018-09-06 20:54 UTC, steven-sheehy commented on stable/rabbitmq-ha/README.md
> +| `definitions.policies`                         | HA policies to add to definitions.json | `{}` |
I don't have a strong opinion either way. One could argue the fact that they're stored in a definitions.json is an implementation detail and not relevant for the helm chart user. You may still need a minor version increment anyway due to new features being added, but lets let helm chart maintainers weigh in on that.

2018-09-07 08:22 UTC, kaizensparc commented on stable/rabbitmq-ha/templates/_helpers.tpl
> +  ]{{- if .Values.definitions.policies -}},
I added the parameters section support. I cannot find any schema or template of a full `definitions.json` file on the internet, so I cannot figure out if there are others (in the examples I found, the only lacking item was the `parameters`). Hope it's ok.

Now the default rendered file looks like this:
```json
{
  "users": [
    {
      "name": "management",
      "password": "E9R3fjZm4ejFkVFE",
      "tags": "management"
    },
    {
      "name": "guest",
      "password": "4LJFVHDVnY2G9252D1gb5VO2",
      "tags": "administrator"
    }
  ],
  "vhosts": [
    {
      "name": "/"
    }
  ],
  "permissions": [
    {
      "user": "guest",
      "vhost": "/",
      "configure": ".*",
      "read": ".*",
      "write": ".*"
    }
  ],
  "parameters": [

  ],
  "policies": [

  ],
  "queues": [

  ],
  "exchanges": [

  ],
  "bindings": [

  ]
}
```

2018-09-07 08:23 UTC, kaizensparc commented on stable/rabbitmq-ha/README.md
> +| `definitions.users`                            | Additional users | `{}` |
Done, it's now 
```
`""`
```

2018-09-07 08:24 UTC, kaizensparc commented on stable/rabbitmq-ha/values.yaml
> +#     "name": "/"
I made a `/rabbit` vhost. Hope it is not ambiguous.

2018-09-07 08:26 UTC, didjcodt commented on stable/rabbitmq-ha/README.md
> +| `definitions.policies`                         | HA policies to add to definitions.json | `{}` |
Ok. I keep it like this, waiting for further discussion to know if I increase version to `1.10.0` or if I put back the policies element in the root values. RFC.

2018-09-07 16:03 UTC, steven-sheehy commented
/assign @davidkarlsen

2018-09-14 15:26 UTC, steven-sheehy commented on stable/rabbitmq-ha/README.md
> +| `definitions.policies`                         | HA policies to add to definitions.json | `{}` |
rabbitmq-ha chart 1.10.0 is now released, so you'll need to bump to fix conflict. I think you can keep as definitions.* but bump chart to 1.11.0.

2018-09-14 15:37 UTC, didjcodt commented on stable/rabbitmq-ha/README.md
> +| `definitions.policies`                         | HA policies to add to definitions.json | `{}` |
I just bumped to `1.11.0`

2018-09-24 19:47 UTC, steven-sheehy commented
@didjcodt You might want to try assigning to some other reviewers to get this moving.

2018-09-27 09:13 UTC, didjcodt commented
/assign gabrtv

2018-09-27 09:15 UTC, cpanato commented
/ok-to-test

2018-09-27 09:30 UTC, didjcodt commented
/test pull-charts-e2e

2018-10-02 09:39 UTC, marcinbojko commented
Hi guys. Any chance to merge this PR soon? It would spare us a lots of import/export stuff.

2018-10-09 13:52 UTC, etiennetremel approved these changes
LGTM, thanks!

2018-10-12 14:36 UTC, marcinbojko commented
Are we missing some abels @etiennetremel ? Can't see it merged.

2018-10-13 11:18 UTC, unguiculus commented
/lgtm

2018-10-13 11:31 UTC, didjcodt commented
@unguiculus It seems the 1.11.0 version of the chart was out, so I just rebased from master and bumped the version to 1.12.0.

2018-10-15 07:31 UTC, didjcodt commented
Rebased to solve version conflict on `Chart.yaml`

2018-10-16 07:34 UTC, cpanato commented
/lgtm

2018-10-16 07:43 UTC, merged