[stable/filebeat] raised filebeat version to 6.4.0
helm/charts pull request #7676
Opened 2018-09-11 20:06 UTC by monotek

**What this PR does / why we need it**:
* raises filebeat version to 6.4.0

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2018-09-11 20:07 UTC, davidkarlsen commented
/ok-to-test
/assign

2018-09-11 20:07 UTC, monotek commented
/assign @seanknox

2018-09-11 20:12 UTC, davidkarlsen requested changes

2018-09-11 20:12 UTC, davidkarlsen commented on stable/filebeat/Chart.yaml
>  version: 1.0.0
please bump the chart version too

2018-09-11 20:13 UTC, davidkarlsen requested changes

2018-09-11 20:13 UTC, davidkarlsen commented on stable/filebeat/values.yaml
> +  tag: 6.4.0
please also update readme to match

2018-09-12 08:29 UTC, monotek commented on stable/filebeat/values.yaml
> +  tag: 6.4.0
readme was already changed ;-)

2018-09-12 08:29 UTC, monotek commented on stable/filebeat/Chart.yaml
>  version: 1.0.0
done :-)

2018-09-13 21:01 UTC, monotek commented
/assign @davidkarlsen

2018-09-13 21:08 UTC, davidkarlsen approved these changes

2018-09-13 21:09 UTC, davidkarlsen commented
/lgtm

2018-09-13 21:15 UTC, merged