Adding node-problem-detector stable chart
helm/charts pull request #7795
Opened 2018-09-18 14:44 UTC by max-rocket-internet

I would like to add a chart for the node-problem-detector:
https://github.com/kubernetes/node-problem-detector

This tool is already in the [cluster addons repo](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/node-problem-detector) for some time now.

2018-09-18 14:49 UTC, max-rocket-internet commented
/assign @unguiculus

2018-10-02 08:47 UTC, max-rocket-internet commented
Any update @unguiculus ?

Or perhaps someone else? @scottrigby or @mgoodness or @davidkarlsen or @prydonius

2018-10-06 19:54 UTC, unguiculus commented
Please compare with what you get from `helm create` using latest Helm and update accordingly. Make sure you follow our review guidelines and please apply our RBAC best practices.

https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md
https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md

2018-10-08 08:58 UTC, max-rocket-internet commented
Hi @unguiculus!

`helm create` is not listed anywhere in the [Contributing Guidelines](https://github.com/helm/charts/blob/master/CONTRIBUTING.md). Nevertheless, I've run this command and compared it to what I have already. As such, I've added:
- Added `affinity` option
- Added `.helmignore` file
- `nameOverride` and `fullnameOverride` options
- Changed all labels

Would be cool if `helm create` produced the RBAC files.

It also seems to remove the `app` and `chart` labels and replaced it with `app.kubernetes.io/name` and `helm.sh/chart` which kind of breaks backwards compatibility? I've included both. Is that OK? This is confusing TBH.

> Make sure you follow our review guidelines

✅

> please apply our RBAC best practices.

OK I added a conditional around the service account and the `serviceAccountName` helper. I've compared it to 2 other popular charts, I think it's in line now.

2018-10-13 11:26 UTC, unguiculus requested changes
There is a new convention for standard labels in Kubernetes land which Helm now follows. Please remove the old labels. Since this is a new chart, there are no backwards compatibility issues at all and we should follow the new convention.

2018-10-13 11:26 UTC, unguiculus commented on stable/node-problem-detector/templates/clusterrolebinding.yaml
> +  name: {{ template "node-problem-detector.fullname" . }}
`node-problem-detector.serviceAccountName`

2018-10-13 11:26 UTC, unguiculus commented on stable/node-problem-detector/templates/daemonset.yaml
> +apiVersion: extensions/v1beta1
Use `apps/v1`

2018-10-13 11:26 UTC, unguiculus commented on stable/node-problem-detector/README.md
> +| `tolerations`                      | Optional daemonset tolerations  | `{}`                                                        |
The config table in incomplete.

2018-10-13 11:26 UTC, unguiculus commented on stable/node-problem-detector/values.yaml
> +resources:
Con' specify defaults for resources. Comment them out.

2018-10-13 11:26 UTC, unguiculus commented on stable/node-problem-detector/values.yaml
> +tolerations: {}
`tolerations: []`

2018-10-15 09:07 UTC, max-rocket-internet commented
@unguiculus 

> There is a new convention for standard labels in Kubernetes land which Helm now follows. Please remove the old labels.

OK understood. I was copying older charts. Now all fixed.

2018-10-29 15:00 UTC, max-rocket-internet commented
Any update @unguiculus ?

2018-10-31 18:29 UTC, unguiculus requested changes

2018-10-31 18:29 UTC, unguiculus commented on stable/node-problem-detector/README.md
> +- Kubernetes 1.8+ with Beta APIs enabled
Should probably be 1.9+

2018-10-31 18:29 UTC, unguiculus commented on stable/node-problem-detector/templates/_helpers.tpl
> +{{- define "node-problem-detector.labels" }}
Not used. Remove it.

2018-11-01 09:06 UTC, max-rocket-internet commented
@unguiculus all done! Please re-review.

2018-11-01 21:31 UTC, unguiculus commented
/ok-to-test

2018-11-01 21:44 UTC, unguiculus commented
/lgtm

2018-11-01 21:52 UTC, merged