Enhanced ingress configuration on anchore-engine chart
helm/charts pull request #7798
Opened 2018-09-18 16:20 UTC by mvisonneau

**What this PR does / why we need it**:

This PR allows a better way of managing ingress configuration of the ingress for the `anchore-engine` chart.

2018-09-18 22:02 UTC, zhill commented
Hi @mvisonneau, I should have time to review this today or tomorrow and will update then. Just letting you know that it's on my radar and I'll get to it very soon. Thanks!

2018-09-20 07:42 UTC, zhill commented
/ok-to-test

2018-09-21 17:23 UTC, zhill requested changes
Found a couple of small issues, so I think it would help if you describe the use-case you're trying to address with this PR. I'm all for added config and flexibility but also want to ensure we can support a simple deployment. Specifically, using the ingress For example, I'm not sure what the use-case is for supporting multiple hosts since this maps to a single backend. Can you provide a bit more context please?

2018-09-21 17:23 UTC, zhill commented on stable/anchore-engine/templates/ingress.yaml
> +{{- $servicePort := .Values.service.port -}}
I think this should be ".Values.service.ports.api". As is, the servicePort for the backend entry is empty.

2018-09-21 17:23 UTC, zhill commented on stable/anchore-engine/values.yaml
> +  hosts:
From my initial testing, if you leave hosts empty, the ingress won't deploy, which I think would be a use-case for a user that just wants simple SSL termination. I don't think a host entry should be a requirement for the ingress, but certainly should be supported.

2018-09-21 21:08 UTC, mvisonneau commented
👋 thanks for the review @zhill. I updated accordingly and answered specific points under your comments.

2018-09-25 16:31 UTC, zhill commented
/lgtm

2018-09-25 16:40 UTC, merged