[stable/rabbimq] Improve consistensy for persistent storage
helm/charts pull request #7807
Opened 2018-09-19 00:30 UTC by dene14

**What this PR does / why we need it**:
- adds headless service
- adds an ability to switch address_type for k8s clustering helper
- makes persistent storage more consistent/persistent since all the data dirs/files named not by pod's IP address but by pod's name which is consistent in a statefulset

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #7806

**Special notes for your reviewer**:
I've tested many different approaches to implement that, the one proposed though doesn't require any immediate changes to docker image et al.

@bitnami-bot

2018-09-19 00:34 UTC, dene14 commented
/assign @sameersbn

2018-09-19 12:57 UTC, f84anton commented
I'm facing same issue with mnesia storage path:

```# ls -l ./mnesia/
total 24
drwxr-sr-x  3 1001 1001 4096 Sep 18 09:20 rabbit@10.233.89.81
drwxr-sr-x 10 1001 1001 4096 Sep 13 14:52 rabbit@10.233.89.81-plugins-expand
-rw-r--r--  1 1001 1001    2 Sep 13 14:52 rabbit@10.233.89.81.pid
drwxrwsr-x  3 1001 1001 4096 Sep 12 22:21 rabbit@10.233.89.88
drwxrwsr-x 10 1001 1001 4096 Sep  5 11:39 rabbit@10.233.89.88-plugins-expand
-rw-rw-r--  1 1001 1001    2 Sep  5 11:38 rabbit@10.233.89.88.pid```

Messages are lost every time the pod recreates.

I think rabbitmq.clustering.address_type must be set to `hostname` by default.

@dene14, you'd better prepare separate pull requests for each problem.

2018-09-19 16:28 UTC, dene14 commented
I've made it so that old behaviour used by default, switch isn't seamless unfortunately. People will definitely lose their schemas during upgrade if they haven't noticed the loss earlier. But I definitely agree that hostname should be default behaviour for that chart in the future

@f84anton  I'm not sure how do you expect it in multiple pull requests. The main thing I was fixing is hostname based clustering - this requires all the changes I've done in that pull request. I just have few benefits in one solution and I described it in details so that maintainers can properly assess the value.

2018-09-25 09:40 UTC, tompizmor requested changes

2018-09-25 09:40 UTC, tompizmor commented on stable/rabbitmq/templates/statefulset.yaml
> +            value: "rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local"
I would also parametrize the `cluster.local` domain in case someone has a cluster domain different to the default one

2018-09-25 09:40 UTC, tompizmor commented on stable/rabbitmq/templates/statefulset.yaml
> +            value: {{ default "ip" .Values.rabbitmq.clustering.address_type }}
using a `default` value in the template is not recommended. The default value should come from the `values.yaml` file

2018-09-25 09:41 UTC, tompizmor commented
@dene14 can you also fix the conflicts in Chart.yaml and README.md?

2018-10-03 12:11 UTC, dene14 commented
@tompizmor Adjusted, please review.

2018-10-04 09:20 UTC, tompizmor commented
/ok-to-test

2018-10-04 10:15 UTC, tompizmor commented
From the pull-charts-e2e job:

```
W1004 09:21:14.562] ERROR: Chart version not ok. Needs a version bump.
W1004 09:21:15.484] ERROR: Chart validation failed.
```

The rabbitmq chart has had another update so it seems you need to update the version again 😬

2018-10-04 11:46 UTC, dene14 commented
/retest

2018-10-04 11:50 UTC, dene14 commented
@tompizmor  @prydonius @juan131 @sameersbn 
Can we merge this?

2018-10-04 15:09 UTC, tompizmor commented
/lgtm

2018-10-04 15:11 UTC, merged

2018-10-09 12:32 UTC, desaintmartin commented
This is a breaking change, needing to manually delete the existing rabbitmq StatefulSet when upgrading. It should have been bumping major version.

https://github.com/helm/charts/pull/7807/files#diff-1e6c6c83dddf5c9d0e6789776eb17f8eR11

2018-10-09 13:45 UTC, dene14 commented
There was some back and force increasing the version. Not sure what we'll do now...
Also, I was like 1 week late late with my merge since major version was bumped from 2.x.x to 3.x.x