Add Couchbase chart
helm/charts pull request #786
Opened 2017-03-13 20:12 UTC by julienstroheker

2017-03-13 20:20 UTC, julienstroheker commented
Page not found to sign the CLA : https://identity.linuxfoundation.org/projects/cncf

2017-03-13 20:26 UTC, julienstroheker commented
I signed it!

2017-05-03 22:18 UTC, viglesiasce commented
@k8s-bot ok to test

2017-05-03 22:27 UTC, viglesiasce requested changes

2017-05-03 22:27 UTC, viglesiasce commented on incubator/couchbase/templates/NOTES.txt
> +Default Username : Administrator / Password : password
Can you add port forwarding instructions here. A good example is the Jenkins NOTES.txt:

https://github.com/kubernetes/charts/blob/master/stable/jenkins/templates/NOTES.txt

2017-05-03 22:27 UTC, viglesiasce commented on incubator/couchbase/templates/svc.yaml
> +  type: LoadBalancer
Make this configurable and default it to ClusterIP. Especially since the username and password are easily guessable and static.

2017-05-03 22:27 UTC, viglesiasce commented on incubator/couchbase/values.yaml
> +# couchbaseRootPassword: ## Default: random 10 character string
These 2 don't appear to be used anywhere.

2017-05-03 22:27 UTC, viglesiasce commented on incubator/couchbase/values.yaml
> +  storageClass: fast
Do not set a storage class by default to ensure that the default storage class for the cluster is used.

2017-05-03 22:27 UTC, viglesiasce commented on incubator/couchbase/templates/couchbase-master-statefulset.yaml
> +    spec:
It doesnt appear that this master stateful set is using any persistence. Shouldn't it be?

2017-05-03 22:27 UTC, viglesiasce commented on incubator/couchbase/templates/_helpers.tpl
> +{{- printf "%s-%s" .Release.Name $name | trunc 24 | trimSuffix "-" -}}
Truncation should be 63 in both of these cases.

2017-05-03 22:28 UTC, viglesiasce requested changes

2017-05-03 22:28 UTC, viglesiasce commented on incubator/couchbase/templates/couchbase-master-statefulset.yaml
> +        image: couchbase/server:sandbox
This should be configurable in the values file

2017-05-03 22:28 UTC, viglesiasce commented on incubator/couchbase/templates/couchbase-worker-statefulset.yaml
> +        image: couchbase/server:sandbox
This should be configurable in the values file

2017-05-10 22:18 UTC, viglesiasce commented
@julienstroheker ping

2017-06-01 05:56 UTC, viglesiasce commented
Closing as this has been stale for more than a week:
https://github.com/kubernetes/charts#stale-pull-requests

2017-06-01 05:56 UTC, closed without merging

2018-10-08 01:13 UTC, ozbillwang commented
@julienstroheker 

Could you re-raise this PR and get it merged? 

thanks a lot.