Add RootCAs as a configurable value to Traefik chart
helm/charts pull request #7877
Opened 2018-09-21 03:58 UTC by rafaelmagu

**What this PR does / why we need it**: It allows a user of the Traefik chart to specify one or more custom certificate authorities to use when connecting to TLS-encrypted backends.

2018-09-23 21:19 UTC, rafaelmagu commented
Something that's a bit unclear to me is the format that `rootCAs` takes when specifying certificates inline. Attempting to add the base64-encoded certificate yields:

```
2018/09/23 21:07:19 Error reading TOML config file /config/traefik.toml : toml: cannot load TOML value of type string into a Go boolean
```

2018-10-05 17:29 UTC, dtomcej requested changes
Can you please bump the chart in addition?

2018-10-05 17:29 UTC, dtomcej commented on stable/traefik/values.yaml
> +rootCAs: []
This should be commented out by default :)

2018-10-05 23:45 UTC, rafaelmagu commented
@dtomcej thank you for the feedback. Rebased and signed off with the change and a bump.

2018-10-05 23:59 UTC, dtomcej commented
/approve

2018-10-06 00:00 UTC, dtomcej approved these changes

2018-10-06 00:00 UTC, dtomcej commented
/lgtm

2018-10-06 00:00 UTC, dtomcej commented
/ok-to-test

2018-10-06 00:06 UTC, merged