[stable/phpMyAdmin] Add nodeSelector, tolerations and affinity for phpMyAdmin
helm/charts pull request #7884
Opened 2018-09-21 09:14 UTC by antoine-rehm

**What this PR does / why we need it**: In order to make pod assignment works

**Special notes for your reviewer**: N/A

_Relevant maintainers:_ @prydonius @tompizmor @sameersbn @carrodher @juan131

2018-09-21 09:21 UTC, cpanato commented on stable/phpmyadmin/Chart.yaml
> +version: 1.0.1
New features plese bump to `1.1.0`

2018-09-21 12:14 UTC, davidkarlsen commented
/ok-to-test

2018-09-21 14:25 UTC, sameersbn commented on stable/phpmyadmin/README.md
> +Use the workaround below to upgrade from versions previous to `1.1.0`. The following example assumes that the release name is `phpmyadmin`:
@antoine-rehm  is this change intended?

2018-09-21 14:35 UTC, antoine-rehm commented on stable/phpmyadmin/README.md
> +Use the workaround below to upgrade from versions previous to `1.1.0`. The following example assumes that the release name is `phpmyadmin`:
no sorry i'm going to correct that

2018-09-24 09:49 UTC, juan131 requested changes

2018-09-24 09:49 UTC, juan131 commented on stable/phpmyadmin/README.md
> +### To 1.1.0
Please do not bump the version here. The workaround shown below is to update from **0.x.x to 1.0.0**. Once you're on **1.0.0** you don't need to do it to upgrade to **1.1.0**

2018-09-24 15:02 UTC, juan131 commented
/lgtm

2018-09-24 15:07 UTC, merged