add grpc-http-proxy chart
helm/charts pull request #7976
Opened 2018-09-26 04:16 UTC by vbanthia

#### What this PR does / why we need it:
Add [grpc-http-proxy](https://github.com/mercari/grpc-http-proxy) chart

#### Special notes for your reviewer:
N/A

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-09-26 05:26 UTC, vbanthia commented
/assign @davidkarlsen

2018-09-28 15:36 UTC, vbanthia commented
@davidkarlsen  Could you look this PR.

2018-09-29 16:47 UTC, davidkarlsen commented
@vbanthia Please aim straight for the stable repo with a 1.0.0 version

2018-09-29 16:49 UTC, davidkarlsen requested changes

2018-09-29 16:49 UTC, davidkarlsen commented on incubator/grpc-http-proxy/templates/deployment.yaml
> +    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
please add labels like described here: https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md

2018-09-29 16:49 UTC, davidkarlsen commented on incubator/grpc-http-proxy/templates/deployment.yaml
> +    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
please add rbac as described here: https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md

2018-10-29 22:36 UTC, closed without merging