Expose more minecraft options
helm/charts pull request #8025
Opened 2018-09-28 02:54 UTC by mcronce

**What this PR does / why we need it**:  The current chart is missing some of the options available in [the underlying container image](https://hub.docker.com/r/itzg/minecraft-server) - this PR adds them; at least, I think I got them all

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4766

**Special notes for your reviewer**:
This was originally submitted in #5036 - it went stale and was closed, though, and I didn't notice until now.

2018-09-28 03:11 UTC, mcronce commented
/assign @viglesiasce

2018-09-28 17:58 UTC, paulczar commented
/ok-to-test

2018-09-28 18:33 UTC, mcronce commented
@paulczar Thank you

2018-10-01 19:23 UTC, viglesiasce requested changes

2018-10-01 19:23 UTC, viglesiasce commented on stable/minecraft/Chart.yaml
> +version: 0.2.3
Bump to 0.3.0

2018-10-01 19:36 UTC, mcronce commented on stable/minecraft/Chart.yaml
> +version: 0.2.3
Done...waiting on tests to rerun now

2018-10-01 19:41 UTC, viglesiasce approved these changes

2018-10-01 19:41 UTC, viglesiasce commented
/lgtm

2018-10-01 19:42 UTC, merged