Prometheus Node Exporter
helm/charts pull request #803
Opened 2017-03-16 18:38 UTC by kfox1111

Adds a chart for managing the Prometheus Node Exporter as a
Daemonset.

2017-03-21 11:03 UTC, sstarcher commented
Do we want a separate node exporter chart now that the prometheus chart will have the node exporter?

https://github.com/kubernetes/charts/pull/627

Or should #627 be updated to reference this as a dependency.

2017-03-21 13:35 UTC, mgoodness commented
@sstarcher The current plan is to get #627 merged, followed by all of the stand-alone components, then refactor using dependencies.

2017-03-21 13:49 UTC, sstarcher commented
Sounds awesome, keep up the good work

2017-03-22 16:29 UTC, kfox1111 commented
Having it separate allows the user to configure versions of the node exporter differently depending on the needs of various pools of hardware.

If the long term goal is to split it out anyway, why not just drop support for the node exporter in the new Prometheus chart for now, and we can work on getting it fixed up here?

That does raise another discussion point. There are kind of two use cases for charts that we've hit for Kolla-Kubernetes. Charts to do one thing, such as a node exporter or a Prometheus server, and there are charts that are for deploying more complex systems, such as a "prometheus + common exporters" group of charts.
How are we going to handle the group use case in kubernetes/charts?

2017-03-22 21:59 UTC, mgoodness commented
> If the long term goal is to split it out anyway, why not just drop support for the node exporter in the new Prometheus chart for now, and we can work on getting it fixed up here?

#627 was already at the end of its review, while this one (and the other components) have yet to begin. I wanted to get something out there for people to use.

> How are we going to handle the group use case in kubernetes/charts?

I expect to see most multi-component charts broken up into individual ones and new "umbrella" versions created that allow specific dependencies to be enabled or disabled by the end-user. Ultimately more charts, but smaller and more flexible ones.

2017-03-22 22:04 UTC, kfox1111 commented
Sounds good. If there are no more revisions of the other chart, and its to merge quickly, then yeah, we can just let it go through and then in a follow on pr, pull it back out. Though arguably that may break compatibility. Is there a policy there about backwards compatibility?

yeah. umbrella charts. thats a good way of putting it. So, would 'prometheus' become an an umbrella chart under stable, would just the server bits become prometheus-server? or would prometheus be just the server bits and an umbrella chart somewhere else would also be called prometheus or maybe prometheus-all or something?

2017-03-22 22:52 UTC, mgoodness commented
> Is there a policy there about backwards compatibility?

We don't have a policy beyond "use SemVer correctly". I'd personally (and generally) like to see backwards compatibility retained unless there's a compelling reason not to.

> umbrella charts

I _think_ the `prometheus` chart wants to define the `server` component, with alertmanager, node exporter, cloudwatch exporter, kube-state-metrics, etc. as optional dependencies. The idea being anyone who wants to install just prometheus can use that chart with everything else disabled. But if they want the kitchen sink, they can enable it all.

2017-03-22 23:31 UTC, kfox1111 commented
So, prometheus would be the umbrella chart sort of and the primary chart for the server? Which way would it default? everything else disabled or enabled?

2017-03-22 23:40 UTC, mgoodness commented
Turning everything else off seems like the best (only?) way to avoid a fight over what should be enabled and what shouldn't. Also, Prometheus configuration is so widely variable that I doubt anyone deploys it without some customization anyway.

2017-03-23 19:26 UTC, kfox1111 commented
the other route is to have 2 charts. one for just prometheus server bits, and one for everything. Then if all you want is prometheus, you just use the server only version. Lets you more easily embed it in other charts maybe?

2017-05-18 16:06 UTC, prydonius commented
ping @mgoodness

2017-05-24 22:50 UTC, kfox1111 commented
So, whats the path forward here?

2017-05-30 20:39 UTC, mgoodness commented
@kfox1111 I'd like to see the PR updated to use the existing `stable/prometheus/templates/node-exporter-*` manifests as the basis for this chart. That'll make it easier for us to pull those manifests out and drop this in as an (optional) dependency.

2017-05-31 23:48 UTC, kfox1111 commented
@mgoodness 
so, I'm hitting an issue with that which I was a afraid of  before letting it merge as it was.

The whole node-exporter thing could be lifted out as its own chart, and then using local path deps pulled back into the prometheus chart with a conditional include to get back to the existing functionality.

But there's a problem. Convention. the package should be named node-exporter by convention but the section name established in the values file is nodeExporter by value convention. The only renaming thing I could find was alias but doesn't allow you to rename, just add more things.

I'm also struggling with getting my prometheus systems that were installed with the previous version of the chart to the new version. a lot has changed. :/

So getting it to the point I can contribute is a bit hard now. I'm working on it though.

should we just rename the section node-exporter, or should we try and land a feature in helm that would allow renaming the section of values.yaml the subchart reads? @technosophos (you might be interested in this too) This may become a more common issue as subcharts are created from primary charts when following established naming conventions.

2017-07-20 18:53 UTC, unguiculus commented
ping @mgoodness

2017-09-01 18:55 UTC, kfox1111 commented
I've split out the bits that are in the Prometheus chart out verbatim:
https://github.com/kubernetes/charts/pull/1886

Once that lands we can merge the couple of extra tweaks I've done in this pr?

2018-01-13 15:15 UTC, unguiculus requested changes
Thanks for the PR. Please read our review guidelines and follow best practices.

https://github.com/unguiculus/charts/blob/master/REVIEW_GUIDELINES.md

2018-01-13 15:15 UTC, unguiculus commented on stable/node-exporter/Chart.yaml
> +  - name: Kevin Fox
Use Github username

2018-01-13 15:15 UTC, unguiculus commented on stable/node-exporter/templates/daemonset.yaml
> +apiVersion: extensions/v1beta1
`apps/v1beta2`

2018-01-13 15:15 UTC, unguiculus commented on stable/node-exporter/templates/daemonset.yaml
> +        image: "{{default "quay.io/prometheus/node-exporter" .Values.image}}:{{default "v0.13.0" .Values.imageTag}}"
Don't use `default` function if not necessary. Defaults should go into `values.yaml`.

2018-01-13 15:15 UTC, unguiculus commented on stable/node-exporter/templates/_helpers.tpl
> +{{/* vim: set filetype=mustache: */}}
Use `_helpers.tpl` you get with `helm create`

2018-01-13 15:15 UTC, unguiculus commented on stable/node-exporter/values.yaml
> +Name: node-exporter
Remove this.

2018-01-13 15:15 UTC, unguiculus commented on stable/node-exporter/templates/daemonset.yaml
> +  name: {{template "fullname" .}}
Use consistent formatting: Space after `{{` and  before `}}`.

2018-01-13 15:20 UTC, unguiculus commented
Just realized there's also #1886. It his one obsolete now?

2018-01-15 17:23 UTC, kfox1111 commented
Yeah, #1886 is the one that was pulled back out of the merged code base. its closer to trunk so probably the better one to adopt.

2018-01-15 17:23 UTC, closed without merging