Prometheus Ceph Exporter
helm/charts pull request #804
Opened 2017-03-16 19:10 UTC by kfox1111

Adds Prometheus support for gathering metrics from Ceph.

2017-05-18 16:06 UTC, prydonius commented
ping @mgoodness

2017-05-31 23:36 UTC, kfox1111 commented
ping

2017-07-20 19:03 UTC, unguiculus requested changes
Thanks for your PR. Sorry for the late feedback.

2017-07-20 19:03 UTC, unguiculus commented on stable/ceph-exporter/Chart.yaml
> +version: 1.0.0
Add `appVersion`.

2017-07-20 19:03 UTC, unguiculus commented on stable/ceph-exporter/Chart.yaml
> +  - name: Kevin Fox
Use Github username.

2017-07-20 19:03 UTC, unguiculus commented on stable/ceph-exporter/templates/deployment.yaml
> +  name: {{template "fullname" .}}
Use consistent formatting throughout the chart:
Space after `{{` and before `}}`.

2017-07-20 19:03 UTC, unguiculus commented on stable/ceph-exporter/templates/deployment.yaml
> +        app: {{template "fullname" .}}
Please apply best practices for labels: https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/labels.md
Note that you will also have to update label selectors.

See chart examples for reference: https://github.com/kubernetes/helm/tree/master/docs/examples

2017-07-20 19:03 UTC, unguiculus commented on stable/ceph-exporter/templates/deployment.yaml
> +        image: "{{default "digitalocean/ceph_exporter" .Values.image}}:{{default "1.0.0" .Values.imageTag}}"
Add default values to `values.yaml`. Then you won't have to specify them here. Apply everywhere.

2017-07-20 19:03 UTC, unguiculus commented on stable/ceph-exporter/values.yaml
> +Name: ceph-exporter
Values should start with a lower case letter.

2017-07-20 19:03 UTC, unguiculus commented on stable/ceph-exporter/values.yaml
> +resources:
We usually recommend not to specify defaults for resources.

2017-07-20 20:06 UTC, kfox1111 commented
@unguiculus thanks for the review. I think I fixed all the issues raised.

2017-07-21 14:33 UTC, unguiculus requested changes

2017-07-21 14:33 UTC, unguiculus commented on stable/ceph-exporter/templates/deployment.yaml
> +        heritage: "{{ .Release.Service }}"
Only `app` and `release` label should be here.

2017-07-21 14:33 UTC, unguiculus commented on stable/ceph-exporter/templates/deployment.yaml
> +      annotations:
Make these annotations optional. They are not necessary when using the Prometheus Operator.

2017-07-21 14:33 UTC, unguiculus commented on stable/ceph-exporter/templates/_helpers.tpl
> +{{/* vim: set filetype=mustache: */}}
Fix formatting issues around braces and truncate to 63 chars. Ideally use `helm create` with Helm 2.5 to get a correct `_helpers.tpl`.

2017-07-21 14:33 UTC, unguiculus commented on stable/ceph-exporter/templates/deployment.yaml
> +      labels:
Only `app` and `release` label should be used here.

2017-07-21 15:41 UTC, kfox1111 commented on stable/ceph-exporter/templates/deployment.yaml
> +      annotations:
how does prometheus operator figure out what pods to scrape? I'm confused.

2017-07-21 20:37 UTC, unguiculus requested changes
Please add a readme file.

2017-07-21 20:37 UTC, unguiculus commented on stable/ceph-exporter/templates/svc.yaml
> +apiVersion: v1
Rename the file to `service.yaml`.

2017-07-23 16:58 UTC, unguiculus commented
The readme should have a table with config options.

2017-07-23 16:58 UTC, unguiculus commented
@k8s-bot ok to test

2017-07-24 16:31 UTC, kfox1111 commented
@unguiculus  I mentioned in another review, a lot of the charts have large amounts of documentation and duplicate stuff (a source of bugs). Should we have a "how to use helm charts" document instead of making every chart carry the load? All the settable values are inside the values.yaml file. Why do we need to duplicate them and then have to keep in sync every option available in both files?

2017-07-24 16:33 UTC, kfox1111 commented
Perhaps we should instead have a 'helm describe-values' or something feature that presents all the values in a helm chart to the user in a pretty way?

2017-07-24 20:52 UTC, kfox1111 commented
So, question. how do you have a chart that must have external secret/external storage to ever work with the e2e tests? Can we disable them per chart?

2017-07-25 19:17 UTC, unguiculus commented
The usual way is to also provide an option that the secrets be created by the chart. The chart should install successfully with defaults if possible.

2017-07-25 19:40 UTC, kfox1111 commented
The format of the secret is pretty particular. It would be much more effort for the user to get the secret passed through values then just kubectl create secret....

I've been a little leary of putting secrets in helm charts too. It puts them in configmaps and other places that may not be the more secure place for them?

And third, passing it through the chart still wont let the container start as it won't have a ceph in e2e? Or is it just checking the secrets/configmaps all exist, not that the pod can actually hits a running state?

2017-07-27 20:23 UTC, unguiculus commented
The tests check that the pods hit running state. One option would be to make it fail gracefully. You can look at the Datadog charts as an example which requires an API key.

https://github.com/kubernetes/charts/blob/master/stable/datadog/templates/deployment.yaml#L2
https://github.com/kubernetes/charts/blob/master/stable/datadog/templates/NOTES.txt

2017-07-27 20:28 UTC, kfox1111 commented
hmm... I guess that could work. still feels a little weird having the chart successfully deploy of the box to appease the tests but be otherwise unusable.

I guess it does give a nice place to print out notes to tell the user how to update it...

Should the notes in README be moved to NOTES then?

2017-07-28 05:19 UTC, unguiculus commented
I guess I'd do it like so:
* Document it in the README. 
* Add a prominent message to NOTES referring to the documentation in the README.

What do you think?

2017-07-28 15:58 UTC, kfox1111 commented
The thing I like about notes, is it shows with packages.

helm install stable/X, then you see the notes.

with readme, you have to checkout a git repo and go hunt for it, or download the package tarball and extract it to get the readme.

2017-07-28 16:06 UTC, unguiculus commented
Well, we kind of need both. You see the Readme on Github and on kubeapps.com *before* you install the chart.

2017-07-28 16:12 UTC, kfox1111 commented
I agree this is a problem. And a furtherance of the huge amount of duplication in each chart, either within each chart or across charts. :/

We might want to put our collective heads together and hash through some of this?

Maybe readme and/or notes should be automatically generated somehow?

2017-07-28 16:25 UTC, prydonius commented
I think this discussion raises some good points about the duplication in chart READMEs/NOTES. @kfox1111 it would be great to discuss this further in a future Charts dev call (every Thus 11am PT) or SIG-Apps as we go to plan priorities for 1.8.

On the successful install by default requirement, we did talk about having a test-values.yaml file that would be used by the CI for tests. This could be the place for fake API keys that allow the charts to be testable in CI, whilst allowing the chart developer to provide a more expected UX for users installing the chart. Another thing we can discuss during one of these next calls.

In the meantime, I think we can copy the approaches in the existing charts to have this PR go through. Once we have a better story for this, we can go back and update all the charts.

2017-07-28 16:33 UTC, kfox1111 commented
I should be able to make the 11am charts dev call I think. is there location info somewhere?

Ok. I'll see about fixing it up for now.

2017-07-29 00:47 UTC, kfox1111 commented
Ok. I still have the notes bit to add, but please review on the approach taken to add ceph configmap and secret generation. I expect to do a chart for https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/rbd soon and it will reuse the configmap/secret charts the same way its used here.

2017-07-29 21:12 UTC, kfox1111 commented
Ok. I think this has all the things added.

2017-08-02 00:43 UTC, mgoodness reviewed
I'm going to defer to @unguiculus, as this PR has waited on me for far too long. Sorry!

2017-08-13 12:34 UTC, unguiculus commented
If I remember correctly, this PR started out with one chart. Now, we have three individual charts. Can you explain why you made this change? It doesn't make sense to me because they don't seem to make sense on their own. Why not create one chart with multiple components? The Nginx Ingress Controller would be a good example for such a chart. See https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress/.

2017-08-14 16:59 UTC, kfox1111 commented
It started off as one chart, but folks wanted "default" secrets and "default" configmap generation support added in. so I added those as separate charts so that they can be reused by other charts that are ceph related and will get the same kind of request in for. I have another one I have been working on to add ceph dynamic pvc support here: https://github.com/kfox1111/charts/tree/ceph-provisioner/stable/ceph-provisioner I will submit it soon, once I can verify it works properly.

2017-08-31 19:57 UTC, viglesiasce commented
The pattern we have seen in other charts is to have a flag to provide your own "custom" configmap (or secret). 

Can we move to that pattern for both secrets and configmaps in the ceph chart?

https://github.com/kubernetes/charts/tree/master/stable/jenkins#custom-configmap

2017-11-22 21:37 UTC, viglesiasce commented
Marking stale.

2017-11-29 18:53 UTC, viglesiasce commented
Closing as stale.

2017-11-29 18:53 UTC, closed without merging