add ability to configure deployment strategy
helm/charts pull request #8073
Opened 2018-10-01 10:00 UTC by TAvardit

Signed-off-by: Vardit Natanson <v.natanson@travelaudience.com>

#### What this PR does / why we need it:
* Adding ability to adjust deployment strategy
* Adding option to state pvc namespace in added pv template.
#### Which issue this PR fixes

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-10-01 19:13 UTC, rjkernick requested changes

2018-10-01 19:13 UTC, rjkernick commented on stable/sonatype-nexus/README.md
> +| `namespace`                        | pvc namespace     |  `default` |
Not sure I understand the use case of manually setting the pvc namespace. Helm charts generally control resource within the same namespace.

2018-10-01 19:13 UTC, rjkernick commented on stable/sonatype-nexus/README.md
> +| `deploymentStrategy`                        | Deployment Strategy     |  `rollingUpdate` |
The deployment strategy is a nice addition.

2018-10-01 19:13 UTC, rjkernick commented on stable/sonatype-nexus/Chart.yaml
> +version: 1.9.1
Please bump the minor version as this adds a feature

2018-10-01 19:14 UTC, rjkernick commented
I like the deployment strategy addition. However, the pvc namespace seems like a change that would break the ability to easily update from an existing version.

2018-10-01 19:14 UTC, rjkernick commented
/assign

2018-10-02 07:55 UTC, TAvardit commented
> I like the deployment strategy addition. However, the pvc namespace seems like a change that would break the ability to easily update from an existing version.

You are totally right,  I changed it to use Helm pre-defined values instead.

2018-10-02 17:11 UTC, rjkernick approved these changes

2018-10-02 17:11 UTC, rjkernick commented
/lgtm

2018-10-02 17:14 UTC, rjkernick commented
/ok-to-test

2018-10-02 17:18 UTC, merged