Kubernetes Dashboard Chart
helm/charts pull request #808
Opened 2017-03-17 00:58 UTC by kfox1111

Adds support for managing the Kubernetes Dashboard lifecycle via
Helm.

2017-03-23 00:10 UTC, seanknox commented
Hi @kfox1111, this charts is missing a `NOTES.txt`. Here's a [good example](https://github.com/kubernetes/charts/blob/master/stable/drupal/templates/NOTES.txt) from the Drupal chart.

Chart looks good otherwise 👍

2017-03-23 19:31 UTC, kfox1111 commented
@seanknox thanks for the review and the NOTES.txt pointer. I just added one using the example as a template.

2017-03-23 21:06 UTC, seanknox requested changes

2017-03-23 21:06 UTC, seanknox commented on stable/kubernetes-dashboard/templates/deployment.yaml
> +  namespace: {{ default "kube-system" .Values.namespace }}
Rule of thumb with configurable values: if it's configurable, set the default value in `values.yaml` and change the reference in the resource to that, e.g. `namespace: {{ .Values.namespace }}`

At the moment, the deployment installs into kube-system by default but the release thinks it's "default":

```
NOTES:
*********************************************************************************
*** PLEASE BE PATIENT: kubernetes-dashboard may take a few minutes to install ***
*********************************************************************************

Get the Kubernetes Dashboard URL by running:

  export POD_NAME=$(kubectl get pods --namespace default -l "app=yucky-dog-kubernetes-das" -o jsonpath="{.items[0].metadata.name}")
  echo http://127.0.0.1:8080/
  kubectl port-forward $POD_NAME 8080:80

$ export POD_NAME=$(kubectl get pods --namespace default -l "app=yucky-dog-kubernetes-das" -o jsonpath="{.items[0].metadata.name}")
No resources found.
error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0
```

2017-03-23 21:06 UTC, seanknox commented on stable/kubernetes-dashboard/templates/svc.yaml
> +    release: {{ .Release.Name | quote }}
You'll need to add a `namespace: {{ .Values.namespace }}` to this spec.

2017-03-23 21:07 UTC, linki commented on stable/kubernetes-dashboard/templates/deployment.yaml
> +        image: "{{default "gcr.io/google_containers/kubernetes-dashboard-amd64" .Values.image}}:{{default "v1.6.0" .Values.imageTag}}"
Since we're dropping the default statements, set the image in the `values.yaml` just like the `imageTag` and drop the defaults here.

2017-03-31 20:31 UTC, kfox1111 commented
@seanknox @linki I think this fixes the issues you raised. Thanks for the review.

2017-03-31 21:14 UTC, unguiculus commented
Formatting is inconsistent, e. g. `{{.Values.namespace}}` vs. `{{ .Values.namespace }}`. The examples in the docs use spaces after opening and before closing braces. I'd suggest you follow this practice.

2017-03-31 23:51 UTC, kfox1111 commented
@unguiculus the ws issues are in a lot of places in the charts in this repo. But, as requested, I fixed them here. :)  Thanks for the review.

2017-04-01 00:20 UTC, seanknox commented on stable/kubernetes-dashboard/values.yaml
> +    cpu: 512m
Minor nit: required resources are high given what dashboard typically needs. Here are the defaults from GKE, for example:

```
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
```
Not blocking for this PR, just something to consider.

2017-04-01 00:22 UTC, seanknox commented
- Missing a `README.md`
- Default install fails:
```
helm install stable/kubernetes-dashboard/
Error: release knotted-mink failed: Service "knotted-mink-kubernetes-" is invalid: [metadata.name: Invalid value: "knotted-mink-kubernetes-": must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123'), metadata.labels: Invalid value: "knotted-mink-kubernetes-": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345'), spec.selector: Invalid value: "knotted-mink-kubernetes-": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345')]
```

2017-04-01 00:28 UTC, kfox1111 commented
hmm... the naming is based on the standard macro in charts repo.... somehow you got very (un)lucky and ended up with a - at the end. :/

This is a more general problem though with kubernetes/charts I think. do we up the limit on the number of characters?

2017-04-01 00:31 UTC, seanknox commented
The `_helpers.tpl` should be updated to truncate at 63 characters. We haven't updated all of the charts yet (it's on the TODO). Here's one you can use:

https://github.com/kubernetes/charts/blob/master/stable/redis/templates/_helpers.tpl

2017-04-01 08:15 UTC, unguiculus commented on stable/kubernetes-dashboard/templates/deployment.yaml
> +        imagePullPolicy: {{ .Values.ImagePullPolicy }}
Wrong case: `ImagePullPolicy ` -> `imagePullPolicy`

2017-04-11 17:11 UTC, seanknox requested changes

2017-04-11 17:11 UTC, seanknox commented on stable/kubernetes-dashboard/values.yaml
> +
You'll need to remove this and let Helm handle the namespace via `helm install --namespace`.

2017-04-11 17:11 UTC, seanknox commented
@kfox1111 One last change requested and then this looks good to go!

2017-04-11 17:13 UTC, kfox1111 commented on stable/kubernetes-dashboard/values.yaml
> +
The intention is for it to work just like all other kube-system namespeced things by default. Yeah, its a little wonky though.... There's going to be a bunch of other packages like this too. Should we talk more about it?

2017-04-11 17:27 UTC, seanknox commented on stable/kubernetes-dashboard/values.yaml
> +
AFAIK the dashboard is usually deployed in `kube-system` by convention, though there's no technical requirement that it has to be there. Cluster operators can and do install cluster-service charts in any namespace. The [core-dns chart](https://github.com/kubernetes/charts/blob/5348297977b97b6c7599cde465f61e499c7ef5e5/stable/coredns/README.md) install example specifies the namespace from the command line, as opposed to it being enforced by the chart itself.

2017-04-11 19:59 UTC, linki commented on stable/kubernetes-dashboard/templates/NOTES.txt
> +  kubectl port-forward $POD_NAME 8080:80
The `port-forward` command needs the `--namespace` set as well.

2017-04-11 20:06 UTC, linki commented on stable/kubernetes-dashboard/templates/svc.yaml
> +    targetPort: http
The named target port `http` doesn't exist in your deployment. This service won't work.

2017-04-11 20:09 UTC, linki commented on stable/kubernetes-dashboard/templates/NOTES.txt
> +  kubectl port-forward $POD_NAME 8080:80
The Dashboard pod acutally listens on port 9090, so this must be `port-forward $POD_NAME 8080:9090`. However, I think it's better we just stick with port `9090` on both ends.

2017-04-11 20:11 UTC, linki commented on stable/kubernetes-dashboard/templates/NOTES.txt
> +  kubectl port-forward $POD_NAME 8080:80
That would also be similar to how GKE deploys the dashboard.

```yaml
kind: Service
...
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9090
```

2017-04-11 20:13 UTC, seanknox commented on stable/kubernetes-dashboard/templates/NOTES.txt
> +  kubectl port-forward $POD_NAME 8080:80
Looks like the `POD_NAME` shell var above captures it.

2017-04-11 20:18 UTC, linki commented on stable/kubernetes-dashboard/values.yaml
> +
Let's do how @seanknox suggests. Currently, `helm list` gets confused and shows the chart living in the "default" namespace although everything is deployed in kube-system.

2017-04-11 20:40 UTC, linki commented on stable/kubernetes-dashboard/Chart.yaml
> +description: Kubernetes Dashboard
Let's change it to their Github description

> General-purpose web UI for Kubernetes clusters

2017-04-11 20:41 UTC, linki commented on stable/kubernetes-dashboard/templates/NOTES.txt
> +  export NODE_IP=$(kubectl get nodes --namespace {{ .Values.namespace }} -o jsonpath="{.items[0].status.addresses[0].address}")
I believe `nodes` are not namespaced, so `--namespace` should be omitted here.

2017-04-11 20:46 UTC, linki commented on stable/kubernetes-dashboard/templates/NOTES.txt
> +  kubectl port-forward $POD_NAME 8080:80
@seanknox Hmm, but that's just the plain pod name in the namespace. How can it know the namespace in the port-forward call?

2017-04-11 20:50 UTC, linki commented on stable/kubernetes-dashboard/templates/svc.yaml
> +    release: {{ .Release.Name | quote }}
`release` is specified twice.

2017-04-11 20:50 UTC, linki commented on stable/kubernetes-dashboard/templates/deployment.yaml
> +    release: {{ .Release.Name | quote }}
`release` is specified twice.

2017-04-11 20:50 UTC, linki commented on stable/kubernetes-dashboard/templates/deployment.yaml
> +        release: {{ .Release.Name | quote }}
`release` is specified twice.

2017-04-11 20:52 UTC, linki commented on stable/kubernetes-dashboard/templates/deployment.yaml
> +  namespace: {{ .Values.namespace }}
This needs to go if we decide to drop `namespace` from `values.yaml`.

2017-04-11 20:52 UTC, linki commented on stable/kubernetes-dashboard/templates/svc.yaml
> +  namespace: {{ .Values.namespace }}
This needs to go if we decide to drop `namespace` from `values.yaml`.

2017-04-11 20:56 UTC, linki commented
Thanks @kfox1111 

Pretty good chart. I found a couple inconsistencies and nitpicks, though. Let me know If you need help with them @kfox1111.

2017-04-11 23:06 UTC, kfox1111 commented on stable/kubernetes-dashboard/values.yaml
> +
hmm... ok. sounds good.

2017-04-11 23:15 UTC, kfox1111 commented
I think this fixes all the issues. Thanks for the reviews. :)  Please let me know if I missed anything.

2017-04-20 21:25 UTC, kfox1111 commented
Ping

2017-05-05 03:48 UTC, olalonde commented
Ping :)

2017-05-22 18:17 UTC, unguiculus commented
@k8s-bot ok to test

2017-05-23 18:38 UTC, unguiculus requested changes

2017-05-23 18:38 UTC, unguiculus commented on stable/kubernetes-dashboard/templates/deployment.yaml
> +    app: {{ template "fullname" . }}
I would prefer to use `{{ template "name" . }}` instead of  `{{ template "fullname" . }}` for the `app` labels.

2017-05-23 18:48 UTC, kfox1111 commented on stable/kubernetes-dashboard/templates/deployment.yaml
> +    app: {{ template "fullname" . }}
Ah. good point. Updated.

2017-05-23 20:13 UTC, unguiculus commented
Please apply the label change also to the service.

2017-05-24 22:13 UTC, kfox1111 commented
Doh. good catch. fixing...

2017-05-26 06:27 UTC, unguiculus requested changes
A few more things, sorry.

2017-05-26 06:27 UTC, unguiculus commented on stable/kubernetes-dashboard/templates/svc.yaml
> +    targetPort: 80
Why didn't you just give the port a name in the deployment? I'd prefer that.

2017-05-26 06:27 UTC, unguiculus commented on stable/kubernetes-dashboard/templates/svc.yaml
> +    app: {{ template "name" . }}
A second selector is required. Use this:
```yaml
selector:
  app: {{ template "name" . }}
  release: {{ .Release.Name }}
```

2017-05-26 15:44 UTC, kfox1111 commented on stable/kubernetes-dashboard/templates/svc.yaml
> +    targetPort: 80
I basically just dropped in the upstream kubernetes-dashboard stuff into a chart.

I'm not really sure why they did some of the things the way they did.

Are you saying a targetPort can be a reference to a named port in a pod?

2017-05-26 15:46 UTC, kfox1111 commented on stable/kubernetes-dashboard/templates/svc.yaml
> +    targetPort: 80
ah. just read the spec. it can be. so it was better before. I'll change it back.

2017-05-26 15:49 UTC, kfox1111 commented
@unguiculus Thanks for the review. I learned something new about services today. :)

2017-05-26 15:58 UTC, unguiculus approved these changes

2017-05-26 16:04 UTC, kfox1111 commented
@seanknox I think all your issues have been fixed. Can you please verify?

2017-05-30 15:27 UTC, linki approved these changes

2017-06-01 00:08 UTC, kfox1111 commented on stable/kubernetes-dashboard/values.yaml
> +
github is saying this is an issue, but I don't it is is anymore. @seanknox know how to fix this?

2017-06-01 15:33 UTC, kfox1111 commented on stable/kubernetes-dashboard/templates/NOTES.txt
> +  kubectl port-forward $POD_NAME 8080:80
re-looked at this. I think it does need the namespace flag passed to both the POD_NAME call and the port-forward call. Adding.

2017-06-12 14:47 UTC, linki commented
@seanknox's remarks regarding the namespace were fixed. So 👍  from my side.

2017-06-12 15:43 UTC, kfox1111 commented
good to merge then?

2017-06-13 13:49 UTC, kenden commented
in the file NOTES.txt, replace
```
export POD_NAME=$(kubectl get pods -n {{ .Release.Namespace }} -l "app={{ template "fullname" . }}" -o jsonpath="{.items[0].metadata.name}")
```
by
```
export POD_NAME=$(kubectl get pods -n {{ .Release.Namespace }} -l "app={{ template "name" . }},release={{ .Release.Name }}" -o jsonpath="{.items[0].metadata.name}")
```

2017-06-13 13:51 UTC, kenden commented on stable/kubernetes-dashboard/templates/NOTES.txt
> +  export POD_NAME=$(kubectl get pods -n {{ .Release.Namespace }} -l "app={{ template "fullname" . }}" -o jsonpath="{.items[0].metadata.name}")
the selector here is not
`-l app="{{ template "fullname" . }}"`
it's
`-l "app={{ template "name" . }},release={{ .Release.Name }}"`

2017-06-13 14:03 UTC, kenden commented
It would be nice to have an ingress for this, too. See the Grafana Chart, for  example:
https://github.com/kubernetes/charts/blob/master/stable/grafana/templates/ingress.yaml

2017-06-13 17:11 UTC, kenden commented
LGTM

2017-06-13 19:19 UTC, unguiculus commented
lgtm

2017-06-13 19:24 UTC, unguiculus requested changes
I noticed one more thing when testing.

2017-06-13 19:24 UTC, unguiculus commented on stable/kubernetes-dashboard/templates/NOTES.txt
> +  kubectl -n {{ .Release.Namespace }} port-forward $POD_NAME 9090:80
Port 80 is wrong.

2017-06-15 15:22 UTC, linki commented on stable/kubernetes-dashboard/templates/ingress.yaml
> +              servicePort: {{ .Values.httpPort }}
When enabling Ingress with a hostname: The `.` inside this loop is one of the `hostname` strings defined in `values.yaml`. So both `template` and `.Values` fails with:

```
Error: render error in "kubernetes-dashboard/templates/ingress.yaml": template: kubernetes-dashboard/templates/_helpers.tpl:14:51: executing "fullname" at <.Values.nameOverride>: can't evaluate field Values in type string
```

2017-06-15 15:33 UTC, unguiculus approved these changes

2017-06-15 16:04 UTC, kfox1111 commented on stable/kubernetes-dashboard/templates/ingress.yaml
> +              servicePort: {{ .Values.httpPort }}
good catch. thanks. I think it should be fixed now. please double check.

2017-06-15 19:49 UTC, unguiculus requested changes
Sorry, I've just discovered one more thing. We've started using Github usernames instead of real name. This makes it easier to identify the chart maintainer for reviews on future changes.

2017-06-15 19:49 UTC, unguiculus commented on stable/kubernetes-dashboard/Chart.yaml
> +  - name: Kevin Fox
Please use Github username.

2017-06-16 10:06 UTC, linki commented
@unguiculus I changed maintainers to the github handle.

2017-06-16 10:42 UTC, unguiculus approved these changes

2017-06-16 10:43 UTC, merged

2017-06-16 12:01 UTC, linki commented
Thanks @kfox1111 @unguiculus