drupal (new chart)
helm/charts pull request #81
Opened 2016-09-19 21:40 UTC by prydonius

#### Details

> [Drupal](https://www.drupal.org/) is one of the most versatile open source content management systems on the market.

- Uses the [Drupal Docker image from Bitnami](https://github.com/bitnami/bitnami-docker-drupal)
- Vendors the MariaDB chart from [stable] (https://github.com/kubernetes/charts/tree/master/stable/mariadb) (with changes for persistence)
- Uses alpha PV provisioning for persistence

#### Functional testing

1. Deploy the chart: `helm install incubator/drupal`
2. Wait for external IP address to be configured, and pod to be ready
4. Visit http://$SERVICE_IP/ and login with username `user` and password `bitnami`

2016-09-21 01:28 UTC, prydonius commented
/cc @michelleN @viglesiasce

2016-09-21 16:28 UTC, viglesiasce commented
Will review this afternoon.

2016-09-21 22:00 UTC, viglesiasce requested changes
The wizard takes a really long time. Can you add a note that they should be very patient. Mine took around 3 minutes.

2016-09-22 03:36 UTC, chrislovecnm commented on incubator/drupal/charts/mariadb/README.md
> +```bash
Nit pick, but their is console u can use instead of bash highlighting ;)

2016-09-22 03:39 UTC, chrislovecnm commented on incubator/drupal/charts/mariadb/README.md
> +For persistence of the data you should replace the `emptyDir` volume with a persistent [storage volume](http://kubernetes.io/docs/user-guide/volumes/), else the data will be lost if the Pod is shutdo
Do we even want to have this with emptyDir? I would never recommend deploying Drupal with emptyDir. Do you have a use case for?

2016-09-22 03:42 UTC, chrislovecnm commented on incubator/drupal/charts/mariadb/templates/deployment.yaml
> +      - name: {{ template "fullname" . }}
Can you recommend and put in some resource limits for MySQL?

2016-09-22 03:44 UTC, chrislovecnm commented on incubator/drupal/templates/NOTES.txt
> +
Nice!

2016-09-22 03:47 UTC, chrislovecnm commented on incubator/drupal/templates/deployment.yaml
> +        image: "{{ .Values.image }}"
Please a resource limits as well.

2016-09-22 03:48 UTC, chrislovecnm commented on incubator/drupal/templates/deployment.yaml
> +        env:
Does the container image allow for tuning Apache? Worker settings, etc?

2016-09-22 03:50 UTC, chrislovecnm reviewed
Appreciate the PR! Lots is good stuff coming in!

2016-09-22 16:57 UTC, prydonius commented on incubator/drupal/charts/mariadb/README.md
> +For persistence of the data you should replace the `emptyDir` volume with a persistent [storage volume](http://kubernetes.io/docs/user-guide/volumes/), else the data will be lost if the Pod is shutdo
Sorry for the confusion on this, we just grabbed the MariaDB from [stable](https://github.com/kubernetes/charts/tree/master/stable/mariadb), changed it to use PVCs by default, but didn't update the README. Kubernetes 1.4 should be released soon, and when it is we will update the standalone MariaDB, and I was just planning on updating all the dependent MariaDBs at the same time.

If you prefer though, I can update the dependent MariaDBs READMEs to reflect the PVC changes we made now.

2016-09-22 16:58 UTC, prydonius commented on incubator/drupal/charts/mariadb/templates/deployment.yaml
> +      - name: {{ template "fullname" . }}
I think this is something that should be added to the standalone MariaDB chart, and then we can update the dependent ones. I missed #60 before, I'll look into it!

2016-09-22 17:03 UTC, prydonius commented on incubator/drupal/templates/deployment.yaml
> +        env:
Not currently, but that's a great idea! I'll create an issue in the [bitnami/apache](https://github.com/bitnami/bitnami-docker-apache) to request those options.

2016-09-22 18:12 UTC, chrislovecnm commented on incubator/drupal/charts/mariadb/README.md
> +For persistence of the data you should replace the `emptyDir` volume with a persistent [storage volume](http://kubernetes.io/docs/user-guide/volumes/), else the data will be lost if the Pod is shutdo
Oh craps... Let's get that into an issue.  Would you be able to run with fixing that outside this PR?

2016-09-22 18:13 UTC, chrislovecnm commented on incubator/drupal/templates/deployment.yaml
> +        env:
@prydonius ping me if you want to review what I am talking about.  I have tuning apache before, and I would rather do Nginx with PHP-fpm running beside it.  Apache is popular, but eh.

2016-09-22 19:16 UTC, prydonius commented on incubator/drupal/templates/deployment.yaml
> +        image: "{{ .Values.image }}"
Hmm I've been investigating and it looks like the startup uses quite a bit of CPU, due to the wizard (peaked to ~650m), but after it drops to <50m after Drupal is configured.

Given this, what do you think is an appropriate CPU request/limit?

For memory, 512Mi is a sensible request.

2016-09-22 19:18 UTC, prydonius commented on incubator/drupal/charts/mariadb/README.md
> +For persistence of the data you should replace the `emptyDir` volume with a persistent [storage volume](http://kubernetes.io/docs/user-guide/volumes/), else the data will be lost if the Pod is shutdo
Yep, I can take care of that outside this :), I assigned #67 to myself.

2016-09-22 19:22 UTC, prydonius commented on incubator/drupal/templates/deployment.yaml
> +        env:
Personally I prefer the separated tier approach too, but we've run into issues with configuring virtual hosts properly when the web server isn't in the same container as the application. Additionally, many of the applications we're configuring make use of `.htaccess` files, another reason it's easier to have the web server and the app in the same container, and also why nginx is a little harder to configure. That's why we've gone with the Apache + mod_php approach in the Bitnami application containers for now.

2016-09-22 19:26 UTC, prydonius commented
Thanks for the reviews @viglesiasce and @chrislovecnm, some really great suggestions!

I'll add a message in NOTES.txt about the long wait time, and change the README to use the console highlighting. I investigated the resource requests, but will need a little help selecting an appropriate CPU request (see comment).

2016-09-23 02:03 UTC, chrislovecnm commented
Does it start ok if you do say 300m? It all varies under load. Just always good to put a disclaimer in the conf saying that people will need to modify the values based on ther use case.

2016-09-23 05:16 UTC, chrislovecnm commented
@viglesiasce LGTM

2016-09-24 01:19 UTC, prydonius commented
@chrislovecnm added a default resource request of 300m. Since it's a request and not a limit, it should be good. Thanks!

2016-09-26 18:06 UTC, viglesiasce approved these changes

2016-09-26 18:06 UTC, viglesiasce commented
Looks great. Thanks @prydonius!!!!

2016-09-26 18:06 UTC, merged