fx: propogate influx deployment labels to pods
helm/charts pull request #8106
Opened 2018-10-02 11:59 UTC by Freyert

#### What this PR does / why we need it:
This PR propagates Deployment labels down to the Pod for InfluxDB. This makes it so that you can easily query for the Pods by their InfluxDB release in Prometheus and group metrics by release. 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

2018-10-31 19:52 UTC, unguiculus requested changes

2018-10-31 19:52 UTC, unguiculus commented on stable/influxdb/templates/deployment.yaml
> +        heritage: "{{ .Release.Service }}"
Only add the release label.

2018-11-07 09:40 UTC, Freyert commented on stable/influxdb/templates/deployment.yaml
> +        heritage: "{{ .Release.Service }}"
Fixed! Thanks @unguiculus

2018-11-09 14:53 UTC, unguiculus approved these changes

2018-11-09 14:53 UTC, unguiculus commented
/ok-to-test

2018-11-09 15:06 UTC, unguiculus commented
/lgtm

2018-11-09 15:35 UTC, merged