Deprecate old Telegraf chart
helm/charts pull request #823
Opened 2017-03-20 22:53 UTC by jackzampolin

This PR completes the breaking up of the telegraf chart by deprecating the current one.

Related PRs:
- https://github.com/kubernetes/charts/pull/822
- https://github.com/kubernetes/charts/pull/742

2017-04-19 14:57 UTC, prydonius requested changes
thanks @jackzampolin

2017-04-19 14:57 UTC, prydonius commented on stable/telegraf/values.yaml
> +  tag: "1.2.0-alpine"
I would not bump the version when deprecating

2017-04-19 14:57 UTC, prydonius commented on stable/telegraf/Chart.yaml
> +version: 0.2.1
0.1.2 is probably a better bump since there should be no functional change in a deprecation

2017-04-24 22:25 UTC, jackzampolin commented
@prydonius Fixed that!

2017-05-10 21:59 UTC, merged

2017-07-16 23:48 UTC, abraithwaite commented
This was merged but of the other two PRs, one was closed as stale and one is still open. 

What's the current status?