add optional ingress for selenium chart
helm/charts pull request #8243
Opened 2018-10-06 14:30 UTC by arnaud-deprez

Signed-off-by: Arnaud Deprez <arnaudeprez@gmail.com>

#### What this PR does / why we need it:
Hi, this PR add an optional ingress for the selenium hub which is useful when deploying in non-cloud kubernetes instance such as openshift on premise, minikube, minishift, etc.

#### Which issue this PR fixes
No issue was created before. Please tell me if you need it.

#### Special notes for your reviewer:
This has been tested on minikube with the following command on minikube with nginx ingress controller: 
helm template --name selenium --set hub.ingress.enabled=true --set hub.ingress.hosts={"hub-selenium.$(minikube ip).nip.io"} selenium | kubectl apply -n selenium -f -

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-10-06 14:33 UTC, arnaud-deprez commented
/assign @davidkarlsen

2018-10-06 17:25 UTC, davidkarlsen requested changes

2018-10-06 17:25 UTC, davidkarlsen commented on stable/selenium/Chart.yaml
> +version: 0.10.1
new feature - set 0.11.0 instead

2018-10-06 23:14 UTC, arnaud-deprez commented on stable/selenium/Chart.yaml
> +version: 0.10.1
Correct ! Here is the change.
Cheers

2018-10-07 15:39 UTC, davidkarlsen commented
/ok-to-test

2018-10-07 15:39 UTC, davidkarlsen approved these changes

2018-10-07 17:17 UTC, davidkarlsen commented
/lgtm

2018-10-07 17:19 UTC, merged