Google Cloud SQL Proxy
helm/charts pull request #826
Opened 2017-03-22 10:34 UTC by rimusz

2017-03-29 05:57 UTC, lachie83 commented
@k8s-bot ok to test

2017-04-10 18:44 UTC, lachie83 requested changes
Looks good. Just a couple of small changes

2017-04-10 18:44 UTC, lachie83 commented on stable/gcloud-sqlproxy/.helmignore
> +.git
Please add `helm create <chart name>` generated .helmignore

2017-04-10 18:44 UTC, lachie83 commented on stable/gcloud-sqlproxy/values.yaml
> +gcpServiceAccountKey: 'Paste base64 encoded data here.'
Why not use the base64 function in the secret?

2017-04-10 18:44 UTC, lachie83 commented on stable/gcloud-sqlproxy/README.md
> +## Introduction
Can you provide details on the access the service account needs?

2017-04-10 18:44 UTC, lachie83 commented on stable/gcloud-sqlproxy/templates/deployment.yaml
> +        image: "{{ .Values.image }}"
Should you split the image and the tag into separate fields?

2017-04-10 18:45 UTC, lachie83 commented on stable/gcloud-sqlproxy/values.yaml
> +gcpServiceAccountKey: 'Paste base64 encoded data here.'
Would also help CI get past the following issue

<details>
Error: release gcloud--1252 failed: unable to decode "": [pos 79]: json: error decoding base64 binary 'Paste base64 encoded data here.': illegal base64 data at input byte 5
</details>

2017-04-11 14:09 UTC, rimusz commented on stable/gcloud-sqlproxy/templates/deployment.yaml
> +        image: "{{ .Values.image }}"
Done

2017-04-11 14:09 UTC, rimusz commented on stable/gcloud-sqlproxy/README.md
> +## Introduction
Done

2017-04-11 14:11 UTC, rimusz commented on stable/gcloud-sqlproxy/values.yaml
> +gcpServiceAccountKey: 'Paste base64 encoded data here.'
It is better to use base64 function as it makes much easier to copy/paste data to the `values.yaml` file or pass as a part of `--set`

2017-04-11 14:11 UTC, rimusz commented on stable/gcloud-sqlproxy/.helmignore
> +.git
done

2017-04-11 14:14 UTC, rimusz commented on stable/gcloud-sqlproxy/values.yaml
> +gcpServiceAccountKey: 'Paste base64 encoded data here.'
also for the test to succeed the real GCP service account key needs to be used, as otherwise SQLProxy fails to start

2017-04-11 16:15 UTC, lachie83 commented on stable/gcloud-sqlproxy/values.yaml
> +gcpServiceAccountKey: 'Paste base64 encoded data here.'
If that's the case, how do you propose getting this through CI?

2017-04-11 16:38 UTC, rimusz commented on stable/gcloud-sqlproxy/values.yaml
> +gcpServiceAccountKey: 'Paste base64 encoded data here.'
it is really GCP dependant chart, plus if there is no GCP SQL instance running it will not pass CI anyway

2017-04-19 16:18 UTC, rimusz commented
ping @lachie83

2017-04-19 16:26 UTC, lachie83 requested changes
Please add NOTES.txt given that pods don't go to running state. I suggest you throw up a warning if the service account key is empty prompting the user to add -- https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements

2017-04-19 17:10 UTC, rimusz commented
@lachie83 I have added the NOTES.txt

2017-04-21 09:22 UTC, rimusz commented
@prydonius would you mind to take a look, please.

2017-04-21 15:46 UTC, lachie83 commented on stable/gcloud-sqlproxy/templates/NOTES.txt
> +{{- if eq (printf "%s" .Values.serviceAccountKey) "" }}
Should you provide any other information if these to things are provided?

2017-04-21 17:10 UTC, rimusz commented
@lachie83 I have added connection info if all required values are provided

2017-04-21 22:31 UTC, lachie83 approved these changes

2017-04-21 22:35 UTC, lachie83 commented
LGTM

2017-04-24 19:06 UTC, prydonius commented
Thanks @rimusz!

2017-04-24 19:08 UTC, prydonius commented
On second thought, can we make this behave like Minecraft/Ghost/etc. and not create the deployment resource (https://github.com/kubernetes/charts/blob/master/stable/minecraft/templates/deployment.yaml#L1) if the required values are not set? We should also have the `helm upgrade` example to fix the release.

2017-04-24 19:37 UTC, rimusz commented
sure, good idea, will do that tomorrow

2017-04-25 10:12 UTC, rimusz commented
@prydonius I have addressed it by your comments

2017-04-26 14:44 UTC, prydonius commented
@rimusz thanks - I simplified your conditionals a bit

2017-04-26 14:46 UTC, merged

2017-04-26 14:46 UTC, lachie83 commented
LGTM