[stable/fluentd-elasticsearch] Add DaemonSet updateStartegy settings to values.yml
helm/charts pull request #8302
Opened 2018-10-09 15:01 UTC by francois-travais

Signed-off-by: François Travais <francois.travais@gmail.com>

#### What this PR does / why we need it:

Make DaemonSet updateStartegy configurable from values.yml

#### Which issue this PR fixes
  - fixes #7978 

#### Special notes for your reviewer:

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-10-09 16:05 UTC, desaintmartin commented on stable/fluentd-elasticsearch/Chart.yaml
> +version: 1.0.4
Since it is a new feature, it may be nice to bump the minor version instead of patch.

2018-11-07 10:00 UTC, maver1ck commented
@francois-travais Could you please fix conflict ?

2018-11-07 10:34 UTC, francois-travais commented
Done.

2018-11-15 17:22 UTC, paulczar commented
/ok-to-test

2018-11-15 22:37 UTC, paulczar requested changes
Looks like you need to fix the length of the persistent volume name ...  see errors in test

```
I1115 17:24:13.935] Error: release fluentd-elasticsearch-f378qxbczk failed: DaemonSet.apps "fluentd-elasticsearch-f378qxbczk-fluentd-elasticsearch" is invalid: [spec.template.spec.volumes[3].name: Invalid value: "config-volume-fluentd-elasticsearch-f378qxbczk-fluentd-elasticsearch": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[3].name: Not found: "config-volume-fluentd-elasticsearch-f378qxbczk-fluentd-elasticsearch"]
```

2018-11-16 08:11 UTC, francois-travais commented
That's a bit odd since it has nothing to do with my changes

2018-11-16 08:34 UTC, francois-travais commented
It's now fixed @paulczar

2018-11-21 09:56 UTC, maver1ck commented
@francois-travais 
1) Please fix conflict
2) Should we have default value for update strategy ? So RollingUpdate instead of `{}`

2018-11-26 23:57 UTC, ScottBrenner commented on stable/fluentd-elasticsearch/Chart.yaml
> +version: 1.4.0
Is there a `1.4.0` version of this chart? Latest I'm seeing is `1.3.0`.

2018-11-27 07:44 UTC, francois-travais commented
@desaintmartin suggested to bump the minor version a while ago
https://github.com/helm/charts/pull/8302#discussion_r223765850, which I
did, so indeed there isn't a version 1.4.0 right now, but that's intended.

2018-11-27 08:33 UTC, maver1ck commented
/lgtm
But I still don't have rights.

2018-11-27 08:34 UTC, maver1ck commented
@paulczar @viglesiasce 
Could you please merge this ?

2018-12-17 17:41 UTC, paulczar commented
/lgtm

2018-12-17 17:41 UTC, paulczar approved these changes

2018-12-17 17:42 UTC, paulczar commented
/retest

2018-12-17 17:43 UTC, desaintmartin commented
chart.yaml: appVersion did change but version did not.

2018-12-17 17:45 UTC, paulczar commented
@desaintmartin yeah i think it did, some weird result of resolving conflicts.

2018-12-17 17:56 UTC, paulczar commented
/retest

2018-12-17 18:42 UTC, paulczar commented
/lgtm

2018-12-17 18:54 UTC, merged