[stable/magic-namespace] Adding annotations and labels to namespaces
helm/charts pull request #8324
Opened 2018-10-10 10:16 UTC by alvgarvilla

Being able to add annotations and labels to namespaces

#### Which issue this PR fixes

  - fixes https://github.com/helm/charts/issues/8321

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x ] Chart Version bumped
- [x ] Variables are documented in the README.md

2018-10-10 18:21 UTC, krancour commented on stable/magic-namespace/Chart.yaml
> +appVersion: 2.8.2
iirc, `appVersion` here denotes the Tiller version, so this shouldn't be revved in this PR. If an upgrade is called for, that should probably be in a separate PR.

2018-10-10 18:22 UTC, krancour commented on stable/magic-namespace/Chart.yaml
> +version: 0.2.1
Since this is a new feature, we should rev the minor (middle) digit; not the patch (last).

2018-10-10 18:23 UTC, krancour commented on stable/magic-namespace/README.md
> +| `namespace.name` | Specify a namespace to be created and used, overriding the one on the command line | |
I see what you're trying to accomplish here by lumping all the properties of a namespace under a namespace "object," but this is, unfortunately, a breaking change-- can't do it.

2018-10-11 09:00 UTC, alvgarvilla commented on stable/magic-namespace/Chart.yaml
> +appVersion: 2.8.2
@krancour thanks for the comment.  `appVersion ` refers to the version of the app it contains (https://github.com/helm/helm/blob/master/docs/charts.md#the-appversion-field). But yes, I should not have increased.

2018-10-11 09:02 UTC, alvgarvilla commented on stable/magic-namespace/README.md
> +| `namespace.name` | Specify a namespace to be created and used, overriding the one on the command line | |
@krancour completely understand and agree since it is a minor change, I will figure something out to keep the namespace object as it is now.

2018-10-11 09:03 UTC, alvgarvilla commented on stable/magic-namespace/Chart.yaml
> +version: 0.2.1
Cool! will be changed in next commits

2018-10-11 09:38 UTC, alvgarvilla commented
@krancour Fixed above issues!

2018-10-15 09:04 UTC, alvgarvilla commented
Hi @krancour / @prydonius , any concern/recommendations about this PR? Fixed @krancour comments. Thanks!!

2018-10-15 23:10 UTC, krancour requested changes

2018-10-15 23:10 UTC, krancour commented on stable/magic-namespace/values.yaml
> +namespace: default
This line should remain commented because specifying a value here significantly alters the behavior of this chart-- specifically, it overrides whatever namespace might have been specified on the command line. That somewhat unconventional behavior should remain opt-in.

2018-10-15 23:11 UTC, krancour commented on stable/magic-namespace/values.yaml
> +namespace: default
Sorry... I thought I gave this feedback days ago and just discovered the comment was "pending."

2018-10-17 20:36 UTC, krancour commented
@alvgarvilla lgtm. Thank you!

/approve
/lgtm

2018-10-25 11:34 UTC, davidarcher commented
@krancour or any team member: can we get an ok-to-test on this so it can move forward pls?

2018-10-25 13:30 UTC, merged