Add support for additional secret, initContainers, postStart command and deployment annotations
helm/charts pull request #8338
Opened 2018-10-10 16:00 UTC by faizanahmad055

Signed-off-by: Faizan Ahmad
username: faizanahmad055
email: faizan.ahmad55@outlook.com

#### What this PR does / why we need it:
This PR adds following in sonatype-nexus chart
- support for additional secrets
- support for init containers in the deployment
- support for postStart command in nexus container
- support for deployment annotations
- support for timeoutSeconds for livenessProb and readinessProbe

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-10-10 16:03 UTC, faizanahmad055 commented
Hi @rjkernick, Can you please take a look.

2018-10-12 17:10 UTC, rjkernick commented
/ok-to-test
/assign

2018-10-12 18:45 UTC, faizanahmad055 commented
Hi @rjkernick ,

I've pushed one more commit can you please take a look.
This commit includes
- Support for additional containers
- Support for additional volumes
- Separate Exposed port and nexus-proxy container port.

The purpose of adding additional container and volumes is to provide the support of running extra sidecars. For example, I want to run keycloak container for nexus SSO authentication so I can add this using additional containers and volumes.

2018-10-12 19:32 UTC, rjkernick requested changes

2018-10-12 19:32 UTC, rjkernick commented on stable/sonatype-nexus/README.md
> +| `nexusProxy.exposedPort`                    | Port for exposing Nexus             | `8080`                                  |
I'd rather see this as port and targetPort to match the yaml

2018-10-15 12:48 UTC, rjkernick approved these changes

2018-10-15 13:10 UTC, rjkernick commented
/lgtm

2018-10-15 13:12 UTC, merged