Add imagePullSecrets to fluent-bit for use with private registry
helm/charts pull request #8391
Opened 2018-10-12 13:42 UTC by donbowman

Other helm charts (e.g. Kibana) use image.imagePullSecrets,
model after them.

Signed-off-by: Don Bowman <db@donbowman.ca>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x ] Chart Version bumped
- [ x] Variables are documented in the README.md

2018-10-12 21:43 UTC, davidkarlsen requested changes

2018-10-12 21:43 UTC, davidkarlsen commented on stable/fluent-bit/Chart.yaml
> +version: 0.12.1
new feature . set 0.13.0

2018-10-12 21:43 UTC, davidkarlsen commented
/assign
/ok-to-test

2018-10-12 22:40 UTC, donbowman commented on stable/fluent-bit/Chart.yaml
> +version: 0.12.1
done

2018-10-13 16:41 UTC, davidkarlsen approved these changes

2018-10-13 16:41 UTC, davidkarlsen commented
/lgtm

2018-10-13 16:48 UTC, davidkarlsen commented
/retest

2018-10-13 16:50 UTC, merged