[stable/consul] Add post-install hook to configure basic acls
helm/charts pull request #8393
Opened 2018-10-12 14:12 UTC by Redlinkk

Signed-off-by: Romain Poirot <romain.poirot@supelec.fr>

#### What this PR does / why we need it:
This PR creates an optional post-install hook which can configure basic ACLs rules to allow cluster nodes to work correctly, and to allow the liveness probe to succeed, so k8s doesn't reboot pods eternally.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-15 17:25 UTC, paulczar requested changes
this is adding features so should be a minor release, not a patch.

2018-11-29 14:12 UTC, Redlinkk commented
@paulczar sorry for the late correction. Version should be good now

2018-12-17 18:43 UTC, paulczar approved these changes

2018-12-17 18:44 UTC, paulczar commented
/lgtm

2018-12-17 19:10 UTC, merged