Add GitLab-EE (Enterprise Edition) 9.0.0
helm/charts pull request #854
Opened 2017-03-23 21:02 UTC by kwent

- Synced with GitLab-CE 9.0.0 version 0.1.6
- Tested on my minikube.

2017-03-25 03:57 UTC, kwent commented
Anyone to trigger tests ?

2017-03-26 17:57 UTC, seanknox requested changes

2017-03-26 17:57 UTC, seanknox commented on stable/gitlab-ee/README.md
> +
You'll need to replace the Community Edition references with Enterprise Edition.

2017-03-26 18:11 UTC, kwent commented
@seanknox My bad i thought i replaced everywhere. Fixed 👍

2017-03-27 18:06 UTC, seanknox commented
Thanks @kwent! FWIW this PR looks OK to me, but couldn't truly test as I don't have a GitLab EE account.

2017-03-27 18:23 UTC, kwent commented
@seanknox Nothing prevents you to install GitLab EE. You don't need a GitLab EE account, you need to put a license otherwise a lot of features are disabled (you can unblock them with a trial license if you really want to https://about.gitlab.com/free-trial/) otherwise GitLabEE without a license is basically GitlabCE.

2017-03-29 18:21 UTC, kwent commented
Good to test/merge ? 9.0.1 is already out there...

2017-04-03 22:22 UTC, seanknox approved these changes

2017-04-03 22:30 UTC, merged