Add external ip and port variables
helm/charts pull request #855
Opened 2017-03-23 22:42 UTC by tarasglek

This lets one expose the service on external ip and a custom port number

2017-03-31 21:25 UTC, unguiculus requested changes

2017-03-31 21:25 UTC, unguiculus commented on stable/postgresql/templates/svc.yaml
> +  {{- end }}
You should remove the if statements and add defaults to the values.yaml.

2017-04-03 19:53 UTC, linki commented
@tarasglek do you want to sign the CLA so we can take in your changes?

2017-04-19 15:02 UTC, prydonius commented
@tarasglek are you able to continue working on this?

2017-04-19 20:53 UTC, tarasglek commented
@prydonius 
yes sorry, missed the earlier notifications that you guys were looking at this change. I'll submit the pullreq without conditionals as requested

2017-04-19 21:46 UTC, tarasglek commented
@unguiculus I got rid of if statements.
`--set 'service.externalIPs=["192.168.50.4"],service.port=5433'`
works, but I'm not sure how one would pass multiple IPs since `,` is already used a param separator

2017-04-24 18:55 UTC, unguiculus commented
@tarasglek Here's an example for externalIPs: https://github.com/kubernetes/charts/blob/e60c6e9d6d0b3cf67291769a940a60f42521fdf5/stable/nginx-ingress/templates/controller-service.yaml#L18

2017-04-25 15:20 UTC, tarasglek commented
@unguiculus thanks, that's similar to how I implemented it. Can I get this merged?

2017-04-25 15:52 UTC, unguiculus commented
@tarasglek Well, the way you implemented it forces one to use the one-line format for a list, which is uncommon. I'd suggest you change it.

2017-04-28 20:58 UTC, tarasglek commented
@unguiculus thanks for explaining. I'm new to yaml. This change is more inline with nginx example

2017-05-04 20:18 UTC, tarasglek commented
Ping, can this be merged?

2017-05-18 16:17 UTC, prydonius commented
@k8s-bot ok to test

2017-05-18 16:20 UTC, merged

2017-05-18 16:20 UTC, prydonius commented
Thanks @tarasglek!!