Adding Metacontroller to incubator charts
helm/charts pull request #8591
Opened 2018-10-19 03:42 UTC by willnewby

#### What this PR does / why we need it:
This PR adds Metacontroller, an addon for creating your own controllers in Kubernetes

#### Special notes for your reviewer:
I previously signed the CLA? Do I also need to sign the DCO?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [?] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

2018-10-19 20:08 UTC, willnewby commented
/assign @davidkarlsen 

(as recommended by the bot)

2018-10-24 16:03 UTC, willnewby commented
Hello?

2018-10-24 17:38 UTC, davidkarlsen requested changes

2018-10-24 17:38 UTC, davidkarlsen commented on incubator/metacontroller/templates/rbac.yaml
> +{{ if .Values.rbac.create }}
split these into three resource-template files:
- serviceaccount
- role
- rolebinding

2018-10-24 17:38 UTC, davidkarlsen commented on incubator/metacontroller/templates/statefulset.yaml
> +apiVersion: apps/v1beta2
use v1

2018-10-24 17:38 UTC, davidkarlsen commented on incubator/metacontroller/values.yaml
> +  name: metacontroller
See https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md for the name and other rbac info

2018-10-24 17:38 UTC, davidkarlsen commented on incubator/metacontroller/templates/rbac.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
use v1

2018-10-24 17:38 UTC, davidkarlsen commented on incubator/metacontroller/templates/crds.yaml
> +apiVersion: apiextensions.k8s.io/v1beta1
See https://docs.helm.sh/developing_charts/ for installing CRDs

2018-10-24 17:38 UTC, davidkarlsen commented on incubator/metacontroller/README.md
> +# Metacontroller
aim straight for the stable repo and skip incubating

2018-10-25 20:05 UTC, willnewby commented on stable/metacontroller/templates/crds.yaml
> +  annotations:
I believe this is the correct way to install these @davidkarlsen, but please let me know if there's some other change I need to make.

2018-10-29 16:33 UTC, willnewby commented
Hello?

2018-10-29 23:57 UTC, davidkarlsen requested changes

2018-10-29 23:57 UTC, davidkarlsen commented on stable/metacontroller/templates/rolebinding.yaml
> +{{ if .Values.serviceAccount.create }}
this does not depend on serviceAccount.create - only rbac.create, see https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md

2018-10-29 23:57 UTC, davidkarlsen commented on stable/metacontroller/templates/serviceaccount.yaml
> +{{ if .Values.rbac.create }}
https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md
this only depends on serviceAccount.create

2018-10-29 23:57 UTC, davidkarlsen commented on stable/metacontroller/README.md
> +$ helm install incubator/metacontroller --name my-release -f values.yaml
stable

2018-10-29 23:57 UTC, davidkarlsen commented on stable/metacontroller/Chart.yaml
> +version: 0.1.0
let it be 1.0.0

2018-10-31 16:57 UTC, willnewby commented
Ready for re-review.

2018-11-05 08:37 UTC, davidkarlsen commented
/ok-to-test

2018-11-05 08:38 UTC, davidkarlsen approved these changes

2018-11-05 08:51 UTC, davidkarlsen commented
/lgtm

2018-11-05 10:52 UTC, davidkarlsen commented
/retest

2018-11-05 11:03 UTC, davidkarlsen commented
/lgtm cancel

2018-11-05 11:04 UTC, davidkarlsen commented
@willnewby Can you have a look at the failing tests?

2018-11-13 19:31 UTC, benjigoldberg commented
/retest

2018-12-29 08:10 UTC, closed without merging

2019-03-09 03:49 UTC, yinzara commented
Any chance this could be finished?

2019-03-09 04:12 UTC, willnewby commented
The chart works and I use it personally, it just doesn't pass the e2e
tests.
---------------
Will Newby
Resident Wizard
Phone: 612.208.3806
Email: willnewby@gmail.com


On Fri, Mar 8, 2019 at 10:49 PM Matthew Morrissette <
notifications@github.com> wrote:

> Any chance this could be finished?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/helm/charts/pull/8591#issuecomment-471142528>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABQLP5itXiP4Dqb-dw5iy-n_Ck16fcIAks5vUy9lgaJpZM4XvnlV>
> .
>

2019-03-19 15:54 UTC, mattfarina commented
The helm hub allows for external charts repos to list their charts. Would be great to get it in there

2019-03-19 16:55 UTC, willnewby commented
@mattfarina I'll take a look at getting this added to helm hub. Thanks!

2019-03-30 01:50 UTC, luisdavim commented
Is this abandoned?

2019-05-07 13:06 UTC, blancsys commented
@willnewby Hi, this is a great work, congratulations. Are you migrating this chart to hub.helm.sh? Where I can find the latest version of this chart? Thanks

2019-05-09 04:23 UTC, willnewby commented
@blancsys I put up a pull request to add a repo with it to hub.helm.sh here https://github.com/helm/hub/pull/81

@luisdavim it is not abandoned, I use and maintain it.

2019-05-09 22:23 UTC, blancsys commented
@willnewby Great thanks