[stable/aerospike] Add load balancer source ranges
helm/charts pull request #8604
Opened 2018-10-19 13:05 UTC by FlavioF

#### What this PR does / why we need it:
It add support to setup k8s service [loadBalancerSourceRanges](https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/) in order to restrict access for LoadBalancer Service.

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-16 17:09 UTC, paulczar commented
/ok-to-test

2018-11-16 17:10 UTC, paulczar requested changes

2018-11-16 17:10 UTC, paulczar commented on stable/aerospike/Chart.yaml
> +version: 0.1.8
should be a minor release change `0.2.0` rather than a patch.

2018-11-21 13:42 UTC, FlavioF commented
Done @paulczar

2018-12-17 18:46 UTC, paulczar commented
/lgtm

2018-12-17 19:18 UTC, merged