[stable/prometheus] Add extraHostPathMounts config
helm/charts pull request #862
Opened 2017-03-27 05:12 UTC by yuanying

* Add nodeExporter.extraHostPathMounts to prometheus

2017-03-27 06:44 UTC, yuanying commented
Hi, I want to use [textfile collector](https://github.com/prometheus/node_exporter#textfile-collector) for node-exporter. But currently it seems that there are no way to share textfile metrics data between other pod which collect another metrics.

So, how about to add extraMounts option to node-exporter to share such data?

2017-05-30 19:20 UTC, mgoodness commented
@k8s-bot ok to test

2017-05-30 19:21 UTC, mgoodness requested changes

2017-05-30 19:21 UTC, mgoodness commented on stable/prometheus/values.yaml
> +  extraHostPathMounts: []
Let's get this array documented in the chart's README.

2017-05-30 19:21 UTC, mgoodness commented on stable/prometheus/values.yaml
> +  extraHostPathMounts: []
Needs to be added to the chart's README.

2017-05-31 04:37 UTC, yuanying commented on stable/prometheus/values.yaml
> +  extraHostPathMounts: []
Thanks for reviewing.
I have added document to README.

2017-06-02 01:41 UTC, mgoodness approved these changes

2017-06-02 01:44 UTC, merged