Helm chart for kuberhealthy 0.1.1
helm/charts pull request #8638
Opened 2018-10-22 18:32 UTC by integrii

Signed-off-by: Eric Greer <eric.greer@comcast.com>

Satisfies https://github.com/Comcast/kuberhealthy/issues/26

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-10-23 16:10 UTC, integrii commented
circleci above shows a generic error, but helm lint does in fact pass on this chart.

![image](https://user-images.githubusercontent.com/98695/47374712-73771f00-d6a3-11e8-87a4-305a2a828e24.png)

2018-10-29 17:40 UTC, integrii commented
@unguiculus @seanknox May I have a review please? :-)

2018-11-05 17:39 UTC, integrii commented
@unguiculus @seanknox Help please!  We are blocked on product release without this chart being approved.

2018-11-16 18:20 UTC, nvtkaszpir commented on stable/kuberhealthy/templates/clusterrolebinding.yaml
> +  namespace: kuberhealthy
I suggest to fix missing newline.

2018-11-16 18:20 UTC, nvtkaszpir commented on stable/kuberhealthy/templates/clusterrole.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
Please try to use v1  API if possible.

2018-11-16 18:48 UTC, integrii commented
@nvtkaszpir I moved several things to the more current kubernetes versions . Thanks for pointing that out!
I also added a newline in that one file.

2018-11-19 22:40 UTC, integrii commented
@nvtkaszpir Can you get some forward movement on publishing this for me?

2018-11-19 23:31 UTC, nvtkaszpir commented
Unfortunately I have no power to push any PRs forward, you can ask owners for review on github/slack. Please to fix build issues first.

2018-11-19 23:33 UTC, nvtkaszpir commented
Unfortunately I have no power to push any PRs forward, you can ask owners for review on github/slack. Please to fix build issues first, notice that maintainers must point to github accounts, unfortunately.

2018-11-26 21:20 UTC, integrii commented
Thanks @nvtkaszpir.  The prior builds were erroring out, so the build that happened most recently was the first time I was actually able to see the errors.

I will work on those and then ping people on slack again.  Thank you!

2018-11-26 22:54 UTC, integrii commented
@unguiculus and @seanknox can you please review my chart? :-)

2018-12-09 02:14 UTC, integrii commented
@unguiculus and @seanknox help! Please review!

2018-12-09 14:39 UTC, unguiculus commented
Please make sure you apply our guidelines (e. g. standard labels on all resources) and our RBAC best practices.

https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md
https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md

2018-12-11 03:59 UTC, integrii commented
Thank you @unguiculus.  I have made the requested changes and now include all the recommended labels and variables.  I also added an `OWNERS` file and helpers for things like RBAC.  Is there anything else you would like to see changed?

 @seanknox 

Are you guys at kubecon this week?  I am there!

2018-12-12 23:19 UTC, viglesiasce requested changes
Remove PNG hinary

2018-12-13 00:05 UTC, closed without merging