Updated apiVersions and fixed doc
helm/charts pull request #8672
Opened 2018-10-23 22:32 UTC by yuchaoran2011

2018-10-23 22:35 UTC, yuchaoran2011 commented
/assign liyinan926

2018-10-23 22:37 UTC, yuchaoran2011 commented
@foxish @ liyinan926 Some minor updates that I thought about while working on another chart. Please take a look. Thanks!

2018-10-23 22:40 UTC, liyinan926 commented
/lgtm
/approve

2018-10-23 22:42 UTC, yuchaoran2011 commented
@liyinan926 Thanks for the quick review. But apparently adding your Github username in `OWNERS` didn't give you the needed permission. It didn't work for me either.

2018-10-23 22:48 UTC, liyinan926 commented
@yuchaoran2011 at least it does not grant permission to change assignee. I cannot give lgtm unless I'm the asignee.

2018-10-24 17:25 UTC, davidkarlsen requested changes

2018-10-24 17:25 UTC, davidkarlsen commented on incubator/sparkoperator/Chart.yaml
>  appVersion: latest
```suggestion
appVersion: v2.3.1-v1alpha1-latest
```

2018-10-24 18:51 UTC, yuchaoran2011 commented
@liyinan926 I saw that you cut a release `v1alpha1-0.4-2.3.x` yesterday. So I updated `appVersion` to use that. @davidkarlsen Your comment is now addressed. Thanks!

2018-10-24 19:18 UTC, liyinan926 commented
@yuchaoran2011 Thanks! The image `gcr.io/spark-operator/spark-operator:v2.3.1-v1alpha1-latest` has been updated.

2018-10-26 01:17 UTC, yuchaoran2011 commented
/assign liyinan926

2018-10-26 01:43 UTC, yuchaoran2011 commented
/assign liyinan926

2018-10-26 01:44 UTC, liyinan926 commented
/assign

2018-10-26 01:45 UTC, liyinan926 commented
/lgtm
/approve

2018-10-26 01:48 UTC, merged