[incubator/corturn] New chart for coturn service on incubator
helm/charts pull request #8676
Opened 2018-10-24 06:29 UTC by wolmi

Signed-off-by: Miquel Ramon Ortega Tido <lenyos@gmail.com>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-10-26 11:04 UTC, wolmi commented
/assign @unguiculus

2018-10-31 19:00 UTC, unguiculus requested changes
I'd suggest you move the chart to stable.

2018-10-31 19:00 UTC, unguiculus commented on incubator/coturn/templates/deployment.yaml
> +apiVersion: apps/v1beta2
Use `apps/v1`

2018-10-31 19:00 UTC, unguiculus commented on incubator/coturn/values.yaml
> +  tag: stable
Use a stable tag.

2018-10-31 19:00 UTC, unguiculus commented on incubator/coturn/templates/config.yaml
> +    {{ template "config_turnserver" .Values.config }}
Please indent two spaces.

2018-11-14 08:09 UTC, wolmi commented on incubator/coturn/values.yaml
> +  tag: stable
Sorry, I don't understand dis comment, I'm now using a "stable" tag, do you want me to use some other format?

2018-11-14 08:15 UTC, wolmi commented on incubator/coturn/templates/deployment.yaml
> +apiVersion: apps/v1beta2
Done

2018-11-14 08:15 UTC, wolmi commented on incubator/coturn/templates/config.yaml
> +    {{ template "config_turnserver" .Values.config }}
Done

2018-12-14 13:51 UTC, unguiculus commented on incubator/coturn/values.yaml
> +  tag: stable
Just because it is named `stable` doesn't mean it is stable. You should use a concrete version.

2019-01-17 01:44 UTC, wolmi commented on incubator/coturn/values.yaml
> +  tag: stable
Understand, I changed the image version to 0.1

2019-02-04 19:47 UTC, unguiculus requested changes
I'd suggest you move the chart to stable and give it a `1.0.0`. We tend to move away from incubator here. Could you please update the chart to use the new label conventions?

See https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#names-and-labels

2019-02-04 19:47 UTC, unguiculus commented on incubator/coturn/templates/_helpers.tpl
> +{{- define "config_turnserver" -}}
All helper templates should be prefixed with `coturn`. Also, please use camel case.

`coturn.configTurnserver`

2019-04-03 11:41 UTC, closed without merging