[stable/traefik] Traefik accesslogs filters
helm/charts pull request #8694
Opened 2018-10-24 13:23 UTC by kenichi-shibata

#### What this PR does / why we need it:

It enables traefik accessLogs filters documented [here](https://docs.traefik.io/configuration/logs/)

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-10-25 15:58 UTC, dtomcej requested changes

2018-10-25 15:58 UTC, dtomcej commented on stable/traefik/templates/configmap.yaml
> +      statusCodes = [{{ range $_, $value := .Values.accessLogs.filters.statusCodes }}"{{ $value }}",{{ end }}]
```suggestion
      statusCodes = [{{ range $_, $value := .Values.accessLogs.filters.statusCodes }}{{ $value | quote }},{{ end }}]
```

2018-10-26 09:00 UTC, kenichi-shibata commented
/retest

2018-10-26 09:06 UTC, rimusz commented
chart needs a version bump

2018-10-26 09:36 UTC, rimusz commented
/lgtm

2018-10-29 08:48 UTC, mmatur requested changes

2018-10-29 08:48 UTC, mmatur commented on stable/traefik/Chart.yaml
> +version: 1.52.4
```suggestion
version: 1.52.5
```

2018-10-30 12:13 UTC, closed without merging