- Adding affinity for kubernetes-dashboard
helm/charts pull request #8713
Opened 2018-10-24 20:37 UTC by ahma

- version bump

Signed-off-by: Ferenc HERNADI <ferenc.hernadi@gmail.com>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-10-24 21:16 UTC, davidkarlsen requested changes

2018-10-24 21:16 UTC, davidkarlsen commented on stable/kubernetes-dashboard/values.yaml
> +affinity: {}
```suggestion
affinity: []
```

2018-10-24 21:17 UTC, davidkarlsen commented
/assign

2018-10-25 08:04 UTC, rimusz reviewed
this commits is missing signoff

2018-10-27 13:06 UTC, ahma commented
@davidkarlsen ff I can do anything else please let me  know. 
Thanks Feri!

2018-10-29 23:50 UTC, davidkarlsen commented
@ahma There seems to be some unrelated keel changes?

2018-10-30 08:37 UTC, davidkarlsen requested changes

2018-10-30 08:37 UTC, davidkarlsen commented on stable/kubernetes-dashboard/Chart.yaml
> +version: 0.7.6
```suggestion
version: 0.8.0
```

new feature

2018-10-30 08:37 UTC, davidkarlsen commented
/ok-to-test

2018-11-04 13:48 UTC, davidkarlsen approved these changes

2018-11-04 13:48 UTC, davidkarlsen commented
/lgtm

2018-11-04 14:02 UTC, merged