[stable/fluentd-elasticsearch] Adding support for the logstash_prefix option
helm/charts pull request #8759
Opened 2018-10-25 17:47 UTC by cidrick

Signed-off-by: Matt Renfrow <mrenfrow@expedia.com>

#### What this PR does / why we need it:

This PR adds support for setting the `logstash_prefix` option for the Elasticsearch output plugin for fluentd. Without being able to set this option, all logs will be sent to an index pattern of `logstash-YYMMDD`, which is undesirable when using a mixed-use Elasticsearch environment.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-04 20:42 UTC, unguiculus commented
cc @monotek

2018-11-04 20:42 UTC, unguiculus commented
/ok-to-test

2018-11-04 21:32 UTC, monotek commented
/lgtm

2018-11-08 21:14 UTC, cidrick commented
/assign @monotek

2018-11-08 21:39 UTC, cidrick commented
@unguiculus I believe this is just waiting for your sign-off :)

2018-11-16 17:12 UTC, paulczar requested changes
to pass tests we need the volume name here to be shortened ...   would do that in the template helpers.

```
Error: release fluentd-elasticsearch-ff5f0rdix3 failed: DaemonSet.apps "fluentd-elasticsearch-ff5f0rdix3-fluentd-elasticsearch" is invalid: [spec.template.spec.volumes[3].name: Invalid value: "config-volume-fluentd-elasticsearch-ff5f0rdix3-fluentd-elasticsearch": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[3].name: Not found: "config-volume-fluentd-elasticsearch-ff5f0rdix3-fluentd-elasticsearch"]
```

2018-11-19 16:53 UTC, cidrick commented
/retest

2018-11-19 17:10 UTC, cidrick commented
/retest

2018-11-19 17:13 UTC, monotek commented
/lgtm

2018-11-19 17:16 UTC, merged