Fix Prometheus and Alertmanager templates to support routePrefix
helm/charts pull request #8760
Opened 2018-10-25 17:54 UTC by gmichels

Fix Prometheus and Alertmanager templates to support routePrefix.

Credit goes to @kovszilard as pretty much all information was taken from https://github.com/coreos/prometheus-operator/issues/1596

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

2018-10-25 17:56 UTC, gmichels commented
/assign @gianrubio

2018-10-26 06:54 UTC, vsliouniaev commented
Hey @gmichels could you fix the sign-off on `68cf08a` ?

2018-10-26 10:46 UTC, vsliouniaev requested changes
Alertmanager part works
- can access alertmanager only on specified prefix
- grafana works
- prometheus sends alerts to and scrapes alertmanager

Prometheus needs a change to its ingress configuration to also apply the prefix

2018-10-26 10:46 UTC, vsliouniaev commented on stable/prometheus-operator/templates/alertmanager/ingress.yaml
> +{{- $routePrefix := .Values.alertmanager.alertmanagerSpec.routePrefix }}
Would you mind applying a similar fix in  `/templates/prometheus/ingress.yaml` ?

2018-10-26 10:46 UTC, vsliouniaev commented on stable/prometheus-operator/templates/alertmanager/servicemonitor.yaml
> +    {{- end }}
You could turn this into a one-liner by leveraging `trimSuffix`

2018-10-26 10:46 UTC, vsliouniaev commented on stable/prometheus-operator/templates/prometheus/servicemonitor.yaml
> +    {{- end }}
Same as above, you could use `trimSuffix` here

2018-10-26 16:35 UTC, gmichels commented on stable/prometheus-operator/templates/alertmanager/ingress.yaml
> +{{- $routePrefix := .Values.alertmanager.alertmanagerSpec.routePrefix }}
Thanks for catching this. For some odd reason it was working when going to my ingress with /prometheus, although I had noticed the lack of the `path` property in the ingress definition.

2018-10-26 16:36 UTC, gmichels commented on stable/prometheus-operator/templates/alertmanager/servicemonitor.yaml
> +    {{- end }}
Done, thanks for the suggestion.

2018-10-26 16:36 UTC, gmichels commented on stable/prometheus-operator/templates/prometheus/servicemonitor.yaml
> +    {{- end }}
Done, thanks for the suggestion.

2018-10-26 16:38 UTC, vsliouniaev commented on stable/prometheus-operator/templates/alertmanager/ingress.yaml
> +{{- $routePrefix := .Values.alertmanager.alertmanagerSpec.routePrefix }}
It also worked when I tested it with the Istio configuration we have but it seemed odd. Didn't work on pure ingress though

2018-10-26 16:39 UTC, vsliouniaev commented
Looks like this is working on my machine.

Could you fix the sign-off on `68cf08a8d1ed788ec3258ba0b7b73069de6dedff` and update the chart version again? (there was a merge while your PR was open)

2018-10-26 17:09 UTC, gmichels commented
I am trying to find a way to sign-off on a single commit, but all I can find is a way to sign-off on all of my commits, which would result in double sign-offs on all commits except `68cf08a8d1ed788ec3258ba0b7b73069de6dedff`.

Do you have a command handy to sign-off on a specific previous commit? Or if you are good with me double signing-off on all commits, that will work as well.

2018-10-26 17:32 UTC, vsliouniaev commented
No matter what you do all commits will be rewritten and history will be lost so you can squash all your commits into one.
A double sign-off will not have ill effects.
You can use interactive rebase to do so `git rebase origin/master -i` and then add the line to the single commit.

2018-10-26 17:50 UTC, gmichels commented
Rebased, sign-off added and chart version bumped.

2018-10-26 18:21 UTC, vsliouniaev commented
Please fix CI

2018-10-26 18:42 UTC, gmichels commented
Sorry, first PR ever here, so I am learning as I go.

2018-10-26 20:59 UTC, vsliouniaev commented
@gmichels if you find me (vas) on kubernetes.slack.com I can help you out

2018-10-27 20:09 UTC, gmichels commented
@vsliouniaev thanks for the help, will do that on Monday. Or if you feel it would be better, I can simply close this and submit a fresh PR.

2018-10-30 18:54 UTC, gianrubio commented
/ok-to-test
/lgtm

2018-10-30 18:57 UTC, gianrubio commented
@gmichels please fix CI

2018-10-30 20:30 UTC, gmichels commented
@gianrubio fixed, thanks

2018-11-02 11:20 UTC, gmichels commented
Hey @gianrubio, just wondering if there is anything left for me to do to get this merged? Thank you

2018-11-02 12:09 UTC, gianrubio commented
/ok-to-test
/lgtm

2018-11-02 12:14 UTC, merged