Make nodeSelector, storage-class configurable
helm/charts pull request #880
Opened 2017-04-04 05:56 UTC by joar

This is my first patch to a Go template ever, feedback welcome!

The aim with this PR is to make nodeSelector and storage-class configurable when installing the patroni chart.

2017-04-04 06:06 UTC, joar commented
CLA signed, I expect that the bot will update the CLA status once it refreshes.

2017-04-04 09:55 UTC, linki commented on incubator/patroni/templates/statefulset-patroni.yaml
> +        volume.alpha.kubernetes.io/storage-class: {{default "default" .Values.StorageClass }}
This should to be `beta` then. Also, there's a pattern in other charts for this matter that we may want to use here as well.

2017-04-28 12:23 UTC, joar commented on incubator/patroni/templates/statefulset-patroni.yaml
> +        volume.alpha.kubernetes.io/storage-class: {{default "default" .Values.StorageClass }}
Do you have any resources/references for the storage class pattern?

2017-04-28 22:17 UTC, joar commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.kubernetes.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/charts/880)
<!-- Reviewable:end -->

2017-05-05 05:07 UTC, viglesiasce commented on incubator/patroni/templates/statefulset-patroni.yaml
> +        volume.alpha.kubernetes.io/storage-class: {{default "default" .Values.StorageClass }}
@joar check out the prometheus chart:
https://github.com/kubernetes/charts/blob/master/stable/prometheus/templates/alertmanager-deployment.yaml#L72

2017-05-05 05:07 UTC, viglesiasce commented
@k8s-bot ok to test

2017-05-10 09:14 UTC, joar commented
@viglesiasce Pushed a commit for the persistentVolume pattern from prometheus, although I modified it slightly to make the PVC non-optional since it was slightly easier and I'm pressed for time.

2017-06-01 10:52 UTC, prydonius requested changes
Thanks! Can you also bump the minor version?

2017-06-01 10:52 UTC, prydonius commented on incubator/patroni/values.yaml
add commented `NodeSelector` example

2017-06-08 10:54 UTC, prydonius approved these changes
lgtm

2017-06-08 11:00 UTC, prydonius commented
@linki want to give this a quick look?

2017-06-08 11:01 UTC, prydonius commented on incubator/patroni/Chart.yaml
> +version: 0.2.1
can we add an appVersion @linki?

2017-06-08 11:01 UTC, prydonius commented on incubator/patroni/Chart.yaml
>    - https://github.com/zalando/patroni
what github ids can we use for the maintainers?

2017-06-08 11:25 UTC, linki commented on incubator/patroni/Chart.yaml
> +version: 0.2.1
done

2017-06-08 11:27 UTC, linki commented on incubator/patroni/Chart.yaml
> +version: 0.2.1
Well, wait, I have to double check

2017-06-08 11:31 UTC, linki commented on incubator/patroni/Chart.yaml
> +version: 0.2.1
@alexeyklyukin I'm wondering should we use the spilo version (1.0-p5 etc., 1.2-p8, ...) or the patroni version (1.2.5)?

2017-06-08 11:51 UTC, prydonius commented on incubator/patroni/Chart.yaml
> +version: 0.2.1
For the Bitnami images we use tag with the format `<upstream version>-r<image version>`, e.g. `1.2.3-r1`. For these, I've just been using the upstream version as the appVersion.

2017-06-12 14:50 UTC, linki commented on incubator/patroni/Chart.yaml
> +version: 0.2.1
Talked to @alexeyklyukin and he recommends using the spilo version.

2017-06-12 14:54 UTC, linki commented on incubator/patroni/Chart.yaml
> +version: 0.2.1
Since the volume template section changed, upgrading this chart will break people's installations (I guess). Should we rather bump the minor version?

2017-07-05 21:07 UTC, merged