[locust] Update Readme, url and logo
helm/charts pull request #881
Opened 2017-04-04 07:18 UTC by so0k

Add url and logo to chart description

2017-04-06 08:58 UTC, so0k commented
I just noticed the README still mentions this chart being in `incubator` - but it was already moved to `stable`

2017-04-06 10:08 UTC, prydonius requested changes
@so0k will make the changes described in https://github.com/kubernetes/charts/pull/891/files#r109957618

2017-04-06 10:08 UTC, prydonius commented on stable/locust/Chart.yaml
>  description: A chart for locust distributed load testing
I updated this to "A modern load testing framework" from the website, but up to you. As long as we remove the "A chart for" part, anything is fine.

2017-04-06 10:09 UTC, prydonius commented
> I just noticed the README still mentions this chart being in incubator - but it was already moved to stable

Yes, please update the readme to reference the stable repo too in this PR.

2017-04-16 07:21 UTC, so0k commented
rebased and updated to include the changes requested

2017-04-17 07:22 UTC, so0k commented
@prydonius - let me know if there is anything still missing

2017-04-19 17:03 UTC, prydonius approved these changes

2017-04-19 17:03 UTC, prydonius commented
LGTM, thanks a lot @so0k!

2017-04-20 16:57 UTC, merged