Remove nodeport from headless service
helm/charts pull request #8810
Opened 2018-10-27 12:17 UTC by dene14

- fixes #8763

#### Special notes for your reviewer:
Fixing crap I've introduced earlier. Headless service shouldn't contain any modes other than ClusterIP.

@carrodher @desaintmartin @juan131 @prydonius @sameersbn @tompizmor

2018-10-29 09:25 UTC, juan131 commented on stable/rabbitmq/templates/svc-headless.yaml
> +  type: ClusterIP
That's the default value. It's not necessary to specify it.

2018-10-29 09:26 UTC, juan131 requested changes
Thanks for the PR!

2018-10-29 10:46 UTC, dene14 commented on stable/rabbitmq/templates/svc-headless.yaml
> +  type: ClusterIP
I though it's a best practice to have everything defined. Shall I remove?

2018-10-29 12:42 UTC, dene14 commented on stable/rabbitmq/templates/svc-headless.yaml
> +  type: ClusterIP
@juan131

2018-10-30 09:32 UTC, juan131 commented on stable/rabbitmq/templates/svc-headless.yaml
> +  type: ClusterIP
If you'd rather define it, I'd make it configurable through **values.yaml**

2018-10-30 10:15 UTC, carrodher commented
It seems a new chart version appears, can you rebase the changes and bump again the version if needed?

2018-10-30 14:22 UTC, dene14 commented
@juan131 @carrodher Ready for merge.

2018-10-30 16:12 UTC, carrodher commented
/ok-to-test
/lgtm

2018-10-30 16:16 UTC, merged