Incubator chart for mongodb exporter
helm/charts pull request #8822
Opened 2018-10-28 16:02 UTC by ananthunair

#### What this PR does / why we need it:

Currently there is no mongodb exporter chart available as standalone. This should be used indepentant of the exporter

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-10-29 04:40 UTC, ananthunair commented
/assign @prydonius

2018-10-30 09:46 UTC, ananthunair commented
/retest

2018-10-30 10:00 UTC, ananthunair commented
/assign unguiculus

2018-10-30 10:00 UTC, ananthunair commented
/assign @unguiculus

2018-10-31 18:03 UTC, unguiculus requested changes
Thanks for the PR. A few things from quickly looking over it:

* Please follow our review guidelines:
  https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md
* Please compare with what you get using `helm create` and update accordingly
* I'd suggest you move the chart to stable directly.

2018-10-31 18:43 UTC, ananthunair commented
Hi @unguiculus,

Can you review and see if the changes look good? 

Thanks in advance

2018-11-13 15:36 UTC, juan131 commented
Hi @ananthunair 

I'm not the proper person to review this contribution since it's a new chart and only the approvers listed in the OWNERS file below can approve this kind of PRs:

https://github.com/helm/charts/blob/master/OWNERS

2018-11-15 05:09 UTC, ananthunair commented
/unassign @juan131

2018-11-15 05:10 UTC, ananthunair commented
/assign foxish
Hi @foxish ,
Can you take a look at this PR?

2018-11-19 05:31 UTC, ananthunair commented
/unassign @foxish

2018-11-19 05:32 UTC, ananthunair commented
/assign @paulczar

2018-11-26 16:55 UTC, steven-sheehy requested changes
Missing README.md

2018-11-26 16:55 UTC, steven-sheehy commented on stable/prometheus-mongodb-exporter/templates/deployment.yaml
> +  replicas: {{ .Values.replicaCount }}
values.yaml has replicas, not replicaCount

2018-11-26 16:55 UTC, steven-sheehy commented on stable/prometheus-mongodb-exporter/values.yaml
> +  repository: ananthunair/mongodb_exporter
This should default to the official percona/mongodb_exporter image as its better maintained and community supported, not one that you maintain. Already, your branch is 19 commits behind.

2018-11-26 16:55 UTC, steven-sheehy commented on stable/prometheus-mongodb-exporter/values.yaml
> +  targetPort: 9216
Remove targetPort as its not used and shouldn't really be customizable

2018-11-26 16:55 UTC, steven-sheehy commented on stable/prometheus-mongodb-exporter/templates/deployment.yaml
> +              value: {{ .Values.config.auth }}
This variable is missing from the values.yaml. Also, give an example of the format as it's unclear.

2018-11-26 16:55 UTC, steven-sheehy commented on stable/prometheus-mongodb-exporter/templates/deployment.yaml
> +              containerPort: 80
Why port 80 is exposed? It looks like the default listening port for exporter is [9216](https://github.com/percona/mongodb_exporter/blob/61e655e36c5ce4215d1732ce769fb591b82aa7b5/mongodb_exporter.go#L46).

2018-11-26 16:55 UTC, steven-sheehy commented on stable/prometheus-mongodb-exporter/values.yaml
> +  prometheus.io/scrape: "true"
Should these annotations be on the service instead of the deployment?

2019-01-09 23:14 UTC, closed without merging