[stable/fluent-bit] Fix indentation of extra params
helm/charts pull request #8825
Opened 2018-10-28 17:49 UTC by naseemkullah

#### What this PR does / why we need it:

Using the extra outputs value, configmap would be produced like this:

```
    [OUTPUT]
        Name  es
        Match *
        Host  elasticsearch-client
        Port  9200
        Logstash_Format On
        Retry_Limit False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix kubernetes_cluster

    Replace_Dots On
```

Where the added `Replace_Dots On` is not indented properly, this PR fixes that.

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-10-29 18:15 UTC, naseemkullah commented
/assign @unguiculus

2018-10-31 18:26 UTC, unguiculus requested changes
cc @kfox1111 @edsiper

2018-10-31 18:26 UTC, unguiculus commented on stable/fluent-bit/templates/config.yaml
> +        {{ .Values.extraInputs }}
This only works for a single line. I think the correct fix would be this:

`{{ .Values.extraInputs | indent 8 }}`

2018-10-31 19:04 UTC, naseemkullah commented on stable/fluent-bit/templates/config.yaml
> +        {{ .Values.extraInputs }}
OK adjusted as per your recommendation!

2018-10-31 19:18 UTC, kfox1111 commented
yeah, this looks good.

I'm thinking we probably need a setting to disable configmap entirely and let the user load their own. As we add more and more options, it is probably easier at some point for the user just to manage the whole config file directly.

2018-10-31 19:45 UTC, naseemkullah commented
@kfox1111 
I believe that is implemented already with the `existingConfigMap: ""` value

2018-10-31 20:20 UTC, kfox1111 commented
Your right. Sorry. Guess its time to go home for the day.... :)

2018-11-01 16:31 UTC, naseemkullah commented
@unguiculus it's ready!

2018-11-01 21:50 UTC, unguiculus approved these changes

2018-11-01 21:51 UTC, unguiculus commented
/ok-to-test

2018-11-01 21:56 UTC, unguiculus commented
/lgtm

2018-11-01 22:06 UTC, merged

2018-11-05 09:58 UTC, Towmeykaw commented
This change seems to have broken the purpose of the extra settings. I created it to be able to add entire sections and not just parameters in existing sections. For example when needing multiple elasticsearch outputs

2018-11-05 13:07 UTC, naseemkullah commented
@Towmeykaw My apologies!
 I actually thought it was to add parameters to existing sections, I will open a PR shortly to revert this, as well as to include a way to add parameters to existing sections!

2018-11-05 14:15 UTC, Towmeykaw commented
Sounds great 😊👍🏼

2018-11-05 14:59 UTC, naseemkullah commented
https://github.com/helm/charts/pull/9008 created @Towmeykaw 
I'll forgo the extra params per section for now as https://github.com/helm/charts/pull/8659/ will solve my problem

2018-11-16 15:51 UTC, max-lobur commented
https://github.com/helm/charts/pull/9008#issuecomment-439433178