[stable/prometheus-operator] Allow annotations on prometheus service
helm/charts pull request #8867
Opened 2018-10-29 21:13 UTC by KierranM

#### What this PR does / why we need it:
Allows setting custom annotations on the prometheus service by setting `prometheus.service.annotations`.
The reason I'm making this change is that I have a use case where it is necessary to have an AWS NLB for the service which we have previously created using annotations on the service while using the stable/prometheus chart.

#### Special notes for your reviewer:

I've only added annotations to the prometheus service to keep the change small, but I'm happy to add them to other services/resources if desired.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-10-30 08:36 UTC, vsliouniaev commented
I think it would be useful to add this to the alertmanager configuration too, grafana already has this capability

2018-10-30 19:03 UTC, gianrubio commented
@KierranM thanks for your contribution! Would you mind to add the same annotation to alertmanager?

2018-11-01 20:47 UTC, vsliouniaev requested changes
Could you please sync up the values with the CI file as well? Apart form that I think it's good to go

2018-11-01 21:00 UTC, rajatvig commented
@KierranM I also ended up creating a similar one at https://github.com/helm/charts/pull/8966. I am ok closing that out. Could you also add options to specify `service.type` and `service.nodePort` as well?

2018-11-02 13:10 UTC, gianrubio commented
/ok-to-test
/lgtm

2018-11-05 18:55 UTC, vsliouniaev commented
@KierranM could you bump the chart version again please?

2018-11-07 16:28 UTC, rajatvig commented
@KierranM are you still working on it? my changes are blocked waiting on this.

2018-11-07 20:12 UTC, KierranM commented
Sorry been away for a few days. Bumping the version now

2018-11-07 20:45 UTC, rajatvig commented
Looks good. Will close my PR once this is in as there is not much extra in mine. Thanks @KierranM

2018-11-07 20:59 UTC, vsliouniaev approved these changes

2018-11-08 09:38 UTC, paskal requested changes
Could you please look into my comments while we still didn't got lgtm tag?

2018-11-08 09:38 UTC, paskal commented on stable/prometheus-operator/README.md
> +| `prometheus.service.type` |  Prometheus Service typre | `ClusterIP` |
typre -> type

2018-11-08 09:38 UTC, paskal commented on stable/prometheus-operator/templates/alertmanager/service.yaml
> +  {{- if .Values.alertmanager.service.annotations }}
is indentation correct?

2018-11-08 09:38 UTC, paskal commented on stable/prometheus-operator/templates/prometheus/service.yaml
> +  {{- if .Values.prometheus.service.annotations }}
is indentation correct?

2018-11-08 13:30 UTC, gianrubio commented
/ok-to-test

2018-11-09 08:50 UTC, gianrubio commented
please fix CI

2018-11-11 17:59 UTC, gianrubio commented
@KierranM CI is still broken

2018-11-11 20:36 UTC, gianrubio commented
/ok-to-test
/lgtm

2018-11-11 20:42 UTC, merged