[stable/kibana] Add kibana plugin installed control (#8581)
helm/charts pull request #8896
Opened 2018-10-30 15:05 UTC by jbdelpech

#### What this PR does / why we need it:
Checks if a plugin is already installed to avoid reinstallation and make Kibana image fail. Allows to upgrade/downgrade plugin (with control version).

#### Which issue this PR fixes
- fixes #8581

#### Special notes for your reviewer:
Tested in Kibana version 6.4.1 and 6.4.2 with elastalert plugin and logtrail plugin.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-01 10:02 UTC, compleatang commented
Thanks for the contribution @jbdelpech . Once the linter is happy I'll mark this ok for end to end testing. One thing I'd like to see as it would help stability dramatically is a plugin-install.yaml test that is added to the `ci` directory of the chart. We have those for the dashboard installation features of the chart and I think they're needed for the plugin installation as well. Not sure it will be possible to test the removal feature here, but at least a test for the installation will go a long way to ensure stability.

Thanks!

2018-11-02 08:14 UTC, jbdelpech commented
Hi @compleatang, thank for your answer and your suggestion. I added a install-plugin.yaml test file to CI (my second commit).
In my third commit, I added the possibility to force remove plugins before installing the new ones. This may prevent kibana from fails when upgrading kibana version (implies kibana plugins version upgrade as well). This is a suggestion that changing a bit the behaviour. Tell me if I should keep this in this PR or open a new one... or just delete it because it's not a good idea !

2018-11-02 10:21 UTC, compleatang commented
@jbdelpech this seems like a meaningful approach to me. 

/ok-to-test

2018-11-02 10:23 UTC, compleatang requested changes

2018-11-02 10:23 UTC, compleatang commented on stable/kibana/Chart.yaml
> +version: 0.16.5
The added functionality is a breaking change so we need to bump this to `0.17.0`

2018-11-03 01:16 UTC, compleatang commented
thanks @jbdelpech !

BTW, @unguiculus or @mattfarina  any idea why CircleCI isn't reporting?

2018-11-05 10:57 UTC, compleatang commented
This is strange. The tests have passed on Circle -> https://circleci.com/gh/helm/charts/tree/pull%2F8896 but it hasn't updated the status here. Can you push a faux commit with a blank line or whitespace somewhere @jbdelpech that will hopefully re-trigger Circle.

This is GTM, but I can't trigger the merge until we have Circle reporting back.

2018-11-05 13:02 UTC, compleatang commented
/lgtm

/approve

2018-11-05 13:02 UTC, compleatang commented
thanks @jbdelpech !!!

2018-11-05 13:03 UTC, jbdelpech commented
Thanks to you @compleatang :)

2018-11-05 13:03 UTC, merged

2018-11-07 17:06 UTC, keithlayne commented
In what situation in using this chart would a plugin already be installed?  If the pod is restarted it will need to reinstall plugins as far as I can see.  This is actually a problem for me, I'm installing a plugin via the chart and the init container has been running for an hour and a half already.

I'm just wondering what use cases cause the issue that this fixed, if someone can explain that would be great.

2018-11-08 17:00 UTC, keithlayne commented
IMO the best option at this point is to bake your own image with plugins installed and configured, and that's what I ended up doing, but still used this chart.  It seems to work well.  What you have done with this chart is awesome, but it turns out not to be practical for me.

My use case is light usage of kibana with modest memory & cpu limits.  This is fine once things are running, but the optimization step in the init container took 2 hours with my limits.  After that kibana decided it needed to optimize again, and I left that running for 2 hours until I killed it and replaced it with my custom kibana image.  That one started up quickly and runs fine with the limits I put on it.

PVCs for the plugins have 2 potential problems I can see: first (in my case at least) it would lock the pod into a single AZ in AWS.  Obviously that can be worked around in different ways, and may be a non-issue for lots of users.  The bigger issue would be if kibana still wanted to do an optimization at startup despite the plugin install like I saw.

It kinda sucks, but I think the best option as of now is to bake your plugins into your own kibana image to get the best experience.  That also made it pretty easy to add a config file in a plugin directory, which I'm not sure (didn't try) this chart is flexible enough to do right now.

Thanks for your work on this!

2018-11-08 19:10 UTC, jbdelpech commented
As you said, PVC is restrictive. I decide to customize this chart to be able to use PVC with an AWS Elastic File System (EFS) for multi AZ, instead of maintain my own Kibana image. In my case, optimization goes fast but it depends of your resources...

Some people could be interested to use a PVC with only one AZ.

At least I really don't see a perfect way to deal with Kibana plugins and generic Helm chart.

Thank for your relevant feed back :)