[stable/prometheus-mysql-exporter] to enable/disable collector flags …
helm/charts pull request #8900
Opened 2018-10-30 15:27 UTC by kilhyunjun

What this PR does / why we need it:

to enable/disable mysql-exporter collector flags from the value file.

Signed-off-by: Kilhyun Jun <Kilhyun@gmail.com>

@Juanchimienti 

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-10-30 15:31 UTC, kilhyunjun commented
/assign @sameersbn

2018-11-16 17:30 UTC, paulczar requested changes

2018-11-16 17:30 UTC, paulczar commented on stable/prometheus-mysql-exporter/templates/deployment.yaml
> +          command: ["/bin/mysqld_exporter",
should we pass these in as `args` vs in the command itself ?

2018-11-16 17:30 UTC, paulczar commented on stable/prometheus-mysql-exporter/values.yaml
> +collectors:
this should be an array to pass to args right ?  then in the deployment could use  `args: {{ args | toyaml }}`

```
args:
  - "--collect.global_status"
  - "--collect.global_variables"
```
or could even do

```
collectors:
  - global_status
  - global_variables
```

and use a helper to add the `--collect.` to the start of each one ?

2018-12-30 19:55 UTC, closed without merging

2019-02-15 06:14 UTC, estahn commented
@paulczar What's the status with this? Would you accept a new PR with the changes you request? I want to get the process list so I can alert on long running queries.