[stable/mongodb-replicaset] fix harcoded busybox image
helm/charts pull request #8938
Opened 2018-10-31 18:05 UTC by floriantraber

Signed-off-by: Florian Traber <github@floriantraber.de>

#### What this PR does / why we need it:

Allow usage of a different busybox image

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-28 17:35 UTC, steven-sheehy commented
I've addressed the init timeout in another PR, since this one wasn't marked as fixing your ticket. Can you bump chart version, remove timeout and assign to unguiculus ?

2018-11-29 09:22 UTC, floriantraber commented
Done.
/assign @unguiculus

2018-11-30 15:58 UTC, unguiculus requested changes

2018-11-30 15:58 UTC, unguiculus commented on stable/mongodb-replicaset/values.yaml
> +  tag: "latest"
I know, this wasn't the case before, but we should use a stable version.

2018-11-30 15:58 UTC, unguiculus commented on stable/mongodb-replicaset/values.yaml
> +  pullPolicy: "Always"
Use `IfNotPresent` as default.

2018-11-30 18:23 UTC, floriantraber commented on stable/mongodb-replicaset/values.yaml
> +  tag: "latest"
Changed

2018-11-30 18:23 UTC, floriantraber commented on stable/mongodb-replicaset/values.yaml
> +  pullPolicy: "Always"
Changed

2018-11-30 18:25 UTC, steven-sheehy commented on stable/mongodb-replicaset/values.yaml
> +  pullPolicy: "Always"
Forgot README

2018-11-30 18:27 UTC, steven-sheehy commented on stable/mongodb-replicaset/values.yaml
> +  tag: "latest"
I think 1.29 would be safer as it's still considered stable and would still get bug fix releases

2018-12-03 20:51 UTC, unguiculus commented
/ok-to-test

2018-12-03 20:51 UTC, unguiculus approved these changes

2018-12-03 20:59 UTC, unguiculus commented
/lgtm

2018-12-03 21:02 UTC, merged