[stable/nginx-ingress] added feature flag to enable hostPort for daemonset
helm/charts pull request #894
Opened 2017-04-06 14:29 UTC by 21stio

pull request for feature request #872

closed #892 in favor of this as I messed up my previous fork

without providing additional flags this version behaves like version 0.3.1

2017-04-18 15:04 UTC, linki commented
> It may take a few minutes for the LoadBalancer IP to be available.

Notes.txt should also be updated to reflect the case where `.Values.controller.service.enabled=false`.

2017-04-18 15:29 UTC, mgoodness requested changes
A couple nits, one usability

2017-04-18 15:29 UTC, mgoodness commented on stable/nginx-ingress/README.md
> +`controller.daemonSet.hostPort.healthz.enabled` create a healthz hostPort for controller.kind 'DaemonSet' | `False`
Nit: let's keep the case consistent (`false`, not `False`)

I also think five keys deep is excessive. How about `controller.hostPort.httpEnabled`, `controller.hostPort.httpsEnabled`, and `controller.hostPort.healthzEnabled`?

2017-04-18 15:29 UTC, mgoodness commented on stable/nginx-ingress/README.md
> +`controller.service.enabled` | enable controller service | `True`
Nit: see above

2017-05-30 16:16 UTC, mgoodness commented
Closes #872

2017-06-14 20:05 UTC, unguiculus commented
Marking this as stale. Please update during the next week.

2017-07-05 22:11 UTC, viglesiasce commented
Closing as stale.

2017-07-05 22:11 UTC, closed without merging