[stable/fluent-bit] Upgrade to Fluent Bit v0.14.6
helm/charts pull request #8962
Opened 2018-11-01 17:03 UTC by edsiper

This patch upgrade the chart image to Fluent Bit v0.14.6. This
upgrade is strongly required since it fixes two memory leaks
found by users who does filtering.

Signed-off-by: Eduardo Silva <eduardo@treasure-data.com>

#### What this PR does / why we need it:

This patch upgrade the chart image to Fluent Bit v0.14.6. This upgrade is strongly required since it fixes two memory leaks found by users who does filtering.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-11-04 13:44 UTC, davidkarlsen requested changes

2018-11-04 13:44 UTC, davidkarlsen commented on stable/fluent-bit/values.yaml
> +    tag: 0.14.6
can you update the readme too please?

2018-11-04 13:49 UTC, edsiper commented on stable/fluent-bit/values.yaml
> +    tag: 0.14.6
thanks, just updated.

2018-11-04 21:04 UTC, unguiculus commented
/ok-to-test

2018-11-05 11:17 UTC, davidkarlsen approved these changes

2018-11-05 11:18 UTC, davidkarlsen commented
/lgtm

2018-11-07 16:39 UTC, davidkarlsen commented
/lgtm

2018-11-07 16:41 UTC, merged