[stable/envoy] Fix deployment spec
helm/charts pull request #8973
Opened 2018-11-02 11:01 UTC by hypnoglow

#### What this PR does / why we need it:

- Remove serviceName as it is not defined for Deployment

- Move terminationGracePeriodSeconds from Deployment spec to pod
template spec

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped

2018-11-02 11:02 UTC, hypnoglow commented
/assign @foxish

Ref. maintainers from Chart.yaml: @josdotso

2018-11-04 21:08 UTC, unguiculus requested changes

2018-11-04 21:08 UTC, unguiculus commented on stable/envoy/templates/deployment.yaml
> +      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
Should be outside the if statement.

2018-11-05 20:12 UTC, hypnoglow commented on stable/envoy/templates/deployment.yaml
> +      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
woops.. fixed.

2018-11-09 14:59 UTC, unguiculus approved these changes

2018-11-09 14:59 UTC, unguiculus commented
/ok-to-test

2018-11-09 15:07 UTC, unguiculus commented
/lgtm

2018-11-09 15:43 UTC, merged