Add ingressmonitorcontroller
helm/charts pull request #8975
Opened 2018-11-02 14:14 UTC by faizanahmad055

Signed-off-by: Faizan Ahmad
username: faizanahmad055
email: faizan.ahmad55@outlook.com

#### What this PR does / why we need it:
- This PR adds the official chart for [IngressMonitorController](https://github.com/stakater/IngressMonitorController)
- IngressMonitorController continuously watches ingresses/routes in specific or all namespaces, and automatically add/remove monitors in any of the uptime checkers.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-05 10:58 UTC, davidkarlsen commented on stable/ingressmonitorcontroller/templates/deployment.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
See best practice label usage at: https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md

2018-11-05 10:58 UTC, davidkarlsen commented on stable/ingressmonitorcontroller/templates/rbac.yaml
> +kind: ServiceAccount
See RBAC best practices at: https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md

2018-11-05 10:58 UTC, davidkarlsen commented on stable/ingressmonitorcontroller/templates/rbac.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
can use api version 1

2018-11-05 10:58 UTC, davidkarlsen commented on stable/ingressmonitorcontroller/templates/rbac.yaml
> +---
the role, rolebinding and clusterrolebinding should be split into separate template-files.

2018-11-05 10:58 UTC, davidkarlsen commented
/ok-to-test

2018-11-05 10:58 UTC, davidkarlsen commented
/assign

2018-11-07 16:33 UTC, davidkarlsen commented on stable/ingressmonitorcontroller/templates/rbac.yaml
> +---
@faizanahmad055 ping

2018-11-08 10:41 UTC, faizanahmad055 commented on stable/ingressmonitorcontroller/templates/deployment.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
Updated.

2018-11-08 10:41 UTC, faizanahmad055 commented on stable/ingressmonitorcontroller/templates/rbac.yaml
> +kind: ServiceAccount
Updated

2018-11-08 10:46 UTC, faizanahmad055 commented on stable/ingressmonitorcontroller/templates/rbac.yaml
> +apiVersion: rbac.authorization.k8s.io/v1beta1
Updated.

2018-11-08 10:46 UTC, faizanahmad055 commented on stable/ingressmonitorcontroller/templates/rbac.yaml
> +---
Hi sorry for the delay, I've updated these. Can you please take a look.

2018-11-09 15:00 UTC, faizanahmad055 commented
@davidkarlsen 
Ping

2018-11-11 00:30 UTC, davidkarlsen requested changes

2018-11-11 00:30 UTC, davidkarlsen commented on stable/ingressmonitorcontroller/templates/deployment.yaml
> +apiVersion: extensions/v1beta1
can be v1

2018-11-11 00:30 UTC, davidkarlsen commented on stable/ingressmonitorcontroller/templates/role.yaml
> +metadata:
add labels

2018-11-11 00:30 UTC, davidkarlsen commented on stable/ingressmonitorcontroller/templates/clusterrolebinding.yaml
> +metadata:
add labels

2018-11-11 00:30 UTC, davidkarlsen commented on stable/ingressmonitorcontroller/templates/clusterrole.yaml
> +{{- if .Values.ingressMonitorController.useFullName }}
add labels

2018-11-12 13:56 UTC, faizanahmad055 commented on stable/ingressmonitorcontroller/templates/clusterrole.yaml
> +{{- if .Values.ingressMonitorController.useFullName }}
Updated

2018-11-12 13:56 UTC, faizanahmad055 commented on stable/ingressmonitorcontroller/templates/deployment.yaml
> +apiVersion: extensions/v1beta1
Updated

2018-11-12 13:57 UTC, faizanahmad055 commented on stable/ingressmonitorcontroller/templates/role.yaml
> +metadata:
Updated

2018-11-12 13:57 UTC, faizanahmad055 commented on stable/ingressmonitorcontroller/templates/clusterrolebinding.yaml
> +metadata:
Updated

2018-11-15 09:21 UTC, faizanahmad055 commented
Hi @davidkarlsen,
Ping

2018-11-16 17:37 UTC, paulczar commented
@davidkarlsen looks like this has implemented your requested changes ... I think it looks mergable now, but I'll give you a few more days to LGTM it before I step in.

2018-11-17 20:36 UTC, davidkarlsen commented
/lgtm

2018-11-17 20:36 UTC, davidkarlsen approved these changes

2018-11-17 20:43 UTC, merged