[mongodb/replicaset] readiness probe now checks if primary or secondary
helm/charts pull request #8981
Opened 2018-11-02 19:31 UTC by agolomoodysaada

Signed-off-by: moody <moody.saada@agolo.com>

#### What this PR does / why we need it:
Currently, the mongodb service sends traffic to pods that are not yet ready to process requests due to readinessProbes passing during initContainer stage. Some init containers spin up mongo, and the only check we currently have are `ping` requests; which will pass when mongo runs in standalone mode during init stage. This PR changes the readinessProbe to check if pod is either Primary or Secondary before considering it healthy.

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-11-04 19:49 UTC, unguiculus commented
/ok-to-test

2018-11-05 16:38 UTC, steven-sheehy commented
According to [Kubernetes](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#differences-from-regular-containers):
> Init Containers do not support readiness probes because they must run to completion before the Pod can be ready.

Also, this can be seen directly in the yaml that the readinessProbe is directly under regular mongodb container and not on any initContainers. So I don't think changing the probe will have any impact as the readiness probe doesn't even start until init containers complete.

I think more likely you are seeing the this due to how mongodb handles connections. The mongodb service is round-robin (unless you're using ipvs) so your client will randomly get one of the primaries or the secondaries that are marked as ready. Once connected, the mongo client will retrieve all replica set member's IPs and state and use a selection algorithm to connect. The selection algorithm varies based upon which query you are performing and your read preference (primary, primaryPreferred, etc). So it's possible that a mongo that is part of the replica set but is not marked as ready yet could be returned via this selection.

Also, the new readiness probe does not properly handle when authentication is enabled. This will have to be fixed regardless of above.

2018-11-05 19:34 UTC, agolomoodysaada commented
@steven-sheehy , thanks for your reply. You're talking about mongo client logic and you're right about how they work. I'm facing more of a DNS resolution problem. The kubernetes Service object lists endpoints for 3 IPs, one per replica, even though only two are running and the third is crashbacklooping during init container stage. Because it's a headless service, the IP resolve to any of the three pod IPs. When the IP matches the failing pod, the client cries and fails. It's not even able to establish the initial connection. Mongo is smart enough not to route a client to an instance that is not healthy in the replicaset yet.

If there's no readiness on initContainers, then... my hypothesis is false. Can you think of other reasons how I can fix this problem?

2018-11-05 20:03 UTC, steven-sheehy commented
Another reason your PR will not work is we tolerate unready endpoints on the [headless service](https://github.com/helm/charts/blob/deb5aa63c414afa65297b91b7d7db4d079a3004c/stable/mongodb-replicaset/templates/mongodb-service.yaml#L6). This is necessary so the mongo in init containers can see each other and join the replicaset. So even only returning primary or secondaries will be ignored since it will return all regardless. We probably need to have two services, one headless with tolerate unready and the other for clients to use without unready.

Perhaps @unguiculus can weigh in here as to why it wasn't originally created with two services?

2018-11-05 20:29 UTC, agolomoodysaada commented
`tolerate-unready-endpoints` explains a lot! I was under the impression that this feature was deprecated from the k8s project. Either way, I'm happy to change the scope of this PR to add this new Service without the annotation.

2018-11-05 20:36 UTC, steven-sheehy commented
The annotation is deprecated and has moved to field `publishNotReadyAddresses`. From [1.11 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md):

> The annotation service.alpha.kubernetes.io/tolerate-unready-endpoints is deprecated. Users should use Service.spec.publishNotReadyAddresses instead. (#63742, @thockin)

Can you add this field to your unready service in your PR as well? So clients don't have to change, you probably want to remove the annotation from existing service and create new discovery service with unready annotation and publishNotReadyAddresses for init containers to use, if that's possible.

2018-11-05 20:44 UTC, agolomoodysaada commented
Sounds great. Would love to hear from @unguiculus as well when he gets a chance to review this discussion

2018-11-09 14:58 UTC, unguiculus commented
Thanks @steven-sheehy @agolomoodysaada 

I'd suggest you add `publishNotReadyAddresses` and the additional service.

2018-11-09 17:15 UTC, agolomoodysaada commented
I removed my old changes and submitted the new discovery service. Let me know if it makes more sense now.

2018-11-09 17:27 UTC, steven-sheehy requested changes

2018-11-09 17:27 UTC, steven-sheehy commented on stable/mongodb-replicaset/Chart.yaml
> +version: 3.6.5
Should be a minor or possibly a major version increase due to new k8s resource.

2018-11-09 17:27 UTC, steven-sheehy commented on stable/mongodb-replicaset/templates/mongodb-service-discovery.yaml
> +{{- if .Values.metrics.enabled }}
I don't think metrics port needs to be in unready service.

2018-11-09 17:27 UTC, steven-sheehy commented on stable/mongodb-replicaset/templates/mongodb-service-discovery.yaml
> +  name: {{ template "mongodb-replicaset.fullname" . }}-discovery
You need to update the bootstrap container to use this new service. Please make sure you test a new install and an upgrade with these changes.

2018-11-09 21:42 UTC, agolomoodysaada commented on stable/mongodb-replicaset/templates/mongodb-service-discovery.yaml
> +  name: {{ template "mongodb-replicaset.fullname" . }}-discovery
I changed the passed service name in the statefulset

2018-11-09 21:42 UTC, agolomoodysaada commented on stable/mongodb-replicaset/templates/mongodb-service-discovery.yaml
> +{{- if .Values.metrics.enabled }}
removed

2018-11-09 21:43 UTC, agolomoodysaada commented on stable/mongodb-replicaset/Chart.yaml
> +version: 3.6.5
bumped to 3.7.0

2018-11-09 21:52 UTC, agolomoodysaada commented
/retest

2018-11-09 22:44 UTC, agolomoodysaada commented
I tried looking at logs for bootstrap container but they're very silent. I attempted everything I could think of with no clues on what could go wrong. Peer Finder seems to get stuck for some reason. But it doesn't complain about the service name. It seems to be okay with the -discovery service lookup but stalls afterwards?

2018-11-09 22:45 UTC, steven-sheehy commented
bootstrap doesn't show logs until complete. exec into it and cat /work-dir/logs.txt to see up to date logs

2018-11-09 22:46 UTC, agolomoodysaada commented
I tried looking for that log file but it never gets created! Something else is going on...

2018-12-16 03:43 UTC, steven-sheehy commented
Thanks for your work here. This issue was addressed separately via PR #9495.
/close

2018-12-16 10:16 UTC, closed without merging