[stable/cluster-autoscaler] support fullnameOverride
helm/charts pull request #9000
Opened 2018-11-05 10:13 UTC by erks

#### What this PR does / why we need it:

Support `fullnameOverride` and be consistent with other charts.

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-11-05 11:06 UTC, davidkarlsen commented
/ok-to-test
/assign

2018-11-05 11:06 UTC, davidkarlsen requested changes

2018-11-05 11:06 UTC, davidkarlsen commented on stable/cluster-autoscaler/Chart.yaml
> +version: 0.8.1
```suggestion
version: 0.9.0
```
due new feature

2018-11-05 15:25 UTC, erks commented on stable/cluster-autoscaler/Chart.yaml
> +version: 0.8.1
done

2018-11-17 21:18 UTC, davidkarlsen approved these changes

2018-11-17 21:18 UTC, davidkarlsen commented
/lgtm

2018-11-17 21:33 UTC, erks commented
@davidkarlsen looks like there was a version conflict on master. I bumped this to `0.10.0` (from `0.9.0` on master). Please `lgtm` again.

2018-12-17 22:02 UTC, erks commented
@davidkarlsen another bump.

2019-01-31 07:26 UTC, closed without merging