Kong ingress controller
helm/charts pull request #9020
Opened 2018-11-05 18:05 UTC by hbagdi

#### What this PR does / why we need it:

Deploy Kong as your Ingress controller!

This is developed by @merqurio and I'm merely making some doc changes and opening this PR.
#7350 is superseded by this.

2018-11-05 18:13 UTC, hbagdi commented
/ok-to-test

2018-11-05 18:14 UTC, hbagdi commented
/assign shashiranjan84

2018-11-07 17:53 UTC, hbagdi commented
/test pull-charts-e2e

2018-11-08 16:22 UTC, hbagdi commented
@cpanato Could you help me figure out why this E2E fails?
The same migration container runs fine in previous deployments but in the third one it fails even though the process inside the container exits fine.

2018-11-08 16:23 UTC, cpanato commented
@hbagdi I will take a look on that tomorrow, if is that ok for you

2018-11-08 16:23 UTC, hbagdi commented
@cpanato Thank you for the prompt response. Tomorrow works, thanks!

2018-11-08 21:02 UTC, merqurio commented
Thanks @hbagdi I really appreciate this. I'm full of work and didn't found time to commit to this. I had to create a fork due to [this issue][https://github.com/helm/helm/issues/4490] and didn't got the time to go back to this fork.

2018-11-09 14:05 UTC, cpanato commented on stable/kong/templates/crd-kongconsumer.yaml
> +metadata:
can you add the 
```
annotations:
    "helm.sh/hook": crd-install
```

in all crds ?

2018-11-09 14:06 UTC, cpanato commented on stable/kong/values.yaml
> +    enabled: false
Persistence should be set to true by default

2018-11-09 14:10 UTC, cpanato commented
/test pull-charts-e2e

2018-11-13 18:11 UTC, hbagdi commented
@cpanato It seems like now we've an issue with (un)installing CRDs on the CI cluster.

cc @scottrigby @unguiculus

2018-11-13 19:56 UTC, unguiculus commented
/retest

2018-11-13 19:57 UTC, unguiculus commented
I deleted the CRDs manually. Can you make sure the chart removes them when it is uninstalled?

2018-11-13 20:21 UTC, unguiculus requested changes
The failing CI is caused by issues with the component label on the ingress controller.

2018-11-13 20:21 UTC, unguiculus commented on stable/kong/templates/controller-cluster-role.yaml
> +{{- if .Values.ingressController.enabled -}}
Please follow our RBAC best practices:
https://github.com/helm/helm/blob/master/docs/chart_best_practices/rbac.md

2018-11-13 20:21 UTC, unguiculus commented on stable/kong/templates/controller-deployment.yaml
> +  namespace: {{ .Release.Namespace }}
It is unnecessary to specify the namespace on resources. This is handlked by Helm automatically.

2018-11-13 20:21 UTC, unguiculus commented on stable/kong/templates/controller-deployment.yaml
> +      release: {{ .Release.Name }}
Selector needs `component` label.

2018-11-13 20:21 UTC, unguiculus commented on stable/kong/templates/controller-deployment.yaml
> +        release: {{ .Release.Name }}
Selector needs `component` label.

2018-11-13 20:21 UTC, unguiculus commented on stable/kong/templates/controller-deployment.yaml
> +    component: "app"
The Kong deployment has the same component label. You need a different one here.

2018-11-13 22:38 UTC, hbagdi commented
/test pull-charts-e2e

2018-11-13 23:33 UTC, hbagdi commented
@unguiculus I'll work on cleaning up RBAC stuff but I think I'll need help from you to clean up the CRDs once more.

2018-11-14 02:42 UTC, hbagdi commented
@unguiculus  Testing locally, the `crd-install` hook seems to have a problem.

It doesn't actually install the CRD.

Running the following:
```
helm install --dry-run --debug . \
    --set ingressController.enabled=true \
    --namespace yolo \
    --set admin.useTLS=false \
    --set readinessProbe.httpGet.scheme=HTTP \
    --set livenessProbe.httpGet.scheme=HTTP
```

give the following output:
https://gist.github.com/hbagdi/fb9edd4c4657670cc12bbf77e141df5a

2018-11-14 03:38 UTC, hbagdi commented
The tests should now pass once the CRDs are deleted manually once from the test infra cluster.
We're not using a `hook` for the chart since we don't use the any object of that CR type.

2018-11-14 04:19 UTC, hbagdi commented
/retest

2018-11-14 18:08 UTC, hbagdi commented
@unguiculus Really appreciate you jumping in on this one and helping out troubleshoot the CI issue. Could you review this once more? 
Thank you!

2018-11-15 18:23 UTC, shashiranjan84 approved these changes
/lgtm

2018-11-16 03:21 UTC, hbagdi commented
@unguiculus Gentle ping for an approval on this PR.

2018-11-16 10:15 UTC, cpanato commented
/lgtm

2018-11-16 10:48 UTC, merged

2018-11-16 10:50 UTC, merqurio commented
Thanks @hbagdi  for this

2018-11-16 15:35 UTC, hbagdi commented
@merqurio @cpanato @unguiculus @shashiranjan84 Thank you for helping get this through!

2018-11-18 06:22 UTC, joe1chen commented
@hbagdi Great work on this! I've been following this issue and testing it the past few days. 

I found a pretty severe bug with this pull though.  It will break the kong proxy because a bug is introduced where traffic is occasionally sent to the ingress controller pod instead of the proxy pods.  I kept on getting intermittent connection refused errors until I found the issue is a result of the services not having a specific enough selector.

In service-kong-admin.yaml:
Change:
```
  selector:
    app: {{ template "kong.name" . }}
    release: {{ .Release.Name }}
```
to
```
  selector:
    app: {{ template "kong.name" . }}
    release: {{ .Release.Name }}
    component: app
```

And the same in service-kong-proxy.yaml:
Change:
```
  selector:
    app: {{ template "kong.name" . }}
    release: {{ .Release.Name }}
```
to:
```
  selector:
    app: {{ template "kong.name" . }}
    release: {{ .Release.Name }}
    component: app
```

Normally I would fork and open a pull request, but the last time I tried to contribute to helm, I had issues getting my environment set up to sign the contributor agreement.  So in the interests of time and because this is a severe bug, I'm hoping you can open the bug for me and fix it.

I also have a few other enhancements to contribute, such as support for TLS, which is working well with cert-manager and LetsEncrypt.