Jenkins Configuration as Code
helm/charts pull request #9057
Opened 2018-11-06 23:26 UTC by holmesb

#### What this PR does / why we need it:
Implements Jenkins Configuration as Code. JCasC has been promoted as a top-level Jenkins project, and the corresponding Jenkins Enhancement Proposal has been accepted.

#### Which issue this PR fixes
Allows configuration of Jenkins using yaml configuration files that are concise and human-readable. The files also have user-friendly naming conventions making it easy for administrators to configure all Jenkins components.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-13 19:50 UTC, holmesb commented
@davidkarlsen, did you get a chance to review this at all?

2018-11-24 12:04 UTC, holmesb commented
Note: Currently this PR only loads Jenkins config at startup.  As an option, should introduce a Jenkins "sidecar" - another container running inside the pod that monitors the JCasC configmap, creates the yaml files on the file-system, then executes the Jenkins CLI command to reload the config.  The Grafana Helm chart is a good example of how "sidecar" functionality can be added.  Would need to ensure this real-time CasC approach won't bork Jenkins if bad config is introduced.  But this is something for a future PR.  Startup-only is good enough for now.

2019-01-08 20:50 UTC, maorfr commented
/assign @maorfr

2019-01-08 20:52 UTC, maorfr commented
Hey @holmesb,

Thanks for contributing!
Can we get the lint-charts tests passing?

2019-01-09 08:40 UTC, torstenwalter commented
Looks like the lint test was failing because the chart version was not incremented.

@holmesb I created a branch which fixes that I just don't know how to send a PR to your fork.
https://github.com/torstenwalter/charts/tree/feature/PR-9057-casc-bump-version

I'd also suggest to increase the version of these plugins to 1.4:
    - configuration-as-code:1.3
    - configuration-as-code-support:1.3

2019-01-14 22:16 UTC, holmesb commented
I've added auto-reload to this PR.  Summary:
- No breaking changes
- Option to use JCasC without auto-reload
- Auto-reload uses CLI via SSH, not API-token authentication since Jenkins does not allow the token to be created programmatically.  This inability was specifically designed to be the case.  Might be possible to create-by-scrape, but would be unreliable and hacky.  SSH authentication is fully supported in Jenkins.
- SSH private key automatically generated by helm or can "bring your own".  Stored in k8s secret.
- According to my testing, a bad configuration will cause the sidecar to error.  Jenkins will remain operational.  After running helm upgrade\install, you should check the sidecar logs using 'kubectl logs <pod> -c jenkins-sc-config'.  Correcting the config will resume normal sidecar operation.
- If you choose to use auto-reload, this enables the SSHD daemon on the master.  This chart does not (currently) provide any mechanism to open the SSHD port in the pod.  Hence SSH is only possible from within the pod, in other words, from the sidecar.
- Hierarchy of sidecar values allows further sidecars to be added for other purposes in future.
- Sidecar is a fork (https://github.com/holmesb/k8s-sidecar) I made from the kiwigrid/k8s-sidecar docker image.  This uses python's kubernetes library to watch the configmap and copy its contents to the CasC directory which is shared between the sidecar and Jenkins containers.  It connects to Jenkins using the Paramiko SSH library and executes the jenkins-reload command.  Runs as a non-root user.
- Outputs some helpful text using NOTES.txt
- JCasC & auto-reload are disabled in values.yaml to keep the default Jenkins "vanilla" and to allow a period of testing.  Eventually might change these defaults to enabled.

Hopefully my values.yaml comments will answer most other questions.

The most opinionated decision was to state in the readme and values that the existing configuration mechanisms that force a reboot and only apply configuration at startup are deprecated.  A single recommended configuration method will keep this chart accessible to newcomers.  JCasC is now a standard component in the Jenkins project.  It brings a step improvement to how Jenkins is configured and I can't imagine a use case for persisting with the old method long-term\green-field.  Your mileage may vary.

JCasC plugin-installation was derived from @torstenwalter's branch, so thank you Torsten.

Please let me know any issues.

2019-01-14 22:36 UTC, maorfr commented
/ok-to-test
I'll let the tests run and review thoroughly within a few days.

2019-01-15 12:50 UTC, torstenwalter commented
@holmesb: Looks great! I thought about adding support within the plugin to allow calling the reload configuration endpoint without authentication from localhost using ssh instead is even better.

As you are configuring the ssh key for the admin user. Do you know it this works even if authentication is delegated to an external system like LDAP and the Jenkins internal user database is no longer used?

2019-01-17 23:42 UTC, holmesb commented
Thanks Torsten.  Unfortunately it seems the admin user won't exist when LDAP\non-internal user database is used so sidecar will fail to authenticate, reboot-loop and back-off.   I'd assumed Jenkins worked like the other LDAP-integrated systems I've used, in that it falls-back to the internal database, but it seems this hasn't progressed beyond the [feature-request](https://issues.jenkins-ci.org/browse/JENKINS-3404) stage.  "Without authentication" isn't possible.   Even against localhost, either token\SSH authentication is needed.  

However, to use a non-internal db will be a simple matter of specifying the name of an existing user in the non-internal db in Master.AdminUser.  See the Readme update in latest commit for more info.  User must have Overall\Read rights which is the default for new users.  

I've tested LDAP users will have the SSH public key successfully assigned using the same init script in this PR that assigns it to the internal admin user (see config.yaml).  It's fair to assume it will also work for other user databases, but I'd appreciate if anyone who has access to a non-LDAP identity store could run init-add-ssh-key-to-admin.groovy and confirm.  You'll need to create a public key on the master in /var/jenkins_home/key.pub.   You should see the SSH Public Key populated in http://<jenkins_url>/user/<username>/configure

I've also fixed the missing casc_configs dir when not using auto-reload.

2019-01-20 08:45 UTC, holmesb commented
A few fixes in last commit:
- Sidecar was reloading once per key in the configmap when any single key had changed.  Resolved by creating separate configmaps, one for each key under ConfigScripts.  
- I was mistaken above that users only need Overall\Read rights to auto-reload.  Seems JCasC has higher privilege requirements than the CLI\API generally.  I've amended the Readme accordingly.  Process for enabling for LDAP\other ID store is still simple.
- Fixed connectivity from sidecar when enabling non-root privileges by using a TCP port > 1024 (1044)
- Bumped the sidecar image from 0.0.1 to 0.0.2 which a few improvements: faster, less error-prone startup by testing the Jenkins container's availability using SSH port instead of the main Jenkins port.  This removes the need for an arbitrary wait.  Also fixed "access denied" when enabling non-root privileges by creating the same Jenkins 1000 user in the sidecar.

2019-01-24 16:09 UTC, torstenwalter commented
@holmesb I did not have the chance to test if with other authentication methods, but I assume that I would need to know a user id for which I could generate an ssh key. In our case users are not know upfront which makes automation complicated.

I opened PR https://github.com/jenkinsci/configuration-as-code-plugin/pull/712 to address this. In case it's accepted it would simplify the implementation here. It also avoids storing an admin credential somewhere.

2019-01-24 17:50 UTC, holmesb commented
Reloading JCasC is potentially an attack vector and should stay privileged IMO.  Currently are two layers of protection to break: (1) creating config files (2) reloading config.  Your PR removes 2.

"need to know a user id for which I could generate an ssh key" - if internal Jenkins user database is used, this isn't true.  Admin user will automatically be selected and it will just work.  
For the LDAP\non-internal case: JCasC will normally be managed by devops\developers who must already have a relationship with the people who manage the non-internal database in order to link\authenticate Jenkins with it.  Hence should fairly easy be able to find or request creation of a suitable user.
"makes automation complicated" - most of the complexity in this PR is in watching for configmap changes and writing them to the file-system.  This would remain after you remove authentication.  I am forking this functionality from a commonly-used, mature sidecar that is used in many other charts in this repo (eg Grafana).  My addition is SSH authn: relatively simple.  I can't envisage helm dropping its SSH key creation function, and [Python's paramiko library](https://github.com/paramiko/paramiko)y is active and well maintained.  I expect this code will remain stable and easy to maintain.
"storing an admin credential somewhere" - we're doing that already and will remain doing so regardless of your PR.  "Somewhere" is a k8s secret.  If we don't trust those, then we may as well delete this whole repo.

2019-01-24 19:06 UTC, torstenwalter commented
@holmesb Sorry for mentioning your PR in the linked configuration as code issue. I just wanted to help as I thought it could be useful here as well. 

For you it might not be an issue to have a user created. For LDAP you need read access to configure the plugin. That's not necessarily true for other systems. For Keycloak authentication I don't need a user pre configured.
I a managing quite a number of Jenkins instances and I don't necessarily need an account on those.

As I said it was just meant as a pointer to something which could be useful. Nothing which prevents this PR from being merged.

2019-01-24 20:14 UTC, holmesb commented
I wasn't aware of Keycloak or any authn for that matter other than Jenkins & LDAP\AD.  We won't use a non-authenticated reload option here.  But if your PR is merged, I'm happy to enable it via a helm boolean value, which will disable SSH key creation, etc and make a REST call from the sidecar instead.

2019-01-25 13:31 UTC, kstevena requested changes
Some plugins or jenkins configuration items to be managed by the Jenkins Configuration as Code plugin would benefit from templating, potentially reusing values passed to the Jenkins helm chart. Then using `tpl` template function to generate configmap's entries would be I guess usefull.

2019-01-25 13:31 UTC, kstevena commented on stable/jenkins/templates/config.yaml
> +{{ $val | indent 4 }}
```suggestion
{{ tpl $val $| indent 4 }}
```
This would allow templating for JCasC config snippets, such as for the welcome message to include the name of the instance:
`
    ConfigScripts:
      welcomemessage: |
        jenkins:
          systemMessage: "{{ template "jenkins.fullname" . }} configured automatically by Helm Chart & Jenkins Configuration as Code Plugin\n\n"
`

2019-01-25 13:31 UTC, kstevena commented on stable/jenkins/templates/jcasc_config.yaml
> +{{ $val | indent 4 }}
```suggestion
{{ tpl $val $| indent 4 }}
```
This would allow templating for JCasC config snippets, such as for the welcome message to include the name of the instance:
`
    ConfigScripts:
      welcomemessage: |
        jenkins:
          systemMessage: "{{ template "jenkins.fullname" . }} configured automatically by Helm Chart & Jenkins Configuration as Code Plugin\n\n"
`

2019-02-07 01:50 UTC, n1try commented
Any news here? I'd love to have that feature!

2019-02-07 06:47 UTC, maorfr commented
Hey all,

The work that has been done here is really extensive, and I would really like to approve this PR.
There is just one thing that I would like to discuss:

The sidecar image that is being used is not an automated build, and as a user, I can not see the source code that was used to build it. This may be intimidating for users. When looking under the [docker hub repo](https://hub.docker.com/r/shadwell/k8s-sidecar), I couldn't find any details regarding this image, as opposed to the image it was [forked from](https://hub.docker.com/r/kiwigrid/k8s-sidecar).

In addition, and this is a smaller comment, I think that the logic in these sections can be simplified to use if-else:
https://github.com/helm/charts/pull/9057/files#diff-7146a5152507fba3404ff5118aab029cR248
https://github.com/helm/charts/pull/9057/files#diff-7146a5152507fba3404ff5118aab029cR274
But that is not as important as the previous comment.

Thanks for all the hard work all of you put in, your contribution is highly appreciated!

2019-02-07 20:58 UTC, holmesb commented
Hi @maorfr, good points.  I've documented my [sidecar image[(https://hub.docker.com/r/shadwell/k8s-sidecar) on dockerhub and included a link to the [github repo](https://github.com/holmesb/k8s-sidecar).  I'll also start getting into the habit of adding proper change logs to each version.

I've replaced a few if conditions with simpler else statements in [config.yaml](https://github.com/helm/charts/pull/9057/commits/56f9c61abb037edf3637c50dcd7c55e51de5ac88#diff-7146a5152507fba3404ff5118aab029c) as you suggested.  Let me know if it isn't what you had in mind.  We've been happily doing on-the-fly config reloads for over two weeks now in our busy Jenkins, so hopefully this is in a good enough state to merge.

2019-02-07 23:24 UTC, maorfr commented
/lgtm

Good job on this PR!

2019-02-08 00:39 UTC, merged

2019-02-08 08:08 UTC, JeanMertz commented
I've been looking into JCasC, and the Helm chart. We've been using a fork of 0.6.0 since two years ago, and are looking into moving back to the latest upstream version. I had some thoughts yesterday that I wanted to post here, but I see the PR has since been merged.

Either way, here's a quick summary, feel free to ignore it if you don't think it's relevant.

I think using the JCasC plugin makes a lot of sense. At the same time, I also think we should take this opportunity to either 1) kill off 90% of the current configuration flags that can just as easily be defined using the JCasC yaml-based set-up (and do a backward breaking release), or 2) create a new chart with only the following features:

* Persistence support (but slightly tweaked to support a useable ephemeral set-up, see https://github.com/helm/charts/pull/11225)
* Plugin installation support (since the JCasC plugin installation support is still considered beta)
* All the relevant Kubernetes tweakables (RBAC, annotations, Ingress, ports, etc)
* All the relevant flags that you need to set _before_ Jenkins starts (JVM arguments, user to run Jenkins as, etc)
* JCasC support
* Init scripts (for those who want full access to the Jenkins API, for the things that JCasC does not yet support)

With this, you can eliminate a lot of extra configs, while still being able to achieve the exact same set-up as before, using JCasC. It would reduce the complexity of this chart, and we'd be able to point to the proper JCasC documentation for people to read, instead of having to read this Chart's documentation to be able to understand what you need to do to get the config you want.

As it currently stands, this PR (and the entire Jenkins chart) has so much complexity and hidden details based on the combination of configurables you set, that I'm almost inclined to ditch the chart and use a more simple set-up. With the above list of features "simple" would not mean "only useful to us", it would just mean less mental overhead when working with the chart, and moving to a set-up that is more in-line with the entire Jenkins ecosystem.

I've been experimenting locally with the JCasC setup, and the official Jenkins Docker image, and with a few volumes, JCasC, and some init scripts, you can get the exact set-up you want. Add to that the regular Kubernetes tweakables, and you end up where this chart is, without all the added complexity.

(note that I'm not criticising the current state, as I know how we got here, and a lot of the things that Jenkins properly supports these days (blueocean, kubernetes, JCasC) where just not easy to do one or two years ago, but given the current state, I think they are, and I think this chart would be better off if it reduced its complexity and off loaded the heavy lifting back to the official plugins)

2019-02-08 11:34 UTC, maorfr commented
I will prioritize any PR that simplifies this chart. Assign me to any such PR!

2019-02-08 11:43 UTC, JeanMertz commented
> I will prioritize any PR that simplifies this chart.

That's good to know, but I'm sure there are qualifiers. Do we want to make backward breaking changes, if so do we want to do them all in one big overhaul PR, and if not, do we see any simplifications we can make without breaking backward compatibility?

---

I'm in the process of reconfiguring our CI right now, starting from scratch. I plan on taking the current chart, stripping it of everything except the things I mentioned above, and see if that works.

I can create a PR with those changes once done (sometime next week), and we can see if anything can be upstreamed, or not.

2019-02-08 11:54 UTC, maorfr commented
My guidelines are:

* as few breaking changes
* PRs should be as small as possible

Maybe we can open an issue to follow this process. Each PR can reference this issue (but not close it). Once all the work is done, the issue can be closed. It will also be a way to involve additional community members!

What do you think? Would you like to lead this effort?

2019-02-08 13:10 UTC, holmesb commented
Simple is good. But I'd prefer not to break existing users who use alternate (non JCasC) methods of configuring Jenkins.  Rather than be too brutal about discarding without warning, I'd prefer marking all non-JCasC configuration methods as deprecated for a period to nudge users off them and onto JCasC.  Breakages will dissuade people from using and relying on this chart.

I suggest moving non-JCasC configuration to the bottom of the Readme table and as low as poss in the values.  Mark them clearly as "deprecated" and add comments that these options will be removed shortly.  Also warn the user in Notes.yaml output if they're using these options.

@JeanMertz, pls can you clarify what "proper JCasC documentation... [not] this Chart's documentation" means?  In values.yaml and notes.yaml, I link clearly to the most authoritative JCasC reference: https://<jenkins_url>/configuration-as-code/reference, which contains info for the user's specific Jenkins implementation (their unique set of plugins, etc).  Also to the [CasC demos on github](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos) which give practical examples that users can copy and paste.  Perhaps these links are needed more prominently in the Readme?

2019-02-08 13:28 UTC, maorfr commented
Would you prefer to discuss this in an issue instead of a merged PR? ;)

2019-02-08 14:58 UTC, holmesb commented
> Would you prefer to discuss this in an issue instead of a merged PR? ;)

[Done.](https://github.com/helm/charts/issues/11276)

2019-02-20 14:56 UTC, ricardompcarvalho commented
@holmesb can you help me, please? How can i run the sidecar configuration to autoreload the casc configuration? I do it like that 
![image](https://user-images.githubusercontent.com/27811451/53100480-c234a880-351f-11e9-8931-7344b48cbf14.png)
but give me error, miss something?

2019-02-20 15:06 UTC, torstenwalter commented
@ricardompcarvalho It would help if you could provide more details about the error.

2019-02-20 15:08 UTC, ricardompcarvalho commented
The configuration that i show in image above is correct? I still need someone else configuration to do an auto-reload? @torstenwalter

2019-02-20 15:45 UTC, ricardompcarvalho commented
@torstenwalter @holmesb gives me this 
![image](https://user-images.githubusercontent.com/27811451/53104003-8224f400-3526-11e9-8f46-0d17ec9972fe.png)

2019-02-20 15:58 UTC, holmesb commented
@ricardompcarvalho 
Pls see latest [values.yaml](https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml)  Should be:
```
Sidecars:
    configAutoReload:
        enabled: true
        image: shadwell/k8s-sidecar:0.0.2
        imagePullPolicy: IfNotPresent
        resoureces:
```
etc.  Sorry we changed this in the latest version to accommodate multiple sidecars.

2019-02-20 16:03 UTC, ricardompcarvalho commented
Yes, i already see that and change. Gives the error that i send above your answer @holmesb

2019-02-20 16:59 UTC, holmesb commented
This is a 403 Forbidden error.  Are you using the internal jenkins user database, or an external one such as LDAP?  The admin user will no longer exist if the later, hence [you must change](https://github.com/helm/charts/tree/master/stable/jenkins#auto-reload-with-non-jenkins-identities) the Master.adminUser property to one that has Overall\Administer perms. 

Anyway, this discussion doesn't belong in this merged PR.  Please raise an issue.

2019-02-20 17:00 UTC, ricardompcarvalho commented
@holmesb thank you