Add dogstatsd chart
helm/charts pull request #909
Opened 2017-04-10 21:53 UTC by yuvipanda

Different from the `datadog` chart in the following ways:

1. Adds a deployment+service you can send statsd metrics to,
   rather than install an agent on each node
2. Much more lightweight if you're only using datadog as a statsd
   backend.

I considered integrating this into the datadog chart but that
seemed less clean

2017-04-10 21:57 UTC, yuvipanda commented
Tagging @gtaylor since they seem to have added the original datadog chart.

2017-04-11 06:29 UTC, sameersbn requested changes
@yuvipanda It is certainly preferred if you contributed to the `datadog` chart instead of creating a new chart. This leads to fragmentation and we should try and avoid it. 

In any event attached is my review. Thanks for the pull-request.

2017-04-11 06:29 UTC, sameersbn commented on stable/dogstatsd/templates/svc.yaml
> +      targetPort: 8125
you can use `targetPort: statsd` here

2017-04-11 06:29 UTC, sameersbn commented on stable/dogstatsd/templates/deployment.yaml
> +        - containerPort: 8125
You need to add `protocol: UDP` to the port spec here

2017-04-11 06:29 UTC, sameersbn commented on stable/dogstatsd/templates/svc.yaml
> +    - protocol: UDP
Consider naming this port `statsd` as well

2017-04-11 06:29 UTC, sameersbn commented on stable/dogstatsd/values.yaml
> +  apiKey: "Put your datadog API key here"
I think `apiKey` should be commented out here and `NOTES.txt` can be used to stop the deployment of the Pods when this value is not specified. For reference take a look a https://github.com/kubernetes/charts/blob/master/stable/datadog/templates/NOTES.txt

Also I think a Secrets volume should be added to store sensitive data such as the API key

2017-04-18 15:16 UTC, gtaylor commented
I think @sameersbn probably has the right idea, re: datadog chart. I'd suggest making the agent and dogstatsd separately enableable/disableable via vars.

2017-04-19 17:22 UTC, prydonius commented
If this is a stripped down version of the datadog chart, I can see why it might be easier to build a separate chart than have a more complicated datadog chart, however I don't have a strong opinion. @yuvipanda if you would prefer to contribute to the datadog chart, please close this out.

2017-04-25 01:10 UTC, yuvipanda commented
I'm going to close this, because we just decided to stop using DataDog instead :D Someone else feel free to merge this into the datadog chart...

Thanks everyone for your review!

2017-04-25 01:10 UTC, closed without merging