[sumologic-fluentd]Control stream and time via values
helm/charts pull request #9095
Opened 2018-11-08 09:17 UTC by pawelbojanowski

#### What this PR does / why we need it:
Adds `sumologic.addTime` and `sumologic.addStream` values, to give more control over adding/removing those values from log metadata (PR in docker image repo: https://github.com/SumoLogic/fluentd-kubernetes-sumologic/pull/96 ). 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

@frankreno @darend @flah00

2018-12-10 04:15 UTC, frankreno commented
We will be merging the downstream PR so that this can be approved...

2019-01-11 15:21 UTC, sameersbn commented
This PR seems to have got corrupt somehow. Could you please rebase

2019-01-12 04:01 UTC, sameersbn requested changes

2019-01-12 04:01 UTC, sameersbn commented on stable/sumologic-fluentd/Chart.yaml
> +version: 0.8.3
since the PR adds a new config parameter to the chart, you should bump the minor version here

2019-01-14 15:04 UTC, frankreno requested changes
One minor change then I think we can merge this

2019-01-14 15:04 UTC, frankreno commented on stable/sumologic-fluentd/Chart.yaml
> +version: 0.9.2
this should be 0.9.0

2019-01-14 19:58 UTC, frankreno commented
@pawelbojanowski - apologies, but we just merged another PR that bumped the version 0.9.0.  Can you please bump this to 0.10.0 then we will be ready to merge.  Sorry about this...

2019-01-15 17:09 UTC, frankreno approved these changes
/lgtm

2019-01-15 17:10 UTC, frankreno commented
/ok-to-test

2019-01-15 17:12 UTC, frankreno commented
@pawelbojanowski - DCO needed on commits...

2019-01-16 02:36 UTC, sameersbn approved these changes

2019-01-16 10:54 UTC, sameersbn commented
/lgtm

2019-01-16 11:01 UTC, merged