Add support for Infoblox external-dns
helm/charts pull request #9102
Opened 2018-11-08 12:43 UTC by rabadin

Signed-off-by: Raphael Badin <rabadin@cisco.com>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-11-16 18:17 UTC, paulczar requested changes
the chart is missing a maintainers in the Chart.yaml.  You can add yourself to get it to pass tests.

2018-11-19 20:01 UTC, rabadin commented
@paulczar Okay, I can do that.  I've seen the error from the CI but I figured it would be a bit weird to put my name since I'm only contributing a tiny change... and since there is no maintainer today things must have landed in the past without any maintainer.

2018-11-26 20:51 UTC, rabadin commented
@paulczar Please have a look when you get a chance. I've made the requested change.

2018-11-29 11:05 UTC, linki commented on stable/external-dns/Chart.yaml
> +version: 1.1.2
This should be `1.1.0`

2018-11-29 11:09 UTC, rabadin commented on stable/external-dns/Chart.yaml
> +version: 1.1.2
Good point. Fixed.

2018-11-29 14:11 UTC, linki commented
/ok-to-test
/lgtm
/approve

2018-11-29 14:15 UTC, merged