[stable/percona-xtradb-cluster] Pod Disruption Budget
helm/charts pull request #9110
Opened 2018-11-08 15:31 UTC by maver1ck

Signed-off-by: Maciej Bryński <maciej.brynski@xcaliber.com>

#### What this PR does / why we need it:

Adding Pod Disruption Budget to Percona Chart

#### Which issue this PR fixes
  - fixes #7056

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

2018-11-15 15:47 UTC, paulczar requested changes
I don't see a bump on the chart version!

2018-11-16 10:20 UTC, maver1ck commented
@paulczar  Done.

2018-11-16 19:28 UTC, paulczar approved these changes

2018-11-16 19:29 UTC, paulczar commented
/lgtm

2018-11-16 19:39 UTC, merged