initial version of sumologic-fluentd
helm/charts pull request #913
Opened 2017-04-11 17:45 UTC by flah00

Initial version of a sumologic and fluent solution. It provides more flexibility than the sumologic collector, because it easily integrates environment variables. This approach also removes the need for keys and secrets. This is replaced with an HTTP collector, managed in the sumo console.

The chart provides some value adds, over the simple [daemon set](https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/master/fluentd.daemonset.yaml) the project provides. Perhaps the most significant is the option to persist the fluent pos files, on each node. It also very neatly exposes all of the options available to the image and codifies the management of the collector url secret.

## Limitations

The current docker image, for [fluentd-kubernetes-sumologic](https://github.com/SumoLogic/fluentd-kubernetes-sumologic)
does not support systemd. The only logs available to SumoLogic are those in
`/var/log/containers`. Logs generated in the `kube-system` namespace can only be
excluded using `EXCLUDE_NAMESPACE`, but there's no finer granularity for containers in the namespace. The `EXPORT_PATH` option is not relevant on a systemd OS. I'm working with the maintainers, to find a [solution](https://github.com/SumoLogic/fluentd-kubernetes-sumologic/issues/19).

2017-04-11 17:46 UTC, flah00 commented
@seanknox maintainer of sumokube

2017-06-01 14:13 UTC, prydonius requested changes
Thanks @flah00, sorry for the late review!

2017-06-01 14:13 UTC, prydonius commented on stable/sumologic-fluentd/Chart.yaml
> +  - name: Philip Champon
Can you change this to `flah00`? We're starting to use GitHub usernames here instead.

2017-06-01 14:13 UTC, prydonius commented on stable/sumologic-fluentd/Chart.yaml
> +  - https://github.com/SumoLogic/fluentd-kubernetes-sumologic
I would set this to the `home` as well and add the sumologic icon

2017-06-01 14:13 UTC, prydonius commented on stable/sumologic-fluentd/templates/_helpers.tpl
> +{{- default .Chart.Name .Values.nameOverride | trunc 63 -}}
Please add `| trimSuffix "-"` to the end of this

2017-06-01 14:13 UTC, prydonius commented on stable/sumologic-fluentd/templates/_helpers.tpl
> +{{- printf "%s-%s" .Release.Name $name | trunc 63 -}}
same as above

2017-06-01 14:13 UTC, prydonius commented on stable/sumologic-fluentd/templates/daemonset.yaml
> +        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
Having these labels in the Pod template can cause issues when upgrade the DaemonSet as the selector changes. You should either only keep `app` or set a custom selector.

2017-06-01 14:13 UTC, prydonius commented on stable/sumologic-fluentd/templates/daemonset.yaml
> +    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
missing app, release and heritage labels

2017-06-01 14:13 UTC, prydonius commented on stable/sumologic-fluentd/templates/daemonset.yaml
> +      serviceAccount: {{ template "fullname" . }}
this should be `serviceAccountName`. `serviceAccount` is a deprecated alias

2017-06-01 14:13 UTC, prydonius commented on stable/sumologic-fluentd/values.yaml
> +  pullPolicy: IfNotPresent
`pullPolicy` should be `Always` for `latest` tag

2017-06-01 14:52 UTC, flah00 commented
@prydonius I believe all issues have been addressed, thanks for the review!

2017-06-01 15:08 UTC, prydonius approved these changes

2017-06-01 15:09 UTC, prydonius commented
code review looks good, @seanknox would you be able to UX review this?

2017-06-12 19:04 UTC, flah00 commented
@seanknox can i get a you-ex? :)

2017-06-26 17:10 UTC, flah00 commented
@prydonius could we mebs get a diff ux reviewer? i've got a pending patch to this chart, for systemd which i would like to also submit ... and since this has already been approved, i was thinking it'd be bad form to piggy back on this pr.

2017-07-10 16:06 UTC, flah00 commented
@prydonius SumoLogic's very own @frankreno has graciously agreed to participate. I updated the `Chart.yaml`. What's next?

2017-07-10 16:15 UTC, frankreno commented
feel free to add my email - freno@sumologic.com to the maintainers as well.

2017-07-12 08:44 UTC, prydonius approved these changes

2017-07-12 08:44 UTC, prydonius commented
Awesome - thanks @flah00 and @frankreno :)

2017-07-12 08:44 UTC, prydonius commented
/ok-to-test

2017-07-12 08:50 UTC, merged