[stable/kibana] Add PVC support and security context for Kibana
helm/charts pull request #9130
Opened 2018-11-08 22:06 UTC by jbdelpech

What this PR does / why we need it:
Add PVC support for Kibana plugins to persist plugins and avoid plugins installation at startup.
Add security context for PVC.

Special notes for your reviewer:
Tested in Kibana 6.4.2 with elastalert plugin. 3 cases tested : 
- without plugins
- with plugins without PVC
- with plugins and PVC and security context to true with default values
I did not test with custom PVC.

Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

  [x] DCO signed
  [x] Chart Version bumped
  [x] Variables are documented in the README.md

2018-11-08 22:07 UTC, jbdelpech commented
Tell me if you need something like `pvc-test.yaml` in the ci directory.

Feedback are welcome... !

2018-11-09 10:09 UTC, compleatang requested changes

2018-11-09 10:09 UTC, compleatang commented on stable/kibana/templates/deployment.yaml
> +        {{- if .Values.securityContext.enabled }}
can we outdent these `if` and `end`'s to make readability easier?

2018-11-09 10:09 UTC, compleatang commented on stable/kibana/templates/volume-claim.yaml
> +  {{- if .Values.persistentVolumeClaim.annotations }}
outdent for readability here too.

2018-11-09 10:14 UTC, compleatang commented
@jbdelpech I do think it would be good to include a test sequence for both the pvc's and security contexts. 

One thing we should probably do is to add in a note into to README (and into the values.yaml as a comment) that lower resource constraints given to the chart + plugins are likely not going to work well. In our testing we found the same issue @keithlayne (https://github.com/helm/charts/pull/8896#issuecomment-437077017) had as to the very long plugin install time because we run kibana with fairly low resource limits.

2018-11-13 22:38 UTC, compleatang commented
/retest

2018-11-15 02:09 UTC, compleatang commented
/lgtm
/approve

2018-11-15 02:10 UTC, compleatang commented
/ok-to-test

2018-11-15 02:19 UTC, merged