[stable/kube-ops-view] Add ingress support & enhance service template metadata
helm/charts pull request #915
Opened 2017-04-12 13:46 UTC by tyrannasaurusbanks

* Add optional ingress for kube-ops-view 
* Add optional metadata items (annotations + labels) to the service template

2017-04-12 14:18 UTC, tyrannasaurusbanks commented
CLA...?

2017-04-12 14:48 UTC, tyrannasaurusbanks commented
💯 ?

2017-04-12 20:40 UTC, thelinuxfoundation commented
bump for cla check

2017-04-12 20:48 UTC, linki commented
/cc @hjacobs

2017-04-13 02:59 UTC, hjacobs commented
@tyrannasaurusbanks thanks for the PR! If you are using [kube-ops-view](https://github.com/hjacobs/kube-ops-view), I would like to hear feedback and improvement suggestions :smile:

2017-04-13 13:46 UTC, tyrannasaurusbanks commented
I've just deployed it to one of our clusters as I thought it provided a pretty cool dashboard for our cluster footprint out-of-the-box, and trying to get it to pull in state from our other clusters is also highlighting some bumps we currently have with our auth-provisioning mechanism.
So thanks @hjacobs ! If I

This PR is just me feeding back some functionality I added to work nicely with out internal-kluster setup: service annotations to allow us to create some ELB & an ingress to give us, well, an ingress!.
I've tried to make my additions optional, but i don't know how you feel about the potentially empty ingress.yaml?
Apologies if I've missed some helm/community conventions - this is my first contribution; Is there anything you'd like me to add?

2017-04-13 14:23 UTC, hjacobs commented
@tyrannasaurusbanks thanks for the feedback! I'm also not a helm expert myself (this was my first chart)..

2017-04-18 09:32 UTC, tyrannasaurusbanks commented
@hjacobs or @linki would you be able to help me get a label 'needs-ok-to-test' added to this PR?

2017-04-18 09:55 UTC, hjacobs commented
@tyrannasaurusbanks I don't have such super powers :smirk:, but I will ping @linki ..

2017-04-19 17:09 UTC, prydonius requested changes
The values you've created should also be defined in the values.yaml file.

Also it would be great to update this to follow the same ingress pattern in #813.

2017-04-19 17:09 UTC, prydonius commented on stable/kube-ops-view/templates/ingress.yaml
> +---
the `---` is not needed, Helm already separates manifests correctly

2017-04-20 12:59 UTC, tyrannasaurusbanks commented
@prydonius Thanks for the review! I've refactored the ingress to match the conventions you linked to and added all new values to values.yaml

2017-04-20 12:59 UTC, tyrannasaurusbanks commented on stable/kube-ops-view/templates/ingress.yaml
> +---
removed, thanks

2017-04-25 08:24 UTC, tyrannasaurusbanks commented
are you happy with these changes @prydonius?

2017-05-04 03:24 UTC, seanknox commented
@k8s-bot ok to test

2017-05-15 08:46 UTC, tyrannasaurusbanks commented
@seanknox is there anything I need to do to trigger a test run or will the k8-bot pick it up in due-course?

2017-05-15 08:54 UTC, prydonius approved these changes

2017-05-15 08:56 UTC, prydonius commented
@tyrannasaurusbanks The k8s bot will automatically run the tests, and they're passing so no worries there. This all lgtm, thanks for the contribution!

2017-05-15 08:56 UTC, merged

2017-05-15 08:59 UTC, tyrannasaurusbanks commented
Thanks for the review @prydonius and for the help getting my first commit in!