Improve Hazelast Chart to support Scaling Up/Down
helm/charts pull request #9150
Opened 2018-11-09 17:46 UTC by leszko

#### What this PR does / why we need it:
- Update Hazelcast to 3.11
- Change Docker image to `hazelcast/hazelcast` (`hazelcast/hazelcast-kubernetes` is no longer supported)
- Add Graceful Shutdown feature (used in scaling down and rolling upgrade)
- Add `resolve-not-ready-addresses` property to check also not ready Hazelcast PODs
- Increase default parameters for livenessProbe and readinessProbe (helps in stability in case of rolling upgrade and huge amount of data)
- Simplify `hazelcast.xml` configuration

#### Which issue this PR fixes
None.

#### Special notes for your reviewer:
None.

#### Checklist
- [ x ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ x ] Chart Version bumped
- [ x ] Variables are documented in the README.md

2018-11-09 17:48 UTC, leszko commented
/assign @paulczar

2018-11-10 18:19 UTC, davidkarlsen requested changes

2018-11-10 18:19 UTC, davidkarlsen commented on stable/hazelcast/Chart.yaml
> +version: 1.0.2
```suggestion
version: 1.1.0
```

since there a bit more changes going on

2018-11-13 10:31 UTC, leszko commented
@davidkarlsen Thanks for the review. I applied the change suggested by you. PTAL.

2018-11-15 10:03 UTC, leszko commented
@davidkarlsen , could you please have a look?

2018-11-15 10:04 UTC, cpanato commented
/ok-to-test

2018-11-15 10:35 UTC, leszko commented
/approve

2018-11-16 09:02 UTC, leszko commented
Do you think this PR is ready to merge?

2018-11-22 11:04 UTC, cpanato commented
ping @davidkarlsen

2018-11-23 08:21 UTC, leszko commented
Any news on that? Could we finally get it merged? It's just a small change!

2018-11-27 08:34 UTC, leszko commented
Guys, it's already 18 days! Could you get it merged?

2018-11-28 08:06 UTC, leszko commented
Guys, again, can we get it merged?

@davidkarlsen @foxish @lachie83 @paulczar @cpanato

2018-11-29 22:26 UTC, davidkarlsen approved these changes

2018-11-29 22:34 UTC, merged