Allow custom annotations for default rules
helm/charts pull request #9154
Opened 2018-11-09 20:50 UTC by rajatvig

Signed-off-by: Rajat Vig <rvig@etsy.com>

#### What this PR does / why we need it:
Allow custom annotations for default rules so that `ruleSelector` modifications can work

#### Special notes for your reviewer:

#### Checklist
- [X] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [X] Chart Version bumped
- [X] Variables are documented in the README.md

2018-11-10 20:27 UTC, vsliouniaev requested changes
The implementation is missing disabling rules for a number of exporters, making the chart's behaviour inconsistent.

Please also consider related changes here: https://github.com/helm/charts/pull/9103

2018-11-10 20:27 UTC, vsliouniaev commented on stable/prometheus-operator/templates/all-prometheus-rules.yaml
> +{{ toYaml .Values.defaultRules.annotations | indent 4 }}
The indentation here is incorrect - annotations should appear under `metadata`. The current code would make them labels

2018-11-11 06:37 UTC, rajatvig commented on stable/prometheus-operator/templates/all-prometheus-rules.yaml
> +{{ toYaml .Values.defaultRules.annotations | indent 4 }}
Fixed it.

2018-11-11 10:50 UTC, vsliouniaev commented
There has been some discussion around doing this already: 
https://github.com/helm/charts/pull/8908#issuecomment-434428551

Syncing from upstream and keeping them in separate sections / files will require that we understand what rule relates to which exporter, which in turn means having information about the the list of metrics exposed by each

2018-11-11 18:01 UTC, gianrubio commented
@rajatvig as @vsliouniaev said, we should fix [8908](https://github.com/helm/charts/pull/8908#issuecomment-434428551) first. Adding more conditionals will cause problems in the future

2018-11-11 21:04 UTC, rajatvig commented
@gianrubio makes sense. will redo this PR to only include the annotations and label changes for default rules.

2018-11-12 22:06 UTC, rajatvig commented
@gianrubio @vsliouniaev does the change look ok to go? have removed the conditional logic from the rules file.

2018-11-12 22:09 UTC, vsliouniaev approved these changes

2018-11-13 09:06 UTC, gianrubio commented
/ok-to-test
/lgtm

2018-11-13 09:12 UTC, merged