Rabbitmq exporter env vars
helm/charts pull request #9244
Opened 2018-11-13 20:52 UTC by bobo333

#### What this PR does / why we need it:
The `rabbitmq-exporter` Dockerfile allows for additional environment variables to be passed in for configuration. This adds the missing environment variables to the helm chart so they may be configured. Specifically, it adds

- INCLUDE_VHOST
- SKIP_VHOST
- RABBIT_EXPORTERS
- OUTPUT_FORMAT
- RABBIT_TIMEOUT
- MAX_QUEUES

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-13 20:59 UTC, bobo333 commented
The linting step failed due to no maintainers being listed for the chart. I didn't remove them, they weren't there from the start. Is it ok to proceed despite this being the case?

2018-11-13 21:01 UTC, bobo333 commented
/assign @mgoodness

2018-11-27 23:08 UTC, bobo333 commented
@mgoodness @unguiculus @seanknox anything I can do to help this one along?

2018-12-13 22:02 UTC, vishiy commented
@bobo333 i see the same in my PR where by i clearly see maintainers. Did you resolve this ?

2018-12-15 02:49 UTC, bobo333 commented
@vishiy unfortunately I have not, I'm considering just putting myself as the maintainer

2018-12-15 02:50 UTC, bobo333 commented
/assign @unguiculus

2018-12-15 02:51 UTC, bobo333 commented
I'm hoping one of the project owners can give some guidance on how to proceed

2018-12-19 13:24 UTC, unguiculus commented
There's a type in `Chart.yaml`. That's why the linter fails

`mantainers`-> `maintainers`

2018-12-21 07:42 UTC, bobo333 commented
@unguiculus thank you for pointing that out, I probably should have found that myself.. 🤦‍♂️ 

regardless, looks like it's passing linting now, what are the next steps? thanks again!

2019-01-04 16:05 UTC, steven-sheehy commented
Can you merge from master? I didn't see your PR and my [PR](https://github.com/helm/charts/pull/10273) had some overlap with yours.

2019-01-04 18:08 UTC, bobo333 commented
@steven-sheehy no problem, I've updated this PR with the current master branch, thanks!

2019-01-04 18:16 UTC, steven-sheehy requested changes

2019-01-04 18:16 UTC, steven-sheehy commented on stable/prometheus-rabbitmq-exporter/Chart.yaml
> +appVersion: v0.29.1
Don't bump the appVersion. There is no v0.29.1 release: https://github.com/kbudde/rabbitmq_exporter/releases

2019-01-04 18:16 UTC, steven-sheehy commented on stable/prometheus-rabbitmq-exporter/README.md
>  | `rabbitmq.skip_queues`   | regex, matching queue names are not exported                           | `.*`                      |
Can you change this to ^$ to match values.yaml?

2019-01-04 18:16 UTC, steven-sheehy commented on stable/prometheus-rabbitmq-exporter/README.md
> +| `rabbitmq.exporters`.    | List of enabled modules. Just "connections" is not enabled by default  | `exchange,node,overview,queue` |
Remove extra period

2019-01-04 19:08 UTC, bobo333 commented
@steven-sheehy thank you for reviewing, I've addressed the comments

2019-01-04 19:19 UTC, steven-sheehy commented
/ok-to-test
@unguiculus lgtm

2019-01-08 10:05 UTC, bobo333 commented
@steven-sheehy @unguiculus anything I can do to move this along? looks like it just needs a "lgtm" label and then can be merged?

2019-01-09 20:32 UTC, unguiculus approved these changes

2019-01-09 20:32 UTC, unguiculus commented on stable/prometheus-rabbitmq-exporter/templates/deployment.yaml
> +              value: "{{ .Values.rabbitmq.max_queues }}"
In general, we want camel case, but since this matches the existing style, I'm going to accept this.

2019-01-09 20:32 UTC, unguiculus commented
/lgtm

2019-01-09 20:38 UTC, merged