stable/coredns: Add a configuration to choose serviceProtocol
helm/charts pull request #928
Opened 2017-04-15 06:41 UTC by shashidharatd

This is to fix the issue  #924 
It is found that when serviceType is "LoadBalancer", on some cloud environments CoreDNS fails to deploy.
CoreDNS listens on both "UDP" and "TCP", but due to limitations some cloud environment does not support external loadbalancers with both "UDP" & "TCP" protocols. 
To fix the issue, this pr adds a configurable parameter `serviceProtocol` to choose protocol for the service and the values could be one of "UDP", "TCP" or "UDPNTCP" (default). By default the service listens on both "UDP" and "TCP"

2017-04-17 03:33 UTC, shashidharatd commented
@lachie83, request to PTAL

2017-04-19 17:01 UTC, prydonius requested changes
Thanks @shashidharatd!

2017-04-19 17:01 UTC, prydonius commented on stable/coredns/README.md
> +CoreDNS service, by default is deployed to listen on both "TCP" and "UDP".
It might be good to have this notice or a similar one in NOTES.txt as well if the serviceType=LoadBalancer and the serviceProtocol= UDPNTCP

2017-04-19 17:01 UTC, prydonius commented on stable/coredns/Chart.yaml
> +version: 0.1.1
As per semver standards, this should be 0.2.0

2017-04-19 18:19 UTC, shashidharatd commented on stable/coredns/Chart.yaml
> +version: 0.1.1
Updated.

2017-04-19 18:19 UTC, shashidharatd commented on stable/coredns/README.md
> +CoreDNS service, by default is deployed to listen on both "TCP" and "UDP".
Added a note now. PTAL
Thanks!

2017-04-24 13:00 UTC, shashidharatd commented
@prydonius, gentle reminder. Have handled the comments. PTAL.

2017-04-24 19:02 UTC, prydonius approved these changes

2017-04-24 19:02 UTC, prydonius commented
Thanks @shashidharatd this lgtm!

2017-05-04 03:13 UTC, merged