[stable/traefik] dashboard serviceType
helm/charts pull request #9291
Opened 2018-11-15 08:23 UTC by Basster

#### What this PR does / why we need it:
This PR adds the ability to set the serviceType of the dashboard service. This is useful for when deploying to a managed k8s environment, e.g GKE.

#### Which issue this PR fixes
  - fixes #7912

#### Special notes for your reviewer:

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-15 08:31 UTC, Basster commented
/assign @nmengin

2018-11-19 17:49 UTC, dtomcej requested changes

2018-11-19 17:49 UTC, dtomcej commented on stable/traefik/README.md
> +| `dashboard.serviceType`                | ServiceType for the Traefik dashboard Service `ClusterIP`                             |
This should be a non-mandatory field

2018-11-19 17:49 UTC, dtomcej commented on stable/traefik/templates/dashboard-service.yaml
> +  type: {{ .Values.dashboard.serviceType }}
Should be non-mandatory

2018-11-19 17:49 UTC, dtomcej commented on stable/traefik/values.yaml
> +  serviceType: ClusterIP
Should be commented out.

2018-11-19 17:54 UTC, dtomcej commented
Also, Is this error coming from GKE directly? I am unsure as to why it is expecting a nodeport service at all....We are not exposing anything via that nodeport...so it seems redundant....

2018-12-01 13:34 UTC, ahoulgrave commented
Having the same issue. Deploying this chart creates a ClusterIP service, while it should be a NodePort.

Error:

```
Error during sync: error while evaluating the ingress spec: service "kube-system/jolly-jellyfish-traefik-dashboard" is type "ClusterIP", expected "NodePort" or "LoadBalancer"
```

2018-12-28 21:19 UTC, smatyas commented
I'm facing the same issue (also on GKE). How could we move forward with it? Can I help somehow?

2019-01-14 03:48 UTC, xaviablaza commented
Also facing a similar issue. This would really help!

2019-01-16 08:37 UTC, Basster commented
I'm currently a little busy and cannot push this issue. Maybe someone can take over and solve @dtomcej  comments.

2019-01-17 08:37 UTC, smatyas commented
I'm interested in doing this... possibly at the weekend.

2019-01-23 17:25 UTC, closed without merging