[stable/rabbitmq-ha] Update version rabbitmq exporter to version 0.29.0
helm/charts pull request #9312
Opened 2018-11-16 09:27 UTC by batazor

Signed-off-by: Victor Login <batazor111@gmail.com>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-21 00:56 UTC, davidkarlsen requested changes

2018-11-21 00:56 UTC, davidkarlsen commented on stable/rabbitmq-ha/values.yaml
> +      tag: v0.29.0
please update the readme too

2018-11-21 00:56 UTC, davidkarlsen commented
@batazor please fix merge conflict

2018-11-21 06:18 UTC, batazor commented on stable/rabbitmq-ha/values.yaml
> +      tag: v0.29.0
done

2018-11-21 06:18 UTC, batazor commented
@davidkarlsen done

2018-12-13 15:40 UTC, steven-sheehy commented
Can you bump version again?

2018-12-14 09:45 UTC, batazor commented
@steven-sheehy @davidkarlsen done

2018-12-14 15:56 UTC, steven-sheehy commented
You bumped the appVersion mistakenly. Please revert and bump the chart version instead.

2018-12-17 13:43 UTC, batazor commented
@steven-sheehy  done

2019-01-07 08:52 UTC, davidkarlsen approved these changes

2019-01-07 08:55 UTC, davidkarlsen commented
/lgtm

2019-01-07 08:58 UTC, merged