Make memcached a statefulset, add anti-affinity and podDisruptionBudget
helm/charts pull request #933
Opened 2017-04-18 10:41 UTC by dhilipkumars

1) Make it statefulset
2) Use alpine images
3) Add pod disruption budge
4) Insert soft Anti-affinity for better distribution.

2017-04-19 17:11 UTC, lachie83 requested changes

2017-04-19 17:11 UTC, lachie83 commented on stable/memcached/templates/pdb.yaml
> +apiVersion: policy/v1beta1
Please remove line end characters

2017-04-19 17:11 UTC, lachie83 commented on stable/memcached/templates/statefulset.yaml
> +kind: StatefulSet
How about we add the option to have some persistent storage given that you are moving this to a statefulset?

2017-04-19 17:11 UTC, lachie83 commented on stable/memcached/templates/svc.yaml
> +  clusterIP: None
What's the purpose of this? Is this required for Statefulset?

2017-04-19 17:13 UTC, prydonius requested changes
Thanks @dhilipkumars

2017-04-19 17:13 UTC, prydonius commented on stable/memcached/Chart.yaml
> +version: 0.5.1
0.5.0

2017-04-19 17:13 UTC, prydonius commented on stable/memcached/templates/pdb.yaml
> +  name: {{ template "fullname" . }}
This resource should have the app, chart, release and heritage labels as in the other resources.

2017-04-21 11:53 UTC, dhilipkumars commented on stable/memcached/templates/statefulset.yaml
> +kind: StatefulSet
AFAIK.  I dont think we use memcachd for disk persistence, popular usecase is 
```
value = Cache.Lookup(key)
if key did not exist then
  value =  DB.Read(key)
  cache.Set(key, value)
fi
```

2017-04-21 11:56 UTC, dhilipkumars commented on stable/memcached/templates/svc.yaml
> +  clusterIP: None
Yes statefulset requires Headlessservices and [this ](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services)is the way to create headless services

2017-04-21 12:00 UTC, dhilipkumars commented on stable/memcached/Chart.yaml
> +version: 0.5.1
done

2017-04-21 12:01 UTC, dhilipkumars commented on stable/memcached/templates/pdb.yaml
> +apiVersion: policy/v1beta1
done, and sorry

2017-04-21 12:01 UTC, dhilipkumars commented on stable/memcached/templates/pdb.yaml
> +  name: {{ template "fullname" . }}
added them.

2017-04-21 12:07 UTC, dhilipkumars commented
@prydonius and @lachie83 Thanks for reviewing PTAL now.

2017-05-04 03:26 UTC, seanknox commented
@k8s-bot ok to test

2017-05-04 07:51 UTC, dhilipkumars commented
@seanknox 
```
W0503 20:27:25.074] Error: release memcach-1468 failed: error validating "": error validating data: found invalid field affinity for v1.PodSpec
```
Are these charts tested against older kubernetes like 1.5?  Affinity moved to podspec from 1.6.  I think that is the error.

2017-05-04 15:52 UTC, seanknox commented
I believe charts test against v1.5 only at the moment.

2017-05-04 16:42 UTC, dhilipkumars commented
How do we handle this situation? Shouldn't it be upgraded to 1.6?

2017-05-09 10:24 UTC, dhilipkumars commented
Hi @seanknox, i was told that the CI is now upgraded to 1.6, how do i trigger a test again?

2017-05-09 16:06 UTC, seanknox commented
@k8s-bot ok to test

2017-05-09 16:06 UTC, seanknox commented
Thanks @dhilipkumars

2017-05-15 17:34 UTC, prydonius commented
Switching from Deployment to StatefulSet is a breaking change so I would bump this chart to 1.0.0. Other than that, this lgtm - thanks @dhilipkumars!

2017-05-17 09:29 UTC, dhilipkumars commented
@prydonius Thanks for the suggestion it is done now.  PTAL

2017-05-17 10:52 UTC, prydonius approved these changes

2017-05-17 10:52 UTC, prydonius commented
Thanks @dhilipkumars!

2017-05-17 10:52 UTC, merged