Add Hazelcast Jet Helm Chart
helm/charts pull request #9372
Opened 2018-11-19 10:32 UTC by eminn

### What this PR does / why we need it:
Add Helm Chart for Hazelcast Jet (https://jet.hazelcast.org/)

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:

#### Checklist
This is an initial PR for Hazelcast Jet, which will be maintained by the Hazelcast Organization (exact names are mentioned in Charts.yaml and OWNERS).

2018-11-26 08:08 UTC, eminn commented
/assign @davidkarlsen

2018-12-19 09:37 UTC, leszko commented
@davidkarlsen , could you kindly have a look at this PR? We belive it's ready to be merged.

2018-12-19 09:42 UTC, davidkarlsen requested changes

2018-12-19 09:42 UTC, davidkarlsen commented on stable/hazelcast-jet/README.md
> +    hazelcast/hazelcast-jet
```suggestion
    stable/hazelcast-jet
```

2018-12-19 09:44 UTC, davidkarlsen commented
/ok-to-test

2018-12-19 12:35 UTC, davidkarlsen approved these changes

2018-12-19 12:35 UTC, davidkarlsen commented
/lgtm

2018-12-19 12:46 UTC, merged