[stable/fluent-bit] Add existing secret for ES credentials
helm/charts pull request #9374
Opened 2018-11-19 11:25 UTC by endrec

#### What this PR does / why we need it:
This changest adds the possibility to use an existing K8S secret for ES credentials and certificate.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-30 16:37 UTC, kfox1111 commented
lgtm

2018-11-30 16:39 UTC, edsiper commented
Looks like chart version is not correct.

2018-11-30 17:50 UTC, endrec commented
@edsiper Corrected version. It was correct, when I filed the PR. :stuck_out_tongue:

2018-12-31 16:35 UTC, kfox1111 commented on stable/fluent-bit/templates/daemonset.yaml
> +{{- if or .Values.env (not .Values.backend.es.http_passwd_secret) }}
I'm not following the logic here...

If values is nothing, and http_password_secret is nothing, still toYaml .Values.env?

Shouldn't this be this:
{{- if .Values.env }}

?

2018-12-31 16:37 UTC, kfox1111 commented on stable/fluent-bit/templates/daemonset.yaml
> -{{- end }}
This seems broken here... where did the end go? its merging a large chunk of code into the above conditional incorrectly?

2018-12-31 16:40 UTC, kfox1111 commented on stable/fluent-bit/templates/daemonset.yaml
>            secretName: "{{ template "fluent-bit.fullname" . }}-es-tls-secret"
Could you just put the conditional around the secretName line? Everything else seems to be the same.

2018-12-31 16:43 UTC, kfox1111 requested changes
A few issues

2019-02-13 18:22 UTC, closed without merging