[stable/traefik] Generate self sign default cert
helm/charts pull request #9375
Opened 2018-11-19 12:47 UTC by kozmagabor

Signed-off-by: Gabor Kozma <gabo@kozmagabor.com>

#### What this PR does / why we need it:
I want to generate cert with specific information. (CN,SAN etc.)

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:
Cloud you check it  @dtomcej  @emilevauge @krancour @ldez, please?

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-19 17:59 UTC, dtomcej requested changes

2018-11-19 17:59 UTC, dtomcej commented on stable/traefik/templates/default-cert-secret.yaml
> +  {{- $cn := .Values.ssl.defaultCN }}
Default CN should be optional.

2018-11-19 17:59 UTC, dtomcej commented on stable/traefik/values.yaml
> +  defaultCN: ""
should be commented out by default.

2018-11-19 17:59 UTC, dtomcej commented
I like the sprig-foo :) Just some comments for usability :)

2018-11-19 18:00 UTC, dtomcej commented on stable/traefik/templates/default-cert-secret.yaml
> +  {{- $cn := .Values.ssl.defaultCN }}
All values but `generateTLS` should be optional (aka need a test for existence before use)

2018-11-19 20:55 UTC, kozmagabor commented
Thanks, @dtomcej I updated my PR

2018-11-20 20:55 UTC, dtomcej commented
@kozmagabor Can you bump the chart version?

2018-11-21 09:35 UTC, kozmagabor commented
@dtomcej It's already bumped to 1.53.0

2018-11-23 09:48 UTC, kozmagabor commented
Ohh, sorry. You are right!  I fixed it.

2018-11-26 16:08 UTC, kozmagabor commented
@dtomcej Could you check it again? Thanks!

2018-12-03 21:40 UTC, kozmagabor commented
@juliens @nmengin Could you check it?

2018-12-20 15:24 UTC, dtomcej commented
Hello @kozmagabor, can you bump the version, so that we can get it merged? Sorry for the delay, catching up after Kubecon.

2019-01-08 18:44 UTC, kozmagabor commented
Hi @dtomcej 

Could you check it again?

2019-01-08 19:13 UTC, kozmagabor commented
Anybody else? @juliens @nmengin

2019-01-08 19:45 UTC, dtomcej commented
/lgtm

2019-01-08 19:52 UTC, merged