Updating image
helm/charts pull request #9383
Opened 2018-11-19 19:20 UTC by naseemkullah

#### What this PR does / why we need it:
Update image from 1.3 to current 1.7 ....

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md *

*No values in README at this time...

2018-11-20 20:06 UTC, naseemkullah commented
cc @jackzampolin

2018-11-28 01:20 UTC, naseemkullah commented
bump

2018-11-28 18:52 UTC, jackzampolin commented
Looks good!

2018-12-01 23:41 UTC, scottrigby requested changes
Same as https://github.com/helm/charts/pull/9384#issuecomment-443467617

2018-12-02 18:32 UTC, naseemkullah commented
Thanks @scottrigby, the requested changes have been applied, please review and let me know if any further changes are required!

@jackzampolin I've added you as an OWNERS of this chart.

2018-12-03 23:01 UTC, scottrigby approved these changes

2018-12-03 23:01 UTC, scottrigby commented
/ok-to-test

2018-12-03 23:04 UTC, scottrigby commented
/lgtm

2018-12-03 23:06 UTC, merged

2018-12-03 23:11 UTC, scottrigby commented
OWNERS file also contributes to helping #7446