[stable/grafana] Add variable to optionally set priorityClassName
helm/charts pull request #9427
Opened 2018-11-20 20:12 UTC by chrisob

Signed-off-by: Chris O'Brien <chrisob91@gmail.com>

@zanhsieh @rtluckie 

#### What this PR does / why we need it:
Allow `priorityClassName` to be set for Grafana's `podSpec`.

#### Which issue this PR fixes
  - fixes #9424 

#### Checklist
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-20 20:18 UTC, chrisob commented
/assign @scottrigby

2018-11-20 20:20 UTC, chrisob commented
/joke

2018-11-20 20:36 UTC, zanhsieh approved these changes

2018-11-21 00:47 UTC, davidkarlsen requested changes

2018-11-21 00:47 UTC, davidkarlsen commented on stable/grafana/Chart.yaml
> +version: 1.18.1
1.19.0

2018-11-21 00:48 UTC, davidkarlsen commented
/assign
/ok-to-test

2018-11-21 13:33 UTC, chrisob commented on stable/grafana/Chart.yaml
> +version: 1.18.1
:+1:

2018-11-22 16:34 UTC, chrisob commented
ping @davidkarlsen I've bumped the chart version as suggested, looks ok?

2018-11-26 17:04 UTC, davidkarlsen approved these changes

2018-11-26 17:04 UTC, davidkarlsen commented
/lgtm

2018-11-26 17:11 UTC, merged