Add GoCD chart
helm/charts pull request #943
Opened 2017-04-19 18:03 UTC by seanknox

This adds a chart for [GoCD](https://www.gocd.io/), a CI/CD server from Thoughtworks.

I've built GoCD server and agent images that work a bit better than the official ones (namely, the official images don't log to STDOUT).

2017-04-19 18:04 UTC, seanknox commented
For your consideration @viglesiasce @lachie83 @mgoodness

2017-04-20 10:58 UTC, prydonius commented
@k8s-bot ok to test

2017-05-05 04:39 UTC, viglesiasce requested changes
I was able to install it fine but was not able to get a build to go through. I tried to create a simple pipeline in the initial wizard that just did a docker build based on a git repo. I dont believe any jobs every launched. Happy to take a look with you offline @seanknox.

2017-05-05 04:39 UTC, viglesiasce commented on stable/gocd/templates/agent-deployment.yaml
> +      containers:
Should we be bind mounting in the docker socket+binary so that the agent can use it for docker builds?

2017-06-01 05:30 UTC, viglesiasce commented
Marking as stale. @seanknox please update within the next week.

2017-06-02 06:39 UTC, seanknox commented
Thanks Vic and sorry I haven't been able to devote more time to it. Closing.

2017-06-02 06:39 UTC, closed without merging

2017-06-02 07:31 UTC, prydonius commented
@seanknox you could put this in incubator if you want to pick it up again later