[stable/jenkins] add nodes
helm/charts pull request #9470
Opened 2018-11-22 04:51 UTC by liangsdet

Signed-off-by: liangsdet <sdetliang@gmail.com>

#### What this PR does / why we need it:
Add Jenkins node config

#### Special notes for your reviewer:
Thank you

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-22 05:53 UTC, liangsdet commented
/assign @viglesiasce

2018-11-23 02:47 UTC, liangsdet commented
@lachie83 
Could you please take a look?

2018-11-28 05:57 UTC, liangsdet commented
Hi @viglesiasce, @lachie83 and @mattfarina
Could you please take a look at this?

2018-12-06 18:11 UTC, viglesiasce requested changes
Can you add documentation to the README on how/why this is used?

2018-12-06 18:11 UTC, viglesiasce commented on stable/jenkins/Chart.yaml
> +
Remove whitespace.

2018-12-06 18:11 UTC, viglesiasce commented on stable/jenkins/Chart.yaml
> +
remove whitespace

2019-01-08 06:00 UTC, liangsdet commented on stable/jenkins/Chart.yaml
> +
Thanks @viglesiasce , It's fixed

2019-01-08 06:00 UTC, liangsdet commented on stable/jenkins/Chart.yaml
> +
Thanks @viglesiasce , It's fixed

2019-01-08 13:53 UTC, liangsdet commented
Hi @viglesiasce,

Thanks for the review, the issue in review has been fixed. And the instruction has been added into README.

Could you please review again? This new feature will add permanent nodes.

2019-01-08 20:12 UTC, viglesiasce commented
Thanks @liangsdet! 

Adding @maorfr who is helping out with Jenkins chart reviews.

@maorfr can you take a look?

/unassign
/assign @maorfr

2019-01-09 03:21 UTC, liangsdet commented
@maorfr 
Thanks a lot for your reply. I have resolve the conflict and add the following use case.

`If you need to add dedicated and permanent agent machine, you may need this.`

2019-01-09 08:00 UTC, maorfr commented
Thanks @liangsdet,

First of all, I can't install the chart with your changes -
```
MountVolume.SetUp failed for volume "jenkins-nodes" : configmap "jenkins-nodes" not found
```

I would like to better understand this feature.
When you say nodes - you actually mean slaves. Am I correct?

If so, since we already have a slave configuration under `Agent` in the values file, and a `config.yaml` template to describe it, it feels strange to define the xml for a node again (duplication?).

If I am indeed correct, I would expect this feature to be exposed in a very simple way. For example:
values.yaml:
```
...
Agent:
  PermanentNodes: 0 # change this setting to have permanent nodes
```

In addition, I don't feel it is right to define the node spec in `values.yaml`, it is cumbersome enough as it is.

Would love to hear your thoughts on that. If I am mistaken, please correct me!

2019-01-10 11:41 UTC, maorfr commented
/hold

2019-01-15 09:22 UTC, liangsdet commented
Thanks, will close for now

2019-01-15 09:22 UTC, closed without merging