Add Fluentd > cloudwatch log forwarder
helm/charts pull request #952
Opened 2017-04-21 21:05 UTC by kenden

Picked up/Updated fluentd-cloudwatch changes from PR https://github.com/kubernetes/charts/pull/211

Now using image from https://github.com/fluent/fluentd-kubernetes-daemonset

The configuration is now inside the image (from PR comment:
#211 (comment)). I then removed the configMap holding that config.

The AWS keys are added as secrets from files, using Files.Glob (from PR
comment
#211 (comment))

2017-05-03 10:10 UTC, so0k commented
I've been using a private helm chart while testing out several logging targets (logzio,loggly,logentries,...) and found that I still needed the config files in a configmap 😢 

Even though the images are slim (each tag only has the minimum required to target it's logging target), config often needed to be customised further through config files.

2017-05-04 03:22 UTC, seanknox commented
@k8s-bot ok to test

2017-05-11 17:42 UTC, kenden commented
@so0k I re-added a configMap. It has the same config than what is inside the docker image 
fluent/fluentd-kubernetes-daemonset:v0.12-cloudwatch

2017-07-20 19:05 UTC, unguiculus commented
ping @mgoodness

2017-09-17 09:59 UTC, unguiculus requested changes
We've started namespacing templates. Please apply this to your PR as well. See #1785.

2017-09-17 09:59 UTC, unguiculus commented on incubator/fluentd-cloudwatch/templates/configmap.yaml
> +    app: {{ template "fullname" . }}
`app: {{ template "name" . }}`

2017-09-17 09:59 UTC, unguiculus commented on incubator/fluentd-cloudwatch/Chart.yaml
> +maintainers:
Use Github usernames.

2017-09-17 09:59 UTC, unguiculus commented on incubator/fluentd-cloudwatch/Chart.yaml
> +version: 0.1.0
Add `appVersion`

2017-09-17 09:59 UTC, unguiculus commented on incubator/fluentd-cloudwatch/Chart.yaml
> +version: 0.1.0
Is there an `icon` you could add?

2017-09-19 09:39 UTC, kenden commented
@unguiculus I updated the Chart as requested

2017-09-19 09:39 UTC, kenden commented on incubator/fluentd-cloudwatch/templates/configmap.yaml
> +    app: {{ template "fullname" . }}
done

2017-09-19 09:39 UTC, kenden commented on incubator/fluentd-cloudwatch/Chart.yaml
> +version: 0.1.0
done and done

2017-09-19 09:39 UTC, kenden commented on incubator/fluentd-cloudwatch/Chart.yaml
> +maintainers:
done

2017-10-12 12:45 UTC, unguiculus requested changes
Sorry for the delay. Almost there.

2017-10-12 12:45 UTC, unguiculus commented on incubator/fluentd-cloudwatch/templates/configmap.yaml
> +    app: {{ template "fluentd-cloudwatch.fullname" . }}
`app: {{ template "fluentd-cloudwatch.name" . }}`

2017-10-12 12:46 UTC, unguiculus commented
/ok-to-test

2017-10-12 13:23 UTC, kenden commented
@unguiculus Updated

2017-10-12 19:23 UTC, unguiculus approved these changes

2017-10-12 19:23 UTC, unguiculus commented
/lgtm

2017-10-12 19:24 UTC, unguiculus commented
Sorry this took so long in the end.

2017-10-12 19:24 UTC, merged