Submit stable Voyager chart
helm/charts pull request #954
Opened 2017-04-24 05:48 UTC by saumanbiswas

cc: @sadlil @TamalSaha

2017-05-04 03:21 UTC, seanknox commented
Hi @saumanbiswas, thanks for your contribution! Can you provide some background on what Voyager is and why it might be relevant in the charts repo?

2017-05-08 14:17 UTC, linki commented
@saumanbiswas your Chart isn't structured correctly. `Chart.yaml` etc. should live under `stable/voyager`, not `stable/voyager/voyager`. Can you just move them over?

2017-05-08 14:21 UTC, linki commented on stable/voyager/voyager/templates/deployment.yaml
> +    run: {{ template "fullname" . }}
this label name should rather be `app`

2017-05-08 14:22 UTC, linki commented on stable/voyager/voyager/README.md
> +| `imageTag`                 |  Image tag of container      | `1.5.1`              |
please also document `cloudProvider` and `clusterName`, their meaning and default values, if any.

2017-05-08 14:23 UTC, linki commented on stable/voyager/voyager/templates/deployment.yaml
> +        - --v=3
The value of `--v` should be configurable or just leave it at their default?

2017-05-08 14:24 UTC, linki commented on stable/voyager/voyager/templates/deployment.yaml
> +        name: {{ template "name" . }}
I think it's fine to just call it "voyager".

2017-05-08 14:31 UTC, linki commented on stable/voyager/voyager/templates/deployment.yaml
> +          name: zero
Are these things (port 1234, name: zero) something related to voyager? If not I would prefer just using 8080 and name: http here or something similar.

2017-05-08 14:31 UTC, linki commented on stable/voyager/voyager/templates/svc.yaml
> +    run: {{ template "fullname" . }}
This should be `app` as well.

2017-05-08 14:32 UTC, linki commented on stable/voyager/voyager/templates/deployment.yaml
> +        run: {{ template "fullname" . }}
This should be `app` as well.

2017-05-08 14:32 UTC, linki commented on stable/voyager/voyager/templates/deployment.yaml
> +      run: {{ template "fullname" . }}
This should be `app` as well.

2017-05-08 14:32 UTC, linki commented on stable/voyager/voyager/templates/svc.yaml
> +    run: "{{ template "fullname" . }}"
This should be `app` as well.

2017-05-08 14:36 UTC, linki submitted a review, later dismissed
Chart needs to be moved to the correct folder in order to run the tests.

2017-06-01 05:51 UTC, viglesiasce commented
Marking as stale. @saumanbiswas please update in the next week if you'd like this to be merged.

2017-06-01 10:36 UTC, TamalSaha commented on stable/voyager/values.yaml
> +imageTag: 1.5.1
@saumanbiswas , use image tag 1.5.5

2017-06-01 15:29 UTC, linki commented
@k8s-bot ok to test

2017-06-02 10:05 UTC, linki commented on stable/voyager/templates/NOTES.txt
> +  kubectl --namespace={{ .Release.Namespace }} get deployments -l "release={{ .Release.Name }}, run={{ template "fullname" . }}"
This still references the `run` label.

2017-06-02 10:06 UTC, linki commented
@seanknox FWIK, voyager is an ingress controller, much like the nginx ingress controller.

2017-06-14 20:18 UTC, unguiculus requested changes

2017-06-14 20:18 UTC, unguiculus commented on stable/voyager/templates/deployment.yaml
> +    app: {{ template "fullname" . }}
Please use `{{ template "name" . }}` for the `app` label. Apply everywhere.

2017-06-14 20:18 UTC, unguiculus commented on stable/voyager/templates/svc.yaml
> +    app: "{{ template "fullname" . }}"
After changing the `app` as mentioned above, the selector should be as follows:

```yaml
app: {{ template "name" . }}
release: {{ .Release.Name }}
```

2017-06-14 20:18 UTC, unguiculus commented on stable/voyager/templates/deployment.yaml
> +    chart: {{.Chart.Name}}-{{.Chart.Version}}
Please use consistent formatting, i. e. space after `{{` and space before `}}`. Apply everywhere.

2017-06-14 20:18 UTC, unguiculus commented on stable/voyager/Chart.yaml
> +  - name: 'AppsCode Inc.'
Use Github username.

2017-06-16 14:28 UTC, TamalSaha commented
@unguiculus , I have addressed your comments.

2017-06-18 16:32 UTC, unguiculus approved these changes

2017-06-20 15:46 UTC, merged