update magento README
helm/charts pull request #958
Opened 2017-04-24 15:32 UTC by bryanlarsen

- add minikube installation instructions
- add metal installation instructions
- add some missing configuration variables
- remove problematic html install --set instructions
- fix NOTES.TXT for serviceType of NodePort, assuming minikube

2017-04-24 15:38 UTC, bryanlarsen commented
CLA signed.

2017-05-04 03:19 UTC, seanknox commented
@k8s-bot ok to test

2017-05-05 14:56 UTC, sameersbn requested changes
I see you have added section on installing on GKE, Minikube and Metal. In my opinion you only need to specify the right `serviceType`. All other parameters will be the same isn't it?

2017-05-05 14:56 UTC, sameersbn commented on stable/magento/README.md
> +### Installing on GKE
You have a typo here, the code block should be closed before the `Installing on GKE` section start.

2017-05-05 14:56 UTC, sameersbn commented on stable/magento/README.md
>  > **Note**:
I see you have moved this into a Installing on GKE section. But the whole section looks missing/incomplete.

2017-05-05 14:56 UTC, sameersbn commented on stable/magento/README.md
> +    $ helm inspect values stable/magento > values.yaml
You should use command formatting syntax here, i.e.

`$ helm inspect values stable/magento > values.yaml`

2017-05-05 14:56 UTC, sameersbn commented on stable/magento/README.md
> +    $ helm install --name my-release -f values.yaml stable/magento
Use command formatting syntax here as well.

2017-05-05 19:30 UTC, bryanlarsen commented on stable/magento/README.md
>  > **Note**:
Yup, that's existing text.   I don't have a GKE account.

2017-05-05 19:32 UTC, bryanlarsen commented
"All other parameters will be the same isn't it?"

No, requirements and persistence are different.

2017-06-01 05:47 UTC, viglesiasce commented
@bryanlarsen can you update as per @sameersbn's requests?

@sameersbn can you just make the changes and merge it in?

2017-06-01 14:13 UTC, bryanlarsen commented
I'm not using this chart any longer, so go ahead and update as you see fit.

2017-06-11 02:25 UTC, seanknox commented
Closing as it's stale. Feel free to re-open if you like.

2017-06-11 02:25 UTC, closed without merging