Update fluentd es
helm/charts pull request #9601
Opened 2018-11-28 14:54 UTC by ahsan-storm

Signed-off by: Muhammad Ahsan
username: ahsan-storm
email: ahsanmuhammad1@outlook.com

#### What this PR does / why we need it:
- Adds support for custom kubernetes resources
- Adds support for making configmap optional
- Adds support for annotations in daemonset
- Adds support for update strategy in daemonset
- Adds support for host network in daemonset
- Adds support for dns policy in daemonset
- Adds support for adding extra envs in daemonset

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-11-30 13:01 UTC, ahsan-storm commented
@lachie83 kindly review this PR, and merge it in master

2018-12-12 13:33 UTC, ahsan-storm commented
/assign @monotek

2018-12-12 13:34 UTC, ahsan-storm commented
@monotek @lachie83 Kindly review this PR, and merge it in master

2018-12-12 14:19 UTC, monotek commented
I'm currently waiting for somebody to merge: https://github.com/helm/charts/pull/9382
After that i'll have a look on this pr asap :-)

2018-12-25 00:09 UTC, monotek commented
Please fix merge conflicts....

2018-12-25 15:23 UTC, monotek requested changes

2018-12-25 15:23 UTC, monotek commented on stable/fluentd-elasticsearch/templates/customResources.yaml
> +{{- if .Values.customResources -}}
What kind of custom resources are we talking about here?

Is it about Kubernetes CRDs? If not, the name is misleading. 
I would suggest "Additional resources" in this case.

2018-12-25 15:23 UTC, monotek commented on stable/fluentd-elasticsearch/templates/daemonset.yaml
> +  updateStrategy:
Imho we should set "RollingUpdate" as the default in the values.yaml so we can remove the if statement.

2018-12-25 15:23 UTC, monotek commented on stable/fluentd-elasticsearch/templates/daemonset.yaml
> +      dnsPolicy: {{ .Values.daemonset.dnsPolicy }}
Same as for updatestrategey. I'd like to see "Default" set in the values.yaml and the if statement removed.

2018-12-25 15:23 UTC, monotek commented on stable/fluentd-elasticsearch/templates/daemonset.yaml
> +      hostNetwork : {{ .Values.daemonset.hostNetwork }}
Why do you want to use hostNetwork?
Did you considered to use NodePort instead?

2018-12-25 15:23 UTC, monotek commented on stable/fluentd-elasticsearch/values.yaml
> +  hostNetwork: true
I don't want to see this set to "true" by default.
Using of hostNetwork is discouraged. See: https://kubernetes.io/docs/concepts/configuration/overview/#services

2018-12-25 15:23 UTC, monotek commented on stable/fluentd-elasticsearch/values.yaml
> +  dnsPolicy: ClusterFirstWithHostNet
Should be "Default" by default.

2018-12-27 10:50 UTC, closed without merging

2018-12-27 11:30 UTC, monotek commented
@ahsan-storm 
Why do you have closed the pr?

2018-12-29 21:03 UTC, ahsan-storm commented
@monotek I actually don't need these changes now