[stable/suitecrm] Add ingress
helm/charts pull request #9640
Opened 2018-11-30 06:42 UTC by chriskolenko

Using other helm charts as a reference I've added in an Ingress template.
- enabled pattern with default to false
- standard annotations + tls values

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-11-30 06:43 UTC, chriskolenko commented
/assign @sameersbn

2018-12-02 21:22 UTC, davidkarlsen requested changes

2018-12-02 21:22 UTC, davidkarlsen commented on stable/suitecrm/Chart.yaml
> +version: 5.0.2
new feature
```suggestion
version: 5.1.0
```

2018-12-04 23:48 UTC, chriskolenko commented
@tompizmor or @carrodher any chance for a review? I've tested this change in a dev cluster with nginx-ingress + cert-manager + external-dns successfully.

2018-12-06 02:02 UTC, chriskolenko commented
> Thanks for the contribution! Changes LGTM, but I would add more information to the NOTES.txt. I mean, some explanation in the ingress `if` like we are doing in the `NodePort` or `ClusterIP`, what do you think?

Damn, it's like you knew where I was struggling. I only quickly patched the NOTES.txt because of the number of if statements. My brain got a little lost.

After reviewing what I wrote. I'm believe it could be made better if we treated Ingress as an unconditional extra instead of an if/else. I.E. If ingress is enabled.. you get a list of the ingress host names and all the Service information. 

Let me change it quickly. Sorry about this message, it came to me writing this comment.

2019-01-07 08:18 UTC, tompizmor commented
Hello @chriskolenko,

Thanks for sending this PR. I am not sure which other charts you have used as a reference but I miss a couple of small features. Please check this other recent PR as reference https://github.com/helm/charts/pull/10335

Precisely, I am missing to be able to provide [custom tls certificates](https://github.com/helm/charts/blob/master/stable/prestashop/values.yaml#L195-L207) from the values.yaml and the [certManager switch](https://github.com/helm/charts/blob/master/stable/prestashop/values.yaml#L171-L172).

Apart from that, please rebase from master to fix te conflicts.

2019-02-20 08:43 UTC, closed without merging