[stable/mysqldump] Add subpath to mysqldump persistence
helm/charts pull request #9654
Opened 2018-11-30 16:52 UTC by Scuilion

Signed-off-by: Kevin O'Neal <oneal.kevin@gmail.com>

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-12-17 20:52 UTC, paulczar requested changes
please fix merge conflicts

2018-12-30 21:46 UTC, Scuilion commented
@paulczar merge conflicts fixed!

2019-01-08 13:38 UTC, monotek commented
/ok-to-test

2019-01-08 13:56 UTC, monotek commented
/lgtm

2019-01-08 14:16 UTC, merged