[stable/prometheus-operator] Upgrading prometheus version to v2.5.0
helm/charts pull request #9710
Opened 2018-12-04 10:14 UTC by harshal-shah

- Upgrading prometheus-operator version to 0.26.0
- Upgrading prometheus version to 2.5.0
- Upgrading alertmanager version to 0.15.3
- Tested on GKE by installing prometheus operator with above versions.
- helm lint passed.

Signed-off-by: Harshal Shah <harshal2623@gmail.com>

#### What this PR does / why we need it:
prometheus operator released a new version. This PR uses the new version of this operator. 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-12-04 10:30 UTC, paskal commented
Could you please alter your changes so they won't interfere with https://github.com/helm/charts/pull/9647 and most important do not update prometheus-operator to 0.26.0 because of https://github.com/coreos/prometheus-operator/issues/2182?

2018-12-04 10:39 UTC, harshal-shah commented
I tested quickly with persistent storage and ran into coreos/prometheus-operator#2182

#9647 is doing pretty much the same thing. I will close this and keep test #9647 on GKE whenever it is ready

2018-12-04 10:40 UTC, harshal-shah commented
closing in favor of #9647

2018-12-04 10:59 UTC, paskal commented
@harshal-shah, I think updating prometheus and alertmanager is worth to do before updating prometheus-operator, as well as adding `stable/prometheus-operator/CONTRIBUTING.md`. Could you please reopen this PR with only these changes? Thank you for your work!

2018-12-05 10:57 UTC, harshal-shah commented
@paskal Added a new commit and reopened the PR.

2018-12-05 12:29 UTC, paskal requested changes

2018-12-05 12:29 UTC, paskal commented on stable/prometheus-operator/Chart.yaml
> +appVersion: "0.26.0"
should be 0.25.0

2018-12-05 12:52 UTC, paskal approved these changes

2018-12-08 22:35 UTC, davidkarlsen commented
/ok-to-test
/assign
/lgtm

2018-12-08 23:03 UTC, merged