Add configmap
helm/charts pull request #9770
Opened 2018-12-06 11:52 UTC by faizanahmad055

Signed-off-by: Faizan Ahmad
username: faizanahmad055
email: faizan.ahmad55@outlook.com

#### What this PR does / why we need it:
Configmaps chart is used in conjunction with other charts. It can come in handy when a public chart does not provide support for the additional configmaps. In that scenario, this chart can be used to deploy additional configmaps.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-12-06 15:24 UTC, faizanahmad055 commented
Hi @seanknox and @mgoodness

Can you guys please take a look

2018-12-10 15:25 UTC, philoserf requested changes

2018-12-10 15:25 UTC, philoserf commented on stable/configmaps/README.md
> +```bash
This is YAML not shell.

2018-12-10 15:25 UTC, philoserf commented on stable/configmaps/templates/NOTES.txt
> +configmaps chart is used with conjunction of other charts. It can come in handy when a public chart does not provide support for additional configmaps. In that scenario, this chart can be used to dep
NOTES.txt is intended as a post install message. This is simply a restatement of the purpose from the README.

2018-12-10 15:25 UTC, philoserf commented on stable/configmaps/README.md
> +This chart is used to apply configmaps. You can specify any number of configmaps. This chart can come in handy when a public chart does not offer additional configmaps. You have to use the following
I think the README need a little more information about the use cases this chart solves. Perhaps a specific example of using it with one of the “public charts”.

2018-12-12 14:22 UTC, faizanahmad055 commented on stable/configmaps/README.md
> +This chart is used to apply configmaps. You can specify any number of configmaps. This chart can come in handy when a public chart does not offer additional configmaps. You have to use the following
Updated

2018-12-12 14:22 UTC, faizanahmad055 commented on stable/configmaps/README.md
> +This chart is used to apply configmaps. You can specify any number of configmaps. This chart can come in handy when a public chart does not offer additional configmaps. You have to use the following
Updated

2018-12-12 14:23 UTC, faizanahmad055 commented on stable/configmaps/templates/NOTES.txt
> +configmaps chart is used with conjunction of other charts. It can come in handy when a public chart does not provide support for additional configmaps. In that scenario, this chart can be used to dep
Updated

2018-12-12 17:50 UTC, philoserf commented
I can’t move the pull request along @faizanahmad055. Like you, I am a member of the community. I’m not an approver.

2018-12-13 06:46 UTC, faizanahmad055 commented
Hi @foxish and @mgoodness
Ping

2018-12-17 06:47 UTC, faizanahmad055 commented
Hi @foxish and @mgoodness
Ping

2018-12-19 08:16 UTC, faizanahmad055 commented
Hi @seanknox and @mgoodness
Can you guys take a look? All requested changes have been implemented. If there are any more; please do let me know.

2018-12-24 12:01 UTC, faizanahmad055 commented
Hi @seanknox and @mgoodness
Ping

2019-01-08 08:55 UTC, faizanahmad055 commented
Hi @seanknox and @mgoodness
Any update on this please

2019-02-21 09:30 UTC, closed without merging