[stable/keycloak] Update pullSecrets variable usage
helm/charts pull request #9802
Opened 2018-12-07 14:41 UTC by alivespirit

#### What this PR does / why we need it:
Updating pullSecrets variable to match the example in values.yaml. Current version has this example:
```
    pullSecrets: []
    #  - myRegistrKeySecretName
```
but the construction in [templates/statefulset.yaml](templates/statefulset.yaml) expects it to be:
```
    pullSecrets:
      - name: myRegistrKeySecretName
```
So, if pull secrets are set like in values.yaml, deploy fails with error like `Spec: v1.PodSpec: ImagePullSecrets: []v1.LocalObjectReference: readObjectStart: expect { or n, parsing 2503 ...ecrets"`
My changes update template to use pull secret value in a similar way as in stable/postgresql chart.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] pullSecret variable usage updated
- [x] Chart Version bumped

2018-12-07 14:47 UTC, unguiculus commented
I'd prefer to keep it a it is. The sample in the comment in `values.yaml` should be fixed.

2018-12-07 14:53 UTC, alivespirit commented
@unguiculus But this way we are going to have inconsistency in values if we want to set pull secrets for both keycloak and postgres. E.g.:
```
keycloak:
  image:
    pullSecrets:
      - name: myRegistrKeySecretName
postgresql:
  image:
    pullSecrets:
      - myRegistrKeySecretName
```
I think we should stick to one standard.

2018-12-07 16:00 UTC, unguiculus requested changes
OK, accepted. Then let's go ahead and change this. Please consider my comments.

2018-12-07 16:00 UTC, unguiculus commented on stable/keycloak/values.yaml
> +    # pullSecrets:
Keep it as an empty list

2018-12-07 16:00 UTC, unguiculus commented on stable/keycloak/templates/statefulset.yaml
> +    {{- if .Values.keycloak.image.pullSecrets }}
Keep `with` instead of `if` as it was.

2018-12-07 17:05 UTC, alivespirit commented on stable/keycloak/templates/statefulset.yaml
> +    {{- if .Values.keycloak.image.pullSecrets }}
Tested:
1)
```
    {{- with .Values.keycloak.image.pullSecrets }}
      imagePullSecrets:
      - name: {{ . }}
    {{- end }}
```
`ImagePullSecrets: []v1.LocalObjectReference: v1.LocalObjectReference: Name: ReadString: expects " or n`
2)
```
    {{- with .Values.keycloak.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.keycloak.image.pullSecrets }}
      - name: {{ . }}
      {{- end }}
    {{- end }}
```
`can't evaluate field Values in type []interface {}`  

Works if set to this:
```
    {{- with .Values.keycloak.image.pullSecrets }}
      imagePullSecrets:
    {{- range $.Values.keycloak.image.pullSecrets }}
      - name: {{ . }}
    {{- end }}
    {{- end }}
```
But I'm actually missing the point of keeping `with`, it makes things a bit more complicated.

2018-12-07 17:47 UTC, unguiculus commented on stable/keycloak/templates/statefulset.yaml
> +    {{- if .Values.keycloak.image.pullSecrets }}
From the top of my head, this should work:

```yaml
{{- with .Values.keycloak.image.pullSecrets }}
  imagePullSecrets:
  {{- range . }}
    - name: {{ . }}
  {{- end }}
{{- end }}
```

2018-12-07 17:49 UTC, Dean-Coakley commented
@alivespirit If you set 
```
pullSecrets: []
      # - name: myRegistrKeySecretName
```

Then I think you could do:
```
{{- with .Values.keycloak.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
```

What do you think?

2018-12-07 17:54 UTC, alivespirit commented on stable/keycloak/templates/statefulset.yaml
> +    {{- if .Values.keycloak.image.pullSecrets }}
You're right, that works, pushing an update.

2018-12-07 18:07 UTC, alivespirit commented
@Dean-Coakley yes, I can do that, but as I mentioned above - than we'll have inconsistency if we would want to use pull secrets for both keycloak and dependent postgresql.

2018-12-07 18:14 UTC, alivespirit commented on stable/keycloak/values.yaml
> +    # pullSecrets:
Pushed an update.

2018-12-07 18:23 UTC, Dean-Coakley approved these changes
I agree. Looks good now.

2018-12-13 08:43 UTC, unguiculus approved these changes

2018-12-13 08:44 UTC, unguiculus commented
/ok-to-test

2018-12-13 09:14 UTC, unguiculus commented
/lgtm

2018-12-13 09:26 UTC, merged