Updating Metabase to 0.31.2
helm/charts pull request #9837
Opened 2018-12-09 21:54 UTC by jevy

@pmint93

#### What this PR does / why we need it: Updating to latest Metabase

#### Special notes for your reviewer: Tested locally. Seems to work!

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2018-12-10 23:38 UTC, davidkarlsen requested changes

2018-12-10 23:38 UTC, davidkarlsen commented on stable/metabase/Chart.yaml
> +appVersion: v0.31.2
please update readme too

2018-12-10 23:38 UTC, davidkarlsen commented
/ok-to-test

2018-12-12 00:52 UTC, jevy commented
@davidkarlsen Should be good.

2019-01-15 14:10 UTC, materemias commented
I think @davidkarlsen 's requests were fulfilled. is there anything left to do?

2019-01-29 19:44 UTC, closed without merging