Update Minio image to latest release and add upgrade strategies
helm/charts pull request #9852
Opened 2018-12-10 13:33 UTC by nitisht

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://www.helm.sh/blog/helm-dco/index.html) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2018-12-10 13:34 UTC, nitisht commented
cc @wlan0

2018-12-10 13:52 UTC, cpanato commented on stable/minio/Chart.yaml
> +version: 2.1.1
I suggest this to be `2.2.0` at least since this is not bug fixing and have some new features and maybe some breaking upgrade.

2018-12-10 13:57 UTC, cpanato commented
I was able to upgrade minio to use this version when using the `distributed`.
when using the `standalone` mode the old replica was still running and the new replica did update.
I scale down manually the old replica

2018-12-10 13:58 UTC, cpanato requested changes
see my comments

2018-12-11 04:25 UTC, wlan0 commented on stable/minio/templates/deployment.yaml
> -apiVersion: apps/v1beta2
I would suggest that we keep the version at `apps/v1beta2`, since we don't lose any functionality, while simultaneously supporting older versions of Kubernetes. 

StatefulSets graduated to v1 in k8s version 1.9. I think we should wait until k8s-1.14 before graduating our helm charts to v1.

latest release is 1.13.

2018-12-11 05:13 UTC, nitisht commented on stable/minio/templates/deployment.yaml
> -apiVersion: apps/v1beta2
done

2018-12-11 17:42 UTC, cpanato commented
@nitisht there is a conflict can you rebase and fix? thanks

2018-12-12 03:13 UTC, nitisht commented
ping @wlan0

2018-12-12 05:49 UTC, wlan0 commented
@nitisht Thanks for the updates! 

LGTM

/lgtm

2018-12-12 05:55 UTC, merged

2018-12-12 06:10 UTC, sanverm2 reviewed
For 
```
DeploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%
```
settings, while upgrading the standalone pod ( with persistence, enabled)  the pod for old version will keep running and pod corresponding to new version will keep waiting to get volume mounted by old version. 

```
  Warning  FailedMount  4s (x8 over 1m)  kubelet, 10.41.14.45  MountVolume.SetUp failed for volume
 "pvc-9ae836c8-fdd2-11e8-9d67-00000a290c67" : mount command failed, status: Failure, reason:
 Rook: Mount volume failed: failed to attach volume pvc-9ae836c8-fdd2-11e8-9d67-00000a290c67
 for pod default/minio-ibm-minio-objectstore-5669d6c9f7-6vhpn. Volume is already attached by pod
 default/minio-ibm-minio-objectstore-759744fb5b-nmvgx. Status Running

```

So, for standalone case(replica 1), we can change  default values for ```maxUnavailable: 0``` to ```  maxUnavailable:  1``` .