redis: optional prometheus metrics exporter
helm/charts pull request #991
Opened 2017-05-03 10:40 UTC by lwolf

This PR adds the option to run a side-car Prometheus metrics exporter for redis. It requires no additional configuration and can be enabled be setting metrics.enabled=true

2017-05-04 03:15 UTC, seanknox commented
@k8s-bot ok to test

2017-05-23 17:06 UTC, unguiculus requested changes

2017-05-23 17:06 UTC, unguiculus commented on stable/redis/templates/svc.yaml
> +{{- if .Values.metrics.enabled }}
I'm not sure if we should always add these annotations when metrics are enabled. Maybe this should be configurable. You don't need these annotations if you use the Prometheus Operator.

@mgoodness What do you think?

2017-05-23 17:06 UTC, unguiculus commented on stable/redis/values.yaml
> +    requests:
Don't specify defaults for resources.

2017-05-23 17:06 UTC, unguiculus commented on stable/redis/Chart.yaml
> +version: 0.5.2
I would make this a `0.6.0`.

2017-05-25 16:35 UTC, mgoodness requested changes

2017-05-25 16:35 UTC, mgoodness commented on stable/redis/templates/svc.yaml
> +{{- if .Values.metrics.enabled }}
I'm very much inclined to agree. How about something like:
```
{{- if .Values.metrics.enabled }}
  annotations:
{{ toYaml .Values.metrics.annotations | indent X }}
{{- end }}
```

2017-05-25 16:35 UTC, mgoodness commented on stable/redis/templates/deployment.yaml
> +        imagePullPolicy: {{ default "" .Values.metrics.imagePullPolicy | quote }}
Avoid using the `default` function if you can - it makes it harder for end-users to determine what the value will be. In this case, set `metrics.imagePullPolicy` explicitly in `values.yaml`.

2017-05-28 08:47 UTC, lwolf commented
updated pull request with all changes.

2017-05-28 15:50 UTC, unguiculus approved these changes

2017-05-30 16:31 UTC, mgoodness approved these changes

2017-05-30 16:32 UTC, mgoodness commented
@unguiculus

2017-05-30 16:46 UTC, merged