allow option to manage alertmanager config externally
helm/charts pull request #9979
Opened 2018-12-13 16:20 UTC by shamsalmon

What this PR does / why we need it:
My company needed to be able to managed alertmanager externally in a repo external to our helm configurations so that engineers inexperienced with helm could make changes more easily. I thought others could use the same ability. 

Which issue this PR fixes
Special notes for your reviewer:
Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

  DCO signed
  Chart Version bumped
  Variables are documented in the README.md

2018-12-15 08:36 UTC, gianrubio approved these changes
/ok-to-test
/lgtm

2018-12-22 13:35 UTC, miracle2k commented
I am curious why the operator chart installs promtheus, alertmanager etc. in the first place. Isn't the whole idea that I can control those via kubernetes resources managed by the operator itself?

2018-12-26 15:16 UTC, shamsalmon commented
@miracle2k the chart does not install prometheus or alertmanager only the operator does.

2019-01-31 12:56 UTC, paskal requested changes

2019-01-31 12:56 UTC, paskal commented on stable/prometheus-operator/templates/alertmanager/secret.yaml
> +{{- if and (.Values.alertmanager.enabled) (eq .Values.alertmanager.alertmanagerConfigExternal false) }}
I don't think it's a good option. Maybe it's better to change to something like "alertmanager.alertmanagerSpec.defaultConfig" so you won't need to check something for being false?

2019-02-14 13:43 UTC, closed without merging